Repository joomla/joomla-cms, pull requests merged in 2018-02, with the labels that each got.

#19528 [4.0] Deprecate Pathway::getInstance
  libraries/src/Application/CMSApplication.php
  libraries/src/Factory.php
  libraries/src/Pathway/Pathway.php
  libraries/src/Pathway/SitePathway.php
  libraries/src/Service/Provider/Pathway.php
Labels: PR-4.0-dev

#19638 [4.0] Setup eslint for es6
  .eslintignore
  .eslintrc
  build/build.php
  package.json
Labels: PR-4.0-dev

#19649 Typo Joomla is vegetarian
  administrator/components/com_admin/postinstall/joomla40checks.php
Labels: PR-staging

#19654 Plain English cont.
  administrator/language/en-GB/en-GB.plg_editors-xtd_article.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_article.sys.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_contact.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_contact.sys.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_fields.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_fields.sys.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_image.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_image.sys.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_menu.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_menu.sys.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_module.ini
  administrator/language/en-GB/en-GB.plg_editors-xtd_module.sys.ini
Labels: RTC

#19199 Fix PHP Warning for Session on PHP 7.2
  libraries/src/Session/Session.php
Labels: PR-staging, RTC

#19233 Remove PHP warning when logging out while editing the article on php >= 7.1
  libraries/legacy/error/error.php
Labels: RTC

#19238 Improve code for setting category view layout
  libraries/src/MVC/View/CategoryView.php
Labels: RTC

#19271 [Modern Routing] make a simpler loop in StandardRules::build
  libraries/src/Component/Router/Rules/StandardRules.php
Labels: RTC

#19284 Improve performance of the com_content category view with filter by tags
  components/com_content/models/articles.php
Labels: PR-staging, RTC

#19551 Multilingual: Associated categories should display only when published
  administrator/components/com_categories/helpers/categories.php
Labels: PR-staging, RTC

#19610 [CS] Array list style
  administrator/components/com_menus/controllers/item.php
Labels: RTC

#19632 Prevent compounding inputmode attribute
  layouts/joomla/form/field/text.php
Labels: RTC

#19633 Fix user profile plugin
  plugins/user/profile/profile.php
Labels: PR-staging, RTC

#19653 Update pagebreak plugin description
  administrator/language/en-GB/en-GB.plg_content_pagebreak.ini
  administrator/language/en-GB/en-GB.plg_content_pagebreak.sys.ini
Labels: RTC

#19668 [4.0] CS for pathway
  libraries/src/Application/CMSApplication.php
  libraries/src/Pathway/Pathway.php
  libraries/src/Pathway/SitePathway.php
Labels: PR-4.0-dev

#19658 [4.0] Config service provider
  libraries/src/Application/Autoconfigurable.php
  libraries/src/Application/CliApplication.php
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Application/WebApplication.php
  libraries/src/Factory.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Config.php
  libraries/src/Service/Provider/Database.php
  libraries/src/Service/Provider/Session.php
Labels: PR-4.0-dev

#19675 Typo
  administrator/language/en-GB/en-GB.plg_editors_tinymce.ini
Labels: Language Change, PR-staging

#19548 Implement Session GC Cli
  cli/sessionGc.php
  libraries/src/Session/Session.php
Labels: PR-staging

#19689 [4.0] Use the config from the container in installation app
  installation/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Config.php
Labels: RTC

#19646 [4.0][Installer] Fix DB selection.
  installation/forms/setup.xml
  installation/src/Model/DatabaseModel.php
Labels: PR-4.0-dev

#19700 Add deprecate log message for the pathway name attribute
  libraries/src/Application/CMSApplication.php
Labels: PR-staging

#19706 [4.0] Remove obsolete configuration tests in applications
  tests/unit/suites/libraries/joomla/application/JApplicationCliTest.php
  tests/unit/suites/libraries/joomla/application/JApplicationWebTest.php
Labels: PR-4.0-dev, Unit/System Tests

#19703 [4.0] Remove pathway name attribute
  libraries/src/Application/CMSApplication.php
  libraries/src/Service/Provider/Pathway.php
  tests/unit/suites/libraries/cms/application/JApplicationCmsTest.php
  tests/unit/suites/libraries/cms/application/JApplicationSiteTest.php
Labels: PR-4.0-dev, Unit/System Tests

#19691 typo
  libraries/joomla/mediawiki/links.php
  media/system/js/calendar-setup-uncompressed.js
  tests/unit/suites/libraries/joomla/crypt/JCryptTest.php
Labels: PR-staging, RTC

#19688 Possible misprint in plugins/sampledata/blog/blog.php
  plugins/sampledata/blog/blog.php
Labels: RTC

#19709 Add the missing import in the application
  libraries/src/Application/CMSApplication.php
Labels: PR-staging

#19655 [4.0] Adapt doc blocks of some service providers
  libraries/src/Service/Provider/Document.php
  libraries/src/Service/Provider/Pathway.php
Labels: PR-4.0-dev

#18901 [4.0] Deprecate Document::getInstance
  administrator/components/com_finder/Controller/IndexerController.php
  installation/src/Application/InstallationApplication.php
  libraries/src/Document/Document.php
  libraries/src/Error/AbstractRenderer.php
  libraries/src/Factory.php
Labels: PR-4.0-dev

#19704 [4.0] Use identical operators for modules
  administrator/modules/mod_menu/Menu/CssMenu.php
  administrator/modules/mod_menu/tmpl/default.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/modules/mod_quickicon/Helper/QuickIconHelper.php
  modules/mod_articles_category/Helper/ArticlesCategoryHelper.php
  modules/mod_languages/Helper/LanguagesHelper.php
  modules/mod_random_image/Helper/RandomImageHelper.php
Labels: RTC

#19702 [4.0] Build.js support file watch
  .gitignore
  build.js
  build/build-modules-js/compilejs.js
  build/build-modules-js/compilescss.js
  package.json
Labels: PR-4.0-dev

#19721 Add note docblocks to 3.9 about a behavior change in escape() methods in 4.0
  libraries/joomla/view/html.php
  libraries/src/Layout/BaseLayout.php
  libraries/src/MVC/View/HtmlView.php
Labels: PR-3.9-dev

#19720 [4.0] Switch escape() methods to ENT_QUOTES to also cover single quotes
  libraries/joomla/view/html.php
  libraries/src/Layout/BaseLayout.php
  libraries/src/MVC/View/HtmlView.php
Labels: PR-4.0-dev

#19701 [4.0] Use identical operators for layouts
  layouts/joomla/form/field/calendar.php
  layouts/joomla/form/field/color/simple.php
  layouts/joomla/form/field/email.php
  layouts/joomla/form/field/number.php
  layouts/joomla/form/field/radio.php
  layouts/joomla/form/field/radiobasic.php
  layouts/joomla/form/field/tel.php
  layouts/joomla/form/field/textarea.php
  layouts/joomla/searchtools/default.php
  layouts/joomla/searchtools/grid/sort.php
Labels: PR-4.0-dev

#19650 [4.0] Feature/compile es6
  .babelrc
  .eslintignore
  .eslintrc
  build/build-modules-js/compile-es6.js
  package.json
Labels: PR-4.0-dev

#19775 fix 404 on github dokukmentation links
  libraries/joomla/github/package/users.php
  libraries/joomla/github/package/users/emails.php
  libraries/joomla/github/package/users/followers.php
  libraries/joomla/github/package/users/keys.php
Labels: RTC

#19778 [4.0] Upgrade IDNA Convert library, migrate to Composer dependency
  .gitignore
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-02-24.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-02-24.sql
  administrator/manifests/libraries/idna_convert.xml
  build/bump.php
  build/phpcs/Joomla/ruleset.xml
  composer.json
  composer.lock
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  language/en-GB/en-GB.lib_idna_convert.sys.ini
  libraries/idna_convert/ReadMe.txt
  libraries/idna_convert/idna_convert.class.php
  libraries/idna_convert/transcode_wrapper.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/String/PunycodeHelper.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/mso/idna-convert/LICENSE
  libraries/vendor/mso/idna-convert/src/EncodingHelper.php
  libraries/vendor/mso/idna-convert/src/IdnaConvert.php
  libraries/vendor/mso/idna-convert/src/NamePrepData.php
  libraries/vendor/mso/idna-convert/src/NamePrepData2003.php
  libraries/vendor/mso/idna-convert/src/NamePrepDataInterface.php
  libraries/vendor/mso/idna-convert/src/Punycode.php
  libraries/vendor/mso/idna-convert/src/PunycodeInterface.php
  libraries/vendor/mso/idna-convert/src/UnicodeTranscoder.php
  libraries/vendor/mso/idna-convert/src/UnicodeTranscoderInterface.php
Labels: Composer Dependency Changed, Language Change, PR-4.0-dev

#19766 [4.0] Ensure the CMSApplications do always have an identity
  components/com_config/dispatcher.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/WebApplication.php
Labels: PR-4.0-dev

#19664 Articles - Latest
  administrator/language/en-GB/en-GB.mod_latest.ini
  administrator/language/en-GB/en-GB.mod_latest.sys.ini
  language/en-GB/en-GB.mod_articles_latest.ini
  language/en-GB/en-GB.mod_articles_latest.sys.ini
Labels: Language Change, PR-staging

#19737 [4.0]Update administrator/modules/mod_feed/mod_feed.xml
  administrator/modules/mod_feed/mod_feed.xml
Labels: PR-4.0-dev

#19648 reCAPTCHA V1 stops on March 31
  administrator/components/com_admin/sql/updates/mysql/3.8.6-2018-02-14.sql
  administrator/components/com_admin/sql/updates/postgresql/3.8.6-2018-02-14.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.8.6-2018-02-14.sql
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha.ini
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
  plugins/captcha/recaptcha/postinstall/actions.php
Labels: Language Change, PR-staging, RTC

#19764 System Information
  administrator/components/com_admin/models/sysinfo.php
  administrator/components/com_admin/views/sysinfo/tmpl/default_system.php
  administrator/language/en-GB/en-GB.com_admin.ini
Labels: Language Change, PR-staging, RTC

#19740 Overrides do not find 3rd party plugins language files when files are in the plugin language folder
  administrator/components/com_languages/models/strings.php
Labels: PR-staging, RTC

#19734 Com_redirect: Differentiating utf8 old_url
  administrator/components/com_redirect/tables/link.php
Labels: PR-staging, RTC

#19731 TinyMCE: uglify the inline XTD-btns script
  plugins/editors/tinymce/tinymce.php
Labels: PR-staging, RTC

#19715 Update bootstrap-rtl.css
  media/jui/css/bootstrap-rtl.css
  media/jui/less/bootstrap-rtl.less
Labels: PR-staging, RTC

#19697 Hide global configuration and system information from non super users
  administrator/modules/mod_menu/menu.php
Labels: PR-staging, RTC

#19686 [a11y] Cache toolbar
  administrator/components/com_cache/views/cache/view.html.php
Labels: RTC

#19685 Wrong desc fixed. Changed title to document!
  libraries/src/Document/Document.php
Labels: PR-staging, RTC

#19656 Move custom buttons to the other buttons in TinyMCE
  plugins/editors/tinymce/tinymce.php
Labels: PR-staging, RTC

#19645 Proxy to a higher error handler if there is one available
  plugins/system/redirect/redirect.php
Labels: PR-staging, RTC

#19611 Correct output_buffering check in 3.8.x
  administrator/components/com_admin/models/sysinfo.php
  installation/model/setup.php
Labels: PR-staging, RTC

#19608 Pass the configuration tmp_path to the archive package for extension installations
  libraries/src/Installer/InstallerHelper.php
Labels: PR-staging, RTC

#19591 Improve header handling in PageController cache
  libraries/src/Cache/Controller/PageController.php
Labels: RTC

#19647 Defining typeAlias in AdminModel
  libraries/src/MVC/Model/AdminModel.php
Labels: RTC

#19582 Fix JRoute('&var=...') not adding current URL variables when current URL is the home page
  libraries/src/Router/SiteRouter.php
  tests/unit/suites/libraries/cms/router/JRouterSiteTest.php
Labels: PR-staging, RTC, Unit/System Tests

#17923 [TemplateAdapter.php] Rewrote hardcoded SQL to query object
  libraries/src/Installer/Adapter/TemplateAdapter.php
Labels: PR-staging, RTC

#17689 Tagged items: add microdata
  components/com_tags/views/tag/tmpl/default_items.php
Labels: PR-staging, RTC

#17351 [Schema checker] (Database FIX) Add support for checking NULL and DEFAULT column attributes
  administrator/language/en-GB/en-GB.com_installer.ini
  libraries/src/Schema/ChangeItem/MysqlChangeItem.php
Labels: Language Change, PR-staging, RTC

#19687 The One Right Session Management Configuration For Joomla! 3
  administrator/components/com_admin/sql/updates/mysql/3.8.6-2018-02-14.sql
  administrator/components/com_admin/sql/updates/postgresql/3.8.6-2018-02-14.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.8.6-2018-02-14.sql
  administrator/language/en-GB/en-GB.plg_system_sessiongc.ini
  administrator/language/en-GB/en-GB.plg_system_sessiongc.sys.ini
  cli/sessionMetadataGc.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
  libraries/src/Application/CMSApplication.php
  libraries/src/Session/MetadataManager.php
  plugins/system/sessiongc/sessiongc.php
  plugins/system/sessiongc/sessiongc.xml
Labels: Language Change, PR-staging, RTC

#19796 Fix mssql installation
  installation/sql/sqlazure/joomla.sql
Labels: RTC
