Repository joomla/joomla-cms, pull requests merged in 2018-11, with the labels that each got.

#22877 Fix PHP 5.3 error in JHtmlContent
  libraries/cms/html/content.php
Labels: RTC

#22663 Add the default.xml file to useractions default view
  administrator/components/com_actionlogs/views/actionlogs/tmpl/default.xml
  administrator/language/en-GB/en-GB.com_actionlogs.sys.ini
Labels: Language Change, PR-staging, RTC

#22453 Removed redundant 'flash uploader' CSS
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/less/blocks/_custom.less
  media/media/css/mediamanager.css
  media/media/css/mediamanager_rtl.css
  media/media/css/popup-imagemanager.css
  media/media/css/popup-imagemanager_rtl.css
Labels: PR-staging, RTC

#22368 Add more search engine bots to robots list
  libraries/src/Environment/Browser.php
Labels: PR-staging, RTC

#22117 [Performance] Category manager / Tag Manager, get all counters via single query, reduce 20, 50, 100 queries (page limit) to 1
  administrator/components/com_banners/helpers/banners.php
  administrator/components/com_contact/helpers/contact.php
  administrator/components/com_content/helpers/content.php
  administrator/components/com_fields/helpers/fields.php
  administrator/components/com_newsfeeds/helpers/newsfeeds.php
  libraries/src/Helper/ContentHelper.php
Labels: PR-staging, RTC

#22897 Fix typos
  libraries/src/Log/Logger/FormattedtextLogger.php
Labels: PR-staging

#22879 Update TinyMCE to 4.5.9
  media/editors/tinymce/changelog.txt
  media/editors/tinymce/tinymce.min.js
  plugins/editors/tinymce/tinymce.xml
Labels: RTC

#22862 [4.0] Inject the application in the breadcrumbs helper
  modules/mod_breadcrumbs/Helper/BreadcrumbsHelper.php
  modules/mod_breadcrumbs/mod_breadcrumbs.php
Labels: PR-4.0-dev

#22863 [4.0] Inject the application in the fields plugins
  administrator/components/com_fields/Plugin/FieldsPlugin.php
  plugins/fields/sql/sql.php
  plugins/fields/user/user.php
Labels: PR-4.0-dev

#22903 [4.0]Remove switcher from admin menu edit
  administrator/components/com_menus/Model/MenuModel.php
  administrator/components/com_menus/forms/menu.xml
  administrator/components/com_menus/tmpl/menu/edit.php
  administrator/language/en-GB/en-GB.com_menus.ini
Labels: Language Change, PR-4.0-dev

#22894 Add an event to trigger when you execute a workflow transition
  libraries/src/Workflow/Workflow.php
Labels: PR-4.0-dev

#22852 [4.0] Fix broken preset menu import
  administrator/components/com_menus/Helper/MenusHelper.php
  administrator/components/com_menus/presets/joomla.xml
  administrator/components/com_menus/presets/modern.xml
  libraries/src/Table/Nested.php
Labels: PR-4.0-dev, RTC

#22917 [4.0] Use the correct params object in the redirect plugin
  plugins/system/redirect/redirect.php
Labels: PR-4.0-dev

#22929 [4.0][com_menus] Saving new menu type fails
  administrator/components/com_menus/Model/MenuModel.php
  administrator/components/com_menus/tmpl/menu/edit.php
Labels: RTC

#22918 [4.0] Fix CSP reporting
  administrator/components/com_csp/Table/ReportTable.php
  components/com_csp/Controller/ReportController.php
Labels: PR-4.0-dev

#22913 [4.0] Load the document properly in the exception handler
  libraries/src/Exception/ExceptionHandler.php
  templates/cassiopeia/error.php
Labels: PR-4.0-dev

#22937 [4.0] Fix blog sampledata plugin
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev

#22927 [com_privacy] Redirect to request form after login
  components/com_privacy/controller.php
Labels: RTC

#22925 [3.9.1] Automatic title at Latest Actions Backend Module
  administrator/language/en-GB/en-GB.mod_latestactions.ini
  administrator/modules/mod_latestactions/helper.php
  administrator/modules/mod_latestactions/mod_latestactions.php
Labels: Language Change, PR-staging, RTC

#22904 [3.9.0] plg_content_contact. Respect default values
  plugins/content/contact/contact.php
  plugins/content/contact/contact.xml
Labels: PR-staging, RTC

#22851 [Batch] Change State: pass only affected items to table and event
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-staging, RTC

#22847 [3.9][plg_user_terms] Add namespaces
  plugins/user/terms/field/terms.php
  plugins/user/terms/terms.php
Labels: PR-staging, RTC

#22757 Fix incorrect row count on nested subforms
  media/system/js/subform-repeatable-uncompressed.js
  media/system/js/subform-repeatable.js
Labels: PR-staging, RTC

#19684 make core_params Registry object
  components/com_tags/views/tag/view.html.php
Labels: PR-staging, RTC

#22916 [4.0] Access the arguments directly from the array to prevent an infinite loop
  libraries/src/Event/AfterExtensionBootEvent.php
  libraries/src/Event/BeforeExecuteEvent.php
  libraries/src/Event/BeforeExtensionBootEvent.php
  libraries/src/Event/ErrorEvent.php
Labels: PR-4.0-dev

#22864 [4.0] Fix the imports of stylesheets and scripts
  administrator/components/com_associations/Field/Modal/AssociationField.php
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_menus/tmpl/items/modal.php
  components/com_contact/Controller/DisplayController.php
  components/com_menus/Controller/DisplayController.php
  libraries/cms/html/formbehavior.php
  libraries/cms/html/sortablelist.php
Labels: PR-4.0-dev

#22953 Add column alias
  libraries/src/Table/Extension.php
Labels: PR-staging

#22947 [4.0] Update jgrid.php to use correct arguments
  libraries/cms/html/jgrid.php
Labels: PR-4.0-dev

#22957 [4.0] Adding links to Modules in the System Panel
  administrator/components/com_cpanel/View/System/HtmlView.php
Labels: PR-4.0-dev, RTC

#22981 [4.0] correct css class for backgrounds
  build/media_src/system/js/core.es6.js
Labels: PR-4.0-dev

#23019 s/occuring/occurring
  administrator/components/com_joomlaupdate/restore_finalisation.php
Labels: PR-4.0-dev

#22939 [plg_system_privacyconsent] Don't redirect on menu logout
  plugins/system/privacyconsent/privacyconsent.php
Labels: RTC

#22948 search filter in getListQuery in ActionlogsModelActionlogs uses the wrong substring when searching by item_id:
  administrator/components/com_actionlogs/models/actionlogs.php
Labels: RTC

#23030 s/postions/positions
  plugins/content/pagenavigation/pagenavigation.php
Labels: RTC

#23026 [4.0] getReorderConditions() cleanup
  administrator/components/com_banners/Model/BannerModel.php
  administrator/components/com_categories/Model/CategoryModel.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_content/Model/FeatureModel.php
  administrator/components/com_fields/Model/FieldModel.php
  administrator/components/com_fields/Model/GroupModel.php
  administrator/components/com_menus/Model/ItemModel.php
  administrator/components/com_modules/Model/ModuleModel.php
  administrator/components/com_newsfeeds/Model/NewsfeedModel.php
  administrator/components/com_plugins/Model/PluginModel.php
  administrator/components/com_workflow/Model/StagesModel.php
  administrator/components/com_workflow/Model/TransitionsModel.php
  administrator/components/com_workflow/Model/WorkflowModel.php
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-4.0-dev, RTC

#23035 [4.0] Remove obsolete template color handling from Cassiopeia offline.php
  templates/cassiopeia/offline.php
Labels: RTC

#23005 s/equivilents/equivalents & remove trailing periods from comments
  libraries/bootstrap.php
  libraries/cms.php
Labels: PR-4.0-dev, RTC

#22991 [4.0] Cleanup - Remove commented out code.
  administrator/components/com_templates/Controller/DisplayController.php
Labels: PR-4.0-dev

#22996 [4.0] Install error pages typo and targe/rel on link to a user editable wikipage
  build/warning_page/template.html
  templates/system/build_incomplete.html
  templates/system/incompatible.html
Labels: PR-4.0-dev, RTC

#23004 s/emtpy/empty
  administrator/components/com_banners/Model/ClientsModel.php
  administrator/components/com_menus/Model/MenusModel.php
Labels: RTC

#22998 s/overriden/overridden
  administrator/components/com_media/src/Model/ApiModel.php
  administrator/components/com_newsfeeds/Table/NewsfeedTable.php
  administrator/components/com_redirect/Table/LinkTable.php
  administrator/components/com_tags/Table/TagTable.php
  administrator/language/en-GB/en-GB.com_templates.ini
  build/media_src/system/js/core.es6.js
  components/com_contact/View/Category/FeedView.php
  components/com_content/Model/ArticlesModel.php
  components/com_content/View/Category/FeedView.php
  libraries/src/Layout/FileLayout.php
  libraries/src/MVC/View/CategoryFeedView.php
Labels: Language Change, PR-4.0-dev, RTC

#23010 s/tranistions/transitions & s/performecd/performecd
  libraries/src/Workflow/WorkflowServiceInterface.php
Labels: RTC

#23011 s/interogate/interrogate
  administrator/components/com_admin/Model/ProfileModel.php
  administrator/components/com_templates/Model/StyleModel.php
  administrator/components/com_users/Model/GroupModel.php
  administrator/components/com_users/Model/LevelModel.php
  administrator/components/com_users/Model/MailModel.php
  administrator/components/com_users/Model/UserModel.php
  components/com_config/Model/TemplatesModel.php
  components/com_users/Model/LoginModel.php
  components/com_users/Model/ProfileModel.php
  components/com_users/Model/RegistrationModel.php
  components/com_users/Model/RemindModel.php
  components/com_users/Model/ResetModel.php
Labels: RTC

#23006 s/cummulative/cumulative/
  administrator/components/com_finder/helpers/indexer/indexer.php
  libraries/src/Component/ComponentHelper.php
  plugins/editors/tinymce/tinymce.php
Labels: RTC

#23000 s/Nmber/Number
  libraries/src/Categories/CategoryNode.php
Labels: RTC

#23002 s/udpating/updating
  libraries/src/Schema/ChangeItem.php
Labels: PR-4.0-dev, RTC

#23003 s/seprated/separated
  libraries/src/Form/Field/CheckboxesField.php
Labels: RTC

#23012 s/presset/preset
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
Labels: RTC

#23013 s/informati/information & s/tha/that
  administrator/components/com_admin/Model/SysinfoModel.php
Labels: RTC

#23014 s/resuls/results
  administrator/components/com_languages/Model/StringsModel.php
Labels: RTC

#23015 s/belons/belongs
  administrator/components/com_workflow/Controller/StageController.php
Labels: RTC

#23016 s/protocals/protocols
  plugins/system/sef/sef.php
Labels: RTC

#23017 s/seach/search
  administrator/components/com_search/Model/SearchesModel.php
Labels: RTC

#23018 s/informations/information
  libraries/src/Component/Router/Rules/RulesInterface.php
Labels: RTC

#23009 s/postion/position
  build/phpcs/Joomla/Sniffs/ControlStructures/ControlSignatureSniff.php
Labels: RTC

#22999 s/newfeed/newsfeed
  components/com_content/Model/CategoryModel.php
  components/com_newsfeeds/Model/CategoryModel.php
Labels: RTC

#23007 s/buton/button
  plugins/editors-xtd/article/article.php
  plugins/editors-xtd/contact/contact.php
  plugins/editors-xtd/image/image.php
  plugins/editors-xtd/menu/menu.php
  plugins/editors-xtd/pagebreak/pagebreak.php
  templates/system/offline.php
Labels: RTC

#22806 Inject the active user into JAdminCssMenu
  administrator/modules/mod_menu/menu.php
  administrator/modules/mod_menu/mod_menu.php
Labels: RTC

#23048 [4.0] Return parent method values
  administrator/components/com_modules/Controller/ModuleController.php
  administrator/components/com_templates/Controller/StyleController.php
  administrator/components/com_workflow/Controller/WorkflowController.php
Labels: PR-4.0-dev, RTC

#23049 remove duplicated meaning comment
  components/com_contact/controllers/contact.php
Labels: RTC

#23052 Fix for #22935 "cannot delete module position for module"
  media/system/js/moduleorder.js
Labels: RTC

#23044 [3.9] Remove factually incorrect sentence
  administrator/language/en-GB/en-GB.plg_privacy_actionlogs.ini
  administrator/language/en-GB/en-GB.plg_privacy_actionlogs.sys.ini
Labels: Language Change, PR-staging, RTC

#22993 Fix extension installation in PostgreSQL
  libraries/src/Installer/InstallerAdapter.php
Labels: RTC

#22187 [3.9] Add php extension & Forbidden head to sql log files
  plugins/system/debug/debug.php
Labels: PR-staging, RTC

#15843 Allow Joomla to be extended with JDEBUG defined by developers
  includes/framework.php
  libraries/cms.php
Labels: PR-staging, RTC

#22985 Fix JS alerts for Joomla/Extension update check
  build/media_src/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_src/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_src/system/js/core.es6.js
  plugins/quickicon/extensionupdate/extensionupdate.php
  plugins/quickicon/joomlaupdate/joomlaupdate.php
Labels: PR-4.0-dev

#23008 [4.0] s/succesfully/successfully
  plugins/system/languagefilter/languagefilter.php
  plugins/user/contactcreator/contactcreator.php
  plugins/user/profile/profile.php
Labels: PR-4.0-dev, RTC

#22926 [3.9] Move confirm consent to use the bs modal vs mootools
  plugins/content/confirmconsent/confirmconsent.php
Labels: PR-staging, RTC

#23066 Improves the getFilenameFromUrl method
  libraries/src/Installer/InstallerHelper.php
Labels: PR-staging

#23065 Fixes issue with install via url failing when header keys are lowercase
  libraries/src/Installer/InstallerHelper.php
Labels: PR-staging

#23027 [4.0][com_workflows] Remove unused function
  administrator/components/com_workflow/Model/WorkflowsModel.php
Labels: PR-4.0-dev, RTC

#23094 [4.0][Testing] Updating drone.yml to always update JoomlaBrowser
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#23084 [actionlogs] Remove limitations on the logDeletePeriod
  plugins/system/actionlogs/actionlogs.xml
Labels: RTC

#22995 s/complient/compliant
  modules/mod_breadcrumbs/helper.php
Labels: PR-staging, RTC

#22976 Actionlogs for installation of package doesn't pick up correct translation
  administrator/components/com_actionlogs/helpers/actionlogs.php
Labels: RTC

#22912 Adds keyup trigger on showon elements
  media/jui/js/cms-uncompressed.js
  media/jui/js/cms.js
Labels: RTC

#21949 Fix Configuration change has no effect #21943
  administrator/components/com_config/model/application.php
Labels: PR-staging, RTC

#20322 Enable Profiling tab for mysql (PDO) queries and disable cache in debug mode
  libraries/joomla/database/driver/mysql.php
  libraries/joomla/database/driver/mysqli.php
  libraries/joomla/database/driver/pdomysql.php
Labels: RTC

#23025 Force file type in Crowdin for new files.
  crowdin.yml
Labels: PR-staging

#23092 [4.0] Fix the batch layout identifiers
  administrator/components/com_categories/tmpl/categories/default_batch_body.php
  administrator/components/com_content/tmpl/articles/default_batch_body.php
Labels: PR-4.0-dev

#23113 [4.0] Fix undefined Awesomplete
  components/com_finder/tmpl/search/default.php
  components/com_finder/tmpl/search/default_form.php
  modules/mod_finder/tmpl/default.php
Labels: PR-4.0-dev

#23125 [4.0] Check if rules are available in rules field rule
  libraries/src/Form/Rule/RulesRule.php
Labels: PR-4.0-dev, RTC

#23047 [4.0] System Panel: Add badges to items when necessary
  administrator/components/com_cpanel/View/System/HtmlView.php
  administrator/components/com_cpanel/tmpl/system/default.php
  administrator/help/helpsites.xml
Labels: PR-4.0-dev, RTC

#23085 [4.0] Fix retrieval of guest user group
  libraries/src/Access/Access.php
Labels: PR-4.0-dev

#23124 [com_content] Deprecate column-related code
  components/com_content/helpers/query.php
  components/com_content/views/category/view.html.php
  components/com_content/views/featured/view.html.php
Labels: RTC

#23104 Update IFW to work with CE, remove JSONP requirement
  build/media_src/plg_installer_webinstaller/js/client.es6.js
Labels: PR-4.0-dev

#22870 Add ability to switch off the animation of showons
  libraries/src/Form/FormField.php
  media/jui/js/cms-uncompressed.js
  media/jui/js/cms.js
Labels: PR-staging, RTC

#23145 Custom elements update
  package-lock.json
  package.json
Labels: PR-4.0-dev

#23140 [4.0] RTL: Correcting Joomla Update version display in System CPanel badge and Joomla Update component
  administrator/components/com_cpanel/tmpl/system/default.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_reinstall.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_upload.php
  administrator/templates/atum/scss/font-awesome.scss
  build/media/com_joomlaupdate/js/default.js
Labels: PR-4.0-dev

#23097 [4.0] Add missing eye icons to installer css
  installation/template/scss/template.scss
Labels: PR-4.0-dev, RTC

#23153 Confirm Consent Plugin Rendering Issues
  plugins/content/confirmconsent/confirmconsent.php
  plugins/content/confirmconsent/fields/consentbox.php
Labels: PR-staging

#23136 [mssql] update sql fix
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-05.sql
Labels: PR-staging

#23095 [4.0] RFC Quickicons Joomla and Extensions updates
  administrator/language/en-GB/en-GB.plg_quickicon_extensionupdate.ini
  administrator/language/en-GB/en-GB.plg_quickicon_joomlaupdate.ini
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_quickicons.scss
  administrator/templates/atum/scss/template-rtl.scss
  administrator/templates/atum/scss/template.scss
  build/media_src/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_src/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  plugins/quickicon/extensionupdate/extensionupdate.php
  plugins/quickicon/joomlaupdate/joomlaupdate.php
Labels: J4 Issue, Language Change, PR-4.0-dev

#23186 Fixing comment
  plugins/privacy/content/content.php
Labels: PR-staging

#23175 Fix a few sql errors in Article List on SQL Server
  administrator/components/com_content/models/articles.php
  installation/sql/sqlazure/joomla.sql
  libraries/joomla/database/query/sqlsrv.php
  libraries/src/Language/Associations.php
Labels: PR-staging, RTC

#23187 [4.0] Can't create field group
  administrator/components/com_fields/Model/GroupModel.php
  administrator/components/com_fields/tmpl/group/edit.php
Labels: PR-4.0-dev

#23143 [4.0] Implementing RTL for admin menus
  administrator/templates/atum/scss/template-rtl.scss
Labels: PR-4.0-dev

#23203 Correcting direction to LTR for Swedish
  installation/language/sv-SE/sv-SE.xml
Labels: Language Change, PR-staging

#23208 [4.0] RTL: Correcting broken installation
  installation/template/scss/template-rtl.scss
Labels: PR-4.0-dev

#23173 [4.0] Cleanup the imports
  administrator/components/com_cache/Controller/DisplayController.php
  administrator/components/com_categories/Controller/DisplayController.php
  administrator/components/com_categories/Field/CategoryeditField.php
  administrator/components/com_fields/tmpl/groups/default_batch_body.php
  administrator/components/com_installer/Controller/DisplayController.php
  administrator/components/com_joomlaupdate/Controller/DisplayController.php
  administrator/components/com_media/src/Model/FileModel.php
  administrator/components/com_menus/Model/MenusModel.php
  administrator/components/com_modules/View/Modules/HtmlView.php
  administrator/modules/mod_sampledata/tmpl/default.php
  libraries/src/Extension/LegacyComponent.php
  libraries/src/MVC/View/ListView.php
  modules/mod_related_items/mod_related_items.php
  modules/mod_search/mod_search.php
  modules/mod_tags_popular/mod_tags_popular.php
Labels: PR-4.0-dev

#23139 [4.0] Correct Table::hasField() uses
  libraries/src/MVC/Model/FormModel.php
  libraries/src/Table/Nested.php
  libraries/src/Table/Table.php
Labels: PR-4.0-dev
