Repository joomla/joomla-cms, pull requests merged in 2018-05, with the labels that each got.

#19953 [4.0] Make switcher type detection more robust
  layouts/joomla/form/field/radio/switcher.php
Labels: PR-4.0-dev

#20299 [com_config] Capitalize label
  administrator/language/en-GB/en-GB.com_config.ini
Labels: Language Change, PR-staging, RTC

#20301 [CS] Add clean lines as defined in the codestyles
  libraries/cms/html/content.php
Labels: RTC

#20280 [fix] openbase_dir correct processing, #13214
  libraries/joomla/filesystem/folder.php
Labels: PR-staging, RTC

#20269 CodeMirror updated to version 5.37.0
  media/editors/codemirror/addon/edit/continuelist.js
  media/editors/codemirror/addon/edit/continuelist.min.js
  media/editors/codemirror/addon/fold/xml-fold.js
  media/editors/codemirror/addon/fold/xml-fold.min.js
  media/editors/codemirror/addon/hint/javascript-hint.js
  media/editors/codemirror/addon/hint/javascript-hint.min.js
  media/editors/codemirror/addon/hint/show-hint.js
  media/editors/codemirror/addon/hint/show-hint.min.js
  media/editors/codemirror/addon/hint/sql-hint.js
  media/editors/codemirror/addon/hint/sql-hint.min.js
  media/editors/codemirror/addon/merge/merge.css
  media/editors/codemirror/addon/merge/merge.js
  media/editors/codemirror/addon/merge/merge.min.css
  media/editors/codemirror/addon/merge/merge.min.js
  media/editors/codemirror/addon/mode/multiplex.js
  media/editors/codemirror/addon/mode/multiplex.min.js
  media/editors/codemirror/addon/search/match-highlighter.js
  media/editors/codemirror/addon/search/match-highlighter.min.js
  media/editors/codemirror/keymap/emacs.js
  media/editors/codemirror/keymap/emacs.min.js
  media/editors/codemirror/keymap/vim.js
  media/editors/codemirror/keymap/vim.min.js
  media/editors/codemirror/lib/addons.js
  media/editors/codemirror/lib/addons.min.js
  media/editors/codemirror/lib/codemirror.js
  media/editors/codemirror/lib/codemirror.min.js
  media/editors/codemirror/mode/clike/clike.js
  media/editors/codemirror/mode/clike/clike.min.js
  media/editors/codemirror/mode/javascript/javascript.js
  media/editors/codemirror/mode/javascript/javascript.min.js
  media/editors/codemirror/mode/markdown/markdown.js
  media/editors/codemirror/mode/markdown/markdown.min.js
  media/editors/codemirror/mode/python/python.js
  media/editors/codemirror/mode/python/python.min.js
  media/editors/codemirror/mode/soy/soy.js
  media/editors/codemirror/mode/soy/soy.min.js
  media/editors/codemirror/mode/sql/sql.js
  media/editors/codemirror/mode/sql/sql.min.js
  media/editors/codemirror/mode/velocity/velocity.js
  media/editors/codemirror/mode/velocity/velocity.min.js
  media/editors/codemirror/theme/gruvbox-dark.css
  media/editors/codemirror/theme/idea.css
  media/editors/codemirror/theme/lucario.css
  media/editors/codemirror/theme/ssms.css
  plugins/editors/codemirror/codemirror.xml
Labels: PR-staging, RTC

#20267 [com_search] Use page title from menu item.
  components/com_search/views/search/view.html.php
Labels: RTC

#20266 Change the defaults for new installs to disable com_mailto in articles
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_learn.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_learn.sql
  installation/sql/sqlazure/joomla.sql
  installation/sql/sqlazure/sample_learn.sql
  tests/unit/stubs/database/jos_extensions.csv
  tests/unit/stubs/database/jos_menu.csv
Labels: PR-staging, RTC

#20247 Don't enable sending the PW on new installs
  administrator/components/com_users/models/user.php
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_learn.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_learn.sql
  installation/sql/postgresql/sample_testing.sql
  installation/sql/sqlazure/joomla.sql
  installation/sql/sqlazure/sample_learn.sql
  installation/sql/sqlazure/sample_testing.sql
  tests/unit/stubs/database/jos_extensions.csv
Labels: PR-staging, RTC, Unit/System Tests

#20306 [4.0] Various installation cleanups
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
  installation/src/Controller/InstallationController.php
  installation/src/Model/CleanupModel.php
  installation/src/Model/ConfigurationModel.php
  installation/src/Model/DatabaseModel.php
  installation/src/Model/SetupModel.php
Labels: Language Change, PR-4.0-dev

#20305 [3.9] Fix filesystem helper class not found
  libraries/src/Filesystem/Stream.php
Labels: PR-3.9-dev

#19987 [4.0] Remove the need for empty dispatcher classes
  administrator/components/com_content/Dispatcher/Dispatcher.php
  libraries/src/Component/ComponentHelper.php
  libraries/src/Dispatcher/Dispatcher.php
  libraries/src/Dispatcher/DispatcherFactory.php
Labels: PR-4.0-dev

#18958 [4.0] Fix issues when people don't enter the right information in the installer
  installation/src/Application/InstallationApplication.php
  installation/src/Controller/InstallationController.php
  installation/src/Controller/JSONController.php
  installation/src/Model/SetupModel.php
  installation/template/js/setup.js
  installation/template/js/template.js
Labels: PR-4.0-dev, RTC

#20326 [4.0] Fix version history preview of Articles
  administrator/components/com_contenthistory/Model/PreviewModel.php
Labels: PR-4.0-dev

#20333 [4.0] Installation strings
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
Labels: Language Change, PR-4.0-dev

#20279 [a11y] Hide Enabled/Disabled users column headers
  administrator/components/com_users/views/groups/tmpl/default.php
Labels: PR-staging, RTC

#20270 Code mirror autofocus issue
  administrator/language/en-GB/en-GB.plg_editors_codemirror.ini
  libraries/src/Form/Field/EditorField.php
  plugins/editors/codemirror/codemirror.php
  plugins/editors/codemirror/codemirror.xml
Labels: Language Change, PR-staging, RTC

#20219 Add a deprecated flag in database query for union queries
  libraries/joomla/database/query.php
Labels: RTC

#20156 [com_media] Add showon attribute
  administrator/components/com_media/config.xml
Labels: PR-staging, RTC

#20124 [com_contact] Display 0 value with custom field
  components/com_contact/layouts/field/render.php
  components/com_contact/layouts/fields/render.php
Labels: PR-staging, RTC

#20023 Single Contact format Tabs
  components/com_contact/views/contact/tmpl/default_user_custom_fields.php
Labels: PR-staging, RTC

#17042 Show a sample editor on the CodeMirror plugin config page.
  administrator/language/en-GB/en-GB.plg_editors_codemirror.ini
  plugins/editors/codemirror/codemirror.xml
Labels: Language Change, PR-staging, RTC

#20337 [4.0] Remove invalid or not used imports
  libraries/src/Dispatcher/LegacyDispatcher.php
  libraries/src/Service/Provider/Application.php
Labels: PR-4.0-dev

#20316 [4.0] Remove invalid classes from the classmap
  libraries/classmap.php
Labels: PR-4.0-dev

#20202 [plg_content_pagebreak] Let users template override TOC
  plugins/content/pagebreak/pagebreak.php
  plugins/content/pagebreak/tmpl/toc.php
Labels: PR-3.9-dev, RTC

#20083 Allow searching article content in backend
  administrator/components/com_content/models/articles.php
  administrator/components/com_content/models/featured.php
  administrator/language/en-GB/en-GB.com_content.ini
Labels: Language Change, PR-3.9-dev, RTC

#19693 Fix subform repeat counter.
  media/system/js/subform-repeatable-uncompressed.js
  media/system/js/subform-repeatable.js
  tests/javascript/subform-repeatable/spec.js
Labels: PR-staging, RTC, Unit/System Tests

#20321 [Deprecate _QQ_ 3] Mark _QQ_ as deprecated and normalize language ini parsing
  administrator/components/com_languages/helpers/languages.php
  administrator/components/com_languages/models/override.php
  administrator/components/com_languages/models/overrides.php
  administrator/components/com_languages/views/overrides/tmpl/default.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
Labels: PR-3.9-dev, RTC

#13396 [mod_admin_stats] - add links to users and articles
  administrator/modules/mod_stats_admin/helper.php
  administrator/modules/mod_stats_admin/tmpl/default.php
Labels: PR-staging, RTC

#18998 Enabling showon to work in list options in JForm (resurrected)
  libraries/joomla/form/fields/list.php
  media/jui/js/cms-uncompressed.js
  media/jui/js/cms.js
Labels: PR-staging, RTC

#20144 Add the return value to the Cancel option
  libraries/src/MVC/Controller/FormController.php
Labels: New Feature, PR-staging, RTC

#20349 (Joomla 4) Fix filters for archive view
  components/com_content/View/Archive/HtmlView.php
  libraries/src/Pagination/Pagination.php
Labels: PR-4.0-dev

#17939 Fixing so that editors-xtd plugins works with com_ajax
  libraries/src/Plugin/PluginHelper.php
Labels: PR-staging

#20385 [4.0] Fix preinstall view in installer
  installation/src/Model/ChecksModel.php
  installation/src/Model/LanguagesModel.php
  installation/src/View/Preinstall/HtmlView.php
Labels: PR-4.0-dev

#20340 [4.0] Add and update docblocks and missing class properties in installer
  installation/src/Model/LanguagesModel.php
  installation/src/View/Remove/HtmlView.php
  installation/tmpl/remove/default.php
Labels: PR-4.0-dev

#20382 [4.0] Give com_modules a service interface so that com_config can integrate
  administrator/components/com_modules/Extension/ModulesComponent.php
  administrator/components/com_modules/dispatcher.php
  administrator/components/com_modules/services/provider.php
  build/phpcs/Joomla/ruleset.xml
  components/com_config/Controller/ModulesController.php
Labels: PR-4.0-dev

#20387 [4.0] Add a migration layer for PostgreSQL configured sites to the database service provider
  libraries/src/Service/Provider/Database.php
Labels: RTC

#20388 [4.0] Bump database and session packages
  composer.lock
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/database/src/DatabaseDriver.php
  libraries/vendor/joomla/database/src/DatabaseQuery.php
  libraries/vendor/joomla/database/src/Exception/ConnectionFailureException.php
  libraries/vendor/joomla/database/src/Exception/ExecutionFailureException.php
  libraries/vendor/joomla/database/src/Exception/PrepareStatementFailureException.php
  libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php
  libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php
  libraries/vendor/joomla/database/src/Oracle/OracleDriver.php
  libraries/vendor/joomla/database/src/Oracle/OracleQuery.php
  libraries/vendor/joomla/database/src/Pgsql/PgsqlExporter.php
  libraries/vendor/joomla/database/src/Pgsql/PgsqlImporter.php
  libraries/vendor/joomla/database/src/Pgsql/PgsqlQuery.php
  libraries/vendor/joomla/database/src/Postgresql/PostgresqlDriver.php
  libraries/vendor/joomla/database/src/Postgresql/PostgresqlExporter.php
  libraries/vendor/joomla/database/src/Postgresql/PostgresqlImporter.php
  libraries/vendor/joomla/database/src/Postgresql/PostgresqlQuery.php
  libraries/vendor/joomla/database/src/Postgresql/PostgresqlStatement.php
  libraries/vendor/joomla/database/src/QueryInterface.php
  libraries/vendor/joomla/database/src/Sqlite/SqliteQuery.php
  libraries/vendor/joomla/database/src/Sqlsrv/SqlsrvDriver.php
  libraries/vendor/joomla/database/src/Sqlsrv/SqlsrvQuery.php
  libraries/vendor/joomla/session/src/Handler/DatabaseHandler.php
  libraries/vendor/joomla/session/src/Session.php
Labels: Composer Dependency Changed, PR-4.0-dev, RTC

#20399 [4.0] Removal of _QQ_
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
Labels: Language Change, PR-4.0-dev, RTC

#19612 Forward port of the output buffering check fix to 3.9
  administrator/components/com_joomlaupdate/models/default.php
Labels: PR-3.10-dev

#20109 [4.0] Change how uncaught exceptions are processed
  composer.json
  composer.lock
  installation/src/Application/InstallationApplication.php
  libraries/bootstrap.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Event/ErrorEvent.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  plugins/system/redirect/redirect.php
Labels: Composer Dependency Changed, PR-4.0-dev

#20410 [Plugins] Add filters to manifest files.
  plugins/authentication/gmail/gmail.xml
  plugins/authentication/ldap/ldap.xml
  plugins/content/emailcloak/emailcloak.xml
  plugins/content/joomla/joomla.xml
  plugins/content/pagebreak/pagebreak.xml
  plugins/content/pagenavigation/pagenavigation.xml
  plugins/search/categories/categories.xml
  plugins/search/contacts/contacts.xml
  plugins/search/content/content.xml
  plugins/search/newsfeeds/newsfeeds.xml
  plugins/search/tags/tags.php
  plugins/search/tags/tags.xml
  plugins/twofactorauth/totp/totp.xml
  plugins/twofactorauth/yubikey/yubikey.xml
  plugins/user/contactcreator/contactcreator.xml
Labels: RTC

#20419 Change 404 message from URL Invalid to Not Found
  libraries/src/Router/Router.php
Labels: PR-4.0-dev

#20392 URL Menu Item Type link should be required.
  administrator/components/com_menus/views/item/tmpl/edit.php
Labels: PR-staging, RTC

#20224 Fix up the protostar template.js
  templates/protostar/js/template.js
Labels: RTC

#18909 Bootstrap alert compatible
  media/system/js/core-uncompressed.js
  media/system/js/core.js
Labels: PR-staging, RTC

#20398 [4.0] Fix frontend module editing
  components/com_config/tmpl/config/default.php
  components/com_config/tmpl/modules/default.php
  components/com_config/tmpl/templates/default.php
  components/com_content/tmpl/form/edit.php
Labels: PR-4.0-dev

#20414 [4.0] Fixes #20395 with encodeURIComponent on form values
  installation/template/js/template.js
Labels: PR-4.0-dev, RTC

#20421 [4.0] Class 'ModulesHelper' not found when creating/editing module
  administrator/components/com_modules/helpers/html/modules.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
Labels: PR-4.0-dev

#20433 [4.0][CS] Inside libraries/form
  libraries/src/Form/Field/AliastagField.php
  libraries/src/Form/Field/CategoryField.php
  libraries/src/Form/Field/ColorField.php
  libraries/src/Form/Field/ComponentlayoutField.php
  libraries/src/Form/Field/EditorField.php
  libraries/src/Form/Field/LanguageField.php
  libraries/src/Form/Field/ListField.php
  libraries/src/Form/Field/MediaField.php
  libraries/src/Form/Field/MenuitemField.php
  libraries/src/Form/Field/ModulelayoutField.php
  libraries/src/Form/Field/RulesField.php
  libraries/src/Form/Field/TextField.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormHelper.php
Labels: PR-4.0-dev, Test instructions missing

#20439 [4.0] Testing: Add command to only install Joomla with the RoboFile
  RoboFile.php
Labels: PR-4.0-dev, Unit/System Tests

#20441 Add PHP 7.3 polyfill
  .gitignore
  composer.json
  composer.lock
  libraries/vendor/composer/ClassLoader.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_files.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/symfony/polyfill-php73/LICENSE
  libraries/vendor/symfony/polyfill-php73/bootstrap.php
Labels: Composer Dependency Changed, PR-staging

#20431 [4.0] Use the app response so we get headers sent on error
  installation/src/Application/InstallationApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Exception/ExceptionHandler.php
Labels: PR-4.0-dev

#20449 [4.0] Point the js tests to the master branch
  drone-package.json
Labels: PR-4.0-dev, Unit/System Tests

#20153 [4.0] Remove caption js
  components/com_contact/tmpl/categories/default.php
  components/com_content/tmpl/archive/default.php
  components/com_content/tmpl/article/default.php
  components/com_content/tmpl/categories/default.php
  components/com_content/tmpl/category/blog.php
  components/com_content/tmpl/category/default.php
  components/com_content/tmpl/featured/default.php
  components/com_newsfeeds/tmpl/categories/default.php
  components/com_newsfeeds/tmpl/category/default.php
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
  libraries/cms/html/behavior.php
  media/legacy/js/caption.js
  media/legacy/js/caption.min.js
Labels: Documentation Required, PR-4.0-dev

#20411 [com_finder] Fix toggle selection (Regression #19969)
  components/com_finder/helpers/html/filter.php
Labels: PR-staging, RTC

#19964 [com_finder] - fix update inner join syntax for postgres
  administrator/components/com_finder/helpers/indexer/indexer.php
Labels: PR-staging, RTC

#19951 Update tag.php
  components/com_tags/models/tag.php
Labels: RTC

#20454 [4.0] Installation text improvement
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
Labels: Language Change, PR-4.0-dev, RTC

#20448 [4.0] Trigger the onBeforeExecute correctly through the dispatcher
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CliApplication.php
  libraries/src/Application/DaemonApplication.php
  libraries/src/Application/WebApplication.php
Labels: PR-4.0-dev

#20460 Typo in nl-NL installation language file
  installation/language/nl-NL/nl-NL.ini
Labels: Language Change, PR-staging

#20444 [4.0] Add the requested new line & await en-GB review
  plugins/system/httpheaders/subform/cspkeyvalue.xml
Labels: PR-4.0-dev

#20453 [4.0] Change com_admin to services
  administrator/components/com_admin/Dispatcher/Dispatcher.php
  administrator/components/com_admin/Extension/AdminComponent.php
  administrator/components/com_admin/Service/HTML/Directory.php
  administrator/components/com_admin/Service/HTML/PhpSetting.php
  administrator/components/com_admin/Service/HTML/System.php
  administrator/components/com_admin/services/provider.php
Labels: PR-4.0-dev

#20443 [4.0] Take the list of tags out of the form
  components/com_tags/tmpl/tags/default_items.php
Labels: PR-4.0-dev

#20429 [4.0] Use the latest polyfills for web components
  media/system/js/core.js
  media/system/js/core.min.js
  media/vendor/webcomponentsjs/js/webcomponents-bundle.js
  media/vendor/webcomponentsjs/js/webcomponents-bundle.min.js
  media/vendor/webcomponentsjs/js/webcomponents-ce.js
  media/vendor/webcomponentsjs/js/webcomponents-ce.min.js
  media/vendor/webcomponentsjs/js/webcomponents-hi-ce.js
  media/vendor/webcomponentsjs/js/webcomponents-hi-ce.js.map
  media/vendor/webcomponentsjs/js/webcomponents-hi-ce.min.js
  media/vendor/webcomponentsjs/js/webcomponents-hi-sd-ce.js
  media/vendor/webcomponentsjs/js/webcomponents-hi-sd-ce.js.map
  media/vendor/webcomponentsjs/js/webcomponents-hi-sd-ce.min.js
  media/vendor/webcomponentsjs/js/webcomponents-hi-sd.js
  media/vendor/webcomponentsjs/js/webcomponents-hi-sd.js.map
  media/vendor/webcomponentsjs/js/webcomponents-hi-sd.min.js
  media/vendor/webcomponentsjs/js/webcomponents-hi.js
  media/vendor/webcomponentsjs/js/webcomponents-hi.js.map
  media/vendor/webcomponentsjs/js/webcomponents-hi.min.js
  media/vendor/webcomponentsjs/js/webcomponents-lite.js
  media/vendor/webcomponentsjs/js/webcomponents-lite.js.map
  media/vendor/webcomponentsjs/js/webcomponents-lite.min.js
  media/vendor/webcomponentsjs/js/webcomponents-sd-ce-pf.js
  media/vendor/webcomponentsjs/js/webcomponents-sd-ce-pf.min.js
  media/vendor/webcomponentsjs/js/webcomponents-sd-ce.js
  media/vendor/webcomponentsjs/js/webcomponents-sd-ce.js.map
  media/vendor/webcomponentsjs/js/webcomponents-sd-ce.min.js
  media/vendor/webcomponentsjs/js/webcomponents-sd.js
  media/vendor/webcomponentsjs/js/webcomponents-sd.min.js
  package.json
Labels: PR-4.0-dev

#20504 [4.0] The dispatcher factory is a required dependency
  administrator/components/com_admin/services/provider.php
  administrator/components/com_content/services/provider.php
  administrator/components/com_modules/services/provider.php
  libraries/src/Extension/Component.php
Labels: PR-4.0-dev

#20503 [4.0] Notices in articles layouts
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
Labels: PR-4.0-dev, RTC

#20512 [4.0] js error in core.js (web components)
  installation/template/index.php
  media/system/js/core.js
  media/system/js/core.min.js
Labels: PR-4.0-dev

#20520 [4.0] Displaying articles captions below the images
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
Labels: PR-4.0-dev

#19744 [4.0] Improve assets handling
  libraries/cms/html/formbehavior.php
  libraries/src/HTML/HTMLHelper.php
Labels: PR-4.0-dev, RTC

#20528 [4.0] Only add debug information during installation on HTML documents
  installation/src/Application/InstallationApplication.php
Labels: PR-4.0-dev, RTC

#20533 Correctly escape the random image module output
  modules/mod_random_image/tmpl/default.php
Labels: RTC

#19297 [4.0] Fields using more namespaced classes
  libraries/src/Form/Field/AccesslevelField.php
  libraries/src/Form/Field/AliastagField.php
  libraries/src/Form/Field/CachehandlerField.php
  libraries/src/Form/Field/CalendarField.php
  libraries/src/Form/Field/CategoryField.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Form/Field/ComponentlayoutField.php
  libraries/src/Form/Field/ComponentsField.php
  libraries/src/Form/Field/ContenthistoryField.php
  libraries/src/Form/Field/ContentlanguageField.php
  libraries/src/Form/Field/ContenttypeField.php
  libraries/src/Form/Field/DatabaseconnectionField.php
  libraries/src/Form/Field/FilelistField.php
  libraries/src/Form/Field/FolderlistField.php
  libraries/src/Form/Field/GroupedlistField.php
  libraries/src/Form/Field/HeadertagField.php
  libraries/src/Form/Field/HelpsiteField.php
  libraries/src/Form/Field/IntegerField.php
  libraries/src/Form/Field/LimitboxField.php
  libraries/src/Form/Field/ListField.php
  libraries/src/Form/Field/MediaField.php
  libraries/src/Form/Field/MenuField.php
  libraries/src/Form/Field/MenuitemField.php
  libraries/src/Form/Field/ModulelayoutField.php
  libraries/src/Form/Field/ModulepositionField.php
  libraries/src/Form/Field/ModuletagField.php
  libraries/src/Form/Field/NoteField.php
  libraries/src/Form/Field/NumberField.php
  libraries/src/Form/Field/OrderingField.php
  libraries/src/Form/Field/PluginsField.php
  libraries/src/Form/Field/PredefinedlistField.php
  libraries/src/Form/Field/SessionhandlerField.php
  libraries/src/Form/Field/SpacerField.php
  libraries/src/Form/Field/SqlField.php
  libraries/src/Form/Field/SubformField.php
  libraries/src/Form/Field/TagField.php
  libraries/src/Form/Field/TemplatestyleField.php
  libraries/src/Form/Field/TextField.php
  libraries/src/Form/Field/TimezoneField.php
  libraries/src/Form/Field/UserField.php
  libraries/src/Form/Field/UsergroupField.php
  libraries/src/Form/Form.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormHelper.php
  libraries/src/Form/Rule/CalendarRule.php
  libraries/src/Form/Rule/CaptchaRule.php
  libraries/src/Form/Rule/EmailRule.php
  libraries/src/Form/Rule/PasswordRule.php
  libraries/src/Form/Rule/UrlRule.php
  libraries/src/Form/Rule/UsernameRule.php
Labels: PR-4.0-dev

#20523 [4.0] Fixing Suggestions in Finder/Smart Search
  components/com_finder/Controller/SuggestionsController.php
Labels: PR-4.0-dev, RTC

#20265 Finally com_mailto allow the usage of a captcha by using JForm
  components/com_content/helpers/icon.php
  components/com_mailto/controller.php
  components/com_mailto/models/forms/mailto.xml
  components/com_mailto/models/mailto.php
  components/com_mailto/views/mailto/tmpl/default.php
  components/com_mailto/views/mailto/view.html.php
  language/en-GB/en-GB.com_mailto.ini
Labels: Language Change, PR-staging, RTC

#20277 Remove check for a valid form from two places in plugins
  plugins/system/languagecode/languagecode.php
  plugins/user/profile/profile.php
Labels: PR-staging, RTC

#20338 [plg_authentication_cookie] Fallback to integers
  plugins/authentication/cookie/cookie.php
Labels: RTC

#20412 [plg_user_profile] Misc fixes
  plugins/user/profile/field/tos.php
  plugins/user/profile/profile.php
  plugins/user/profile/profile.xml
  plugins/user/profile/profiles/profile.xml
Labels: PR-staging, RTC

#20456 [plg_system] Manifest file filters
  plugins/system/cache/cache.php
  plugins/system/cache/cache.xml
  plugins/system/debug/debug.php
  plugins/system/debug/debug.xml
  plugins/system/languagefilter/languagefilter.php
  plugins/system/languagefilter/languagefilter.xml
  plugins/system/log/log.xml
  plugins/system/redirect/form/excludes.xml
  plugins/system/redirect/redirect.php
  plugins/system/redirect/redirect.xml
  plugins/system/sef/sef.php
Labels: PR-staging, RTC

#20522 [CS] fix some doc comment types
  administrator/components/com_banners/helpers/banners.php
  administrator/components/com_banners/models/banner.php
  administrator/components/com_banners/tables/banner.php
  administrator/components/com_banners/tables/client.php
  administrator/components/com_categories/controllers/categories.php
  administrator/components/com_categories/models/categories.php
  administrator/components/com_categories/models/category.php
  administrator/components/com_contact/helpers/contact.php
  administrator/components/com_contact/tables/contact.php
  administrator/components/com_content/helpers/content.php
  administrator/components/com_content/models/article.php
  administrator/components/com_content/tables/featured.php
  administrator/components/com_contenthistory/models/history.php
  administrator/components/com_fields/helpers/fields.php
  administrator/components/com_fields/models/field.php
  build/phpcs/Joomla/ruleset.xml
Labels: PR-staging, RTC

#20542 [styles] Fix checkboxes/buttons not clickable under Menu Assignment in Chrome
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/less/pages/_com_templates.less
Labels: PR-staging, RTC

#19949 [Regression] Menu item type url with rel attribute nofollow
  modules/mod_menu/tmpl/default_url.php
Labels: PR-staging, RTC

#13868 To many elements to index
  plugins/finder/tags/tags.php
Labels: PR-staging, RTC

#20505 [4.0] Check for the correct countItems callback function
  libraries/src/Extension/LegacyComponent.php
Labels: PR-4.0-dev

#20574 [4.0][com_menus] Use correct language constant
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
Labels: PR-4.0-dev, RTC

#20565 [4.0] Fix template preview alignment
  administrator/components/com_templates/tmpl/template/default_description.php
Labels: PR-4.0-dev, RTC

#20586 Fix folder browsing and file upload that broke in 3.8.8 due to escaping
  media/media/js/popup-imagemanager.js
  media/media/js/popup-imagemanager.min.js
Labels: RTC

#20577 standardise contact strings
  administrator/language/en-GB/en-GB.com_contact.ini
Labels: RTC

#20353 Deprecate ContactModelContact::getContactQuery()
  components/com_contact/models/contact.php
Labels: PR-3.9-dev, RTC

#20313 Enable to change FormData in com_menu
  administrator/components/com_banners/models/download.php
  administrator/components/com_menus/models/item.php
Labels: RTC

#20169 [mod_articles_news] Option Intro/Full Images of the article
  language/en-GB/en-GB.mod_articles_news.ini
  modules/mod_articles_news/helper.php
  modules/mod_articles_news/mod_articles_news.xml
  modules/mod_articles_news/tmpl/_item.php
Labels: Language Change, PR-3.9-dev, RTC

#20021 show_profile option
  components/com_contact/views/contact/tmpl/default.xml
Labels: PR-3.9-dev, RTC

#19509 [com_content] - Add tags filtering based on language filter
  components/com_content/views/category/tmpl/default_articles.php
Labels: PR-3.9-dev, RTC

#20599 [4.0] Multilingual minimum correction to be able to test stuff in frontend
  plugins/system/languagefilter/languagefilter.php
Labels: PR-4.0-dev

#20607 fix typo in installation string
  installation/language/en-GB/en-GB.ini
Labels: Language Change, PR-staging

#20570 [4.0][A11Y] CSS4 focus visible polyfill
  administrator/templates/atum/component.php
  administrator/templates/atum/css/bootstrap.css
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  media/vendor/flying-focus-a11y/MIT-LICENSE.txt
  media/vendor/flying-focus-a11y/js/flying-focus.js
  media/vendor/flying-focus-a11y/js/flying-focus.min.js
  media/vendor/flying-focus-a11y/scss/flying-focus.scss
  media/vendor/focus-visible/LICENSE.md
  media/vendor/focus-visible/js/focus-visible.js
  media/vendor/focus-visible/js/focus-visible.min.js
  media/vendor/webcomponentsjs/js/webcomponents-bundle.js
  media/vendor/webcomponentsjs/js/webcomponents-bundle.min.js
  package.json
Labels: PR-4.0-dev, RTC

#20564 Resync deleted files list back to 1.7.3 tag
  administrator/components/com_admin/script.php
Labels: PR-staging

#20612 [4.0] Change com_joomlaupdate to services
  administrator/components/com_joomlaupdate/dispatcher.php
  administrator/components/com_joomlaupdate/services/provider.php
Labels: PR-4.0-dev

#20555 [4.0] remove <php 7 code
  administrator/components/com_joomlaupdate/Model/UpdateModel.php
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
  installation/src/Model/ChecksModel.php
Labels: Language Change, PR-4.0-dev

#19868 [4.0] Namespace content site associations helper
  components/com_content/Dispatcher/Dispatcher.php
  components/com_content/Helper/AssociationHelper.php
  components/com_content/Model/ArticlesModel.php
  components/com_content/View/Article/HtmlView.php
  components/com_content/tmpl/category/default_articles.php
Labels: PR-4.0-dev

#19836 [4.0] Modules can't be created
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-03-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-03-05.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#20624 [4.0] Missing argument in sprintf().
  libraries/src/Toolbar/ContainerAwareToolbarFactory.php
Labels: PR-4.0-dev

#20614 [4.0] Change com_checkin to services
  administrator/components/com_checkin/dispatcher.php
  administrator/components/com_checkin/services/provider.php
Labels: PR-4.0-dev

#20613 [4.0] Change com_cache to services
  administrator/components/com_cache/dispatcher.php
  administrator/components/com_cache/services/provider.php
Labels: PR-4.0-dev

#20622 [4.0] Finish the move of com_modules to services
  administrator/components/com_modules/Extension/ModulesComponent.php
  administrator/components/com_modules/Service/HTML/Modules.php
  administrator/components/com_modules/helpers/modules.php
  administrator/components/com_modules/services/provider.php
  components/com_modules/Dispatcher/Dispatcher.php
Labels: PR-4.0-dev

#20619 [4.0] Change com_templates to services
  administrator/components/com_templates/Extension/TemplatesComponent.php
  administrator/components/com_templates/Service/HTML/Templates.php
  administrator/components/com_templates/dispatcher.php
  administrator/components/com_templates/helpers/template.php
  administrator/components/com_templates/helpers/templates.php
  administrator/components/com_templates/services/provider.php
Labels: PR-4.0-dev
