Repository joomla/joomla-cms, pull requests merged in 2018-09, with the labels that each got.

#21950 [3.9] Adjustments for upcoming Install from Web plugin update
  .gitignore
  administrator/language/en-GB/en-GB.plg_installer_webinstaller.ini
Labels: Language Change, PR-3.9-dev

#21954 [3.9] Unused string. Code was modified to use a JGLOBAL one
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, PR-3.9-dev

#21955 [3.9] en-GB.plg_captcha_recaptcha.ini: Alpha sorting strings. Taking off blank lines before comments.
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha.ini
Labels: Language Change, PR-3.9-dev

#21966 Removing unnecessary line
  administrator/components/com_content/forms/filter_articles.xml
Labels: PR-4.0-dev

#21604 [4.0] [a11y] Admin Login Page
  administrator/templates/atum/login.php
Labels: PR-4.0-dev, RTC

#21608 [4.0] [a11y] cyan
  administrator/templates/atum/scss/_variables.scss
  templates/cassiopeia/scss/_variables.scss
Labels: PR-4.0-dev, RTC

#21559 [4.0] [a11y] Rules permissions - text filters notes
  administrator/components/com_config/Field/FiltersField.php
  administrator/templates/atum/scss/pages/_com_config.scss
  layouts/joomla/form/field/rules.php
Labels: PR-4.0-dev, RTC

#21965 [4.0] Template name missing string
  language/en-GB/en-GB.tpl_cassiopeia.sys.ini
  templates/cassiopeia/language/en-GB/en-GB.tpl_cassiopeia.sys.ini
Labels: Language Change, PR-4.0-dev

#21011 added a new parameter nolangfilter (Replaces #8117)
  plugins/system/languagefilter/languagefilter.php
Labels: PR-staging

#21962 [3.9] Add privacy note to the new captcha plugin
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha.ini
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.sys.ini
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
Labels: Language Change, PR-3.9-dev

#21012 [3.9] Cache Plugin improvements (Replaces #8431)
  administrator/language/en-GB/en-GB.plg_system_cache.ini
  plugins/system/cache/cache.php
Labels: Language Change, PR-staging

#21969 [plg_quickicon_phpversioncheck] Correct displayed PHP support date
  plugins/quickicon/phpversioncheck/phpversioncheck.php
Labels: RTC

#21844 [SQL] - use db api dateAdd() instead of mysql dialect
  components/com_content/models/articles.php
  libraries/joomla/database/query.php
  libraries/joomla/database/query/postgresql.php
  tests/unit/suites/database/driver/postgresql/JDatabaseQueryPostgresqlTest.php
  tests/unit/suites/libraries/joomla/database/JDatabaseQueryTest.php
Labels: PR-staging, RTC, Unit/System Tests

#21722 [3.8] Make sure we don't send a referrer on the remind and reset views
  components/com_users/controller.php
Labels: PR-staging, RTC

#21695 Use search tools in the overrides view
  administrator/components/com_languages/models/fields/languageclient.php
  administrator/components/com_languages/models/forms/filter_overrides.xml
  administrator/components/com_languages/models/overrides.php
  administrator/components/com_languages/views/overrides/tmpl/default.php
  administrator/components/com_languages/views/overrides/view.html.php
Labels: PR-staging, RTC

#21692 Ordering field in module's settings
  layouts/joomla/form/field/moduleorder.php
  media/system/js/moduleorder.js
Labels: RTC

#21690 Fix tags RSS Feed
  components/com_tags/views/tag/view.feed.php
Labels: RTC

#21152 [3.9] Use the new link helper to generate links for specific app
  administrator/components/com_messages/models/message.php
  components/com_users/models/registration.php
Labels: RTC

#20629 Remove duplicate observers ~ 20 queries less while saving the article
  libraries/joomla/observer/updater.php
Labels: PR-staging, RTC

#20158 Remove not necessary line of code
  administrator/components/com_fields/helpers/fields.php
  plugins/system/fields/fields.php
  plugins/system/updatenotification/updatenotification.php
Labels: PR-staging, RTC

#16069 [com_fields] Error message when creating a field with a name already existing
  administrator/language/en-GB/en-GB.com_fields.ini
Labels: Language Change, PR-staging, RTC

#21980 [3.9] missing string in en-GB.plg_system_actionlogs.ini
  administrator/language/en-GB/en-GB.plg_system_actionlogs.ini
Labels: RTC

#21984 [3.9] Unification plugin name plg_system_actionlogs
  administrator/language/en-GB/en-GB.plg_system_actionlogs.sys.ini
Labels: Language Change, RTC

#21853 [Drone] Make sure an copied repo don't run into issues with the rips step & add tests for 4.0-dev
  .drone.yml
Labels: PR-staging, Unit/System Tests

#21916 [4.0] Multilingual : Correcting info-block category and parent category urls
  components/com_content/Model/ArticleModel.php
  components/com_content/Model/ArticlesModel.php
  components/com_content/View/Archive/HtmlView.php
  components/com_content/View/Article/HtmlView.php
  components/com_content/View/Category/HtmlView.php
  components/com_content/View/Featured/HtmlView.php
  components/com_content/helpers/route.php
  components/com_content/tmpl/archive/default_items.php
  components/com_content/tmpl/category/blog_children.php
  components/com_content/tmpl/category/default_children.php
  layouts/joomla/content/info_block.php
  layouts/joomla/content/info_block/category.php
  layouts/joomla/content/info_block/parent_category.php
  libraries/src/Component/Router/Rules/MenuRules.php
Labels: PR-4.0-dev, RTC

#21851 [4.0][GSoC 2018] Improve Override Management
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-02.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-19.sql
  administrator/components/com_installer/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/Model/UpdateModel.php
  administrator/components/com_templates/Controller/TemplateController.php
  administrator/components/com_templates/Model/TemplateModel.php
  administrator/components/com_templates/Model/TemplatesModel.php
  administrator/components/com_templates/View/Template/HtmlView.php
  administrator/components/com_templates/View/Templates/HtmlView.php
  administrator/components/com_templates/forms/source.xml
  administrator/components/com_templates/tmpl/template/default.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/language/en-GB/en-GB.com_templates.ini
  administrator/language/en-GB/en-GB.plg_installer_override.ini
  administrator/language/en-GB/en-GB.plg_installer_override.sys.ini
  administrator/language/en-GB/en-GB.plg_quickicon_overridecheck.ini
  administrator/language/en-GB/en-GB.plg_quickicon_overridecheck.sys.ini
  build/media/com_templates/css/admin-templates-default.css
  build/media/webcomponents/js/toolbar-button/toolbar-button.js
  build/media_src/com_templates/js/admin-template-compare.es6.js
  build/media_src/com_templates/js/admin-template-toggle-switch.es6.js
  build/media_src/plg_quickicon_overridecheck/js/overridecheck.es6.js
  build/media_src/system/js/core.es6.js
  build/media_src/system/js/multiselect.es6.js
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  libraries/cms/html/grid.php
  libraries/cms/html/jgrid.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Toolbar/Button/StandardButton.php
  libraries/src/Toolbar/ToolbarHelper.php
  plugins/installer/override/override.php
  plugins/installer/override/override.xml
  plugins/quickicon/overridecheck/overridecheck.php
  plugins/quickicon/overridecheck/overridecheck.xml
Labels: Language Change, PR-4.0-dev

#22024 [4.0] Typo in update sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-19.sql
Labels: PR-4.0-dev

#22021 Remove trailing whitespaces from com_tags xml files
  administrator/components/com_tags/config.xml
  administrator/components/com_tags/models/forms/tag.xml
  components/com_tags/views/tag/tmpl/default.xml
  components/com_tags/views/tag/tmpl/list.xml
  components/com_tags/views/tags/tmpl/default.xml
Labels: PR-staging, RTC

#22027 [3.9] missing closing tag in string
  administrator/language/en-GB/en-GB.com_actionlogs.ini
Labels: RTC

#21662 [4.0] More state => stage renaming
  administrator/components/com_content/Model/ArticlesModel.php
  administrator/components/com_content/Model/FeaturedModel.php
  administrator/components/com_content/forms/filter_articles.xml
  administrator/components/com_content/forms/filter_featured.xml
  administrator/components/com_content/tmpl/featured/default.php
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, New Feature Workflow, PR-4.0-dev, RTC

#21942 [4.0] Add publish up/down information to articles list
  administrator/components/com_content/tmpl/articles/default.php
  administrator/language/en-GB/en-GB.com_content.ini
  layouts/joomla/button/transition-button.php
Labels: Language Change, PR-4.0-dev, RTC

#21963 [4.0] Add default stages/transitions when creating a new workflow
  administrator/components/com_workflow/Model/WorkflowModel.php
Labels: PR-4.0-dev, RTC

#21836 [4.0] Workflow Enable/Disable
  administrator/components/com_workflow/forms/stage.xml
  administrator/components/com_workflow/forms/transition.xml
  administrator/components/com_workflow/forms/workflow.xml
  administrator/language/en-GB/en-GB.com_workflow.ini
  build/media_src/system/js/fields/select-colour.es6.js
Labels: Language Change, New Feature Workflow, PR-4.0-dev, RTC

#20904 [4.0] Enabling plg_content_finder plugin by default
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: RTC

#21847 [4.0] Fix broken iframe + modal + backdrop combination
  libraries/src/Toolbar/Button/PopupButton.php
Labels: PR-4.0-dev, RTC

#21953 [4.0] Implement the workflow into the blog sample data
  administrator/language/en-GB/en-GB.plg_sampledata_blog.ini
  plugins/sampledata/blog/blog.php
Labels: Language Change, PR-4.0-dev, RTC

#21641 [4.0][Workflow] Remove com_content defaults from workflow code
  administrator/components/com_workflow/Controller/DisplayController.php
  administrator/components/com_workflow/Controller/StageController.php
  administrator/components/com_workflow/Controller/StagesController.php
  administrator/components/com_workflow/Controller/TransitionController.php
  administrator/components/com_workflow/Controller/TransitionsController.php
  administrator/components/com_workflow/Controller/WorkflowController.php
  administrator/components/com_workflow/Controller/WorkflowsController.php
  administrator/components/com_workflow/Model/StageModel.php
  administrator/components/com_workflow/Model/StagesModel.php
  administrator/components/com_workflow/Model/TransitionModel.php
  administrator/components/com_workflow/Model/TransitionsModel.php
  administrator/components/com_workflow/Model/WorkflowModel.php
  administrator/components/com_workflow/Model/WorkflowsModel.php
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/forms/filter_workflows.xml
  administrator/components/com_workflow/tmpl/workflow/edit.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/Form/Field/WorkflowstageField.php
Labels: New Feature Workflow, PR-4.0-dev

#22054 [4.0] Fix for #22053 COM_USERS enabling and adding YubiKey runs into Fatal error Joomla\CMS\Encrypt\Randvalinterface not found
  libraries/src/Encrypt/Randval.php
Labels: PR-4.0-dev

#22051 [3.9][postgresql] - wrong field name subjext
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-24.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-3.9-dev

#22062 [4.0] Fix transitions controller missing namespace
  administrator/components/com_workflow/Controller/StagesController.php
  administrator/components/com_workflow/Controller/TransitionsController.php
Labels: PR-4.0-dev

#22059 Workflows: Changed column labels in com_workflow transitions
  administrator/language/en-GB/en-GB.com_workflow.ini
Labels: Language Change, PR-4.0-dev

#21938 [4.0] Table Column alignment (part2) [a11y]
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev

#21967 [4.0] Table Column alignment (part3) [a11y]
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/users/default.php
Labels: PR-4.0-dev

#22071 [4.0] Fixed the drag and drop installation failing due to missing data
  build/media_src/com_installer/js/installer.es6.js
  libraries/src/Installer/InstallerScript.php
Labels: RTC

#22078 [4.0] Fixed duplicated use.
  libraries/src/Form/Field/TransitionField.php
Labels: PR-4.0-dev, RTC

#22072 Change joomla toolbar logo size
  administrator/templates/atum/images/logo-blue.svg
Labels: RTC

#21691 Change language debug mode to allow it to show the language constants
  administrator/components/com_config/model/form/application.xml
  administrator/language/en-GB/en-GB.com_config.ini
  installation/configuration.php-dist
  installation/model/configuration.php
  libraries/src/Language/Language.php
Labels: Language Change, PR-staging, RTC

#21937 [3.9-alpha] [mod_articles_category] Make sure the tag does not conflict with the title of the article
  modules/mod_articles_category/helper.php
  modules/mod_articles_category/tmpl/default.php
Labels: PR-3.9-dev, RTC

#21979 [plugin][captcha] - not so invisible Captcha
  libraries/src/Form/Field/CaptchaField.php
Labels: PR-3.9-dev, RTC

#22028 [3.9][plugin][privacyconsent] - notify more than one
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-3.9-dev, RTC

#22040 [com_modules] Client filter not respected in fields after editing module
  administrator/components/com_modules/models/fields/modulesmodule.php
  administrator/components/com_modules/models/fields/modulesposition.php
Labels: RTC

#22048 [3.9] Capitals in label callback
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha.ini
  administrator/language/en-GB/en-GB.plg_captcha_recaptcha_invisible.ini
Labels: RTC

#22092 Make privacy consent required
  plugins/system/privacyconsent/privacyconsent/privacyconsent.xml
Labels: RTC

#20383 Email Domain Restrictions
  administrator/components/com_admin/models/forms/profile.xml
  administrator/components/com_users/config.xml
  administrator/components/com_users/models/forms/config_domain.xml
  administrator/components/com_users/models/forms/user.xml
  administrator/language/en-GB/en-GB.com_users.ini
  administrator/language/en-GB/en-GB.ini
  administrator/language/en-GB/en-GB.lib_joomla.ini
  components/com_users/models/forms/profile.xml
  components/com_users/models/forms/registration.xml
  language/en-GB/en-GB.com_users.ini
  language/en-GB/en-GB.ini
  language/en-GB/en-GB.lib_joomla.ini
  libraries/src/Form/Rule/EmailRule.php
Labels: Language Change, PR-staging, RTC

#22090 Make sure the extension name is known
  libraries/src/Installer/InstallerScript.php
Labels: PR-3.9-dev

#22073 [4.0] Remove nowrap class
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_banners/tmpl/tracks/default.php
  administrator/components/com_cache/tmpl/cache/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/maps/default.php
  administrator/components/com_finder/tmpl/searches/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_languages/tmpl/installed/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_messages/tmpl/messages/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_search/tmpl/searches/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/template/default_folders.php
  administrator/components/com_templates/tmpl/template/default_tree.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/components/com_users/tmpl/users/modal.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
Labels: PR-4.0-dev

#22015 [4.0] Dropdown menu overflow
  administrator/templates/atum/scss/template-rtl.scss
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
  layouts/joomla/toolbar/dropdown.php
Labels: PR-4.0-dev, RTC

#22067 [4.0] Improve Layout of workflowfield in articles batch
  layouts/joomla/html/batch/workflowstage.php
Labels: PR-4.0-dev, RTC

#22074 [4.0] Fix for #22070 Missing Language Key or Translation in Administrator Module
  administrator/language/en-GB/en-GB.mod_menu.ini
Labels: Language Change, PR-4.0-dev

#21982 [4.0] Atum table head border bottom
  administrator/templates/atum/scss/vendor/bootstrap/_table.scss
Labels: RTC

#21790 [4.0] Move the manifest files to the back end
  administrator/components/com_mailto/mailto.xml
  administrator/components/com_wrapper/wrapper.xml
Labels: PR-4.0-dev

#22088 [3.9][plugin][privacyconsent] - proper quote with dateAdd()
  modules/mod_tags_popular/helper.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-3.9-dev

#22055 [3.9][plugin][actionlogs] - use dateAdd()
  plugins/system/actionlogs/actionlogs.php
Labels: PR-3.9-dev

#22047 [3.9]Update privacyconsent.php to properly 'namespace' the consents state
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-3.9-dev

#21899 [3.9][com_privacy] Make sure we don't send a referrer on the request
  components/com_privacy/controller.php
Labels: PR-3.9-dev

#21500 [3.9] Remove AdminController::display() method overload which disables the inherited functionality from BaseController::display()
  libraries/src/MVC/Controller/AdminController.php
Labels: PR-3.9-dev

#21436 [postgresql] - wrong GROUP BY in multilanguage site
  administrator/components/com_content/models/articles.php
Labels: PR-3.9-dev

#21837 [3.9] Update the type of $displayData for LayoutHelper::render() (and actually fix my original complaint)
  libraries/src/Layout/LayoutHelper.php
Labels: PR-3.9-dev

#21400 [3.9] Change the Label Server Time Zone to Website Time Zone
  administrator/language/en-GB/en-GB.com_config.ini
Labels: Language Change, PR-3.9-dev, RTC

#21897 [3.9] [com_actionlogs] If no actions logs to export no notice
  administrator/components/com_actionlogs/models/fields/extension.php
Labels: PR-3.9-dev

#21978 [4.0] Add workflow to the installation sample data
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/sample_testing.sql
Labels: RTC

#21939 [4.0] Translate workflows via language file
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  administrator/components/com_content/Helper/ContentHelper.php
  administrator/components/com_content/forms/category.xml
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.com_workflow.ini
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  libraries/cms/html/workflowstage.php
  libraries/src/Form/Field/WorkflowstageField.php
Labels: Language Change, PR-4.0-dev, RTC

#21985 [4.0] [a11y] Move search label
  layouts/joomla/searchtools/default/bar.php
Labels: PR-4.0-dev, RTC

#20380 [4.0] Debug bar
  administrator/language/en-GB/en-GB.plg_system_debug.ini
  build/build-modules-js/update.js
  build/media/plg_system_debug/css/debug.css
  build/media/plg_system_debug/widgets/info/widget.css
  build/media/plg_system_debug/widgets/info/widget.js
  build/media/plg_system_debug/widgets/languageErrors/widget.css
  build/media/plg_system_debug/widgets/languageErrors/widget.js
  build/media/plg_system_debug/widgets/languageFiles/widget.css
  build/media/plg_system_debug/widgets/languageFiles/widget.js
  build/media/plg_system_debug/widgets/languageStrings/widget.css
  build/media/plg_system_debug/widgets/languageStrings/widget.js
  build/media/plg_system_debug/widgets/sqlqueries/widget.css
  build/media/plg_system_debug/widgets/sqlqueries/widget.js
  composer.json
  composer.lock
  libraries/src/Language/Language.php
  plugins/system/debug/AbstractDataCollector.php
  plugins/system/debug/DataCollector/InfoCollector.php
  plugins/system/debug/DataCollector/LanguageErrorsCollector.php
  plugins/system/debug/DataCollector/LanguageFilesCollector.php
  plugins/system/debug/DataCollector/LanguageStringsCollector.php
  plugins/system/debug/DataCollector/ProfileCollector.php
  plugins/system/debug/DataCollector/QueryCollector.php
  plugins/system/debug/DataCollector/SessionCollector.php
  plugins/system/debug/DataFormatter.php
  plugins/system/debug/DebugMonitor.php
  plugins/system/debug/debug.php
  plugins/system/debug/debug.xml
Labels: Composer Dependency Changed, Language Change, PR-4.0-dev, RTC

#21817 [4.0] Update the com_content manifest file
  administrator/components/com_content/content.xml
Labels: PR-4.0-dev

#21592 [4.0] Workflow Transitions/Stages
  administrator/components/com_workflow/Model/StagesModel.php
  administrator/components/com_workflow/Model/TransitionsModel.php
  administrator/components/com_workflow/forms/stage.xml
  administrator/components/com_workflow/forms/transition.xml
  administrator/components/com_workflow/tmpl/stage/edit.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transition/edit.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/language/en-GB/en-GB.com_workflow.ini
Labels: Language Change, New Feature Workflow, PR-4.0-dev

#22022 [4.0] Follow-up adding category language to getCategoryRoute()
  components/com_contact/View/Contact/HtmlView.php
  components/com_newsfeeds/View/Category/HtmlView.php
  components/com_newsfeeds/tmpl/category/default_children.php
  modules/mod_articles_categories/tmpl/default_items.php
  modules/mod_articles_category/Helper/ArticlesCategoryHelper.php
  plugins/search/categories/categories.php
Labels: PR-4.0-dev

#22131 Adjusting the order of two strings
  administrator/language/en-GB/en-GB.com_config.ini
Labels: RTC

#22138 [4.0] Add update scripts for manifest file back end move
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-09-12.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-09-12.sql
Labels: PR-4.0-dev

#22143 Improve menus listview 2
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/language/en-GB/en-GB.com_menus.ini
Labels: Language Change, PR-4.0-dev

#22151 [4.0] Remove unused classes
  administrator/components/com_associations/forms/filter_associations.xml
  administrator/components/com_banners/forms/banner.xml
  administrator/components/com_banners/forms/client.xml
  administrator/components/com_banners/forms/filter_banners.xml
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_content/forms/filter_featured.xml
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/forms/group.xml
  administrator/components/com_finder/forms/filter.xml
  administrator/components/com_menus/forms/filter_itemsadmin.xml
  administrator/components/com_menus/forms/item.xml
  administrator/components/com_menus/forms/itemadmin.xml
  administrator/components/com_menus/tmpl/item/edit.php
  administrator/components/com_modules/forms/filter_modulesadmin.xml
  administrator/components/com_modules/forms/module.xml
  administrator/components/com_modules/forms/moduleadmin.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_redirect/forms/link.xml
  administrator/components/com_tags/forms/tag.xml
  administrator/components/com_templates/forms/style.xml
  administrator/components/com_users/forms/filter_users.xml
  administrator/components/com_users/forms/mail.xml
  administrator/components/com_users/forms/note.xml
  components/com_config/forms/modules.xml
  components/com_contact/forms/filter_contacts.xml
  components/com_content/forms/filter_articles.xml
  components/com_fields/forms/filter_fields.xml
  components/com_menus/forms/filter_items.xml
  components/com_modules/forms/filter_modules.xml
  plugins/editors/tinymce/form/setoptions.xml
  plugins/fields/radio/params/radio.xml
  plugins/installer/folderinstaller/tmpl/default.php
  plugins/installer/urlinstaller/tmpl/default.php
  plugins/system/cache/cache.xml
Labels: PR-4.0-dev

#22161 [4.0] Correct spacer in template options
  administrator/components/com_templates/config.xml
  administrator/language/en-GB/en-GB.com_templates.ini
Labels: Language Change, PR-4.0-dev

#21768 [4.0] Language factory
  libraries/src/Factory.php
  libraries/src/Language/CachingLanguageFactory.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageFactory.php
  libraries/src/Language/LanguageFactoryInterface.php
  libraries/src/Service/Provider/Language.php
Labels: PR-4.0-dev, RTC

#22176 [4.0] Fix markup
  administrator/components/com_banners/Field/ClicksField.php
Labels: PR-4.0-dev

#22162 [4.0] Generic string
  administrator/language/en-GB/en-GB.ini
Labels: RTC

#22185 [4.0] Fix missed subform field
  build/build-modules-js/settings.json
Labels: PR-4.0-dev

#22196 Correct length of column "subject" of table "#__privacy_consents" in mysql/3.9.0-2018-05-24.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-24.sql
Labels: RTC

#22189 [com_menus] Menu item type ordering
  administrator/components/com_menus/views/menutypes/view.html.php
Labels: RTC

#22163 Make com_actionlogs accessible for super admins only
  administrator/components/com_actionlogs/actionlogs.php
Labels: RTC

#22155 Fix export action logs error
  administrator/components/com_actionlogs/controllers/actionlogs.php
  administrator/components/com_actionlogs/views/actionlogs/tmpl/default.php
Labels: PR-staging, RTC

#22107 [staging] Fix overrides usability
  administrator/components/com_languages/layouts/joomla/searchtools/default/bar.php
  administrator/components/com_languages/models/fields/languageclient.php
  administrator/components/com_languages/models/forms/filter_overrides.xml
  administrator/components/com_languages/models/overrides.php
  administrator/components/com_languages/views/override/view.html.php
  administrator/components/com_languages/views/overrides/view.html.php
  administrator/language/en-GB/en-GB.com_languages.ini
Labels: Language Change, PR-staging, RTC

#17769 [com_fields] Support categories with a section for field categories
  administrator/components/com_fields/models/field.php
  administrator/components/com_fields/models/fields.php
  administrator/components/com_fields/views/fields/tmpl/default.php
  libraries/src/Categories/Categories.php
Labels: PR-staging, RTC

#22204 [4.0] Fix npm run test and use it for done
  .drone.yml
  package.json
Labels: PR-4.0-dev, Unit/System Tests

#22049 [4.0] Draggable
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_users/tmpl/levels/default.php
Labels: PR-4.0-dev

#22201 [postgresql] Fix SQL errors in schema updates which make update from 3.8.12 to staging fail
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-05.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-02.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-07-09.sql
Labels: PR-staging

#21766 [4.0] Generate the classmap from the manifest files
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2016-19-03.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-09.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2016-10-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-09.sql
  administrator/components/com_media/media.xml
  components/com_media/src/Dispatcher/Dispatcher.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  libraries/namespacemap.php
  libraries/src/Component/ComponentHelper.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Installer.php
  plugins/filesystem/local/local.php
  plugins/filesystem/local/local.xml
Labels: PR-4.0-dev

#21925 [com_media] Correct error strings
  administrator/language/en-GB/en-GB.com_media.ini
Labels: Language Change, PR-staging

#22190 [4.0] Users and User groups: Separate columns for group and permissions button
  administrator/components/com_users/config.xml
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/language/en-GB/en-GB.com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#22218 Missing language string in plugin
  administrator/language/en-GB/en-GB.plg_fields_repeatable.ini
  administrator/language/en-GB/en-GB.plg_fields_repeatable.sys.ini
Labels: Language Change, PR-staging

#22186 [4.0] Make Notification Dropdown viewable.
  administrator/templates/atum/scss/blocks/_header.scss
Labels: PR-4.0-dev, RTC

#22084 [4.0] Add the possibility to have a custom login logo
  administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/blocks/_login.scss
  administrator/templates/atum/templateDetails.xml
Labels: Language Change, PR-4.0-dev

#22222 Missing strings in plugin_confirmconsent
  administrator/language/en-GB/en-GB.plg_content_confirmconsent.ini
Labels: PR-staging

#22224 [com_actionlogs] Capitalize/simplify labels
  administrator/language/en-GB/en-GB.com_actionlogs.ini
Labels: Language Change, PR-staging

#22230 [4.0] minified file overwritten
  build/build-modules-js/settings.json
Labels: PR-4.0-dev

#22206 [postgresql] fix sequence start value
  installation/sql/postgresql/joomla.sql
Labels: PR-staging, RTC

#22235 Fix constants and ordering for com_actionslogs ini file
  administrator/components/com_actionlogs/config.xml
  administrator/language/en-GB/en-GB.com_actionlogs.ini
Labels: Language Change, PR-staging

#22042 [4.0] Finder: Replacing iconv() with mb_convert_encoding()
  administrator/components/com_finder/helpers/indexer/parser/html.php
Labels: PR-4.0-dev

#22252 Vote plugin
  plugins/content/vote/tmpl/vote.php
Labels: PR-4.0-dev

#20693 [4.0] Introduce category factory
  administrator/components/com_banners/Extension/BannersComponent.php
  administrator/components/com_banners/services/provider.php
  administrator/components/com_categories/Model/CategoriesModel.php
  administrator/components/com_categories/Model/CategoryModel.php
  administrator/components/com_content/Extension/ContentComponent.php
  administrator/components/com_content/services/provider.php
  administrator/components/com_fields/Model/FieldModel.php
  administrator/components/com_tags/Model/TagsModel.php
  libraries/src/Categories/Categories.php
  libraries/src/Categories/CategoryFactory.php
  libraries/src/Categories/CategoryFactoryInterface.php
  libraries/src/Categories/CategoryInterface.php
  libraries/src/Categories/CategoryServiceInterface.php
  libraries/src/Categories/CategoryServiceTrait.php
  libraries/src/Extension/LegacyComponent.php
  libraries/src/Extension/Service/Provider/CategoryFactory.php
Labels: PR-4.0-dev

#21865 [4.0] [a11y] Sampledata progress bar
  build/media_src/mod_sampledata/js/sampledata-process.es6.js
Labels: PR-4.0-dev

#22268 [4.0] Migrate com_categories to services
  administrator/components/com_categories/Extension/CategoriesComponent.php
  administrator/components/com_categories/Helper/CategoryAssociationHelper.php
  administrator/components/com_categories/Service/HTML/AdministratorService.php
  administrator/components/com_categories/dispatcher.php
  administrator/components/com_categories/helpers/categories.php
  administrator/components/com_categories/services/provider.php
  administrator/components/com_categories/tmpl/categories/default.php
  components/com_contact/helpers/association.php
  components/com_content/Helper/AssociationHelper.php
  components/com_newsfeeds/helpers/association.php
Labels: PR-4.0-dev

#21426 [4.0] Take results outside the form tag in Archives page
  components/com_content/tmpl/archive/default.php
Labels: PR-4.0-dev, RTC

#22281 [4.0] Remove deprecated profiler global
  administrator/includes/framework.php
  includes/framework.php
Labels: Documentation Required, PR-4.0-dev

#22309 Fix typo in comments
  administrator/components/com_languages/models/installed.php
  libraries/joomla/database/importer/mysqli.php
  libraries/joomla/database/importer/pdomysql.php
Labels: PR-staging, RTC

#22307 [4.0] Remove not needed jQuery imports as the JS files are vanilla JS
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_banners/tmpl/banner/edit.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_finder/tmpl/indexer/default.php
  administrator/components/com_languages/tmpl/override/edit.php
  administrator/components/com_menus/tmpl/item/edit_modules.php
  components/com_contact/layouts/joomla/form/renderfield.php
  layouts/joomla/edit/associations.php
Labels: Documentation Required, PR-4.0-dev

#22123 [4.0] Implement the workflow into the multilang sample data
  administrator/language/en-GB/en-GB.plg_sampledata_multilang.ini
  plugins/sampledata/multilang/multilang.php
Labels: Language Change, PR-4.0-dev

#22319 Show the full sub-tree of menu-items when filtering by a parent menu item, while respecting the max levels filter
  administrator/components/com_menus/models/items.php
Labels: PR-staging, RTC

#22288 [com_content] Deprecate getAuthors()
  administrator/components/com_content/models/articles.php
  administrator/components/com_content/views/articles/view.html.php
  administrator/components/com_content/views/featured/view.html.php
Labels: RTC

#22285 [com_privacy] xml header encoding utf-8
  administrator/components/com_privacy/helpers/privacy.php
Labels: PR-staging, RTC

#22277 [com_admin] Simplify profile form layout. Fixes #22262
  administrator/components/com_admin/views/profile/tmpl/edit.php
Labels: RTC

#22276 Add 'btn-small' to mod-stats-admin buttons
  administrator/modules/mod_stats_admin/tmpl/default.php
Labels: PR-staging, RTC

#22275 [privacy] Align columns in 'Total Request Count'
  administrator/components/com_privacy/views/dashboard/tmpl/default.php
  administrator/modules/mod_privacy_dashboard/tmpl/default.php
Labels: PR-staging, RTC

#22274 [privacy] Style com-privacy 'wells' to match com-cpanel
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/less/pages/_com_privacy.less
  administrator/templates/isis/less/template.less
Labels: RTC

#22272 Module preview styling
  libraries/src/Helper/ModuleHelper.php
  templates/system/html/modules.php
Labels: PR-staging, RTC

#22253 [Privacy XML export] standardized convention for domain (Redo #22240)
  plugins/privacy/actionlogs/actionlogs.php
  plugins/privacy/contact/contact.php
  plugins/privacy/content/content.php
  plugins/privacy/message/message.php
  plugins/privacy/user/user.php
Labels: PR-staging, RTC

#22250 [3.9] action logs notifications. showon attribute for field logs_notification_extensions
  plugins/system/actionlogs/forms/actionlogs.xml
Labels: PR-staging, RTC

#22248 [com_templates] Support plugin layout overrides
  administrator/components/com_templates/models/template.php
  administrator/components/com_templates/views/template/tmpl/default.php
  administrator/language/en-GB/en-GB.com_templates.ini
Labels: Language Change, PR-staging, RTC

#22246 Tags view - remove "PHP Warning: Creating default object from empty value"
  components/com_tags/views/tags/view.html.php
Labels: RTC

#22244 Only show ip address sort options in actions log if IP logging is enabled
  administrator/components/com_actionlogs/models/actionlogs.php
  administrator/components/com_actionlogs/models/forms/filter_actionlogs.xml
Labels: PR-staging, RTC

#22200 [mysql] Correct position of column "state" in table "#__privacy_consents" in file "3.9.0-2018-08-12.sql"
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-08-12.sql
Labels: RTC

#22157 [plg_actionlog_joomla] - reset & remind
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
  components/com_users/models/remind.php
  plugins/actionlog/joomla/joomla.php
Labels: Language Change, PR-staging, RTC

#20677 Add trigger events onBeforeRespond and onAfterRespond during redirection
  libraries/src/Application/WebApplication.php
Labels: PR-staging, RTC

#19466 Implement initial port support for PostgreSQL driver
  libraries/joomla/database/driver/postgresql.php
Labels: PR-staging, RTC

#17552 Create possibility for nested subforms
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable-table/section.php
  layouts/joomla/form/field/subform/repeatable.php
  layouts/joomla/form/field/subform/repeatable/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable/section.php
  libraries/joomla/form/fields/subform.php
  media/system/js/subform-repeatable-uncompressed.js
  media/system/js/subform-repeatable.js
  tests/javascript/subform-repeatable/fixtures/fixture.html
Labels: New Feature, PR-staging, RTC, Unit/System Tests

#22313 [3.9] Empty lines in log, non functional defer option
  libraries/src/Log/Logger/FormattedtextLogger.php
Labels: RTC

#22333 [Fix] Missing error string in frontend
  language/en-GB/en-GB.ini
Labels: Language Change, PR-staging

#22326 [4.0] Add icons to conditions in workflow-stages
  administrator/components/com_workflow/tmpl/stages/default.php
Labels: RTC

#22320 [4.0] Fix broken stage filter
  administrator/components/com_content/forms/filter_articles.xml
  administrator/components/com_content/forms/filter_featured.xml
Labels: RTC

#22323 [4.0] Fix sorting transitions list
  administrator/components/com_workflow/tmpl/transitions/default.php
Labels: RTC

#22308 [4.0] Remove jQuery from modal fields JS file
  administrator/components/com_categories/Field/Modal/CategoryField.php
  administrator/components/com_contact/Field/Modal/ContactField.php
  administrator/components/com_content/Field/Modal/ArticleField.php
  administrator/components/com_content/View/Article/HtmlView.php
  administrator/components/com_menus/Field/Modal/MenuField.php
  administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
  build/media/system/js/fields/modal-fields.js
Labels: PR-4.0-dev

#22301 [4.0] Remove the deprecated code in the MultilangstatusHelper class
  administrator/components/com_languages/Helper/MultilangstatusHelper.php
Labels: Documentation Required, PR-4.0-dev

#22337 Add Yandex search engine to the robots list
  libraries/src/Environment/Browser.php
Labels: PR-staging

#22302 [4.0] Remove the deprecated code in the ItemsController class
  administrator/components/com_menus/Controller/ItemsController.php
Labels: Documentation Required, PR-4.0-dev

#22299 [4.0] Remove the deprecated code in the CheckinModel class
  administrator/components/com_checkin/Model/CheckinModel.php
Labels: Documentation Required, PR-4.0-dev

#22290 [4.0] Remove the deprecated UserWrapper class
  libraries/classmap.php
  libraries/src/User/User.php
  libraries/src/User/UserWrapper.php
Labels: Documentation Required, PR-4.0-dev

#22292 [4.0] Remove the deprecated code in the JHtmlSearchtools class
  libraries/cms/html/searchtools.php
Labels: Documentation Required, PR-4.0-dev

#22289 [4.0] Remove the deprecated code in the Pagination class
  libraries/src/Pagination/Pagination.php
Labels: Documentation Required, PR-4.0-dev

#22293 [4.0] Remove the deprecated code in the InstalledModel class
  administrator/components/com_languages/Model/InstalledModel.php
Labels: Documentation Required, PR-4.0-dev

#22294 [4.0] Remove the deprecated code in the JHtmlJGrid class
  libraries/cms/html/jgrid.php
Labels: Documentation Required, PR-4.0-dev

#22341 [4.0] Fix multiple Editor instances
  libraries/src/Editor/Editor.php
Labels: PR-4.0-dev
