Repository joomla/joomla-cms, pull requests merged in 2018-06, with the labels that each got.

#13523 Be able to use unique language strings for the rules field
  administrator/language/en-GB/en-GB.com_banners.ini
  administrator/language/en-GB/en-GB.com_cache.ini
  administrator/language/en-GB/en-GB.com_checkin.ini
  administrator/language/en-GB/en-GB.com_config.ini
  administrator/language/en-GB/en-GB.com_contact.ini
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.com_installer.ini
  administrator/language/en-GB/en-GB.com_languages.ini
  administrator/language/en-GB/en-GB.com_media.ini
  administrator/language/en-GB/en-GB.com_menus.ini
  administrator/language/en-GB/en-GB.com_messages.ini
  administrator/language/en-GB/en-GB.com_modules.ini
  administrator/language/en-GB/en-GB.com_newsfeeds.ini
  administrator/language/en-GB/en-GB.com_plugins.ini
  administrator/language/en-GB/en-GB.com_redirect.ini
  administrator/language/en-GB/en-GB.com_templates.ini
  administrator/language/en-GB/en-GB.com_users.ini
  administrator/language/en-GB/en-GB.com_weblinks.ini
  libraries/joomla/form/fields/rules.php
Labels: Language Change, PR-3.10-dev, RTC

#20451 Deprecate JHtmlBehavior::caption
  libraries/cms/html/behavior.php
Labels: PR-3.9-dev, RTC

#19134 [new feature] Article notes field
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2017-12-22.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2017-12-22.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2017-12-22.sql
  administrator/components/com_content/models/articles.php
  administrator/components/com_content/models/featured.php
  administrator/components/com_content/models/forms/article.xml
  administrator/components/com_content/views/articles/tmpl/default.php
  administrator/components/com_content/views/articles/tmpl/modal.php
  administrator/components/com_content/views/featured/tmpl/default.php
  administrator/language/en-GB/en-GB.com_content.ini
  components/com_content/models/forms/article.xml
  components/com_content/views/form/tmpl/edit.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
  language/en-GB/en-GB.com_content.ini
  templates/beez3/html/com_content/form/edit.php
Labels: Language Change, PR-3.9-dev, PR-staging, RTC

#18757 Add additional check that view exists before proceeding
  components/com_content/helpers/legacyrouter.php
Labels: PR-staging, RTC

#18955 [IMP] Adding filtering by element in the plugins Manager (#18868)
  administrator/components/com_plugins/helpers/plugins.php
  administrator/components/com_plugins/models/fields/pluginelement.php
  administrator/components/com_plugins/models/forms/filter_plugins.xml
  administrator/components/com_plugins/models/plugins.php
  administrator/language/en-GB/en-GB.com_plugins.ini
Labels: Language Change, PR-staging, RTC

#18571 Adding an alternate layout parameter to custom fields
  administrator/components/com_fields/models/fields/fieldlayout.php
  administrator/components/com_fields/models/forms/field.xml
  administrator/language/en-GB/en-GB.com_fields.ini
  components/com_contact/layouts/fields/render.php
  components/com_fields/layouts/fields/render.php
  plugins/content/fields/fields.php
Labels: Language Change, New Feature, PR-3.9-dev, RTC

#20649 [4.0] Register the correct templates component class in the container
  administrator/components/com_modules/Service/HTML/Modules.php
  administrator/components/com_modules/tmpl/module/edit_positions.php
  administrator/components/com_templates/helpers/template.php
  administrator/components/com_templates/helpers/templates.php
  administrator/components/com_templates/services/provider.php
  administrator/components/com_templates/tmpl/template/default_description.php
Labels: PR-4.0-dev

#20639 [4.0][a11y] Focus highlighting
  administrator/templates/atum/css/bootstrap.css
  administrator/templates/atum/css/template-rtl.css
  administrator/templates/atum/css/template-rtl.min.css
  administrator/templates/atum/css/template.css
  administrator/templates/atum/css/template.min.css
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/template.scss
  templates/cassiopeia/css/template.css
  templates/cassiopeia/css/template.min.css
  templates/cassiopeia/scss/template.scss
Labels: PR-4.0-dev

#20652 [4.0] Template colour field
  templates/cassiopeia/templateDetails.xml
Labels: PR-4.0-dev

#19830 [4.0]Introduce modals API
  administrator/components/com_banners/tmpl/download/default.php
  administrator/components/com_fields/Field/Modal/FieldField.php
  administrator/components/com_redirect/layouts/toolbar/batch.php
  administrator/components/com_users/tmpl/users/modal.php
  build/webcomponents/js/field-media/field-media.js
  build/webcomponents/js/field-user/field-user.js
  layouts/joomla/form/field/contenthistory.php
  layouts/joomla/toolbar/batch.php
  layouts/joomla/toolbar/modal.php
  layouts/joomla/toolbar/versions.php
  media/com_associations/js/modal-associations.js
  media/com_associations/js/modal-associations.min.js
  media/com_finder/js/indexer.js
  media/com_finder/js/indexer.min.js
  media/com_menus/js/admin-item-modal.js
  media/com_menus/js/admin-item-modal.min.js
  media/com_menus/js/admin-menus-default.js
  media/com_menus/js/admin-menus-default.min.js
  media/com_modules/js/admin-module-edit.js
  media/com_modules/js/admin-module-edit.min.js
  media/legacy/js/bootstrap-init.js
  media/legacy/js/bootstrap-init.min.js
  media/system/js/core.js
  media/system/js/core.min.js
  media/system/js/fields/modal-fields.js
  media/system/js/fields/modal-fields.min.js
  media/system/webcomponents/js/joomla-editor-none-es5.min.js
  media/system/webcomponents/js/joomla-field-media-es5.js
  media/system/webcomponents/js/joomla-field-media-es5.min.js
  media/system/webcomponents/js/joomla-field-media.js
  media/system/webcomponents/js/joomla-field-media.min.js
  media/system/webcomponents/js/joomla-field-user-es5.js
  media/system/webcomponents/js/joomla-field-user-es5.min.js
  media/system/webcomponents/js/joomla-field-user.js
  media/system/webcomponents/js/joomla-field-user.min.js
Labels: PR-4.0-dev

#20655 Default installation value in configuration.php-dist
  installation/configuration.php-dist
Labels: PR-staging

#20654 [4.0] Installation license etc
  installation/COPYRIGHT
  installation/CREDITS
  installation/LICENSE.txt
  installation/LICENSES
Labels: PR-4.0-dev

#20636 CodeMirror updated to 5.38.0
  media/editors/codemirror/addon/dialog/dialog.js
  media/editors/codemirror/addon/dialog/dialog.min.js
  media/editors/codemirror/addon/hint/show-hint.js
  media/editors/codemirror/addon/hint/show-hint.min.js
  media/editors/codemirror/addon/lint/json-lint.js
  media/editors/codemirror/addon/lint/json-lint.min.js
  media/editors/codemirror/lib/codemirror.js
  media/editors/codemirror/lib/codemirror.min.js
  media/editors/codemirror/mode/javascript/javascript.js
  media/editors/codemirror/mode/javascript/javascript.min.js
  media/editors/codemirror/mode/markdown/markdown.js
  media/editors/codemirror/mode/markdown/markdown.min.js
  media/editors/codemirror/theme/darcula.css
  media/editors/codemirror/theme/lesser-dark.css
  media/editors/codemirror/theme/monokai.css
  plugins/editors/codemirror/codemirror.xml
Labels: PR-staging, RTC

#20147 [4.0] [mod-login] Adopt BEM HTML class naming
  modules/mod_login/tmpl/default.php
  modules/mod_login/tmpl/default_logout.php
Labels: PR-4.0-dev

#20620 [4.0] Change com_config to services
  administrator/components/com_config/dispatcher.php
  administrator/components/com_config/services/provider.php
  administrator/components/com_templates/Controller/StyleController.php
  components/com_config/Controller/ConfigController.php
  components/com_config/Controller/TemplatesController.php
  components/com_config/Dispatcher/Dispatcher.php
  components/com_config/tmpl/config/default.php
Labels: PR-4.0-dev

#20659 [4.0] Fix template preview JS error
  media/system/js/multiselect.js
  media/system/js/multiselect.min.js
Labels: PR-4.0-dev, RTC

#20663 [fix] Error decoding JSON data: Syntax error
  libraries/src/User/User.php
  tests/unit/stubs/database/jos_users.csv
  tests/unit/suites/libraries/joomla/user/JUserTest.php
Labels: PR-staging, Unit/System Tests

#20675 Don't try to json_decode() a null value
  administrator/components/com_fields/models/field.php
  composer.lock
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/registry/src/Format/Json.php
Labels: Composer Dependency Changed, PR-staging, RTC

#20680 Joomla\CMS\Categories\Categories fix
  libraries/src/Categories/Categories.php
Labels: PR-staging

#20676 [4.0] Fix multiple sampledata
  media/mod_sampledata/js/sampledata-process.js
  media/mod_sampledata/js/sampledata-process.min.js
Labels: PR-4.0-dev, PR-staging

#20688 [4.0] Removing obsolete azure update file
  administrator/components/com_admin/sql/updates/sqlazure/3.8.4-2018-01-16.sql
Labels: PR-4.0-dev, RTC

#20690 [4.0] Httpheader language
  administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
Labels: Language Change, PR-4.0-dev, RTC

#20192 [4.0] Multilingual: Mod_languages - Adding the Full Languages Names parameter to dropdown display
  language/en-GB/en-GB.mod_languages.ini
  modules/mod_languages/mod_languages.xml
  modules/mod_languages/tmpl/default.php
Labels: Language Change, PR-4.0-dev, RTC

#20694 [4.0] Grammar in lang string
  language/en-GB/en-GB.mod_languages.ini
Labels: PR-4.0-dev, RTC

#19893 [4.0] Remove deprecated cache handlers, cleanup cache/session config related to deprecations
  administrator/components/com_admin/Model/SysinfoModel.php
  administrator/components/com_config/forms/application.xml
  administrator/components/com_joomlaupdate/restore_finalisation.php
  administrator/language/en-GB/en-GB.lib_joomla.ini
  build/travis/phpenv/apcu-7.2.ini
  installation/configuration.php-dist
  language/en-GB/en-GB.lib_joomla.ini
  libraries/classmap.php
  libraries/src/Cache/Storage/ApcStorage.php
  libraries/src/Cache/Storage/MemcacheStorage.php
  libraries/src/Cache/Storage/XcacheStorage.php
  phpunit.xml.dist
Labels: Language Change, PR-4.0-dev, Unit/System Tests

#20653 [4.0] Cancel button class
  components/com_content/tmpl/form/edit.php
  components/com_mailto/tmpl/mailto/default.php
  components/com_users/tmpl/profile/edit.php
  components/com_users/tmpl/registration/default.php
Labels: PR-4.0-dev

#20695 [4.0] Module description not a manual
  language/en-GB/en-GB.mod_languages.ini
  language/en-GB/en-GB.mod_languages.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#20417 [4.0] Allow Preview to load in new _blank instead of modal
  libraries/src/Toolbar/CoreButtonsTrait.php
Labels: PR-4.0-dev, RTC

#20668 [4.0] Refactor component router of com_finder
  components/com_finder/router.php
Labels: RTC

#20611 [4.0] Change com_banners to services
  administrator/components/com_banners/Extension/BannersComponent.php
  administrator/components/com_banners/Helper/BannersHelper.php
  administrator/components/com_banners/Service/Html/Banner.php
  administrator/components/com_banners/dispatcher.php
  administrator/components/com_banners/helpers/banners.php
  administrator/components/com_banners/services/provider.php
  administrator/components/com_content/Helper/ContentHelper.php
  administrator/components/com_content/helpers/content.php
  components/com_banners/Service/Category.php
  components/com_banners/dispatcher.php
  libraries/src/Categories/CategoriesServiceTrait.php
  libraries/src/Dispatcher/DispatcherFactoryInterface.php
  modules/mod_banners/Helper/ModBannersHelper.php
  modules/mod_banners/mod_banners.php
Labels: PR-4.0-dev

#20185 [4.0] Removing artificial sharding from com_finder
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-04-14.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-04-14.sql
  administrator/components/com_finder/Model/IndexModel.php
  administrator/components/com_finder/helpers/indexer/driver/mysql.php
  administrator/components/com_finder/helpers/indexer/driver/postgresql.php
  administrator/components/com_finder/helpers/indexer/indexer.php
  administrator/components/com_finder/sql/install.mysql.sql
  administrator/components/com_finder/sql/install.postgresql.sql
  administrator/components/com_finder/sql/uninstall.mysql.sql
  administrator/components/com_finder/sql/uninstall.postgresql.sql
  components/com_finder/Model/SearchModel.php
  components/com_finder/View/Search/HtmlView.php
  components/com_finder/helpers/html/filter.php
  components/com_finder/helpers/html/query.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev, RTC

#20717 [Newsfeeds] Use item link instead of guid.
  administrator/modules/mod_feed/tmpl/default.php
  components/com_newsfeeds/views/newsfeed/tmpl/default.php
  libraries/src/Feed/Parser/RssParser.php
  modules/mod_feed/tmpl/default.php
Labels: PR-staging, RTC

#20708 Verb wrong tense
  administrator/language/en-GB/en-GB.com_media.ini
Labels: Language Change, PR-staging, RTC

#20706 Make the fieldname required as the field otherwise doesn't work
  plugins/fields/repeatable/params/repeatable.xml
Labels: RTC

#20672 Replace 2 queries by one in UCMType
  libraries/src/UCM/UCMType.php
Labels: PR-staging, RTC

#20671 JTableAsset::loadByName(): replace two sql queries by one
  libraries/src/Table/Asset.php
Labels: PR-staging, RTC

#20664 Display 404 page when tracking clicks of a non-existing banner
  components/com_banners/models/banner.php
Labels: PR-staging, RTC

#20591 Image CSS style strings
  administrator/language/en-GB/en-GB.com_menus.ini
Labels: RTC

#20590 Fix stale session data wrongly overriding configuration file when editing global configuration
  administrator/components/com_config/controller/application/save.php
Labels: PR-staging, RTC

#18471 [com_menus] - fix php warning
  administrator/components/com_menus/models/fields/menuitembytype.php
Labels: RTC

#18258 Enhance Content - Contact plugin
  administrator/language/en-GB/en-GB.plg_content_contact.ini
  plugins/content/contact/contact.php
  plugins/content/contact/contact.xml
Labels: Language Change, PR-staging, RTC

#20702 [4.0] Correct css classes of mod_menu and the Cassiopeia template's css for menu at the "menu" module position
  modules/mod_menu/tmpl/default.php
  templates/cassiopeia/css/template.css
  templates/cassiopeia/css/template.min.css
  templates/cassiopeia/scss/blocks/_global.scss
  templates/cassiopeia/scss/blocks/_header.scss
Labels: PR-4.0-dev

#20718 [4.0] HTML class naming standard [frontend modules]
  modules/mod_articles_archive/tmpl/default.php
  modules/mod_articles_categories/tmpl/default.php
  modules/mod_articles_category/tmpl/default.php
  modules/mod_articles_latest/tmpl/default.php
  modules/mod_articles_news/tmpl/default.php
  modules/mod_articles_news/tmpl/horizontal.php
  modules/mod_articles_news/tmpl/vertical.php
  modules/mod_banners/tmpl/default.php
  modules/mod_breadcrumbs/tmpl/default.php
  modules/mod_custom/tmpl/default.php
  modules/mod_finder/tmpl/default.php
  modules/mod_footer/tmpl/default.php
  modules/mod_languages/tmpl/default.php
  modules/mod_menu/tmpl/default.php
  modules/mod_menu/tmpl/default_heading.php
  modules/mod_menu/tmpl/default_separator.php
  modules/mod_random_image/tmpl/default.php
  modules/mod_related_items/tmpl/default.php
  modules/mod_search/tmpl/default.php
  modules/mod_stats/tmpl/default.php
  modules/mod_syndicate/tmpl/default.php
  modules/mod_tags_popular/tmpl/cloud.php
  modules/mod_tags_popular/tmpl/default.php
  modules/mod_tags_similar/tmpl/default.php
  modules/mod_users_latest/tmpl/default.php
  modules/mod_whosonline/tmpl/default.php
  modules/mod_whosonline/tmpl/disabled.php
  modules/mod_wrapper/tmpl/default.php
Labels: PR-4.0-dev

#20726 [4.0] Rename label for menu type
  administrator/language/en-GB/en-GB.com_menus.ini
Labels: Language Change, PR-4.0-dev, RTC

#20650 [4.0][RFC] Custom Element: Joomla! Toolbar button
  build/webcomponents/js/toolbar-button/toolbar-button.js
  layouts/joomla/toolbar/standard.php
  libraries/src/Toolbar/Button/StandardButton.php
  libraries/src/Toolbar/CoreButtonsTrait.php
  media/system/js/core.js
  media/system/js/core.min.js
  media/system/webcomponents/js/joomla-toolbar-button-es5.js
  media/system/webcomponents/js/joomla-toolbar-button-es5.min.js
  media/system/webcomponents/js/joomla-toolbar-button.js
  media/system/webcomponents/js/joomla-toolbar-button.min.js
  package.json
Labels: PR-4.0-dev, Request for Comment

#20711 [4.0] New feature. Adding a multilingual sample data plugin
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-11.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-11.sql
  administrator/language/en-GB/en-GB.plg_sampledata_multilang.ini
  administrator/language/en-GB/en-GB.plg_sampledata_multilang.sys.ini
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  plugins/sampledata/multilang/multilang.php
  plugins/sampledata/multilang/multilang.xml
Labels: Language Change, PR-4.0-dev

#20751 Singular not plural
  administrator/language/en-GB/en-GB.mod_sampledata.ini
Labels: Language Change, PR-staging

#20755 [4.0] [a11y] Incorrect aria role
  layouts/joomla/searchtools/default/bar.php
Labels: PR-4.0-dev

#20328 [4.0] Replace "label" classes with the new "badge" ones
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
  components/com_contact/tmpl/category/default_items.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/featured/default_items.php
  components/com_content/tmpl/article/default.php
  components/com_content/tmpl/category/default_articles.php
  components/com_content/tmpl/featured/default_item.php
  components/com_newsfeeds/tmpl/category/default_items.php
  components/com_newsfeeds/tmpl/newsfeed/default.php
  layouts/joomla/content/tags.php
  media/com_joomlaupdate/js/default.js
  media/com_joomlaupdate/js/default.min.js
  modules/mod_languages/tmpl/default.php
  plugins/editors/tinymce/form/setoptions.xml
  plugins/system/debug/debug.php
Labels: Language Change, PR-4.0-dev

#20763 [4.0] Installer cleanup
  installation/forms/setup.xml
Labels: PR-4.0-dev

#20648 [com_tags] Image caption in Tags view
  components/com_tags/views/tags/tmpl/default_items.php
Labels: RTC

#20632 [4.0] No size for readonly number fields
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
Labels: PR-4.0-dev

#20573 [4.0] Preventing weight in Finder from locale formating
  administrator/components/com_finder/helpers/indexer/indexer.php
Labels: PR-4.0-dev

#20766 [4.0] wrong language code
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#20745 Put all build packages in one directory
  build/build.php
Labels: PR-staging

#20723 [com_tags] Tagged item link in feed
  components/com_tags/models/tag.php
  components/com_tags/views/tag/tmpl/default_items.php
  components/com_tags/views/tag/tmpl/list_items.php
  components/com_tags/views/tag/view.feed.php
Labels: RTC

#20730 [mod_tags_similar] Link cleanup
  modules/mod_tags_similar/helper.php
  modules/mod_tags_similar/tmpl/default.php
Labels: PR-staging, RTC

#20772 Com_finder meta data
  components/com_finder/views/search/view.html.php
Labels: PR-staging, RTC

#20769 Add UTF-8 encoding to phpcs in .drone.yml
  .drone.yml
Labels: PR-staging, Unit/System Tests

#20744 [4.0] Sample Data not available message
  administrator/language/en-GB/en-GB.mod_sampledata.ini
  administrator/modules/mod_sampledata/tmpl/default.php
Labels: Language Change, PR-4.0-dev, RTC

#17537 [4.0] Fix database for Extensions - GSoC Expand Extensions Manager
  administrator/components/com_installer/Controller/DatabaseController.php
  administrator/components/com_installer/Helper/InstallerHelper.php
  administrator/components/com_installer/Model/DatabaseModel.php
  administrator/components/com_installer/View/Database/HtmlView.php
  administrator/components/com_installer/forms/filter_database.xml
  administrator/components/com_installer/tmpl/database/default.php
  administrator/language/en-GB/en-GB.com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#20752 [4.0] Remove unused strings
  administrator/language/en-GB/en-GB.com_banners.ini
  administrator/language/en-GB/en-GB.com_categories.ini
  administrator/language/en-GB/en-GB.com_checkin.ini
  administrator/language/en-GB/en-GB.com_contact.ini
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.com_fields.ini
  administrator/language/en-GB/en-GB.com_finder.ini
  administrator/language/en-GB/en-GB.com_menus.ini
  administrator/language/en-GB/en-GB.com_modules.ini
  administrator/language/en-GB/en-GB.com_newsfeeds.ini
  administrator/language/en-GB/en-GB.com_plugins.ini
  administrator/language/en-GB/en-GB.com_tags.ini
Labels: Language Change, PR-4.0-dev, RTC

#20777 [4.0] Toolbar button CE: Fix Disabled state when nothing is checked in a list. Fix #20756
  build/webcomponents/js/toolbar-button/toolbar-button.js
  media/system/webcomponents/js/joomla-toolbar-button-es5.js
  media/system/webcomponents/js/joomla-toolbar-button-es5.min.js
  media/system/webcomponents/js/joomla-toolbar-button.js
  media/system/webcomponents/js/joomla-toolbar-button.min.js
Labels: RTC

#20779 [4.0] setMetaData
  components/com_contact/View/Contact/HtmlView.php
  components/com_contact/View/Featured/HtmlView.php
  components/com_content/View/Article/HtmlView.php
  components/com_content/View/Category/HtmlView.php
  components/com_content/View/Form/HtmlView.php
  components/com_newsfeeds/View/Newsfeed/HtmlView.php
  components/com_search/View/Search/HtmlView.php
  components/com_tags/View/Tag/HtmlView.php
  components/com_users/View/Remind/HtmlView.php
  libraries/src/MVC/View/CategoriesView.php
  libraries/src/MVC/View/CategoryView.php
Labels: RTC

#20765 [4.0] Installation unused strings
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
Labels: Language Change, PR-4.0-dev, RTC

#20732 Login to view the article redirect fix
  components/com_content/views/article/view.html.php
Labels: RTC

#20743 Mouse over edit - rename
  administrator/language/en-GB/en-GB.com_config.ini
Labels: RTC

#20746 Better mode autoloading.
  plugins/editors/codemirror/layouts/editors/codemirror/init.php
Labels: RTC

#20713 Respect access of editor plugin inside profile form
  administrator/components/com_admin/models/forms/profile.xml
  components/com_users/models/forms/frontend.xml
  libraries/joomla/form/fields/plugins.php
Labels: PR-staging, RTC

#20687 [mod_articles_latest] Option for choose an specific author(s)
  language/en-GB/en-GB.mod_articles_latest.ini
  modules/mod_articles_latest/helper.php
  modules/mod_articles_latest/mod_articles_latest.xml
Labels: Language Change, PR-staging, RTC

#20660 Fix jQuery XSS Issue
  media/jui/js/jquery.js
  media/jui/js/jquery.min.js
Labels: PR-3.9-dev, RTC

#20714 [3.9] Deprecate JAdapter classes
  libraries/joomla/base/adapter.php
  libraries/joomla/base/adapterinstance.php
Labels: RTC

#20646 [3.9] Make sure the extension install works as expected
  administrator/components/com_installer/models/install.php
  administrator/components/com_installer/models/update.php
  administrator/language/en-GB/en-GB.com_installer.ini
  libraries/src/Installer/InstallerHelper.php
Labels: Language Change, PR-3.9-dev, RTC

#20644 [3.9] Make sure the update hash checker produces the correct result
  administrator/components/com_joomlaupdate/controllers/update.php
  administrator/components/com_joomlaupdate/models/default.php
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-3.9-dev, RTC

#20616 Additional Escaping Of Paths In com_media
  administrator/components/com_media/views/medialist/tmpl/details_img.php
  administrator/components/com_media/views/medialist/tmpl/details_imgs.php
  administrator/components/com_media/views/medialist/tmpl/thumbs_imgs.php
  administrator/templates/isis/html/com_media/imageslist/default_folder.php
  administrator/templates/isis/html/com_media/medialist/thumbs_imgs.php
  templates/protostar/html/com_media/imageslist/default_folder.php
Labels: PR-staging, RTC

#20601 [com_tags] Images in Tagged Items view
  components/com_tags/views/tag/view.html.php
Labels: RTC

#20430 [com_contenthistory] - fix for not delete keep forever items
  administrator/components/com_contenthistory/models/history.php
Labels: PR-staging, RTC

#20413 Fixing com_fields integration in com_contact
  components/com_contact/models/contact.php
Labels: PR-staging, RTC

#20785 [4.0] com_admin safe mode
  administrator/components/com_admin/Model/SysinfoModel.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
  administrator/language/en-GB/en-GB.com_admin.ini
Labels: Language Change, PR-4.0-dev

#20784 [4.0] Installer safe mode
  installation/src/Model/ConfigurationModel.php
Labels: PR-4.0-dev

#20794 [4.0] Remove the build.js from the final package
  build/build.php
Labels: PR-4.0-dev

#20770 [4,0] HTML class naming standard [frontend][com-contact]
  components/com_contact/tmpl/categories/default.php
  components/com_contact/tmpl/categories/default_items.php
  components/com_contact/tmpl/category/default.php
  components/com_contact/tmpl/category/default_children.php
  components/com_contact/tmpl/category/default_items.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/contact/default_address.php
  components/com_contact/tmpl/contact/default_articles.php
  components/com_contact/tmpl/contact/default_form.php
  components/com_contact/tmpl/contact/default_links.php
  components/com_contact/tmpl/contact/default_profile.php
  components/com_contact/tmpl/contact/default_user_custom_fields.php
  components/com_contact/tmpl/featured/default.php
  components/com_contact/tmpl/featured/default_items.php
Labels: PR-4.0-dev

#20795 3.9: Dealing with parse_ini
  libraries/src/Language/LanguageHelper.php
Labels: PR-3.9-dev

#20791 [4.0] Refactoring com_finder fields
  administrator/components/com_finder/Field/BranchesField.php
  administrator/components/com_finder/Field/ContentmapField.php
  administrator/components/com_finder/Field/ContenttypesField.php
Labels: RTC

#20775 [4.0] Installer Checks
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
  installation/src/Model/ChecksModel.php
Labels: Language Change, PR-4.0-dev

#20710 [4.0] Finally use the inflector in the FormHelper
  libraries/src/Form/FormHelper.php
Labels: PR-4.0-dev

#18703 [4.0] Move namespacing be explicit
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  libraries/bootstrap.php
  libraries/loader.php
  libraries/namespacemap.php
Labels: Documentation Required, PR-4.0-dev

#20094 [4.0] Use Symfony's LDAP package in LDAP authentication plugin
  composer.json
  composer.lock
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_files.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/symfony/ldap/Adapter/AbstractConnection.php
  libraries/vendor/symfony/ldap/Adapter/AbstractQuery.php
  libraries/vendor/symfony/ldap/Adapter/AdapterInterface.php
  libraries/vendor/symfony/ldap/Adapter/CollectionInterface.php
  libraries/vendor/symfony/ldap/Adapter/ConnectionInterface.php
  libraries/vendor/symfony/ldap/Adapter/EntryManagerInterface.php
  libraries/vendor/symfony/ldap/Adapter/ExtLdap/Adapter.php
  libraries/vendor/symfony/ldap/Adapter/ExtLdap/Collection.php
  libraries/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php
  libraries/vendor/symfony/ldap/Adapter/ExtLdap/ConnectionOptions.php
  libraries/vendor/symfony/ldap/Adapter/ExtLdap/EntryManager.php
  libraries/vendor/symfony/ldap/Adapter/ExtLdap/Query.php
  libraries/vendor/symfony/ldap/Adapter/QueryInterface.php
  libraries/vendor/symfony/ldap/Adapter/RenameEntryInterface.php
  libraries/vendor/symfony/ldap/Entry.php
  libraries/vendor/symfony/ldap/Exception/ConnectionException.php
  libraries/vendor/symfony/ldap/Exception/DriverNotFoundException.php
  libraries/vendor/symfony/ldap/Exception/ExceptionInterface.php
  libraries/vendor/symfony/ldap/Exception/LdapException.php
  libraries/vendor/symfony/ldap/Exception/NotBoundException.php
  libraries/vendor/symfony/ldap/LICENSE
  libraries/vendor/symfony/ldap/Ldap.php
  libraries/vendor/symfony/ldap/LdapClient.php
  libraries/vendor/symfony/ldap/LdapClientInterface.php
  libraries/vendor/symfony/ldap/LdapInterface.php
  libraries/vendor/symfony/options-resolver/Debug/OptionsResolverIntrospector.php
  libraries/vendor/symfony/options-resolver/Exception/AccessException.php
  libraries/vendor/symfony/options-resolver/Exception/ExceptionInterface.php
  libraries/vendor/symfony/options-resolver/Exception/InvalidArgumentException.php
  libraries/vendor/symfony/options-resolver/Exception/InvalidOptionsException.php
  libraries/vendor/symfony/options-resolver/Exception/MissingOptionsException.php
  libraries/vendor/symfony/options-resolver/Exception/NoConfigurationException.php
  libraries/vendor/symfony/options-resolver/Exception/NoSuchOptionException.php
  libraries/vendor/symfony/options-resolver/Exception/OptionDefinitionException.php
  libraries/vendor/symfony/options-resolver/Exception/UndefinedOptionsException.php
  libraries/vendor/symfony/options-resolver/LICENSE
  libraries/vendor/symfony/options-resolver/Options.php
  libraries/vendor/symfony/options-resolver/OptionsResolver.php
  libraries/vendor/symfony/polyfill-php56/LICENSE
  libraries/vendor/symfony/polyfill-php56/Php56.php
  libraries/vendor/symfony/polyfill-php56/bootstrap.php
  libraries/vendor/symfony/polyfill-util/Binary.php
  libraries/vendor/symfony/polyfill-util/BinaryNoFuncOverload.php
  libraries/vendor/symfony/polyfill-util/BinaryOnFuncOverload.php
  libraries/vendor/symfony/polyfill-util/LICENSE
  libraries/vendor/symfony/polyfill-util/LegacyTestListener.php
  libraries/vendor/symfony/polyfill-util/TestListenerTrait.php
  plugins/authentication/ldap/ldap.php
Labels: Composer Dependency Changed, PR-4.0-dev

#20626 [ModuleHelper] Accept integer as owncache value
  libraries/src/Helper/ModuleHelper.php
Labels: RTC

#20805 Changed return 0 to continue
  libraries/src/Installer/Installer.php
Labels: PR-staging

#20391 [4.0] Using language specific tokeniser and stemmer for com_finder
  .drone.yml
  .gitignore
  administrator/components/com_finder/config.xml
  administrator/components/com_finder/helpers/indexer/helper.php
  administrator/components/com_finder/helpers/indexer/indexer.php
  administrator/components/com_finder/helpers/indexer/language.php
  administrator/components/com_finder/helpers/indexer/language/da.php
  administrator/components/com_finder/helpers/indexer/language/de.php
  administrator/components/com_finder/helpers/indexer/language/el.php
  administrator/components/com_finder/helpers/indexer/language/en.php
  administrator/components/com_finder/helpers/indexer/language/es.php
  administrator/components/com_finder/helpers/indexer/language/fr.php
  administrator/components/com_finder/helpers/indexer/language/it.php
  administrator/components/com_finder/helpers/indexer/language/nl.php
  administrator/components/com_finder/helpers/indexer/language/nn.php
  administrator/components/com_finder/helpers/indexer/language/pt.php
  administrator/components/com_finder/helpers/indexer/language/ro.php
  administrator/components/com_finder/helpers/indexer/language/ru.php
  administrator/components/com_finder/helpers/indexer/language/sv.php
  administrator/components/com_finder/helpers/indexer/language/zh.php
  administrator/components/com_finder/helpers/indexer/query.php
  administrator/components/com_finder/helpers/indexer/stemmer.php
  administrator/components/com_finder/helpers/indexer/stemmer/fr.php
  administrator/components/com_finder/helpers/indexer/stemmer/porter_en.php
  administrator/components/com_finder/helpers/indexer/stemmer/snowball.php
  administrator/components/com_finder/helpers/indexer/taxonomy.php
  administrator/components/com_finder/helpers/indexer/token.php
  administrator/language/en-GB/en-GB.com_finder.ini
  build.xml
  components/com_finder/Model/SearchModel.php
  components/com_finder/Model/SuggestionsModel.php
  composer.json
  composer.lock
  libraries/vendor/composer/ClassLoader.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/wamania/php-stemmer/LICENSE
  libraries/vendor/wamania/php-stemmer/src/Danish.php
  libraries/vendor/wamania/php-stemmer/src/Dutch.php
  libraries/vendor/wamania/php-stemmer/src/English.php
  libraries/vendor/wamania/php-stemmer/src/French.php
  libraries/vendor/wamania/php-stemmer/src/German.php
  libraries/vendor/wamania/php-stemmer/src/Italian.php
  libraries/vendor/wamania/php-stemmer/src/Norwegian.php
  libraries/vendor/wamania/php-stemmer/src/Portuguese.php
  libraries/vendor/wamania/php-stemmer/src/Romanian.php
  libraries/vendor/wamania/php-stemmer/src/Russian.php
  libraries/vendor/wamania/php-stemmer/src/Spanish.php
  libraries/vendor/wamania/php-stemmer/src/Stem.php
  libraries/vendor/wamania/php-stemmer/src/Stemmer.php
  libraries/vendor/wamania/php-stemmer/src/Swedish.php
  libraries/vendor/wamania/php-stemmer/src/Utf8.php
Labels: Language Change, PR-4.0-dev, RTC, Unit/System Tests

#20812 Deprecating JFormFieldDirectories
  administrator/components/com_finder/models/fields/directories.php
Labels: PR-3.9-dev

#20686 [4.0] Content Security Policy (CSP) Management Component
  .github/CODEOWNERS
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-03.sql
  administrator/components/com_csp/Controller/DisplayController.php
  administrator/components/com_csp/Controller/ReportsController.php
  administrator/components/com_csp/Helper/ReporterHelper.php
  administrator/components/com_csp/Model/ReportModel.php
  administrator/components/com_csp/Model/ReportsModel.php
  administrator/components/com_csp/Table/ReportTable.php
  administrator/components/com_csp/View/Reports/HtmlView.php
  administrator/components/com_csp/access.xml
  administrator/components/com_csp/config.xml
  administrator/components/com_csp/csp.xml
  administrator/components/com_csp/forms/filter_reports.xml
  administrator/components/com_csp/services/provider.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/language/en-GB/en-GB.com_csp.ini
  administrator/language/en-GB/en-GB.com_csp.sys.ini
  administrator/language/en-GB/en-GB.ini
  components/com_csp/Controller/ReportController.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  libraries/src/Extension/ExtensionHelper.php
Labels: Documentation Required, Language Change, New Feature, PR-4.0-dev, RTC

#20491 [4.0] httpheaders Implement the suggestion by @brianteeman
  administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
  administrator/language/en-GB/en-GB.plg_system_httpheaders.sys.ini
  plugins/system/httpheaders/httpheaders.php
  plugins/system/httpheaders/httpheaders.xml
  plugins/system/httpheaders/subform/customhttpheaders.xml
Labels: Language Change, PR-4.0-dev

#20135 [4.0] Add space before the ellipsis
  administrator/language/en-GB/en-GB.plg_quickicon_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev

#20818 [4.0] HTML class naming standard [frontend][com-wrapper]
  components/com_wrapper/tmpl/wrapper/default.php
Labels: RTC

#20797 Enable mod_sampledata extension
  administrator/components/com_admin/sql/updates/mysql/3.8.9-2018-06-19.sql
  administrator/components/com_admin/sql/updates/postgresql/3.8.9-2018-06-19.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.8.9-2018-06-19.sql
Labels: RTC

#20817 [4.0] HTML class naming standard [frontend][com-users]
  components/com_users/tmpl/login/default_login.php
  components/com_users/tmpl/login/default_logout.php
  components/com_users/tmpl/profile/default.php
  components/com_users/tmpl/profile/default_core.php
  components/com_users/tmpl/profile/default_custom.php
  components/com_users/tmpl/profile/default_params.php
  components/com_users/tmpl/profile/edit.php
  components/com_users/tmpl/registration/complete.php
  components/com_users/tmpl/registration/default.php
  components/com_users/tmpl/remind/default.php
  components/com_users/tmpl/reset/complete.php
  components/com_users/tmpl/reset/confirm.php
  components/com_users/tmpl/reset/default.php
Labels: PR-4.0-dev

#20829 [4.0] Changed getCfg to get
  libraries/src/Installer/InstallerHelper.php
Labels: PR-4.0-dev

#20819 [4.0] HTML class naming standard [frontend][com-tags]
  components/com_tags/tmpl/tag/default.php
  components/com_tags/tmpl/tag/default_items.php
  components/com_tags/tmpl/tag/list.php
  components/com_tags/tmpl/tag/list_items.php
  components/com_tags/tmpl/tags/default.php
  components/com_tags/tmpl/tags/default_items.php
Labels: PR-4.0-dev, RTC

#20834 [mod_articles_category] Fatal error
  modules/mod_articles_category/tmpl/default.php
Labels: RTC

#20684 [4.0] Fix Codemirror as a custom elements
  administrator/language/en-GB/en-GB.plg_editors_codemirror.ini
  build/webcomponents/js/editor-codemirror/editor-codemirror.js
  media/system/webcomponents/js/joomla-editor-codemirror-es5.js
  media/system/webcomponents/js/joomla-editor-codemirror-es5.min.js
  media/system/webcomponents/js/joomla-editor-codemirror.js
  media/system/webcomponents/js/joomla-editor-codemirror.min.js
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
Labels: Language Change, PR-4.0-dev, RTC

#20842 [4.0] incompatible.html
  templates/system/incompatible.html
Labels: PR-4.0-dev

#20844 Very small language file cs
  administrator/language/en-GB/en-GB.plg_editors_tinymce.ini
Labels: Language Change, PR-staging

#20827 Keep the J4 branch working for now
  libraries/namespacemap.php
  plugins/filesystem/local/local.php
Labels: PR-4.0-dev

#20848 [4.0] Clean up backend mod_login view
  administrator/modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev

#20830 [4.0] Removed custom_data and system_data
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2017-10-10.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-11.sql
Labels: PR-4.0-dev

#20866 [4.0] Rel noopener noreferrer
  administrator/language/en-GB/en-GB.plg_system_httpheaders.ini
Labels: RTC

#20861 [4.0] HTML class naming standard [frontend][com-finder]
  components/com_finder/tmpl/search/default.php
  components/com_finder/tmpl/search/default_form.php
  components/com_finder/tmpl/search/default_result.php
  components/com_finder/tmpl/search/default_results.php
Labels: PR-4.0-dev, RTC

#20860 [4.0] HTML class naming standard [frontend][com-mailto]
  components/com_mailto/tmpl/mailto/default.php
  components/com_mailto/tmpl/sent/default.php
Labels: PR-4.0-dev, RTC

#20820 [4.0] HTML class naming standard [frontend][com-newsfeeds]
  components/com_newsfeeds/tmpl/categories/default.php
  components/com_newsfeeds/tmpl/categories/default_items.php
  components/com_newsfeeds/tmpl/category/default.php
  components/com_newsfeeds/tmpl/category/default_items.php
  components/com_newsfeeds/tmpl/newsfeed/default.php
Labels: PR-4.0-dev

#20854 [4.0] Various improvements to the Local FileSystem plugin
  administrator/components/com_media/src/View/Media/HtmlView.php
  administrator/language/en-GB/en-GB.com_media.ini
  administrator/language/en-GB/en-GB.plg_filesystem_local.ini
  administrator/language/en-GB/en-GB.plg_filesystem_local.sys.ini
  plugins/filesystem/local/local.php
  plugins/filesystem/local/local.xml
Labels: Language Change, PR-4.0-dev

#20877 Fix the autoloader for Windows platforms
  libraries/loader.php
Labels: PR-staging

#20863 [4.0] HTML class naming standard [frontend][com-content]
  components/com_content/tmpl/archive/default.php
  components/com_content/tmpl/archive/default_items.php
  components/com_content/tmpl/article/default.php
  components/com_content/tmpl/article/default_links.php
  components/com_content/tmpl/categories/default.php
  components/com_content/tmpl/categories/default_items.php
  components/com_content/tmpl/category/blog.php
  components/com_content/tmpl/category/blog_children.php
  components/com_content/tmpl/category/blog_links.php
  components/com_content/tmpl/category/default.php
  components/com_content/tmpl/category/default_articles.php
  components/com_content/tmpl/category/default_children.php
Labels: PR-4.0-dev

#20898 [4.0] Wrong sql update for com_csp
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-03.sql
Labels: PR-4.0-dev

#20910 [4.0] Namespace com_modules
  components/com_modules/Controller/DisplayController.php
Labels: PR-4.0-dev

#20909 [4.0]Namespace com-banners
  components/com_banners/Model/BannerModel.php
  components/com_banners/Model/BannersModel.php
Labels: PR-4.0-dev

#20913 [4.0] Namespace com_tags
  components/com_tags/Controller/DisplayController.php
  components/com_tags/Helper/TagsHelperRoute.php
  components/com_tags/Model/TagModel.php
  components/com_tags/Model/TagsModel.php
  components/com_tags/View/Tag/FeedView.php
  components/com_tags/View/Tag/HtmlView.php
  components/com_tags/View/Tags/FeedView.php
  components/com_tags/View/Tags/HtmlView.php
  components/com_tags/router.php
  components/com_tags/tmpl/tag/default.php
  components/com_tags/tmpl/tag/default_items.php
  components/com_tags/tmpl/tag/list.php
  components/com_tags/tmpl/tag/list_items.php
  components/com_tags/tmpl/tags/default.php
  components/com_tags/tmpl/tags/default_items.php
Labels: PR-4.0-dev

#20916 [4.0]Namespace com_ajax
  components/com_ajax/ajax.php
Labels: PR-4.0-dev

#20918 [4.0] Namespace com_fields
  components/com_fields/fields.php
Labels: PR-4.0-dev

#20920 [4.0] Namespace com_newsfeeds
  components/com_newsfeeds/Controller/DisplayController.php
  components/com_newsfeeds/Helper/Route.php
  components/com_newsfeeds/Model/CategoriesModel.php
  components/com_newsfeeds/Model/CategoryModel.php
  components/com_newsfeeds/Model/NewsfeedModel.php
  components/com_newsfeeds/View/Newsfeed/HtmlView.php
  components/com_newsfeeds/helpers/association.php
  components/com_newsfeeds/helpers/category.php
  components/com_newsfeeds/router.php
  components/com_newsfeeds/tmpl/categories/default.php
  components/com_newsfeeds/tmpl/categories/default_items.php
  components/com_newsfeeds/tmpl/category/default.php
  components/com_newsfeeds/tmpl/category/default_children.php
  components/com_newsfeeds/tmpl/category/default_items.php
  components/com_newsfeeds/tmpl/newsfeed/default.php
Labels: PR-4.0-dev

#20906 FIX: Install Languages Manager language badges wrongly set to not match since upgrade to 3.8.10
  administrator/components/com_installer/views/languages/tmpl/default.php
  administrator/components/com_languages/views/installed/tmpl/default.php
Labels: PR-staging, RTC

#19452 Replace the URL parameter "limitstart=0" with "start=0" if the SEF mode is on
  libraries/src/Router/SiteRouter.php
  tests/unit/suites/libraries/cms/router/JRouterSiteTest.php
Labels: PR-staging, RTC

#20093 Remove non callable array items from field categories
  administrator/components/com_fields/helpers/fields.php
Labels: PR-staging, RTC

#17944 Deprecate editor form field save function
  libraries/src/Form/Field/EditorField.php
Labels: PR-3.9-dev, RTC

#20845 [Site Modules] Manifest file filters, part 1
  administrator/components/com_modules/views/module/tmpl/edit.php
  modules/mod_articles_archive/mod_articles_archive.xml
  modules/mod_articles_categories/mod_articles_categories.xml
  modules/mod_articles_category/helper.php
  modules/mod_articles_category/mod_articles_category.xml
  modules/mod_articles_latest/helper.php
  modules/mod_articles_latest/mod_articles_latest.xml
  modules/mod_articles_news/helper.php
  modules/mod_articles_news/mod_articles_news.xml
  modules/mod_articles_news/tmpl/_item.php
  modules/mod_articles_popular/mod_articles_popular.xml
  modules/mod_banners/mod_banners.xml
Labels: RTC

#20858 [cs] leading spaces
  administrator/language/en-GB/en-GB.com_media.ini
  administrator/language/en-GB/en-GB.com_menus.ini
  administrator/language/en-GB/en-GB.plg_content_pagebreak.ini
  language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.ini
Labels: RTC

#20856 [Site Modules] Manifest file filters, part 2
  modules/mod_breadcrumbs/mod_breadcrumbs.xml
  modules/mod_custom/mod_custom.xml
  modules/mod_feed/mod_feed.xml
  modules/mod_feed/tmpl/default.php
  modules/mod_finder/mod_finder.xml
  modules/mod_finder/tmpl/default.php
  modules/mod_footer/mod_footer.xml
  modules/mod_languages/mod_languages.xml
  modules/mod_languages/tmpl/default.php
  modules/mod_login/mod_login.xml
  modules/mod_login/tmpl/default.php
  modules/mod_login/tmpl/default_logout.php
  modules/mod_menu/helper.php
  modules/mod_menu/mod_menu.php
  modules/mod_menu/mod_menu.xml
  modules/mod_random_image/helper.php
  modules/mod_random_image/mod_random_image.xml
Labels: PR-staging, RTC

#20857 [Site Modules] Manifest file filters, part 3
  modules/mod_related_items/mod_related_items.xml
  modules/mod_search/mod_search.xml
  modules/mod_stats/helper.php
  modules/mod_stats/mod_stats.php
  modules/mod_stats/mod_stats.xml
  modules/mod_syndicate/mod_syndicate.xml
  modules/mod_tags_popular/helper.php
  modules/mod_tags_popular/mod_tags_popular.xml
  modules/mod_tags_similar/mod_tags_similar.xml
  modules/mod_users_latest/helper.php
  modules/mod_users_latest/mod_users_latest.xml
  modules/mod_whosonline/mod_whosonline.xml
  modules/mod_whosonline/tmpl/default.php
  modules/mod_wrapper/helper.php
  modules/mod_wrapper/mod_wrapper.xml
Labels: RTC

#20740 (UX) Add link to edit categories and show parent category
  administrator/components/com_content/models/articles.php
  administrator/components/com_content/models/featured.php
  administrator/components/com_content/views/articles/tmpl/default.php
  administrator/components/com_content/views/featured/tmpl/default.php
Labels: PR-3.9-dev, RTC

#20868 [Admin Modules] Manifest file filters
  administrator/modules/mod_custom/mod_custom.xml
  administrator/modules/mod_feed/mod_feed.xml
  administrator/modules/mod_feed/tmpl/default.php
  administrator/modules/mod_latest/helper.php
  administrator/modules/mod_latest/mod_latest.xml
  administrator/modules/mod_logged/helper.php
  administrator/modules/mod_logged/mod_logged.xml
  administrator/modules/mod_login/mod_login.xml
  administrator/modules/mod_login/tmpl/default.php
  administrator/modules/mod_menu/menu.php
  administrator/modules/mod_menu/mod_menu.xml
  administrator/modules/mod_popular/helper.php
  administrator/modules/mod_popular/mod_popular.xml
  administrator/modules/mod_quickicon/mod_quickicon.xml
  administrator/modules/mod_stats_admin/helper.php
  administrator/modules/mod_stats_admin/mod_stats_admin.xml
  administrator/modules/mod_status/mod_status.xml
  administrator/modules/mod_submenu/mod_submenu.xml
  administrator/modules/mod_title/mod_title.xml
  administrator/modules/mod_version/helper.php
  administrator/modules/mod_version/mod_version.xml
Labels: RTC

#18431 [com_fields] Adding label Class for input
  administrator/components/com_fields/libraries/fieldsplugin.php
  administrator/components/com_fields/models/forms/field.xml
  administrator/language/en-GB/en-GB.com_fields.ini
  components/com_contact/layouts/field/render.php
  components/com_fields/layouts/field/render.php
Labels: Language Change, PR-3.9-dev, RTC

#20934 Deprecate FinderIndexerHelper::getContentPath()
  administrator/components/com_finder/helpers/indexer/helper.php
Labels: PR-staging

#20917 [4.0] Namespace com_mailto
  components/com_mailto/Controller/DisplayController.php
  components/com_mailto/Helper/MailtoHelper.php
  components/com_mailto/View/Mailto/HtmlView.php
  components/com_mailto/tmpl/mailto/default.php
  components/com_mailto/tmpl/sent/default.php
Labels: PR-4.0-dev

#20930 [4.0] Classsmap typo
  libraries/classmap.php
Labels: PR-4.0-dev

#20915 [4.0] Namespace com_search
  components/com_search/Controller/DisplayController.php
  components/com_search/Model/SearchModel.php
  components/com_search/View/Search/HtmlView.php
  components/com_search/View/Search/OpensearchView.php
  components/com_search/tmpl/search/default_form.php
  components/com_search/tmpl/search/default_results.php
Labels: PR-4.0-dev

#20924 [4.0] Namespace modules/plugins/layouts
  layouts/joomla/form/field/rules.php
  layouts/joomla/links/groupopen.php
  modules/mod_whosonline/tmpl/disabled.php
  plugins/installer/packageinstaller/tmpl/default.php
  plugins/search/content/content.php
  plugins/system/debug/debug.php
  plugins/system/httpheaders/postinstall/introduction.php
  plugins/system/languagefilter/languagefilter.php
  plugins/system/remember/remember.php
  plugins/system/stats/stats.php
  plugins/system/updatenotification/updatenotification.php
Labels: PR-4.0-dev
