Repository joomla/joomla-cms, pull requests merged in 2018-10, with the labels that each got.

#22433 [4.0] Admin menu hard coded [a11y] strings
  administrator/language/en-GB/en-GB.mod_menu.ini
  administrator/modules/mod_menu/tmpl/default.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
Labels: Language Change, PR-4.0-dev

#22363 [4.0] Remove the deprecated code in the contact view
  components/com_contact/View/Contact/HtmlView.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/contact/default_address.php
  components/com_contact/tmpl/contact/default_form.php
  components/com_contact/tmpl/contact/default_links.php
Labels: Documentation Required, PR-4.0-dev

#22359 [4.0] Remove deprecated code from the LibraryHelper class
  libraries/src/Helper/LibraryHelper.php
Labels: Documentation Required, PR-4.0-dev

#22358 [4.0] Remove deprecated code from the TextField class
  libraries/src/Form/Field/TextField.php
Labels: Documentation Required, PR-4.0-dev

#22343 [4.0] Workflow transitions layout 2
  administrator/components/com_workflow/Model/TransitionsModel.php
  administrator/components/com_workflow/tmpl/transitions/default.php
Labels: PR-4.0-dev, RTC

#22283 [4.0] Adds deprecated messages to the getInstance functions for the model and controller
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
Labels: Documentation Required, PR-4.0-dev

#22287 [4.0] Remove the deprecated code in the HTMLHelper class
  libraries/src/HTML/HTMLHelper.php
Labels: Documentation Required, PR-4.0-dev

#22165 [4.0] Completely remove tooltips from forms [a11y]
  layouts/joomla/form/renderfield.php
  layouts/joomla/form/renderlabel.php
Labels: PR-4.0-dev

#21187 [4.0] Router fix - layouts
  libraries/src/Component/Router/Rules/MenuRules.php
Labels: PR-4.0-dev, RTC

#22452 [4.0] Class 'ModulesHelper' not found
  administrator/components/com_modules/tmpl/modules/default_batch_body.php
Labels: PR-4.0-dev

#22447 [4.0] Fix markup in JGrid
  libraries/cms/html/jgrid.php
Labels: PR-4.0-dev

#22451 [4.0] Alpha ordering of admin mod_menu.ini strings
  administrator/language/en-GB/en-GB.mod_menu.ini
Labels: Language Change, PR-4.0-dev

#22428 Alpha ordering plg_actionlog_joomla.ini strings
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
Labels: Language Change, PR-staging

#22403 Language switcher module: load helpers without component constant
  modules/mod_languages/helper.php
Labels: RTC

#22372 [isis] Template menu assign - 4 columns on lg screen
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/less/pages/_com_templates.less
Labels: RTC

#22367 [Isis] Use native display sticky on toolbar
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/index.php
  administrator/templates/isis/js/template.js
  administrator/templates/isis/less/blocks/_global.less
  administrator/templates/isis/less/blocks/_toolbar.less
Labels: PR-staging, RTC

#22413 Option to disable save article hits
  administrator/components/com_content/config.xml
  administrator/language/en-GB/en-GB.ini
  components/com_content/controller.php
Labels: Language Change, PR-staging, RTC

#22345 Create and apply 'dropdown-reverse' css class
  administrator/components/com_menus/views/menus/tmpl/default.php
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/less/blocks/_custom.less
  administrator/templates/isis/less/template-rtl.less
Labels: PR-staging, RTC

#22239 [modules] - only for superadmin eyes
  administrator/modules/mod_latestactions/mod_latestactions.php
  administrator/modules/mod_privacy_dashboard/mod_privacy_dashboard.php
  plugins/quickicon/privacycheck/privacycheck.php
Labels: PR-staging, RTC

#22237 Make sure manifest object returned before logging actions
  plugins/actionlog/joomla/joomla.php
Labels: RTC

#21696 Allow groups to render custom form elements
  administrator/components/com_users/models/forms/group.xml
  administrator/components/com_users/views/group/tmpl/edit.php
Labels: RTC

#18166 [microdata] - worstRating should be 1
  plugins/content/vote/tmpl/rating.php
Labels: PR-staging, RTC

#17735 Authorization at article level in com_content not always working: Article model
  components/com_content/models/article.php
Labels: PR-staging, RTC

#20339 [4.0] Introduce router service
  administrator/components/com_content/Extension/ContentComponent.php
  administrator/components/com_content/services/provider.php
  administrator/components/com_finder/Extension/FinderComponent.php
  administrator/components/com_finder/services/provider.php
  administrator/components/com_newsfeeds/Extension/NewsfeedsComponent.php
  administrator/components/com_newsfeeds/services/provider.php
  administrator/components/com_users/Extension/UsersComponent.php
  administrator/components/com_users/services/provider.php
  components/com_contact/Service/Router.php
  components/com_content/Service/Router.php
  components/com_finder/Service/Router.php
  components/com_newsfeeds/Service/Router.php
  components/com_users/Service/Router.php
  libraries/src/Categories/CategoryFactory.php
  libraries/src/Categories/CategoryFactoryInterface.php
  libraries/src/Component/Router/RouterFactory.php
  libraries/src/Component/Router/RouterFactoryInterface.php
  libraries/src/Component/Router/RouterServiceInterface.php
  libraries/src/Component/Router/RouterServiceTrait.php
  libraries/src/Component/Router/RouterView.php
  libraries/src/Extension/LegacyComponent.php
  libraries/src/Extension/Service/Provider/RouterFactory.php
  libraries/src/Router/SiteRouter.php
Labels: PR-4.0-dev

#22462 [4.0] Menu Type select button [a11y]
  administrator/components/com_menus/Field/MenutypeField.php
Labels: PR-4.0-dev

#22461 [4.0] Editor buttons [a11y]
  layouts/joomla/editors/buttons/button.php
Labels: PR-4.0-dev

#22467 [4.0] Fix installer js error
  administrator/components/com_installer/tmpl/install/default.php
Labels: PR-4.0-dev

#22472 [4.0] href fix
  administrator/components/com_menus/Field/MenutypeField.php
  layouts/joomla/editors/buttons/button.php
Labels: PR-4.0-dev

#22444 Change responsive layout for repeatable-table.
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section-byfieldsets.php
Labels: RTC

#22477 [4.0] Add crowdin.yml to the doNotPackage array
  build/build.php
Labels: PR-4.0-dev

#22469 [4.0] Update composer dependencies
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#22485 [4.0] Cancel/Close button
  administrator/components/com_config/View/Application/HtmlView.php
  administrator/components/com_config/View/Component/HtmlView.php
  administrator/components/com_messages/View/Message/HtmlView.php
Labels: PR-4.0-dev

#22473 [4.0] joomla-field-media [a11y]
  layouts/joomla/form/field/media.php
Labels: PR-4.0-dev

#22457 [4.0] Reference the session from the application
  libraries/src/Application/CMSApplication.php
  libraries/src/Factory.php
Labels: PR-4.0-dev

#22458 [4.0] Get the secret from the global application in the helper
  libraries/src/Application/ApplicationHelper.php
Labels: PR-4.0-dev

#22498 [4.0] Class MenusHelper not found
  administrator/components/com_menus/tmpl/item/edit_container.php
  libraries/src/Form/Field/MenuitemField.php
Labels: PR-4.0-dev

#22499 [4.0] com_associations: sidebyside js and css not loaded
  administrator/components/com_associations/tmpl/association/edit.php
Labels: PR-4.0-dev

#21733 Missing language string
  administrator/language/en-GB/en-GB.com_associations.ini
Labels: Language Change, PR-staging

#22464 [4.0] Correcting help menu and view
  administrator/components/com_cpanel/View/Help/HtmlView.php
  administrator/components/com_cpanel/tmpl/help/default.php
  administrator/modules/mod_menu/Menu/CssMenu.php
Labels: PR-4.0-dev

#22509 [4.0] lower case extension name c/s
  administrator/manifests/libraries/joomla.xml
  administrator/manifests/libraries/phpass.xml
  plugins/installer/folderinstaller/folderinstaller.xml
  plugins/installer/urlinstaller/urlinstaller.xml
Labels: PR-4.0-dev

#22503 [4.0] Legend font weight
  administrator/templates/atum/scss/blocks/_global.scss
Labels: PR-4.0-dev

#22510 p4.0] com-cache namespace
  administrator/components/com_cache/tmpl/cache/default.php
Labels: RTC

#22513 [4.0] Calendar js files not loading
  layouts/joomla/form/field/calendar.php
Labels: PR-4.0-dev

#22508 [4.0] stats plugin buttons [a11y]
  plugins/system/stats/layouts/message.php
Labels: PR-4.0-dev

#22506 [3.9] Revert #22367
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/index.php
  administrator/templates/isis/js/template.js
  administrator/templates/isis/less/blocks/_global.less
  administrator/templates/isis/less/blocks/_toolbar.less
Labels: RTC

#22494 Links to buttons
  administrator/components/com_banners/views/banners/tmpl/default_batch_footer.php
  administrator/components/com_categories/views/categories/tmpl/default_batch_footer.php
  administrator/components/com_contact/views/contacts/tmpl/default_batch_footer.php
  administrator/components/com_content/views/articles/tmpl/default_batch_footer.php
  administrator/components/com_fields/views/fields/tmpl/default_batch_footer.php
  administrator/components/com_fields/views/groups/tmpl/default_batch_footer.php
  administrator/components/com_menus/views/items/tmpl/default_batch_footer.php
  administrator/components/com_modules/views/modules/tmpl/default_batch_footer.php
  administrator/components/com_newsfeeds/views/newsfeeds/tmpl/default_batch_footer.php
  administrator/components/com_redirect/views/links/tmpl/default_batch_footer.php
  administrator/components/com_tags/views/tags/tmpl/default_batch_footer.php
  administrator/components/com_templates/views/template/tmpl/default_modal_copy_footer.php
  administrator/components/com_templates/views/template/tmpl/default_modal_delete_footer.php
  administrator/components/com_templates/views/template/tmpl/default_modal_file_footer.php
  administrator/components/com_templates/views/template/tmpl/default_modal_folder_footer.php
  administrator/components/com_templates/views/template/tmpl/default_modal_rename_footer.php
  administrator/components/com_templates/views/template/tmpl/default_modal_resize_footer.php
  administrator/components/com_users/views/users/tmpl/default_batch_footer.php
Labels: PR-staging, RTC

#22481 [3.9] Workaround for consentbox for com_mailto
  components/com_mailto/controller.php
  components/com_mailto/models/mailto.php
Labels: RTC, release-blocker

#22432 Add a redirection for the menu item alias
  libraries/src/Application/CMSApplication.php
Labels: RTC

#22402 [privacy] Move common code to PrivacyPlugin class
  administrator/components/com_privacy/helpers/plugin.php
  plugins/privacy/actionlogs/actionlogs.php
  plugins/privacy/contact/contact.php
  plugins/privacy/content/content.php
  plugins/privacy/message/message.php
  plugins/privacy/user/user.php
Labels: PR-staging, RTC

#22389 [action logs] Add action log plugin library class
  administrator/components/com_actionlogs/libraries/actionlogplugin.php
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging, RTC

#22534 [4.0] JText not found in JROOT\libraries\src\Form\Field\PluginsField.php:173
  libraries/src/Form/Field/PluginsField.php
Labels: RTC

#22512 [4.0] Error in System Information
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
Labels: PR-4.0-dev, RTC

#22526 [com_actionlogs] - fix non object notice
  administrator/components/com_actionlogs/libraries/actionlogplugin.php
Labels: RTC

#22557 [3.9.0] No need to escape PLG_QUICKICON_PRIVACYCHECK language strings values
  plugins/quickicon/privacycheck/privacycheck.php
Labels: RTC

#22563 Follow en-GB style guide
  language/en-GB/en-GB.com_users.ini
Labels: RTC

#22562 Fix wrong action log link when add/edit article
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging, RTC

#22542 [com_actionlogs] Sort events in alpha order
  administrator/components/com_actionlogs/models/fields/logtype.php
Labels: PR-staging, RTC

#22537 Remove redundant comment
  modules/mod_whosonline/helper.php
Labels: RTC

#22523 com_associations long titles
  administrator/components/com_associations/views/associations/tmpl/default.php
Labels: RTC

#22518 [staging fix] Class 'ContentHelperAssociation' not found when editing a module in frontend
  components/com_content/models/articles.php
Labels: PR-staging

#22479 Fixed capitalisation for vote language strings.
  language/en-GB/en-GB.com_content.ini
Labels: Language Change, PR-staging

#22547 [4.0] Improve workflow association DB keys
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#22539 [4.0] XAMPP on Windows. Template Manager. Saving of files fails
  administrator/components/com_templates/Controller/TemplateController.php
Labels: PR-4.0-dev

#22536 [4.0] Installer library query fixes
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
Labels: RTC

#22538 [4.0] Translate JHTML WorkflowStage
  libraries/cms/html/workflowstage.php
Labels: PR-4.0-dev

#22493 [4.0] Use the setLimit function in the database model
  libraries/src/MVC/Model/BaseDatabaseModel.php
Labels: PR-4.0-dev

#22490 [4.0] Remove transition code in the legacy dispatcher
  libraries/src/Dispatcher/LegacyComponentDispatcher.php
Labels: PR-4.0-dev

#22585 Don't delete 3rd party license file
  administrator/components/com_admin/script.php
Labels: PR-staging

#22528 [4.0] Module assignment dropdown [a11y]
  administrator/components/com_modules/tmpl/module/edit_assignment.php
Labels: PR-4.0-dev

#22602 [3.9] Make sure ArrayHelper is used correctly
  administrator/components/com_newsfeeds/models/newsfeeds.php
Labels: PR-staging

#22611 [4.0] Missing css
  administrator/templates/atum/scss/vendor/bootstrap/_table.scss
Labels: PR-4.0-dev

#21678 [4.0] Deprecate JPATH_COMPONENT path constants
  libraries/src/Component/ComponentHelper.php
Labels: PR-4.0-dev

#22442 [4.0] Use non deprecated code in core extensions
  administrator/modules/mod_logged/Helper/LoggedHelper.php
  administrator/modules/mod_logged/mod_logged.php
  administrator/modules/mod_status/tmpl/default.php
  plugins/system/sessiongc/sessiongc.php
Labels: PR-4.0-dev

#22614 [4.0] Quick Icons - [a11y]
  administrator/language/en-GB/en-GB.mod_quickicon.ini
  administrator/modules/mod_quickicon/tmpl/default.php
  administrator/templates/atum/scss/blocks/_quickicons.scss
  layouts/joomla/quickicons/icon.php
Labels: Language Change, PR-4.0-dev

#22613 [4.0] admin replace btn-xs
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_messages/Service/HTML/Messages.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  administrator/modules/mod_logged/tmpl/default.php
Labels: PR-4.0-dev

#22435 [4.0][RFC] Elephant can manage assets also. The WebAssetRegistry class to manage assets and it`s dependacies
  administrator/templates/atum/index.php
  administrator/templates/atum/joomla.asset.json
  build/build-modules-js/settings.json
  build/build-modules-js/update.js
  build/media/legacy/joomla.asset.json
  build/media_src/system/joomla.asset.json
  libraries/cms/html/behavior.php
  libraries/cms/html/bootstrap.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Document/Document.php
  libraries/src/Document/Renderer/Html/MetasRenderer.php
  libraries/src/Event/WebAsset/AbstractEvent.php
  libraries/src/Event/WebAsset/WebAssetBeforeAttachEvent.php
  libraries/src/Event/WebAsset/WebAssetStateChangedEvent.php
  libraries/src/Factory.php
  libraries/src/Service/Provider/WebAsset.php
  libraries/src/WebAsset/WebAssetItem.php
  libraries/src/WebAsset/WebAssetRegistry.php
  templates/cassiopeia/index.php
  templates/cassiopeia/joomla.asset.json
Labels: PR-4.0-dev, Request for Comment

#22612 [4.0] docblock copy/paste error
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev

#22470 [4.0] Update JS dependencies
  package-lock.json
Labels: PR-4.0-dev

#22615 [4.0] btn-secondary missing css
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
Labels: PR-4.0-dev

#22448 [4.0] Use the injected application and db in the update notification plugin
  plugins/system/updatenotification/updatenotification.php
Labels: PR-4.0-dev

#22502 [4.0] Remove some deprecated code used on the front end
  modules/mod_articles_archive/Helper/ArticlesArchiveHelper.php
  modules/mod_tags_popular/Helper/TagsPopularHelper.php
  plugins/system/languagefilter/languagefilter.php
Labels: PR-4.0-dev

#22616 [4.0] Update jquery migrate
  package.json
Labels: PR-4.0-dev

#22505 [4.0] configuration tab background
  administrator/templates/atum/scss/_variables.scss
Labels: PR-4.0-dev

#22617 [4.0] Update package lock
  package-lock.json
Labels: PR-4.0-dev

#22628 [4.0] Fix jQuery Minicolors positioning
  administrator/templates/atum/scss/template.scss
  build/media/system/scss/_jquery-minicolors.scss
  templates/cassiopeia/scss/template.scss
Labels: PR-4.0-dev

#19699 [4.0] Use identical operators for plugins
  plugins/content/fields/fields.php
  plugins/content/vote/tmpl/rating.php
  plugins/search/categories/categories.php
  plugins/system/cache/cache.php
  plugins/system/fields/fields.php
Labels: PR-4.0-dev, RTC

#22610 [4.0] Dropdown user menu
  administrator/templates/atum/scss/blocks/_header.scss
Labels: PR-4.0-dev

#22541 [4.0] Update override.xml to use namespace
  administrator/components/com_languages/forms/override.xml
Labels: PR-4.0-dev

#22213 [4.0] Spacer text
  administrator/templates/atum/scss/blocks/_form.scss
Labels: PR-4.0-dev

#22646 dont delete default_ftp.php
  administrator/components/com_admin/script.php
Labels: PR-staging

#22648 do not delete ajax-loader.gif
  administrator/components/com_admin/script.php
Labels: PR-staging

#22655 Use better text from other file, which has now been corrected
  administrator/components/com_actionlogs/models/fields/logcreator.php
Labels: PR-staging

#22649 Terminate with period instead of semi-colon
  .github/SUPPORT.md
Labels: RTC

#22653 s/article/Actionlog
  administrator/components/com_actionlogs/models/actionlog.php
Labels: RTC

#22654 s/users/extensions
  administrator/components/com_actionlogs/models/fields/extension.php
Labels: PR-staging

#22652 s/Referer/Referrer-Policy/
  components/com_privacy/controller.php
Labels: PR-staging

#22650 s/proxys/proxies
  components/com_privacy/router.php
Labels: PR-staging

#22647 Convert PHP developer line endings to text reading line endings ;-)
  README.md
Labels: RTC

#22599 Indexer fix for large articles
  administrator/components/com_finder/helpers/indexer/helper.php
  administrator/components/com_finder/helpers/indexer/indexer.php
Labels: PR-staging, RTC

#22658 Remove Space in value of JHELP_MENUS_MENU_ITEM_PRIVACY_CREATE_REQUEST
  administrator/language/en-GB/en-GB.ini
Labels: RTC

#22665 [4.0] Fix xpath for the section in the rules field
  libraries/src/Form/Field/RulesField.php
  libraries/src/Form/Rule/RulesRule.php
Labels: PR-4.0-dev

#22675 [com_privacy] Use configured TimeZone
  administrator/components/com_privacy/views/request/tmpl/default.php
Labels: PR-staging

#22588 [com_actionlogs] - show guest actions
  administrator/components/com_actionlogs/models/actionlogs.php
Labels: PR-staging, RTC

#22584 Fix the default value for the ordering field in Articles - Latest module
  modules/mod_articles_latest/mod_articles_latest.xml
Labels: RTC

#22582 Correct path to ajax-loader.gif
  administrator/modules/mod_sampledata/tmpl/default.php
Labels: RTC

#22608 [privacy] Create only 1 domain for the items custom fields (simplify export xml)
  administrator/components/com_privacy/helpers/plugin.php
  plugins/privacy/contact/contact.php
  plugins/privacy/content/content.php
  plugins/privacy/user/user.php
Labels: RTC

#22454 [4.0] Namespace the users html services
  administrator/components/com_users/Extension/UsersComponent.php
  administrator/components/com_users/Service/HTML/Users.php
  administrator/components/com_users/View/Note/HtmlView.php
  administrator/components/com_users/View/Notes/HtmlView.php
  administrator/components/com_users/View/Users/HtmlView.php
  administrator/components/com_users/services/provider.php
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/components/com_users/tmpl/group/edit.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/level/edit.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/notes/modal.php
  administrator/components/com_users/tmpl/user/edit.php
  administrator/components/com_users/tmpl/user/edit_groups.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/components/com_users/tmpl/users/modal.php
  components/com_users/helpers/html/users.php
  components/com_users/tmpl/profile/default_custom.php
  components/com_users/tmpl/profile/default_params.php
Labels: PR-4.0-dev

#22385 [4.0] Remove the deprecated code in the Profiler class
  libraries/src/Profiler/Profiler.php
Labels: Documentation Required, PR-4.0-dev

#22676 Test PHP 7.3 on Travis, remove allowed failure for 7.2
  .travis.yml
  build/travis/phpenv/apcu-7.3.ini
Labels: PR-staging, Unit/System Tests

#22666 [4.0] Adapt the password view script to new markup and move to ES6
  administrator/modules/mod_login/tmpl/default.php
  build/media/system/js/fields/passwordview.js
  build/media_src/system/js/fields/passwordview.es6.js
  layouts/joomla/form/field/password.php
Labels: PR-4.0-dev

#21983 [3.9][com_actionlogs] Move log notification option to own table
  administrator/components/com_actionlogs/models/actionlog.php
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-09-04.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-09-04.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-09-04.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
  plugins/system/actionlogs/actionlogs.php
  plugins/system/actionlogs/forms/actionlogs.xml
Labels: PR-staging, RTC

#22667 [4.0] Refactored admin-item-edit_container.es6.js to no longer use jQuery anymore
  build/media_src/com_menus/js/admin-item-edit_container.es6.js
Labels: PR-4.0-dev

#22683 Deprecate isClient and isAdmin for version 4
  libraries/src/Application/CMSApplication.php
Labels: RTC

#22386 Deprecates the filesystem wrapper classes
  libraries/src/Filesystem/Wrapper/FileWrapper.php
  libraries/src/Filesystem/Wrapper/FolderWrapper.php
  libraries/src/Filesystem/Wrapper/PathWrapper.php
Labels: Documentation Required, PR-staging

#22587 [4.0] Sidebar - switch to vertical collapsing
  administrator/components/com_menus/presets/joomla.xml
  administrator/modules/mod_menu/tmpl/default.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
  build/build-modules-js/settings.json
  build/media/mod_menu/js/admin-menu.js
  package.json
Labels: PR-4.0-dev

#22387 [4.0] Remove the filesystem wrapper classes
  libraries/classmap.php
  libraries/src/Filesystem/File.php
  libraries/src/Filesystem/Folder.php
  libraries/src/Filesystem/Path.php
  libraries/src/Filesystem/Wrapper/FileWrapper.php
  libraries/src/Filesystem/Wrapper/FolderWrapper.php
  libraries/src/Filesystem/Wrapper/PathWrapper.php
Labels: Documentation Required, PR-4.0-dev

#22455 [4.0] Remove not needed helpers call in the blog layout
  layouts/joomla/content/blog_style_default_item_title.php
Labels: PR-4.0-dev

#22456 [4.0] Remove not needed helpers call in the list model
  libraries/src/MVC/View/ListView.php
Labels: Documentation Required, PR-4.0-dev

#22354 [4.0] Remove the deprecated code in the CacheController class
  libraries/src/Cache/CacheController.php
  libraries/src/Cache/Controller/CallbackController.php
  libraries/src/Cache/Controller/ViewController.php
Labels: Documentation Required, PR-4.0-dev

#22104 [4.0] Create workflow association for batch copy article
  administrator/components/com_content/Model/ArticleModel.php
Labels: PR-4.0-dev

#22035 [4.0] Remove database check for utf8mb4 support
  libraries/src/Filter/InputFilter.php
Labels: PR-4.0-dev

#22678 [4.0] Remove deprecated item title layout
  administrator/components/com_languages/tmpl/language/edit.php
  administrator/components/com_users/tmpl/user/edit.php
  layouts/joomla/edit/item_title.php
Labels: Documentation Required, PR-4.0-dev

#22687 [4.0] Introduce cache controller service provider
  libraries/src/Cache/Cache.php
  libraries/src/Cache/CacheController.php
  libraries/src/Cache/CacheControllerFactory.php
  libraries/src/Cache/CacheControllerFactoryInterface.php
  libraries/src/Factory.php
  libraries/src/Service/Provider/CacheController.php
Labels: PR-4.0-dev

#19834 [4.0] Module dispatcher
  administrator/components/com_admin/services/provider.php
  administrator/components/com_associations/services/provider.php
  administrator/components/com_banners/services/provider.php
  administrator/components/com_cache/services/provider.php
  administrator/components/com_categories/services/provider.php
  administrator/components/com_checkin/services/provider.php
  administrator/components/com_config/services/provider.php
  administrator/components/com_content/services/provider.php
  administrator/components/com_contenthistory/services/provider.php
  administrator/components/com_cpanel/services/provider.php
  administrator/components/com_csp/services/provider.php
  administrator/components/com_fields/services/provider.php
  administrator/components/com_finder/services/provider.php
  administrator/components/com_installer/services/provider.php
  administrator/components/com_joomlaupdate/services/provider.php
  administrator/components/com_languages/services/provider.php
  administrator/components/com_login/services/provider.php
  administrator/components/com_mailto/services/provider.php
  administrator/components/com_media/services/provider.php
  administrator/components/com_menus/services/provider.php
  administrator/components/com_messages/services/provider.php
  administrator/components/com_modules/services/provider.php
  administrator/components/com_plugins/services/provider.php
  administrator/components/com_postinstall/services/provider.php
  administrator/components/com_redirect/services/provider.php
  administrator/components/com_search/services/provider.php
  administrator/components/com_tags/services/provider.php
  administrator/components/com_templates/services/provider.php
  administrator/components/com_users/services/provider.php
  administrator/components/com_workflow/services/provider.php
  administrator/components/com_wrapper/services/provider.php
  administrator/modules/mod_quickicon/Dispatcher/Dispatcher.php
  administrator/modules/mod_quickicon/Helper/QuickIconHelper.php
  administrator/modules/mod_quickicon/mod_quickicon.php
  administrator/modules/mod_quickicon/services/provider.php
  build/phpcs/Joomla/ruleset.xml
  libraries/src/Dispatcher/AbstractModuleDispatcher.php
  libraries/src/Dispatcher/ComponentDispatcher.php
  libraries/src/Dispatcher/ComponentDispatcherFactory.php
  libraries/src/Dispatcher/ComponentDispatcherFactoryInterface.php
  libraries/src/Dispatcher/Dispatcher.php
  libraries/src/Dispatcher/DispatcherInterface.php
  libraries/src/Dispatcher/ModuleDispatcher.php
  libraries/src/Dispatcher/ModuleDispatcherFactory.php
  libraries/src/Dispatcher/ModuleDispatcherFactoryInterface.php
  libraries/src/Extension/Component.php
  libraries/src/Extension/ExtensionManagerInterface.php
  libraries/src/Extension/ExtensionManagerTrait.php
  libraries/src/Extension/Module.php
  libraries/src/Extension/ModuleInterface.php
  libraries/src/Extension/Service/Provider/ComponentDispatcherFactory.php
  libraries/src/Extension/Service/Provider/Module.php
  libraries/src/Extension/Service/Provider/ModuleDispatcherFactory.php
  libraries/src/Helper/ModuleHelper.php
Labels: PR-4.0-dev

#22692 [4.0] Sidebar Menu [a11y]
  administrator/modules/mod_menu/tmpl/default.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev

#22706 [4.0] Update build script
  build/build-modules-js/update.js
Labels: PR-4.0-dev

#22637 [3.9.0] com_actionlogs: Translating extension_name not working in some situations
  administrator/components/com_actionlogs/helpers/actionlogs.php
Labels: PR-staging

#22705 [com_actionlogs][Security][RELEASE BLOCKER] Check for token before allowing purge
  administrator/components/com_actionlogs/controllers/actionlogs.php
Labels: PR-staging

#22737 [4.0] Forward port the hsts max-age fix from the original plugin
  plugins/system/httpheaders/httpheaders.php
Labels: PR-4.0-dev

#22733 [4.0] Add New sidebar menu
  administrator/components/com_menus/presets/joomla.xml
Labels: PR-4.0-dev

#22760 [4.0] Workflows copy/paste error
  administrator/modules/mod_menu/Menu/CssMenu.php
Labels: PR-4.0-dev

#22773 [4.0] Double label in filter_modulesadmin.xml breaks admin modules manager
  administrator/components/com_modules/forms/filter_modulesadmin.xml
Labels: PR-4.0-dev

#22771 [4.0] Use the static class to lookup the path
  libraries/src/Filesystem/File.php
Labels: PR-4.0-dev

#22764 [4.0] Update draggablelist.php to use array as parameters
  libraries/cms/html/draggablelist.php
Labels: PR-4.0-dev

#22730 [4.0] Load the cache controller through the factory in the site application
  libraries/src/Application/SiteApplication.php
Labels: PR-4.0-dev

#22731 [4.0] Get the config in the uri class from the container
  libraries/src/Uri/Uri.php
Labels: PR-4.0-dev

#22748 Drop checked_out capability in com_privacy
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-10-20.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-10-20.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-10-20.sql
  administrator/components/com_privacy/models/forms/request.xml
  administrator/components/com_privacy/models/requests.php
  administrator/components/com_privacy/tables/request.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
Labels: PR-staging, RTC

#22751 Standardize CSV export timezone on UTC, don't use translated timestamp format, include timezone in printed text
  administrator/components/com_actionlogs/controllers/actionlogs.php
  administrator/components/com_actionlogs/helpers/actionlogs.php
Labels: PR-staging, RTC

#22743 [com_privacy][3.9] Clear confirm_token when no longer needed
  components/com_privacy/models/confirm.php
Labels: PR-staging

#22746 [com_privacy][3.9] Make urgent less meh, give more room for date
  administrator/components/com_privacy/views/requests/tmpl/default.php
Labels: PR-staging

#22688 Common class for list type modules
  modules/mod_articles_archive/tmpl/default.php
  modules/mod_articles_categories/tmpl/default.php
  modules/mod_articles_category/tmpl/default.php
  modules/mod_articles_latest/tmpl/default.php
  modules/mod_articles_news/tmpl/horizontal.php
  modules/mod_articles_news/tmpl/vertical.php
  modules/mod_articles_popular/tmpl/default.php
  modules/mod_menu/tmpl/default.php
  modules/mod_related_items/tmpl/default.php
  modules/mod_users_latest/tmpl/default.php
Labels: RTC

#22691 [3.9.0] Enable privacy modules in sql updates
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-20.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-20.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-20.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-12.sql
Labels: PR-staging

#22682 [plugin][invisible recapctha] - detect correct IP address
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
Labels: PR-staging

#22672 [plugin][recaptcha] - detect correct IP address
  plugins/captcha/recaptcha/recaptcha.php
Labels: PR-staging

#22671 [com_content] - detect correct IP address when voting
  components/com_content/models/article.php
Labels: PR-staging

#22670 [com_actionlogs] - detect correct IP address
  administrator/components/com_actionlogs/models/actionlog.php
Labels: PR-staging

#22579 [3.9] Making the alias menu item multilingual aware (for core menu module only)
  modules/mod_menu/helper.php
Labels: PR-staging, RTC

#22811 [4.0] Fix drone errors coming from debug plugin
  plugins/system/debug/debug.php
Labels: PR-4.0-dev

#22786 [4.0]Fix loading language files from module extension folder
  libraries/src/Dispatcher/AbstractModuleDispatcher.php
Labels: PR-4.0-dev

#22808 Only get config and user from factory when needed in `JHtml::date()`
  libraries/src/HTML/HTMLHelper.php
Labels: PR-staging
