Repository joomla/joomla-cms, pull requests merged in 2018-12, with the labels that each got.

#23194 [FIX 3.9.1] Add column alias com_finder Search Filter (Published state broken)
  administrator/components/com_finder/tables/filter.php
Labels: RTC

#23193 [FIX 3.9.1] Add column alias com_banners Clients (Published state broken)
  administrator/components/com_banners/tables/client.php
Labels: RTC

#23192 [FIX 3.9.1] Add column alias com_messages (Read state broken)
  administrator/components/com_messages/tables/message.php
Labels: RTC

#23191 [FIX 3.9.1] Add column alias com_users Notes (Published state broken)
  administrator/components/com_users/tables/note.php
Labels: RTC

#23174 [mod_languages] - no need of cache fields
  modules/mod_languages/mod_languages.xml
Labels: RTC

#23166 [mod_syndicate] - no need field cache
  modules/mod_syndicate/mod_syndicate.xml
Labels: RTC

#23165 [mod_random_image] - no need field cache
  modules/mod_random_image/mod_random_image.xml
Labels: RTC

#23152 [mod_login] - no need field cache
  modules/mod_login/mod_login.xml
Labels: RTC

#22955 [3.9] actions log. Fix possible "Undefined offset" with plugins
  administrator/components/com_actionlogs/helpers/actionlogs.php
Labels: RTC

#20584 Change spacer's tooltip from tooltip to popover
  libraries/joomla/form/fields/spacer.php
  tests/unit/suites/libraries/joomla/form/fields/JFormFieldSpacerTest.php
Labels: PR-staging, RTC, Unit/System Tests

#23220 [4.0] Fatal error in FormModel
  libraries/src/MVC/Model/FormModel.php
Labels: RTC

#23214 [4.0] Joomla update: correcting missing code from #23095
  administrator/components/com_cpanel/View/System/HtmlView.php
  build/media_src/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
Labels: PR-4.0-dev

#23200 Fix state not possible to be changed to unpublish, when Model's (J)Table does not set correct alias for 'published' column
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-staging, RTC

#22984 [libraries][installer] - ModuleAdapter
  libraries/src/Installer/Adapter/ModuleAdapter.php
Labels: PR-staging, RTC

#23196 [4.0] Add classes to represent help screens and move to the model
  administrator/components/com_cpanel/Entities/SystemHeader.php
  administrator/components/com_cpanel/Entities/SystemItem.php
  administrator/components/com_cpanel/Model/SystemModel.php
  administrator/components/com_cpanel/View/System/HtmlView.php
  administrator/components/com_cpanel/tmpl/system/default.php
  administrator/components/com_postinstall/Model/MessagesModel.php
Labels: PR-4.0-dev

#23230 [4.0] RTL admin various corrections
  administrator/components/com_admin/tmpl/sysinfo/default_directory.php
  administrator/components/com_cache/tmpl/cache/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/templates/atum/scss/template-rtl.scss
Labels: PR-4.0-dev

#23158 [4.0] npm build tools update
  .babelrc
  build/build-modules-js/babel.js
  build/build-modules-js/build-check.js
  build/build-modules-js/compile-es6.js
  build/build-modules-js/compilecejs.js
  build/build-modules-js/compilejs.js
  build/build-modules-js/compilescss.js
  build/build-modules-js/make-dir.js
  build/build-modules-js/minify-vendor.js
  build/build-modules-js/rootpath.js
  build/build-modules-js/update.js
  build/build-modules-js/walk-sync.js
  build/media_src/com_contact/js/categories-default.es6.js
  build/media_src/com_fields/js/admin-fields-modal.es6.js
  build/media_src/com_mailto/js/mailto-default.es6.js
  build/media_src/com_tags/js/tag-list.es6.js
  build/media_src/layouts/js/joomla/html/batch/batch-language.es6.js
  build/media_src/plg_installer_webinstaller/scss/client.scss
  build/media_src/plg_system_stats/js/stats.es6.js
  build/media_src/system/js/core.es6.js
  build/media_src/system/js/searchtools.es6.js
  build/warning_page/template.js
  package-lock.json
  package.json
  templates/system/build_incomplete.html
  templates/system/incompatible.html
Labels: PR-4.0-dev

#23238 Fix several TODOs in code
  libraries/src/Filesystem/FilesystemHelper.php
  libraries/src/Pagination/Pagination.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
Labels: PR-4.0-dev

#23120 [4.0] Fix notice in layouts/joomla/form/field/combo.php
  layouts/joomla/form/field/combo.php
Labels: PR-4.0-dev, RTC

#23253 PHP 7.3 warning in debug plugin
  plugins/system/debug/debug.php
Labels: PR-4.0-dev

#23112 [4.0] WebAsset for JHtmlJquery, JHtmlSearchtools
  build/media/legacy/joomla.asset.json
  build/media_src/system/joomla.asset.json
  libraries/cms/html/jquery.php
  libraries/cms/html/searchtools.php
Labels: PR-4.0-dev

#23169 [4.0] Custom Elements fix - editor none
  build/media/webcomponents/js/editor-none/editor-none.js
Labels: PR-4.0-dev

#23167 [4.0] Align editors to the rest of the plugins
  build/media/plg_editors_codemirror/css/codemirror.css
  build/media/plg_editors_tinymce/css/tinymce-builder.css
  build/media/plg_editors_tinymce/js/tinymce-builder.js
  build/media_src/plg_editors_tinymce/js/plugins/dragdrop/plugin.es6.js
  build/media_src/plg_editors_tinymce/js/tinymce.es6.js
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  plugins/editors/codemirror/layouts/editors/codemirror/styles.php
  plugins/editors/tinymce/field/tinymcebuilder.php
  plugins/editors/tinymce/tinymce.php
  templates/system/incompatible.html
Labels: PR-4.0-dev

#22827 [4.0] Protect the default workflow
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  administrator/components/com_workflow/Controller/StageController.php
  administrator/components/com_workflow/Controller/TransitionController.php
  administrator/components/com_workflow/Controller/WorkflowController.php
  administrator/components/com_workflow/Model/StageModel.php
  administrator/components/com_workflow/Model/StagesModel.php
  administrator/components/com_workflow/Model/TransitionModel.php
  administrator/components/com_workflow/Model/TransitionsModel.php
  administrator/components/com_workflow/Model/WorkflowModel.php
  administrator/components/com_workflow/Model/WorkflowsModel.php
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
  administrator/components/com_workflow/View/Workflow/HtmlView.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#21579 [4.0] Workflow prevent trashing of used stages/workflows
  administrator/components/com_content/Extension/ContentComponent.php
  administrator/components/com_workflow/Model/StageModel.php
  administrator/language/en-GB/en-GB.com_workflow.ini
  administrator/language/en-GB/en-GB.plg_content_joomla.ini
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Workflow/WorkflowServiceInterface.php
  plugins/content/joomla/joomla.php
  plugins/content/joomla/joomla.xml
Labels: Language Change, New Feature Workflow, PR-4.0-dev, RTC

#21705 [4.0] Respect stage ordering
  administrator/components/com_workflow/forms/transition.xml
  libraries/src/Form/Field/WorkflowstageField.php
Labels: New Feature Workflow, PR-4.0-dev

#22593 [4.0] Smart Search: Adding debug information
  administrator/components/com_finder/Controller/IndexerController.php
  administrator/components/com_finder/tmpl/indexer/default.php
  build/media_src/com_finder/js/indexer.es6.js
Labels: PR-4.0-dev, RTC

#23229 Improve Update Message, remember Users to make a backup
  administrator/components/com_installer/views/update/view.html.php
  administrator/components/com_joomlaupdate/views/default/view.html.php
  administrator/language/en-GB/en-GB.com_installer.ini
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-staging, RTC

#23091 TinyMCE modals (editors-xtd buttons) are responsive
  plugins/editors/tinymce/tinymce.php
Labels: PR-staging, RTC

#22546 Links to buttons
  administrator/components/com_associations/models/fields/modalassociation.php
  administrator/components/com_categories/models/fields/modal/category.php
  administrator/components/com_contact/models/fields/modal/contact.php
  administrator/components/com_content/models/fields/modal/article.php
  administrator/components/com_menus/models/fields/menutype.php
  administrator/components/com_menus/models/fields/modal/menu.php
  administrator/components/com_newsfeeds/models/fields/modal/newsfeed.php
  administrator/components/com_redirect/layouts/toolbar/batch.php
  administrator/templates/hathor/html/layouts/joomla/toolbar/batch.php
  administrator/templates/isis/html/layouts/joomla/form/field/media.php
  administrator/templates/isis/html/layouts/joomla/form/field/user.php
  administrator/templates/isis/html/layouts/joomla/toolbar/versions.php
  layouts/joomla/modal/header.php
  layouts/joomla/toolbar/batch.php
  templates/protostar/html/layouts/joomla/form/field/contenthistory.php
  templates/protostar/html/layouts/joomla/form/field/media.php
  templates/protostar/html/layouts/joomla/form/field/user.php
Labels: RTC

#18966 Only add search module in error page if current JDocument is HtmlDocument
  templates/beez3/error.php
  templates/protostar/error.php
Labels: PR-staging, RTC

#18554 [3.x][Installer] Add upload progress and improve error handling
  administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
  plugins/installer/packageinstaller/tmpl/default.php
Labels: Language Change, PR-staging, RTC

#23271 Fixing composr.lock file
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#23280 Merge in part of Joomla 3.8.8
  administrator/components/com_messages/Model/MessageModel.php
  administrator/language/en-GB/en-GB.com_messages.ini
  administrator/language/en-GB/en-GB.ini
  administrator/language/en-GB/en-GB.plg_editors_codemirror.ini
  build/build-modules-js/update.js
  components/com_contact/View/Contact/HtmlView.php
  language/en-GB/en-GB.com_messages.ini
  language/en-GB/en-GB.ini
  libraries/src/Installer/Installer.php
  plugins/authentication/ldap/ldap.php
  plugins/editors/codemirror/codemirror.php
  plugins/editors/codemirror/codemirror.xml
  plugins/search/content/content.php
Labels: Language Change, PR-4.0-dev

#23275 [4.0] Translating Joomla default workflow title
  administrator/components/com_workflow/tmpl/workflows/default.php
Labels: PR-4.0-dev, RTC

#23062 [4.0] Revert to jQuery in menus module selection till CE modals are used
  administrator/components/com_menus/tmpl/menus/default.php
  build/media_src/com_menus/js/admin-menus-default.es6.js
Labels: PR-4.0-dev, RTC

#23055 [4.0] Remove obsolete menu class "nav-pills" from menu modules' parameters and contact links
  components/com_contact/tmpl/contact/default_links.php
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev, RTC

#23093 [4.0] Update Joomla browser with system test fixes
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#23285 Merge in most the rest of Joomla 3.8.8
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Custom.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  administrator/components/com_admin/postinstall/updatedefaultsettings.php
  administrator/components/com_admin/sql/updates/mysql/3.8.8-2018-05-18.sql
  administrator/components/com_admin/sql/updates/postgresql/3.8.8-2018-05-18.sql
  administrator/components/com_categories/Helper/CategoryAssociationHelper.php
  administrator/components/com_finder/Service/HTML/Filter.php
  administrator/components/com_finder/helpers/indexer/indexer.php
  administrator/components/com_media/config.xml
  administrator/components/com_menus/tmpl/item/edit.php
  administrator/components/com_users/Model/UserModel.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/language/en-GB/en-GB.com_config.ini
  administrator/language/en-GB/en-GB.com_cpanel.ini
  administrator/language/en-GB/en-GB.plg_editors_codemirror.ini
  build/media/webcomponents/js/field-subform/field-subform.js
  components/com_contact/layouts/field/render.php
  components/com_contact/layouts/fields/render.php
  components/com_contact/tmpl/contact/default_user_custom_fields.php
  components/com_content/Helper/AssociationHelper.php
  components/com_content/Model/ArticlesModel.php
  components/com_content/View/Form/HtmlView.php
  components/com_content/helpers/route.php
  components/com_search/View/Search/HtmlView.php
  components/com_tags/Model/TagModel.php
  composer.json
  composer.lock
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_testing.sql
  layouts/joomla/edit/params.php
  libraries/src/Filesystem/Folder.php
  libraries/src/Form/Field/EditorField.php
  libraries/src/Form/Field/TagField.php
  libraries/src/Language/Associations.php
  libraries/src/Language/Language.php
  package-lock.json
  package.json
  plugins/authentication/ldap/ldap.xml
  plugins/content/emailcloak/emailcloak.xml
  plugins/content/joomla/joomla.xml
  plugins/content/pagebreak/pagebreak.xml
  plugins/content/pagenavigation/pagenavigation.xml
  plugins/editors/codemirror/codemirror.php
  plugins/editors/codemirror/codemirror.xml
  plugins/search/categories/categories.xml
  plugins/search/contacts/contacts.xml
  plugins/search/content/content.xml
  plugins/search/newsfeeds/newsfeeds.xml
  plugins/search/tags/tags.php
  plugins/search/tags/tags.xml
  plugins/twofactorauth/totp/totp.xml
  plugins/twofactorauth/yubikey/yubikey.xml
  plugins/user/contactcreator/contactcreator.xml
Labels: Composer Dependency Changed, Language Change, PR-4.0-dev

#23278 [Regression] Make a redirection optional for the menu item alias
  administrator/components/com_menus/models/forms/item.xml
  administrator/components/com_menus/models/forms/item_alias.xml
  administrator/components/com_menus/views/item/tmpl/edit.php
  administrator/language/en-GB/en-GB.com_menus.ini
  libraries/src/Application/CMSApplication.php
Labels: Language Change, PR-staging, RTC

#23274 Links to buttons
  administrator/components/com_banners/views/tracks/tmpl/default.php
  administrator/components/com_contact/views/contacts/tmpl/default_batch.php
  administrator/components/com_media/views/media/tmpl/default.php
  administrator/components/com_menus/views/item/tmpl/edit_modules.php
  administrator/components/com_menus/views/menus/tmpl/default.php
  administrator/components/com_messages/views/messages/view.html.php
  administrator/components/com_redirect/views/links/tmpl/default.php
  administrator/components/com_templates/helpers/html/templates.php
  administrator/components/com_users/helpers/html/users.php
  administrator/modules/mod_multilangstatus/tmpl/default.php
  administrator/templates/hathor/html/com_banners/tracks/default.php
  administrator/templates/hathor/html/com_menus/menus/default.php
  administrator/templates/hathor/html/com_templates/template/default.php
Labels: PR-staging, RTC

#23273 Correct markup in inline editing
  layouts/joomla/edit/frontediting_modules.php
Labels: RTC

#23248 [3.x] Trim extra spaces from download URL in com_installer and com_joomlaupdate
  administrator/components/com_installer/models/update.php
  administrator/components/com_joomlaupdate/models/default.php
Labels: RTC

#23244 Calendar off screen detection broken when window scrolled
  media/system/js/fields/calendar.js
  media/system/js/fields/calendar.min.js
Labels: PR-staging, RTC

#23135 Fix for Field Group being output when empty
  components/com_fields/layouts/fields/render.php
Labels: PR-staging, RTC

#23240 Fixing notices in debug plugin
  plugins/system/debug/debug.php
Labels: PR-staging

#21724 [4.0] Improve a11y for systeminformation
  administrator/components/com_admin/tmpl/sysinfo/default.php
  administrator/components/com_admin/tmpl/sysinfo/default_config.php
  administrator/components/com_admin/tmpl/sysinfo/default_directory.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpinfo.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
  administrator/components/com_admin/tmpl/sysinfo/default_system.php
  administrator/templates/atum/scss/pages/_com_admin.scss
  administrator/templates/atum/scss/template.scss
Labels: PR-4.0-dev, RTC

#23299 [4.0] Fix markup
  layouts/joomla/searchtools/grid/sort.php
Labels: RTC

#23308 Fix missing line numbers in language file errors when xdebug.file_link_format is not set
  build/media/plg_system_debug/widgets/languageErrors/widget.js
Labels: PR-4.0-dev

#23314 [4.0][a11y] Sysinfo table caption
  administrator/components/com_admin/tmpl/sysinfo/default_config.php
  administrator/components/com_admin/tmpl/sysinfo/default_directory.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
  administrator/components/com_admin/tmpl/sysinfo/default_system.php
Labels: PR-4.0-dev

#23313 [4.0] Language string. Correct typo unkown instead of unknown
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev, RTC

#23319 Fix Updater Stability Constant reference
  libraries/src/Updater/Update.php
Labels: PR-staging, RTC

#23303 Remove logic in library extension updates that causes them to be uninstalled for some unknown reason that makes absolutely zero sense
  libraries/src/Installer/Adapter/LibraryAdapter.php
Labels: PR-staging

#23190 Re-add generic CSS classes in subforms.
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable-table/section.php
  layouts/joomla/form/field/subform/repeatable.php
  layouts/joomla/form/field/subform/repeatable/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable/section.php
Labels: RTC

#23332 [4.0] [a11y] Views user/ usergroup permissions: Improve accessibility
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
Labels: PR-4.0-dev

#22393 [4.0] Workflow article buttons
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_content/View/Articles/HtmlView.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/articles/default_stage_body.php
  administrator/components/com_content/tmpl/articles/default_stage_footer.php
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.ini
  administrator/templates/atum/scss/blocks/_icons.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
  build/media/webcomponents/js/toolbar-button/toolbar-button.js
  build/media_src/com_content/js/admin-articles-default-stage-footer.es6.js
  build/media_src/com_content/js/admin-articles-workflow-buttons.es6.js
  layouts/joomla/toolbar/basic.php
  layouts/joomla/toolbar/dropdown.php
  libraries/src/Toolbar/Button/DropdownButton.php
  libraries/src/Toolbar/ToolbarButton.php
  templates/cassiopeia/scss/blocks/_icons.scss
Labels: Language Change, PR-4.0-dev, RTC

#23340 [4.0][a11y] Layout user modal: Dismiss button
  layouts/joomla/form/field/user.php
Labels: PR-4.0-dev

#23343 Merge in the rest of 3.8.8
  administrator/components/com_users/Controller/LevelController.php
  administrator/components/com_users/Model/LevelModel.php
  administrator/components/com_users/tmpl/level/edit.php
  administrator/components/com_users/tmpl/levels/default.php
  components/com_tags/Controller/TagsController.php
  installation/src/Model/ConfigurationModel.php
  installation/src/Model/DatabaseModel.php
  installation/src/Model/SetupModel.php
  libraries/src/Filter/InputFilter.php
  libraries/src/Session/Storage/JoomlaStorage.php
  modules/mod_random_image/tmpl/default.php
  plugins/fields/editor/editor.xml
  plugins/fields/editor/params/editor.xml
  plugins/fields/text/params/text.xml
  plugins/fields/text/text.xml
  plugins/fields/textarea/params/textarea.xml
  plugins/fields/textarea/textarea.xml
Labels: PR-4.0-dev

#23336 [4.0] Group toolbar buttons for com_menu
  administrator/components/com_menus/View/Items/HtmlView.php
Labels: PR-4.0-dev, RTC

#23337 [4.0] Group categories toolbar buttons
  administrator/components/com_categories/View/Categories/HtmlView.php
Labels: PR-4.0-dev, RTC

#23344 [4.0] Update database package to fix menu manager
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#23353 [4.0] Removing obsolete code from ComponentHelper
  libraries/src/Component/ComponentHelper.php
Labels: PR-4.0-dev

#23355 [4.0] Fixing bugs in menu manager (Redo of half of #23293)
  administrator/components/com_menus/Model/ItemModel.php
Labels: PR-4.0-dev

#19978 [com_fields] List field to always return array.
  administrator/components/com_fields/helpers/fields.php
  plugins/fields/list/list.php
Labels: PR-staging, RTC

#21898 [plugin][actionlog][joomla] - Notice when disabled
  administrator/components/com_actionlogs/models/fields/plugininfo.php
  administrator/language/en-GB/en-GB.plg_system_actionlogs.ini
  plugins/system/actionlogs/actionlogs.php
  plugins/system/actionlogs/forms/information.xml
Labels: Language Change, PR-staging, RTC

#22339 Option to stop robots inc banners views
  administrator/components/com_banners/config.xml
  administrator/language/en-GB/en-GB.com_banners.ini
  modules/mod_banners/helper.php
Labels: Language Change, New Feature, PR-staging, RTC

#22898 Document _getListCount() assumption of unique set by getListQuery()
  libraries/src/MVC/Model/BaseDatabaseModel.php
Labels: PR-staging, RTC

#23206 [ContenttypeField] Fix notice when using custom options
  libraries/src/Form/Field/ContenttypeField.php
Labels: RTC

#23259 com_media: normalizing uploaded file names
  administrator/components/com_media/controllers/file.json.php
  administrator/components/com_media/controllers/file.php
Labels: PR-staging, RTC

#23310 Batch article copy/move Fix json encoded values
  plugins/fields/repeatable/repeatable.php
Labels: PR-staging, RTC

#23342 [mod_latestactions] namespaced
  administrator/modules/mod_latestactions/helper.php
  administrator/modules/mod_latestactions/mod_latestactions.php
  administrator/modules/mod_latestactions/tmpl/default.php
Labels: PR-staging, RTC

#23351 [plugin][user][contactcreator] namespaced
  plugins/user/contactcreator/contactcreator.php
Labels: RTC

#23379 3.8.9 Merge part 2
  administrator/components/com_config/Controller/ApplicationController.php
  administrator/components/com_fields/Model/FieldModel.php
  administrator/components/com_finder/Model/IndexModel.php
  administrator/components/com_finder/Model/MapsModel.php
  administrator/components/com_finder/Table/FilterTable.php
  administrator/components/com_finder/Table/LinkTable.php
  administrator/components/com_finder/Table/MapTable.php
  administrator/components/com_finder/helpers/indexer/adapter.php
  administrator/components/com_finder/helpers/indexer/helper.php
  administrator/components/com_finder/helpers/indexer/query.php
  administrator/components/com_installer/Model/InstallerModel.php
  administrator/components/com_installer/Model/ManageModel.php
  administrator/components/com_installer/Model/UpdateModel.php
  administrator/components/com_installer/Model/UpdatesitesModel.php
  administrator/components/com_menus/Field/MenuItemByTypeField.php
  administrator/components/com_menus/Helper/MenusHelper.php
  administrator/components/com_menus/Model/ItemModel.php
  administrator/components/com_menus/View/Menutypes/HtmlView.php
  administrator/language/en-GB/en-GB.com_menus.ini
  administrator/language/en-GB/en-GB.mod_sampledata.ini
  administrator/modules/mod_feed/tmpl/default.php
  build/phpcs/Joomla/ruleset.xml
  components/com_banners/Model/BannerModel.php
  components/com_newsfeeds/tmpl/newsfeed/default.php
  libraries/src/Feed/Parser/RssParser.php
  libraries/src/Table/Asset.php
  libraries/src/UCM/UCMType.php
  modules/mod_feed/tmpl/default.php
Labels: Language Change, PR-4.0-dev

#23381 Fix javascript lint
  build/media_src/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_src/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
Labels: PR-4.0-dev

#23363 [4.0] ESLint javascript scripts or fail
  .drone.yml
  package.json
Labels: PR-4.0-dev, Unit/System Tests

#23389 Merge in 3.8.9 and 3.8.10
  administrator/components/com_admin/sql/updates/mysql/3.8.9-2018-06-19.sql
  administrator/components/com_admin/sql/updates/postgresql/3.8.9-2018-06-19.sql
  administrator/components/com_login/Model/LoginModel.php
  components/com_mailto/Model/MailtoModel.php
  components/com_users/Controller/UserController.php
  components/com_users/Model/LoginModel.php
  composer.json
  composer.lock
  libraries/loader.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Input/Input.php
  libraries/src/Installer/Installer.php
  modules/mod_articles_category/tmpl/default.php
  modules/mod_languages/tmpl/default.php
Labels: Composer Dependency Changed, PR-4.0-dev

#21532 Remove trash button from article toolbar
  administrator/components/com_content/View/Articles/HtmlView.php
Labels: PR-4.0-dev

#23362 [4.0] Drop for loops
  build/media_src/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_src/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_src/plg_quickicon_overridecheck/js/overridecheck.es6.js
Labels: PR-4.0-dev

#23411 [4.0] Make sure the SECURITY.md is not included in the final packages
  build/build.php
Labels: PR-4.0-dev
