Repository joomla/joomla-cms, pull requests merged in 2019-02, with the labels that each got.

#23604 [staging] Bug: Correcting mod_custom-like module edit in frontend
  components/com_config/view/modules/tmpl/default.php
Labels: PR-staging, RTC

#23585 [staging] Deleting unused Contacts "banned" fields
  administrator/components/com_contact/models/forms/contact.xml
  administrator/language/en-GB/en-GB.com_contact.ini
  components/com_contact/models/forms/form.xml
  components/com_contact/views/categories/tmpl/default.xml
  components/com_contact/views/category/tmpl/default.xml
  components/com_contact/views/contact/tmpl/default.xml
  components/com_contact/views/featured/tmpl/default.xml
  installation/sql/mysql/sample_brochure.sql
  installation/sql/mysql/sample_learn.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/sample_brochure.sql
  installation/sql/postgresql/sample_learn.sql
  installation/sql/postgresql/sample_testing.sql
  installation/sql/sqlazure/sample_brochure.sql
  installation/sql/sqlazure/sample_learn.sql
  installation/sql/sqlazure/sample_testing.sql
  language/en-GB/en-GB.com_contact.ini
  tests/unit/stubs/database/jos_contact_details.csv
  tests/unit/stubs/database/jos_menu.csv
Labels: RTC

#23693 [3.9][a11y] Improve accessiblity in mod_finder
  modules/mod_finder/tmpl/default.php
Labels: RTC

#23722 [staging] Correcting multilingual status module when a content language is in the trash
  administrator/components/com_languages/views/multilangstatus/tmpl/default.php
  administrator/language/en-GB/en-GB.com_languages.ini
Labels: Language Change, PR-staging, RTC

#23736 [Smart Search] Taxonomy node values should not be added as search terms in the index
  administrator/components/com_finder/helpers/indexer/driver/mysql.php
  administrator/components/com_finder/helpers/indexer/driver/postgresql.php
  administrator/components/com_finder/helpers/indexer/driver/sqlsrv.php
Labels: PR-staging

#23726 [4.0] Correcting success colour after installing sample data
  build/media_src/mod_sampledata/js/sampledata-process.es6.js
Labels: PR-4.0-dev, RTC

#23719 [4.0] Normalize sample data plugins to use Joomla default workflow
  administrator/language/en-GB/en-GB.plg_sampledata_blog.ini
  administrator/language/en-GB/en-GB.plg_sampledata_multilang.ini
  plugins/sampledata/blog/blog.php
  plugins/sampledata/multilang/multilang.php
Labels: Language Change, PR-4.0-dev, RTC

#23673 Invalid field settings
  administrator/components/com_templates/config.xml
Labels: RTC

#23704 [4.0] Fix database name validation for MySQL in installation app
  installation/language/en-GB/en-GB.ini
  installation/src/Model/DatabaseModel.php
  installation/src/Model/SetupModel.php
Labels: Language Change, PR-4.0-dev, RTC

#23688 [4.0] Fix save contact
  administrator/components/com_contact/Table/ContactTable.php
Labels: PR-4.0-dev, RTC

#23653 [4.0] Remove libraries/cms/html/language/en-GB/en-GB.jhtmldate.ini
  libraries/cms/html/language/en-GB/en-GB.jhtmldate.ini
Labels: PR-4.0-dev, RTC

#22860 [4.0] Clean the node modules in the media folder on install
  package.json
Labels: PR-4.0-dev, RTC

#23727 [4.0] Fix stats alert information
  build/media_src/plg_system_stats/js/stats-message.es6.js
Labels: RTC

#23750 [4.0] Remove unused string
  administrator/templates/atum/language/en-GB/en-GB.tpl_atum.ini
Labels: Language Change, PR-4.0-dev

#23753 [4.0] Remove extra type attribute
  administrator/components/com_content/View/Article/HtmlView.php
Labels: PR-4.0-dev, RTC

#23718 [4.0] [a11y] Make ActionButton Featured accessible
  administrator/components/com_content/tmpl/articles/default.php
  layouts/joomla/button/action-button.php
Labels: PR-4.0-dev, RTC

#23731 [4.0] Fixes #20374 Cannot order on plugins page
  administrator/components/com_plugins/tmpl/plugins/default.php
Labels: PR-4.0-dev, RTC

#23642 [4.0] Fix for #23629
  build/media_src/com_modules/js/admin-module-edit.es6.js
Labels: PR-4.0-dev, RTC

#23638 [4.0] - fix save article
  libraries/src/Table/Content.php
Labels: PR-4.0-dev, RTC

#23330 Clean up hard coded usage of state values
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_content/Service/HTML/Icon.php
  components/com_content/tmpl/featured/default_item.php
Labels: PR-4.0-dev, RTC

#23669 [4.0] FIX SQL int default value to numeric
  administrator/components/com_finder/sql/install.mysql.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev, RTC

#23607 [4.0] Set default workflow for protected workflows
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
Labels: PR-4.0-dev, RTC

#23388 [4.0] fix a todo, drop the slider button
  build/media_src/system/js/showon.es6.js
  layouts/joomla/toolbar/slider.php
  libraries/classmap.php
  libraries/src/Toolbar/Button/SliderButton.php
Labels: Documentation Required, PR-4.0-dev, RTC

#23771 [4.0] remove duplicate string
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, PR-4.0-dev

#23716 [4.0] Fix: Saving menu item fails. Call to a member function validate() on bool. Field "show_associations"
  administrator/components/com_content/Model/ArticleModel.php
  libraries/src/Form/Form.php
  libraries/src/Form/FormField.php
Labels: PR-4.0-dev, RTC

#23788 Fix running npm install and npm ci
  package.json
Labels: PR-4.0-dev

#23789 Some webcomponents already pass linting
  .eslintignore
Labels: PR-4.0-dev

#23804 [4.0] Disable Back to Control Panel link
  administrator/templates/atum/index.php
Labels: PR-4.0-dev, RTC

#23691 [3.9][a11y] Add landmark to breadcrumbs
  modules/mod_breadcrumbs/tmpl/default.php
Labels: PR-staging, RTC

#23599 Breadcrumbs for tags
  components/com_tags/views/tag/view.html.php
Labels: PR-staging, RTC

#23595 [com_tags] Fix field name typo
  administrator/components/com_tags/config.xml
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
  tests/unit/stubs/database/jos_extensions.csv
Labels: PR-staging, RTC, Unit/System Tests

#23593 List of all tags
  components/com_tags/views/tags/tmpl/default_items.php
Labels: PR-staging, RTC

#23852 [com_actionlogs] username vs name on checkin
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging

#23857 [com_actionlogs] Fix plugin links
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging, RTC

#23873 Resolve GPL compliance issue on third-party libraries
  libraries/fof/database/query.php
  libraries/fof/dispatcher/dispatcher.php
  libraries/fof/encrypt/aes.php
  libraries/fof/form/field/actions.php
  libraries/fof/form/field/calendar.php
  libraries/fof/form/field/components.php
  libraries/fof/form/field/imagelist.php
  libraries/fof/form/field/list.php
  libraries/fof/form/field/media.php
  libraries/fof/form/field/published.php
  libraries/fof/form/header.php
  libraries/fof/form/header/fielddate.php
  libraries/fof/include.php
  libraries/fof/utils/installscript/installscript.php
  libraries/fof/view/view.php
Labels: PR-staging

#23880 [4.0] fix media edit modal cancel button
  build/media_source/com_media/js/edit-images.es6.js
Labels: PR-4.0-dev, RTC

#23878 [4.0]fixed language of 'insert image' to 'Insert Image'
  administrator/language/en-GB/en-GB.plg_editors-xtd_image.ini
  plugins/editors-xtd/image/image.php
Labels: Language Change, PR-4.0-dev, RTC

#23797 [4.0] Plugins Change status
  administrator/components/com_plugins/View/Plugins/HtmlView.php
Labels: PR-4.0-dev, RTC

#23784 [staging] Category and field date fields do not display jalali date
  administrator/components/com_categories/models/forms/category.xml
  administrator/components/com_fields/models/forms/field.xml
Labels: PR-staging

#23834 [4.0][a11n] Incorrectly named ARIA attribute
  build/media_source/system/js/fields/joomla-field-switcher.w-c.es6.js
Labels: PR-4.0-dev, RTC

#22177 Isis template button group handling
  administrator/templates/isis/js/template.js
Labels: PR-staging, RTC

#23917 Update htaccess.txt
  htaccess.txt
Labels: PR-staging

#23916 Update robots.txt.dist
  robots.txt.dist
Labels: PR-staging

#23842 Deprecating several backend menu related classes for 4.0
  administrator/components/com_menus/helpers/menus.php
  administrator/modules/mod_menu/helper.php
  administrator/modules/mod_menu/menu.php
  libraries/src/Menu/MenuHelper.php
  libraries/src/Menu/Node.php
  libraries/src/Menu/Node/Component.php
  libraries/src/Menu/Node/Container.php
  libraries/src/Menu/Node/Heading.php
  libraries/src/Menu/Node/Separator.php
  libraries/src/Menu/Node/Url.php
  libraries/src/Menu/Tree.php
Labels: PR-3.10-dev

#23922 [4.0][a11y] Labels Module Assignment are not associated with forms
  administrator/components/com_modules/tmpl/module/edit_assignment.php
Labels: PR-4.0-dev, RTC

#23921 [4.0] User Notes Category tags
  administrator/components/com_categories/forms/category.xml
Labels: PR-4.0-dev

#23930 [4.0] Field Display when read only
  administrator/components/com_fields/forms/field.xml
Labels: PR-4.0-dev

#23855 [4.0] Improve a Language String
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/language/en-GB/en-GB.com_templates.ini
Labels: Language Change, PR-4.0-dev, RTC

#23787 Add layouts to plg_user_terms
  layouts/plugins/user/terms/label.php
  layouts/plugins/user/terms/message.php
  plugins/user/terms/field/terms.php
Labels: PR-staging

#23903 [4.0] Fix calendar tweaks
  administrator/templates/atum/scss/vendor/bootstrap/_table.scss
  build/media_source/system/css/fields/calendar-rtl.css
  build/media_source/system/css/fields/calendar.css
Labels: PR-4.0-dev

#23660 Add layouts to plg_system_privacyconsent
  layouts/plugins/system/privacyconsent/label.php
  layouts/plugins/system/privacyconsent/message.php
  plugins/system/privacyconsent/field/privacy.php
Labels: PR-staging, RTC

#23768 [4.0] Fancy Select custom element improvements
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
Labels: NPM Dependency Changed, PR-4.0-dev

#23927 [4.0] Style legend the same as label
  administrator/templates/atum/scss/blocks/_form.scss
Labels: PR-4.0-dev

#23662 [a11y] Fix aria attribute aria-sort
  build/media_source/system/js/searchtools.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#23884 [Staging] Correcting some spelling and alpha order in new lang strings
  administrator/language/en-GB/en-GB.com_config.ini
  administrator/language/en-GB/en-GB.com_cpanel.ini
Labels: Language Change, PR-staging

#23847 [4.0] Update joomla/console package and adapt code to changes
  composer.lock
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Console/CheckUpdatesCommand.php
  libraries/src/Console/CleanCacheCommand.php
  libraries/src/Console/RemoveOldFilesCommand.php
  libraries/src/Console/SessionGcCommand.php
  libraries/src/Console/SessionMetadataGcCommand.php
  libraries/src/Service/Provider/Application.php
Labels: Composer Dependency Changed, PR-4.0-dev

#23953 [4.0] Update media manager dependency (browserify)
  administrator/components/com_media/package-lock.json
  administrator/components/com_media/package.json
Labels: NPM Resource Changed, PR-4.0-dev

#23942 [4.0] Changes in Toolbar, separate Save (and stay) button from Save button …
  administrator/components/com_admin/View/Profile/HtmlView.php
  administrator/components/com_banners/View/Banner/HtmlView.php
  administrator/components/com_banners/View/Client/HtmlView.php
  administrator/components/com_categories/View/Category/HtmlView.php
  administrator/components/com_config/View/Application/HtmlView.php
  administrator/components/com_config/View/Component/HtmlView.php
  administrator/components/com_contact/View/Contact/HtmlView.php
  administrator/components/com_content/View/Article/HtmlView.php
  administrator/components/com_fields/View/Field/HtmlView.php
  administrator/components/com_fields/View/Group/HtmlView.php
  administrator/components/com_finder/View/Filter/HtmlView.php
  administrator/components/com_languages/View/Language/HtmlView.php
  administrator/components/com_languages/View/Override/HtmlView.php
  administrator/components/com_menus/View/Item/HtmlView.php
  administrator/components/com_menus/View/Menu/HtmlView.php
  administrator/components/com_modules/View/Module/HtmlView.php
  administrator/components/com_newsfeeds/View/Newsfeed/HtmlView.php
  administrator/components/com_plugins/View/Plugin/HtmlView.php
  administrator/components/com_redirect/View/Link/HtmlView.php
  administrator/components/com_tags/View/Tag/HtmlView.php
  administrator/components/com_templates/View/Style/HtmlView.php
  administrator/components/com_templates/View/Template/HtmlView.php
  administrator/components/com_users/View/Group/HtmlView.php
  administrator/components/com_users/View/Level/HtmlView.php
  administrator/components/com_users/View/Note/HtmlView.php
  administrator/components/com_users/View/User/HtmlView.php
  administrator/components/com_workflow/View/Stage/HtmlView.php
  administrator/components/com_workflow/View/Transition/HtmlView.php
  administrator/components/com_workflow/View/Workflow/HtmlView.php
Labels: PR-4.0-dev

#23583 Featured articles page subheading
  components/com_content/views/featured/tmpl/default.php
  components/com_content/views/featured/tmpl/default.xml
Labels: PR-staging

#23970 [4.0] Checkboxes [a11y]
  layouts/joomla/form/field/checkboxes.php
  plugins/editors/codemirror/codemirror.xml
Labels: PR-4.0-dev

#23940 [4.0]Added placeholder for tag
  administrator/components/com_tags/forms/tag.xml
Labels: PR-4.0-dev, RTC

#23936 System dashboard
  administrator/components/com_cpanel/Controller/SystemController.php
  administrator/components/com_cpanel/Entities/SystemItem.php
  administrator/components/com_cpanel/Model/SystemModel.php
  administrator/components/com_cpanel/tmpl/system/default.php
  administrator/language/en-GB/en-GB.com_cpanel.ini
  build/media_source/com_cpanel/js/admin-system-loader.es6.js
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#23458 [4.0] Workflow new article stage category change
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  administrator/components/com_categories/Field/CategoryeditField.php
  administrator/components/com_categories/layouts/joomla/form/field/categoryedit.php
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_fields/Helper/FieldsHelper.php
  administrator/components/com_workflow/Model/WorkflowModel.php
  build/media_source/layouts/js/joomla/form/field/category-change.es6.js
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  layouts/joomla/edit/global.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#23742 [4.0] Do NOT force jQuery.js and Bootstrap.js in the backend template
  administrator/components/com_cpanel/tmpl/cpanel/default.php
  administrator/modules/mod_feed/tmpl/default.php
  administrator/modules/mod_latest/tmpl/default.php
  administrator/modules/mod_logged/tmpl/default.php
  administrator/modules/mod_multilangstatus/tmpl/default.php
  administrator/modules/mod_popular/tmpl/default.php
  administrator/modules/mod_sampledata/tmpl/default.php
  administrator/modules/mod_status/tmpl/default.php
  administrator/templates/atum/component.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/joomla.asset.json
Labels: PR-4.0-dev

#23729 [4.0] Permissions custom element improvements
  build/media_source/system/js/fields/joomla-field-permissions.w-c.es6.js
  build/media_source/system/scss/fields/joomla-field-permissions.scss
Labels: NPM Resource Changed, PR-4.0-dev

#23918 [install] - validate username
  installation/form/rule/username.php
  installation/model/forms/site.xml
Labels: PR-staging, RTC

#23730 [4.0] Hidden-mail custom element improvements
  build/media_source/system/js/joomla-hidden-mail.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#23901 [4.0] Wrong string in com_users
  administrator/components/com_users/Service/HTML/Users.php
Labels: PR-4.0-dev, RTC

#23747 [4.0] Fixes issue #23746- unclear sidebar
  administrator/templates/atum/scss/blocks/_sidebar-nav.scss
Labels: PR-4.0-dev, RTC

#23990 [4.0][com_tag] - class not found
  components/com_tags/Model/TagModel.php
Labels: PR-4.0-dev, RTC

#23919 [4.0] [a11y] aria-describedby when field has a description
  layouts/joomla/form/field/accesslevel.php
  layouts/joomla/form/field/calendar.php
  layouts/joomla/form/field/combo.php
  layouts/joomla/form/field/email.php
  layouts/joomla/form/field/list.php
  layouts/joomla/form/field/number.php
  layouts/joomla/form/field/range.php
  layouts/joomla/form/field/tel.php
  layouts/joomla/form/field/text.php
  layouts/joomla/form/field/textarea.php
  layouts/joomla/form/field/url.php
  layouts/joomla/form/renderfield.php
Labels: PR-4.0-dev

#24017 [3.9] Remove sourcecode from RIPS after scan is finished
  .drone.yml
Labels: PR-staging, Unit/System Tests

#23741 [staging] Follow up on #23604 Custom modules editor field
  administrator/components/com_modules/views/module/tmpl/edit.php
  components/com_config/view/modules/tmpl/default.php
Labels: PR-staging, RTC

#24014 [4.0] Wrong toolbar preferences for com_contact
  administrator/components/com_contact/View/Contacts/HtmlView.php
Labels: RTC

#24009 [4.0] mso/idna-convert is abandoned
  composer.json
Labels: Composer Dependency Changed, PR-4.0-dev

#24016 [4.0] Adjust CI call to RIPS
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#23902 [4.0] Text overlapping in image info
  administrator/components/com_media/resources/styles/components/_media-infobar.scss
Labels: NPM Resource Changed, PR-4.0-dev

#24011 [4.0] Removing legacy module chromes
  templates/system/html/modules.php
Labels: PR-4.0-dev

#22645 Formfield layouts
  libraries/src/Form/FormField.php
  tests/unit/suites/libraries/joomla/form/JFormFieldTest.php
  tests/unit/suites/libraries/joomla/form/_testfields/customlayouts.php
Labels: PR-staging, RTC, Unit/System Tests

#24018 [4.0] Media Manager create new folder: placeholder removed and text changed
  administrator/components/com_media/resources/scripts/components/modals/create-folder-modal.vue
  administrator/components/com_media/resources/scripts/components/modals/modal.vue
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#23756 [4.0] [NO CACHE] Fix Media Manager delete alert not used.
  administrator/components/com_media/layouts/toolbar/delete.php
  administrator/components/com_media/layouts/toolbar/upload.php
  administrator/components/com_media/resources/scripts/components/app.vue
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  administrator/components/com_media/resources/scripts/components/modals/confirm-delete-modal.vue
  administrator/components/com_media/resources/scripts/store/actions.js
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#23950 [4.0] [a11y] [NO CACHE] Make media manager browse view work with keyboard navigation
  administrator/components/com_media/resources/scripts/app/Api.js
  administrator/components/com_media/resources/scripts/components/app.vue
  administrator/components/com_media/resources/scripts/components/breadcrumb/breadcrumb.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.js
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  administrator/components/com_media/resources/scripts/components/modals/preview-modal.vue
  administrator/components/com_media/resources/scripts/components/modals/rename-modal.vue
  administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue
  administrator/components/com_media/resources/scripts/plugins/translate.js
  administrator/components/com_media/resources/scripts/store/actions.js
  administrator/components/com_media/resources/styles/components/_media-breadcrumb.scss
  administrator/components/com_media/resources/styles/components/_media-browser.scss
  administrator/components/com_media/resources/styles/components/_media-toolbar.scss
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24036 Missing translation of error text
  libraries/src/Table/Asset.php
Labels: PR-staging

#24006 [4.0][a11y] 'Print' button changes from styled link to button
  administrator/components/com_content/Service/HTML/Icon.php
Labels: PR-4.0-dev, RTC

#23985 [4.0] [a11y] Incorrect buttons
  administrator/components/com_categories/Field/Modal/CategoryField.php
  administrator/components/com_contact/Field/Modal/ContactField.php
  administrator/components/com_content/Field/Modal/ArticleField.php
  administrator/components/com_menus/Field/Modal/MenuField.php
  administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
  build/media_source/system/js/fields/modal-fields.es5.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#24013 [4.0][a11y] Toolbar in a nav tag
  layouts/joomla/toolbar/containerclose.php
  layouts/joomla/toolbar/containeropen.php
Labels: PR-4.0-dev, RTC

#23870 [4.0][a11y] Missing ID attribute in the input field on the Smart Search module
  modules/mod_finder/tmpl/default.php
Labels: PR-4.0-dev, RTC

#23694 [4.0][a11y] Improve accessiblity in mod_search
  modules/mod_search/tmpl/default.php
Labels: PR-4.0-dev, RTC

#23685 [4.0][a11y] Add landmark to breadcrumbs
  modules/mod_breadcrumbs/tmpl/default.php
Labels: PR-4.0-dev

#23996 [4.0] Fix wrong transition XML for article edit
  administrator/components/com_content/forms/article.xml
  components/com_content/forms/article.xml
Labels: PR-4.0-dev, RTC

#23407 [4.0] Prevent loading LoadingLayer twice
  build/media_source/system/js/core.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#23739 [4.0] Deleting obsolete template.min.js
  administrator/templates/atum/js/template.min.js
Labels: PR-4.0-dev

#23591 [4.0][com_config] Fixed sending the test mail
  administrator/language/en-GB/en-GB.com_config.ini
  build/media_source/system/js/fields/joomla-field-send-test-mail.w-c.es6.js
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#23752 [4.0] Disable status module links
  administrator/modules/mod_status/tmpl/default.php
Labels: PR-4.0-dev

#23882 [4.0] Field media custom element clean up
  .eslintignore
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  build/media_source/system/scss/fields/joomla-field-media.scss
Labels: NPM Resource Changed, PR-4.0-dev

#24037 [4.0] Update composer deps
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#21327 [4.0] Smart Search: Adding nested taxonomy
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-16.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-16.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-29.sql
  administrator/components/com_finder/Model/IndexModel.php
  administrator/components/com_finder/Model/MapsModel.php
  administrator/components/com_finder/Service/HTML/Filter.php
  administrator/components/com_finder/Table/MapTable.php
  administrator/components/com_finder/helpers/indexer/driver/mysql.php
  administrator/components/com_finder/helpers/indexer/driver/postgresql.php
  administrator/components/com_finder/helpers/indexer/indexer.php
  administrator/components/com_finder/helpers/indexer/result.php
  administrator/components/com_finder/helpers/indexer/taxonomy.php
  administrator/components/com_finder/sql/install.mysql.sql
  administrator/components/com_finder/sql/install.postgresql.sql
  administrator/components/com_finder/tmpl/maps/default.php
  administrator/language/en-GB/en-GB.plg_extension_finder.ini
  administrator/language/en-GB/en-GB.plg_extension_finder.sys.ini
  components/com_finder/tmpl/search/default_result.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  language/en-GB/en-GB.com_finder.commonwords.txt
  plugins/extension/finder/finder.php
  plugins/extension/finder/finder.xml
  plugins/finder/contacts/contacts.php
  plugins/finder/content/content.php
  plugins/finder/newsfeeds/newsfeeds.php
Labels: Language Change, PR-4.0-dev

#24043 [4.0][com_media] RTL: adapting media manager to rtl + some
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/resources/scripts/components/infobar/infobar.vue
  administrator/components/com_media/resources/styles/components/_media-breadcrumb.scss
  administrator/components/com_media/resources/styles/components/_media-infobar.scss
  administrator/components/com_media/resources/styles/components/_media-tree.scss
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
  plugins/filesystem/local/Adapter/LocalAdapter.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24003 [4.0] Update bootstrap version
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#23563 Single contact - show contact name
  components/com_contact/views/categories/tmpl/default.xml
  components/com_contact/views/category/tmpl/default.xml
  components/com_contact/views/contact/tmpl/default.xml
Labels: PR-staging, RTC

#24046 [4.0][com_finder] fix default date for postgresql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#24048 [4.0] Toolbar button consistency
  administrator/components/com_menus/View/Items/HtmlView.php
Labels: PR-4.0-dev

#24047 [4.0][com_finder] fix default date for postgresql on update
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-16.sql
Labels: PR-4.0-dev
