Repository joomla/joomla-cms, pull requests merged in 2019-06, with the labels that each got.

#25075 [4.0] Changelog: Correcting RTL display for the changelog modal
  administrator/templates/atum/scss/template-rtl.scss
Labels: PR-4.0-dev

#24971 Changed the default value to type double
  libraries/src/Profiler/Profiler.php
Labels: PR-staging, RTC

#25006 [4.0] Changing phpcs to run from composer and a generic image in drone
  .drone.yml
  build/phpcs/Joomla/ruleset.xml
Labels: PR-4.0-dev, Unit/System Tests

#25079 Code style. Remove space. plg_extension_joomla
  plugins/extension/joomla/joomla.php
Labels: RTC

#25081 [4.0] Fix install sample data
  administrator/components/com_content/Model/ArticleModel.php
Labels: PR-4.0-dev

#25082 [4.0] Select modal button
  administrator/components/com_categories/Field/Modal/CategoryField.php
  administrator/components/com_contact/Field/Modal/ContactField.php
  administrator/components/com_content/Field/Modal/ArticleField.php
  administrator/components/com_menus/Field/Modal/MenuField.php
  administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
  administrator/language/en-GB/en-GB.com_categories.ini
  administrator/language/en-GB/en-GB.com_contact.ini
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.com_menus.ini
  administrator/language/en-GB/en-GB.com_newsfeeds.ini
  administrator/language/en-GB/en-GB.plg_user_profile.ini
Labels: Language Change, PR-4.0-dev, RTC

#25089 [4.0] namespace error
  plugins/system/languagefilter/languagefilter.php
Labels: RTC

#25093 [4.0] @subpackage fixes
  administrator/components/com_actionlogs/models/fields/logtype.php
  administrator/components/com_admin/Extension/AdminComponent.php
  administrator/components/com_contenthistory/services/provider.php
  administrator/components/com_cpanel/tmpl/help/default.php
  administrator/components/com_cpanel/tmpl/system/default.php
  components/com_mailto/Model/MailtoModel.php
Labels: PR-4.0-dev

#25098 [4.0] @package fixes
  administrator/components/com_categories/layouts/joomla/form/field/categoryedit.php
  administrator/components/com_content/Service/HTML/Icon.php
  build/media_source/legacy/js/ajax-chosen.es5.js
  build/media_source/system/js/keepalive.es6.js
  components/com_config/Controller/ConfigController.php
  components/com_config/Controller/ModulesController.php
  components/com_config/Controller/TemplatesController.php
  components/com_config/Dispatcher/Dispatcher.php
  layouts/joomla/html/treeprefix.php
  libraries/src/Toolbar/ToolbarHelper.php
  plugins/actionlog/joomla/joomla.php
  templates/system/css/offline_rtl.css
Labels: NPM Resource Changed, PR-4.0-dev

#25097 [4.0] mod_banners does not load 'bannerclient' field type
  modules/mod_banners/mod_banners.xml
Labels: PR-4.0-dev

#25104 [4.0] Drone fix
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev

#25085 [4.0] Render label
  layouts/joomla/form/renderfield.php
Labels: PR-4.0-dev, RTC, a11y

#24956 [4.0] [mod_articles_category] Always render module layout
  modules/mod_articles_category/mod_articles_category.php
  modules/mod_articles_category/tmpl/default.php
Labels: PR-4.0-dev, RTC

#25071 [4.0] Always render module layout
  modules/mod_articles_archive/tmpl/default.php
  modules/mod_articles_categories/mod_articles_categories.php
  modules/mod_articles_categories/tmpl/default.php
  modules/mod_articles_latest/tmpl/default.php
  modules/mod_articles_news/tmpl/default.php
  modules/mod_articles_news/tmpl/horizontal.php
  modules/mod_articles_news/tmpl/vertical.php
  modules/mod_articles_popular/tmpl/default.php
Labels: PR-4.0-dev, RTC

#25100 [4.0] User group tabs
  administrator/components/com_users/tmpl/group/edit.php
Labels: PR-4.0-dev

#25108 [4.0] useCoreUI
  components/com_content/tmpl/form/edit.php
Labels: PR-4.0-dev

#25028 [4.0] Help Admin Menu item should always display
  administrator/components/com_cpanel/View/Help/HtmlView.php
  administrator/modules/mod_menu/Menu/CssMenu.php
Labels: PR-4.0-dev, RTC

#24965 [4.0] [com_contact] convert to prepared statement
  administrator/components/com_contact/Field/Modal/ContactField.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_contact/Model/ContactsModel.php
  components/com_contact/Model/CategoryModel.php
  components/com_contact/Model/ContactModel.php
  components/com_contact/Model/FeaturedModel.php
Labels: PR-4.0-dev

#25084 [4.0] Site Login Module does not load 'modal_menu' type
  modules/mod_login/mod_login.xml
Labels: PR-4.0-dev, RTC

#25083 [4.0] 3 plugins do not load the 'modal_article' type
  plugins/content/confirmconsent/confirmconsent.xml
  plugins/system/privacyconsent/privacyconsent.xml
  plugins/user/terms/terms.xml
Labels: PR-4.0-dev, RTC

#23107 RTL: adapting display of Joomla versions plus some
  administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
  administrator/components/com_joomlaupdate/views/default/tmpl/default_upload.php
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/less/template-rtl.less
  media/plg_quickicon_joomlaupdate/js/jupdatecheck.js
Labels: PR-staging, RTC

#25111 [4.0] Remove default class from tag form
  administrator/components/com_tags/forms/tag.xml
Labels: RTC

#25091 [4.0] Comments typo
  includes/app.php
Labels: PR-4.0-dev, RTC

#25112 [4.0] Replace old Bootstrap label classes with badge
  administrator/components/com_privacy/Service/HTML/Privacy.php
  administrator/components/com_privacy/tmpl/dashboard/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  components/com_content/tmpl/article/default.php
  components/com_content/tmpl/category/default_articles.php
  layouts/joomla/content/info_block/associations.php
Labels: RTC

#25113 [4.0] Remove control-label class from form field labels
  administrator/components/com_banners/forms/banner.xml
  administrator/components/com_banners/forms/client.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_tags/forms/tag.xml
  administrator/components/com_users/forms/note.xml
  components/com_content/forms/article.xml
Labels: RTC

#25119 [4.0] Fix saving custom fields without params
  administrator/components/com_fields/Table/FieldTable.php
Labels: RTC

#25120 [4.0] contact view
  components/com_contact/View/Contact/HtmlView.php
Labels: RTC

#24077 [4.0] Removing extra Expired Cache view and menu item
  administrator/components/com_cache/Controller/DisplayController.php
  administrator/components/com_cache/Helper/CacheHelper.php
  administrator/components/com_cache/View/Cache/HtmlView.php
  administrator/components/com_cache/View/Purge/HtmlView.php
  administrator/components/com_cache/tmpl/purge/default.php
  administrator/components/com_cache/tmpl/purge/default.xml
  administrator/components/com_cpanel/Model/SystemModel.php
Labels: PR-4.0-dev, RTC

#25038 iFrameHeight() needs to be called with a reference to the iframe-object
  components/com_wrapper/views/wrapper/view.html.php
Labels: PR-staging, RTC

#24089 Choose the correct protocol in route::link when force https is disabled
  administrator/components/com_actionlogs/helpers/actionlogs.php
  administrator/components/com_messages/models/message.php
  administrator/components/com_privacy/models/dashboard.php
  administrator/components/com_privacy/models/request.php
  components/com_privacy/models/request.php
  components/com_users/models/registration.php
  libraries/src/Router/Route.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-staging, RTC

#24932 Wrong item category shown in category feed
  libraries/src/MVC/View/CategoryFeedView.php
Labels: PR-staging, RTC

#24927 remove Help Server unofficial property
  administrator/components/com_admin/models/forms/profile.xml
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.7-2019-05-16.sql
  administrator/components/com_config/model/form/application.xml
  administrator/components/com_users/controllers/profile.json.php
  administrator/components/com_users/models/forms/user.xml
  administrator/help/helpsites.xml
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/language/en-GB/en-GB.com_config.ini
  administrator/language/en-GB/en-GB.com_users.ini
  administrator/language/en-GB/en-GB.ini
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/less/blocks/_custom.less
  components/com_users/controllers/profile.json.php
  components/com_users/controllers/profile_base_json.php
  components/com_users/models/forms/frontend_admin.xml
  installation/application/web.php
  installation/localise.xml
  language/en-GB/en-GB.com_users.ini
  language/en-GB/en-GB.ini
  libraries/src/Form/Field/HelpsiteField.php
  libraries/src/Help/Help.php
  templates/protostar/css/template.css
  templates/protostar/less/template.less
  tests/unit/suites/libraries/cms/form/field/JFormFieldHelpsiteTest.php
Labels: Language Change, PR-staging, RTC, Unit/System Tests

#24924 com_mediamanger fix for failure to traverse/create/delete directories
  administrator/components/com_media/controllers/file.json.php
  administrator/components/com_media/controllers/file.php
  administrator/components/com_media/controllers/folder.php
  administrator/components/com_media/models/list.php
Labels: PR-staging, RTC

#25062 Fixing a mistake made with PR #24397 + fixing setting description for clarity
  administrator/components/com_fields/libraries/fieldsplugin.php
  administrator/components/com_fields/models/forms/field.xml
  administrator/language/en-GB/en-GB.com_fields.ini
Labels: Documentation Required, Language Change, PR-staging, RTC

#25037 Tinymce doesn't need to remove the images basepath
  plugins/editors/tinymce/tinymce.php
Labels: PR-staging, RTC

#24627 Remove chosen from com_tags
  components/com_tags/views/tags/tmpl/default_items.php
Labels: PR-staging, RTC

#24999 Pg schema
  libraries/joomla/database/driver/postgresql.php
Labels: PR-staging, RTC

#24978 [staging] Update TinyMCE
  administrator/language/en-GB/en-GB.plg_editors_tinymce.ini
  media/editors/tinymce/changelog.txt
  media/editors/tinymce/themes/modern/theme.min.js
  media/editors/tinymce/tinymce.min.js
  plugins/editors/tinymce/tinymce.xml
Labels: Language Change, PR-staging, RTC

#24947 Move a subform template out of the form scope, for IE compatibility
  media/system/js/subform-repeatable-uncompressed.js
  media/system/js/subform-repeatable.js
Labels: PR-staging, RTC

#22936 If plugins return false when login, should mark as failure.
  libraries/src/Application/CMSApplication.php
Labels: PR-staging, RTC

#25076 Document loadmoduleid in plugin description
  administrator/language/en-GB/en-GB.plg_content_loadmodule.ini
  administrator/language/en-GB/en-GB.plg_content_loadmodule.sys.ini
Labels: Language Change, PR-staging, RTC

#25136 [4.0] Don't require some steps of CI
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#25138 Update SECURITY.md
  .github/SECURITY.md
Labels: RTC

#25123 [4.0] Media Manager icons in 2 columns
  administrator/components/com_media/resources/styles/components/_media-browser.scss
Labels: NPM Resource Changed, PR-4.0-dev

#24879 [4.0] [mod_tags_similar] Always render module layout
  language/en-GB/en-GB.mod_tags_similar.ini
  modules/mod_tags_similar/mod_tags_similar.php
  modules/mod_tags_similar/tmpl/default.php
Labels: Language Change, PR-4.0-dev, RTC

#25140 [4.0] Empty trash string
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, PR-4.0-dev

#24967 [4.0] Backend: add a note-field to plugins
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-05-20.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-05-20.sql
  administrator/components/com_plugins/Model/PluginsModel.php
  administrator/components/com_plugins/forms/plugin.xml
  administrator/components/com_plugins/tmpl/plugin/edit.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev, RTC

#25139 [4.0] Remove unused file
  administrator/components/com_fields/Field/Modal/FieldField.php
Labels: PR-4.0-dev

#25046 [4.0] Add prepared statements for plg_actionlog_joomla
  plugins/actionlog/joomla/joomla.php
Labels: PR-4.0-dev, RTC

#25078 [4.0] Handle errors generated by language downloads gracefully
  installation/template/js/remove.js
  installation/template/js/template.js
Labels: PR-4.0-dev, RTC

#25137 [4.0] Namespace
  administrator/components/com_templates/Model/TemplateModel.php
  administrator/components/com_workflow/Table/StageTable.php
  administrator/components/com_workflow/Table/TransitionTable.php
  administrator/components/com_workflow/Table/WorkflowTable.php
  build/helpTOC.php
  components/com_finder/View/Search/FeedView.php
  installation/src/Model/LanguagesModel.php
  libraries/src/Application/DaemonApplication.php
  libraries/src/Cache/Storage/RedisStorage.php
  libraries/src/Component/ComponentHelper.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Filter/InputFilter.php
  libraries/src/Image/Image.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/Log/Logger/FormattedtextLogger.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/View/CategoryFeedView.php
  libraries/src/MVC/View/ListView.php
  libraries/src/Mail/MailHelper.php
  libraries/src/Plugin/PluginHelper.php
  libraries/src/Table/User.php
  libraries/src/Table/Usergroup.php
  libraries/src/User/UserHelper.php
  plugins/content/confirmconsent/fields/consentbox.php
  plugins/filesystem/local/Adapter/LocalAdapter.php
  plugins/finder/contacts/contacts.php
  plugins/finder/content/content.php
  plugins/finder/newsfeeds/newsfeeds.php
  plugins/sampledata/multilang/multilang.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/debug/DataCollector/ProfileCollector.php
  plugins/system/privacyconsent/field/privacy.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-4.0-dev

#25126 [4.0] role =Button
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/modules/mod_multilangstatus/tmpl/default.php
Labels: PR-4.0-dev

#25121 [4.0] J Installation: Install Languages. Make sure the namespace autoloader exists
  installation/src/Application/InstallationApplication.php
Labels: PR-4.0-dev, RTC

#24990 Correct archived article links in search results
  plugins/search/content/content.php
Labels: PR-staging, RTC

#25147 [4.0] Fix History Versions Modal display
  administrator/components/com_banners/tmpl/banner/edit.php
  administrator/components/com_banners/tmpl/client/edit.php
  administrator/components/com_categories/tmpl/category/edit.php
  administrator/components/com_contact/tmpl/contact/edit.php
  administrator/components/com_content/tmpl/article/edit.php
  administrator/components/com_newsfeeds/tmpl/newsfeed/edit.php
  administrator/components/com_tags/tmpl/tag/edit.php
  administrator/components/com_users/tmpl/note/edit.php
  build/media_source/com_contenthistory/js/admin-history-versions.es5.js
Labels: NPM Resource Changed, PR-4.0-dev

#25146 [4.0] Fix reference in tos field
  plugins/user/profile/field/tos.php
Labels: PR-4.0-dev, RTC

#25148 [4.0] Cleanup controllers in Joomla
  administrator/components/com_actionlogs/controllers/actionlogs.php
  administrator/components/com_banners/Controller/TracksController.php
  administrator/components/com_categories/Controller/CategoryController.php
  administrator/components/com_categories/Controller/DisplayController.php
  administrator/components/com_config/Controller/ApplicationController.php
  administrator/components/com_config/Controller/RequestController.php
  administrator/components/com_contact/Controller/ContactController.php
  administrator/components/com_contact/Controller/ContactsController.php
  administrator/components/com_content/Controller/ArticleController.php
  administrator/components/com_content/Controller/ArticlesController.php
  administrator/components/com_content/Controller/FeaturedController.php
  administrator/components/com_cpanel/Controller/SystemController.php
  administrator/components/com_fields/Controller/FieldController.php
  administrator/components/com_fields/Controller/GroupController.php
  administrator/components/com_finder/Controller/FilterController.php
  administrator/components/com_finder/Controller/MapsController.php
  administrator/components/com_installer/Controller/DatabaseController.php
  administrator/components/com_installer/Controller/DisplayController.php
  administrator/components/com_installer/Controller/ManageController.php
  administrator/components/com_installer/Controller/UpdatesitesController.php
  administrator/components/com_languages/Controller/OverrideController.php
  administrator/components/com_languages/Controller/OverridesController.php
  administrator/components/com_menus/Controller/DisplayController.php
  administrator/components/com_menus/Controller/ItemController.php
  administrator/components/com_menus/Controller/ItemsController.php
  administrator/components/com_menus/Controller/MenusController.php
  administrator/components/com_messages/Controller/ConfigController.php
  administrator/components/com_modules/Controller/DisplayController.php
  administrator/components/com_modules/Controller/ModuleController.php
  administrator/components/com_privacy/Controller/DisplayController.php
  administrator/components/com_privacy/Controller/RequestController.php
  administrator/components/com_tags/Controller/TagsController.php
  administrator/components/com_templates/Controller/DisplayController.php
  administrator/components/com_templates/Controller/StyleController.php
  administrator/components/com_templates/Controller/StylesController.php
  administrator/components/com_templates/Controller/TemplateController.php
  administrator/components/com_users/Controller/UserController.php
  administrator/components/com_users/Controller/UsersController.php
  administrator/components/com_workflow/Controller/DisplayController.php
  administrator/components/com_workflow/Controller/StageController.php
  administrator/components/com_workflow/Controller/StagesController.php
  administrator/components/com_workflow/Controller/TransitionController.php
  administrator/components/com_workflow/Controller/TransitionsController.php
  administrator/components/com_workflow/Controller/WorkflowController.php
  administrator/components/com_workflow/Controller/WorkflowsController.php
Labels: PR-4.0-dev

#25142 Fix actionlogs when making a state change in the content list view
  administrator/components/com_content/Model/ArticleModel.php
  libraries/src/Workflow/Workflow.php
Labels: PR-4.0-dev

#25115 [4.0] Fix warning with cache enabled
  libraries/src/Document/Renderer/Html/ModuleRenderer.php
Labels: RTC

#25114 [4.0] Deleting apcu-7.3.ini
  build/travis/phpenv/apcu-7.3.ini
Labels: PR-4.0-dev

#22295 [4.0] Remove the deprecated code in the JHtmlBehavior class
  components/com_content/tmpl/article/default_links.php
  libraries/cms/html/behavior.php
  libraries/src/Form/Field/ModulepositionField.php
  libraries/src/HTML/HTMLHelper.php
  plugins/system/privacyconsent/field/privacy.php
  plugins/user/profile/field/tos.php
  plugins/user/terms/field/terms.php
Labels: Documentation Required, PR-4.0-dev

#25150 [4.0] Removed obsolete use statement
  administrator/components/com_actionlogs/controllers/actionlogs.php
Labels: PR-4.0-dev

#25053 [4.0] Add prepared statements for plg_editors_tinymce
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev

#25049 [4.0] Add prepared statements for plg_authentication_joomla
  plugins/authentication/joomla/joomla.php
Labels: PR-4.0-dev

#25151 [4.0] Fix History Versions Modal display (.es6.js instead of .es5)
  build/media_source/com_contenthistory/js/admin-history-versions.es5.js
  build/media_source/com_contenthistory/js/admin-history-versions.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#25156 [4.0] com_csp word break
  administrator/components/com_csp/tmpl/reports/default.php
Labels: PR-4.0-dev

#25153 Use joomla's constants instead of JPATH_ROOT in the namespace mapper
  installation/includes/defines.php
  libraries/namespacemap.php
Labels: PR-4.0-dev

#25161 [4.0] fix display of item association popover
  administrator/templates/atum/scss/blocks/_form.scss
Labels: RTC

#25155 [4.0] Template Style assignment: Fix toggle checkboxes
  administrator/components/com_templates/tmpl/style/edit_assignment.php
  build/media_source/com_templates/js/admin-template-toggle-assignment.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#25158 [4.0] Improve menu item access check
  libraries/src/Menu/AbstractMenu.php
Labels: PR-4.0-dev

#25168 [4.0] TagsHelperRoute not found in tags view
  components/com_tags/tmpl/tags/default_items.php
Labels: PR-4.0-dev

#25170 Fix menu access
  libraries/src/Menu/AbstractMenu.php
Labels: PR-4.0-dev

#25040 [4.0][com_finder] dirty temporary fix for class not found
  administrator/components/com_finder/Indexer/Query.php
Labels: RTC

#25058 [4.0] Add prepared statements for plg_installer_override
  plugins/installer/override/override.php
Labels: PR-4.0-dev

#25057 [4.0] Add prepared statements for plg_finder_categories
  plugins/finder/categories/categories.php
Labels: PR-4.0-dev

#25055 [4.0] Add prepared statements for plg_extension_joomla
  plugins/extension/joomla/joomla.php
Labels: PR-4.0-dev

#25054 [4.0] Add prepared statements for plg_extension_finder
  plugins/extension/finder/finder.php
Labels: PR-4.0-dev

#25172 [4.0] Fix menu access check for PDO
  libraries/src/Menu/AbstractMenu.php
Labels: PR-4.0-dev

#25175 Fix doc block to use correct element order
  libraries/joomla/github/package/data.php
Labels: PR-staging

#25177 Fix user params after Joomla 3.9.7 with selected french help site
  administrator/components/com_admin/sql/updates/mysql/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.8-2019-06-11.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.8-2019-06-11.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.8-2019-06-11.sql
Labels: PR-staging

#25181 [4.0] Fix filters in com_menus
  administrator/components/com_menus/Controller/DisplayController.php
Labels: RTC

#24899 [4.0] HTML on Locked-Article
  administrator/templates/atum/scss/blocks/_form.scss
  libraries/cms/html/jgrid.php
Labels: PR-4.0-dev, RTC

#25189 [com_fields] Field type Repeatable. Editor and Textarea subfields remove HTML since J 3.9.7
  plugins/fields/repeatable/params/repeatable.xml
  plugins/fields/repeatable/repeatable.php
Labels: PR-staging, RTC

#25195 Fix pagination when uninstalling extensions
  administrator/components/com_installer/models/extension.php
Labels: RTC

#20401 Default cache keys based on JPATH_CONFIGURATION instead of null
  libraries/src/Cache/CacheStorage.php
  tests/unit/suites/libraries/joomla/cache/JCacheStorageTest.php
Labels: PR-staging, Unit/System Tests

#24025 [4.0] Remove article print and email
  administrator/components/com_content/config.xml
  administrator/components/com_content/forms/article.xml
  administrator/language/en-GB/en-GB.ini
  components/com_content/tmpl/article/default.php
  components/com_content/tmpl/article/default.xml
  components/com_content/tmpl/categories/default.xml
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/category/blog_item.php
  components/com_content/tmpl/category/default.xml
  components/com_content/tmpl/featured/default.xml
  components/com_content/tmpl/featured/default_item.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/src/Model/LanguagesModel.php
  layouts/joomla/content/icons.php
  layouts/joomla/content/icons/email.php
  layouts/joomla/content/icons/print_popup.php
  layouts/joomla/content/icons/print_screen.php
  plugins/sampledata/multilang/multilang.php
Labels: Language Change, PR-4.0-dev, RTC

#22902 [4.0] Inject the dependencies in the stats module
  administrator/modules/mod_multilangstatus/Helper/MultilangstatusAdminHelper.php
  administrator/modules/mod_status/mod_status.php
  administrator/modules/mod_status/tmpl/default.php
  libraries/src/Language/Multilanguage.php
Labels: PR-4.0-dev

#21038 [4.0] Adding language column to com_finder index backend
  administrator/components/com_finder/Field/ContentmapField.php
  administrator/components/com_finder/Model/IndexModel.php
  administrator/components/com_finder/View/Index/HtmlView.php
  administrator/components/com_finder/forms/filter_index.xml
  administrator/components/com_finder/tmpl/index/default.php
Labels: PR-4.0-dev, RTC

#22887 [4.0] Inject the database into the query helper
  components/com_content/Helper/QueryHelper.php
  components/com_content/Model/ArchiveModel.php
  components/com_content/Model/CategoryModel.php
  components/com_content/Model/FeaturedModel.php
Labels: PR-4.0-dev

#19870 [4.0] Namespace content site route helper
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_content/tmpl/articles/modal.php
  components/com_contact/tmpl/contact/default_articles.php
  components/com_content/Dispatcher/Dispatcher.php
  components/com_content/Helper/AssociationHelper.php
  components/com_content/Helper/RouteHelper.php
  components/com_content/View/Article/HtmlView.php
  components/com_content/tmpl/article/default.php
  components/com_search/View/Search/HtmlView.php
  libraries/extensions.classmap.php
  modules/mod_articles_categories/mod_articles_categories.php
  modules/mod_articles_category/Helper/ArticlesCategoryHelper.php
  modules/mod_articles_latest/Helper/ArticlesLatestHelper.php
  modules/mod_articles_news/Helper/ArticlesNewsHelper.php
  modules/mod_articles_popular/Helper/ArticlesPopularHelper.php
  modules/mod_related_items/Helper/RelatedItemsHelper.php
  plugins/finder/categories/categories.php
  plugins/finder/content/content.php
  plugins/search/categories/categories.php
  plugins/search/content/content.php
  plugins/user/profile/field/tos.php
Labels: PR-4.0-dev

#22475 Compact image modal layout
  administrator/components/com_media/views/images/tmpl/default.php
  administrator/components/com_media/views/imageslist/tmpl/default.php
  administrator/templates/isis/css/template-rtl.css
  administrator/templates/isis/css/template.css
  administrator/templates/isis/html/layouts/joomla/form/field/media.php
  administrator/templates/isis/less/blocks/_media.less
  administrator/templates/isis/less/blocks/_modals.less
  media/media/css/popup-imagelist.css
  media/media/css/popup-imagemanager.css
Labels: PR-staging

#25208 [4.0] Clear Cache toolbar
  administrator/components/com_cache/View/Cache/HtmlView.php
Labels: PR-4.0-dev

#25212 [4.0] Remove unused file
  administrator/components/com_installer/tmpl/discover/default_item.php
Labels: PR-4.0-dev

#25210 [4.0] Override files string
  administrator/language/en-GB/en-GB.com_templates.ini
Labels: Language Change, PR-4.0-dev

#25077 [4.0] Removing base tag from frontend
  libraries/src/Application/SiteApplication.php
Labels: PR-4.0-dev, RTC

#25218 Merge in Joomla 3.9.3
  administrator/components/com_admin/postinstall/addnosniff.php
  administrator/components/com_admin/sql/updates/mysql/3.9.3-2019-02-07.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.3-2019-02-07.sql
  administrator/components/com_banners/forms/banner.xml
  administrator/components/com_config/Field/FiltersField.php
  administrator/components/com_config/forms/application.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_finder/Indexer/Driver/Mysql.php
  administrator/components/com_finder/Indexer/Driver/Postgresql.php
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_tags/config.xml
  administrator/components/com_templates/Controller/TemplateController.php
  administrator/components/com_templates/config.xml
  administrator/language/en-GB/en-GB.com_config.ini
  administrator/language/en-GB/en-GB.com_contact.ini
  administrator/language/en-GB/en-GB.com_cpanel.ini
  administrator/language/en-GB/en-GB.com_languages.ini
  administrator/modules/mod_menu/mod_menu.xml
  components/com_config/tmpl/modules/default.php
  components/com_contact/tmpl/categories/default.xml
  components/com_contact/tmpl/category/default.xml
  components/com_contact/tmpl/contact/default.xml
  components/com_contact/tmpl/featured/default.xml
  components/com_tags/View/Tag/HtmlView.php
  components/com_tags/tmpl/tags/default_items.php
  composer.json
  composer.lock
  htaccess.txt
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_testing.sql
  layouts/joomla/form/field/subform/repeatable-table.php
  libraries/bootstrap.php
  libraries/cms.php
  libraries/src/Encrypt/Aes.php
  libraries/src/Help/Help.php
  libraries/src/Toolbar/Button/HelpButton.php
  plugins/actionlog/joomla/joomla.php
  plugins/user/profile/profiles/profile.xml
  web.config.txt
Labels: Composer Dependency Changed, Language Change, PR-4.0-dev

#25191 [4.0] Resolve LDAP Plugin Error
  plugins/authentication/ldap/ldap.php
Labels: PR-4.0-dev

#25219 3.9.4 Merge
  administrator/components/com_actionlogs/controllers/actionlogs.php
  administrator/components/com_actionlogs/models/actionlogs.php
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-02.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-24.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-08-12.sql
  administrator/components/com_cache/Controller/DisplayController.php
  administrator/components/com_cache/Model/CacheModel.php
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_config/Controller/ApplicationController.php
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_users/Field/GroupparentField.php
  administrator/language/en-GB/en-GB.com_config.ini
  administrator/language/en-GB/en-GB.com_cpanel.ini
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
  administrator/modules/mod_sampledata/mod_sampledata.php
  administrator/modules/mod_sampledata/tmpl/default.php
  build/media_source/mod_sampledata/js/sampledata-process.es6.js
  components/com_config/tmpl/modules/default.php
  components/com_contact/tmpl/categories/default.xml
  components/com_contact/tmpl/category/default.xml
  components/com_contact/tmpl/contact/default.xml
  components/com_content/tmpl/featured/default.php
  components/com_content/tmpl/featured/default.xml
  components/com_tags/View/Tag/FeedView.php
  composer.json
  composer.lock
  installation/forms/setup.xml
  installation/sql/mysql/joomla.sql
  installation/src/Form/Rule/UsernameRule.php
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/plugins/system/privacyconsent/label.php
  layouts/plugins/system/privacyconsent/message.php
  layouts/plugins/user/terms/label.php
  layouts/plugins/user/terms/message.php
  libraries/src/Form/FormField.php
  libraries/src/Table/Asset.php
  modules/mod_articles_category/Helper/ArticlesCategoryHelper.php
  modules/mod_articles_latest/Helper/ArticlesLatestHelper.php
  modules/mod_articles_news/Helper/ArticlesNewsHelper.php
  modules/mod_articles_popular/Helper/ArticlesPopularHelper.php
  plugins/actionlog/joomla/joomla.php
  plugins/sampledata/blog/blog.php
  plugins/system/fields/fields.php
  plugins/system/privacyconsent/field/privacy.php
  plugins/system/privacyconsent/privacyconsent.xml
  plugins/user/terms/field/terms.php
  robots.txt.dist
Labels: Composer Dependency Changed, Language Change, NPM Resource Changed, PR-4.0-dev

#25217 [4.0] Execute transition string
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, PR-4.0-dev

#24595 [SQL] fix field home of #__template_styles table
  administrator/components/com_admin/sql/updates/mysql/3.9.8-2019-06-15.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.8-2019-06-15.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.8-2019-06-15.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
Labels: PR-staging, RTC

#25201 Clean article cache after voting
  components/com_content/models/article.php
Labels: RTC

#25232 [4.0] Update joomla/database package from framework
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#25221 [4.0] Namespace from 3.9.4
  libraries/src/Table/Asset.php
Labels: RTC

#25243 Update joomla/string from framework to fix Appveyor
  composer.lock
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/string/src/Inflector.php
  libraries/vendor/joomla/string/src/Normalise.php
  libraries/vendor/joomla/string/src/String.php
  libraries/vendor/joomla/string/src/StringHelper.php
  libraries/vendor/joomla/string/src/phputf8/utf8.php
Labels: Composer Dependency Changed, PR-staging

#25242 [4.0] Update string package from framework and fix content-hash in composer.lock
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#25241 [4.0] Use the right branch for AppVeyor badge
  README.md
Labels: RTC

#25240 Using domain for drone badge
  README.md
Labels: PR-staging, RTC

#25157 [cs] Remove tabs
  administrator/components/com_categories/models/category.php
Labels: PR-staging, RTC

#24623 Remove chosen from com_search
  components/com_search/views/search/tmpl/default.php
Labels: PR-staging, RTC

#25246 [4.0] Update minimum database version strings
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
  installation/src/Model/DatabaseModel.php
Labels: Language Change, PR-4.0-dev

#25223 [4.0] Correcting mutilingual sampledata plugin
  plugins/sampledata/multilang/multilang.php
Labels: PR-4.0-dev, RTC

#25252 [4.0] Increase php minimum
  administrator/index.php
  api/index.php
  cli/joomla.php
  composer.json
  composer.lock
  index.php
  installation/index.php
  plugins/quickicon/phpversioncheck/phpversioncheck.php
Labels: Composer Dependency Changed, PR-4.0-dev

#25251 Update phar wrapper to 3.1.2
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#25236 [4.0] Extension Update Sources
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: RTC

#25256 [4.0] Removing broken CSS rule
  templates/cassiopeia/scss/blocks/_css-grid.scss
Labels: PR-4.0-dev

#25261 [4.0] Make sure the function matches the parent return type
  composer.lock
  libraries/src/Session/Storage/JoomlaStorage.php
Labels: Composer Dependency Changed, PR-4.0-dev

#25257 Use Symfony 4 components in 4.x, dump the PHP 7.1 polyfill
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#25263 [4.0] Remove reference to obsolete language string
  components/com_contact/tmpl/contact/default.xml
Labels: PR-4.0-dev

#25233 [4.0] Remove title on some buttons
  administrator/components/com_categories/Field/Modal/CategoryField.php
  administrator/components/com_contact/Field/Modal/ContactField.php
  administrator/components/com_content/Field/Modal/ArticleField.php
  administrator/components/com_menus/Field/Modal/MenuField.php
  administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
Labels: PR-4.0-dev, RTC

#25249 [4.0] Plugin description
  administrator/language/en-GB/en-GB.plg_system_languagefilter.ini
Labels: RTC

#25231 [4.0] com_templates tooltips
  administrator/components/com_templates/Service/HTML/Templates.php
  administrator/components/com_templates/tmpl/template/default_modal_copy_body.php
  administrator/components/com_templates/tmpl/template/default_modal_file_body.php
  administrator/components/com_templates/tmpl/template/default_modal_rename_body.php
  administrator/components/com_templates/tmpl/template/default_modal_resize_body.php
  administrator/language/en-GB/en-GB.com_templates.ini
Labels: Language Change, PR-4.0-dev

#25276 [4.0] Update the AppVeyor badge to project changes
  README.md
Labels: RTC

#25275 Update the AppVeyor badge to project changes
  README.md
Labels: RTC

#25264 [4.0] com_associations remove unused JHtml::sidebar
  administrator/components/com_associations/View/Association/HtmlView.php
  administrator/components/com_associations/View/Associations/HtmlView.php
  administrator/components/com_associations/tmpl/associations/modal.php
Labels: PR-4.0-dev, RTC

#25278 [4.0] [com_associations] Fix filters display in Target modal
  administrator/components/com_associations/layouts/joomla/searchtools/default.php
Labels: PR-4.0-dev, RTC

#24992 Correct username in plg_actionlog
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging

#25291 Correcting action logs filter due to #24992
  administrator/components/com_actionlogs/models/fields/logcreator.php
Labels: RTC

#24989 [4.0] Updating PHPUnit to 8.0
  composer.json
  composer.lock
  tests/Unit/Libraries/Cms/Console/Loader/WritableContainerLoaderTest.php
  tests/Unit/Libraries/Cms/Environment/BrowserTest.php
  tests/Unit/Libraries/Cms/Feed/FeedEntryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedFactoryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedLinkTest.php
  tests/Unit/Libraries/Cms/Feed/FeedParserTest.php
  tests/Unit/Libraries/Cms/Feed/FeedTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
  tests/Unit/Libraries/Cms/Layout/BaseLayoutTest.php
  tests/Unit/Libraries/Cms/Mail/MailTest.php
  tests/Unit/Libraries/Cms/Object/CMSObjectTest.php
  tests/Unit/Libraries/Cms/Toolbar/ToolbarTest.php
  tests/Unit/Libraries/Cms/VersionTest.php
Labels: Composer Dependency Changed, PR-4.0-dev, Unit/System Tests

#25292 [4.0] Enable utf8mb4 connections for mysql adapters on installation
  installation/src/Helper/DatabaseHelper.php
Labels: PR-4.0-dev

#25266 [4.0] com_banners - remove unused submenu
  administrator/components/com_banners/View/Banners/HtmlView.php
  administrator/components/com_banners/View/Clients/HtmlView.php
  administrator/components/com_banners/View/Tracks/HtmlView.php
Labels: PR-4.0-dev, RTC

#25265 [4.0] com_categories remove unused sidebar references
  administrator/components/com_categories/Controller/DisplayController.php
  administrator/components/com_categories/Helper/CategoriesHelper.php
  administrator/components/com_categories/View/Categories/HtmlView.php
  administrator/components/com_categories/tmpl/categories/default.php
Labels: PR-4.0-dev, RTC

#25238 [4.0] Fix installer plugin detection
  administrator/components/com_installer/tmpl/install/default.php
Labels: PR-4.0-dev, RTC

#25222 [4.0] sr-only
  administrator/components/com_privacy/tmpl/requests/default.php
Labels: PR-4.0-dev, RTC

#25207 [4.0] Installer Database should not use popovers
  administrator/components/com_installer/tmpl/database/default.php
Labels: PR-4.0-dev, RTC

#25205 [4.0] Fixing children when changing menu of menu item
  administrator/components/com_menus/Model/ItemModel.php
Labels: PR-4.0-dev, RTC

#25197 [4.0] Menus Manager: Fix system links menu items Status icon and adding badge when component is disabled
  administrator/components/com_menus/Model/ItemsModel.php
  administrator/components/com_menus/Service/HTML/Menus.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/language/en-GB/en-GB.com_menus.ini
Labels: Language Change, PR-4.0-dev, RTC

#25050 [4.0] Add prepared statements for plg_content_joomla
  plugins/content/joomla/joomla.php
Labels: PR-4.0-dev, RTC

#25045 [4.0] Add prepared statements for mod_users_latest
  modules/mod_users_latest/Helper/UsersLatestHelper.php
Labels: PR-4.0-dev, RTC

#25044 [4.0] Add prepared statements for mod_whosonline
  modules/mod_whosonline/Helper/WhosonlineHelper.php
Labels: PR-4.0-dev, RTC

#25041 [4.0] Add prepared statements for mod_articles_archive
  modules/mod_articles_archive/Helper/ArticlesArchiveHelper.php
Labels: PR-4.0-dev, RTC

#24870 [4.0] com_users sidebar
  administrator/components/com_users/View/Groups/HtmlView.php
  administrator/components/com_users/View/Levels/HtmlView.php
  administrator/components/com_users/View/Notes/HtmlView.php
  administrator/components/com_users/View/Users/HtmlView.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_users/tmpl/users/default.php
Labels: PR-4.0-dev, RTC

#25226 [4.0] Extensions Manage
  administrator/components/com_installer/tmpl/manage/default.php
Labels: PR-4.0-dev, RTC

#25281 Send proper MariaDB database version to the stats server
  plugins/system/stats/stats.php
Labels: RTC

#25228 [4.0] com_templates tooltip
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/language/en-GB/en-GB.com_templates.ini
Labels: Language Change, PR-4.0-dev, RTC

#25285 [4.0] Composer update jooma/database for MariaDB compatibility
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#25259 Contact and Newsfeed title not incremented during batch copy
  administrator/components/com_contact/models/contact.php
  administrator/components/com_contact/tables/contact.php
  administrator/components/com_newsfeeds/models/newsfeed.php
  administrator/components/com_newsfeeds/tables/newsfeed.php
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-staging, RTC

#25134 Improved PHPDoc for JDatabaseDriver::updateObject
  libraries/joomla/database/driver.php
Labels: PR-staging, RTC

#24858 Revert "[4.0] Wrong order for attachActiveAssetsToDocument in MetasRenderer.php"
  libraries/src/Document/Renderer/Html/MetasRenderer.php
Labels: PR-4.0-dev, RTC

#24000 [4.0] Remove button Cancel from Registration form
  components/com_users/tmpl/registration/default.php
Labels: PR-4.0-dev, RTC, a11y

#23661 [4.0] Move sidebar modules into grid
  templates/cassiopeia/index.php
  templates/cassiopeia/scss/blocks/_css-grid.scss
Labels: PR-4.0-dev, RTC
