Repository joomla/joomla-cms, pull requests merged in 2019-11, with the labels that each got.

#26824 [4.0] WCAG 1.4.3: Elements must have sufficient color contrast (#disk-1)
  administrator/components/com_media/resources/styles/components/_media-tree.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#26886 Workflows Default - message
  administrator/components/com_workflow/Controller/StagesController.php
  administrator/components/com_workflow/Controller/WorkflowsController.php
  administrator/language/en-GB/en-GB.com_workflow.ini
Labels: Language Change, PR-4.0-dev, RTC

#26781 [4.0] [libraries] Add check for real null datetimes to CoreContent table class
  libraries/src/Table/CoreContent.php
Labels: PR-4.0-dev, RTC

#25503 [4.0] [plg_system_actionlogs] Convert to prepared statement
  plugins/system/actionlogs/actionlogs.php
Labels: PR-4.0-dev, RTC

#26927 [4.0] Remove selenium.log from final build
  build/build.php
Labels: PR-staging

#26877 [4.0] Fix tooltip cutoff
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
Labels: PR-4.0-dev, RTC

#25432 [4.0] [plg_privacy_user] Convert to prepared statement
  plugins/privacy/user/user.php
Labels: PR-4.0-dev, RTC

#26611 [4.0] [com_users] Fix default value for datetime columns and make some nullable
  administrator/components/com_actionlogs/Model/ActionlogsModel.php
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-10-17.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-10-17.sql
  administrator/components/com_users/Model/UsersModel.php
  administrator/components/com_users/tmpl/users/default.php
  components/com_users/Model/RegistrationModel.php
  components/com_users/tmpl/profile/default_core.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/src/Model/ConfigurationModel.php
  libraries/src/Table/User.php
  libraries/src/User/UserHelper.php
Labels: PR-4.0-dev, RTC

#26776 [4.0] Use getBase64 filter
  administrator/components/com_users/tmpl/user/edit.php
Labels: PR-4.0-dev, RTC

#26825 [4.0] Remove the meanwhile obsolete updateDates routine from installation database model
  installation/src/Model/DatabaseModel.php
Labels: PR-4.0-dev

#26745 [4.0] Set modified by user to created by user for new items
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-04-22.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-06-28.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-06-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-14.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-25.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-27.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-28.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-04-22.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-06-28.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-06-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-14.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-25.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-27.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-28.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-29.sql
  administrator/components/com_banners/Table/BannerTable.php
  administrator/components/com_contact/Table/ContactTable.php
  administrator/components/com_fields/Table/FieldTable.php
  administrator/components/com_fields/Table/GroupTable.php
  administrator/components/com_finder/Table/FilterTable.php
  administrator/components/com_newsfeeds/Table/NewsfeedTable.php
  administrator/components/com_tags/Table/TagTable.php
  administrator/components/com_users/Table/NoteTable.php
  administrator/components/com_workflow/Table/WorkflowTable.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/src/Model/DatabaseModel.php
  libraries/src/Table/Category.php
  libraries/src/Table/Content.php
  libraries/src/Table/CoreContent.php
Labels: PR-4.0-dev

#26939 [4.0]Create User Group - Group parent dropdown gets blank.#pbf19 #bug
  administrator/components/com_users/Field/GroupparentField.php
Labels: PR-4.0-dev, RTC

#26681 [4.0] Feature: Article > Save To Menu
  administrator/components/com_content/Controller/ArticleController.php
  administrator/components/com_content/View/Article/HtmlView.php
  administrator/language/en-GB/en-GB.ini
  libraries/src/MVC/Controller/FormController.php
Labels: Language Change, PR-4.0-dev, RTC

#26960 [4.0] Fix No User button not clickable
  administrator/components/com_users/tmpl/users/modal.php
Labels: PR-4.0-dev

#26902 [4.0][com_messages]: Private message: Tooltip is missing for search filter
  administrator/components/com_messages/forms/filter_messages.xml
Labels: PR-4.0-dev, RTC

#26892 [4.0] Move Session's getHandlers method from Framework to CMS
  libraries/src/Form/Field/SessionhandlerField.php
  libraries/src/Session/Session.php
Labels: PR-4.0-dev, RTC

#26853 [4.0] Fix Article show_associations parameter
  administrator/components/com_content/forms/article.xml
  administrator/components/com_content/tmpl/article/edit.php
Labels: PR-4.0-dev, RTC

#26777 [4.0] [com_contenthistory] Add check for real null datetimes
  administrator/components/com_contenthistory/Model/CompareModel.php
  administrator/components/com_contenthistory/Model/PreviewModel.php
Labels: PR-4.0-dev, RTC

#26810 Fixing validation of emails by changing 'error-handling' in EmailRule.php (related to 26637)
  libraries/src/Form/Rule/EmailRule.php
Labels: PR-4.0-dev, RTC

#24816 [4.0] Return correct validation result to form.
  libraries/src/Form/FormField.php
Labels: PR-4.0-dev, RTC

#26868 [4.0] Fix redundant description
  administrator/components/com_banners/forms/download.xml
Labels: PR-4.0-dev, RTC

#26943 Issue #26708 fix: Category Icon & Author Icon Missing from Article
  layouts/joomla/content/info_block/author.php
  layouts/joomla/content/info_block/category.php
Labels: PR-4.0-dev, RTC

#26962 [4.0] Remove Settings text from legend
  administrator/language/en-GB/en-GB.com_config.ini
Labels: RTC

#26963 [4.0] Info_block associations icon misssing
  layouts/joomla/content/info_block/associations.php
Labels: PR-4.0-dev

#26966 [4.0] Replaced JText occurrences
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  plugins/sampledata/testing/testing.php
Labels: RTC

#26971 [4.0] Replaced JApplicationHelper occurrences
  plugins/sampledata/testing/testing.php
Labels: RTC

#26970 [4.0] Fix register date together with last visit date range filter in users model
  administrator/components/com_users/Model/UsersModel.php
Labels: PR-4.0-dev, RTC

#26969 [4.0] Remove bottom margin
  administrator/components/com_templates/tmpl/template/default_modal_file_body.php
Labels: RTC

#26967 [com_users] Confirmation window shown when no users in group
  build/media_source/com_users/js/admin-users-groups.es6.js
Labels: RTC

#26965 [4.0] RTL: correcting some fields display
  administrator/templates/atum/scss/template-rtl.scss
  administrator/templates/atum/scss/vendor/bootstrap/_form.scss
Labels: PR-4.0-dev

#26977 [4.0] Remove extra period
  administrator/language/en-GB/en-GB.com_media.ini
Labels: Language Change, PR-4.0-dev, RTC

#26978 [4.0] Replaced JFactory and JRoute occurrences
  administrator/components/com_mails/tmpl/templates/default.php
  plugins/actionlog/joomla/joomla.php
Labels: PR-4.0-dev, RTC

#26979 [4.0] Webservices createCRUDRoutes
  plugins/webservices/banners/banners.php
  plugins/webservices/contact/contact.php
  plugins/webservices/content/content.php
  plugins/webservices/languages/languages.php
  plugins/webservices/menus/menus.php
  plugins/webservices/messages/messages.php
  plugins/webservices/modules/modules.php
  plugins/webservices/newsfeeds/newsfeeds.php
  plugins/webservices/redirect/redirect.php
  plugins/webservices/tags/tags.php
  plugins/webservices/templates/templates.php
  plugins/webservices/users/users.php
Labels: PR-4.0-dev

#26883 [mod_banners] - tooltip text
  language/en-GB/en-GB.mod_banners.ini
Labels: PR-staging, RTC

#26989 [4.0] user notes category delete
  plugins/content/joomla/joomla.php
Labels: PR-4.0-dev

#26990 [4.0] [com_templates] Error when filtering template styles by menu item
  administrator/components/com_templates/Model/StylesModel.php
Labels: PR-4.0-dev

#25540 [4.0] Convert plugin system privacyconsent to prepared statements
  plugins/system/privacyconsent/field/privacy.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-4.0-dev

#26998 [4.0] Add closing </div>
  layouts/joomla/edit/params.php
Labels: PR-4.0-dev

#27000 [4.0] Fix progressive cache
  libraries/src/Document/HtmlDocument.php
Labels: RTC

#26985 [4.0] Media Info
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
Labels: RTC

#26988 [4.0] Remove horizontal scrollbar in media modal
  administrator/components/com_media/resources/scripts/components/app.vue
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#26982 [4.0] Fix filtering in users model
  administrator/components/com_users/Model/UsersModel.php
Labels: PR-4.0-dev, RTC

#26987 [4.0] optgroup color
  administrator/templates/atum/scss/vendor/bootstrap/_custom-forms.scss
Labels: PR-4.0-dev, RTC

#26983 [4.0] Select options font-size
  administrator/templates/atum/scss/blocks/_searchtools.scss
Labels: PR-4.0-dev, RTC

#26996 [4.0] Add space to separate sentences
  plugins/content/joomla/joomla.php
Labels: PR-4.0-dev

#27006 [4.0] Fix radio buttons markup
  layouts/joomla/form/field/radio/buttons.php
Labels: RTC

#27008 [4.0] Fix failing sample data installation caused by unset featured_up and featured_down
  administrator/components/com_content/Model/ArticleModel.php
Labels: PR-4.0-dev, RTC

#27013 [4.0] Screen reader text for quickicons
  administrator/language/en-GB/en-GB.com_categories.ini
  administrator/language/en-GB/en-GB.com_checkin.ini
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/language/en-GB/en-GB.com_menus.ini
  administrator/language/en-GB/en-GB.com_modules.ini
  administrator/language/en-GB/en-GB.com_plugins.ini
  administrator/language/en-GB/en-GB.com_users.ini
Labels: Language Change, PR-4.0-dev

#26392 [4.0] Fixing removeOrphanNodes() in Finder Taxonomy
  administrator/components/com_finder/Indexer/Adapter.php
  administrator/components/com_finder/Indexer/Indexer.php
  administrator/components/com_finder/Indexer/Taxonomy.php
  plugins/sampledata/testing/testing.php
Labels: PR-4.0-dev

#26742 [4.0] fix when error on massmail
  administrator/components/com_users/Model/MailModel.php
Labels: PR-4.0-dev

#26952 s/autocopleter/autocompleter
  components/com_finder/controllers/suggestions.json.php
Labels: PR-staging, RTC

#26953 s/sumitted/submitted
  components/com_config/controller/modules/save.php
Labels: PR-staging, RTC

#26954 +show
  administrator/includes/subtoolbar.php
Labels: PR-staging, RTC

#26955 (another) +show
  libraries/cms/html/sidebar.php
Labels: PR-staging, RTC

#26957 remove extra whitespace
  administrator/components/com_languages/controller.php
Labels: PR-staging, RTC

#26958 remove whitespace/tabs
  administrator/components/com_languages/controllers/strings.json.php
Labels: PR-staging, RTC

#26959 s/dlete/delete, remove whitespace/tabs
  administrator/components/com_languages/controllers/overrides.php
Labels: PR-staging, RTC

#26879 Composer update
  composer.lock
  libraries/vendor/composer/autoload_psr4.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/event/src/AbstractEvent.php
  libraries/vendor/joomla/event/src/DelegatingDispatcher.php
  libraries/vendor/joomla/event/src/Dispatcher.php
  libraries/vendor/joomla/event/src/DispatcherAwareInterface.php
  libraries/vendor/joomla/event/src/DispatcherAwareTrait.php
  libraries/vendor/joomla/event/src/DispatcherInterface.php
  libraries/vendor/joomla/event/src/Event.php
  libraries/vendor/joomla/event/src/EventImmutable.php
  libraries/vendor/joomla/event/src/EventInterface.php
  libraries/vendor/joomla/event/src/ListenersPriorityQueue.php
  libraries/vendor/joomla/event/src/Priority.php
  libraries/vendor/psr/log/Psr/Log/LoggerInterface.php
  libraries/vendor/psr/log/Psr/Log/LoggerTrait.php
  libraries/vendor/psr/log/Psr/Log/NullLogger.php
Labels: Composer Dependency Changed, PR-staging

#27015 [4.0] Fix namespace of file
  tests/Unit/Libraries/Cms/Document/DocumentTest.php
Labels: PR-4.0-dev, Unit/System Tests

#27012 [4.0] [com_contact] Missing parameterized queries, fixed double quoting
  administrator/components/com_contact/Service/HTML/AdministratorService.php
  components/com_contact/Model/FeaturedModel.php
  components/com_contact/Service/Router.php
Labels: PR-4.0-dev, RTC

#27020 [4.0] Download Keys quick icon could crash the site
  administrator/components/com_installer/Helper/InstallerHelper.php
Labels: PR-4.0-dev

#27023 [4.0] Fixing display Notice in Associations tab when item language is set to All
  administrator/components/com_categories/tmpl/category/edit.php
  administrator/components/com_contact/tmpl/contact/edit.php
  administrator/components/com_content/tmpl/article/edit.php
  administrator/components/com_menus/tmpl/item/edit.php
  administrator/components/com_newsfeeds/tmpl/newsfeed/edit.php
Labels: PR-4.0-dev, RTC

#27029 [4.0] Missing string
  administrator/language/en-GB/en-GB.com_categories.ini
Labels: Language Change, PR-4.0-dev

#27030 [4.0] Class caps naming
  libraries/src/Image/Filter/Sketchy.php
Labels: RTC

#27031 [4.0] Fix category edit page title when Associations toolbar fails
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-4.0-dev, RTC

#26017 [4.0][com_privacy] - convert to prepared statement
  administrator/components/com_privacy/Model/ConsentsModel.php
  administrator/components/com_privacy/Model/ExportModel.php
  administrator/components/com_privacy/Model/RemoveModel.php
  administrator/components/com_privacy/Model/RequestModel.php
  administrator/components/com_privacy/Model/RequestsModel.php
  components/com_privacy/Model/RemindModel.php
  components/com_privacy/Model/RequestModel.php
Labels: PR-4.0-dev

#27041 [4.0] Fix com_privacy prepared statements
  administrator/components/com_privacy/Model/ExportModel.php
  administrator/components/com_privacy/Model/RemoveModel.php
  administrator/components/com_privacy/Model/RequestModel.php
Labels: PR-4.0-dev

#27038 [4.0] Deleting unused joomlaupdate strings
  plugins/quickicon/joomlaupdate/Extension/Joomlaupdate.php
Labels: PR-4.0-dev, RTC

#27035 [4.0] Fix search tooltip in modal
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/templates/atum/scss/blocks/_form.scss
  administrator/templates/atum/scss/blocks/_global.scss
Labels: PR-4.0-dev, RTC

#26867 [4.0] Don't use custom classes when loading database results
  administrator/components/com_finder/Indexer/Adapter.php
  administrator/components/com_installer/Helper/InstallerHelper.php
  administrator/components/com_installer/Model/UpdatesiteModel.php
  administrator/components/com_menus/Helper/MenusHelper.php
  libraries/src/Component/ComponentHelper.php
  libraries/src/Menu/SiteMenu.php
Labels: PR-4.0-dev

#27028 [4.0] fontawesome update
  package-lock.json
  package.json
Labels: PR-4.0-dev, RTC

#26813 [4.0] Workflows checked out / checkin
  administrator/components/com_workflow/Model/StagesModel.php
  administrator/components/com_workflow/Model/TransitionsModel.php
  administrator/components/com_workflow/Model/WorkflowsModel.php
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
  administrator/components/com_workflow/View/Workflows/HtmlView.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
Labels: PR-4.0-dev, RTC

#26910 [4.0] Add tooltip for workflow list view text-search box #pbf19 #codepatch
  administrator/components/com_workflow/forms/filter_workflows.xml
  administrator/language/en-GB/en-GB.com_workflow.ini
Labels: Language Change, PR-4.0-dev

#26323 [4.0] Eaccelerator post-install
  administrator/components/com_admin/postinstall/eaccelerator.php
  administrator/language/en-GB/en-GB.com_cpanel.ini
Labels: Language Change, PR-4.0-dev

#27048 [4.0] Update core extensions list in extension helper
  libraries/src/Extension/ExtensionHelper.php
Labels: PR-4.0-dev

#26085 [4.0][com_installer] convert to prepared statement
  administrator/components/com_installer/Helper/InstallerHelper.php
  administrator/components/com_installer/Model/DatabaseModel.php
  administrator/components/com_installer/Model/DiscoverModel.php
  administrator/components/com_installer/Model/ManageModel.php
  administrator/components/com_installer/Model/UpdateModel.php
  administrator/components/com_installer/Model/UpdatesiteModel.php
  administrator/components/com_installer/Model/UpdatesitesModel.php
Labels: PR-4.0-dev, RTC

#27058 [4.0] Joomla update grammar etc
  administrator/components/com_joomlaupdate/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default.php
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
  libraries/src/Updater/Updater.php
Labels: Language Change, PR-4.0-dev

#27051 Don't call jhtml functions directly. Use _ so that they can be overridden if needed.
  layouts/joomla/searchtools/default/bar.php
Labels: PR-staging, RTC

#27061 [4.0] Fix markup in dashboard
  administrator/modules/mod_submenu/tmpl/default.php
Labels: RTC

#27064 Word missing in CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR-staging

#27045 [4.0] Adding some quickstart in default and alternate menu presets
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/default.xml
Labels: PR-4.0-dev, RTC

#27062 [4.0] Menus preset should include Custom Administrator Menus
  administrator/components/com_menus/presets/menus.xml
Labels: PR-4.0-dev, RTC

#27052 [4.0] Allow switching displaying Help menu also in Joomla Main Menu preset
  administrator/modules/mod_menu/Menu/CssMenu.php
Labels: PR-4.0-dev, RTC

#27036 [4.0] Fixing useless blank img tag in admin menu
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/modules/mod_submenu/Menu/Menu.php
Labels: PR-4.0-dev, RTC

#27067 [3.10] Deprecation notice for tabstate
  libraries/cms/html/behavior.php
Labels: PR-3.10-dev

#26835 [4.0] Fixing Articles batch copy
  administrator/components/com_content/Model/ArticleModel.php
Labels: PR-4.0-dev, RTC

#26912 [4.0][mod_messages] messages badge
  administrator/modules/mod_messages/mod_messages.php
  administrator/modules/mod_messages/tmpl/default.php
Labels: PR-4.0-dev, RTC

#27082 [4.0] Language strings are coupled to template
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/component/default.php
  administrator/language/en-GB/en-GB.ini
  administrator/language/en-GB/en-GB.tpl_atum.ini
  administrator/templates/atum/index.php
  layouts/joomla/sidebars/submenu.php
Labels: Language Change, PR-4.0-dev, RTC

#27093 [4.0] Update Choices.js, fix placeholder for a select with multiple attribute
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
  package-lock.json
  package.json
Labels: RTC

#27078 [4.0] Correcting wrong debug lang untranslated strings
  administrator/components/com_banners/forms/filter_banners.xml
  administrator/components/com_contact/forms/filter_contacts.xml
  administrator/components/com_content/forms/filter_articles.xml
  layouts/joomla/button/transition-button.php
Labels: PR-4.0-dev, RTC

#27079 [4.0] Correcting accessibility in sidebar menu
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/default.xml
  administrator/language/en-GB/en-GB.mod_menu.ini
Labels: Language Change, PR-4.0-dev, RTC

#27074 [4.0] Correcting mod_submenu markup
  administrator/modules/mod_submenu/Menu/Menu.php
  administrator/modules/mod_submenu/tmpl/default.php
Labels: PR-4.0-dev, RTC

#27105 [4.0] PackageAdapter and Updater parameterized queries
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Updater/Updater.php
Labels: PR-4.0-dev

#27076 [4.0] [mod_tags_similar] Parameterized queries
  modules/mod_tags_similar/Helper/TagsSimilarHelper.php
Labels: PR-4.0-dev, RTC

#27115 [4.0] Allow com_media CSS to be overridden
  administrator/components/com_media/tmpl/file/default.php
  administrator/components/com_media/tmpl/media/default.php
Labels: PR-4.0-dev

#27102 Update News Feed ID in Single News Feed menu item - SQL Azure
  installation/sql/sqlazure/sample_learn.sql
Labels: RTC

#27124 [4.0] Remove obsolete JHtml includes
  administrator/components/com_finder/View/Filter/HtmlView.php
  administrator/components/com_finder/View/Filters/HtmlView.php
  administrator/components/com_finder/View/Index/HtmlView.php
  administrator/components/com_finder/View/Maps/HtmlView.php
  administrator/components/com_finder/tmpl/searches/default.php
  administrator/components/com_privacy/tmpl/request/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/modules/mod_privacy_dashboard/mod_privacy_dashboard.php
  administrator/modules/mod_privacy_status/mod_privacy_status.php
  components/com_finder/View/Search/FeedView.php
  components/com_finder/View/Search/HtmlView.php
  components/com_finder/tmpl/search/default.php
Labels: PR-4.0-dev, RTC

#26857 Minor changes on README.md & README.txt
  README.md
  README.txt
Labels: PR-4.0-dev, RTC

#26794 [4.0][Cassiopeia][CS] Line-breaks, indents and spaces
  templates/cassiopeia/scss/blocks/_banner.scss
  templates/cassiopeia/scss/blocks/_css-grid.scss
  templates/cassiopeia/scss/blocks/_demo-styling.scss
  templates/cassiopeia/scss/blocks/_form.scss
  templates/cassiopeia/scss/blocks/_global.scss
  templates/cassiopeia/scss/blocks/_header.scss
  templates/cassiopeia/scss/blocks/_layout.scss
  templates/cassiopeia/scss/blocks/_modifiers.scss
  templates/cassiopeia/scss/blocks/_utilities.scss
  templates/cassiopeia/scss/offline.scss
  templates/cassiopeia/scss/template-rtl.scss
  templates/cassiopeia/scss/template.scss
  templates/cassiopeia/scss/vendor/_choicesjs.scss
  templates/cassiopeia/scss/vendor/_chosen.scss
  templates/cassiopeia/scss/vendor/bootstrap/_card.scss
  templates/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
  templates/cassiopeia/scss/vendor/bootstrap/_dropdown.scss
  templates/cassiopeia/scss/vendor/bootstrap/_modal.scss
  templates/cassiopeia/scss/vendor/bootstrap/_nav.scss
Labels: PR-4.0-dev, RTC

#27110 [4.0] [mod_privacy_status] Parameterized queries
  administrator/modules/mod_privacy_status/Helper/PrivacyStatusHelper.php
Labels: PR-4.0-dev, RTC

#25948 [4.0] JHtml prepared statements
  libraries/cms/html/access.php
  libraries/cms/html/category.php
  libraries/cms/html/contentlanguage.php
  libraries/cms/html/list.php
  libraries/cms/html/menu.php
  libraries/cms/html/tag.php
  libraries/cms/html/user.php
  libraries/cms/html/workflowstage.php
Labels: PR-4.0-dev, RTC

#26890 [4.0] Use Custom Element tabs on Global Config
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/component/default.php
Labels: PR-4.0-dev, RTC

#26923 [#26922] fix - Repeatable-table field - UX issue
  layouts/joomla/form/field/subform/repeatable-table.php
Labels: PR-4.0-dev, RTC

#26984 [4.0] Fix query when searching items in backend
  administrator/components/com_csp/Model/ReportsModel.php
  administrator/components/com_modules/Model/ModulesModel.php
  administrator/components/com_redirect/Model/LinksModel.php
  administrator/components/com_templates/Model/StylesModel.php
  administrator/components/com_templates/Model/TemplatesModel.php
  administrator/components/com_users/Model/DebuggroupModel.php
  administrator/components/com_users/Model/DebuguserModel.php
  administrator/components/com_users/Model/NotesModel.php
Labels: PR-4.0-dev, RTC

#27125 [4.0] Fix Contact Creator plugin
  plugins/user/contactcreator/contactcreator.php
Labels: PR-4.0-dev, RTC

#27101 Update News Feed ID in Single News Feed menu item - PostgreSQL
  installation/sql/postgresql/sample_learn.sql
Labels: PR-staging, RTC

#27081 Bug #27080 fix: Incorect id generated for input fields in repetable s…
  media/system/js/subform-repeatable-uncompressed.js
  media/system/js/subform-repeatable.js
Labels: PR-staging, RTC

#27146 [4.0] Deletes some specific cpanel strings for help and system presets and creates mod_menu strings with same value
  administrator/components/com_menus/presets/help.xml
  administrator/components/com_menus/presets/system.xml
  administrator/language/en-GB/com_cpanel.ini
  administrator/language/en-GB/mod_menu.ini
Labels: Language Change, PR-4.0-dev

#27143 [4.0][a11y] Fix 'High Contrast' option - currently inverts
  administrator/templates/atum/scss/blocks/_global.scss
Labels: RTC

#27145 [4.0] Remove duplicate class for monochrome settings
  administrator/templates/atum/index.php
Labels: PR-4.0-dev, RTC

#27141 [4.0] Move options from grid to column layout
  administrator/templates/atum/scss/blocks/_utilities.scss
  administrator/templates/atum/templateDetails.xml
  layouts/joomla/edit/params.php
Labels: PR-4.0-dev

#27142 [4.0][a11y] Allow enabling of both 'High Contrast' & 'Monochrome'
  administrator/templates/atum/scss/blocks/_global.scss
Labels: PR-4.0-dev, RTC

#27099 [4.0] Select Client/Administrator filter [a11y]
  administrator/components/com_languages/forms/filter_installed.xml
  administrator/components/com_menus/forms/filter_items.xml
  administrator/components/com_menus/forms/filter_menus.xml
  administrator/components/com_menus/layouts/joomla/searchtools/default.php
  administrator/components/com_modules/forms/filter_modules.xml
  administrator/components/com_modules/forms/filter_modulesadmin.xml
  administrator/language/en-GB/com_languages.ini
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#27117 [3.10] Joomla.popWindow is no longer going to be removed in J4
  media/system/js/core-uncompressed.js
  media/system/js/core.js
Labels: PR-3.10-dev

#25502 [4.0] Remove behavior.tabstate
  administrator/components/com_admin/tmpl/sysinfo/default.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/component/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/components/com_fields/tmpl/field/edit.php
  administrator/components/com_fields/tmpl/group/edit.php
  administrator/components/com_finder/tmpl/filter/edit.php
  administrator/components/com_installer/tmpl/install/default.php
  administrator/components/com_languages/tmpl/language/edit.php
  administrator/components/com_menus/tmpl/item/edit.php
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugin/edit.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_tags/tmpl/tag/edit.php
  administrator/components/com_templates/tmpl/style/edit.php
  administrator/components/com_templates/tmpl/template/default.php
  administrator/components/com_users/tmpl/users/default.php
  components/com_content/tmpl/form/edit.php
  libraries/cms/html/behavior.php
Labels: PR-4.0-dev, RTC

#27129 [4.0] remove obsolete 3.x sql updates
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-02.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-03.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-05.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-19.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-20.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-24.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-27.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-02.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-13.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-14.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-17.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-07-09.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-07-10.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-07-11.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-08-12.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-08-28.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-08-29.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-09-04.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-10-15.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-10-20.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-10-21.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.10-2019-07-09.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.3-2019-01-12.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.3-2019-02-07.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.7-2019-04-23.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.7-2019-04-26.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.8-2019-06-11.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.8-2019-06-15.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-02.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-03.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-05.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-19.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-20.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-24.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-27.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-02.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-13.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-14.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-17.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-07-09.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-07-10.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-07-11.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-08-12.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-08-28.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-08-29.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-09-04.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-10-15.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-10-20.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-10-21.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.10-2019-07-09.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.3-2019-01-12.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.3-2019-02-07.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-04-23.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-04-26.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-05-16.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.8-2019-06-11.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.8-2019-06-15.sql
Labels: PR-4.0-dev

#27100 Update News Feed ID in Single News Feed menu item - MySQL
  installation/sql/mysql/sample_learn.sql
Labels: PR-staging, RTC

#27157 [4.0] Sidebar - remove redundant CSS
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev

#27155 [4.0] Remove onBeforeExecute event from CMS applications
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CliApplication.php
  libraries/src/Application/DaemonApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Application/WebApplication.php
  libraries/src/Event/BeforeExecuteEvent.php
  plugins/system/languagefilter/languagefilter.php
Labels: PR-4.0-dev

#27156 [4.0] Align sidebar icon
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/template-rtl.scss
Labels: PR-4.0-dev, RTC

#27170 [4.0] Remove variable from singular language strings
  administrator/language/en-GB/com_categories.ini
  administrator/language/en-GB/com_contenthistory.ini
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/com_installer.ini
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/com_tags.ini
  administrator/language/en-GB/com_templates.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: Language Change, PR-4.0-dev

#27128 [4.0] Mobile: Fix fieldset associations display
  administrator/templates/atum/scss/blocks/_global.scss
Labels: PR-4.0-dev, RTC

#23682 [4.0] Imported google fonts without the use of @import
  templates/cassiopeia/index.php
  templates/cassiopeia/scss/blocks/_global.scss
Labels: PR-4.0-dev, RTC

#26889 [4.0] No TLS transfer encryption for database connections if localhost
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/tmpl/application/default.php
  build/media_source/com_config/js/admin-config-default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27181 [4.0] Remove redundant array element
  layouts/joomla/form/field/radio/switcher.php
Labels: RTC

#27179 [4.0] Fixing multilingual sample data en-GB items creation
  plugins/sampledata/multilang/multilang.php
Labels: RTC

#27111 [4.0] [com_associations] Improving display of the sidebyside page
  administrator/components/com_associations/Field/Modal/AssociationField.php
  administrator/components/com_associations/tmpl/association/edit.php
  build/media_source/com_associations/css/sidebyside.css
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27069 [4.0] [com_cache] Fix cached items not shown
  administrator/components/com_cache/tmpl/cache/default.php
Labels: PR-4.0-dev, RTC

#26537 [4.0] Remove deprecated code in Joomla\CMS\Menu\MenuItem
  administrator/components/com_menus/Helper/MenusHelper.php
  administrator/components/com_menus/View/Menu/XmlView.php
  administrator/modules/mod_menu/Menu/CssMenu.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/modules/mod_submenu/Menu/Menu.php
  administrator/modules/mod_submenu/tmpl/default.php
  components/com_contact/Model/CategoriesModel.php
  components/com_contact/Model/CategoryModel.php
  components/com_content/Model/CategoriesModel.php
  components/com_content/Model/CategoryModel.php
  components/com_content/Model/FeaturedModel.php
  components/com_newsfeeds/Model/CategoriesModel.php
  components/com_newsfeeds/Model/CategoryModel.php
  components/com_tags/View/Tag/HtmlView.php
  components/com_users/Controller/UserController.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Menu/AbstractMenu.php
  libraries/src/Menu/AdministratorMenuItem.php
  libraries/src/Menu/MenuItem.php
  libraries/src/Menu/SiteMenu.php
  libraries/src/Pathway/SitePathway.php
  libraries/src/Router/SiteRouter.php
  modules/mod_menu/Helper/MenuHelper.php
  modules/mod_menu/tmpl/default.php
  modules/mod_menu/tmpl/default_component.php
  modules/mod_menu/tmpl/default_heading.php
  modules/mod_menu/tmpl/default_separator.php
  modules/mod_menu/tmpl/default_url.php
  plugins/system/languagefilter/languagefilter.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#26077 [4.0] Fix the vendor css for the template
  administrator/templates/atum/component.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/joomla.asset.json
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/fonts/_fontawesome.scss
  administrator/templates/atum/scss/template.scss
  administrator/templates/atum/scss/vendor/_awesomplete.scss
  administrator/templates/atum/scss/vendor/_choicesjs.scss
  administrator/templates/atum/scss/vendor/_chosen.scss
  administrator/templates/atum/scss/vendor/awesomplete/awesomplete.scss
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
  administrator/templates/atum/scss/vendor/fontawesome-free/fontawesome.scss
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
  administrator/templates/atum/scss/vendor/minicolors/minicolors.scss
  build/build-modules-js/compilecss.es6.js
  build/media_source/system/scss/_icomoon.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27180 [4.0] Adapt pages build script to language file changes
  build/build-modules-js/error-pages.es6.js
Labels: PR-4.0-dev, RTC

#27177 [4.0] Remove variable for 0 items for language strings
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: Language Change, PR-4.0-dev, RTC
