Repository joomla/joomla-cms, pull requests merged in 2019-03, with the labels that each got.

#23608 [4.0] Group toolbar buttons for workflow stages and transitions
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
Labels: PR-4.0-dev

#23679 [FIX][4.0] An error has occurred on Search Filter
  administrator/components/com_finder/tmpl/filters/default.php
Labels: PR-4.0-dev, RTC

#24031 [4.0] Global checkin - select all style
  administrator/components/com_checkin/tmpl/checkin/default.php
Labels: PR-4.0-dev, RTC

#24068 Merge 3.8.11 Release into Joomla 4
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Security.md
  README.md
  administrator/components/com_associations/View/Association/HtmlView.php
  administrator/components/com_associations/tmpl/association/edit.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_content/Model/FeaturedModel.php
  administrator/components/com_fields/Model/FieldsModel.php
  administrator/components/com_installer/Field/TypeField.php
  administrator/components/com_installer/Model/UpdatesitesModel.php
  administrator/components/com_menus/forms/item_component.xml
  administrator/components/com_users/Model/DebuggroupModel.php
  administrator/components/com_users/Model/DebuguserModel.php
  administrator/language/en-GB/en-GB.plg_sampledata_blog.ini
  administrator/language/en-GB/en-GB.plg_twofactorauth_totp.ini
  administrator/templates/atum/error_login.php
  build/media_source/com_associations/js/sidebyside.es5.js
  build/media_source/vendor/tinymce/langs/lt.es5.js
  language/en-GB/en-GB.mod_articles_category.ini
  libraries/src/Form/FormField.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Plugin/PluginHelper.php
  libraries/src/Table/Usergroup.php
  media/system/js/fields/calendar-locales/lt.js
  modules/mod_articles_category/mod_articles_category.xml
  plugins/content/emailcloak/emailcloak.php
  plugins/sampledata/blog/blog.php
  plugins/user/profile/field/tos.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
  templates/cassiopeia/offline.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24069 Start of 3.8.12 merge
  .editorconfig
  .github/CODEOWNERS
  .gitignore
  CODE_OF_CONDUCT.md
  README.txt
  administrator/components/com_banners/Model/BannerModel.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_content/Model/ArticlesModel.php
  administrator/components/com_newsfeeds/Model/NewsfeedModel.php
  appveyor-phpunit.xml
  build/build.php
  build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
  components/com_content/tmpl/category/blog_item.php
  components/com_content/tmpl/featured/default_item.php
  installation/src/Model/SetupModel.php
  layouts/joomla/form/field/color/advanced.php
  libraries/src/Component/ComponentHelper.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Mail/Mail.php
  libraries/src/Schema/ChangeItem/PostgresqlChangeItem.php
  modules/mod_articles_latest/Helper/ArticlesLatestHelper.php
  modules/mod_articles_news/Helper/ArticlesNewsHelper.php
Labels: NPM Resource Changed, PR-4.0-dev, Unit/System Tests

#24072 Merge in the rest of Joomla 3.8.12 and all 1 commit of 3.8.13
  administrator/components/com_finder/helpers/indexer/adapter.php
  administrator/components/com_finder/helpers/indexer/driver/mysql.php
  administrator/components/com_finder/helpers/indexer/driver/postgresql.php
  administrator/components/com_finder/helpers/indexer/helper.php
  administrator/components/com_finder/helpers/indexer/indexer.php
  administrator/components/com_finder/helpers/indexer/parser/html.php
  administrator/components/com_finder/helpers/indexer/parser/rtf.php
  administrator/components/com_finder/helpers/indexer/query.php
  administrator/components/com_finder/helpers/indexer/result.php
  administrator/components/com_finder/helpers/indexer/taxonomy.php
  administrator/components/com_finder/helpers/indexer/token.php
  administrator/components/com_installer/Controller/DatabaseController.php
  administrator/components/com_installer/Controller/DiscoverController.php
  administrator/components/com_joomlaupdate/Dispatcher/Dispatcher.php
  administrator/modules/mod_menu/Menu/CssMenu.php
  build/media_source/system/js/fields/calendar-locales/lt.js
  cli/finder_indexer.php
  components/com_contact/Controller/ContactController.php
  components/com_tags/Controller/TagsController.php
  components/com_tags/View/Tags/HtmlView.php
  components/com_users/Controller/RegistrationController.php
  components/com_users/Model/RegistrationModel.php
  components/com_users/tmpl/profile/default_core.php
  language/en-GB/en-GB.com_users.ini
  libraries/cms/html/menu.php
  libraries/src/Document/Document.php
  libraries/src/Filter/InputFilter.php
  libraries/src/Form/Field/CalendarField.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Form/Field/RedirectStatusField.php
  libraries/src/Form/Form.php
  libraries/src/Helper/TagsHelper.php
  libraries/src/MVC/Model/AdminModel.php
  modules/mod_search/mod_search.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24074 Fix path to file
  layouts/joomla/toolbar/basic.php
Labels: PR-4.0-dev

#24075 [4.0] Fix webcomponents not being included on the page
  libraries/src/HTML/HTMLHelper.php
Labels: PR-4.0-dev

#23964 Article Module comments
  modules/mod_articles_category/helper.php
  modules/mod_articles_latest/helper.php
  modules/mod_articles_news/helper.php
  modules/mod_articles_popular/helper.php
Labels: PR-3.10-dev, RTC

#24064 [4.0] Remove com_admin profile
  administrator/components/com_admin/Controller/ProfileController.php
  administrator/components/com_admin/Model/ProfileModel.php
  administrator/components/com_admin/View/Profile/HtmlView.php
  administrator/components/com_admin/forms/profile.xml
  administrator/components/com_admin/tmpl/profile/edit.php
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/modules/mod_status/tmpl/default.php
Labels: Language Change, PR-4.0-dev

#24060 [4.0] Fix SQL Code
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-06.sql
Labels: PR-4.0-dev, RTC

#24078 [4.0] Change Status dropdown consistency
  administrator/components/com_content/View/Articles/HtmlView.php
  administrator/components/com_content/View/Featured/HtmlView.php
Labels: PR-4.0-dev

#24022 [4.0]Table text changed
  administrator/language/en-GB/en-GB.ini
  layouts/joomla/searchtools/default/bar.php
Labels: Language Change, PR-4.0-dev

#24041 [4.0] Fix typehint to be compatible with parent interface
  administrator/components/com_workflow/Model/WorkflowModel.php
Labels: PR-4.0-dev

#24085 Privacy consent plugin is in system group
  plugins/system/privacyconsent/privacyconsent.xml
Labels: RTC

#23984 Fix fatal error on repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table.php
Labels: PR-staging, RTC

#23637 [4.0] Fix debug
  plugins/system/debug/debug.php
Labels: PR-4.0-dev, RTC

#23211 Fix dateadd function for MS SQL Server
  libraries/joomla/database/query/sqlsrv.php
  tests/unit/suites/database/driver/sqlsrv/JDatabaseQuerySqlsrvTest.php
Labels: PR-staging, RTC, Unit/System Tests

#24051 Fix invalid argument supplied & undefined index: id
  components/com_tags/views/tag/view.feed.php
Labels: PR-staging, RTC

#24103 [4.0] Fatal error when editing FileSystem - Local plugin
  plugins/filesystem/local/local.xml
Labels: RTC

#24094 [MSSQL] Correct privacy plugin installation SQL
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-07-09.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.4-2019-03-06.sql
  installation/sql/sqlazure/joomla.sql
Labels: PR-staging, RTC

#23951 [4.0]Added lang string for upload file
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#23967 [4.0]com_media missing download lang string
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
Labels: Language Change, PR-4.0-dev, RTC

#22923 [3.9.1] [com_fields] Make sure disabled fields are not added to the request at all
  plugins/system/fields/fields.php
Labels: PR-staging

#24021 [3.9] Fix possible parent loop issues user groups
  administrator/components/com_users/models/fields/groupparent.php
Labels: PR-staging

#23424 [4.0] [NO CACHE] Web Services
  .drone.yml
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
  administrator/components/com_config/forms/application.xml
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_content/Model/ArticlesModel.php
  administrator/includes/defines.php
  administrator/language/en-GB/en-GB.plg_api-authentication_basic.ini
  administrator/language/en-GB/en-GB.plg_api-authentication_basic.sys.ini
  administrator/language/en-GB/en-GB.plg_webservices_content.ini
  administrator/language/en-GB/en-GB.plg_webservices_content.sys.ini
  api/components/com_content/Controller/ArticlesController.php
  api/components/com_content/View/Articles/JsonapiView.php
  api/includes/app.php
  api/includes/defines.php
  api/includes/framework.php
  api/index.php
  composer.json
  composer.lock
  includes/defines.php
  installation/includes/defines.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  libraries/namespacemap.php
  libraries/src/Access/Exception/AuthenticationFailed.php
  libraries/src/Application/ApiApplication.php
  libraries/src/Application/ApplicationHelper.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/Exception/NotAcceptable.php
  libraries/src/Authentication/Authentication.php
  libraries/src/Component/ComponentHelper.php
  libraries/src/Dispatcher/ApiDispatcher.php
  libraries/src/Document/JsonapiDocument.php
  libraries/src/Error/JsonApi/AuthenticationFailedExceptionHandler.php
  libraries/src/Error/JsonApi/InvalidRouteExceptionHandler.php
  libraries/src/Error/JsonApi/NotAcceptableExceptionHandler.php
  libraries/src/Error/JsonApi/NotAllowedExceptionHandler.php
  libraries/src/Error/JsonApi/ResourceNotFoundExceptionHandler.php
  libraries/src/Error/Renderer/JsonapiRenderer.php
  libraries/src/Extension/Service/Provider/MVCFactory.php
  libraries/src/Factory.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/MVC/Controller/ApiController.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Controller/Exception/ResourceNotFound.php
  libraries/src/MVC/Factory/ApiMVCFactory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/MVC/View/JsonApiView.php
  libraries/src/MVC/View/JsonView.php
  libraries/src/Router/ApiRouter.php
  libraries/src/Serializer/JoomlaSerializer.php
  libraries/src/Service/Provider/ApiRouter.php
  libraries/src/Service/Provider/Application.php
  plugins/api-authentication/basic/basic.php
  plugins/api-authentication/basic/basic.xml
  plugins/system/debug/debug.php
  plugins/webservices/content/content.php
  plugins/webservices/content/content.xml
Labels: Composer Dependency Changed, Language Change, PR-4.0-dev, Unit/System Tests

#22740 [com_actionlogs] - log actionlog purge/export
  administrator/components/com_actionlogs/controllers/actionlogs.php
  administrator/components/com_actionlogs/models/actionlogs.php
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
  plugins/actionlog/joomla/joomla.php
Labels: Language Change, PR-staging

#24058 [3.9] Wrong default value [SQL ]
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-02.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-24.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-08-12.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-staging, RTC

#23767 [4.0] Toolbar custom element improvements
  build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#22739 [com_actionlogs] - log cache actions
  administrator/components/com_cache/controller.php
  administrator/components/com_cache/models/cache.php
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
  plugins/actionlog/joomla/joomla.php
Labels: Language Change, PR-staging, RTC

#24121 Fix missing string for webservices login permission
  administrator/language/en-GB/en-GB.ini
  language/en-GB/en-GB.ini
Labels: Language Change, PR-4.0-dev

#23881 [4.0] User field custom element clean up
  build/media_source/system/js/fields/joomla-field-user.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, PR-staging

#22844 [BS2] Fix for XSS issue with data-target attributes in BS2 JS
  media/jui/js/bootstrap.js
  media/jui/js/bootstrap.min.js
Labels: PR-staging, RTC

#24133 Small webservice related fixes
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
  plugins/webservices/content/content.xml
Labels: PR-4.0-dev

#24124 [4.0] Remove references to non-existing files
  libraries/bootstrap.php
  libraries/import.legacy.php
  libraries/import.php
Labels: PR-4.0-dev

#24120 [4.0] Fix session constant
  libraries/src/Session/MetadataManager.php
Labels: PR-4.0-dev

#24119 [4.0] Namespace JMailHelper
  libraries/src/Table/User.php
Labels: PR-4.0-dev, RTC

#24136 [4.0] Postgres default date
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev, RTC

#23986 Feature/unit tests
  .appveyor.yml
  .drone.yml
  .travis.yml
  composer.json
  libraries/src/Feed/FeedFactory.php
  libraries/src/Mail/Mail.php
  phpunit.xml.dist
  tests/README.md
  tests/Unit/Libraries/Cms/Access/RuleTest.php
  tests/Unit/Libraries/Cms/Access/RulesTest.php
  tests/Unit/Libraries/Cms/Document/DocumentTest.php
  tests/Unit/Libraries/Cms/Environment/BrowserTest.php
  tests/Unit/Libraries/Cms/Feed/FeedEntryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedFactoryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedLinkTest.php
  tests/Unit/Libraries/Cms/Feed/FeedParserTest.php
  tests/Unit/Libraries/Cms/Feed/FeedTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlDateTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlNumberTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlStringTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlTelTest.php
  tests/Unit/Libraries/Cms/Layout/BaseLayoutTest.php
  tests/Unit/Libraries/Cms/Mail/MailHelperTest.php
  tests/Unit/Libraries/Cms/Mail/MailTest.php
  tests/Unit/Libraries/Cms/Mircodata/MicrodataTest.php
  tests/Unit/Libraries/Cms/Object/CMSObjectTest.php
  tests/Unit/Libraries/Cms/Toolbar/Button/CustomButtonTest.php
  tests/Unit/Libraries/Cms/Toolbar/ToolbarTest.php
  tests/Unit/Libraries/Cms/VersionTest.php
  tests/Unit/README.md
  tests/Unit/UnitTestCase.php
  tests/Unit/bootstrap.php
Labels: Composer Dependency Changed, PR-4.0-dev, Unit/System Tests

#24044 [4.0] Bring the Tests Back Home
  package-lock.json
  package.json
  tests/README.md
  tests/javascript/joomla-switcher/fixtures/fixture.html
  tests/javascript/joomla-switcher/joomla-switcher.spec.js
  tests/javascript/karma.conf.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Unit/System Tests

#24086 [com_actionlogs] - fix checkLoggable for com_checkin
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging, RTC

#24143 [4.0] Correct update SQL
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
Labels: PR-4.0-dev, RTC

#24172 [4.0] Test: Fixing name of Microdata Test
  tests/Unit/Libraries/Cms/Microdata/MicrodataTest.php
Labels: PR-4.0-dev, Unit/System Tests

#24163 [4.0] Fix uninstalling extensions
  plugins/extension/finder/finder.php
Labels: PR-4.0-dev

#24101 [4.0] Set sample data articles to publish
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev, RTC

#24166 [4.0] Warning message : JUser: :_load: Unable to load user with ID
  administrator/language/en-GB/en-GB.lib_joomla.ini
Labels: Language Change, PR-4.0-dev

#22380 [4.0] Remove deprecated code from the Content table class
  libraries/src/Table/Content.php
Labels: PR-4.0-dev

#24169 [4.0] Fix SCSS build script
  build/build-modules-js/compilecss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
Labels: PR-4.0-dev

#24192 Joomla 3.9.0 Part 2
  administrator/components/com_content/config.xml
  administrator/components/com_installer/Model/InstallModel.php
  administrator/components/com_installer/Model/InstallerModel.php
  administrator/components/com_installer/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/Model/UpdateModel.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/language/en-GB/en-GB.com_installer.ini
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
  administrator/language/en-GB/en-GB.ini
  administrator/language/en-GB/en-GB.mod_feed.ini
  administrator/modules/mod_feed/mod_feed.xml
  administrator/modules/mod_feed/tmpl/default.php
  build/media_source/com_modules/js/admin-modules-modal.es6.js
  components/com_content/Model/ArticlesModel.php
  components/com_content/View/Category/HtmlView.php
  components/com_content/tmpl/category/default.xml
  components/com_content/tmpl/category/default_articles.php
  language/en-GB/en-GB.ini
  language/en-GB/en-GB.mod_feed.ini
  libraries/cms/html/content.php
  libraries/joomla/controller/base.php
  libraries/joomla/model/base.php
  libraries/joomla/model/database.php
  libraries/joomla/model/model.php
  libraries/joomla/view/base.php
  libraries/joomla/view/html.php
  libraries/joomla/view/view.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/Layout/BaseLayout.php
  libraries/src/MVC/View/HtmlView.php
  libraries/src/Router/AdministratorRouter.php
  libraries/src/Router/Route.php
  libraries/src/Router/SiteRouter.php
  modules/mod_feed/mod_feed.xml
  modules/mod_feed/tmpl/default.php
  plugins/content/loadmodule/loadmodule.php
  plugins/system/languagefilter/languagefilter.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#23667 [4.0] FIX Unreliable way of loading ServiceProviderInterface class in ExtensionManagerTrait.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Extension/ExtensionManagerTrait.php
Labels: PR-4.0-dev

#24149 [4.0] - PDO Session table field guest
  libraries/src/Session/MetadataManager.php
Labels: PR-4.0-dev

#24173 [4.0] Preview button translated twice
  administrator/components/com_content/View/Article/HtmlView.php
Labels: PR-4.0-dev, RTC

#24106 [4.0] Use namespaced version of JFactory everywhere
  administrator/components/com_associations/layouts/joomla/searchtools/default.php
  administrator/components/com_content/tmpl/articles/default_batch_body.php
  build/stubGenerator.php
  cli/finder_indexer.php
  installation/template/message.php
  libraries/joomla/base/adapter.php
  libraries/joomla/base/adapterinstance.php
  libraries/joomla/controller/base.php
  libraries/src/Form/Field/CalendarField.php
  plugins/system/updatenotification/postinstall/updatecachetime.php
  plugins/twofactorauth/totp/postinstall/actions.php
  templates/system/html/modules.php
  templates/system/offline.php
Labels: PR-4.0-dev, RTC

#24113 [4.0]Breadcrumbs are now more accessible
  modules/mod_breadcrumbs/tmpl/default.php
Labels: PR-4.0-dev, RTC

#24098 [4.0] fix the page break tabs view
  administrator/components/com_plugins/tmpl/plugin/edit.php
  plugins/content/pagebreak/pagebreak.php
Labels: PR-4.0-dev, RTC

#24090 [4.0] Filesystem plugin - simplify text
  administrator/language/en-GB/en-GB.plg_filesystem_local.ini
  administrator/language/en-GB/en-GB.plg_filesystem_local.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#24091 [4.0] Packages or Extensions
  administrator/language/en-GB/en-GB.com_installer.ini
  administrator/language/en-GB/en-GB.plg_installer_folderinstaller.ini
  administrator/language/en-GB/en-GB.plg_installer_folderinstaller.sys.ini
  administrator/language/en-GB/en-GB.plg_installer_packageinstaller.ini
  administrator/language/en-GB/en-GB.plg_installer_packageinstaller.sys.ini
  administrator/language/en-GB/en-GB.plg_installer_urlinstaller.ini
  administrator/language/en-GB/en-GB.plg_installer_urlinstaller.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#24147 [4.0] - wrong sql in WorkflowstageField
  libraries/src/Form/Field/WorkflowstageField.php
Labels: PR-4.0-dev

#24118 [4.0] Namespace com_templates default
  administrator/components/com_templates/tmpl/templates/default.php
Labels: PR-4.0-dev, RTC

#24158 [4.0] Fix case of "Blog Sample data"
  administrator/language/en-GB/en-GB.plg_sampledata_blog.ini
Labels: Language Change, PR-4.0-dev, RTC

#23892 [4.0][Fix] Language change for toggle editor button
  administrator/language/en-GB/en-GB.plg_editors_tinymce.ini
Labels: Language Change, PR-4.0-dev, RTC

#23764 [4.0] Fix wrong error message on connecting mysql
  installation/language/en-GB/en-GB.ini
  installation/language/en-US/en-US.ini
Labels: Language Change, PR-4.0-dev, RTC

#24199 [4.0] Fix install error: JInstallerHelper' not found
  administrator/components/com_installer/Model/InstallModel.php
Labels: PR-4.0-dev, RTC

#24219 [4.0] Use namespaced classes in Access library
  libraries/src/Access/Access.php
Labels: PR-4.0-dev

#24220 [4.0] Use namespaced classes in Language library
  libraries/src/Language/Associations.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/Language/Text.php
Labels: PR-4.0-dev

#24223 [4.0] Add a writable command loader
  libraries/src/Console/Loader/WritableContainerLoader.php
  libraries/src/Console/Loader/WritableLoaderInterface.php
  libraries/src/Service/Provider/Application.php
  tests/Unit/Libraries/Cms/Console/Loader/WritableContainerLoaderTest.php
Labels: Documentation Required, PR-4.0-dev, Unit/System Tests

#23931 [4.0] contrast improved
  build/media_source/system/scss/fields/joomla-field-switcher.scss
Labels: NPM Resource Changed, PR-4.0-dev

#23385 [4.0] A zero cost huge performance win
  build.js
  build/build-modules-js/gzip-assets.es6.js
  build/build.php
  htaccess.txt
  installation/template/css/template.css.map
  package-lock.json
  package.json
Labels: Documentation Required, NPM Resource Changed, PR-4.0-dev

#24228 [4.0] Correcting contacts batch notice (uncomplete)
  administrator/components/com_contact/tmpl/contacts/default_batch.php
  administrator/components/com_contact/tmpl/contacts/default_batch_body.php
Labels: PR-4.0-dev

#23851 [4.0] adapting saved language message to different settings
  administrator/components/com_languages/Controller/InstalledController.php
  administrator/language/en-GB/en-GB.com_languages.ini
Labels: Language Change, PR-4.0-dev

#23254 [4.0][a11y] Amenu
  build/media_src/mod_menu/js/menu.es6.js
  modules/mod_menu/tmpl/default.php
Labels: PR-4.0-dev

#24210 [3.9][com_installer] Show error alert on error, not message alert
  administrator/components/com_installer/models/update.php
Labels: PR-staging, RTC

#24224 [4.0] Namespace classes in com_finder
  administrator/components/com_finder/tmpl/filter/edit.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/searches/default.php
Labels: PR-4.0-dev

#24225 [4.0] Namespace classes
  installation/template/message.php
Labels: PR-4.0-dev

#24236 [3.9] Wrong language string. Menu item type content/featured
  components/com_content/views/featured/tmpl/default.xml
Labels: RTC

#21901 [4.0] Replace the zero datetime value '0000-00-00 00:00:00' by the real NULL value
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-08-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-08-29.sql
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_testing.sql
  installation/src/Model/DatabaseModel.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Table/Module.php
  libraries/src/Table/Table.php
Labels: Documentation Required, PR-4.0-dev

#24243 [4.0] Fix Toolbar Buttons enable and disable
  build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#24258 [4.0] [com_media] Various changes for the delete vue
  administrator/components/com_media/resources/scripts/components/modals/confirm-delete-modal.vue
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#23934 [4.0] Add support to unpublish module from Control Panel
  administrator/components/com_cpanel/tmpl/cpanel/default.php
  administrator/language/en-GB/en-GB.com_cpanel.ini
  administrator/language/en-GB/en-GB.ini
  administrator/modules/mod_status/tmpl/default.php
  administrator/templates/atum/html/modules.php
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_header.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/system/scss/joomla-toolbar-button.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24263 [4.0] Replace deprecated Joomla\DI\Container::exists() calls
  libraries/joomla/base/adapter.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Factory.php
  libraries/src/Installer/Installer.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/Router/Router.php
  libraries/src/Table/Table.php
Labels: PR-4.0-dev

#24267 [4.0] Deprecated language strings
  administrator/language/en-GB/en-GB.ini
  language/en-GB/en-GB.com_messages.ini
  language/en-GB/en-GB.ini
Labels: RTC

#24277 [4.0] [a11y] Remove redundant title from templates
  templates/cassiopeia/offline.php
  templates/system/error.php
Labels: PR-4.0-dev

#24010 [4.0] Removing module chrome "no" from atum
  administrator/templates/atum/html/modules.php
Labels: PR-4.0-dev

#24285 [4.0] com_media untranslated string
  administrator/components/com_media/resources/scripts/components/modals/share-modal.vue
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24282 [4.0] [a11y] Remove redundant title from site components
  components/com_contact/tmpl/categories/default_items.php
  components/com_content/tmpl/categories/default_items.php
  components/com_content/tmpl/category/blog_children.php
  components/com_content/tmpl/category/default_children.php
  components/com_mailto/tmpl/mailto/default.php
  components/com_newsfeeds/tmpl/categories/default_items.php
  components/com_newsfeeds/tmpl/category/default_items.php
  components/com_users/tmpl/registration/default.php
  language/en-GB/en-GB.com_content.ini
Labels: Language Change, PR-4.0-dev

#24278 [4.0] [a11y] Remove redundant title from modules
  administrator/modules/mod_stats_admin/tmpl/default.php
  language/en-GB/en-GB.mod_finder.ini
  modules/mod_finder/tmpl/default.php
Labels: Language Change, PR-4.0-dev

#24213 [4.0]improved contrast in icon during installation
  installation/template/scss/template.scss
Labels: PR-4.0-dev, RTC

#24088 [4.0][com_users] Add cancel action to profile form
  components/com_users/Controller/ProfileController.php
  components/com_users/tmpl/profile/edit.php
Labels: PR-4.0-dev, RTC

#24274 [4.0] Modals: using default padding
  administrator/templates/atum/scss/blocks/_modals.scss
Labels: PR-4.0-dev

#23757 [4.0][a11y]Extra column for icon featured
  administrator/components/com_content/tmpl/featured/default.php
Labels: PR-4.0-dev, RTC

#24080 [4.0] Remove sidebar from com_installer
  administrator/components/com_installer/Helper/InstallerHelper.php
  administrator/components/com_installer/View/Discover/HtmlView.php
  administrator/components/com_installer/View/Installer/HtmlView.php
  administrator/components/com_installer/View/Manage/HtmlView.php
  administrator/components/com_installer/View/Update/HtmlView.php
  administrator/components/com_installer/View/Updatesites/HtmlView.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/install/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_installer/tmpl/warnings/default.php
  administrator/language/en-GB/en-GB.com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#24092 [4.0] com_templates sidebar
  administrator/components/com_templates/View/Styles/HtmlView.php
  administrator/components/com_templates/View/Templates/HtmlView.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/templates/default.php
Labels: PR-4.0-dev, RTC

#23885 [4.0][a11y] Extra column for icon featured in com_contact
  administrator/components/com_contact/tmpl/contacts/default.php
Labels: PR-4.0-dev, RTC

#23978 [4.0] Fix modified time for new entries in fields and field groups
  administrator/components/com_fields/Table/FieldTable.php
  administrator/components/com_fields/Table/GroupTable.php
Labels: PR-4.0-dev, RTC

#24053 [4.0][mod_articles_category] Remove unused variable
  modules/mod_articles_category/mod_articles_category.php
Labels: PR-4.0-dev, RTC

#24123 [4.0] Fix for article being submitted by Enter key
  layouts/joomla/editors/buttons/modal.php
  layouts/joomla/form/field/media.php
Labels: PR-4.0-dev, RTC

#23686 [4.0][a11y] Improve accessiblity in mod_finder
  modules/mod_finder/tmpl/default.php
Labels: PR-4.0-dev, RTC

#23497 Add a filter featured to content articles
  administrator/components/com_content/Model/ArticlesModel.php
  administrator/components/com_content/forms/filter_articles.xml
  administrator/language/en-GB/en-GB.com_content.ini
Labels: Language Change, PR-4.0-dev, RTC

#24276 [4.0] Fix disable and enable buttons
  build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#24275 [4.0] [a11y] Remove title from fieldset
  administrator/components/com_config/tmpl/application/default_ftplogin.php
  administrator/components/com_installer/tmpl/installer/default_ftp.php
Labels: PR-4.0-dev

#24280 [4.0] [a11y] Remove redundant title from layouts and plugins
  administrator/components/com_media/layouts/toolbar/create-folder.php
  administrator/components/com_media/layouts/toolbar/delete.php
  administrator/components/com_media/layouts/toolbar/upload.php
  administrator/components/com_modules/layouts/toolbar/cancelselect.php
  layouts/joomla/form/field/contenthistory.php
  layouts/joomla/pagination/link.php
  layouts/joomla/searchtools/default/bar.php
  layouts/joomla/tinymce/togglebutton.php
  layouts/joomla/toolbar/modal.php
  layouts/joomla/toolbar/versions.php
  plugins/user/profile/field/tos.php
Labels: PR-4.0-dev

#24272 [4.0] Get document from application in HTMLHelper
  libraries/src/HTML/HTMLHelper.php
Labels: PR-4.0-dev

#24273 [4.0] [com_modules] Batch language broken
  administrator/components/com_modules/tmpl/modules/default_batch_body.php
Labels: PR-4.0-dev

#24281 [4.0] Status Module: Edit Account redirection
  administrator/components/com_users/Controller/UserController.php
  administrator/components/com_users/tmpl/user/edit.php
  administrator/modules/mod_status/tmpl/default.php
Labels: PR-4.0-dev

#24271 [4.0] Redirect to CPanel when module in cpanel position has been edited
  administrator/components/com_modules/Controller/ModuleController.php
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/templates/atum/html/modules.php
Labels: PR-4.0-dev

#24283 [4.0] [a11y] Remove redundant title from admin components
  administrator/components/com_menus/Field/MenutypeField.php
  administrator/components/com_menus/tmpl/menutypes/default.php
  administrator/components/com_users/Service/HTML/Users.php
  administrator/components/com_users/tmpl/user/edit.php
Labels: PR-4.0-dev

#23946 [4.0] Move description label
  administrator/components/com_contact/tmpl/contact/edit.php
  administrator/components/com_tags/tmpl/tag/edit.php
Labels: RTC

#24242 [4.0] Label com_content
  administrator/components/com_content/tmpl/article/edit.php
Labels: PR-4.0-dev

#24265 [4.0] Change color to have sufficient contrast as per a11y standards
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_login.scss
Labels: PR-4.0-dev

#24206 [4.0][plg_authentication_joomla] Use injected app and DB
  plugins/authentication/joomla/joomla.php
Labels: PR-4.0-dev

#22849 [4.0] Use a factory to create user objects from
  libraries/src/Application/IdentityAware.php
  libraries/src/Factory.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/User.php
  libraries/src/User/User.php
  libraries/src/User/UserFactory.php
  libraries/src/User/UserFactoryInterface.php
Labels: PR-4.0-dev

#23769 [4.0] Fix FolderlistField.php on Windows
  libraries/src/Form/Field/FolderlistField.php
Labels: PR-4.0-dev

#24146 [4.0] - install on Postgresql fixes
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-02.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#24207 [4.0] Fix inconsistency in order of toolbar buttons in com_users
  administrator/components/com_modules/View/Modules/HtmlView.php
  administrator/components/com_users/View/Users/HtmlView.php
Labels: PR-4.0-dev

#24212 [4.0] Use namespaced classes in Form library
  libraries/src/Form/Field/AliastagField.php
  libraries/src/Form/Field/AuthorField.php
  libraries/src/Form/Field/CachehandlerField.php
  libraries/src/Form/Field/CategoryField.php
  libraries/src/Form/Field/CheckboxesField.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Form/Field/ComboField.php
  libraries/src/Form/Field/ComponentsField.php
  libraries/src/Form/Field/ContentlanguageField.php
  libraries/src/Form/Field/ContenttypeField.php
  libraries/src/Form/Field/DatabaseconnectionField.php
  libraries/src/Form/Field/EditorField.php
  libraries/src/Form/Field/EmailField.php
  libraries/src/Form/Field/FilelistField.php
  libraries/src/Form/Field/FolderlistField.php
  libraries/src/Form/Field/FrontendlanguageField.php
  libraries/src/Form/Field/HeadertagField.php
  libraries/src/Form/Field/HelpsiteField.php
  libraries/src/Form/Field/ImagelistField.php
  libraries/src/Form/Field/IntegerField.php
  libraries/src/Form/Field/LanguageField.php
  libraries/src/Form/Field/LastvisitdaterangeField.php
  libraries/src/Form/Field/LimitboxField.php
  libraries/src/Form/Field/MenuField.php
  libraries/src/Form/Field/MenuitemField.php
  libraries/src/Form/Field/MeterField.php
  libraries/src/Form/Field/ModulepositionField.php
  libraries/src/Form/Field/ModuletagField.php
  libraries/src/Form/Field/PluginstatusField.php
  libraries/src/Form/Field/RadioField.php
  libraries/src/Form/Field/RadiobasicField.php
  libraries/src/Form/Field/RangeField.php
  libraries/src/Form/Field/RedirectStatusField.php
  libraries/src/Form/Field/RegistrationdaterangeField.php
  libraries/src/Form/Field/SessionhandlerField.php
  libraries/src/Form/Field/SqlField.php
  libraries/src/Form/Field/StatusField.php
  libraries/src/Form/Field/TelephoneField.php
  libraries/src/Form/Field/TemplatestyleField.php
  libraries/src/Form/Field/TimezoneField.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/Form/Field/UrlField.php
  libraries/src/Form/Field/UseractiveField.php
  libraries/src/Form/Field/UsergrouplistField.php
  libraries/src/Form/Field/UserstateField.php
  libraries/src/Form/Form.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormFilterInterface.php
Labels: PR-4.0-dev

#24222 [4.0] Use namespaced classes in Menu library
  libraries/src/Menu/AbstractMenu.php
  libraries/src/Menu/SiteMenu.php
Labels: PR-4.0-dev

#24221 [4.0] Use namespaced classes in Helper library
  libraries/src/Helper/AuthenticationHelper.php
  libraries/src/Helper/LibraryHelper.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Helper/RouteHelper.php
  libraries/src/Helper/TagsHelper.php
Labels: PR-4.0-dev

#24289 [4.0] Sidebar failure from #24080
  administrator/components/com_installer/Controller/DisplayController.php
Labels: PR-4.0-dev

#23123 [4.0][com_content] Remove column-related code.
  administrator/language/en-GB/en-GB.ini
  components/com_content/Helper/QueryHelper.php
  components/com_content/View/Category/HtmlView.php
  components/com_content/View/Featured/HtmlView.php
  components/com_content/tmpl/categories/default.xml
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_testing.sql
  installation/src/Model/LanguagesModel.php
  plugins/sampledata/multilang/multilang.php
Labels: Language Change, PR-4.0-dev

#24244 Correcting Associations tab display when using Indonesian id-ID language
  media/system/js/associations-edit-uncompressed.js
  media/system/js/associations-edit.js
Labels: PR-staging, RTC

#24200 [3.9] Message reporting changed to error type
  libraries/src/Application/SiteApplication.php
Labels: PR-staging, RTC

#24216 [staging] category field readonly when editing an existing item in frontend
  administrator/components/com_content/models/article.php
Labels: PR-staging, RTC

#24309 [4.0] fix javascript linter failures
  .drone.yml
  build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
  package-lock.json
  package.json
  plugins/system/stats/stats.php
Labels: NPM Resource Changed, PR-4.0-dev, Unit/System Tests

#24301 [4.0] WebComponents not loading without media version
  build/media_source/system/js/core.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#24230 Add minimum lowercase rule for password validation.
  administrator/components/com_users/config.xml
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/language/en-GB/en-GB.com_users.ini
  language/en-GB/en-GB.com_users.ini
  libraries/src/Form/Rule/PasswordRule.php
Labels: Language Change, PR-staging, RTC

#24310 [4.0] Date in example string
  administrator/language/en-GB/en-GB.plg_user_profile.ini
Labels: Language Change, PR-4.0-dev

#24178 [staging] Correcting User Actions Log Manager when debug language is enabled
  administrator/components/com_actionlogs/helpers/actionlogs.php
Labels: PR-staging, RTC

#24313 [4.0] Move defined statement
  administrator/components/com_config/tmpl/application/default_ftplogin.php
Labels: PR-4.0-dev

#24296 [4.0] com_admin.ini review
  administrator/language/en-GB/en-GB.com_admin.ini
Labels: Language Change, PR-4.0-dev

#24320 [4.0] Remove magic quotes
  administrator/language/en-GB/en-GB.ini
  tests/Unit/bootstrap.php
Labels: RTC

#24321 [4.0] Remove tag_desc
  administrator/language/en-GB/en-GB.ini
  language/en-GB/en-GB.ini
  modules/mod_articles_news/mod_articles_news.xml
Labels: Language Change, PR-4.0-dev, RTC

#24332 [4.0] Correcting broken multilingual
  plugins/system/languagefilter/languagefilter.php
Labels: PR-4.0-dev

#24256 Change alert type for mail disabled notification
  libraries/src/Mail/Mail.php
Labels: PR-staging

#24026 [4.0] Show changelog - GSoC Expand Extensions Manager #17536 redo
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2017-06-03.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2017-06-03.sql
  administrator/components/com_installer/Controller/ManageController.php
  administrator/components/com_installer/Model/ManageModel.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/language/en-GB/en-GB.com_installer.ini
  administrator/templates/atum/scss/blocks/_modals.scss
  build/media_source/system/js/core.es6.js
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  layouts/joomla/installer/changelog.php
  libraries/src/Changelog/Changelog.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/InstallerAdapter.php
  libraries/src/Updater/UpdateAdapter.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24142 [4.0] [a11y] Add SkipTo Navigation plugin
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
  administrator/language/en-GB/en-GB.plg_system_skipto.ini
  administrator/language/en-GB/en-GB.plg_system_skipto.sys.ini
  build/build-modules-js/settings.json
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  package.json
  plugins/system/skipto/skipto.php
  plugins/system/skipto/skipto.xml
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#24353 [4.0] Fix Language Code plugin
  plugins/system/languagecode/languagecode.php
Labels: PR-4.0-dev

#24356 Joomla 3.9.0 Merge Part 3
  administrator/components/com_content/Model/ArticlesModel.php
  administrator/components/com_content/Model/FeaturedModel.php
  administrator/components/com_languages/Helper/LanguagesHelper.php
  administrator/components/com_languages/Model/OverrideModel.php
  administrator/components/com_languages/Model/OverridesModel.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/language/en-GB/en-GB.com_content.ini
  administrator/modules/mod_stats_admin/Helper/StatsAdminHelper.php
  administrator/modules/mod_stats_admin/tmpl/default.php
  build/media_source/system/js/showon.es6.js
  layouts/joomla/form/field/list.php
  libraries/cms/html/content.php
  libraries/src/Form/Field/ListField.php
  libraries/src/Form/Rule/ExistsRule.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/MVC/Controller/FormController.php
  plugins/content/pagebreak/pagebreak.php
  plugins/content/pagebreak/tmpl/toc.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#23570 [4.0] Change ModuleChromes to JLayouts
  administrator/components/com_login/tmpl/login/default.php
  administrator/components/com_modules/forms/advanced.xml
  administrator/templates/atum/error_full.php
  administrator/templates/atum/html/layouts/chromes/body.php
  administrator/templates/atum/html/layouts/chromes/title.php
  administrator/templates/atum/html/layouts/chromes/well.php
  administrator/templates/atum/html/modules.php
  administrator/templates/atum/index.php
  administrator/templates/system/html/modules.php
  layouts/chromes/html5.php
  layouts/chromes/none.php
  layouts/chromes/outline.php
  layouts/chromes/sliders.php
  layouts/chromes/table.php
  layouts/chromes/tabs.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Helper/ModuleHelper.php
  templates/cassiopeia/html/layouts/chromes/cardGrey.php
  templates/cassiopeia/html/layouts/chromes/default.php
  templates/cassiopeia/html/modules.php
  templates/system/html/modules.php
Labels: PR-4.0-dev

#24347 [4.0] com _CSP Options help link
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, PR-4.0-dev

#24195 [4.0] Make the preview url respect SEF settings
  administrator/components/com_content/Helper/PreviewHelper.php
  administrator/components/com_content/View/Article/HtmlView.php
Labels: PR-4.0-dev

#24371 Joomla 3.9.0 Part #5
  administrator/components/com_actionlogs/models/actionlogs.php
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-05-05.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.0-2018-06-14.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-05-05.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.0-2018-06-14.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-14.sql
  administrator/components/com_menus/presets/joomla.xml
  administrator/components/com_menus/presets/modern.xml
  administrator/components/com_privacy/controller.php
  administrator/components/com_privacy/controllers/request.php
  administrator/components/com_privacy/helpers/removal/status.php
  administrator/components/com_privacy/models/remove.php
  administrator/components/com_privacy/models/request.php
  administrator/components/com_privacy/views/request/tmpl/default.php
  administrator/components/com_privacy/views/request/view.html.php
  administrator/components/com_privacy/views/requests/tmpl/default.php
  administrator/language/en-GB/en-GB.com_actionlogs.ini
  administrator/language/en-GB/en-GB.com_privacy.ini
  administrator/language/en-GB/en-GB.mod_menu.ini
  administrator/language/en-GB/en-GB.mod_privacy_dashboard.ini
  administrator/language/en-GB/en-GB.mod_privacy_dashboard.sys.ini
  administrator/language/en-GB/en-GB.plg_privacy_user.ini
  administrator/language/en-GB/en-GB.plg_system_privacyconsent.ini
  administrator/modules/mod_privacy_dashboard/helper.php
  administrator/modules/mod_privacy_dashboard/mod_privacy_dashboard.php
  administrator/modules/mod_privacy_dashboard/mod_privacy_dashboard.xml
  administrator/modules/mod_privacy_dashboard/tmpl/default.php
  components/com_privacy/models/confirm.php
  components/com_privacy/models/request.php
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_testing.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_testing.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/privacy/user/user.php
  plugins/system/privacyconsent/field/privacy.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: Language Change, PR-4.0-dev

#24352 [4.0][com_plugins] Missing plugin ordering field type
  administrator/components/com_plugins/forms/plugin.xml
Labels: PR-4.0-dev

#24367 [4.0] - install remove notice
  libraries/src/Installer/Adapter/ComponentAdapter.php
Labels: PR-4.0-dev

#24394 Missing imports in content plugins
  plugins/content/pagebreak/pagebreak.php
  plugins/content/pagenavigation/pagenavigation.php
Labels: PR-staging

#24358 [4.0] Fix module ordering field
  build/media_source/system/js/fields/joomla-field-module-order.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#24390 [3.9][JLayout images] Remove unnecessary isset(...)
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
Labels: PR-staging, RTC

#24396 [4.0] [NO CACHE] Update package lock
  package-lock.json
Labels: NPM Resource Changed, PR-4.0-dev

#24389 [3.9][com_content featured] Remove redundant intro_image check
  components/com_content/views/featured/tmpl/default_item.php
Labels: PR-staging, RTC

#24408 [4.0] en-GB spelling
  administrator/language/en-GB/en-GB.plg_fields_repeatable.sys.ini
Labels: Language Change, PR-4.0-dev

#24399 [4.0] Remove myself from code owners
  .github/CODEOWNERS
Labels: PR-staging
