Repository joomla/joomla-cms, pull requests merged in 2019-12, with the labels that each got.

#27191 [4.0] Bump PHP minimum to 7.2.5
  administrator/index.php
  api/index.php
  cli/joomla.php
  index.php
  installation/index.php
Labels: Documentation Required, RTC

#27189 [4.0] Change plugin statistics popup to be alertdialog
  plugins/system/stats/layouts/message.php
Labels: PR-4.0-dev, RTC

#27190 Joomla 4.0 updated to PHP 7.2.5 as minimum
  administrator/components/com_admin/postinstall/joomla40checks.php
  administrator/language/en-GB/en-GB.com_cpanel.ini
Labels: PR-staging, RTC

#27204 [4.0] [lib_joomla.ini] alpha order, add missing strings, syncing admin and site files
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: Language Change, PR-4.0-dev

#27183 [4.0] [plg_sampledata_multilang] Add missing checks
  plugins/sampledata/multilang/multilang.php
Labels: PR-4.0-dev, RTC

#27088 [4.0][com_associations] convert to prepared statement
  administrator/components/com_associations/Helper/AssociationsHelper.php
  administrator/components/com_associations/Model/AssociationsModel.php
Labels: PR-4.0-dev, RTC

#27187 [4.0] Fixing iframes missing assets
  administrator/templates/atum/component.php
Labels: PR-4.0-dev, RTC

#27206 [4.0][com_menu] fix blank space in menu type
  administrator/components/com_menus/Controller/MenuController.php
Labels: PR-4.0-dev, RTC

#27174 [4.0] Fix Untranslated tip
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  layouts/joomla/button/action-button.php
  layouts/joomla/button/transition-button.php
  libraries/src/Button/FeaturedButton.php
  libraries/src/Button/PublishedButton.php
Labels: PR-4.0-dev, RTC

#27161 Allow JSON Document caching
  components/com_ajax/ajax.php
  components/com_config/controller/display.php
  components/com_finder/controllers/suggestions.json.php
  libraries/src/Document/ErrorDocument.php
  libraries/src/Document/FeedDocument.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Document/ImageDocument.php
  libraries/src/Document/JsonDocument.php
  libraries/src/Document/OpensearchDocument.php
  libraries/src/Document/RawDocument.php
  libraries/src/Document/XmlDocument.php
Labels: PR-staging

#27209 Fix language debug on multilingual sites
  plugins/system/languagefilter/languagefilter.php
Labels: PR-staging, RTC

#27203 [com_banners] Remove onchange submit from calendar fields
  administrator/components/com_banners/models/forms/filter_tracks.xml
Labels: PR-staging, RTC

#27197 [plg_quickicon_phpversioncheck] Avoid errors when Joomla! gets outdated
  administrator/language/en-GB/en-GB.plg_quickicon_phpversioncheck.ini
  plugins/quickicon/phpversioncheck/phpversioncheck.php
Labels: PR-staging, RTC

#27186 [4.0] Remove duplicate buttons in installation
  installation/tmpl/remove/default.php
Labels: PR-4.0-dev, RTC

#26875 [com_banners] Avoid running the query when no keywords are provided
  components/com_banners/models/banners.php
Labels: PR-staging, RTC

#27055 calendar field not triggering onchange after clear button pressed
  media/system/js/fields/calendar.js
  media/system/js/fields/calendar.min.js
Labels: PR-staging, RTC

#21007 Fix caching of the script options
  libraries/src/Document/HtmlDocument.php
Labels: PR-staging, RTC

#20225 Fix up the beez3 template.js
  templates/beez3/javascript/template.js
Labels: PR-staging, RTC

#17009 fixed missing own asset rule for parent recursive get access rule
  libraries/src/Access/Access.php
Labels: PR-staging, RTC

#26974 Update jQuery Autocomplete to 1.4.10
  media/jui/js/jquery.autocomplete.js
  media/jui/js/jquery.autocomplete.min.js
Labels: PR-staging, RTC

#26675 [4.0] Fixed lost request parameters on save
  administrator/components/com_menus/Controller/ItemController.php
Labels: PR-4.0-dev, RTC

#27044 [4.0] Update joomla/database
  administrator/components/com_menus/Controller/MenusController.php
  administrator/components/com_menus/Model/ItemModel.php
  administrator/components/com_menus/Model/MenusModel.php
  composer.lock
  libraries/src/Installer/Adapter/LanguageAdapter.php
Labels: Composer Dependency Changed, PR-4.0-dev

#27216 [4.0] Correct implode() argument order
  layouts/joomla/form/field/moduleorder.php
Labels: PR-4.0-dev

#27159 [4.0] [com_associations] Fix language association "clear" action
  build/media_source/com_associations/js/sidebyside.es5.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27219 Fix Notice on Joomla update with PHP 7.4
  administrator/components/com_joomlaupdate/views/default/view.html.php
Labels: PR-staging, RTC

#26747 Fields - hidden secrets
  administrator/components/com_fields/models/forms/filter_fields.xml
  administrator/components/com_fields/models/forms/filter_groups.xml
  administrator/language/en-GB/en-GB.com_fields.ini
Labels: Language Change, PR-staging, RTC

#27218 MySql 8 EXPLAIN syntax
  plugins/system/debug/debug.php
Labels: RTC

#27228 [4.0] Fix update to 4.0-beta1-dev failing with SQL error when updating from 3.9 or 3.10 with testing sample data
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-08-01.sql
Labels: PR-4.0-dev, RTC

#27230 [3.9] com_media. Show full video filename and preview icon
  administrator/components/com_media/views/medialist/tmpl/details_videos.php
Labels: PR-staging, RTC

#25996 Show a different message when we cant connect to the languages update site
  administrator/components/com_installer/models/languages.php
  administrator/language/en-GB/en-GB.com_installer.ini
Labels: Language Change, PR-staging, RTC

#27233 Fix syntax error in calendar minified file
  media/system/js/fields/calendar.min.js
Labels: PR-staging

#26754 Action Logs - hidden secret
  administrator/components/com_actionlogs/models/forms/filter_actionlogs.xml
  administrator/language/en-GB/en-GB.com_actionlogs.ini
Labels: Language Change, PR-staging, RTC

#19781 Avoid duplicate paths if path is not a directory
  libraries/src/Form/FormHelper.php
Labels: PR-staging, RTC

#27184 [4.0] Multilingual status module improvements
  administrator/components/com_languages/Helper/MultilangstatusHelper.php
  administrator/components/com_languages/View/Multilangstatus/HtmlView.php
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/language/en-GB/com_languages.ini
Labels: Language Change, PR-4.0-dev, RTC

#27247 Typo in doc block
  administrator/components/com_banners/models/tracks.php
Labels: PR-staging

#27249 [4.0] Remove unnecessary casts
  administrator/modules/mod_multilangstatus/Helper/MultilangstatusAdminHelper.php
  components/com_users/Model/RegistrationModel.php
  libraries/src/Table/User.php
Labels: PR-4.0-dev

#27250 [4.0] Reverse loading order of language files
  administrator/components/com_languages/Controller/InstalledController.php
  installation/src/Model/LanguagesModel.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
Labels: RTC

#27272 [4.0] Error when rebuilding update sites
  administrator/components/com_installer/Model/UpdatesitesModel.php
Labels: RTC

#27276 [4.0] Fix language override search
  administrator/components/com_languages/Model/StringsModel.php
Labels: RTC

#27265 [4.0] Fix overrides language strings
  administrator/components/com_languages/forms/filter_overrides.xml
  administrator/language/en-GB/com_languages.ini
Labels: Language Change, PR-4.0-dev, RTC

#27286 [4.0] quickicon user add link
  administrator/modules/mod_quickicon/Helper/QuickIconHelper.php
Labels: PR-4.0-dev, RTC

#27288 [4.0] users dashboard
  administrator/components/com_menus/presets/users.xml
Labels: PR-4.0-dev, RTC

#27290 [4.0] menu dashboard
  administrator/components/com_menus/presets/menus.xml
Labels: PR-4.0-dev, RTC

#27273 Fix warnings in layouts on PHP 7.4
  components/com_contact/views/featured/tmpl/default_items.php
  components/com_content/views/category/tmpl/default_articles.php
  templates/beez3/html/com_content/category/blog_links.php
  templates/beez3/html/com_content/category/default_articles.php
  templates/beez3/html/com_weblinks/category/default_items.php
Labels: PR-staging, RTC

#27289 [4.0] content dashboard
  administrator/components/com_menus/presets/content.xml
Labels: PR-4.0-dev, RTC

#27309 [4.0] plg_system_logrotation.ini, alpha sorting
  administrator/language/en-GB/plg_system_logrotation.ini
Labels: Language Change, PR-4.0-dev

#27310 [4.0] Drop description plg_system_logrotation
  administrator/language/en-GB/plg_system_logrotation.ini
  plugins/system/logrotation/logrotation.xml
Labels: Language Change, PR-4.0-dev

#27311 [4.0] Drop line plg_system_cache.sys.ini
  administrator/language/en-GB/plg_system_cache.sys.ini
Labels: Language Change, PR-4.0-dev

#27269 [4.0] Fix a warning "language has been changed"
  build/media_source/com_associations/js/associations-edit.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27313 update german installation files
  installation/language/de-AT/de-AT.ini
  installation/language/de-AT/de-AT.xml
  installation/language/de-CH/de-CH.ini
  installation/language/de-CH/de-CH.xml
  installation/language/de-DE/de-DE.ini
  installation/language/de-DE/de-DE.xml
  installation/language/de-LI/de-LI.ini
  installation/language/de-LI/de-LI.xml
  installation/language/de-LU/de-LU.ini
  installation/language/de-LU/de-LU.xml
Labels: Language Change, PR-staging

#27305 [4.0] Typo in the tinymce ini
  administrator/language/en-GB/plg_editors_tinymce.ini
Labels: Language Change, PR-4.0-dev, RTC

#27304 [4.0] Drop descriptions as for all other fields in the repetable custom field
  administrator/language/en-GB/plg_fields_repeatable.ini
  plugins/fields/repeatable/params/repeatable.xml
Labels: Language Change, PR-4.0-dev, RTC

#27299 Fixing String Search for Language Override Creator so it loads non-prefixed language files
  administrator/components/com_languages/models/strings.php
Labels: PR-3.10-dev

#21929 [3.10] Debug Tuneup
  plugins/system/debug/debug.php
Labels: PR-3.10-dev

#23479 Preparing 3.10 for 4.0 content versioning
  libraries/src/Versioning/VersionableControllerTrait.php
  libraries/src/Versioning/VersionableModelTrait.php
  libraries/src/Versioning/VersionableTableInterface.php
Labels: PR-3.10-dev

#27317 Revert "Preparing 3.10 for 4.0 content versioning"
  libraries/src/Versioning/VersionableControllerTrait.php
  libraries/src/Versioning/VersionableModelTrait.php
  libraries/src/Versioning/VersionableTableInterface.php
Labels: PR-3.10-dev

#27278 [4.0] Cassiopea: Correcting positions translation
  language/en-GB/tpl_cassiopeia.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#27238 [4.0] Frontend com_users remove deprecated strings
  language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#27321 [staging] Correcting metafile version
  administrator/language/en-GB/en-GB.xml
  administrator/language/en-GB/install.xml
  administrator/manifests/packages/pkg_en-GB.xml
  language/en-GB/en-GB.xml
  language/en-GB/install.xml
Labels: Language Change, PR-staging

#27264 [4.0]housekeeping
  .appveyor.yml
  administrator/components/com_finder/Indexer/Taxonomy.php
  administrator/components/com_installer/Model/UpdatesitesModel.php
  administrator/components/com_joomlaupdate/restore.php
  administrator/components/com_media/src/Model/ApiModel.php
  administrator/components/com_media/src/Model/FileModel.php
  administrator/components/com_menus/Controller/MenusController.php
  administrator/components/com_menus/Model/ItemModel.php
  administrator/components/com_templates/Model/TemplateModel.php
  administrator/components/com_users/Model/GroupsModel.php
  administrator/components/com_users/Model/UsersModel.php
  build/stubGenerator.php
  installation/INSTALL
  installation/src/Response/JsonResponse.php
  libraries/php-encryption/Crypto.php
  libraries/src/Application/CMSApplicationInterface.php
  libraries/src/Document/PreloadManager.php
  libraries/src/Document/PreloadManagerInterface.php
  libraries/src/Error/AbstractRenderer.php
  plugins/filesystem/local/Adapter/LocalAdapter.php
  plugins/installer/override/override.php
  plugins/system/languagefilter/languagefilter.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Content.php
  tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
  tests/Unit/Libraries/Cms/Feed/FeedParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
  tests/Unit/Libraries/Cms/Microdata/MicrodataTest.php
Labels: PR-4.0-dev, RTC, Unit/System Tests

#27298 Replace inline styles with classes (joomla#27297)
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_menus/tmpl/item/edit_container.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
  build/media_source/com_associations/js/associations-edit.es6.js
  build/media_source/com_banners/js/admin-banner-edit.es6.js
  build/media_source/com_fields/js/admin-fields-default-batch.es6.js
  build/media_source/com_installer/js/installer.es6.js
  build/media_source/com_joomlaupdate/js/default.es5.js
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/com_menus/js/admin-item-edit.es6.js
  build/media_source/com_menus/js/admin-item-edit_modules.es6.js
  build/media_source/com_menus/js/default-batch-body.es6.js
  build/media_source/com_modules/js/admin-module-edit_assignment.es6.js
  build/media_source/com_templates/js/admin-templates-default.es6.js
  build/media_source/com_users/js/admin-users-user.es6.js
  build/media_source/com_users/js/two-factor-switcher.es6.js
  build/media_source/layouts/js/joomla/html/batch/batch-language.es6.js
  build/media_source/mod_login/js/admin-login.es6.js
  build/media_source/plg_system_debug/js/debug.es6.js
  build/media_source/plg_system_stats/js/stats-message.es6.js
  build/media_source/system/js/core.es6.js
  build/media_source/system/js/fields/calendar.es5.js
  build/media_source/system/js/fields/joomla-field-color-slider.es6.js
  build/media_source/system/js/showon.es6.js
  build/media_source/vendor/jquery-ui/js/jquery.ui.core.es5.js
  installation/template/index.php
  installation/template/js/preinstall.js
  installation/template/js/setup.js
  installation/template/js/template.js
  installation/tmpl/remove/default.php
  layouts/joomla/edit/fieldset.php
  layouts/joomla/form/field/media.php
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable.php
  plugins/installer/packageinstaller/tmpl/default.php
  plugins/system/stats/layouts/message.php
  templates/cassiopeia/scss/blocks/_utilities.scss
Labels: NPM Resource Changed, PR-4.0-dev

#27301 [4.0] Cassiopeia - fixes fluid width option
  templates/cassiopeia/scss/blocks/_css-grid.scss
  templates/cassiopeia/scss/blocks/_layout.scss
Labels: PR-4.0-dev, RTC

#27343 Hiding .login-initial via class .hidden instead of display none
  administrator/modules/mod_login/tmpl/default.php
  administrator/templates/atum/scss/blocks/_login.scss
Labels: PR-4.0-dev

#27326 [4.0] mail templates empty style
  administrator/components/com_mails/tmpl/templates/default.php
Labels: PR-4.0-dev, RTC

#26882 Fixed "answer provided by user" issue on reCAPTCHA
  plugins/captcha/recaptcha/recaptcha.php
Labels: PR-staging

#27334 Fix subform with double field name
  media/system/js/subform-repeatable-uncompressed.js
  media/system/js/subform-repeatable.js
Labels: PR-staging, RTC

#27340 [4.0] Multilang associations: Display error when Content Language is trashed or deleted
  administrator/components/com_associations/Helper/AssociationsHelper.php
  administrator/components/com_categories/Service/HTML/AdministratorService.php
  administrator/components/com_contact/Service/HTML/AdministratorService.php
  administrator/components/com_content/Service/HTML/AdministratorService.php
  administrator/components/com_menus/Service/HTML/Menus.php
  administrator/components/com_newsfeeds/Service/HTML/AdministratorService.php
  administrator/language/en-GB/joomla.ini
  layouts/joomla/content/associations.php
Labels: Language Change, PR-4.0-dev, RTC

#27318 [3.10] Dont dublicate extensions with more than one update server
  administrator/components/com_joomlaupdate/controllers/update.php
  administrator/components/com_joomlaupdate/models/default.php
Labels: PR-3.10-dev, RTC, Release Blocker

#27225 [4.0][codemirror] Add space between attributes
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
Labels: PR-4.0-dev, RTC

#27341 [4.0] Impossible to Prepare multilingual site associations with Content Language when site language is not yet installed
  administrator/components/com_associations/Field/ItemlanguageField.php
  administrator/components/com_associations/Helper/AssociationsHelper.php
  administrator/components/com_categories/Controller/AjaxController.php
  administrator/components/com_categories/Field/Modal/CategoryField.php
  administrator/components/com_categories/Model/CategoryModel.php
  administrator/components/com_contact/Controller/AjaxController.php
  administrator/components/com_contact/Field/Modal/ContactField.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_content/Controller/AjaxController.php
  administrator/components/com_content/Field/Modal/ArticleField.php
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_menus/Controller/AjaxController.php
  administrator/components/com_menus/Field/Modal/MenuField.php
  administrator/components/com_menus/Model/ItemModel.php
  administrator/components/com_newsfeeds/Controller/AjaxController.php
  administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
  administrator/components/com_newsfeeds/Model/NewsfeedModel.php
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-4.0-dev, RTC

#27350 [3] com_tags. Microdata. Add position to itemListElement LIs
  components/com_tags/views/tag/tmpl/default_items.php
Labels: RTC

#27362 [4.0] Docblock: JMail to Mail
  libraries/src/Factory.php
Labels: PR-4.0-dev

#27364 [4.0] namespace JText
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_noupdate.php
  cli/finder_indexer.php
  plugins/content/joomla/joomla.php
Labels: RTC

#27366 [4.0] namespace JHtml
  administrator/components/com_mails/tmpl/template/edit.php
Labels: PR-4.0-dev, RTC

#27365 [4.0] namespace JCache
  plugins/system/logrotation/logrotation.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-4.0-dev, RTC

#27363 [4.0] namespace Jplugin
  administrator/components/com_mails/Model/TemplateModel.php
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
  plugins/system/logrotation/logrotation.php
Labels: RTC

#27376 [4.0] Dashboard colour
  administrator/templates/atum/scss/blocks/_quickicons.scss
Labels: PR-4.0-dev, RTC

#27379 [4.0] [Admin template] RTL: Correcting display of quicktask
  administrator/templates/atum/scss/blocks/_quickicons.scss
Labels: PR-4.0-dev

#27355 [4.0] Fix missing onchange events on switcher fields
  layouts/joomla/form/field/radio/switcher.php
Labels: PR-4.0-dev

#27377 [4.0] Menu arrows RTL support
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev

#27367 [4.0] TFA google authenticator
  administrator/components/com_users/tmpl/user/edit.php
Labels: PR-4.0-dev, RTC

#27381 [4.0] remove adddsubmenu
  administrator/components/com_fields/Helper/FieldsHelper.php
  administrator/components/com_menus/View/Items/HtmlView.php
  administrator/components/com_menus/View/Menus/HtmlView.php
  administrator/components/com_newsfeeds/View/Newsfeeds/HtmlView.php
  administrator/components/com_privacy/Controller/DisplayController.php
  administrator/components/com_redirect/Controller/DisplayController.php
  administrator/components/com_redirect/Helper/RedirectHelper.php
  administrator/components/com_workflow/Helper/WorkflowHelper.php
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
  administrator/components/com_workflow/View/Workflows/HtmlView.php
Labels: PR-4.0-dev

#27389 [4.0] Workflows comments
  administrator/components/com_workflow/Controller/WorkflowController.php
  administrator/components/com_workflow/Controller/WorkflowsController.php
  administrator/components/com_workflow/View/Transition/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
  administrator/components/com_workflow/View/Workflow/HtmlView.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
Labels: PR-4.0-dev

#27352 [4.0] toggled menu flyout
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/templates/atum/index.php
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev, RTC

#27392 [4.0] copy paste in docblock
  administrator/components/com_csp/services/provider.php
Labels: PR-4.0-dev
