Repository joomla/joomla-cms, pull requests merged in 2019-01, with the labels that each got.

#23413 [4.0] Eliminate jQuery from Modal footer
  administrator/components/com_banners/tmpl/tracks/default.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_messages/View/Messages/HtmlView.php
  administrator/components/com_redirect/tmpl/links/default.php
  build/media_src/system/js/core.es6.js
  layouts/joomla/toolbar/modal.php
Labels: Documentation Required, PR-4.0-dev

#23375 [4.0] Use DebugMonitor from joomla/database vendor
  libraries/src/Service/Provider/Database.php
  plugins/system/debug/DataCollector/QueryCollector.php
  plugins/system/debug/DebugMonitor.php
  plugins/system/debug/debug.php
Labels: PR-4.0-dev

#23412 [4.0] CSP vs. Content Security Policy
  administrator/language/en-GB/en-GB.com_csp.ini
Labels: Language Change, PR-4.0-dev, RTC

#23436 [4.0] Fix notice in newsfeed
  components/com_newsfeeds/tmpl/newsfeed/default.php
Labels: PR-4.0-dev, RTC

#23364 [4.0] Adding a node object interface
  libraries/src/Tree/ImmutableNodeInterface.php
  libraries/src/Tree/NodeInterface.php
Labels: PR-4.0-dev

#23289 [4.0] Admin modules: Cannot select or filter by position
  administrator/components/com_modules/Field/ModulesModuleField.php
  administrator/components/com_modules/Field/ModulesPositionField.php
  administrator/components/com_modules/Field/ModulesPositioneditField.php
  administrator/components/com_modules/forms/moduleadmin.xml
Labels: PR-4.0-dev, RTC

#23431 [4.0] Add a View Interface
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Factory/LegacyFactory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Factory/MVCFactoryInterface.php
  libraries/src/MVC/View/AbstractView.php
  libraries/src/MVC/View/CategoriesView.php
  libraries/src/MVC/View/CategoryFeedView.php
  libraries/src/MVC/View/CategoryView.php
  libraries/src/MVC/View/FormView.php
  libraries/src/MVC/View/HtmlView.php
  libraries/src/MVC/View/ListView.php
  libraries/src/MVC/View/ViewInterface.php
Labels: PR-4.0-dev

#23445 Remove unused postSaveHook methods
  administrator/components/com_newsfeeds/Controller/NewsfeedController.php
  administrator/components/com_newsfeeds/Controller/NewsfeedsController.php
Labels: PR-4.0-dev

#23350 [plugin][user][joomla] namespaced
  plugins/user/joomla/joomla.php
Labels: PR-staging, RTC

#23349 [plugin][user][profile] namespaced
  plugins/user/profile/profile.php
Labels: RTC

#23341 [com_actionlogs] namespaced
  administrator/components/com_actionlogs/actionlogs.php
  administrator/components/com_actionlogs/controllers/actionlogs.php
  administrator/components/com_actionlogs/helpers/actionlogs.php
  administrator/components/com_actionlogs/helpers/actionlogsphp55.php
  administrator/components/com_actionlogs/layouts/logstable.php
  administrator/components/com_actionlogs/libraries/actionlogplugin.php
  administrator/components/com_actionlogs/models/actionlog.php
  administrator/components/com_actionlogs/models/actionlogs.php
  administrator/components/com_actionlogs/models/fields/extension.php
  administrator/components/com_actionlogs/models/fields/logcreator.php
  administrator/components/com_actionlogs/models/fields/logsdaterange.php
  administrator/components/com_actionlogs/models/fields/logtype.php
  administrator/components/com_actionlogs/views/actionlogs/tmpl/default.php
  administrator/components/com_actionlogs/views/actionlogs/view.html.php
Labels: PR-staging, RTC

#23335 [plugin][system][actionlog] use namespaced class
  plugins/system/actionlogs/actionlogs.php
Labels: PR-staging, RTC

#23334 [plugin][actionlog][joomla] use namespaced User/Factory
  plugins/actionlog/joomla/joomla.php
  plugins/actionlog/joomla/joomla.xml
Labels: PR-staging, RTC

#23417 [4.0] no jquery workflow button
  build/media_src/com_content/js/admin-articles-workflow-buttons.es6.js
  layouts/joomla/button/transition-button.php
Labels: PR-4.0-dev, RTC

#23416 [4.0] No jQuery
  administrator/components/com_fields/Field/SectionField.php
  administrator/components/com_finder/Service/HTML/Filter.php
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_plugins/tmpl/plugin/edit.php
  administrator/components/com_templates/tmpl/style/edit_assignment.php
Labels: PR-4.0-dev, RTC

#23406 [4.0] Reimplementing client filter in Modules Manager
  administrator/components/com_modules/forms/filter_modules.xml
  administrator/components/com_modules/forms/filter_modulesadmin.xml
Labels: PR-4.0-dev, RTC

#23443 [4.0] Hide "All" option in stage edit for conditions
  administrator/components/com_workflow/forms/stage.xml
  libraries/src/Form/Field/WorkflowconditionField.php
Labels: PR-4.0-dev, RTC

#23394 [4.0] Remove un-used line of code
  libraries/src/Component/ComponentHelper.php
Labels: PR-4.0-dev, RTC

#23384 [4.0] Fix user notes state change
  administrator/components/com_users/Model/NotesModel.php
  administrator/components/com_users/Table/NoteTable.php
Labels: PR-4.0-dev, RTC

#23391 [4.0] Group toolbar buttons in com_plugins
  administrator/components/com_plugins/View/Plugins/HtmlView.php
Labels: PR-4.0-dev, RTC

#23402 [4.0] Fixing lots of issues in Tags component and grouping toolbar buttons
  administrator/components/com_tags/Model/TagsModel.php
  administrator/components/com_tags/View/Tag/HtmlView.php
  administrator/components/com_tags/View/Tags/HtmlView.php
  administrator/language/en-GB/en-GB.com_tags.ini
  libraries/src/Form/Field/TagField.php
Labels: Language Change, PR-4.0-dev, RTC

#23339 [4.0] Fix wrong status of custom field enable switcher in com_contact
  administrator/components/com_contact/config.xml
Labels: PR-4.0-dev, RTC

#23374 [4.0] Group action buttons in users
  administrator/components/com_users/View/Users/HtmlView.php
Labels: PR-4.0-dev

#23370 [4.0] Group action buttons for com_fields
  administrator/components/com_fields/View/Fields/HtmlView.php
Labels: PR-4.0-dev, RTC

#23371 [4.0] Group action buttons for com_fields group
  administrator/components/com_fields/View/Groups/HtmlView.php
Labels: PR-4.0-dev, RTC

#23467 [4.0] Dispatcher access check
  administrator/components/com_categories/Dispatcher/Dispatcher.php
  administrator/components/com_workflow/Dispatcher/Dispatcher.php
Labels: PR-4.0-dev

#23368 [4.0] Group action buttons for banner clients
  administrator/components/com_banners/View/Clients/HtmlView.php
Labels: PR-4.0-dev

#23378 [4.0] Group action buttons for com_modules
  administrator/components/com_admin/script.php
  administrator/components/com_modules/View/Modules/HtmlView.php
  administrator/components/com_modules/layouts/toolbar/newmodule.php
Labels: PR-4.0-dev

#23471 [4.0] JFactory error in PLuginsField.php
  libraries/src/Form/Field/PluginsField.php
Labels: PR-4.0-dev

#23475 [4.0] correcting/adding JFactory to Factory (pass 1)
  administrator/components/com_categories/Helper/CategoriesHelper.php
  administrator/components/com_content/Helper/ContentHelper.php
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_finder/Controller/FilterController.php
  administrator/components/com_finder/Field/ContenttypesField.php
  build/helpTOC.php
  components/com_content/tmpl/category/blog_item.php
  installation/src/Model/DatabaseModel.php
  installation/src/Service/Provider/Application.php
  libraries/joomla/model/database.php
  plugins/content/joomla/joomla.php
  plugins/system/redirect/redirect.php
Labels: PR-4.0-dev

#23472 [4.0] Modules Manager: normalize client filter code
  administrator/components/com_modules/forms/filter_modules.xml
Labels: PR-4.0-dev

#23459 [4.0] Fix featured view and add grouped buttons
  administrator/components/com_content/View/Featured/HtmlView.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_content/tmpl/featured/default_stage_body.php
  administrator/components/com_content/tmpl/featured/default_stage_footer.php
Labels: PR-4.0-dev

#23380 [4.0] Group action toolbar buttons usernotes
  administrator/components/com_users/View/Notes/HtmlView.php
Labels: PR-4.0-dev

#23460 [4.0] Add back button to the transitions and stages view button toolbars
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Transitions/HtmlView.php
Labels: PR-4.0-dev

#20640 [4.0] Introduce model interfaces
  administrator/components/com_contenthistory/Model/CompareModel.php
  administrator/components/com_contenthistory/Model/PreviewModel.php
  libraries/src/Form/FormFactoryAwareTrait.php
  libraries/src/MVC/Factory/LegacyFactory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Factory/MVCFactoryAwareTrait.php
  libraries/src/MVC/Factory/MVCFactoryInterface.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/BaseModel.php
  libraries/src/MVC/Model/DatabaseAwareTrait.php
  libraries/src/MVC/Model/DatabaseModelInterface.php
  libraries/src/MVC/Model/FormBehaviorTrait.php
  libraries/src/MVC/Model/FormModel.php
  libraries/src/MVC/Model/FormModelInterface.php
  libraries/src/MVC/Model/ItemModel.php
  libraries/src/MVC/Model/ItemModelInterface.php
  libraries/src/MVC/Model/LeagcyModelLoaderTrait.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/MVC/Model/ListModelInterface.php
  libraries/src/MVC/Model/ModelInterface.php
  libraries/src/MVC/Model/StateBehaviorTrait.php
  libraries/src/MVC/Model/StatefulModelInterface.php
Labels: Documentation Required, PR-4.0-dev

#23463 [4.0] WebAsset: split WebAssetRegistry to Registry and Manager
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Document/Document.php
  libraries/src/Event/WebAsset/AbstractEvent.php
  libraries/src/Event/WebAsset/WebAssetBeforeAttachEvent.php
  libraries/src/Event/WebAsset/WebAssetStateChangedEvent.php
  libraries/src/Factory.php
  libraries/src/Service/Provider/WebAssetRegistry.php
  libraries/src/WebAsset/Exception/UnknownAssetException.php
  libraries/src/WebAsset/Exception/UnsatisfiedDependencyException.php
  libraries/src/WebAsset/Exception/WebAssetExceptionInterface.php
  libraries/src/WebAsset/WebAssetItem.php
  libraries/src/WebAsset/WebAssetItemInterface.php
  libraries/src/WebAsset/WebAssetManager.php
  libraries/src/WebAsset/WebAssetManagerInterface.php
  libraries/src/WebAsset/WebAssetRegistry.php
  libraries/src/WebAsset/WebAssetRegistryInterface.php
Labels: PR-4.0-dev

#23484 [4.0] Missing files in template manifests
  administrator/templates/atum/templateDetails.xml
  templates/cassiopeia/templateDetails.xml
Labels: PR-4.0-dev

#23492 Updated installation language files for german dialects
  installation/language/de-AT/de-AT.ini
  installation/language/de-AT/de-AT.xml
  installation/language/de-CH/de-CH.ini
  installation/language/de-CH/de-CH.xml
  installation/language/de-DE/de-DE.ini
  installation/language/de-DE/de-DE.xml
  installation/language/de-LI/de-LI.ini
  installation/language/de-LI/de-LI.xml
  installation/language/de-LU/de-LU.ini
  installation/language/de-LU/de-LU.xml
Labels: Language Change, PR-staging

#23502 [4.0] Fix notice in mod_syndicate.xml
  modules/mod_syndicate/mod_syndicate.xml
Labels: PR-4.0-dev

#23498 [4.0] Not only set the redirect but actually return
  administrator/components/com_config/Controller/ApplicationController.php
Labels: PR-4.0-dev

#23506 Undefined class \Joomla\CMS\Filesystem\AKFactory
  administrator/components/com_joomlaupdate/restore_finalisation.php
Labels: PR-4.0-dev

#22888 Privacy dashboard: direct access to the privacy consent plugin
  administrator/components/com_privacy/helpers/privacy.php
  administrator/components/com_privacy/views/dashboard/tmpl/default.php
  administrator/components/com_privacy/views/dashboard/view.html.php
  administrator/language/en-GB/en-GB.com_privacy.ini
Labels: Language Change, PR-staging, RTC

#23487 Update draggable.js to post 1-based array
  build/media/system/js/draggable.js
Labels: PR-4.0-dev

#23509 [40.] Finder Index: Check access to plugins
  administrator/components/com_finder/View/Index/HtmlView.php
  administrator/language/en-GB/en-GB.com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#23521 Reverse order of template params for green/red. Fixes #23519
  administrator/templates/atum/templateDetails.xml
Labels: RTC

#23525 [4.0] Fix Legacy Model loading. Fixes #23517
  libraries/src/MVC/Controller/BaseController.php
Labels: PR-4.0-dev, RTC

#23531 [4.0][com_tags] Fix "Too few arguments to function PlgContentJoomla::onContentBeforeSave". Add $data to event_before_save
  administrator/components/com_tags/Model/TagModel.php
Labels: PR-4.0-dev

#23535 [4.0] [com_menus] Fix "Too few arguments to function PlgContentJoomla::onContentBeforeSave"
  administrator/components/com_menus/Model/MenuModel.php
Labels: PR-4.0-dev

#23470 [4.0] Add json to source_formats of template editor
  administrator/components/com_templates/config.xml
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev

#23501 [4.0] Remove show_associations field of association is not enabled
  administrator/components/com_content/Model/ArticleModel.php
Labels: PR-4.0-dev

#23481 [com_joomlaupdate] restore vs php 7.3
  administrator/components/com_joomlaupdate/restore.php
Labels: RTC

#23552 Fixed small typos in months of Joomla core extension
  administrator/components/com_associations/associations.xml
  administrator/modules/mod_quickicon/mod_quickicon.xml
  administrator/modules/mod_status/mod_status.xml
  administrator/modules/mod_submenu/mod_submenu.xml
  administrator/modules/mod_title/mod_title.xml
  administrator/modules/mod_toolbar/mod_toolbar.xml
  tests/unit/stubs/database/jos_extensions.csv
Labels: RTC

#23155 [4.0] Move mod menu script to es6
  build/media/mod_menu/js/admin-menu.js
  build/media_src/mod_menu/js/admin-menu.es6.js
Labels: PR-4.0-dev

#23558 CodeStyle - use caps
  components/com_contact/views/featured/tmpl/default.xml
  components/com_content/views/archive/tmpl/default.xml
  components/com_content/views/article/tmpl/default.xml
  components/com_privacy/views/confirm/tmpl/default.xml
  components/com_privacy/views/remind/tmpl/default.xml
  components/com_privacy/views/request/tmpl/default.xml
  components/com_tags/views/tag/tmpl/default.xml
  components/com_tags/views/tag/tmpl/list.xml
  components/com_tags/views/tags/tmpl/default.xml
  components/com_users/views/login/tmpl/default.xml
  components/com_users/views/profile/tmpl/default.xml
  components/com_users/views/profile/tmpl/edit.xml
  components/com_users/views/reset/tmpl/default.xml
Labels: RTC

#23561 CSS Class for tag link
  administrator/language/en-GB/en-GB.com_tags.ini
Labels: Language Change, PR-staging

#23564 [4.0] Fix missing use statement
  administrator/components/com_workflow/View/Transitions/HtmlView.php
Labels: RTC

#23579 Csp doc block change.
  administrator/components/com_csp/Controller/ReportsController.php
Labels: PR-4.0-dev

#23556 [3.9.2][com_menus] template style select not shown
  administrator/components/com_menus/models/forms/item.xml
Labels: RTC

#23560 Smart Search (finder) module
  modules/mod_finder/tmpl/default.php
Labels: RTC

#23478 Deprecating loadFieldType & loadRuleType
  libraries/src/Form/Form.php
Labels: RTC

#23454 [com_content][featured] - fix category filter
  administrator/components/com_content/models/featured.php
Labels: RTC

#23210 Fix sql queries in the update file for mssql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-02.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-03.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-05.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-19.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-20.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-24.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-27.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-02.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-12.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-13.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-14.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-06-17.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-07-09.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-07-10.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-07-11.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-08-12.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-08-29.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-10-15.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-10-20.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-10-21.sql
  libraries/src/Schema/ChangeItem/SqlsrvChangeItem.php
Labels: RTC

#23495 [4.0] Smart Search searching performance improvement
  components/com_finder/Model/SearchModel.php
Labels: PR-4.0-dev

#23594 [4.0][com_templates] Copying Atum administrator template fails.
  administrator/templates/atum/templateDetails.xml
Labels: PR-4.0-dev, RTC

#19353 Add support for non prefixed language files
  administrator/components/com_languages/controllers/installed.php
  installation/model/languages.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
Labels: PR-3.10-dev, PR-staging

#23590 [staging] Debug language correction
  libraries/src/Language/Language.php
Labels: RTC

#23676 [4.0] Typo in js comments
  build/media/system/js/fields/tag.js
  build/media_src/system/js/searchtools.es6.js
Labels: RTC

#23695 en-GB grammar
  administrator/language/en-GB/en-GB.com_installer.ini
  components/com_users/controllers/registration.php
  libraries/src/Editor/Editor.php
  libraries/src/Form/Field/EditorField.php
  libraries/src/Installer/InstallerAdapter.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  libraries/src/Updater/Update.php
  media/com_associations/js/sidebyside-uncompressed.js
  plugins/content/confirmconsent/fields/consentbox.php
  plugins/system/languagefilter/languagefilter.php
Labels: Language Change, PR-staging

#23681 [4.0] Mod SampleData xml desccription
  administrator/language/en-GB/en-GB.mod_sampledata.ini
  administrator/language/en-GB/en-GB.mod_sampledata.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#23707 Remove myself from most CODEOWNERS paths
  .github/CODEOWNERS
Labels: PR-4.0-dev

#23692 [3.9][a11y] Improve accessiblity in mod_search
  modules/mod_search/tmpl/default.php
  tests/unit/suites/libraries/joomla/document/renderer/JDocumentRendererHtmlModulesTest.php
Labels: PR-staging, RTC

#20658 [4.0] Smart Search categories plugin needs to use right extension element
  plugins/finder/categories/categories.php
Labels: PR-4.0-dev, RTC

#21037 [4.0] com_finder: Filtering common & numeric words and language fix
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-10.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-10.sql
  administrator/components/com_finder/config.xml
  administrator/components/com_finder/helpers/indexer/driver/mysql.php
  administrator/components/com_finder/helpers/indexer/helper.php
  administrator/components/com_finder/helpers/indexer/indexer.php
  administrator/components/com_finder/helpers/indexer/query.php
  administrator/language/en-GB/en-GB.com_finder.ini
  components/com_finder/Model/SearchModel.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: Language Change, PR-4.0-dev
