Repository joomla/joomla-cms, pull requests merged in 2020-06, with the labels that each got.

#29349 Update uk-UA installation language
  installation/language/uk-UA/uk-UA.ini
  installation/language/uk-UA/uk-UA.xml
Labels: Language Change, PR-staging, RTC

#29356 [4.0] Support null values in Extensions table
  libraries/src/Table/Extension.php
Labels: PR-4.0-dev, RTC

#29339 [4.0] com_users front end forms
  components/com_users/layouts/joomla/form/renderfield.php
  components/com_users/tmpl/profile/edit.php
  language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#29358 [4.0] Readonly switcher, not disabled
  layouts/joomla/form/field/radio/switcher.php
Labels: PR-4.0-dev, RTC

#29373 [4.0] docblock update
  libraries/src/Layout/BaseLayout.php
  libraries/src/MVC/View/HtmlView.php
Labels: RTC

#29367 [4.0] Change button string
  components/com_users/tmpl/profile/edit.php
Labels: PR-4.0-dev, RTC

#29359 [4.0] [com_templates] Move form manipulation to model
  administrator/components/com_templates/forms/style_administrator.xml
  administrator/components/com_templates/forms/style_site.xml
  administrator/components/com_templates/src/Model/StyleModel.php
  administrator/components/com_templates/src/View/Style/HtmlView.php
Labels: PR-4.0-dev, RTC

#29351 [4.0] TinyMCE not saving
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  layouts/joomla/tinymce/togglebutton.php
  plugins/editors/tinymce/tinymce.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29368 [4.0] Add markup to move buttons to next line
  administrator/language/en-GB/plg_system_updatenotification.ini
Labels: Language Change, PR-4.0-dev

#29375 [4.0] Fix the extra padding under the modal buttons
  administrator/templates/atum/scss/blocks/_modals.scss
Labels: PR-4.0-dev, RTC

#29357 [4.0] Add table rename to database schema check
  administrator/language/en-GB/com_installer.ini
  libraries/src/Schema/ChangeItem/MysqlChangeItem.php
  libraries/src/Schema/ChangeItem/PostgresqlChangeItem.php
Labels: PR-4.0-dev, RTC

#29387 [4.0] Remove btn-sm
  layouts/joomla/toolbar/versions.php
Labels: RTC

#29395 [4.0] btn-sm toolbar buttons
  administrator/components/com_associations/src/View/Association/HtmlView.php
  administrator/components/com_media/layouts/toolbar/create-folder.php
  administrator/components/com_media/layouts/toolbar/delete.php
  administrator/components/com_media/layouts/toolbar/upload.php
  administrator/components/com_redirect/layouts/toolbar/batch.php
  layouts/joomla/toolbar/modal.php
Labels: RTC

#29417 [4.0] Mail Templates descriptions
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/plg_system_updatenotification.ini
  administrator/language/en-GB/plg_user_joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#29397 [4.0] LDAP Authentication fix
  plugins/authentication/ldap/ldap.php
Labels: PR-4.0-dev

#29390 [4.0] Removing obsolete code from com_banners table classes
  administrator/components/com_banners/src/Table/BannerTable.php
  administrator/components/com_banners/src/Table/ClientTable.php
Labels: PR-4.0-dev, RTC

#29389 [4.0] com Finder table caption
  administrator/components/com_finder/tmpl/statistics/default.php
  administrator/templates/atum/scss/pages/_com_finder.scss
  administrator/templates/atum/scss/template.scss
Labels: PR-4.0-dev, RTC

#29391 [4.0] Removing obsolete code from com_contact table class
  administrator/components/com_contact/src/Table/ContactTable.php
Labels: PR-4.0-dev

#29365 [4.0] TFA forms not shown in frontend
  administrator/components/com_users/tmpl/user/edit.php
  build/media_source/com_users/js/admin-users-user.es6.js
  build/media_source/com_users/js/two-factor-switcher.es6.js
  components/com_users/tmpl/profile/edit.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#29404 Trigger "change" event after updating user field input value
  build/media_source/system/js/fields/joomla-field-user.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#29444 [4.0] Indicate current menu item in sidebar
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev, RTC

#29431 [4.0] Fix useless red class when unpublishing Content Language
  administrator/language/en-GB/com_languages.ini
Labels: Language Change, PR-4.0-dev, RTC

#29447 [4.0] Load jQuery for Treeselectmenu
  administrator/components/com_menus/tmpl/item/edit_container.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  build/media_source/legacy/joomla.asset.json
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29448 Rename transition field label to workflow
  libraries/src/MVC/Model/WorkflowBehaviorTrait.php
Labels: PR-4.0-dev, RTC

#29443 [4.0] Module assignment page not updating
  administrator/components/com_menus/tmpl/item/edit_modules.php
Labels: PR-4.0-dev, RTC

#29462 Fix shownon to also work on radio with btn-group btn-group-yesno class
  build/media_source/system/js/showon.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29269 [4.0] State dropdown fixes
  templates/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
Labels: Information Required, PR-4.0-dev, RTC

#29465 [4.0] PluginHelper classname invalide - fixed
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
Labels: RTC

#29430 Check if the versions object has the property
  administrator/components/com_contenthistory/models/compare.php
  administrator/components/com_contenthistory/models/preview.php
Labels: PR-staging, RTC

#29466 [4.0] Fix filtering articles by multiple categories
  administrator/components/com_content/src/Model/ArticlesModel.php
Labels: PR-4.0-dev, RTC

#29460 [4.0] Fix bulk importing redirects
  administrator/components/com_redirect/src/Model/LinksModel.php
Labels: PR-4.0-dev, RTC

#29458 [4.0] Correct tooltip on contact edit icon on PDO
  administrator/components/com_contact/src/Service/HTML/Icon.php
Labels: PR-4.0-dev, RTC

#29463 [4.0] Filter the module types in the new module page
  administrator/components/com_modules/tmpl/select/default.php
  build/media_source/com_modules/js/admin-module-search.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#29457 [4.0] Set checked_out value to null if supported
  libraries/src/Table/Table.php
Labels: PR-4.0-dev, RTC

#29446 [4.0][com_templates] Display buttons when applicable
  administrator/components/com_templates/src/View/Template/HtmlView.php
Labels: PR-4.0-dev, RTC

#29449 [4.0] Installer enable the bootup error trace when debug enabled
  installation/includes/framework.php
Labels: RTC

#29370 [4.0] Simplify Switcher layout
  layouts/joomla/form/field/radio/switcher.php
Labels: PR-4.0-dev, RTC

#29270 [4.0] Prevent global timezone changing after use of JDate class
  libraries/src/Date/Date.php
Labels: Documentation Required, PR-4.0-dev, RTC

#29440 [4.0] Add unit tests for AccessiblemediaField
  tests/Unit/Libraries/Cms/Form/Field/AccessiblemediaFieldTest.php
Labels: PR-4.0-dev, Unit/System Tests

#29475 [4.0] Fix media manager slide animation in RTL
  administrator/components/com_media/resources/styles/components/_animations.scss
Labels: RTC

#29479 [4.0] Revert condition to published filter
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_tags/tmpl/tags/default.php
Labels: RTC

#29478 [4.0] Add missing workflow plugins to list of core extensions in ExtensionsHelper
  libraries/src/Extension/ExtensionHelper.php
Labels: PR-4.0-dev, RTC

#29480 [4.0] Filtering by core extensions returns non-core extensions
  administrator/components/com_installer/src/Model/ManageModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  libraries/src/Extension/ExtensionHelper.php
Labels: PR-4.0-dev, RTC

#29453 [4.0] Fix RTL tree select styling
  administrator/templates/atum/scss/blocks/_treeselect.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29380 [4.0] Allow varchar in PostgreSQL update SQL scripts
  libraries/src/Schema/ChangeItem/PostgresqlChangeItem.php
Labels: PR-4.0-dev, RTC

#29500 [4.0] Remove string that was only used in the GMail plugin
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: RTC

#29482 [4.0] Reduce table padding
  administrator/templates/atum/scss/vendor/bootstrap/_table.scss
Labels: RTC

#29515 [4.0] Fix typos
  plugins/workflow/featuring/featuring.php
  plugins/workflow/publishing/publishing.php
Labels: PR-4.0-dev, RTC

#29481 [4.0] RTL: fix treeselect chevron direction
  build/media_source/legacy/js/treeselectmenu.es5.js
Labels: PR-4.0-dev, RTC

#29483 [4.0] RTL: fix media info alignment
  administrator/components/com_media/resources/styles/components/_media-infobar.scss
Labels: NPM Resource Changed, PR-4.0-dev

#29439 [4.0] Used tagged framework betas, remove controller framework package
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev, RTC

#29520 [4.0] Notice when "Link to Author's Contact Page" option is enabled
  plugins/content/contact/contact.php
Labels: RTC

#29554 [4.0] Workflow string
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/language/en-GB/com_workflow.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#29570 [4.0] Add accessibility to stats table
  administrator/language/en-GB/plg_system_stats.ini
  plugins/system/stats/layouts/stats.php
Labels: Language Change, PR-4.0-dev, RTC

#29572 [4.0] Mass mail subject prefix styling
  administrator/components/com_users/tmpl/mail/default.php
Labels: PR-4.0-dev, RTC

#29555 [4.0] Duplicate queries when user has no contacts
  plugins/content/contact/contact.php
Labels: PR-4.0-dev, RTC

#29362 [4.0] Refactor and harden database checks at installation
  installation/src/Helper/DatabaseHelper.php
  installation/src/Model/DatabaseModel.php
  installation/src/Model/SetupModel.php
Labels: PR-4.0-dev, Release Blocker

#29428 [4.0] Fixing several issues in com_finder/Smart Search
  administrator/components/com_finder/src/Controller/IndexerController.php
  administrator/components/com_finder/src/Indexer/Adapter.php
  administrator/components/com_finder/src/Indexer/Driver/Mysql.php
  administrator/components/com_finder/src/Indexer/Driver/Postgresql.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Model/SearchesModel.php
  components/com_finder/src/Helper/FinderHelper.php
  components/com_finder/src/Model/SearchModel.php
Labels: PR-4.0-dev, RTC

#29203 Change header_class type from text to textarea
  components/com_config/forms/modules_advanced.xml
Labels: PR-4.0-dev, RTC

#29578 [4.0] Correct link preload header
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#29393 [4.0] Removing obsolete code from com_messages table
  administrator/components/com_messages/src/Table/MessageTable.php
Labels: PR-4.0-dev, RTC

#29579 [4.0] Remove margin between accordion slides
  components/com_config/tmpl/modules/default.php
  libraries/src/HTML/Helpers/Bootstrap.php
Labels: PR-4.0-dev, RTC

#29574 [4.0] Private message display
  administrator/components/com_messages/tmpl/message/default.php
Labels: PR-4.0-dev, RTC

#29568 [4.0] Allow optional port numbers in remote database security check of installation
  installation/src/Helper/DatabaseHelper.php
Labels: PR-4.0-dev, RTC

#29469 [4.0] Improve user token plugin display in the profile page
  plugins/user/token/token.php
Labels: PR-4.0-dev, RTC

#29486 [4.0] Fix filtering banners by keywords
  components/com_banners/src/Model/BannersModel.php
Labels: PR-4.0-dev

#29539 [com_users] Clear user state on cancel
  administrator/components/com_users/controllers/mail.php
Labels: PR-staging, RTC

#29593 [4.0] fix typo remember pluign
  plugins/system/remember/remember.php
Labels: PR-4.0-dev, RTC

#29587 [4.0] Fix unlimited checkbox markup
  administrator/components/com_banners/src/Field/ImptotalField.php
Labels: RTC

#29594 [4.0] Modal for articles fix form
  administrator/components/com_content/tmpl/articles/modal.php
Labels: PR-4.0-dev

#29263 [4.0] [Workflow] Implement the whole permission system for the workflow
  administrator/components/com_content/access.xml
  administrator/components/com_workflow/access.xml
  administrator/components/com_workflow/forms/stage.xml
  administrator/components/com_workflow/forms/transition.xml
  administrator/components/com_workflow/forms/workflow.xml
  administrator/components/com_workflow/src/Controller/DisplayController.php
  administrator/components/com_workflow/src/Controller/StageController.php
  administrator/components/com_workflow/src/Controller/StagesController.php
  administrator/components/com_workflow/src/Controller/TransitionController.php
  administrator/components/com_workflow/src/Controller/WorkflowController.php
  administrator/components/com_workflow/src/Controller/WorkflowsController.php
  administrator/components/com_workflow/src/Dispatcher/Dispatcher.php
  administrator/components/com_workflow/src/Model/StageModel.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
  administrator/components/com_workflow/src/Table/StageTable.php
  administrator/components/com_workflow/src/Table/TransitionTable.php
  administrator/components/com_workflow/src/Table/WorkflowTable.php
  administrator/components/com_workflow/src/View/Stage/HtmlView.php
  administrator/components/com_workflow/src/View/Workflow/HtmlView.php
  administrator/components/com_workflow/tmpl/stage/edit.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transition/edit.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflow/edit.php
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_workflow.ini
  administrator/language/en-GB/joomla.ini
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/MVC/Model/WorkflowBehaviorTrait.php
  libraries/src/Workflow/Workflow.php
  plugins/content/joomla/joomla.php
Labels: Language Change, PR-4.0-dev, RTC

#29493 [4.0] Featured button: Swap popover title and body
  libraries/src/Button/FeaturedButton.php
Labels: PR-4.0-dev

#29584 Preparing 3.10 for 4.0 content versioning
  libraries/src/Versioning/VersionableControllerTrait.php
  libraries/src/Versioning/VersionableModelTrait.php
  libraries/src/Versioning/VersionableTableInterface.php
Labels: PR-3.10-dev

#29605 [4.0] Alpha sort site lang strings part 1
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/com_ajax.ini
  language/en-GB/com_config.ini
  language/en-GB/com_contact.ini
  language/en-GB/com_finder.ini
  language/en-GB/com_newsfeeds.ini
  language/en-GB/com_users.ini
  language/en-GB/com_wrapper.ini
  language/en-GB/files_joomla.sys.ini
  language/en-GB/finder_cli.ini
  language/en-GB/joomla.ini
  language/en-GB/lib_joomla.ini
  language/en-GB/mod_articles_categories.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#29607 [4.0] Alpha sort site lang strings part 2
  language/en-GB/mod_articles_category.ini
  language/en-GB/mod_articles_latest.ini
  language/en-GB/mod_articles_latest.sys.ini
  language/en-GB/mod_articles_news.ini
  language/en-GB/mod_articles_news.sys.ini
  language/en-GB/mod_finder.ini
  language/en-GB/mod_languages.ini
  language/en-GB/mod_whosonline.ini
  language/en-GB/mod_wrapper.sys.ini
  language/en-GB/tpl_cassiopeia.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#29616 [4.0] Alpha sort admin lang strings [components]
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_admin.ini
  administrator/language/en-GB/com_admin.sys.ini
  administrator/language/en-GB/com_ajax.ini
  administrator/language/en-GB/com_ajax.sys.ini
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_banners.sys.ini
  administrator/language/en-GB/com_cache.ini
  administrator/language/en-GB/com_checkin.ini
  administrator/language/en-GB/com_checkin.sys.ini
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/com_config.sys.ini
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_contact.sys.ini
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_contenthistory.ini
  administrator/language/en-GB/com_cpanel.ini
  administrator/language/en-GB/com_csp.ini
  administrator/language/en-GB/com_csp.sys.ini
  administrator/language/en-GB/com_fields.ini
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/com_installer.ini
  administrator/language/en-GB/com_installer.sys.ini
  administrator/language/en-GB/com_languages.ini
  administrator/language/en-GB/com_mails.ini
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/com_menus.sys.ini
  administrator/language/en-GB/com_messages.sys.ini
  administrator/language/en-GB/com_modules.ini
  administrator/language/en-GB/com_newsfeeds.ini
  administrator/language/en-GB/com_newsfeeds.sys.ini
  administrator/language/en-GB/com_plugins.ini
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/com_redirect.ini
  administrator/language/en-GB/com_tags.ini
  administrator/language/en-GB/com_templates.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/com_users.sys.ini
  administrator/language/en-GB/com_workflow.ini
  administrator/language/en-GB/com_workflow.sys.ini
  administrator/language/en-GB/com_wrapper.sys.ini
Labels: Language Change, PR-4.0-dev

#29623 [4.0] install string - pre-installation check
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#29625 [4.0] Add folder forms to the manifest file.
  plugins/workflow/featuring/featuring.xml
  plugins/workflow/notification/notification.xml
  plugins/workflow/publishing/publishing.xml
Labels: PR-4.0-dev, RTC

#29627 [4.0][com_tags] Add language string
  administrator/components/com_tags/forms/tag.xml
  administrator/language/en-GB/com_tags.ini
Labels: RTC

#29622 [4.0] Updates without description not working
  libraries/src/Table/Update.php
Labels: PR-4.0-dev, RTC

#29619 [4.0] Use update description from update XML
  administrator/components/com_installer/src/Model/UpdateModel.php
Labels: PR-4.0-dev, RTC

#29604 Fix undefined index for user token plugin
  plugins/user/token/token.php
Labels: PR-4.0-dev, RTC

#29601 [4.0] Check whether CSP is enabled and enabled by the current client
  administrator/components/com_csp/config.xml
  administrator/language/en-GB/com_csp.ini
  plugins/system/httpheaders/httpheaders.php
Labels: PR-4.0-dev, RTC

#29599 [4.0] Normalize main menu in error and main atum template views
  administrator/templates/atum/error_full.php
Labels: PR-4.0-dev, RTC

#29603 Clear backend cache when purging the updates
  administrator/components/com_installer/models/update.php
Labels: PR-staging, RTC

#29577 Custom fields missing when editing articles using Beez3
  templates/beez3/html/com_content/form/edit.php
Labels: PR-staging, RTC

#29445 [3.x] explain symbols
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/language/en-GB/en-GB.com_users.ini
  language/en-GB/en-GB.com_users.ini
Labels: PR-staging, RTC

#29237 Fix feed image
  administrator/modules/mod_feed/tmpl/default.php
  components/com_newsfeeds/views/newsfeed/tmpl/default.php
  libraries/src/Feed/Feed.php
  modules/mod_feed/tmpl/default.php
Labels: PR-staging, RTC

#29416 Fix array offset notice on PHP 7.4 when installing extensions
  administrator/components/com_installer/models/install.php
Labels: PR-staging, RTC

#29596 [4.0] No user information if the user hast not the right to manage users
  administrator/modules/mod_stats_admin/src/Helper/StatsAdminHelper.php
Labels: PR-4.0-dev, RTC

#29612 [3.x] Fix language strings for robots options
  administrator/language/en-GB/en-GB.ini
Labels: Language Change, PR-staging

#29517 [4.0] Upgrade to filter version 2.0 beta 2
  administrator/components/com_languages/src/Helper/LanguagesHelper.php
  composer.lock
  libraries/src/Component/ComponentHelper.php
  libraries/src/Filter/InputFilter.php
  libraries/src/Form/Filter/SafehtmlFilter.php
  plugins/editors/tinymce/tinymce.php
Labels: Composer Dependency Changed, PR-4.0-dev

#29637 [4.0] Alpha sort admin modules lang strings
  administrator/language/en-GB/mod_feed.ini
  administrator/language/en-GB/mod_latest.ini
  administrator/language/en-GB/mod_logged.sys.ini
  administrator/language/en-GB/mod_loginsupport.sys.ini
  administrator/language/en-GB/mod_menu.sys.ini
  administrator/language/en-GB/mod_messages.sys.ini
  administrator/language/en-GB/mod_multilangstatus.sys.ini
  administrator/language/en-GB/mod_popular.ini
  administrator/language/en-GB/mod_popular.sys.ini
  administrator/language/en-GB/mod_post_installation_messages.sys.ini
  administrator/language/en-GB/mod_privacy_dashboard.sys.ini
  administrator/language/en-GB/mod_quickicon.ini
  administrator/language/en-GB/mod_quickicon.sys.ini
  administrator/language/en-GB/mod_stats_admin.sys.ini
  administrator/language/en-GB/mod_title.sys.ini
  administrator/language/en-GB/mod_toolbar.sys.ini
Labels: Language Change, PR-4.0-dev

#29632 [4.0] Alpha sort admin and api joomla.ini strings
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev

#29639 [4.0] Alpha sort admin plugins lang strings
  administrator/language/en-GB/plg_captcha_recaptcha.ini
  administrator/language/en-GB/plg_captcha_recaptcha.sys.ini
  administrator/language/en-GB/plg_captcha_recaptcha_invisible.ini
  administrator/language/en-GB/plg_content_contact.ini
  administrator/language/en-GB/plg_content_emailcloak.ini
  administrator/language/en-GB/plg_content_emailcloak.sys.ini
  administrator/language/en-GB/plg_content_finder.ini
  administrator/language/en-GB/plg_content_pagebreak.ini
  administrator/language/en-GB/plg_content_pagebreak.sys.ini
  administrator/language/en-GB/plg_content_pagenavigation.sys.ini
  administrator/language/en-GB/plg_editors-xtd_article.sys.ini
  administrator/language/en-GB/plg_editors-xtd_image.sys.ini
  administrator/language/en-GB/plg_editors-xtd_readmore.ini
  administrator/language/en-GB/plg_editors-xtd_readmore.sys.ini
  administrator/language/en-GB/plg_editors_tinymce.ini
  administrator/language/en-GB/plg_extension_finder.sys.ini
  administrator/language/en-GB/plg_extension_joomla.ini
  administrator/language/en-GB/plg_fields_calendar.ini
  administrator/language/en-GB/plg_fields_checkboxes.ini
  administrator/language/en-GB/plg_fields_list.ini
  administrator/language/en-GB/plg_fields_radio.ini
  administrator/language/en-GB/plg_finder_contacts.ini
  administrator/language/en-GB/plg_finder_content.ini
  administrator/language/en-GB/plg_finder_newsfeeds.ini
  administrator/language/en-GB/plg_finder_tags.ini
  administrator/language/en-GB/plg_installer_override.ini
  administrator/language/en-GB/plg_installer_webinstaller.sys.ini
  administrator/language/en-GB/plg_media-action_resize.ini
  administrator/language/en-GB/plg_media-action_rotate.ini
  administrator/language/en-GB/plg_quickicon_privacycheck.ini
  administrator/language/en-GB/plg_sampledata_blog.ini
  administrator/language/en-GB/plg_system_actionlogs.ini
  administrator/language/en-GB/plg_system_debug.ini
  administrator/language/en-GB/plg_system_httpheaders.ini
  administrator/language/en-GB/plg_system_languagecode.sys.ini
  administrator/language/en-GB/plg_system_languagefilter.ini
  administrator/language/en-GB/plg_system_logout.ini
  administrator/language/en-GB/plg_system_logout.sys.ini
  administrator/language/en-GB/plg_system_privacyconsent.ini
  administrator/language/en-GB/plg_system_sef.ini
  administrator/language/en-GB/plg_system_updatenotification.ini
  administrator/language/en-GB/plg_system_webauthn.ini
  administrator/language/en-GB/plg_twofactorauth_totp.ini
  administrator/language/en-GB/plg_twofactorauth_totp.sys.ini
  administrator/language/en-GB/plg_twofactorauth_yubikey.ini
  administrator/language/en-GB/plg_user_token.ini
  administrator/language/en-GB/plg_workflow_notification.ini
  administrator/language/en-GB/plg_workflow_notification.sys.ini
  administrator/language/en-GB/tpl_atum.ini
Labels: Language Change, PR-4.0-dev

#29631 [4.0] Fix Installation language strings
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
  installation/language/en-US/langmetadata.xml
Labels: Language Change, PR-4.0-dev

#29635 Use JHtml underscore method
  administrator/components/com_modules/views/module/tmpl/edit.php
  administrator/components/com_plugins/views/plugin/tmpl/edit.php
  administrator/components/com_users/views/users/tmpl/default.php
  administrator/templates/hathor/html/com_languages/installed/default.php
  layouts/joomla/sidebars/submenu.php
  templates/beez3/html/com_contact/contact/default.php
  templates/beez3/html/com_contact/contact/default_links.php
  templates/beez3/html/com_contact/contact/default_user_custom_fields.php
  templates/protostar/component.php
Labels: PR-staging, RTC

#29629 [4.0] [plg_privacy_contact] Parameterized queries
  plugins/privacy/contact/contact.php
Labels: PR-4.0-dev, RTC

#29638 [4.0.beta1]Fix non existing FA back icon
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev

#29643 [4.0] Fix workflow transition search
  administrator/components/com_workflow/src/Model/TransitionsModel.php
Labels: PR-4.0-dev, RTC

#29633 [4.0] [com_workflow] Parameterized queries
  administrator/components/com_workflow/src/Controller/WorkflowController.php
  administrator/components/com_workflow/src/Model/StagesModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowsModel.php
  administrator/components/com_workflow/src/Table/StageTable.php
  administrator/components/com_workflow/src/Table/WorkflowTable.php
Labels: PR-4.0-dev, RTC

#29602 [4.0] Issue warnings when unsafe-inline or unsafe-eval are used in auto mode
  administrator/components/com_csp/src/Helper/ReporterHelper.php
  administrator/components/com_csp/src/View/Reports/HtmlView.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/language/en-GB/com_csp.ini
Labels: Documentation Required, Language Change, PR-4.0-dev, RTC

#29665 [4.0] installer override plugin: Fix wrong plural string format
  administrator/language/en-GB/plg_installer_override.ini
  plugins/installer/override/override.php
Labels: Language Change, PR-4.0-dev, RTC

#29669 Make ToolbarHelper::back rtl compliant
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev

#29668 [4.0] Normalizing authentication joomla plugin strings
  administrator/language/en-GB/plg_authentication_joomla.ini
  administrator/language/en-GB/plg_authentication_joomla.sys.ini
  plugins/authentication/joomla/joomla.php
  plugins/authentication/joomla/joomla.xml
Labels: Language Change, PR-4.0-dev, RTC

#29667 [4.0] Correct class casing
  administrator/components/com_admin/src/View/Sysinfo/HtmlView.php
  administrator/components/com_admin/src/View/Sysinfo/JsonView.php
  administrator/components/com_admin/src/View/Sysinfo/TextView.php
  administrator/components/com_associations/src/Dispatcher/Dispatcher.php
  administrator/components/com_contenthistory/src/Dispatcher/Dispatcher.php
  administrator/components/com_cpanel/src/Dispatcher/Dispatcher.php
  administrator/components/com_fields/src/Dispatcher/Dispatcher.php
  administrator/components/com_users/src/Controller/DisplayController.php
  administrator/components/com_users/src/Controller/GroupsController.php
  administrator/components/com_users/src/Controller/LevelController.php
  administrator/components/com_users/src/View/Debuggroup/HtmlView.php
  administrator/components/com_users/src/View/Debuguser/HtmlView.php
  components/com_config/src/Dispatcher/Dispatcher.php
  components/com_contenthistory/src/Dispatcher/Dispatcher.php
Labels: PR-4.0-dev

#29649 Fix webservice plugin to show super user group
  plugins/user/token/token.xml
Labels: PR-4.0-dev, RTC

#29675 [4.0] Fix Atum Safari not displaying svg background when using choices
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: RTC

#29666 [4.0] Normalizing authentication cookie plugin lang strings
  administrator/language/en-GB/plg_authentication_cookie.ini
  administrator/language/en-GB/plg_authentication_cookie.sys.ini
  plugins/authentication/cookie/cookie.php
  plugins/authentication/cookie/cookie.xml
Labels: Language Change, PR-4.0-dev, RTC

#29624 [4.0] Safari fix
  installation/template/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev

#29685 [4.0] stdClass casing
  administrator/components/com_templates/src/Model/TemplateModel.php
  libraries/src/Extension/ExtensionHelper.php
  plugins/system/actionlogs/actionlogs.php
Labels: PR-4.0-dev, RTC

#29682 [4.0] tag field cursor
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29688 [4.0] Correct class name
  administrator/components/com_login/src/Model/LoginModel.php
Labels: PR-4.0-dev, RTC

#29681 [4.0] Media Manager modal toolbar
  administrator/components/com_media/tmpl/media/default.php
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29686 [4.0] Remove reference to non-existing class
  plugins/system/webauthn/webauthn.php
Labels: PR-4.0-dev, RTC

#29692 [4.0] Fix history version preview
  administrator/components/com_contenthistory/src/Helper/ContenthistoryHelper.php
Labels: PR-4.0-dev, RTC

#29693 [4.0] Fix php notice when no version_id specified
  administrator/components/com_contenthistory/src/Model/PreviewModel.php
Labels: PR-4.0-dev, RTC

#29630 [4.0][api][com_content] render the image field
  administrator/components/com_content/src/Model/ArticlesModel.php
  api/components/com_content/src/Helper/ContentHelper.php
  api/components/com_content/src/View/Articles/JsonapiView.php
Labels: PR-4.0-dev, RTC

#29664 Banner impressions exceeded by 1
  components/com_banners/models/banners.php
Labels: PR-staging, RTC

#29705 [4.0] Correct class casing
  administrator/components/com_users/src/Model/LevelsModel.php
Labels: PR-4.0-dev, RTC

#29704 [4.0] Fix WebAuthn white icons
  layouts/plugins/system/webauthn/manage.php
Labels: PR-4.0-dev

#29720 [4.0] comment typo
  administrator/components/com_categories/src/View/Category/HtmlView.php
Labels: PR-4.0-dev

#29663 [4.0] Fix redirect after deleting content history versions
  administrator/components/com_contenthistory/src/Controller/HistoryController.php
Labels: PR-4.0-dev, RTC

#29714 [4.0] Use base64 filter for return URL
  administrator/components/com_mails/tmpl/template/edit.php
  administrator/components/com_modules/tmpl/module/edit.php
Labels: RTC

#29726 [4.0] namespace path
  administrator/language/en-GB/plg_extension_namespacemap.ini
  administrator/language/en-GB/plg_extension_namespacemap.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#29715 [4.0] Modal button height
  administrator/templates/atum/scss/blocks/_modals.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29730 [4.0] mod sampledata help link
  administrator/modules/mod_sampledata/mod_sampledata.xml
Labels: PR-4.0-dev, RTC

#29718 [4.0] add module permissions
  administrator/components/com_cpanel/tmpl/cpanel/default.php
Labels: PR-4.0-dev, RTC

#29716 [4.0] com_messages icon
  administrator/components/com_messages/src/View/Message/HtmlView.php
Labels: PR-4.0-dev, RTC

#29717 [4.0] Template preview link
  administrator/components/com_templates/tmpl/styles/default.php
Labels: PR-4.0-dev, RTC

#29713 Use base64 filter for return URL
  administrator/components/com_content/views/article/tmpl/edit.php
  administrator/components/com_finder/views/filter/tmpl/edit.php
  administrator/components/com_installer/controllers/install.php
  administrator/templates/hathor/html/com_content/article/edit.php
Labels: PR-staging, RTC

#29691 Showon doesn't work with new items in a subform field
  build/media_source/system/js/showon.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29684 Remove reference to non-existing class
  libraries/src/Form/Form.php
Labels: PR-staging, RTC

#29672 Fix workflow notification plugin
  administrator/language/en-GB/plg_workflow_notification.ini
  plugins/workflow/notification/notification.php
Labels: Language Change, PR-4.0-dev, RTC, Updates Requested

#29636 Unclosed tab set in contact view using Beez3 template
  templates/beez3/html/com_contact/contact/default.php
Labels: PR-staging, RTC

#29737 [4.0] statistcis help
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#29732 Suggest text change of PR Template to make it more clear
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR-staging, RTC

#29753 [4.0] language column alignment
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_tags/tmpl/tags/default.php
Labels: PR-4.0-dev, RTC

#29707 [4.0] WebAuthn: Cannot take an administrative action after adding an authenticator
  build/media_source/plg_system_webauthn/js/management.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29751 [4.0] remove redundant code & general cleanup
  plugins/system/debug/debug.php
  plugins/system/debug/src/DataCollector/InfoCollector.php
  plugins/system/debug/src/DataCollector/LanguageErrorsCollector.php
  plugins/system/debug/src/DataCollector/LanguageFilesCollector.php
  plugins/system/debug/src/DataCollector/LanguageStringsCollector.php
  plugins/system/debug/src/DataCollector/ProfileCollector.php
  plugins/system/debug/src/DataCollector/QueryCollector.php
  plugins/system/debug/src/Storage/FileStorage.php
Labels: PR-4.0-dev

#29757 [4.0] Workflow help button
  administrator/components/com_workflow/src/View/Stages/HtmlView.php
  administrator/components/com_workflow/src/View/Transitions/HtmlView.php
  administrator/components/com_workflow/src/View/Workflows/HtmlView.php
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#29755 [4.0] Remove placeholder translation not used
  components/com_finder/tmpl/search/default.php
Labels: PR-4.0-dev, RTC

#29752 [4.0] Add missing vars from extract into the docblock
  layouts/joomla/form/field/text.php
Labels: PR-4.0-dev, RTC

#29769 [4.0] Use name when sending mass mail
  administrator/components/com_users/src/Model/MailModel.php
Labels: PR-4.0-dev, RTC

#29771 [4.0] Fixed error message when closing add module modal.
  build/media_source/com_cpanel/js/admin-add_module.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29777 [4.0] Fix filters width
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
Labels: RTC

#29772 [4.0][com_installer] Fix width of Name column
  administrator/components/com_installer/tmpl/update/default.php
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#29784 [4.0] Add missing language strings
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: RTC

#29761 [4.0] Fix select missing icon for removing the selected value
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29801 [4.0] Fix column alignment
  administrator/components/com_installer/tmpl/update/default.php
Labels: RTC
