Repository joomla/joomla-cms, pull requests merged in 2020-12, with the labels that each got.

#30144 Fix possible warning in the System-Debug's DataFormatter.php file
  plugins/system/debug/src/DataFormatter.php
Labels: PR-4.0-dev

#31557 Remove robot strings from article form menuitem
  components/com_content/models/forms/article.xml
Labels: PR-staging

#31553 [4] View user profile. aria-hidden="true" for icon-user
  components/com_users/tmpl/profile/default.php
Labels: PR-4.0-dev

#31555 [4.0-dev] Cassiopeia set font-size-root to 1em
  templates/cassiopeia/scss/tools/variables/_variables.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31559 Two typos detected by a Translator
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: PR-4.0-dev, RTC

#31561 Fix session's moving from Joomla 3 to Joomla 4
  .appveyor.yml
  administrator/language/en-GB/com_languages.ini
Labels: PR-4.0-dev, Release Blocker

#31563 Fix session error
  libraries/src/Session/Session.php
Labels: PR-4.0-dev

#31573 [4.0] Update com_languages.ini
  administrator/language/en-GB/com_languages.ini
Labels: Language Change, PR-4.0-dev

#31574 [4.0] fix play icon
  build/media_source/system/scss/_icomoon.scss
Labels: PR-4.0-dev, RTC

#31537 [3][com_postinstall] warning on php 8
  libraries/fof/model/behavior.php
  libraries/fof/model/behavior/filters.php
Labels: PHP 8, PR-staging, RTC

#31575 Add Joomla 3 session namespace to has function
  libraries/src/Session/Session.php
Labels: PR-4.0-dev, RTC

#31581 [4.0][api] core delete
  administrator/components/com_content/src/Model/ArticleModel.php
  tests/Codeception/api/com_content/ContentCest.php
Labels: PR-4.0-dev, Unit/System Tests

#31577 [4.0] Alt Text
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/plg_editors_tinymce.ini
  language/en-GB/joomla.ini
Labels: PR-4.0-dev, RTC

#31357 [4.0] Newsfeeds image alt
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/language/en-GB/com_newsfeeds.ini
  components/com_newsfeeds/tmpl/newsfeed/default.php
Labels: PR-4.0-dev, RTC

#31515 Use stored PW for Test Email feature
  administrator/components/com_config/model/application.php
Labels: PR-staging, RTC

#31361 [4.0] Typo/Spelling BASIS
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  components/com_users/tmpl/login/default.xml
Labels: Language Change, PR-4.0-dev, RTC

#30897 [4.0] Fix icon to display adjacent to field
  modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31606 [4.0] Media manager icons
  administrator/components/com_media/resources/styles/components/_media-browser.scss
Labels: RTC

#31607 [4.0] Media Manager strings
  administrator/language/en-GB/com_media.ini
  language/en-GB/com_media.ini
Labels: RTC

#31578 [4.0] Add empty alt checkbox for tinyMCE dnd
  administrator/language/en-GB/plg_editors_tinymce.ini
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es6.js
  plugins/editors/tinymce/tinymce.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#31576 [4.0] Intro image link [a11y]
  layouts/joomla/content/intro_image.php
Labels: PR-4.0-dev, RTC

#31608 [4.0] Admin module checkout id [a11y]
  administrator/modules/mod_latest/tmpl/default.php
  administrator/modules/mod_popular/tmpl/default.php
Labels: PR-4.0-dev, RTC

#30921 Fix strtotime() warnings on PHP 8
  components/com_content/views/article/tmpl/default.php
  components/com_content/views/category/tmpl/blog_item.php
  components/com_content/views/category/tmpl/default_articles.php
  components/com_content/views/featured/tmpl/default_item.php
  layouts/joomla/content/blog_style_default_item_title.php
  layouts/joomla/content/icons/edit.php
  templates/beez3/html/com_content/category/blog_item.php
  templates/beez3/html/com_content/featured/default_item.php
Labels: PHP 8, PR-staging, RTC

#31597 [4.0] Article Info fields
  templates/cassiopeia/scss/blocks/_modifiers.scss
Labels: PR-4.0-dev, RTC

#31539 [4.0] Frontend Edit Article [a11y]
  components/com_content/forms/article.xml
  components/com_content/tmpl/form/edit.php
  language/en-GB/com_content.ini
Labels: Language Change, PR-4.0-dev, RTC

#31617 [4.0] Action Logs Search
  administrator/components/com_actionlogs/forms/filter_actionlogs.xml
  administrator/language/en-GB/com_actionlogs.ini
Labels: Language Change, PR-4.0-dev

#31616 [4.0] Action Logs Icon
  administrator/components/com_actionlogs/src/View/Actionlogs/HtmlView.php
Labels: PR-4.0-dev, RTC

#31618 [4.0] Successfully remove
  administrator/language/en-GB/com_contenthistory.ini
  administrator/language/en-GB/com_templates.ini
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#31601 [4.0] Regression and b/c fix for session handling
  libraries/src/Session/Session.php
Labels: PR-4.0-dev, Release Blocker

#31500 [4.0] Fix password hash comparison
  libraries/src/User/UserHelper.php
Labels: PR-4.0-dev, RTC, Release Blocker

#31518 Fix broken versioning in workflow items
  administrator/components/com_contenthistory/tmpl/compare/compare.php
  libraries/src/Versioning/Versioning.php
  plugins/workflow/featuring/featuring.php
  plugins/workflow/publishing/publishing.php
Labels: PR-4.0-dev, Release Blocker

#31620 [staging] Displaying error when updating an extension/package
  administrator/components/com_installer/models/update.php
  administrator/language/en-GB/en-GB.com_installer.ini
Labels: Language Change, PR-staging, RTC

#31626 [4.0] COM_MENUS_ITEM_ROOT
  administrator/components/com_menus/forms/item.xml
  administrator/components/com_menus/forms/itemadmin.xml
  administrator/language/en-GB/com_menus.ini
Labels: Language Change, PR-4.0-dev, RTC

#31625 [4.0] com_tags unused strings
  administrator/language/en-GB/com_tags.ini
Labels: PR-4.0-dev, RTC

#31632 [4.0] Upstream Security issue
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#31624 [4.0] Fix banner module
  components/com_banners/src/Helper/BannerHelper.php
  modules/mod_banners/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31600 Revert #31537 and fix warnings on php 8 in fof
  libraries/fof/model/behavior.php
  libraries/fof/model/behavior/filters.php
  libraries/fof/model/model.php
Labels: PHP 8, PR-staging, RTC

#31638 [4.0] template strings review
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/language/en-GB/com_templates.ini
Labels: Language Change, PR-4.0-dev, RTC

#31639 [4.0]mod_related strings
  language/en-GB/mod_related_items.ini
Labels: RTC

#31645 Fix query with nulldate
  components/com_content/src/Helper/QueryHelper.php
Labels: PR-4.0-dev, RTC

#31643 [4.0] com_csp enabled not published
  administrator/components/com_csp/src/View/Reports/HtmlView.php
  administrator/language/en-GB/com_csp.ini
Labels: Language Change, PR-4.0-dev

#31628 [3.9][com_admin] warning in Edit Account
  administrator/components/com_admin/models/profile.php
Labels: PHP 8, PR-staging, RTC

#31604 [4.0] Blog sampledata text
  administrator/language/en-GB/plg_sampledata_blog.ini
  administrator/language/en-GB/plg_sampledata_blog.sys.ini
Labels: J4 Issue, Language Change, PR-4.0-dev, RTC

#31328 [4.0] https updates and fix @link
  administrator/components/com_redirect/src/Field/RedirectField.php
  administrator/manifests/libraries/phpass.xml
  libraries/src/Document/Document.php
  libraries/src/Form/Field/CheckboxField.php
  libraries/src/Form/Field/ColorField.php
  libraries/src/Form/Field/EmailField.php
  libraries/src/Form/Field/FileField.php
  libraries/src/Form/Field/HiddenField.php
  libraries/src/Form/Field/MeterField.php
  libraries/src/Form/Field/NoteField.php
  libraries/src/Form/Field/NumberField.php
  libraries/src/Form/Field/PasswordField.php
  libraries/src/Form/Field/RadioField.php
  libraries/src/Form/Field/RangeField.php
  libraries/src/Form/Field/TelephoneField.php
  libraries/src/Form/Field/TextField.php
  libraries/src/Form/Field/TextareaField.php
  libraries/src/Form/Field/UrlField.php
  libraries/src/Form/Filter/UrlFilter.php
  libraries/src/Form/Form.php
  libraries/src/Form/Rule/UrlRule.php
  templates/cassiopeia/offline.php
Labels: PR-4.0-dev, RTC

#31544 [4.0] webservices xml
  plugins/webservices/banners/banners.xml
  plugins/webservices/config/config.xml
  plugins/webservices/contact/contact.xml
  plugins/webservices/content/content.xml
  plugins/webservices/installer/installer.xml
  plugins/webservices/languages/languages.xml
  plugins/webservices/menus/menus.xml
  plugins/webservices/messages/messages.xml
  plugins/webservices/modules/modules.xml
  plugins/webservices/newsfeeds/newsfeeds.xml
  plugins/webservices/plugins/plugins.xml
  plugins/webservices/privacy/privacy.xml
  plugins/webservices/redirect/redirect.xml
  plugins/webservices/tags/tags.xml
  plugins/webservices/templates/templates.xml
  plugins/webservices/users/users.xml
Labels: PR-4.0-dev, RTC

#31448 [4.0] Delete unused contact lang string
  administrator/language/en-GB/com_contact.ini
Labels: Language Change, PR-4.0-dev, RTC

#31652 [4.0] com_privacy capabilities
  administrator/components/com_privacy/tmpl/capabilities/default.php
  administrator/templates/atum/scss/pages/_com_privacy.scss
Labels: NPM Resource Changed, PR-4.0-dev

#31646 [4.0] Cassiopeia component.php
  templates/cassiopeia/component.php
Labels: PR-4.0-dev

#31651 [4.0] Password reset time
  administrator/language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev

#30570 [3.x-4.0] enable install in a dedicated schema on PostgreSQL databases
  libraries/joomla/database/driver/pgsql.php
  libraries/joomla/database/driver/postgresql.php
Labels: PR-staging, RTC

#31465 [4.0] Refactor JFTP error messages strings
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Client/FtpClient.php
Labels: Language Change, PR-4.0-dev, RTC

#31554 [J!3.9] Update of joomla-framework/image #31552
  libraries/vendor/joomla/image/src/Image.php
  libraries/vendor/joomla/image/src/ImageFilter.php
Labels: Composer Dependency Changed, PR-staging

#31654 [4.0] Update sites
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev

#31662 Revert "[J!3.9] Update of joomla-framework/image #31552"
  libraries/vendor/joomla/image/src/Image.php
  libraries/vendor/joomla/image/src/ImageFilter.php
Labels: Composer Dependency Changed, PR-staging

#31656 [4.0] Accredited Language Translations - simplify
  administrator/language/en-GB/com_admin.ini
Labels: Language Change, PR-4.0-dev, RTC

#31666 Use Factory::, not JFactory
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
Labels: PR-4.0-dev, RTC

#31659 [4.0][com_content] remove comment from c&p mistake
  administrator/components/com_content/src/Model/ArticleModel.php
Labels: PR-4.0-dev, RTC

#31669 [4.0] JFactory
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_fields/src/Model/GroupModel.php
  administrator/components/com_menus/src/Model/MenuModel.php
  components/com_contact/src/Model/ContactModel.php
  libraries/src/Adapter/Adapter.php
  libraries/src/Adapter/AdapterInstance.php
  plugins/actionlog/joomla/joomla.php
  plugins/user/joomla/joomla.php
Labels: PR-4.0-dev

#31668 [4.0] en-GB style guide issues
  administrator/language/en-GB/com_modules.ini
  administrator/language/en-GB/com_modules.sys.ini
  administrator/language/en-GB/plg_system_sessiongc.ini
  administrator/language/en-GB/plg_system_webauthn.ini
  administrator/language/en-GB/plg_user_token.ini
  language/en-GB/mod_whosonline.ini
  plugins/sampledata/testing/language/en-GB/en-GB.plg_sampledata_testing.ini
Labels: Language Change, PR-4.0-dev

#31636 [4.x] Fix open redirects in cancel actions
  administrator/components/com_modules/src/Controller/ModuleController.php
  administrator/components/com_users/src/Controller/UserController.php
Labels: PR-4.0-dev, RTC, Release Blocker

#31670 [4.0] Capitalize IS NULL
  components/com_content/src/Helper/QueryHelper.php
Labels: PR-4.0-dev

#31663 Update joomla/image dependency
  composer.lock
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/image/src/Filter/Backgroundfill.php
  libraries/vendor/joomla/image/src/Filter/Brightness.php
  libraries/vendor/joomla/image/src/Filter/Contrast.php
  libraries/vendor/joomla/image/src/Filter/Smooth.php
  libraries/vendor/joomla/image/src/Image.php
  libraries/vendor/joomla/image/src/ImageFilter.php
  libraries/vendor/leafo/lessphp/lessify
  libraries/vendor/leafo/lessphp/plessc
Labels: Composer Dependency Changed, PR-staging

#31379 [4.0][webservices] Allow customizing CORS headers and add support for OPTIONS method
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/application/default_webservices.php
  administrator/language/en-GB/com_config.ini
  libraries/src/Application/ApiApplication.php
  libraries/src/Router/ApiRouter.php
Labels: Language Change, PR-4.0-dev

#31680 [4.0] little fix for #31379
  libraries/src/Router/ApiRouter.php
Labels: PR-4.0-dev

#31676 Fix missing composer files from archive update
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
Labels: Composer Dependency Changed, PR-staging

#31672 [3] Allow to set password empty passwords and add database password back
  administrator/components/com_config/model/application.php
  administrator/components/com_config/model/form/application.xml
  administrator/language/en-GB/en-GB.com_config.ini
  layouts/joomla/form/field/password.php
  libraries/joomla/form/fields/password.php
Labels: Language Change, PR-staging

#31681 [4.0] Remove duplicate line
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_plugins/tmpl/plugin/edit.php
Labels: PR-4.0-dev

#31683 [4.0] Provide empty string as default for empty protected fields when saving configuration.php
  administrator/components/com_config/src/Model/ApplicationModel.php
Labels: PR-4.0-dev, RTC, Release Blocker

#31686 [4.0] use Joomla\CMS\Factory
  layouts/joomla/content/blog_style_default_item_title.php
Labels: PR-4.0-dev, RTC

#31685 [4.0] use Joomla\CMS\HTML\HTMLHelper;
  administrator/components/com_tags/tmpl/tags/default.php
Labels: PR-4.0-dev, RTC

#31684 [4.0] use Joomla\CMS\Filter\InputFilter;
  administrator/components/com_contenthistory/tmpl/history/modal.php
Labels: PR-4.0-dev, RTC

#31667 [4.0] Cassiopeia: Add height auto to images to maintain aspect ratio
  templates/cassiopeia/scss/blocks/_global.scss
Labels: J4 Frontend Template, NPM Resource Changed, PR-4.0-dev, RTC

#31660 [4.0] Refactor JInstaller strings
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/language/en-GB/lib_joomla.ini
  installation/language/en-GB/joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/Installer.php
Labels: Language Change, PR-4.0-dev

#31489 [4.0] plugin installation order
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#31694 [4.0] Menu home not default
  administrator/language/en-GB/com_menus.ini
Labels: PR-4.0-dev, RTC

#31689 [4.0] Correcting articles blog badge date
  layouts/joomla/content/blog_style_default_item_title.php
Labels: PR-4.0-dev

#31370 [4.0] Remove IDs from URLs
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#30399 [4.0] Remove unneeded strings from robots parameter
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#31397 [4.0] Specify title and icon of dashboards in the component manifest
  administrator/components/com_content/content.xml
  administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php
  administrator/components/com_menus/menus.xml
  administrator/components/com_privacy/privacy.xml
  administrator/components/com_users/users.xml
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_cpanel.ini
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#31688 Add a hidden menuItem Search to blog sample data
  administrator/language/en-GB/plg_sampledata_blog.ini
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev, RTC

#31481 [4.0] Prefill tags with most used items
  libraries/src/Form/Field/TagField.php
Labels: PR-4.0-dev, RTC, Release Blocker

#31425 [4.0] Media field Image select Features parity
  administrator/language/en-GB/joomla.ini
  build/media_source/system/css/fields/joomla-image-select.css
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
  language/en-GB/joomla.ini
  plugins/editors-xtd/image/image.php
  plugins/editors/tinymce/tinymce.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, Release Blocker

#31322 FeaturedButton fix
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/language/en-GB/com_content.ini
  libraries/src/Button/FeaturedButton.php
Labels: Language Change, PR-4.0-dev

#31701 Improve error message for broken JSON
  libraries/src/WebAsset/WebAssetRegistry.php
Labels: PR-4.0-dev, RTC

#31221 [4.0] Allow scss compilation for any template
  .gitignore
  administrator/templates/system/css/error.css
  administrator/templates/system/css/system.css
  administrator/templates/system/scss/error.scss
  administrator/templates/system/scss/system.scss
  build/build-modules-js/compilecss.es6.js
  package-lock.json
  templates/system/css/editor.css
  templates/system/css/error.css
  templates/system/css/general.css
  templates/system/css/offline.css
  templates/system/scss/editor.scss
  templates/system/scss/error.scss
  templates/system/scss/error_rtl.scss
  templates/system/scss/general.scss
  templates/system/scss/offline.scss
  templates/system/scss/offline_rtl.scss
Labels: NPM Resource Changed, PR-4.0-dev

#31703 [4.0] Offsets separated by white space(s) are deprecated, use a comma (,) instead.
  libraries/src/HTML/Helpers/Bootstrap.php
Labels: PR-4.0-dev

#31655 [4.0] Language Install button [a11y]
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#31640 [4.0] newsflash string
  language/en-GB/mod_articles_news.ini
Labels: Language Change, PR-4.0-dev, RTC

#31710 [4.0] Add sanity checks on the asset file
  administrator/components/com_templates/src/Controller/TemplateController.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/language/en-GB/com_templates.ini
Labels: Language Change, PR-4.0-dev

#31712 [4.0] Fix merge error
  package-lock.json
Labels: NPM Resource Changed, PR-4.0-dev

#31742 [4.0] Blocked Users
  administrator/language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#31749 com_templates removal of PHP warnings
  administrator/components/com_templates/views/template/tmpl/default.php
Labels: PR-staging, RTC

#31739 [4.0] fields xtd-editor button
  plugins/editors-xtd/fields/fields.php
Labels: PR-4.0-dev, RTC

#31745 [4.0] Loading plg_system_actionlogs lang even when disabled
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
Labels: PR-4.0-dev, RTC

#31733 [4.0] Update Checks quickicon module
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-12-20.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-12-20.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#31360 [4.0] Login/Logout page image description [a11y]
  administrator/language/en-GB/com_users.ini
  components/com_users/tmpl/login/default.xml
  components/com_users/tmpl/login/default_login.php
  components/com_users/tmpl/login/default_logout.php
  language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev

#31732 [4.0] Composer update
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#31744 [4.0] Fix Notice in edit account
  administrator/components/com_admin/tmpl/profile/edit.php
Labels: PR-4.0-dev, RTC

#31755 [4.0] Render com_admin tabs with the global JLayout
  administrator/components/com_admin/tmpl/profile/edit.php
Labels: PR-4.0-dev

#31724 [3.9.24rc] Do not send the smtppass on test if field is disabled
  media/system/js/sendtestmail-uncompressed.js
  media/system/js/sendtestmail.js
Labels: PR-staging, RTC

#31760 [4.0] Do not delete associated tags while reordering
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-4.0-dev, Release Blocker

#31750 [4.0] Fix for subfields values not outputting 0 values
  plugins/fields/subfields/subfields.php
Labels: PR-4.0-dev

#31761 [4.0] contact xtd-editor button
  plugins/editors-xtd/contact/contact.php
Labels: PR-4.0-dev

#31769 [4.0] menu xtd-editor icon
  plugins/editors-xtd/menu/menu.php
Labels: PR-4.0-dev, RTC

#31771 [4.0] Cassiopeia module header class
  templates/cassiopeia/html/layouts/chromes/card.php
Labels: PR-4.0-dev, RTC

#31775 [4.0] Password focus
  build/media_source/system/js/fields/passwordview.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31699 [4.0] Fix mail template not found error
  administrator/components/com_mails/src/Controller/DisplayController.php
  administrator/language/en-GB/com_mails.ini
Labels: Language Change, PR-4.0-dev

#31779 [4.0] Finder js Uncaught TypeError when Advanced Search is set to hide or link to component
  build/media_source/com_finder/js/finder.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31784 Fix comments
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging, RTC

#31789 [4.0] Fix notice in com_csp
  components/com_csp/src/Controller/ReportController.php
Labels: PR-4.0-dev

#31788 [4.0] Fix broken finder suggestion
  components/com_finder/src/Model/SuggestionsModel.php
Labels: PR-4.0-dev, RTC

#31787 [3.9] Smart Search: Fix indexing for Postgres
  administrator/components/com_finder/helpers/indexer/driver/postgresql.php
Labels: PR-staging

#31776 [3.x] Versions button
  templates/protostar/css/template.css
  templates/protostar/html/layouts/joomla/form/field/contenthistory.php
  templates/protostar/less/template.less
Labels: PR-staging, RTC

#31399 Fix subform default value filtering, and warning while string foreach()
  libraries/src/Form/Form.php
Labels: PR-staging, RTC

#31380 Debug plugin freezes page with lots of DB queries
  plugins/system/debug/debug.php
Labels: PR-staging, RTC

#31794 Fix CSS build script to avoid multiple min files (Windows machine)
  build/build-modules-js/compilecss.es6.js
Labels: PR-4.0-dev

#31728 Clear old session data before save in global configuration
  administrator/components/com_config/controller/application/save.php
Labels: PR-staging, RTC

#31791 [4.0] Fix movecopy JS in field list
  administrator/components/com_fields/tmpl/fields/default_batch_body.php
  administrator/components/com_menus/tmpl/items/default_batch_body.php
  administrator/components/com_modules/tmpl/modules/default_batch_body.php
  administrator/components/com_users/tmpl/users/default_batch_body.php
  build/media_source/layouts/js/joomla/html/batch/batch-copymove.es6.js
  build/media_source/system/joomla.asset.json
  layouts/joomla/html/batch/adminlanguage.php
  layouts/joomla/html/batch/item.php
  layouts/joomla/html/batch/language.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31706 Hashing the simpleXMLElement doesn't produce an unique hash per element
  libraries/src/Form/Field/LimitboxField.php
Labels: PR-staging, RTC

#31799 [4.0] Adapt choices and custom_forms scss in Cassiopeia to better fit to each other
  templates/cassiopeia/scss/system/searchtools/searchtools.scss
  templates/cassiopeia/scss/tools/variables/_variables.scss
  templates/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
  templates/cassiopeia/scss/vendor/choicesjs/choices.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31808 [4.0][plugin][content][pagenavigation] fix wrong sql on order by
  plugins/content/pagenavigation/pagenavigation.php
Labels: PR-4.0-dev, RTC

#31800 [4.0] Move gzip command to work on windows
  build/build.js
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#31813 Cleanup warnings/deprecations in tests
  tests/Unit/Libraries/Cms/Document/DocumentTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
Labels: PR-4.0-dev, Unit/System Tests

#31812 [4.0] Cleanup Image tests
  tests/Unit/Libraries/Cms/Image/ImageTest.php
  tests/Unit/Libraries/Cms/Image/stubs/ImageInspector.php
Labels: PR-4.0-dev, Unit/System Tests

#31817 Rework final unit test to remove image inspector
  tests/Unit/Libraries/Cms/Image/ImageFilterTest.php
  tests/Unit/Libraries/Cms/Image/ImageTest.php
  tests/Unit/Libraries/Cms/Image/stubs/ImageFilterInspector.php
  tests/Unit/Libraries/Cms/Image/stubs/ImageInspector.php
Labels: PR-4.0-dev, Unit/System Tests

#31805 [4.0] Rework tags to have a dedicated interface
  administrator/components/com_banners/src/Table/BannerTable.php
  administrator/components/com_banners/src/Table/ClientTable.php
  administrator/components/com_contact/src/Table/ContactTable.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_newsfeeds/src/Table/NewsfeedTable.php
  administrator/components/com_tags/src/Table/TagTable.php
  administrator/components/com_users/src/Table/NoteTable.php
  libraries/src/Event/Model/BeforeBatchEvent.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Table/Category.php
  libraries/src/Table/Content.php
  libraries/src/Tag/TaggableTableInterface.php
  libraries/src/Tag/TaggableTableTrait.php
  plugins/behaviour/taggable/taggable.php
Labels: PR-4.0-dev, RTC
