Repository joomla/joomla-cms, pull requests merged in 2020-09, with the labels that each got.

#30531 [4.0] Sort options
  plugins/system/httpheaders/httpheaders.xml
Labels: PR-4.0-dev

#30268 [4.0] FieldsHelper: Choose a first available category correctly
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  libraries/src/MVC/Model/WorkflowBehaviorTrait.php
Labels: PR-4.0-dev, Release Blocker

#30473 [4.0] Implementing display of password minimum requirements for frontend registration
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/joomla.ini
  components/com_users/forms/registration.xml
  language/en-GB/joomla.ini
  layouts/joomla/form/field/password.php
  libraries/src/Form/Field/PasswordField.php
Labels: Language Change, PR-4.0-dev, RTC

#30516 [4.0] Messages/Alerts: using icons instead of text as heading
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
  build/media_source/system/js/core.es6/message.es6
  layouts/joomla/system/message.php
  templates/cassiopeia/scss/vendor/joomla-custom-elements/joomla-alert.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30534 [4.0] com_finder ul instead of dl for easier styling
  components/com_finder/tmpl/search/default_result.php
  components/com_finder/tmpl/search/default_results.php
Labels: PR-4.0-dev, RTC

#30535 [4.0] [a11y] add statement on found results
  administrator/components/com_finder/src/Service/HTML/Query.php
  components/com_finder/tmpl/search/default_results.php
  language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#30352 [4.0] Removing old docker images from drone setup
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#30505 Appveyor: Cleaning up logfile
  .appveyor.yml
Labels: PR-staging, Unit/System Tests

#30462 Moving CI from Travis to Drone
  .drone.jsonnet
  .drone.yml
  .hound.yml
  .travis.yml
  README.md
  phpunit.xml.dist
  tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageMemcachedTest.php
  tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageRedisTest.php
  travisci-phpunit.xml
Labels: PR-staging, Unit/System Tests

#30528 [4.0] [a11y] com_finder :: add missing legend to fieldset
  components/com_finder/tmpl/search/default_form.php
  language/en-GB/com_finder.ini
Labels: PR-4.0-dev, RTC

#30346 [3.10] Backport Categories #30297
  libraries/src/Categories/Categories.php
  libraries/src/Categories/CategoryFactory.php
  libraries/src/Categories/CategoryFactoryInterface.php
  libraries/src/Categories/CategoryInterface.php
  libraries/src/Categories/SectionNotFoundException.php
Labels: PR-3.10-dev

#30555 [4.0] Redundant words
  administrator/language/en-GB/com_privacy.ini
  language/en-GB/com_privacy.ini
Labels: Language Change, PR-4.0-dev, RTC

#30557 Fieldsfix
  administrator/components/com_fields/src/Model/FieldsModel.php
Labels: PR-4.0-dev

#30552 [4.0] Accessibility plugin position
  plugins/system/accessibility/accessibility.php
Labels: PR-4.0-dev, RTC

#30553 Appveyor: Downloading explicit composer.phar
  .appveyor.yml
Labels: PR-staging, Unit/System Tests

#30559 [4.0] Numbers not digits
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/joomla.ini
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
  language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev

#30568 [4.0] Useless installation lang strings
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
Labels: Language Change, PR-4.0-dev

#30527 [4.0] Display of horizontal mod_articles_news module
  build/media_source/mod_articles_news/css/template.css
  modules/mod_articles_news/tmpl/horizontal.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30537 [4.0] [Multilingual Status module] Adding displaying a possible error if URL Language Code is empty
  administrator/components/com_languages/src/Helper/MultilangstatusHelper.php
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/language/en-GB/com_languages.ini
Labels: Language Change, PR-4.0-dev, RTC

#30539 [4.0] Update Readme for Api tests
  tests/Codeception/README.md
Labels: PR-4.0-dev, Unit/System Tests

#30388 [4.0] favicon changes to support child templates
  libraries/src/Document/HtmlDocument.php
Labels: PR-4.0-dev, RTC

#30572 Fix media manager when using 0 maximum file size
  administrator/components/com_media/src/Controller/ApiController.php
Labels: PR-4.0-dev, RTC

#30573 Show exception messages on media error
  administrator/components/com_media/resources/scripts/app/Api.js
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/com_media.ini
  build/media_source/system/js/core.es6/text.es6
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#30571 [4.0] Apply the proposed changes from @brianteeman to the testing plugin language file
  plugins/sampledata/testing/language/en-GB/en-GB.plg_sampledata_testing.ini
Labels: PR-4.0-dev, RTC

#30543 [4.0] Align content info block icons
  layouts/joomla/content/icons.php
  layouts/joomla/content/icons/create.php
  layouts/joomla/content/icons/edit.php
  layouts/joomla/content/icons/edit_lock.php
  layouts/joomla/content/info_block/associations.php
  layouts/joomla/content/info_block/author.php
  layouts/joomla/content/info_block/category.php
  layouts/joomla/content/info_block/create_date.php
  layouts/joomla/content/info_block/hits.php
  layouts/joomla/content/info_block/modify_date.php
  layouts/joomla/content/info_block/publish_date.php
Labels: PR-4.0-dev, RTC

#30589 [staging] Correcting small typo from 30496
  administrator/language/en-GB/en-GB.com_languages.ini
Labels: RTC

#30585 [4.0] fix color selector box too small issue
  build/media_source/system/scss/_jquery-minicolors.scss
Labels: PR-4.0-dev, RTC

#30583 [4.0] Fix TinyMCE - simple preset
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev, RTC

#30596 dropdown corner css issue fix
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
  libraries/src/Toolbar/Toolbar.php
  libraries/src/Toolbar/ToolbarButton.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30588 [4.0] Modify display and tip for Edit Article in Frontend
  administrator/components/com_content/src/Service/HTML/Icon.php
  language/en-GB/com_content.ini
  layouts/joomla/content/icons.php
  layouts/joomla/content/icons/edit.php
  layouts/joomla/content/icons/edit_lock.php
  templates/cassiopeia/scss/blocks/_form.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#30580 [4.0] Fix "explain" feature in the debug plugin
  build/media_source/plg_system_debug/widgets/sqlqueries/widget.es5.js
  composer.lock
  plugins/system/debug/debug.php
  plugins/system/debug/src/DataCollector/QueryCollector.php
Labels: Composer Dependency Changed, NPM Resource Changed, PR-4.0-dev, RTC

#30523 [4.0] Saving article cause : hits = '' is not a valid integer
  administrator/components/com_content/forms/article.xml
Labels: PR-4.0-dev, RTC

#30609 [staging] Correcting variables specifiers in some installation language files
  installation/language/bn-BD/bn-BD.ini
  installation/language/hi-IN/hi-IN.ini
  installation/language/kk-KZ/kk-KZ.ini
  installation/language/vi-VN/vi-VN.ini
Labels: Language Change, PR-staging

#30601 [4.0] Adding back string deleted by error in 30588
  administrator/components/com_content/src/Service/HTML/Icon.php
  language/en-GB/com_content.ini
Labels: Language Change, PR-4.0-dev, RTC

#30470 [4.0] [JLayout] merge two equal JLayouts for iconclass into one new JLayout for iconclass
  layouts/joomla/button/iconclass.php
  layouts/joomla/content/info_block/category.php
  layouts/joomla/icon/iconclass.php
  layouts/joomla/toolbar/iconclass.php
  libraries/src/HTML/Helpers/ActionsDropdown.php
  libraries/src/HTML/Helpers/JGrid.php
  libraries/src/Toolbar/ToolbarButton.php
Labels: PR-4.0-dev, RTC

#30593 [4.0] adding additional check to avoid js script error
  build/media_source/plg_media-action_rotate/js/rotate.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#30373 [4.0] Revert removal of the "custom_data" field of the "extensions" database table.
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2017-03-18.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2017-04-25.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2017-10-10.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-11.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-02.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-19.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-05.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-01-16.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-31.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-04-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-07-02.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-07-13.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-08-21.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-10-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-11-07.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-02-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-03-10.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-04-11.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-04-18.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2017-03-18.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2017-04-25.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2017-10-10.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-11.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-02.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-01-16.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-31.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-04-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-02.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-08-21.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-10-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-11-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-02-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-03-10.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-04-11.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-04-18.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  installation/src/Model/ConfigurationModel.php
  libraries/src/Table/Extension.php
Labels: PR-4.0-dev

#30594 [4.0] Wrong link for Help in User Actions Log Options
  administrator/language/en-GB/joomla.ini
Labels: PR-4.0-dev, RTC

#30605 [4.0] Modify display and tip for Edit Contact in Frontend
  administrator/components/com_contact/src/Service/HTML/Icon.php
  components/com_contact/tmpl/category/default_items.php
  components/com_contact/tmpl/contact/default.php
  language/en-GB/com_contact.ini
  layouts/joomla/content/icons/edit_lock.php
  templates/cassiopeia/scss/blocks/_form.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, a11y

#30618 [4.0] save group button hover fix
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30613 [4.0] Get categories from component
  administrator/components/com_fields/src/Model/FieldsModel.php
Labels: PR-4.0-dev, RTC

#30520 [4.0] [webauthn] Set a default site name when the option is empty
  plugins/system/webauthn/src/Helper/CredentialsCreation.php
Labels: PR-4.0-dev, RTC

#30629 [4.0] Fix colouring of "Fluid Layout" toggle in Cassiopeia's template style options
  templates/cassiopeia/templateDetails.xml
Labels: J4 Frontend Template, PR-4.0-dev, RTC

#30632 align icons in mod_login
  modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev, RTC

#30617 [4.0] Fixing com_media URLs for frontend
  administrator/components/com_media/src/Controller/PluginController.php
  administrator/components/com_media/src/Model/FileModel.php
  administrator/components/com_media/tmpl/file/default.php
  administrator/components/com_media/tmpl/media/default.php
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  components/com_media/src/Dispatcher/Dispatcher.php
  layouts/joomla/form/field/media.php
  libraries/src/WebAsset/AssetItem/CoreAssetItem.php
  plugins/editors-xtd/image/image.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30641 Update template.js
  installation/template/js/template.js
Labels: PR-4.0-dev

#30600 [4.0] Remove unused model class
  components/com_config/src/Model/CmsModel.php
Labels: PR-4.0-dev

#30626 [4.0] Fix extension SQL check for generic components, modules and plugins
  administrator/components/com_installer/src/Model/DatabaseModel.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  libraries/src/Schema/ChangeSet.php
Labels: PR-4.0-dev, RTC, Release Blocker

#30574 [4.0] Store memory and time as float in Profiler
  libraries/src/Profiler/Profiler.php
Labels: PR-4.0-dev, RTC

#30550 Feature/4.0 dev a11y com finder refactor search result
  build/media_source/com_finder/css/finder.css
  components/com_finder/tmpl/search/default_result.php
  components/com_finder/tmpl/search/default_results.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30642 [4.0][com_contact] - fix unpublished contact
  components/com_contact/src/Model/ContactModel.php
Labels: PR-4.0-dev, RTC

#30355 [4.0] remove user from user group
  libraries/src/User/UserHelper.php
Labels: PR-4.0-dev, RTC

#30653 [4.0] re-throw the original exception
  components/com_contact/src/Model/ContactModel.php
  components/com_content/src/Model/ArticleModel.php
Labels: PR-4.0-dev, RTC

#30671 Missing string when uploading files
  language/en-GB/com_media.ini
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: Language Change, PR-4.0-dev, RTC

#30672 fix get list position error
  administrator/components/com_modules/src/Model/PositionsModel.php
Labels: PR-4.0-dev, RTC

#30648 [4.0] List Contacts in a Category display
  components/com_contact/tmpl/category/default_items.php
  language/en-GB/com_contact.ini
  templates/cassiopeia/scss/blocks/_global.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#30675 Fix tabs not wrapping and trigger horizontal scrolling
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30681 Add missing space between attributes
  administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue
Labels: NPM Resource Changed, PR-4.0-dev

#30684 [4.0] Missing alerts strings
  administrator/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
  layouts/joomla/system/message.php
Labels: Language Change, PR-4.0-dev, RTC

#30131 [4.0] Fix toolbar collapse in mobile view
  build/media_source/templates/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30687 [4.0] Correct field name
  administrator/components/com_contact/forms/contact.xml
Labels: PR-4.0-dev, RTC

#30688 [4.0] Fix media URLs when SEF suffix is enabled
  administrator/components/com_media/tmpl/file/default.php
  administrator/components/com_media/tmpl/media/default.php
Labels: PR-4.0-dev, RTC

#30578 Fix module rendering on error page
  templates/protostar/error.php
Labels: PR-staging, RTC

#30595 [staging]Wrong link for Help in User Actions Log Options
  administrator/language/en-GB/en-GB.ini
Labels: PR-staging, RTC

#30655 Correct module name in htaccess
  administrator/components/com_admin/sql/updates/mysql/3.9.22-2020-09-16.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.22-2020-09-16.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.22-2020-09-16.sql
  administrator/language/en-GB/en-GB.com_admin.ini
  htaccess.txt
Labels: Language Change, PR-staging, RTC

#30663 Correct markup in postinstall message
  administrator/language/en-GB/en-GB.com_cpanel.ini
Labels: Language Change, PR-staging, RTC

#30694 [4.0] Batch fieldset markup [a11y]
  administrator/components/com_users/tmpl/users/default_batch_body.php
  layouts/joomla/html/batch/item.php
Labels: PR-4.0-dev, RTC

#30686 [4.0] [Atum] Fix admin menu remaining hidden when enlarging screen width from small mobile to larger
  build/media_source/templates/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30696 [4.0] Admin menu redundant link
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-09-19.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#30676 Correct checkin permissions
  libraries/src/MVC/Model/FormModel.php
Labels: PR-staging, RTC

#30720 [4.0] more elements hard coded to string
  administrator/language/en-GB/tpl_atum.ini
  administrator/templates/atum/index.php
  build/media_source/templates/atum/js/template.es6.js
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#30710 [4.0] Cassiopea: fix category x layout
  templates/cassiopeia/scss/vendor/choicesjs/choices.scss
Labels: PR-4.0-dev, RTC

#30458 [4.0] Admin Module Help strings
  administrator/language/en-GB/joomla.ini
  administrator/modules/mod_loginsupport/mod_loginsupport.xml
Labels: Language Change, PR-4.0-dev, RTC

#30724 [4.0] codestyle
  libraries/src/Component/Router/Rules/MenuRules.php
  libraries/src/Component/Router/Rules/NomenuRules.php
  libraries/src/Component/Router/Rules/StandardRules.php
Labels: PR-4.0-dev, RTC

#30733 [4.0] Move route calls to layout in Breadcrumbs module
  modules/mod_breadcrumbs/src/Helper/BreadcrumbsHelper.php
  modules/mod_breadcrumbs/tmpl/default.php
Labels: PR-4.0-dev

#30692 [4.0] Composer update 19 sep
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev, RTC

#30717 [4.0] Fix Debug plugin to display query parameters
  build/media_source/plg_system_debug/widgets/sqlqueries/widget.css
  build/media_source/plg_system_debug/widgets/sqlqueries/widget.es5.js
  plugins/system/debug/src/DataCollector/QueryCollector.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29710 Fix hiddenLabel and add hiddenLegend form attribute
  layouts/joomla/form/renderfield.php
  libraries/src/Form/Field/NoteField.php
  libraries/src/Form/FormField.php
Labels: PR-4.0-dev

#30522 [4.1] Extend 2FA Enforcement option to select usergroups
  administrator/components/com_users/config.xml
  administrator/language/en-GB/com_users.ini
  libraries/src/Application/CMSApplication.php
Labels: Language Change, PR-4.1-dev, RTC

#30725 [3.9][plg_actionlogs] self activate account
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
  plugins/actionlog/joomla/joomla.php
Labels: PR-staging, RTC

#30729 [4.0] Cleanup cassiopeia chromes and rename "default" to "card"
  templates/cassiopeia/error.php
  templates/cassiopeia/html/layouts/chromes/card.php
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#30730 [4.0] Fix saving images
  build/media_source/com_media/js/edit-images.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30581 [4.0] Remove use of ReflectionParameter::getClass()
  libraries/src/Plugin/CMSPlugin.php
Labels: PR-4.0-dev, RTC

#30646 Fix JFile::getExt() when path contains period and file has no extension
  libraries/src/Filesystem/File.php
  tests/unit/suites/libraries/joomla/filesystem/JFileTest.php
Labels: PR-staging, RTC, Unit/System Tests

#30742 [4.0] spelling
  libraries/src/Component/Router/Rules/MenuRules.php
  libraries/src/Component/Router/Rules/NomenuRules.php
  libraries/src/Component/Router/Rules/StandardRules.php
Labels: PR-4.0-dev, RTC

#30738 [4.0] Use renderField() method to render fields in user profile
  components/com_users/tmpl/profile/edit.php
Labels: PR-4.0-dev, RTC

#30747 [4.0] Check out improvements related to nullable columns
  administrator/components/com_checkin/src/Model/CheckinModel.php
Labels: PR-4.0-dev, RTC

#30737 [4.0] Remove obsolete html code
  components/com_config/tmpl/config/default.php
Labels: PR-4.0-dev, RTC

#30734 [4.0] Remove "cardGrey" chrome
  templates/cassiopeia/error.php
  templates/cassiopeia/html/layouts/chromes/cardGrey.php
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#30754 [4.0] Remove Cassiopeias "_card.scss" override
  templates/cassiopeia/scss/template.scss
  templates/cassiopeia/scss/vendor/bootstrap/_card.scss
Labels: NPM Resource Changed, PR-4.0-dev

#28751 Ensure Itemid is never an array
  libraries/src/Application/CMSApplication.php
Labels: Documentation Required, PR-3.10-dev

#30597 [3.x] Register to read more
  components/com_content/views/article/tmpl/default.php
Labels: PR-3.10-dev, RTC

#18441 Support arbitrary relations for stylesheets
  libraries/src/Document/Renderer/Html/HeadRenderer.php
Labels: PR-3.10-dev

#30749 [4.0] Fix icons display in debug bar
  build/media_source/plg_system_debug/widgets/sqlqueries/widget.css
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30755 [staging] Backporting xtd menu items modal frontend filters
  administrator/components/com_menus/views/items/tmpl/modal.php
  components/com_menus/models/forms/filter_items.xml
Labels: PR-staging, RTC

#28447 [4.0] Improve text in batch modal
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: Language Change, PR-4.0-dev

#30102 [3.10] Backport Table _supportNullValue handling to 3.10
  libraries/src/Table/Table.php
Labels: PR-3.10-dev

#30765 [4.0] Cassiopeia missing string
  language/en-GB/tpl_cassiopeia.ini
Labels: RTC

#30549 [3.x] composer update --no-dev
  .gitignore
  composer.lock
  libraries/vendor/brumann/polyfill-unserialize/src/Unserialize.php
  libraries/vendor/composer/LICENSE
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/google/recaptcha/LICENSE
  libraries/vendor/google/recaptcha/src/ReCaptcha/ReCaptcha.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/CurlPost.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Socket.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/SocketPost.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestParameters.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/Response.php
  libraries/vendor/google/recaptcha/src/autoload.php
  libraries/vendor/joomla/filesystem/src/Buffer.php
  libraries/vendor/joomla/filesystem/src/Clients/FtpClient.php
  libraries/vendor/joomla/filesystem/src/Exception/FilesystemException.php
  libraries/vendor/joomla/filesystem/src/File.php
  libraries/vendor/joomla/filesystem/src/Folder.php
  libraries/vendor/joomla/filesystem/src/Helper.php
  libraries/vendor/joomla/filesystem/src/Patcher.php
  libraries/vendor/joomla/filesystem/src/Path.php
  libraries/vendor/joomla/filesystem/src/Stream.php
  libraries/vendor/joomla/filesystem/src/Stream/String.php
  libraries/vendor/joomla/filesystem/src/Stream/StringWrapper.php
  libraries/vendor/joomla/filesystem/src/Support/StringController.php
  libraries/vendor/joomla/filter/src/InputFilter.php
  libraries/vendor/joomla/filter/src/OutputFilter.php
  libraries/vendor/joomla/registry/src/AbstractRegistryFormat.php
  libraries/vendor/joomla/registry/src/Factory.php
  libraries/vendor/joomla/registry/src/Format/Ini.php
  libraries/vendor/joomla/registry/src/Format/Json.php
  libraries/vendor/joomla/registry/src/Format/Php.php
  libraries/vendor/joomla/registry/src/Format/Xml.php
  libraries/vendor/joomla/registry/src/Format/Yaml.php
  libraries/vendor/joomla/registry/src/FormatInterface.php
  libraries/vendor/joomla/registry/src/Registry.php
  libraries/vendor/joomla/string/src/Inflector.php
  libraries/vendor/joomla/string/src/Normalise.php
  libraries/vendor/joomla/string/src/String.php
  libraries/vendor/joomla/string/src/StringHelper.php
  libraries/vendor/joomla/string/src/phputf8/utils/unicode.php
  libraries/vendor/psr/log/Psr/Log/LoggerInterface.php
  libraries/vendor/symfony/polyfill-ctype/bootstrap.php
  libraries/vendor/symfony/polyfill-php55/Php55.php
  libraries/vendor/symfony/polyfill-php55/bootstrap.php
  libraries/vendor/symfony/polyfill-php56/bootstrap.php
  libraries/vendor/symfony/polyfill-php71/bootstrap.php
  libraries/vendor/symfony/polyfill-php73/bootstrap.php
  libraries/vendor/typo3/phar-stream-wrapper/composer.json
  libraries/vendor/typo3/phar-stream-wrapper/src/Helper.php
Labels: Composer Dependency Changed, PR-staging, RTC

#30761 [4.0] Wrap all buttons in btn-group to improve styling
  components/com_content/tmpl/category/default_articles.php
Labels: PR-4.0-dev, RTC

#30763 [4.0] Add missing Table Caption
  components/com_content/tmpl/category/default_articles.php
  language/en-GB/com_content.ini
Labels: PR-4.0-dev, RTC

#30739 [4.0] Fancy selectbox fix
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#18088 Refactored ExceptionHandler: separated logging and rendering
  libraries/cms.php
  libraries/src/Exception/ExceptionHandler.php
Labels: PR-3.10-dev, PR-staging, RTC

#30758 [4.0] Modifying com_actionlogs string
  administrator/language/en-GB/com_actionlogs.ini
Labels: Language Change, PR-4.0-dev, RTC

#30772 [4.0] Template layout select
  language/en-GB/tpl_cassiopeia.ini
Labels: PR-4.0-dev, RTC

#30751 Backport 2FA edit screen for com_admin
  administrator/components/com_admin/models/forms/profile.xml
  administrator/components/com_admin/models/profile.php
  administrator/components/com_admin/views/profile/tmpl/edit.php
  administrator/components/com_admin/views/profile/view.html.php
Labels: PR-staging, RTC

#30714 [3.9] Log the from version on actionlogs when Joomla update
  administrator/components/com_joomlaupdate/controllers/update.php
  administrator/components/com_joomlaupdate/models/default.php
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
  plugins/actionlog/joomla/joomla.php
Labels: Language Change, PR-staging, RTC

#30785 Improve code, remove separator
  modules/mod_articles_news/tmpl/horizontal.php
Labels: RTC

#30780 [4.0] mod_article_news readmore
  modules/mod_articles_news/tmpl/_item.php
Labels: PR-4.0-dev, RTC

#30713 [4.0] Update NPM dependencies
  package-lock.json
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30748 [4.0] Pluginless lazyloading for the core
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-04-18.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-27.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-04-18.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-09-27.sql
  administrator/language/en-GB/plg_content_imagelazyload.sys.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/HTML/HTMLHelper.php
  plugins/content/imagelazyload/imagelazyload.php
  plugins/content/imagelazyload/imagelazyload.xml
Labels: Language Change, PR-4.0-dev, RTC

#30781 Change grid minmax definition for newsflash module
  build/media_source/mod_articles_news/css/template.css
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30791 Revert "[3.x] composer update --no-dev"
  .gitignore
  composer.lock
  libraries/vendor/brumann/polyfill-unserialize/src/Unserialize.php
  libraries/vendor/composer/LICENSE
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/google/recaptcha/LICENSE
  libraries/vendor/google/recaptcha/src/ReCaptcha/ReCaptcha.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/CurlPost.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Socket.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/SocketPost.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/RequestParameters.php
  libraries/vendor/google/recaptcha/src/ReCaptcha/Response.php
  libraries/vendor/google/recaptcha/src/autoload.php
  libraries/vendor/joomla/filesystem/src/Buffer.php
  libraries/vendor/joomla/filesystem/src/Clients/FtpClient.php
  libraries/vendor/joomla/filesystem/src/Exception/FilesystemException.php
  libraries/vendor/joomla/filesystem/src/File.php
  libraries/vendor/joomla/filesystem/src/Folder.php
  libraries/vendor/joomla/filesystem/src/Helper.php
  libraries/vendor/joomla/filesystem/src/Patcher.php
  libraries/vendor/joomla/filesystem/src/Path.php
  libraries/vendor/joomla/filesystem/src/Stream.php
  libraries/vendor/joomla/filesystem/src/Stream/String.php
  libraries/vendor/joomla/filesystem/src/Stream/StringWrapper.php
  libraries/vendor/joomla/filesystem/src/Support/StringController.php
  libraries/vendor/joomla/filter/src/InputFilter.php
  libraries/vendor/joomla/filter/src/OutputFilter.php
  libraries/vendor/joomla/registry/src/AbstractRegistryFormat.php
  libraries/vendor/joomla/registry/src/Factory.php
  libraries/vendor/joomla/registry/src/Format/Ini.php
  libraries/vendor/joomla/registry/src/Format/Json.php
  libraries/vendor/joomla/registry/src/Format/Php.php
  libraries/vendor/joomla/registry/src/Format/Xml.php
  libraries/vendor/joomla/registry/src/Format/Yaml.php
  libraries/vendor/joomla/registry/src/FormatInterface.php
  libraries/vendor/joomla/registry/src/Registry.php
  libraries/vendor/joomla/string/src/Inflector.php
  libraries/vendor/joomla/string/src/Normalise.php
  libraries/vendor/joomla/string/src/String.php
  libraries/vendor/joomla/string/src/StringHelper.php
  libraries/vendor/joomla/string/src/phputf8/utils/unicode.php
  libraries/vendor/psr/log/Psr/Log/LoggerInterface.php
  libraries/vendor/symfony/polyfill-ctype/bootstrap.php
  libraries/vendor/symfony/polyfill-php55/Php55.php
  libraries/vendor/symfony/polyfill-php55/bootstrap.php
  libraries/vendor/symfony/polyfill-php56/bootstrap.php
  libraries/vendor/symfony/polyfill-php71/bootstrap.php
  libraries/vendor/symfony/polyfill-php73/bootstrap.php
  libraries/vendor/typo3/phar-stream-wrapper/composer.json
  libraries/vendor/typo3/phar-stream-wrapper/src/Helper.php
Labels: Composer Dependency Changed, PR-staging

#30788 [4.0] Blog view links
  components/com_content/tmpl/category/blog.php
  components/com_content/tmpl/category/blog_links.php
  components/com_content/tmpl/featured/default.php
  components/com_content/tmpl/featured/default_links.php
Labels: PR-4.0-dev, RTC, a11y

#30740 [4.0] Cassiopea table css
  templates/cassiopeia/scss/vendor/bootstrap/_table.scss
Labels: J4 Frontend Template, NPM Resource Changed, PR-4.0-dev, RTC

#30575 [4.0] Error in legacy plugins when method contains $event argument
  libraries/src/Plugin/CMSPlugin.php
Labels: PR-4.0-dev, RTC

#30800 [4.0] Replace file_exists() where applicable
  libraries/loader.php
  libraries/namespacemap.php
  libraries/src/Adapter/Adapter.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Dispatcher/LegacyComponentDispatcher.php
  libraries/src/Dispatcher/ModuleDispatcher.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Document/OpensearchDocument.php
  libraries/src/Document/Renderer/Html/MessageRenderer.php
  libraries/src/Extension/ExtensionManagerTrait.php
  libraries/src/Extension/LegacyComponent.php
  libraries/src/Form/Field/AccessiblemediaField.php
  libraries/src/Form/Field/ComponentlayoutField.php
  libraries/src/Form/Field/MediaField.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Image/Image.php
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/Pagination/Pagination.php
  libraries/src/Plugin/PluginHelper.php
  libraries/src/Router/SiteRouter.php
  libraries/src/Service/Provider/Config.php
  libraries/src/Workflow/WorkflowPluginTrait.php
Labels: PR-4.0-dev, RTC

#30796 [4.0] Clean up com_users forms
  components/com_users/forms/registration.xml
  components/com_users/forms/remind.xml
  components/com_users/forms/reset_complete.xml
  components/com_users/forms/reset_confirm.xml
  components/com_users/forms/reset_request.xml
  components/com_users/forms/sitelang.xml
  components/com_users/layouts/joomla/form/renderfield.php
  language/en-GB/com_users.ini
  plugins/user/profile/profile.php
Labels: PR-4.0-dev, RTC

#30804 [3.x] COM_USERS_PROFILE_TWOFACTOR_DESC
  language/en-GB/en-GB.com_users.ini
Labels: Language Change, PR-staging

#30811 [4.0] Workflow missing string
  language/en-GB/com_content.ini
Labels: Language Change, PR-4.0-dev
