Repository joomla/joomla-cms, pull requests merged in 2020-07, with the labels that each got.

#29877 Add "accept" attribute to the upload file input element of com_joomlaupdate's Upload & Update tab
  administrator/components/com_joomlaupdate/views/default/tmpl/default_upload.php
Labels: PR-staging

#29889 [4.0] Install from url messages
  administrator/components/com_installer/tmpl/install/default.php
Labels: RTC

#29840 [4.0] Fix for AccessibleMediaField
  libraries/src/Form/Field/AccessiblemediaField.php
  plugins/fields/media/media.php
  plugins/fields/media/tmpl/media.php
  tests/Unit/Libraries/Cms/Form/Field/AccessiblemediaFieldTest.php
Labels: PR-4.0-dev, Unit/System Tests

#29878 [4.0] Simple correct spelling, and rephrase sentence
  libraries/src/Exception/ExceptionHandler.php
Labels: PR-4.0-dev, RTC

#29860 [4] Use modal.js instead of batch.js in editor when inserting article link
  administrator/components/com_content/tmpl/articles/modal.php
Labels: PR-4.0-dev, RTC

#29900 [4.0] Missing icon
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
Labels: PR-4.0-dev, RTC

#29907 [4.0] com_redirect bulk import [a11y]
  administrator/components/com_redirect/tmpl/links/default_batch_body.php
Labels: PR-4.0-dev, RTC

#29913 [4.0] Mail Templates broken ARIA [a11y]
  administrator/components/com_mails/tmpl/templates/default.php
Labels: PR-4.0-dev

#29921 [4.0] [mod_login] Safe cross-origin link
  administrator/modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev

#29251 [4.0] Restore com_admin profile view
  administrator/components/com_admin/forms/profile.xml
  administrator/components/com_admin/src/Controller/ProfileController.php
  administrator/components/com_admin/src/Model/ProfileModel.php
  administrator/components/com_admin/src/View/Profile/HtmlView.php
  administrator/components/com_admin/tmpl/profile/edit.php
  administrator/components/com_users/forms/user.xml
  administrator/language/en-GB/com_admin.ini
  administrator/modules/mod_user/tmpl/default.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/fields/fields.php
  plugins/user/token/token.php
Labels: Language Change, PR-4.0-dev, RTC

#29925 Undeprecate Joomla\CMS\Image classes
  libraries/src/Image/Image.php
  libraries/src/Image/ImageFilter.php
Labels: PR-staging

#29923 [4.0] Remove client-side password validation from login form
  components/com_users/forms/login.xml
Labels: PR-4.0-dev

#29915 [4.0] batch user field label [a11y]
  layouts/joomla/html/batch/user.php
Labels: PR-4.0-dev, RTC

#29919 [4.0] subform repeatable-table cleanup
  layouts/joomla/form/field/subform/repeatable-table.php
Labels: PR-4.0-dev, RTC

#29916 [4.0] calendar field [a11y]
  layouts/joomla/form/field/calendar.php
Labels: PR-4.0-dev, RTC

#29918 [4.0] contact misc info [a11y]
  administrator/components/com_contact/tmpl/contact/edit.php
Labels: PR-4.0-dev, RTC

#29917 [4.0] com_banner batch client [a11y]
  administrator/components/com_banners/src/Service/Html/Banner.php
Labels: PR-4.0-dev, RTC

#29932 [4.0] Use rel="noopener" for more links
  administrator/components/com_templates/tmpl/template/default.php
  components/com_content/src/View/Category/FeedView.php
  components/com_content/src/View/Featured/FeedView.php
  components/com_newsfeeds/tmpl/newsfeed/default.php
  modules/mod_feed/tmpl/default.php
Labels: PR-4.0-dev

#29935 [4.0] Fix SVG code
  plugins/editors-xtd/menu/menu.php
Labels: RTC

#29908 [4.0] Change in Installation form for showing Congratulations-Section after skip installation of additional language
  installation/template/js/remove.js
Labels: RTC

#29939 [4.0] [a11y] empty headings com languages
  administrator/components/com_languages/tmpl/language/edit.php
  administrator/language/en-GB/com_languages.ini
Labels: PR-4.0-dev, RTC

#29963 [4.0] For the same reasons /cli is there - add /api to robots.txt
  robots.txt.dist
Labels: PR-4.0-dev

#29946 [4.0] Fix notice in extension manager
  administrator/components/com_installer/tmpl/manage/default.php
Labels: PR-4.0-dev, RTC

#29964 Fix doc block for addIncludePaths($paths)
  libraries/src/Layout/FileLayout.php
Labels: PR-staging

#29966 Fix doc block for addIncludePaths
  libraries/src/Layout/FileLayout.php
Labels: PR-staging

#29962 [4.0] No Matching Results in wrong place in contacts model
  administrator/components/com_contact/tmpl/contacts/modal.php
Labels: PR-4.0-dev, RTC

#29967 [4.0] s/this/that
  administrator/components/com_finder/src/Indexer/Language/Zh.php
  administrator/components/com_menus/src/Model/ItemModel.php
  layouts/plugins/system/privacyconsent/label.php
  layouts/plugins/system/privacyconsent/message.php
  libraries/src/Access/Access.php
  libraries/src/HTML/Helpers/Bootstrap.php
  plugins/sampledata/testing/testing.php
  plugins/system/debug/debug.php
  tests/Unit/Libraries/Cms/Image/ImageTest.php
  tests/Unit/bootstrap.php
Labels: PR-4.0-dev, Unit/System Tests

#29892 [4.0] Wrong language string selected when creating overrides
  build/media_source/com_languages/js/overrider.es6.js
Labels: PR-4.0-dev, RTC

#29959 [4.0[] Fix Features Icon color missing - s/color-featured/icon-color-featured
  libraries/src/Button/FeaturedButton.php
Labels: PR-4.0-dev, RTC

#29933 [4.0] Undefined variable: icon
  libraries/src/HTML/Helpers/JGrid.php
Labels: PR-4.0-dev, RTC

#29927 [4.0] Fix Vertical Tabs - The orientation parameter is ignored
  libraries/src/HTML/Helpers/UiTab.php
Labels: PR-4.0-dev, RTC

#29894 [4.0] Hide and disable "More Results" button in Language Overrides when no more results
  administrator/components/com_languages/tmpl/override/edit.php
  build/media_source/com_languages/js/overrider.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29849 [4.0] Remove unused variables in template files
  administrator/templates/atum/component.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#29960 [4.0] Remove unneeded version attribute from XML files
  administrator/components/com_mails/mails.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/modules/mod_frontend/mod_frontend.xml
  administrator/modules/mod_loginsupport/mod_loginsupport.xml
  administrator/modules/mod_messages/mod_messages.xml
  administrator/modules/mod_post_installation_messages/mod_post_installation_messages.xml
  administrator/modules/mod_privacy_status/mod_privacy_status.xml
  administrator/modules/mod_submenu/mod_submenu.xml
  administrator/modules/mod_user/mod_user.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  installation/language/en-GB/langmetadata.xml
  installation/language/en-US/langmetadata.xml
  language/en-GB/langmetadata.xml
  plugins/api-authentication/token/token.xml
  plugins/fields/subfields/subfields.xml
  plugins/quickicon/downloadkey/downloadkey.xml
  plugins/user/token/token.xml
  plugins/webservices/banners/banners.xml
  plugins/webservices/config/config.xml
  plugins/webservices/contact/contact.xml
  plugins/webservices/installer/installer.xml
  plugins/webservices/languages/languages.xml
  plugins/webservices/menus/menus.xml
  plugins/webservices/messages/messages.xml
  plugins/webservices/modules/modules.xml
  plugins/webservices/newsfeeds/newsfeeds.xml
  plugins/webservices/plugins/plugins.xml
  plugins/webservices/privacy/privacy.xml
  plugins/webservices/redirect/redirect.xml
  plugins/webservices/tags/tags.xml
  plugins/webservices/templates/templates.xml
  plugins/webservices/users/users.xml
Labels: Language Change, PR-4.0-dev

#29920 [4.0] [a11y] PR for #29909 rfc empty headings
  administrator/components/com_users/tmpl/user/edit.php
  administrator/language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#29969 [4.0] Fix modal layout if no items are found
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
Labels: PR-4.0-dev, RTC

#29972 [4.0] tinymce plugin missing string [a11y]
  administrator/language/en-GB/plg_editors_tinymce.ini
  plugins/editors/tinymce/tinymce.xml
Labels: Language Change, PR-4.0-dev, RTC

#29971 [4.0] Add open new window tooltip
  administrator/components/com_templates/tmpl/styles/default.php
Labels: PR-4.0-dev, RTC

#29893 [4.0] com_templates labels [a11y]
  administrator/components/com_templates/tmpl/template/default_modal_file_body.php
  administrator/components/com_templates/tmpl/template/default_modal_folder_body.php
  administrator/components/com_templates/tmpl/template/default_modal_rename_body.php
  administrator/components/com_templates/tmpl/template/default_modal_resize_body.php
Labels: PR-4.0-dev, RTC

#29863 [4.0] Fix admin login button hover
  administrator/templates/atum/scss/blocks/_login.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29973 [4.0] Fix Text case
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_reinstall.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php
Labels: PR-4.0-dev, RTC

#29970 [4.0] Media Action plugins
  administrator/language/en-GB/plg_media-action_crop.ini
  administrator/language/en-GB/plg_media-action_resize.ini
  administrator/language/en-GB/plg_media-action_rotate.ini
  plugins/media-action/crop/form/crop.xml
  plugins/media-action/resize/form/resize.xml
  plugins/media-action/resize/resize.xml
  plugins/media-action/rotate/form/rotate.xml
Labels: Language Change, PR-4.0-dev, RTC

#29978 [4.0] Fix typo
  libraries/src/HTML/Helpers/SortableList.php
Labels: PR-4.0-dev

#29977 [4.0] Untranslated string
  administrator/components/com_content/forms/filter_articles.xml
Labels: PR-4.0-dev

#29984 [4.0] typo draggable
  libraries/src/HTML/Helpers/SortableList.php
Labels: PR-4.0-dev

#29833 [4.0] Fix "Exit Recovery Mode" link
  administrator/modules/mod_menu/src/Menu/CssMenu.php
Labels: PR-4.0-dev

#29999 [4.0] Correct field type casing
  components/com_modules/forms/filter_modules.xml
Labels: PR-4.0-dev, RTC

#29975 [4.0] Double translations
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev, RTC

#29911 [4.0] Database information [a11y]
  administrator/components/com_installer/tmpl/database/default.php
Labels: PR-4.0-dev, RTC

#29928 [4.0] Featured Contact [a11y]
  administrator/components/com_contact/src/Service/HTML/AdministratorService.php
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#30004 [4.0] Add versioning traits to frontend controllers
  components/com_contact/src/Controller/ContactController.php
  components/com_content/src/Controller/ArticleController.php
Labels: PR-4.0-dev

#30010 [4.0] Finder: pseudo-empty search query should not throw error
  administrator/components/com_finder/src/Indexer/Query.php
Labels: PR-4.0-dev, RTC

#30011 [4.0] Show error message when restoring version fails
  libraries/src/Versioning/VersionableControllerTrait.php
Labels: PR-4.0-dev, RTC

#29914 [4.0] com_finder labels [a11y]
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/maps/default.php
Labels: PR-4.0-dev, RTC

#30003 [4.0] com_users tfa hover
  administrator/components/com_users/tmpl/users/default.php
Labels: PR-4.0-dev, RTC

#30042 [4.0] Transitions still shown when workflows disabled
  administrator/components/com_content/src/View/Featured/HtmlView.php
Labels: PR-4.0-dev, RTC

#30058 [4.0] Cleanup .gitignore a little - can be merged on sight :)
  .gitignore
Labels: PR-4.0-dev

#30059 [4.0] Fix column name ordering
  administrator/components/com_modules/src/Model/PositionsModel.php
Labels: PR-4.0-dev, RTC

#30038 [4.0] Fix Cassiopea Modals body and Close button display
  templates/cassiopeia/scss/blocks/_modals.scss
Labels: RTC

#30025 [4.0] Fix for wrong site title when using ToobarHelper in frontend
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev, RTC

#30063 [4.0][com_installer] Refactor using new Toolbar
  administrator/components/com_installer/src/View/Manage/HtmlView.php
Labels: PR-4.0-dev, RTC

#30066 [4.0] Fix a falsie error alert on media field
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
Labels: PR-4.0-dev, RTC

#30040 [4.0] add additional php settings to system info helpful for debugging
  administrator/components/com_admin/src/Model/SysinfoModel.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
  administrator/language/en-GB/com_admin.ini
Labels: Language Change, PR-4.0-dev, RTC

#30036 [4] Don't interrupt getCoreList() if single template has no /html/
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: PR-4.0-dev, RTC

#30031 [4.0] Auto removing $root_user gives Invalid controller class: config
  libraries/src/Application/AdministratorApplication.php
Labels: PR-4.0-dev, RTC

#30022 [4.0] Fix translation of message titles in Cassiopea
  layouts/joomla/system/message.php
Labels: PR-4.0-dev, RTC

#30068 [4.0][com_plugins] Move buttons out of dropdown
  administrator/components/com_plugins/src/View/Plugins/HtmlView.php
Labels: PR-4.0-dev, RTC

#29823 [4.0] Standardise indents of instructions in .htaccess
  htaccess.txt
Labels: PR-4.0-dev, RTC

#29938 [4.0] IFW client js
  build/media_source/plg_installer_webinstaller/js/client.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29905 [4.0] com_checkin [a11y]
  administrator/components/com_checkin/tmpl/checkin/default.php
Labels: PR-4.0-dev, RTC

#29904 [4.0] Template Styles [a11y]
  administrator/components/com_templates/tmpl/styles/default.php
Labels: PR-4.0-dev, RTC

#29902 [4.0] Discover extensions [a11y]
  administrator/components/com_installer/tmpl/discover/default.php
Labels: PR-4.0-dev, RTC

#29882 [4.0] Correct @param docblock parameter types
  libraries/src/Application/ApplicationHelper.php
Labels: PR-4.0-dev, RTC

#29912 [4.0] update sites [a11y]
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev, RTC

#30072 [4] com_menus. Items modal. Right align toolbar fields like in all other modals.
  administrator/components/com_menus/tmpl/items/modal.php
Labels: PR-4.0-dev

#30069 [4.0] Add margins to header title
  administrator/templates/atum/scss/blocks/_header.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30071 [4.0] Reset the state on the media field
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
Labels: PR-4.0-dev, RTC

#30075 [4.0] Fixed filtering by multiple tags in a blog layout
  components/com_content/src/Model/ArticlesModel.php
Labels: PR-4.0-dev, RTC

#30077 [4.0] Fix Cassiopea searchtools alignment in modals
  templates/cassiopeia/scss/system/searchtools/searchtools.scss
Labels: PR-4.0-dev, RTC

#29249 [4.0] Center status/date created headers
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_finder/tmpl/index/default.php
Labels: PR-4.0-dev, RTC

#30078 [3.10] Switcher field transition, from j3.10 to j4
  layouts/joomla/form/field/radio/switcher.php
Labels: PR-3.10-dev, RTC

#30085 [4.0][com_postinstall] Refactor using new Toolbar
  administrator/components/com_postinstall/src/View/Messages/HtmlView.php
Labels: PR-4.0-dev, RTC

#30089 [4.0] Change all
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_modules/tmpl/select/default.php
  administrator/modules/mod_login/tmpl/default.php
  components/com_users/tmpl/login/default_login.php
  modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev, RTC

#30087 [4.0] Menu items modal: adding missing filters
  administrator/components/com_menus/tmpl/items/modal.php
  components/com_menus/forms/filter_items.xml
Labels: PR-4.0-dev, RTC

#30092 [4.0] Correct incorrect @return documentation
  plugins/workflow/featuring/featuring.php
Labels: PR-4.0-dev

#30094 [4.0][com_fields] Fix draggable sorting
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
Labels: PR-4.0-dev

#30097 [4.0] Cassiopea: Fixing modals custom-select fields display
  templates/cassiopeia/scss/_variables.scss
  templates/cassiopeia/scss/blocks/_modals.scss
  templates/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
Labels: PR-4.0-dev, RTC

#29881 Add missing return statement in joomlaupdate controller
  administrator/components/com_joomlaupdate/controllers/update.php
Labels: PR-staging, RTC

#29980 [4.0] Fix js ajax for pre update checker
  build/media_source/com_joomlaupdate/js/default.es5.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30008 [4.0] Optimizing Smart Search for larger content
  administrator/components/com_finder/src/Indexer/Helper.php
  administrator/components/com_finder/src/Indexer/Indexer.php
Labels: PR-4.0-dev, RTC

#30037 [4.0] Removing unnecessary workaround in finder indexer
  administrator/components/com_finder/src/Controller/IndexerController.php
Labels: Documentation Required, PR-4.0-dev, RTC

#29987 Feature/draggable typo fixes
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  build/media_source/system/js/draggable.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29811 [4.0] CLI help text
  libraries/src/Console/AddUserCommand.php
  libraries/src/Console/AddUserToGroupCommand.php
  libraries/src/Console/ChangeUserPasswordCommand.php
  libraries/src/Console/CheckJoomlaUpdatesCommand.php
  libraries/src/Console/CheckUpdatesCommand.php
  libraries/src/Console/CleanCacheCommand.php
  libraries/src/Console/DeleteUserCommand.php
  libraries/src/Console/ExtensionInstallCommand.php
  libraries/src/Console/ExtensionRemoveCommand.php
  libraries/src/Console/ExtensionsListCommand.php
  libraries/src/Console/GetConfigurationCommand.php
  libraries/src/Console/ListUserCommand.php
  libraries/src/Console/RemoveOldFilesCommand.php
  libraries/src/Console/RemoveUserFromGroupCommand.php
  libraries/src/Console/SessionGcCommand.php
  libraries/src/Console/SessionMetadataGcCommand.php
  libraries/src/Console/SetConfigurationCommand.php
  libraries/src/Console/SiteDownCommand.php
  libraries/src/Console/SiteUpCommand.php
  libraries/src/Console/UpdateCoreCommand.php
Labels: PR-4.0-dev, RTC

#29694 [4.0] Refactor to return early, remove if depths and throw NotAllowed
  administrator/components/com_contenthistory/src/Model/CompareModel.php
  administrator/components/com_contenthistory/src/Model/HistoryModel.php
  administrator/components/com_contenthistory/src/Model/PreviewModel.php
Labels: PR-4.0-dev, RTC

#29731 [4.0] Webauthn gmp warning
  administrator/language/en-GB/plg_system_webauthn.ini
  layouts/plugins/system/webauthn/manage.php
Labels: Language Change, PR-4.0-dev, RTC

#29870 [4.0] Wrap component output in `main` element to make Cassiopeia more accessible
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#30132 [4.0] Display sidebar nav/toolbar when resizing from mobile to desktop
  build/media_source/templates/atum/js/template.es6.js
Labels: PR-4.0-dev, RTC

#30039 [4.0] Get menu directly in com_tags menu route helper
  components/com_tags/src/Helper/RouteHelper.php
Labels: PR-4.0-dev, RTC

#30007 [4.0] Generate routed Modal links for iframes when not on the root
  layouts/joomla/form/field/contenthistory.php
  layouts/joomla/form/field/media.php
Labels: PR-4.0-dev, RTC

#29474 [4.0] Smart Search: Fixing ordering, order direction and disabled button
  administrator/components/com_finder/config.xml
  administrator/language/en-GB/com_finder.ini
  components/com_finder/src/Model/SearchModel.php
  components/com_finder/tmpl/search/default.xml
  components/com_finder/tmpl/search/default_form.php
Labels: Language Change, PR-4.0-dev, RTC

#30064 [4.0] A load of general cleanup
  components/com_contact/layouts/joomla/form/renderfield.php
  components/com_users/layouts/joomla/form/renderfield.php
  layouts/chromes/outline.php
  layouts/joomla/button/action-button.php
  layouts/joomla/button/transition-button.php
  layouts/joomla/edit/publishingdata.php
  layouts/joomla/form/field/color/simple.php
  layouts/joomla/form/field/contenthistory.php
  layouts/joomla/form/field/media.php
  layouts/joomla/form/field/radio/buttons.php
  layouts/joomla/form/field/radio/switcher.php
  layouts/joomla/form/field/rules.php
  layouts/joomla/form/field/subform/default.php
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable-table/section.php
  layouts/joomla/form/field/subform/repeatable.php
  layouts/joomla/form/field/subform/repeatable/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable/section.php
  layouts/joomla/form/field/textarea.php
  layouts/joomla/form/field/time.php
  layouts/joomla/form/field/user.php
  layouts/joomla/form/renderfield.php
  layouts/joomla/form/renderlabel.php
  layouts/joomla/html/batch/access.php
  layouts/joomla/html/batch/adminlanguage.php
  layouts/joomla/html/batch/item.php
  layouts/joomla/html/batch/language.php
  layouts/joomla/html/batch/tag.php
  layouts/joomla/html/batch/user.php
  layouts/joomla/html/batch/workflowstage.php
  layouts/joomla/html/treeprefix.php
  layouts/joomla/modal/body.php
  layouts/joomla/modal/footer.php
  layouts/joomla/modal/header.php
  layouts/joomla/modal/iframe.php
  layouts/joomla/modal/main.php
  layouts/joomla/toolbar/base.php
  layouts/joomla/toolbar/basic.php
  layouts/joomla/toolbar/dropdown.php
  layouts/joomla/toolbar/link.php
  layouts/joomla/toolbar/popup.php
  layouts/joomla/toolbar/separator.php
  layouts/joomla/toolbar/standard.php
  layouts/joomla/toolbar/versions.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder/setoptions.php
  layouts/plugins/system/privacyconsent/label.php
  layouts/plugins/user/profile/fields/dob.php
  layouts/plugins/user/terms/label.php
  plugins/system/stats/layouts/message.php
  plugins/system/stats/layouts/stats.php
Labels: PR-4.0-dev, RTC

#29524 [3.10] Compatibilitycheck
  administrator/components/com_joomlaupdate/controllers/update.php
  administrator/components/com_joomlaupdate/models/default.php
  administrator/components/com_joomlaupdate/views/default/tmpl/default.php
  administrator/components/com_joomlaupdate/views/default/tmpl/default_preupdatecheck.php
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
  administrator/templates/hathor/html/com_joomlaupdate/default/default.php
  media/com_joomlaupdate/js/default.js
  media/com_joomlaupdate/js/default.min.js
Labels: Language Change, PR-3.10-dev

#30158 [3.x] Set the threshold for rips to 0 and write out the rips cli options
  .drone.yml
Labels: PR-staging, Unit/System Tests

#30163 [4.0] Remove redundant type checks
  plugins/system/webauthn/src/PluginTraits/UserProfileFields.php
  plugins/user/token/token.php
Labels: PR-4.0-dev, RTC

#30156 [4.0] [a11y] :recycle: replace non-a11y form in table by a11y form
  administrator/components/com_installer/tmpl/installer/default_ftp.php
Labels: PR-4.0-dev, RTC

#30146 [4.0][CLI] list:user needs cast to char
  libraries/src/Console/ListUserCommand.php
Labels: PR-4.0-dev, RTC

#28839 [4.0] Template Atum - Cleanup and fix Logo Usage
  administrator/language/en-GB/tpl_atum.ini
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/images/logo-blue.svg
  administrator/templates/atum/images/logo-joomla-blue.svg
  administrator/templates/atum/images/logo-joomla-white.svg
  administrator/templates/atum/images/logo.svg
  administrator/templates/atum/images/logos/brand-large.svg
  administrator/templates/atum/images/logos/brand-small.svg
  administrator/templates/atum/images/logos/login.svg
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/blocks/_header.scss
  administrator/templates/atum/templateDetails.xml
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#30091 [4.0] fix typehint syntax & other comment issues
  plugins/workflow/featuring/featuring.php
  plugins/workflow/notification/notification.php
  plugins/workflow/publishing/publishing.php
Labels: PR-4.0-dev, RTC

#30170 [4.0] Fix admin menu collapse when joomla is in a folder with uppercase name
  build/media_source/mod_menu/js/admin-menu.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30174 [4.0] Rename Purge to Clear Log
  administrator/language/en-GB/com_actionlogs.ini
Labels: Language Change, PR-4.0-dev

#30167 [4.0] Fix permission display in mobile view
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: PR-4.0-dev, RTC

#30140 [4.0] Improve card layout for JED extensions
  build/media_source/plg_installer_webinstaller/scss/client.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30096 [4.0] Move status message below field
  administrator/components/com_languages/tmpl/override/edit.php
  build/media_source/com_languages/css/overrider.css
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29983 [4.0] 29957 css
  administrator/templates/atum/scss/blocks/_icons.scss
  build/media_source/system/scss/_icomoon.scss
  libraries/src/HTML/Helpers/JGrid.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30176 [4.0] Set fixed width for password toggle icon
  administrator/modules/mod_login/tmpl/default.php
  layouts/joomla/form/field/password.php
  modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev

#30172 [4.0] Support Model::getInstance for namespaced components
  libraries/src/MVC/Model/LegacyModelLoaderTrait.php
Labels: PR-4.0-dev, RTC

#30119 [4.0] Check if service is registered before registering
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
Labels: PR-4.0-dev, RTC

#29886 [4.0] add aria-label / aria-labelledby to module rendering
  layouts/chromes/html5.php
  templates/cassiopeia/html/layouts/chromes/cardGrey.php
  templates/cassiopeia/html/layouts/chromes/default.php
Labels: PR-4.0-dev, RTC

#29854 [4.0] Move from Factory::getConfig to getting config from application
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_finder/src/Table/MapTable.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_privacy/src/Model/RequestModel.php
  administrator/components/com_privacy/src/View/Request/HtmlView.php
  administrator/components/com_privacy/src/View/Requests/HtmlView.php
  cli/finder_indexer.php
  components/com_privacy/src/Model/RequestModel.php
  components/com_privacy/src/View/Request/HtmlView.php
  installation/src/Model/LanguagesModel.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Factory.php
  libraries/src/Form/Field/CalendarField.php
  libraries/src/Log/Logger/FormattedtextLogger.php
  libraries/src/Mail/MailTemplate.php
  libraries/src/Session/Storage/JoomlaStorage.php
  plugins/privacy/user/user.php
  plugins/sampledata/blog/blog.php
  plugins/sampledata/multilang/multilang.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/logrotation/logrotation.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-4.0-dev, RTC

#29396 [4.0] Removing obsolete code from core table classes
  libraries/src/Table/CoreContent.php
  libraries/src/Table/Extension.php
  libraries/src/Table/Update.php
Labels: PR-4.0-dev, RTC

#30152 [4.0] Redirect to com_admin when forcing TFA
  administrator/components/com_admin/forms/profile.xml
  administrator/components/com_admin/src/Model/ProfileModel.php
  libraries/src/Application/CMSApplication.php
Labels: PR-4.0-dev, RTC

#29789 [4.0][CLI] version option
  libraries/src/Application/ConsoleApplication.php
Labels: PR-4.0-dev, RTC

#29827 [4.0][CLI] add confirmation step before delete user
  libraries/src/Console/DeleteUserCommand.php
Labels: PR-4.0-dev, RTC

#30134 [4.0][api][com_content] render metafields "metakey", "metadesc" and "metadata" and fields "featured" and "access"
  administrator/components/com_content/src/Model/ArticlesModel.php
  api/components/com_content/src/View/Articles/JsonapiView.php
Labels: PR-4.0-dev, RTC

#30188 [4.0] mod_syndicate a11y and more
  language/en-GB/mod_syndicate.ini
  modules/mod_syndicate/mod_syndicate.xml
  modules/mod_syndicate/tmpl/default.php
Labels: Language Change, PR-4.0-dev, RTC

#30183 [4.0] fix Templates : Edit style - unsaved menu assignments
  administrator/components/com_templates/src/Model/StyleModel.php
Labels: PR-4.0-dev, RTC

#30202 [4.0][api][com_content] complete the list of fields to render
  administrator/components/com_content/src/Model/ArticlesModel.php
  api/components/com_content/src/View/Articles/JsonapiView.php
Labels: PR-4.0-dev, RTC

#30204 Missing FA for icon-save
  layouts/joomla/button/iconclass.php
  layouts/joomla/toolbar/iconclass.php
Labels: PR-4.0-dev

#30206 [4.0] Missing icon on Crop button
  administrator/components/com_templates/src/View/Template/HtmlView.php
  layouts/joomla/button/iconclass.php
  layouts/joomla/toolbar/iconclass.php
  libraries/src/Toolbar/Button/StandardButton.php
  libraries/src/Toolbar/ToolbarButton.php
Labels: PR-4.0-dev, RTC

#30196 [4.0] Removing Hound and moving to Drone
  .drone.yml
  .eslintignore
  .hound.yml
  .stylelintrc.json
  administrator/components/com_media/resources/styles/components/_layout.scss
  administrator/components/com_media/resources/styles/components/_media-breadcrumb.scss
  administrator/components/com_media/resources/styles/components/_media-browser.scss
  administrator/components/com_media/resources/styles/components/_media-modal.scss
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_form.scss
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_header.scss
  administrator/templates/atum/scss/blocks/_icons.scss
  administrator/templates/atum/scss/blocks/_login.scss
  administrator/templates/atum/scss/blocks/_quickicons.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/blocks/_switcher.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/blocks/_utilities.scss
  administrator/templates/atum/scss/pages/_com_content.scss
  administrator/templates/atum/scss/pages/_com_cpanel.scss
  administrator/templates/atum/scss/pages/_com_templates.scss
  administrator/templates/atum/scss/template-rtl.scss
  administrator/templates/atum/scss/vendor/_tinymce.scss
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
  administrator/templates/atum/scss/vendor/bootstrap/_reboot.scss
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
  build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
  build/media_source/plg_editors_tinymce/scss/tinymce-builder.scss
  build/media_source/plg_installer_webinstaller/scss/client.scss
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-module-order.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-send-test-mail.w-c.es6.js
  build/media_source/system/scss/_jalert.scss
  build/media_source/system/scss/joomla-core-loader.scss
  package-lock.json
  package.json
  scss-lint.yml
  templates/cassiopeia/scss/_variables.scss
  templates/cassiopeia/scss/blocks/_alerts.scss
  templates/cassiopeia/scss/blocks/_css-grid.scss
  templates/cassiopeia/scss/blocks/_demo-styling.scss
  templates/cassiopeia/scss/blocks/_footer.scss
  templates/cassiopeia/scss/blocks/_modifiers.scss
  templates/cassiopeia/scss/system/searchtools/searchtools.scss
  templates/cassiopeia/scss/vendor/_tinymce.scss
Labels: NPM Resource Changed, PR-4.0-dev, Unit/System Tests

#30213 [4.0] Remove Gemfiles
  Gemfile
  Gemfile.lock
Labels: PR-4.0-dev

#30194 [4.0] Reduced duplicated code in ProfileModel.
  administrator/components/com_admin/src/Model/ProfileModel.php
Labels: PR-4.0-dev, RTC
