Repository joomla/joomla-cms, pull requests merged in 2020-10, with the labels that each got.

#30801 Update Composer dependencies
  composer.lock
  libraries/vendor/brumann/polyfill-unserialize/src/DisallowedClassesSubstitutor.php
  libraries/vendor/brumann/polyfill-unserialize/src/Unserialize.php
  libraries/vendor/composer/ClassLoader.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_real.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/filesystem/src/Buffer.php
  libraries/vendor/joomla/filesystem/src/Clients/FtpClient.php
  libraries/vendor/joomla/filesystem/src/Exception/FilesystemException.php
  libraries/vendor/joomla/filesystem/src/File.php
  libraries/vendor/joomla/filesystem/src/Folder.php
  libraries/vendor/joomla/filesystem/src/Helper.php
  libraries/vendor/joomla/filesystem/src/Patcher.php
  libraries/vendor/joomla/filesystem/src/Path.php
  libraries/vendor/joomla/filesystem/src/Stream.php
  libraries/vendor/joomla/filesystem/src/Stream/String.php
  libraries/vendor/joomla/filesystem/src/Stream/StringWrapper.php
  libraries/vendor/joomla/filesystem/src/Support/StringController.php
  libraries/vendor/joomla/filter/src/InputFilter.php
  libraries/vendor/joomla/filter/src/OutputFilter.php
  libraries/vendor/joomla/registry/src/AbstractRegistryFormat.php
  libraries/vendor/joomla/registry/src/Factory.php
  libraries/vendor/joomla/registry/src/Format/Ini.php
  libraries/vendor/joomla/registry/src/Format/Json.php
  libraries/vendor/joomla/registry/src/Format/Php.php
  libraries/vendor/joomla/registry/src/Format/Xml.php
  libraries/vendor/joomla/registry/src/Format/Yaml.php
  libraries/vendor/joomla/registry/src/FormatInterface.php
  libraries/vendor/joomla/registry/src/Registry.php
  libraries/vendor/joomla/string/src/Inflector.php
  libraries/vendor/joomla/string/src/Normalise.php
  libraries/vendor/joomla/string/src/String.php
  libraries/vendor/joomla/string/src/StringHelper.php
  libraries/vendor/joomla/string/src/phputf8/utils/unicode.php
  libraries/vendor/psr/log/Psr/Log/LoggerInterface.php
  libraries/vendor/symfony/polyfill-ctype/bootstrap.php
  libraries/vendor/symfony/polyfill-php55/Php55.php
  libraries/vendor/symfony/polyfill-php55/bootstrap.php
  libraries/vendor/symfony/polyfill-php56/bootstrap.php
  libraries/vendor/symfony/polyfill-php71/bootstrap.php
  libraries/vendor/symfony/polyfill-php73/bootstrap.php
  libraries/vendor/typo3/phar-stream-wrapper/composer.json
  libraries/vendor/typo3/phar-stream-wrapper/src/Helper.php
Labels: Composer Dependency Changed, PR-staging

#30797 [4.0-dev] Add css style for mod_articles_news vertical layout
  build/media_source/mod_articles_news/css/template-vert.css
  modules/mod_articles_news/tmpl/vertical.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30842 [4.0] delete a duplicate string in com_mails
  administrator/language/en-GB/com_mails.ini
Labels: RTC

#30837 [4.0] hidden-xs-up
  components/com_content/tmpl/category/default_articles.php
Labels: PR-4.0-dev, RTC

#30806 Fixed version history modals.
  administrator/templates/isis/html/layouts/joomla/toolbar/versions.php
  media/com_contenthistory/js/admin-history-versions.js
Labels: PR-staging, RTC

#30825 [4.0] tinmyce toolbar icons
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
Labels: PR-4.0-dev, RTC

#30419 [3.x] clean cache after enabling 2fa in postinstall
  plugins/twofactorauth/totp/postinstall/actions.php
Labels: PR-staging, RTC

#30810 [4.0] Language reinstall
  administrator/components/com_installer/tmpl/languages/default.php
Labels: PR-4.0-dev, RTC

#30824 [4.0] Article Links markup
  components/com_content/tmpl/article/default_links.php
Labels: PR-4.0-dev, RTC

#30813 [4.0] Site Contacts Category List Search Filters
  build/media_source/com_contact/joomla.asset.json
  components/com_contact/tmpl/category/default_items.php
  language/en-GB/com_contact.ini
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#30859 [4.0] Missing js file in #30813
  build/media_source/com_contact/js/contacts-list.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#30701 [4.0] Don't use the "id" column as criterion in WHERE clauses for updating menu items in update SQL scripts
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-05-05.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-22.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-05-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-09-22.sql
Labels: PR-4.0-dev, RTC

#30867 [4.0] Update lib_joomla.ini
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: Language Change, PR-4.0-dev

#30852 [4.0] com_media options
  administrator/components/com_media/config.xml
  administrator/language/en-GB/com_media.ini
Labels: PR-4.0-dev, RTC

#30849 [4.0] joomla update show password
  administrator/components/com_joomlaupdate/tmpl/upload/captive.php
Labels: PR-4.0-dev, RTC

#30857 [4.0] Fall back to system template when template file not found
  libraries/src/Document/HtmlDocument.php
Labels: PR-4.0-dev, RTC

#30865 [4.0] Use namespaced classes in typehints
  administrator/components/com_installer/src/Table/UpdatesiteTable.php
  libraries/src/Adapter/AdapterInstance.php
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-4.0-dev, RTC

#30847 [4.0] Templates: Styles (Administrator) menu color changes on save
  administrator/templates/atum/templateDetails.xml
Labels: PR-4.0-dev, RTC

#30892 [4.0] xtd-editor button for module
  plugins/editors-xtd/module/module.php
Labels: PR-4.0-dev, RTC

#30889 [4.0] Fix pagebreak modal missing style
  administrator/components/com_content/tmpl/article/pagebreak.php
Labels: PR-4.0-dev, RTC

#30854 [4.0] treeselect alerts
  administrator/components/com_menus/tmpl/item/edit_container.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
Labels: PR-4.0-dev, RTC

#30853 [4.0] sticky sidebar menu
  administrator/templates/atum/index.php
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev, RTC

#30851 [4.0] Media Manager close preview
  administrator/components/com_media/resources/scripts/components/modals/modal.vue
  administrator/components/com_media/resources/styles/components/_media-modal.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30845 [4.1] Add prebuilt packages for 4.1-dev
  .drone.yml
Labels: PR-4.1-dev, Unit/System Tests, hacktoberfest-accepted

#30850 Link to a field outside of any group (showon)
  libraries/src/Form/FormHelper.php
Labels: PR-staging, RTC

#30915 Revert "Link to a field outside of any group (showon)"
  libraries/src/Form/FormHelper.php
Labels: PR-staging

#30890 [4.0] size of the template name font in module position selector
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
  templates/cassiopeia/scss/vendor/choicesjs/choices.scss
Labels: NPM Resource Changed, PR-4.0-dev

#30909 [4] Add generic AJAX error message translation
  administrator/templates/atum/login.php
Labels: PR-4.0-dev, RTC, hacktoberfest-accepted

#30870 [4.0] media manager transparent preview
  administrator/components/com_media/resources/scripts/components/modals/preview-modal.vue
Labels: PR-4.0-dev, RTC

#30901 Joomla\CMS\Installation\Helper\ArrayHelper not found
  installation/src/Helper/DatabaseHelper.php
Labels: PR-4.0-dev, RTC

#30902 [4.0] Make sure hsts is only added on https sites
  plugins/system/httpheaders/httpheaders.php
Labels: PR-4.0-dev, RTC

#30846 [4.0] resize webauthn logo
  build/media_source/plg_system_webauthn/images/webauthn-black.png
  build/media_source/plg_system_webauthn/images/webauthn-color.png
  build/media_source/plg_system_webauthn/images/webauthn-white.png
Labels: NPM Resource Changed, PR-4.0-dev

#30935 [4.0] Button text double translation
  administrator/components/com_content/src/View/Article/HtmlView.php
Labels: PR-4.0-dev, RTC

#30712 Change all JHELP value strings in jooml.ini
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#30946 typo in ArticlesNewsHelper.php
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
Labels: PR-4.0-dev

#30868 [4.0] Normalise Featured Contact List
  components/com_contact/src/Model/FeaturedModel.php
  components/com_contact/tmpl/featured/default.xml
  components/com_contact/tmpl/featured/default_items.php
  language/en-GB/com_contact.ini
Labels: Language Change, PR-4.0-dev, RTC

#30879 [4.0] yubikey text
  administrator/language/en-GB/plg_twofactorauth_yubikey.ini
Labels: PR-4.0-dev, RTC

#30981 [4.0] Frontend List articles in a category: adding Clear filter, refactoring layout for a11y+
  build/media_source/com_content/joomla.asset.json
  build/media_source/com_content/js/articles-list.es6.js
  components/com_content/tmpl/category/default_articles.php
Labels: PR-4.0-dev, RTC

#30984 [4.0] Frontend: Normalise List contacts
  components/com_contact/tmpl/category/default_items.php
Labels: PR-4.0-dev, RTC

#30904 [4.0] Frontend: Fix List Contacts Category List Limit
  administrator/components/com_contact/config.xml
  administrator/language/en-GB/com_contact.ini
  components/com_contact/src/Model/CategoryModel.php
  components/com_contact/tmpl/category/default.xml
Labels: Language Change, PR-4.0-dev, RTC

#30987 [4.0] Remove None Selected option in FileSystem
  plugins/filesystem/local/local.xml
Labels: PR-4.0-dev, RTC

#30941 [4.0] Add update SQL to delete plg_authentication_gmail from extensions table
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-27.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-09-27.sql
Labels: PR-4.0-dev, RTC

#30907 [4.0] Small refactor of typehint check in CMSPlugin
  libraries/src/Plugin/CMSPlugin.php
Labels: PR-4.0-dev, RTC

#30989 Do not package .drone.jsonnet
  build/build.php
Labels: PR-staging

#31002 Fix markup in com_admin profile view
  administrator/components/com_admin/views/profile/tmpl/edit.php
Labels: PR-staging, RTC

#30999 [4.0] Ooops: frontend contacts layouts `filter-field` correction
  components/com_contact/tmpl/category/default_items.php
  components/com_contact/tmpl/featured/default_items.php
Labels: PR-4.0-dev, RTC

#30917 [4.0] Fix media manage console error
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
Labels: NPM Resource Changed, PR-4.0-dev

#31006 [4] Remove Unnecessary Local Variable
  api/components/com_languages/src/Controller/OverridesController.php
Labels: PR-4.0-dev

#30990 [4.0] codemirror height
  administrator/components/com_templates/forms/source.xml
  plugins/editors/codemirror/layouts/editors/codemirror/styles.php
Labels: PR-4.0-dev, RTC

#31016 Validate redirect header code
  administrator/components/com_redirect/models/forms/link.xml
Labels: PR-4.0-dev, RTC

#31018 [4.0] Correct @deprecated version
  libraries/src/Application/ConsoleApplication.php
Labels: PR-4.0-dev, RTC

#31019 [4.0] Update comment
  libraries/src/Plugin/CMSPlugin.php
Labels: PR-4.0-dev, RTC

#31029 [4.0] template editor tree
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC

#31022 [4.0] Increase right margin
  administrator/components/com_templates/tmpl/template/default_description.php
Labels: PR-4.0-dev, RTC

#31015 [4.0] Missing field class
  administrator/components/com_redirect/forms/link.xml
Labels: PR-4.0-dev, RTC

#30993 [4.0] Remove hover effect from com_cpanel card, make your eyes happy
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: PR-4.0-dev, RTC

#30977 Transparency lost when cropping/resizing images
  administrator/components/com_templates/models/template.php
Labels: PR-staging, RTC

#31055 Remove unnecessary semicolon
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev

#31053 Update TinyMCE Links to documentation
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev

#30983 [4.0] Prioritise /tmpl component folder for menu items .xml definitions and componentlayout field
  administrator/components/com_menus/src/Model/ItemModel.php
  libraries/src/Form/Field/ComponentlayoutField.php
Labels: PR-4.0-dev, RTC

#31062 [4] s/alised/aliased
  cli/joomla.php
Labels: PR-4.0-dev

#31059 [4] Return value type is not compatible with declared type in doc
  modules/mod_syndicate/src/Helper/SyndicateHelper.php
Labels: PR-4.0-dev

#31069 s/Santize/Sanitize
  libraries/src/Table/Table.php
Labels: PR-4.0-dev

#31070 [4] remove three unneeded semicolons
  administrator/components/com_joomlaupdate/restore.php
  administrator/components/com_users/tmpl/users/default.php
  layouts/joomla/form/field/radio/buttons.php
Labels: PR-4.0-dev

#31072 [4] Return is unnecessary as the last statement in a void method
  administrator/components/com_associations/src/Controller/AssociationsController.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Controller/FieldController.php
  administrator/components/com_fields/src/Controller/GroupController.php
  administrator/components/com_login/src/Controller/DisplayController.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_users/src/Controller/UserController.php
  libraries/src/Access/Rules.php
  libraries/src/Feed/Parser/Rss/ItunesRssParser.php
  libraries/src/Feed/Parser/Rss/MediaRssParser.php
  libraries/src/HTML/Helpers/Behavior.php
  libraries/src/HTML/Helpers/Dropdown.php
  libraries/src/HTML/Helpers/Jquery.php
  libraries/src/Image/Filter/Backgroundfill.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/Utility/BufferStreamHandler.php
Labels: PR-4.0-dev

#30873 [4.0] ATUM prefers-reduced-motion [a11y]
  administrator/templates/atum/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31054 Added Mail template Help strings
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_mails/src/View/Templates/HtmlView.php
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: PR-4.0-dev, RTC

#31047 [4.0] Ignore missing template description
  administrator/components/com_templates/tmpl/template/default_description.php
Labels: PR-4.0-dev, RTC

#31064 [4] fix obviously wrong docs
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/templates/atum/Service/HTML/Atum.php
  libraries/src/Cache/Cache.php
  plugins/twofactorauth/yubikey/yubikey.php
Labels: PR-4.0-dev, RTC

#31071 [4] Ternary Expression can be safely replaced with condition removing codesmell
  administrator/components/com_associations/layouts/joomla/searchtools/default.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_menus/layouts/joomla/searchtools/default.php
  administrator/components/com_menus/src/Model/ItemModel.php
  layouts/joomla/searchtools/default.php
  libraries/bootstrap.php
  libraries/src/Cache/Cache.php
  libraries/src/Filesystem/File.php
  libraries/src/Form/Filter/RulesFilter.php
  libraries/src/Form/FormField.php
  libraries/src/Mail/Mail.php
  libraries/src/Microdata/Microdata.php
  plugins/content/emailcloak/emailcloak.php
Labels: PR-4.0-dev, RTC

#30998 [4.0] Frontend: correcting Tags layouts
  components/com_tags/tmpl/tag/default_items.php
  components/com_tags/tmpl/tag/list.xml
  components/com_tags/tmpl/tag/list_items.php
  components/com_tags/tmpl/tags/default_items.php
  language/en-GB/com_tags.ini
Labels: Language Change, PR-4.0-dev, RTC

#31093 [4.0] Fix Tags Compact list bug
  components/com_tags/tmpl/tag/list_items.php
Labels: RTC

#31097 [4.0] Expired content shown in tag view
  libraries/src/Helper/TagsHelper.php
Labels: RTC

#30985 [4.0] Replace old contact icons by icons
  administrator/components/com_contact/config.xml
  administrator/language/en-GB/com_contact.ini
  build/media_source/contacts/images/con_address.png
  build/media_source/contacts/images/con_fax.png
  build/media_source/contacts/images/con_info.png
  build/media_source/contacts/images/con_mobile.png
  build/media_source/contacts/images/con_tel.png
  build/media_source/contacts/images/emailButton.png
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/contact/default_address.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#31030 [4.0] Extra space cpanel tables
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: PR-4.0-dev, RTC

#31081 [4] add missing import for exception
  api/components/com_plugins/src/Controller/PluginsController.php
Labels: PR-4.0-dev, RTC

#31080 [4.0] Move calls out of the loop
  libraries/src/Image/Image.php
Labels: PR-4.0-dev, RTC

#31066 [4] Variable key is used in both the inner and outer foreach loops
  libraries/src/Console/GetConfigurationCommand.php
Labels: PR-4.0-dev, RTC

#31061 [4] Return value type is not compatible with declared
  installation/src/Model/ConfigurationModel.php
Labels: PR-4.0-dev, RTC

#31040 [4.0] Non-empty, non-matching searches shouldn't return anything
  components/com_finder/src/Model/SearchModel.php
Labels: PR-4.0-dev, RTC

#31060 [4] Update PHPDoc comment to match method signatures in installation app
  installation/src/Application/InstallationApplication.php
  installation/src/Controller/InstallationController.php
  installation/src/Form/Field/Installation/LanguageField.php
  installation/src/Form/Rule/UsernameRule.php
  installation/src/Model/BaseInstallationModel.php
  installation/src/Model/ChecksModel.php
  installation/src/Model/LanguagesModel.php
  installation/src/Model/SetupModel.php
  installation/src/View/DefaultView.php
  installation/src/View/Preinstall/HtmlView.php
  installation/src/View/Remove/HtmlView.php
  installation/template/message.php
Labels: PR-4.0-dev, RTC

#30855 [4.0] Share image link
  administrator/templates/atum/scss/blocks/_form.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31057 [4] Remove unused array - Array is only updated, but never queried
  plugins/sampledata/testing/testing.php
Labels: PR-4.0-dev, RTC

#30986 [4.0] Correcting addInline() to support WebAssetItemInterface and String, as planned
  libraries/src/WebAsset/WebAssetManager.php
Labels: PR-4.0-dev, RTC

#30779 [4.0] Fixed frontend module editing for non-superusers.
  components/com_config/src/Dispatcher/Dispatcher.php
Labels: PR-4.0-dev, RTC

#31102 [4.0] Fix paths
  .github/CODEOWNERS
Labels: PR-4.0-dev, RTC

#31007 Remove unused namespace declaration
  build/warning_page/template.html
Labels: PR-4.0-dev

#31073 [4.0] Fixing "expand all" for com_finder in filter
  build/media_source/com_finder/js/finder-edit.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#31051 [4] Return is unnecessary as the last statement in a void method
  plugins/content/emailcloak/emailcloak.php
  plugins/system/redirect/redirect.php
  plugins/workflow/featuring/featuring.php
  plugins/workflow/publishing/publishing.php
Labels: PR-4.0-dev

#31107 [4.0] Fix retrieving articles for contact
  components/com_contact/src/Model/ContactModel.php
Labels: PR-4.0-dev, RTC

#31058 [4] Cleanup of switch statements to remove code smell & adhere to code style guidelines
  administrator/components/com_finder/src/Indexer/Adapter.php
  administrator/components/com_installer/src/Model/InstallModel.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  components/com_ajax/ajax.php
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_content/src/Helper/QueryHelper.php
  components/com_content/tmpl/category/default_articles.php
  components/com_finder/src/Model/SearchModel.php
  components/com_tags/src/Model/TagModel.php
  components/com_users/src/Controller/DisplayController.php
  modules/mod_articles_category/mod_articles_category.php
  modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
  modules/mod_articles_latest/src/Helper/ArticlesLatestHelper.php
  plugins/content/confirmconsent/src/Field/ConsentBoxField.php
  plugins/content/pagenavigation/pagenavigation.php
  plugins/system/debug/debug.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandler.php
Labels: PR-4.0-dev

#31095 [4.0] Hide gear icon since no toolbar to display
  administrator/components/com_admin/tmpl/help/default.php
  administrator/templates/atum/index.php
Labels: PR-4.0-dev, RTC

#31074 [4.0] Take off the Trash dropdown Action when filtering by trashed items
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_content/src/View/Featured/HtmlView.php
  administrator/components/com_fields/src/View/Fields/HtmlView.php
  administrator/components/com_fields/src/View/Groups/HtmlView.php
  administrator/components/com_tags/src/View/Tags/HtmlView.php
Labels: PR-4.0-dev, RTC

#31048 [4.0] Add WebP support to Image library
  libraries/src/Image/Image.php
  tests/Unit/Libraries/Cms/Image/ImageTest.php
  tests/Unit/Libraries/Cms/Image/stubs/koala.webp
Labels: PR-4.0-dev, RTC, Unit/System Tests

#30823 [4.0] blog intro image
  administrator/components/com_content/config.xml
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/featured/default.xml
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  layouts/joomla/content/intro_image.php
Labels: Documentation Required, Language Change, PR-4.0-dev, RTC

#30262 [4.0] [a11y] add sr-only text to first column of table head
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
  installation/tmpl/remove/default.php
Labels: Language Change, PR-4.0-dev, RTC

#30317 [4.0] Fix debug logging. Move logging to application
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/application/default_logging.php
  administrator/components/com_config/tmpl/application/default_logging_custom.php
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/plg_system_debug.ini
  libraries/src/Application/CMSApplication.php
  libraries/src/Log/Logger/InMemoryLogger.php
  libraries/src/Log/LoggerRegistry.php
  plugins/system/debug/debug.php
  plugins/system/debug/debug.xml
Labels: Documentation Required, Language Change, PR-4.0-dev, RTC, Release Blocker

#29024 [4.0] Option to use a menu item for privacy policy.
  administrator/language/en-GB/plg_content_confirmconsent.ini
  administrator/language/en-GB/plg_system_privacyconsent.ini
  layouts/plugins/system/privacyconsent/label.php
  plugins/content/confirmconsent/confirmconsent.php
  plugins/content/confirmconsent/confirmconsent.xml
  plugins/content/confirmconsent/src/Field/ConsentBoxField.php
  plugins/system/privacyconsent/privacyconsent.php
  plugins/system/privacyconsent/privacyconsent.xml
  plugins/system/privacyconsent/src/Field/PrivacyField.php
Labels: Language Change, PR-4.0-dev, RTC

#30945 [4.0] Fix duplicate "Sample Data - Multilingual" plugin in database on 4.0 sites which have been updated from 3.10
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-11.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-27.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-11.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-09-27.sql
Labels: PR-4.0-dev, RTC

#30949 [4] Bunch of docblock updates
  administrator/components/com_categories/src/Controller/CategoryController.php
  administrator/components/com_categories/src/Controller/DisplayController.php
  administrator/components/com_categories/src/Field/CategoryeditField.php
  administrator/components/com_categories/src/Helper/CategoryAssociationHelper.php
  administrator/components/com_categories/src/Model/CategoriesModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_categories/src/Table/CategoryTable.php
  administrator/components/com_categories/src/View/Categories/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
Labels: PR-4.0-dev, hacktoberfest-accepted

#31108 [4.0] Update HTML error pages
  templates/system/build_incomplete.html
  templates/system/incompatible.html
Labels: PR-4.0-dev

#31118 [4.0] Fix broken post install message display when not using Joomla! core
  administrator/components/com_postinstall/src/Model/MessagesModel.php
Labels: PR-4.0-dev

#31119 [4.0] Fix broken B/C layer for event triggering in workflow plugins
  plugins/workflow/featuring/featuring.php
  plugins/workflow/publishing/publishing.php
Labels: PR-4.0-dev

#29979 [4.x] - com_finder doesn't stop indexing on CSRF token mismatch
  administrator/components/com_finder/src/Controller/IndexerController.php
  administrator/components/com_finder/src/Response/Response.php
  build/media_source/com_finder/js/indexer.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, Release Blocker, Updates Requested

#31068 [4] use integer in sql
  administrator/components/com_content/src/Model/ArticlesModel.php
Labels: PR-4.0-dev, RTC

#31049 [4] Second condition is always 'true' because 'is_object($data)'
  plugins/system/webauthn/src/PluginTraits/UserProfileFields.php
Labels: PR-4.0-dev

#31123 [4.0] Global strings for readmore layout
  language/en-GB/joomla.ini
  layouts/joomla/content/readmore.php
Labels: Language Change, PR-4.0-dev

#31041 [4.0] Categories need to have a route to be indexed
  plugins/finder/categories/categories.php
Labels: PR-4.0-dev, RTC

#30866 [4.0] Fix rehashing passwords
  libraries/src/User/UserHelper.php
Labels: PR-4.0-dev

#29573 [4.0] Add a sample workflow to blog sample data
  administrator/language/en-GB/plg_sampledata_blog.ini
  plugins/sampledata/blog/blog.php
Labels: Language Change, PR-4.0-dev, Updates Requested

#31017 [4.0] Replace com_content 'Image Float' with 'Image Class
  administrator/components/com_content/config.xml
  administrator/components/com_content/forms/article.xml
  administrator/language/en-GB/com_content.ini
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
  templates/cassiopeia/scss/blocks/_legacy.scss
  templates/cassiopeia/scss/template.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#31131 [4.0] missing upper case table
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#30882 Make authorization header case insensitive in API
  plugins/api-authentication/token/token.php
Labels: PR-4.0-dev

#30979 Undefined constant on PHP 5.3
  administrator/components/com_templates/views/template/tmpl/default_tree.php
Labels: PR-staging, RTC

#31105 [4.0] Component configuration deleted on failed validation
  administrator/components/com_config/src/Controller/ComponentController.php
  administrator/components/com_config/src/Model/ComponentModel.php
  administrator/components/com_config/src/View/Component/HtmlView.php
Labels: PR-4.0-dev, RTC

#31099 [4.0] Finder pagination
  components/com_finder/src/Model/SearchModel.php
  components/com_finder/tmpl/search/default.xml
Labels: PR-4.0-dev

#31092 Added height control and v-scroll to com_admin sidebars
  administrator/components/com_admin/tmpl/help/default.php
  administrator/components/com_config/tmpl/component/default.php
  administrator/templates/atum/scss/blocks/_sidebar-nav.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29571 [4.0] Remove AJAX for login
  administrator/components/com_login/src/Controller/DisplayController.php
  administrator/modules/mod_login/tmpl/default.php
  build/media_source/mod_login/js/admin-login.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31037 [4.0 dev] Correct the layout of the modals in "Manage Folders" and "New File" in Template manager.
  administrator/components/com_templates/tmpl/template/default.php
  administrator/components/com_templates/tmpl/template/default_modal_file_body.php
  administrator/components/com_templates/tmpl/template/default_modal_folder_body.php
  build/media_source/com_templates/css/admin-templates-default.css
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31146 [4.0] Cleanup jstools
  .drone.yml
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/modals/modal.vue
  build/.eslintrc
  build/.stylelintrc.json
  build/build.js
  build/media_source/com_media/js/edit-images.es6.js
  drone-package.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev, Unit/System Tests

#31152 [4.0] Add dashboard module
  administrator/components/com_cpanel/tmpl/cpanel/default.php
Labels: PR-4.0-dev

#31028 [4.0] move icon to block
  administrator/templates/atum/images/logos/login.svg
  build/media_source/plg_system_webauthn/images/webauthn-black.png
  build/media_source/plg_system_webauthn/images/webauthn-black.svg
  build/media_source/plg_system_webauthn/images/webauthn-color.png
  build/media_source/plg_system_webauthn/images/webauthn-white.png
  build/media_source/plg_system_webauthn/images/webauthn-white.svg
  build/media_source/plg_system_webauthn/scss/button.scss
  plugins/system/webauthn/src/PluginTraits/AdditionalLoginButtons.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31145 [4.0] Backend: use default bootstrap tabs styling for .nav-tabs
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/template.scss
  administrator/templates/atum/scss/vendor/bootstrap/_nav.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31129 [4.0] JS: Users Field: init Bootstrap Modal
  build/media_source/system/js/fields/joomla-field-user.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31164 [4.0] Fix wrong line break in params value in postgresql/base.sql caused by PR #30823
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#31163 [4.0] Replace com_content 'Image Float' with 'Image Class'
  administrator/language/en-GB/com_content.ini
  components/com_content/forms/article.xml
  language/en-GB/com_content.ini
Labels: PR-4.0-dev, RTC

#31177 [4.0] Remove unused language files
  administrator/language/en-GB/plg_fields_image.ini
  administrator/language/en-GB/plg_fields_image.sys.ini
Labels: RTC

#31169 [4.0] Add type attribute to button
  administrator/modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31171 [4.0] Fix MySQL error 1093 caused by my PR #30945 when updating to latest 4.0-dev or 4.0 nightly
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-27.sql
Labels: PR-4.0-dev

#31158 [4.0] More cleanup on the jstools
  .eslintignore
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-module-order.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-permissions.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-send-test-mail.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#31121 [4.0] Fix undefined error when invalid redis cache host
  libraries/src/Cache/Storage/RedisStorage.php
Labels: PR-4.0-dev, RTC

#30760 [4.0] wrap message container output in an array and implode it so it prevents obsolete spaces
  layouts/joomla/system/message.php
Labels: PR-4.0-dev

#31175 Set alt="" for images in the random image module
  modules/mod_random_image/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31156 [4.0] Active menu does not exist, fatal error
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#31197 [4.0] Lint .es6 files
  build/media_source/system/js/core.es6/form.es6
  build/media_source/system/js/core.es6/message.es6
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#31182 Update checksum not validated when in different character case
  libraries/src/Installer/InstallerHelper.php
Labels: PR-staging, RTC

#31195 [4.0] House cleaning => remove obsolete div element in system message container
  build/media_source/system/css/system.css
  build/media_source/system/images/notice-alert.png
  build/media_source/system/images/notice-download.png
  build/media_source/system/images/notice-info.png
  build/media_source/system/images/notice-note.png
  layouts/joomla/system/message.php
  templates/system/css/offline.css
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31189 [4.0] Fix error on System Information page
  administrator/components/com_admin/src/Extension/AdminComponent.php
  administrator/components/com_admin/src/Service/HTML/Configuration.php
  administrator/components/com_admin/tmpl/sysinfo/default_config.php
Labels: PR-4.0-dev, RTC

#31198 [4.0] Remove unused file
  build/media_source/system/scss/_jalert.scss
Labels: PR-4.0-dev, RTC

#31216 Delete .drone.jsonnet on update
  administrator/components/com_admin/script.php
Labels: PR-staging

#31213 [4.0] [NO CACHE] Fix js console error
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#31116 [4.0] Cleaning up Drone configuration
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#31215 [4.0] Reset, Remind, Register
  modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31214 [4.0] WebAsset exceptions
  libraries/src/WebAsset/WebAssetManager.php
Labels: PR-4.0-dev

#31222 remove 3.9 files from 4
  administrator/components/com_admin/sql/updates/postgresql/3.9.15-2020-01-08.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.19-2020-06-01.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.9.19-2020-06-01.sql
Labels: PR-4.0-dev

#31224 [4.0] One more 3.9 file to be deleted: mysql/3.9.19-2020-06-01.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.19-2020-06-01.sql
Labels: PR-4.0-dev

#31217 [4.0] Admin display password requirements
  administrator/components/com_admin/forms/profile.xml
  administrator/components/com_users/forms/user.xml
Labels: PR-4.0-dev, RTC

#31225 Set composer version to 1 on appveyor
  .appveyor.yml
Labels: PR-4.0-dev, Unit/System Tests

#30770 [4.0] Written by
  language/en-GB/com_content.ini
Labels: Language Change, PR-4.0-dev, RTC

#31170 Remove reference to Media manager in Imagelist Custom Field
  administrator/language/en-GB/en-GB.plg_fields_imagelist.ini
Labels: Language Change, PR-staging, RTC
