Repository joomla/joomla-cms, pull requests merged in 2020-11, with the labels that each got.

#31137 [4.0] Use component when building session key
  administrator/components/com_config/src/Controller/ComponentController.php
  administrator/components/com_config/src/Model/ComponentModel.php
Labels: PR-4.0-dev, RTC

#30054 [4.0] Flush the opcache on extension install to ensure consistency
  libraries/src/Installer/Installer.php
Labels: PR-4.0-dev

#31289 Use random filenames for image tests
  tests/Unit/Libraries/Cms/Image/ImageTest.php
Labels: PR-4.0-dev, Unit/System Tests

#31295 Revert incorrectly changed files in #30778
  .github/SECURITY.md
Labels: PR-staging

#31236 [4.x] Only allow POST requests for admin login
  administrator/components/com_login/src/Controller/DisplayController.php
Labels: PR-4.0-dev

#31287 Log that PDF Fonts in language packs are deprecated and will be removed in 4.0
  libraries/src/Installer/Adapter/LanguageAdapter.php
Labels: PR-staging, RTC

#31288 Remove pdf_fonts handling for language installer
  libraries/src/Installer/Adapter/LanguageAdapter.php
Labels: PR-4.0-dev, RTC

#31273 [4.0] Fix saving items without creation date
  administrator/components/com_banners/src/Table/BannerTable.php
  administrator/components/com_contact/src/Table/ContactTable.php
  administrator/components/com_fields/src/Table/FieldTable.php
  administrator/components/com_fields/src/Table/GroupTable.php
  administrator/components/com_finder/src/Table/FilterTable.php
  administrator/components/com_newsfeeds/src/Table/NewsfeedTable.php
  libraries/src/Table/Category.php
  libraries/src/Table/Content.php
Labels: PR-4.0-dev, RTC

#31201 [4.0] Don't ship .es6 files
  build/build-modules-js/init.es6.js
Labels: PR-4.0-dev, RTC

#31280 [4.0] NPM package update
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31301 [4.0] br
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: RTC

#31181 [4.0] Rename method arguments to use camelCase casing
  administrator/components/com_content/src/Helper/ContentHelper.php
  administrator/components/com_finder/src/Indexer/Language/El.php
  administrator/components/com_finder/src/Indexer/Taxonomy.php
  administrator/components/com_workflow/src/Model/StageModel.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
  api/components/com_contact/src/Controller/ContactController.php
  libraries/src/Encrypt/Aes.php
  libraries/src/MVC/Model/WorkflowBehaviorTrait.php
  libraries/src/MVC/Model/WorkflowModelInterface.php
  libraries/src/Mail/MailTemplate.php
  libraries/src/Versioning/VersionableModelTrait.php
  libraries/src/Workflow/Workflow.php
  libraries/src/Workflow/WorkflowPluginTrait.php
  plugins/content/joomla/joomla.php
  plugins/fields/subfields/subfields.php
  plugins/sampledata/multilang/multilang.php
Labels: PR-4.0-dev, RTC

#31279 [4.0] Composer packages update
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/modules/mod_login/tmpl/default.php
  components/com_newsfeeds/tmpl/newsfeed/default.php
  components/com_users/tmpl/login/default_login.php
  composer.lock
  modules/mod_login/tmpl/default.php
Labels: Composer Dependency Changed, PR-4.0-dev, RTC

#31307 [4.0] Fix undefined variable notice
  administrator/components/com_config/src/Controller/ComponentController.php
Labels: PR-4.0-dev, RTC

#31303 [4.0] Remove redundant id attribute
  administrator/components/com_banners/config.xml
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_contact/config.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/config.xml
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/forms/group.xml
  administrator/components/com_finder/forms/filter.xml
  administrator/components/com_menus/forms/item.xml
  administrator/components/com_menus/forms/itemadmin.xml
  administrator/components/com_menus/forms/menu.xml
  administrator/components/com_newsfeeds/config.xml
  administrator/components/com_redirect/forms/link.xml
  administrator/components/com_templates/forms/style.xml
  administrator/modules/mod_latest/mod_latest.xml
  administrator/modules/mod_popular/mod_popular.xml
  components/com_config/forms/templates.xml
  components/com_contact/forms/form.xml
  components/com_content/forms/article.xml
  components/com_newsfeeds/tmpl/categories/default.xml
  components/com_newsfeeds/tmpl/category/default.xml
  components/com_tags/tmpl/tag/list.xml
  installation/forms/language.xml
  installation/forms/preinstall.xml
  installation/forms/setup.xml
  plugins/user/profile/forms/profile.xml
Labels: PR-4.0-dev, RTC

#31302 [4.0] Validate access level fields
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_config/forms/application.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_content/tmpl/articles/default.xml
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/forms/group.xml
  administrator/components/com_languages/forms/language.xml
  administrator/components/com_menus/forms/item.xml
  administrator/components/com_modules/forms/module.xml
  administrator/components/com_modules/forms/moduleadmin.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_plugins/forms/plugin.xml
  administrator/components/com_tags/forms/tag.xml
  components/com_config/forms/config.xml
  components/com_config/forms/modules.xml
  components/com_contact/forms/form.xml
  components/com_content/forms/article.xml
Labels: PR-4.0-dev, RTC

#31290 [4.0] Move to Dart SASS
  administrator/templates/atum/scss/vendor/fontawesome-free/fontawesome.scss
  build/build-modules-js/javascript/compile-w-c.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/media_source/system/scss/_icomoon.scss
  package-lock.json
  package.json
  templates/cassiopeia/scss/_variables.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31315 Added JLIB_INSTALLER_DISCOVER_INSTALL
  administrator/language/en-GB/en-GB.lib_joomla.ini
  language/en-GB/en-GB.lib_joomla.ini
Labels: Language Change, PR-staging, RTC

#31321 [4.0] grammar corrections
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: RTC

#31274 [3] - same DDL for table #__contact_details
  administrator/components/com_contact/sql/install.mysql.utf8.sql
Labels: PR-staging, RTC

#31323 [4.0] Accessible media field ALt Text
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Form/Field/AccessiblemediaField.php
  plugins/fields/media/tmpl/media.php
Labels: Language Change, PR-4.0-dev, RTC

#31318 [4.0] Intro and Full image accessibility
  administrator/components/com_content/forms/article.xml
  administrator/language/en-GB/com_content.ini
  components/com_content/forms/article.xml
  components/com_content/tmpl/form/edit.php
  language/en-GB/com_content.ini
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
Labels: Language Change, PR-4.0-dev, RTC

#31336 [4.0] Search tip com_menus
  administrator/components/com_menus/forms/filter_items.xml
Labels: RTC

#30113 [4.0] Remove mod_multilangstatus tampering from mod_user
  administrator/modules/mod_multilangstatus/mod_multilangstatus.php
  administrator/modules/mod_multilangstatus/mod_multilangstatus.xml
  administrator/modules/mod_multilangstatus/src/Helper/MultilangstatusAdminHelper.php
  administrator/modules/mod_multilangstatus/tmpl/default.php
  administrator/modules/mod_user/mod_user.php
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#31327 Update robots.txt.dist
  robots.txt.dist
Labels: RTC

#31358 Update en-GB.com_users.ini
  language/en-GB/en-GB.com_users.ini
Labels: Language Change, PR-staging, RTC

#31202 [4.0] "Authentification" correction
  administrator/language/en-GB/com_login.ini
  administrator/modules/mod_login/tmpl/default.php
  administrator/templates/atum/scss/blocks/_login.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#31310 [4.0] installer header
  installation/template/images/Joomla-brandmark-monochrome-white-RGB.svg
  installation/template/images/Joomla-logo-monochrome-horizontal-white.svg
  installation/template/images/logo-blue.svg
  installation/template/index.php
  installation/template/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31356 [4.0] Fix markup in color field
  layouts/joomla/form/field/color/advanced.php
Labels: PR-4.0-dev, RTC

#31333 [4.0] Accessibility Highlight Links Inconsistent
  administrator/modules/mod_messages/tmpl/default.php
Labels: PR-4.0-dev

#31366 [4.0] Fix custom fields in com_users
  administrator/components/com_users/src/Extension/UsersComponent.php
  administrator/components/com_users/src/Helper/UsersHelper.php
Labels: PR-4.0-dev, RTC

#31365 [4.0] Fix category select in field editing form
  administrator/components/com_categories/layouts/joomla/form/field/categoryedit.php
  administrator/components/com_fields/forms/field.xml
Labels: PR-4.0-dev, RTC

#31349 [4.0] Atum logo and login image alt [a11y]
  administrator/language/en-GB/tpl_atum.ini
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  administrator/templates/atum/templateDetails.xml
Labels: Language Change, PR-4.0-dev, RTC

#31283 [4.0] TinyMCE & Codemirror updates with new lineheight for tinymce
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  plugins/editors/codemirror/codemirror.xml
  plugins/editors/tinymce/tinymce.php
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31188 [4.0] Remove remaining PSR-0 code in JLoader
  libraries/loader.php
Labels: Documentation Required, PR-4.0-dev, RTC

#31363 [4.0] Select article etc button styling
  administrator/components/com_categories/src/Field/Modal/CategoryField.php
  administrator/components/com_contact/src/Field/Modal/ContactField.php
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_menus/src/Field/Modal/MenuField.php
  administrator/components/com_newsfeeds/src/Field/Modal/NewsfeedField.php
Labels: PR-4.0-dev, RTC

#31190 [4.0] Webauth inline SVG button with fill
  administrator/modules/mod_login/tmpl/default.php
  administrator/templates/atum/scss/blocks/_icons.scss
  build/media_source/plg_system_webauthn/images/webauthn-black.svg
  build/media_source/plg_system_webauthn/images/webauthn-white.svg
  build/media_source/plg_system_webauthn/images/webauthn.svg
  libraries/src/HTML/Helpers/Icons.php
  libraries/src/Helper/AuthenticationHelper.php
  modules/mod_login/tmpl/default.php
  plugins/system/webauthn/src/PluginTraits/AdditionalLoginButtons.php
  templates/cassiopeia/scss/blocks/_icons.scss
Labels: Documentation Required, NPM Resource Changed, PR-4.0-dev, RTC

#31389 [4.x] Tinmyce image decorative [a11y]
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev, RTC

#31390 [4.0] Finder pagination options
  components/com_finder/tmpl/search/default_results.php
Labels: PR-4.0-dev, RTC

#31393 [4.0] Smart search missing strings
  administrator/language/en-GB/com_finder.ini
Labels: PR-4.0-dev, RTC

#31128 [4.0]Make sure we do not add one header twice but we support to set a different header per client.
  plugins/system/httpheaders/httpheaders.php
Labels: PR-4.0-dev, RTC

#31155 [4.0] re-do temporary change of filter published-condition
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
Labels: PR-4.0-dev, RTC

#31211 [4.0] Deprecate unused $iconOver
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_cache/src/View/Cache/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_checkin/src/View/Checkin/HtmlView.php
  administrator/components/com_contact/src/View/Contact/HtmlView.php
  administrator/components/com_finder/src/View/Searches/HtmlView.php
  administrator/components/com_installer/src/View/Database/HtmlView.php
  administrator/components/com_installer/src/View/Discover/HtmlView.php
  administrator/components/com_installer/src/View/Update/HtmlView.php
  administrator/components/com_installer/src/View/Updatesites/HtmlView.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_languages/src/View/Installed/HtmlView.php
  administrator/components/com_languages/src/View/Overrides/HtmlView.php
  administrator/components/com_menus/src/View/Item/HtmlView.php
  administrator/components/com_menus/src/View/Menus/HtmlView.php
  administrator/components/com_messages/src/View/Message/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  administrator/components/com_templates/src/View/Styles/HtmlView.php
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_users/src/View/Mail/HtmlView.php
  libraries/src/MVC/View/ListView.php
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev, RTC

#31391 Mod submenu fix display of Components dashboard Dashboard icons
  administrator/modules/mod_submenu/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31372 [4.0] Enable hotkey support for accessibility plugin
  administrator/language/en-GB/plg_system_accessibility.ini
  administrator/language/en-GB/plg_system_accessibility.sys.ini
  plugins/system/accessibility/accessibility.php
Labels: Language Change, PR-4.0-dev, RTC

#31382 [4.0] Fixed titles for 3rd party component dashboards
  administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php
Labels: PR-4.0-dev, RTC

#31326 [4.0] Category ALT text
  administrator/components/com_categories/forms/category.xml
  administrator/language/en-GB/com_categories.ini
  components/com_content/tmpl/category/blog.php
  layouts/joomla/content/category_default.php
Labels: Language Change, PR-4.0-dev, RTC

#31373 [4.0] frontend articles category list improvements
  components/com_content/tmpl/category/default_articles.php
Labels: PR-4.0-dev, RTC

#31381 [4.0] Articles List Layout vote/ratings fields xml should not be switchers
  administrator/components/com_content/config.xml
  administrator/components/com_content/src/Field/VotelistField.php
  components/com_content/tmpl/category/default.xml
Labels: PR-4.0-dev, RTC

#30922 FoF and PHP 8
  libraries/fof/controller/controller.php
  libraries/fof/database/iterator.php
  libraries/fof/layout/helper.php
  libraries/fof/table/relations.php
Labels: PHP 8, PR-staging, RTC

#29353 fixes issue with type transformations
  libraries/src/Profiler/Profiler.php
Labels: Information Required, PHP 8, PR-staging, RTC

#30582 Remove duplicate minus sign in Profiler
  libraries/src/Profiler/Profiler.php
Labels: PHP 8, PR-staging, RTC

#30608 Fix call_user_func_array() arguments on PHP 8
  libraries/joomla/event/dispatcher.php
  libraries/joomla/event/event.php
Labels: PHP 8, PR-staging

#31246 Use ZipArchive in JArchiveZip
  libraries/joomla/archive/zip.php
Labels: PHP 8, PR-staging

#31394 [4.0] Disabled dropdown styling
  administrator/templates/atum/scss/vendor/bootstrap/_custom-forms.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30467 [4.0] Replace filter.condition by filter.published in com_content
  api/components/com_content/src/Controller/ArticlesController.php
  components/com_content/src/Model/ArchiveModel.php
  components/com_content/src/Model/ArticlesModel.php
  components/com_content/src/Model/CategoriesModel.php
  components/com_content/src/Model/CategoryModel.php
  components/com_content/src/Model/FeaturedModel.php
  modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
  modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
Labels: PR-4.0-dev, RTC

#31405 Fix reference by variables notice
  administrator/components/com_templates/models/template.php
Labels: RTC

#31406 [4.0] mod_privacy_status layout field class missing
  administrator/modules/mod_privacy_status/mod_privacy_status.xml
Labels: RTC

#31403 Remove unused import Closes #31383
  administrator/components/com_contact/models/contact.php
Labels: RTC

#30784 Images loading=lazy, part 2n
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/resources/scripts/components/browser/items/row.vue
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/plg_editors_tinymce.ini
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es6.js
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
  language/en-GB/joomla.ini
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
  layouts/joomla/editors/buttons/modal.php
  layouts/joomla/form/field/media.php
  libraries/src/HTML/HTMLHelper.php
  plugins/editors-xtd/image/image.php
  plugins/editors/tinymce/tinymce.php
  plugins/fields/imagelist/tmpl/imagelist.php
  plugins/fields/media/tmpl/media.php
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#31407 [4.0] scss stylint
  build/.stylelintrc.json
Labels: PR-4.0-dev, RTC

#31412 [3][com_contact] fix manifest
  administrator/components/com_contact/contact.xml
Labels: PR-staging, RTC

#31369 Make read more URLs absolute in feed
  components/com_content/views/category/view.feed.php
  components/com_content/views/featured/view.feed.php
Labels: PR-staging, RTC

#31299 Repalce `dirname(__FILE__)` with `__DIR__`
  plugins/system/actionlogs/actionlogs.php
Labels: PR-staging, RTC

#31426 [3.9] Missing lines JLIB_ when installing language packs
  installation/language/en-GB/en-GB.ini
Labels: Language Change, PR-staging

#31428 Update composer packages j/archive, j/string and j-backports/lessphp
  .drone.yml
  composer.json
  composer.lock
  libraries/vendor/bin/lessify
  libraries/vendor/bin/lessify.bat
  libraries/vendor/bin/plessc
  libraries/vendor/bin/plessc.bat
  libraries/vendor/composer/ClassLoader.php
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_real.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/archive/.drone.jsonnet
  libraries/vendor/joomla/archive/.drone.yml
  libraries/vendor/joomla/archive/src/Archive.php
  libraries/vendor/joomla/archive/src/Bzip2.php
  libraries/vendor/joomla/archive/src/Exception/UnknownArchiveException.php
  libraries/vendor/joomla/archive/src/Exception/UnsupportedArchiveException.php
  libraries/vendor/joomla/archive/src/ExtractableInterface.php
  libraries/vendor/joomla/archive/src/Gzip.php
  libraries/vendor/joomla/archive/src/Tar.php
  libraries/vendor/joomla/archive/src/Zip.php
  libraries/vendor/joomla/string/.drone.jsonnet
  libraries/vendor/joomla/string/.drone.yml
  libraries/vendor/joomla/string/src/phputf8/utils/bad.php
  libraries/vendor/leafo/lessphp/.drone.yml
  libraries/vendor/leafo/lessphp/LICENSE
  libraries/vendor/leafo/lessphp/lessc.inc.php
  libraries/vendor/leafo/lessphp/lessify
  libraries/vendor/leafo/lessphp/lessify.inc.php
  libraries/vendor/leafo/lessphp/phpunit.xml.dist
  libraries/vendor/leafo/lessphp/plessc
  libraries/vendor/leafo/lessphp/ruleset.xml
Labels: Composer Dependency Changed, PR-staging, Unit/System Tests

#31440 Cleanup unnecessary files
  .gitignore
  administrator/components/com_admin/script.php
  composer.lock
  libraries/vendor/bin/lessify
  libraries/vendor/bin/lessify.bat
  libraries/vendor/bin/plessc
  libraries/vendor/bin/plessc.bat
  libraries/vendor/composer/ClassLoader.php
  libraries/vendor/composer/autoload_real.php
  libraries/vendor/joomla/archive/.drone.jsonnet
  libraries/vendor/joomla/archive/.drone.yml
  libraries/vendor/joomla/string/.drone.jsonnet
  libraries/vendor/joomla/string/.drone.yml
  libraries/vendor/leafo/lessphp/.drone.yml
  libraries/vendor/leafo/lessphp/phpunit.xml.dist
  libraries/vendor/leafo/lessphp/ruleset.xml
Labels: Composer Dependency Changed, PR-staging, RTC

#31443 [4.0] Don't display hidden menu items at all.
  administrator/modules/mod_submenu/tmpl/default.php
Labels: PR-4.0-dev, RTC

#31451 [4.0] search ellipsis
  administrator/language/en-GB/com_media.ini
Labels: Language Change, PR-4.0-dev, RTC

#31444 Limit offset to max len in com_search
  administrator/components/com_search/helpers/search.php
Labels: PHP 8, PR-staging, RTC

#31434 [3][com_content] fix php8 Deprecated
  administrator/components/com_contact/helpers/html/contact.php
  administrator/components/com_content/helpers/html/contentadministrator.php
Labels: PHP 8, PR-staging

#31442 Fix "Uncaught ValueError: Path cannot be empty ..." in com_joomlaupdate restore.php
  administrator/components/com_joomlaupdate/restore.php
Labels: PHP 8, PR-staging, RTC

#31445 Use proper string comparison function for tag aliases
  libraries/joomla/form/fields/aliastag.php
Labels: PHP 8, PR-staging, RTC

#31447 Updated installation language files
  installation/language/da-DK/da-DK.ini
  installation/language/da-DK/da-DK.xml
  installation/language/fr-FR/fr-FR.ini
  installation/language/fr-FR/fr-FR.xml
  installation/language/hr-HR/hr-HR.ini
  installation/language/hr-HR/hr-HR.xml
  installation/language/nl-NL/nl-NL.ini
  installation/language/nl-NL/nl-NL.xml
  installation/language/sl-SI/sl-SI.ini
  installation/language/sl-SI/sl-SI.xml
  installation/language/sr-RS/sr-RS.ini
  installation/language/sr-RS/sr-RS.xml
  installation/language/sr-YU/sr-YU.ini
  installation/language/sr-YU/sr-YU.xml
  installation/language/sv-SE/sv-SE.ini
  installation/language/sv-SE/sv-SE.xml
  installation/language/sw-KE/sw-KE.ini
  installation/language/sw-KE/sw-KE.xml
  installation/language/ta-IN/ta-IN.ini
  installation/language/ta-IN/ta-IN.xml
Labels: Language Change, PR-staging

#31427 [4.0] media manager fix inconsistent select
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31354 [4.0] [Backend] In Banners: Clients details page Contact column is di…
  administrator/components/com_banners/src/Table/ClientTable.php
  administrator/language/en-GB/com_banners.ini
Labels: Language Change, PR-4.0-dev, RTC

#31462 updated german language files
  installation/language/de-AT/de-AT.ini
  installation/language/de-AT/de-AT.xml
  installation/language/de-CH/de-CH.ini
  installation/language/de-CH/de-CH.xml
  installation/language/de-DE/de-DE.ini
  installation/language/de-DE/de-DE.xml
  installation/language/de-LI/de-LI.ini
  installation/language/de-LI/de-LI.xml
  installation/language/de-LU/de-LU.ini
  installation/language/de-LU/de-LU.xml
Labels: Language Change, PR-staging

#31461 Updated installation language files
  installation/language/el-GR/el-GR.ini
  installation/language/el-GR/el-GR.xml
  installation/language/it-IT/it-IT.ini
  installation/language/it-IT/it-IT.xml
  installation/language/nb-NO/nb-NO.ini
  installation/language/nb-NO/nb-NO.xml
  installation/language/ru-RU/ru-RU.ini
  installation/language/ru-RU/ru-RU.xml
  installation/language/th-TH/th-TH.ini
  installation/language/th-TH/th-TH.xml
Labels: Language Change, PR-staging

#31464 [4.0] Revert ajax login message
  administrator/templates/atum/login.php
Labels: PR-4.0-dev, RTC

#31456 [4.0] Refactoring some lib_joomla language strings
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/MVC/Controller/AdminController.php
  libraries/src/MVC/Controller/ApiController.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Controller/FormController.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/BaseModel.php
  libraries/src/MVC/View/AbstractView.php
Labels: Language Change, PR-4.0-dev

#31469 [4.0] Ensure images are cleaned up after tests are run
  tests/Unit/Libraries/Cms/Image/ImageTest.php
Labels: PR-4.0-dev, Unit/System Tests

#31459 [4] Add missing validate="CssIdentifier" to blog_class_leading field
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/featured/default.xml
Labels: PR-4.0-dev, RTC

#31436 [4.0] SVG favicons
  administrator/templates/atum/component.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/images/favicon.ico
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  build/media_source/system/images/joomla-favicon-pinned.svg
  build/media_source/system/images/joomla-favicon.svg
  libraries/src/Document/HtmlDocument.php
  libraries/src/Document/Renderer/Html/MetasRenderer.php
  templates/cassiopeia/component.php
  templates/cassiopeia/error.php
  templates/cassiopeia/images/favicon.ico
  templates/cassiopeia/index.php
  templates/cassiopeia/offline.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#30819 Deprecate feature-policy and add the new Permissions Policy
  libraries/src/Application/WebApplication.php
Labels: PR-staging, RTC

#31476 Updated installation language files
  installation/language/en-AU/en-AU.ini
  installation/language/en-AU/en-AU.xml
  installation/language/en-CA/en-CA.ini
  installation/language/en-CA/en-CA.xml
  installation/language/en-NZ/en-NZ.ini
  installation/language/en-NZ/en-NZ.xml
  installation/language/en-US/en-US.ini
  installation/language/en-US/en-US.xml
Labels: Language Change, PR-staging

#31439 Removing unused contact field
  administrator/components/com_contact/models/forms/contact.xml
Labels: PR-staging, RTC

#31486 [3.x] URL Invalid
  libraries/src/Router/Router.php
Labels: PR-staging, RTC

#31494 [4.0] JText namespace
  administrator/components/com_installer/src/Model/InstallModel.php
  components/com_content/tmpl/article/default.php
  libraries/src/Table/Usergroup.php
Labels: PR-4.0-dev

#31493 [4.0] Pre-update check Codestyle
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
Labels: PR-4.0-dev

#31492 [4.0] Smart Search submenu
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/com_finder.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#31487 [4.0] Incorrect language constant in installation files
  installation/src/Helper/DatabaseHelper.php
  libraries/src/Console/SetConfigurationCommand.php
Labels: Language Change, PR-4.0-dev, RTC

#31474 [4.0] fix obsolete underlined whitespace in link
  administrator/components/com_menus/tmpl/items/modal.php
Labels: PR-4.0-dev, RTC

#31478 [4.0] blog sample data
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: Language Change, PR-4.0-dev, RTC

#31497 Updating Installation Language Files
  installation/language/bs-BA/bs-BA.ini
  installation/language/bs-BA/bs-BA.xml
  installation/language/ja-JP/ja-JP.ini
  installation/language/ja-JP/ja-JP.xml
Labels: Language Change, PR-staging

#31501 [4.0] Minimum Stability info
  administrator/components/com_installer/config.xml
  administrator/language/en-GB/com_installer.ini
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: PR-4.0-dev, RTC

#31503 [4.0] Information link -contrast [a11y]
  administrator/language/en-GB/com_installer.ini
Labels: PR-4.0-dev, RTC

#31510 Removing superfluous white space
  administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini
Labels: Language Change, PR-staging

#31480 Start reordering with 1 instead of 0
  build/media_source/system/js/draggable.es6.js
Labels: PR-4.0-dev, RTC

#31525 [4.0] Fix broken Joomla manifest and therefore broken Joomla Update check caused by recently merged PR #31504
  administrator/manifests/files/joomla.xml
Labels: PR-4.0-dev, Release Blocker

#31527 Save config and logging of selenium
  tests/Codeception/drone-system-run.sh
Labels: PR-4.0-dev, Unit/System Tests

#31529 [4.0] Fix system test
  tests/Codeception/drone-system-run.sh
Labels: PR-4.0-dev, Unit/System Tests

#31531 [4.0] Site title Cassiopeia
  language/en-GB/tpl_cassiopeia.ini
  templates/cassiopeia/templateDetails.xml
Labels: RTC

#31533 Fix bug in AJAX smart search with Cyrillic words (#31532)
  components/com_finder/models/suggestions.php
Labels: PR-staging, RTC

#31535 [4.0] Cassiopeia copyright dates
  templates/cassiopeia/component.php
  templates/cassiopeia/error.php
  templates/cassiopeia/js/template.js
  templates/cassiopeia/offline.php
Labels: PR-4.0-dev

#31400 [4.0] Fix subform default value filtering, and warning while string foreach()
  libraries/src/Form/Field/SubformField.php
Labels: PR-4.0-dev, RTC

#31432 [4.0] Do not create the Uri object again
  libraries/src/Router/Router.php
Labels: PR-4.0-dev, RTC

#30869 [4.0] media manager remove xs
  administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue
  administrator/components/com_media/resources/scripts/store/mutations.es6.js
  administrator/components/com_media/resources/styles/components/_media-browser.scss
  administrator/components/com_media/resources/styles/variables.scss
  tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31512 [4.0] Favicons fixes
  administrator/templates/atum/images/favicon.ico
  administrator/templates/atum/templateDetails.xml
  build/media_source/system/images/favicon.ico
  templates/cassiopeia/templateDetails.xml
Labels: PR-4.0-dev, RTC

#31511 [4.0] Fix for Lazyloading bad url
  libraries/src/HTML/HTMLHelper.php
  templates/cassiopeia/offline.php
Labels: PR-4.0-dev, RTC

#31454 [4.0] #29722 hidden recaptcha v2
  build/media_source/plg_captcha_recaptcha_invisible/scss/recaptcha_invisible.scss
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
Labels: PR-4.0-dev, RTC

#31536 [3]fix batch/copy on php 8
  administrator/components/com_categories/views/categories/tmpl/default_batch_body.php
  administrator/components/com_content/views/articles/tmpl/default_batch_body.php
  administrator/components/com_menus/views/items/tmpl/default_batch_body.php
  administrator/components/com_newsfeeds/views/newsfeeds/tmpl/default_batch_body.php
Labels: PHP 8, PR-staging, RTC

#31514 [31506] Solved performance issue with zip archives containing zip files
  composer.lock
  libraries/joomla/archive/zip.php
  libraries/vendor/joomla/archive/src/Zip.php
Labels: PR-staging, RTC
