Repository joomla/joomla-cms, pull requests merged in 2020-05, with the labels that each got.

#28894 [4.0] Media manager fix renaming to the same filename
  administrator/components/com_media/src/Controller/ApiController.php
Labels: PR-4.0-dev

#28896 Redo of #28894
  administrator/components/com_media/src/Controller/ApiController.php
Labels: PR-4.0-dev

#28882 [4.0] Fix float-right for other quickicons than counters in the Atum system dashboard for LTR
  administrator/modules/mod_submenu/tmpl/default.php
Labels: RTC

#28346 [4.0] [Installation] Fix minimum required version check when creating a new database
  installation/src/Helper/DatabaseHelper.php
  installation/src/Model/DatabaseModel.php
  installation/src/Model/SetupModel.php
Labels: PR-4.0-dev, RTC

#28817 Use renderField frontend com_contig modules view
  components/com_config/view/modules/tmpl/default_options.php
Labels: PR-staging, RTC

#28901 [4.0] [plg_content_pagebreak] Fix first page appearing in tab/slider
  plugins/content/pagebreak/pagebreak.php
Labels: PR-4.0-dev, RTC

#28824 [4.0] Move system alerts inline
  administrator/templates/atum/index.php
  administrator/templates/atum/scss/blocks/_alerts.scss
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
  build/build-modules-js/compilecss.es6.js
Labels: PR-4.0-dev, RTC

#28889 [4.0] com contact select field groups cont.
  components/com_contact/tmpl/category/default.xml
  components/com_contact/tmpl/contact/default.xml
Labels: PR-4.0-dev, RTC

#28703 [4.0] Fix typos
  libraries/src/Toolbar/Button/DropdownButton.php
Labels: PR-4.0-dev, RTC

#28666 [4.0] CLI commands
  administrator/components/com_config/src/Model/ApplicationModel.php
  installation/src/Model/ConfigurationModel.php
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Console/CheckJoomlaUpdatesCommand.php
  libraries/src/Console/ExtensionInstallCommand.php
  libraries/src/Console/ExtensionRemoveCommand.php
  libraries/src/Console/ExtensionsListCommand.php
  libraries/src/Console/GetConfigurationCommand.php
  libraries/src/Console/SetConfigurationCommand.php
  libraries/src/Console/SiteDownCommand.php
  libraries/src/Console/SiteUpCommand.php
  libraries/src/Console/UpdateCoreCommand.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Console.php
Labels: PR-4.0-dev, RTC

#28823 [4.0] Check if file exists before trying to copy
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: PR-4.0-dev, RTC

#28772 [3.10] Add the explanation about the compatibility tag to the pre update checker
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-3.10-dev, RTC

#28726 [4.0][a11y]Make module assignment accessible - step 1
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  administrator/language/en-GB/com_modules.ini
Labels: Language Change, PR-4.0-dev, RTC

#28714 [4.0] Test sample data help links
  plugins/sampledata/testing/language/en-GB/en-GB.plg_sampledata_testing.ini
Labels: RTC

#28730 [4.0] Replace inline style 10% with w-10
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_banners/tmpl/tracks/default.php
  administrator/components/com_cache/tmpl/cache/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/maps/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_languages/tmpl/installed/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#28854 [4.0] Quickicon text for Template styles
  administrator/language/en-GB/mod_quickicon.ini
Labels: J4 Backend Template, RTC

#28833 [4.0] Remove useless code for alerts
  build/media_source/system/js/core.es6/message.es6
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28788 Fix Colorscheme
  administrator/language/en-GB/tpl_atum.ini
  administrator/templates/atum/Service/HTML/Atum.php
  administrator/templates/atum/images/logo-blue.svg
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_header.scss
  administrator/templates/atum/scss/blocks/_login.scss
  administrator/templates/atum/scss/blocks/_quickicons.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/templateDetails.xml
Labels: Language Change, PR-4.0-dev, RTC

#28903 Lazy loading properly
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
Labels: NPM Resource Changed, PR-4.0-dev

#28888 [4.0] Loader web component styling fixes
  build/media_source/system/js/joomla-core-loader.w-c.es6.js
  build/media_source/system/scss/joomla-core-loader.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28563 [4] Revision of protected and locked states for core extensions in #__extensions table (update and installation)
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-04-11.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-04-11.sql
  administrator/language/en-GB/lib_joomla.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  language/en-GB/lib_joomla.ini
  libraries/src/Installer/InstallerAdapter.php
Labels: Language Change, PR-4.0-dev, RTC

#28907 [4.0] Template Atum - Toolbar Button colors
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: PR-4.0-dev, RTC

#27631 [4.0] Toggle menu selection template style
  build/media_source/com_templates/js/admin-template-toggle-assignment.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28831 Add Count items to Tags Overview - v2
  administrator/components/com_tags/forms/filter_tags.xml
  administrator/components/com_tags/src/Model/TagsModel.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/language/en-GB/com_tags.ini
Labels: Language Change, PR-4.0-dev, RTC

#28897 [4.0] Client-side validation not triggered when submitting some forms
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev, RTC

#28908 [4.0] sidebar height
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev

#28870 [4.0] Optimizing routing in languagefilter plugin
  plugins/system/languagefilter/languagefilter.php
Labels: PR-4.0-dev

#28869 [4.0] Sort namespaces
  libraries/namespacemap.php
Labels: PR-4.0-dev

#28910 [4.0] Fix media manager file rename
  administrator/components/com_media/src/Controller/ApiController.php
Labels: RTC

#28911 [4.0] Fix login alert in footer
  administrator/templates/atum/error_full.php
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/template-rtl.scss
  templates/cassiopeia/scss/blocks/_alerts.scss
Labels: PR-4.0-dev, RTC

#28902 Drop index if exists.
  administrator/components/com_admin/sql/updates/postgresql/3.9.16-2020-03-04.sql
Labels: RTC

#28912 [4.0] Improve add module tooltip
  administrator/language/en-GB/mod_quickicon.ini
Labels: Language Change, PR-4.0-dev

#28576 [3.x] send emails to dotless domains
  libraries/src/Mail/Mail.php
Labels: PR-staging, RTC

#28917 Show message when saving config with "Save & Close" button
  administrator/components/com_config/controller/component/save.php
Labels: PR-staging, RTC

#28919 Add loading=lazy for the custom field imagelist
  plugins/fields/imagelist/tmpl/imagelist.php
Labels: PR-staging

#28923 Revert "Add loading=lazy for the custom field imagelist"
  plugins/fields/imagelist/tmpl/imagelist.php
Labels: PR-staging

#28921 [4.0] th on safari
  administrator/templates/atum/scss/template.scss
  administrator/templates/atum/scss/vendor/bootstrap/_reboot.scss
Labels: PR-4.0-dev, RTC

#28914 Default to showing language strings when language debug is enabled
  libraries/src/Language/Language.php
Labels: PR-staging, RTC

#28947 [4.0] [com_languages] Remove deprecated method
  administrator/components/com_languages/src/Helper/LanguagesHelper.php
  administrator/components/com_languages/src/Model/StringsModel.php
Labels: RTC

#28939 Wrong message shown when saving profile in backend
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/language/en-GB/en-GB.com_messages.ini
Labels: RTC

#28893 [com_messages] Fix inbox lock not working
  administrator/components/com_messages/models/message.php
Labels: PR-staging, RTC

#28905 [4.0] Replace inline style 5% with w-5
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_languages/tmpl/installed/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_privacy/tmpl/consents/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#28955 [3.9] Invalid constant in Featured Contacts menu item
  components/com_contact/views/featured/tmpl/default.xml
Labels: RTC

#28960 [4.0] Add extension name/id to uninstall message if extension is locked, redo of PR 28916
  administrator/components/com_installer/src/Model/ManageModel.php
  administrator/language/en-GB/com_installer.ini
  libraries/src/Console/ExtensionRemoveCommand.php
Labels: RTC

#28944 [4.0][a11y]Make module assignment accessible - step 2
  administrator/components/com_modules/tmpl/module/edit_assignment.php
Labels: PR-4.0-dev, RTC

#28946 [4.0] Fix Language Override filtering
  administrator/components/com_languages/src/Helper/LanguagesHelper.php
Labels: PR-4.0-dev, RTC

#28937 [4.0] Fix validation in menu field
  administrator/components/com_associations/src/Field/Modal/AssociationField.php
  administrator/components/com_categories/src/Field/Modal/CategoryField.php
  administrator/components/com_contact/src/Field/Modal/ContactField.php
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_menus/src/Field/Modal/MenuField.php
  administrator/components/com_newsfeeds/src/Field/Modal/NewsfeedField.php
  layouts/joomla/form/field/user.php
Labels: RTC

#28763 Adjust en-GB.localise.php with string based suffixes
  administrator/language/en-GB/en-GB.localise.php
  language/en-GB/en-GB.localise.php
  tests/unit/suites/libraries/joomla/language/JLanguageTest.php
Labels: Language Change, PR-staging, RTC, Unit/System Tests

#28936 [4.0] Implementing administrator template preview
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#28983 [4.0] Fix template preview on PDO
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/templates/default.php
Labels: PR-4.0-dev, RTC

#28972 [4.0] Template Atum - Remove static text
  administrator/templates/atum/index.php
Labels: PR-4.0-dev, RTC

#28981 [4.0] Install From Web improvements
  administrator/components/com_installer/tmpl/install/default.php
  build/media_source/plg_installer_webinstaller/js/client.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28961 Allow tinyMCE's dnd plugin to be overridden
  plugins/editors/tinymce/tinymce.php
Labels: PR-staging, RTC

#28965 Update jQuery Autocomplete to 1.4.11
  media/jui/js/jquery.autocomplete.js
  media/jui/js/jquery.autocomplete.min.js
Labels: PR-staging, RTC

#28929 [4.0] Add loading=lazy for the custom field imagelist
  plugins/fields/imagelist/tmpl/imagelist.php
Labels: PR-4.0-dev

#28930 [4.0] Add loading=lazy for the custom field media images
  plugins/fields/media/tmpl/media.php
Labels: PR-4.0-dev

#28982 [4.0] Multilingual: modifying lang badges to fit languages with different country codes
  administrator/components/com_associations/src/Helper/AssociationsHelper.php
  administrator/components/com_categories/src/Service/HTML/AdministratorService.php
  administrator/components/com_contact/src/Service/HTML/AdministratorService.php
  administrator/components/com_content/src/Service/HTML/AdministratorService.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_menus/src/Service/HTML/Menus.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_newsfeeds/src/Service/HTML/AdministratorService.php
  administrator/components/com_templates/tmpl/styles/default.php
Labels: PR-4.0-dev, RTC

#28989 [4.0] NodeJS 14.x support
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#28829 Front-end Module Parameters - added validate=options to all fields pa…
  modules/mod_articles_archive/mod_articles_archive.xml
  modules/mod_articles_categories/mod_articles_categories.xml
  modules/mod_articles_category/mod_articles_category.xml
  modules/mod_articles_latest/mod_articles_latest.xml
  modules/mod_articles_news/mod_articles_news.xml
  modules/mod_articles_popular/mod_articles_popular.xml
  modules/mod_banners/mod_banners.xml
  modules/mod_breadcrumbs/mod_breadcrumbs.xml
  modules/mod_custom/mod_custom.xml
  modules/mod_feed/mod_feed.xml
  modules/mod_finder/mod_finder.xml
  modules/mod_footer/mod_footer.xml
  modules/mod_languages/mod_languages.xml
  modules/mod_menu/mod_menu.xml
  modules/mod_related_items/mod_related_items.xml
  modules/mod_stats/mod_stats.xml
  modules/mod_syndicate/mod_syndicate.xml
  modules/mod_tags_popular/mod_tags_popular.xml
  modules/mod_tags_similar/mod_tags_similar.xml
  modules/mod_users_latest/mod_users_latest.xml
  modules/mod_whosonline/mod_whosonline.xml
  modules/mod_wrapper/mod_wrapper.xml
Labels: PR-4.0-dev, RTC

#28827 Front-end Component Parameters - added validate=options to all fields…
  components/com_config/forms/config.xml
  components/com_config/forms/modules.xml
  components/com_contact/forms/form.xml
  components/com_contact/tmpl/categories/default.xml
  components/com_contact/tmpl/category/default.xml
  components/com_contact/tmpl/contact/default.xml
  components/com_contact/tmpl/featured/default.xml
  components/com_content/forms/article.xml
  components/com_content/forms/filter_articles.xml
  components/com_content/tmpl/archive/default.xml
  components/com_content/tmpl/article/default.xml
  components/com_content/tmpl/categories/default.xml
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/category/default.xml
  components/com_content/tmpl/featured/default.xml
  components/com_finder/tmpl/search/default.xml
  components/com_newsfeeds/tmpl/categories/default.xml
  components/com_newsfeeds/tmpl/category/default.xml
  components/com_newsfeeds/tmpl/newsfeed/default.xml
  components/com_tags/tmpl/tag/default.xml
  components/com_tags/tmpl/tag/list.xml
  components/com_tags/tmpl/tags/default.xml
  components/com_users/tmpl/login/default.xml
  components/com_wrapper/tmpl/wrapper/default.xml
Labels: PR-4.0-dev, RTC

#28969 [4.0] Replace inline style width 15% with w-15
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/searches/default.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_languages/tmpl/installed/default.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_menus/tmpl/item/edit_modules.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_messages/tmpl/messages/default.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#28967 Missing client check when uninstalling template
  libraries/src/Installer/Adapter/TemplateAdapter.php
Labels: RTC

#29004 [4.0] [com_menus] Untranslated string
  administrator/language/en-GB/com_menus.ini
Labels: RTC

#29000 [4.0] Replace inline style width 20% with w-20
  administrator/components/com_banners/tmpl/tracks/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_messages/tmpl/messages/default.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/modules/mod_latest/tmpl/default.php
  administrator/modules/mod_latestactions/tmpl/default.php
  administrator/modules/mod_logged/tmpl/default.php
  administrator/modules/mod_popular/tmpl/default.php
  administrator/modules/mod_privacy_dashboard/tmpl/default.php
  administrator/modules/mod_privacy_status/tmpl/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#28990 [4.0] Fix inline scripts/style with caching enabled
  libraries/src/Document/HtmlDocument.php
Labels: PR-4.0-dev

#28710 [4.0] Javascript - destruct params
  build/media_source/com_associations/js/admin-associations-modal.es6.js
  build/media_source/com_associations/js/associations-edit.es6.js
  build/media_source/com_banners/js/admin-banner-edit.es6.js
  build/media_source/com_cache/js/admin-cache-default.es6.js
  build/media_source/com_categories/js/shared-categories-accordion.es6.js
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/com_fields/js/admin-field-edit.es6.js
  build/media_source/com_finder/js/finder.es6.js
  build/media_source/com_joomlaupdate/js/default.es5.js
  build/media_source/com_languages/js/admin-language-edit-change-flag.es6.js
  build/media_source/com_languages/js/admin-override-edit-refresh-searchstring.es6.js
  build/media_source/com_mails/js/admin-email-template-edit.es6.js
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/com_menus/js/admin-item-edit.es6.js
  build/media_source/com_menus/js/admin-item-edit_modules.es6.js
  build/media_source/com_modules/js/admin-module-edit_assignment.es6.js
  build/media_source/com_modules/js/admin-select-modal.es6.js
  build/media_source/mod_menu/js/admin-menu.es6.js
  build/media_source/mod_menu/js/menu.es6.js
  build/media_source/mod_sampledata/js/sampledata-process.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  build/media_source/plg_media-action_crop/js/crop.es6.js
  build/media_source/plg_media-action_resize/js/resize.es6.js
  build/media_source/plg_media-action_rotate/js/rotate.es6.js
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-user.w-c.es6.js
  build/media_source/system/js/fields/select-colour.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
  build/media_source/system/js/multiselect.es6.js
  build/media_source/system/js/searchtools.es6.js
  build/media_source/system/js/showon.es6.js
  build/media_source/templates/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28997 [4.0] Filtered item information [a11y]
  administrator/components/com_contact/forms/filter_contacts.xml
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/language/en-GB/joomla.ini
  build/media_source/system/js/searchtools.es6.js
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#29009 [4.0] Replace inline style width 1% with w-1
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_cache/tmpl/cache/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_checkin/tmpl/checkin/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/maps/default.php
  administrator/components/com_finder/tmpl/searches/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_languages/tmpl/installed/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_messages/tmpl/messages/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_privacy/tmpl/consents/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/components/com_users/tmpl/users/modal.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev

#29017 [4.0] useless nonbreakingspace in en-GB
  administrator/language/en-GB/joomla.ini
Labels: RTC

#29012 [4.0] Replace inline style width 30%, 40%, 60%, 80% with w-30, w-40, w-60, …
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_menus/tmpl/item/edit_modules.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/modules/mod_latest/tmpl/default.php
  administrator/modules/mod_latestactions/tmpl/default.php
  administrator/modules/mod_logged/tmpl/default.php
  administrator/modules/mod_popular/tmpl/default.php
  administrator/modules/mod_privacy_dashboard/tmpl/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#29034 [4.0] packager drone step
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#29036 [4.0] Fix badge for removed item in changelog
  layouts/joomla/installer/changelog.php
Labels: PR-4.0-dev

#29006 [4.0] com_messages: fix user settings and move these params to a view
  administrator/components/com_messages/src/Controller/ConfigController.php
  administrator/components/com_messages/src/View/Config/HtmlView.php
  administrator/components/com_messages/src/View/Messages/HtmlView.php
  administrator/components/com_messages/tmpl/config/default.php
Labels: PR-4.0-dev, RTC

#29003 [staging] Multilingual: add lang tag to categories names in batch dropdown
  libraries/cms/html/category.php
Labels: RTC

#29027 [4.0] Replace inline style width 3%, 6%, 7% with w-3, w-6, w-7
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#29016 [4.0] com_menu - Change Featured Icon to Home Icon in
  administrator/components/com_menus/tmpl/items/default.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/modules/mod_submenu/src/Menu/Menu.php
  administrator/templates/atum/scss/blocks/_icons.scss
  libraries/src/HTML/Helpers/JGrid.php
Labels: PR-4.0-dev, RTC

#29055 [4.0] Force file type in Crowdin
  crowdin.yml
Labels: PR-4.0-dev

#29053 [4.0] Fix Batch categories Add to root missing in dropdown
  administrator/components/com_categories/tmpl/categories/default_batch_body.php
  layouts/joomla/html/batch/item.php
Labels: PR-4.0-dev, RTC

#29023 [4.0] Template Atum closed sidebar hover fix
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev, RTC

#29056 [4.0] Replace inline style width 12%, 35% with w-12, w-35
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: PR-4.0-dev, RTC

#29045 Add CSRF prevention to com_postinstall
  administrator/components/com_postinstall/controllers/message.php
  administrator/components/com_postinstall/views/messages/tmpl/default.php
Labels: PR-staging

#24738 Extend the checks to make sure only real user admins can create the accounts
  components/com_users/controllers/registration.php
  components/com_users/models/registration.php
Labels: PR-staging, RTC

#29102 [4.0] [com_finder] Class error
  administrator/components/com_finder/src/Indexer/Parser.php
Labels: PR-4.0-dev, RTC

#29101 [4.0] Error deleting access levels
  administrator/components/com_users/src/Model/LevelModel.php
Labels: PR-4.0-dev, RTC

#29106 [4.0] Add woff2 to the the valid font formats
  administrator/components/com_templates/config.xml
Labels: PR-4.0-dev

#29050 [4.0] Template Atum - Improve appereance of backend icons
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_icons.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/vendor/fontawesome-free/fontawesome.scss
  build/media_source/system/scss/_icomoon.scss
  libraries/src/Button/FeaturedButton.php
  libraries/src/HTML/Helpers/JGrid.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29118 [4.0] Generic INI filetype doesn't work due to missing plural detection
  crowdin.yml
Labels: PR-4.0-dev

#29113 [4.0] Style toolbar buttons
  administrator/components/com_modules/layouts/toolbar/cancelselect.php
  layouts/joomla/toolbar/modal.php
Labels: PR-4.0-dev, RTC

#29044 [4.0] Change .center to .text-center
  administrator/components/com_actionlogs/tmpl/actionlogs/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_privacy/tmpl/consents/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_tags/tmpl/tags/default.php
Labels: PR-4.0-dev, RTC

#29066 [4.0] Fix searchtools js error
  build/media_source/system/js/searchtools.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28515 [4.0] Adapt utf8mb4 conversion to changes in J4
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-01.sql
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-03.sql
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion.sql
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion_optional.sql
  administrator/components/com_installer/src/Model/DatabaseModel.php
  administrator/language/en-GB/com_installer.ini
  installation/sql/mysql/base.sql
  installation/src/Model/DatabaseModel.php
  libraries/src/Installer/Installer.php
  libraries/src/Schema/ChangeItem.php
  libraries/src/Schema/ChangeItem/MysqlChangeItem.php
  libraries/src/Schema/ChangeSet.php
Labels: Language Change, PR-4.0-dev, Release Blocker

#29127 Use selenium version provided by os
  tests/Codeception/drone-system-run.sh
Labels: PR-4.0-dev, Unit/System Tests

#29128 [4.0] Allow publish-diff to fail
  .drone.yml
  tests/Codeception/drone-api-run.sh
Labels: PR-4.0-dev, Unit/System Tests

#29124 [4.0] Fix js error when previewing admin template
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28991 [4.0][com_users] - fix param type onUserAfterSave
  administrator/components/com_users/src/Model/UserModel.php
  plugins/user/token/token.php
Labels: PR-4.0-dev, RTC

#28942 [4.0] Fix required checkbox client-side validation
  build/media_source/system/js/fields/validate.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29103 [4.0] Replace fixed width with class
  administrator/components/com_admin/tmpl/sysinfo/default_config.php
  administrator/components/com_admin/tmpl/sysinfo/default_directory.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
  administrator/components/com_admin/tmpl/sysinfo/default_system.php
Labels: PR-4.0-dev, RTC

#29153 [4.0] Missing check icon in media manager
  administrator/components/com_media/resources/styles/components/_media-browser.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28725 [4.0] Get rid of the not used gravatar form the webauthn plugin.
  plugins/system/webauthn/src/Helper/CredentialsCreation.php
Labels: PR-4.0-dev

#29145 [4.0] [com_postinstall] Parameterized queries
  administrator/components/com_postinstall/src/Model/MessagesModel.php
Labels: RTC

#29167 Remove publish-diff from drone
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#22032 Fix for exclude attribute in folderlist field
  libraries/joomla/form/fields/folderlist.php
Labels: PR-staging, RTC

#29122 [4.0] Change width to class
  administrator/components/com_actionlogs/tmpl/actionlogs/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_privacy/tmpl/consents/default.php
  installation/tmpl/remove/default.php
Labels: PR-4.0-dev

#29163 [4.0] Codestyle
  administrator/components/com_postinstall/src/Model/MessagesModel.php
Labels: PR-4.0-dev

#29115 Fix "Keep Forever" option for content history versions on PostgreSQL
  administrator/components/com_contenthistory/models/history.php
Labels: PR-staging, RTC

#29099 [4.0] Use namespaced classes in privacy plugins
  plugins/privacy/actionlogs/actionlogs.php
  plugins/privacy/consents/consents.php
  plugins/privacy/contact/contact.php
  plugins/privacy/content/content.php
  plugins/privacy/message/message.php
  plugins/privacy/user/user.php
Labels: PR-4.0-dev, RTC

#29098 [4.0] Language extension fixes
  administrator/components/com_installer/src/Helper/InstallerHelper.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  administrator/components/com_installer/src/Model/UpdateModel.php
Labels: PR-4.0-dev, RTC

#28977 [4.0] Quickicons - Add Shortcut to Template Code
  administrator/language/en-GB/mod_quickicon.ini
  administrator/modules/mod_quickicon/mod_quickicon.xml
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: Language Change, PR-4.0-dev, RTC

#29179 [4.0] Don't show empty tooltip
  administrator/components/com_menus/tmpl/items/modal.php
  libraries/src/HTML/Helpers/JGrid.php
Labels: PR-4.0-dev, RTC

#29146 [4.0] AfterSave events to return void
  plugins/actionlog/joomla/joomla.php
  plugins/content/finder/finder.php
  plugins/content/joomla/joomla.php
  plugins/finder/categories/categories.php
  plugins/finder/contacts/contacts.php
  plugins/finder/content/content.php
  plugins/finder/newsfeeds/newsfeeds.php
  plugins/finder/tags/tags.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/fields/fields.php
  plugins/system/languagefilter/languagefilter.php
  plugins/system/privacyconsent/privacyconsent.php
  plugins/user/contactcreator/contactcreator.php
  plugins/user/joomla/joomla.php
  plugins/user/profile/profile.php
  plugins/user/terms/terms.php
  plugins/user/token/token.php
Labels: PR-4.0-dev, RTC

#29187 [4.0] Fix admin extraneous spaces in some lang strings
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_cache.ini
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_messages.ini
  administrator/language/en-GB/com_modules.ini
Labels: Language Change, PR-4.0-dev, RTC

#29194 Fix line height parameter in CodeMirror
  plugins/editors/codemirror/codemirror.xml
Labels: PR-staging, RTC

#29172 [4.0] All values are deleted when changing list-based custom field options
  administrator/components/com_fields/src/Model/FieldModel.php
Labels: PR-4.0-dev, RTC

#29148 [4.0] AfterDelete events to return void
  plugins/actionlog/joomla/joomla.php
  plugins/content/finder/finder.php
  plugins/finder/contacts/contacts.php
  plugins/finder/content/content.php
  plugins/finder/newsfeeds/newsfeeds.php
  plugins/finder/tags/tags.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/fields/fields.php
  plugins/system/privacyconsent/privacyconsent.php
  plugins/system/webauthn/src/PluginTraits/UserDeletion.php
  plugins/user/joomla/joomla.php
  plugins/user/profile/profile.php
  plugins/user/token/token.php
Labels: PR-4.0-dev

#29205 [4.0] Toggler icons missing in backend
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29135 [4.0] Simplify post install messages module
  administrator/modules/mod_post_installation_messages/tmpl/default.php
Labels: PR-4.0-dev, RTC

#29197 [4.0] Fix changing UCM state
  plugins/content/joomla/joomla.php
Labels: PR-4.0-dev, RTC

#29191 Remove create/edit menu item buttons in frontend
  administrator/components/com_menus/models/fields/modal/menu.php
Labels: PR-staging, RTC

#29160 [4.0] [com_content] Fix filtering by author alias
  components/com_content/src/Model/ArticlesModel.php
  components/com_content/src/Service/Router.php
Labels: PR-4.0-dev, RTC

#28928 [4.0] TinyMCE, Fix drag and drop
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es6.js
  plugins/editors/tinymce/tinymce.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#29029 Only add count as suffix if it's a real plural
  libraries/src/Language/Text.php
Labels: PR-staging, RTC

#29041 [4.0] Use <meter> for password strength indicator
  administrator/templates/atum/scss/blocks/_global.scss
  build/media_source/system/js/fields/passwordstrength.es5.js
  build/media_source/system/js/fields/passwordstrength.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29063 [com_content] Unused variable
  components/com_content/views/article/tmpl/default.php
Labels: PR-staging, RTC

#29125 [3.x] com_privacy messages
  administrator/language/en-GB/en-GB.com_privacy.ini
  language/en-GB/en-GB.com_privacy.ini
Labels: Language Change, PR-staging, RTC

#29142 [4.0] Clean up disabled property code in toolbar button
  build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
Labels: RTC

#29143 [4.0] Frontend module form button spacing
  components/com_config/tmpl/modules/default.php
Labels: PR-4.0-dev, RTC

#29159 [4.0] Optimize Discover and Update menu badges
  administrator/components/com_installer/src/Controller/DiscoverController.php
  administrator/components/com_installer/src/Controller/UpdateController.php
Labels: PR-4.0-dev, RTC

#29171 Fix removing values from list-based custom fields
  administrator/components/com_fields/models/field.php
Labels: PR-staging, RTC

#29141 [4.0] Fix module form buttons in frontend
  build/media_source/com_config/js/modules-default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29201 Change header_class type from text to textarea
  administrator/components/com_modules/forms/advanced.xml
Labels: PR-4.0-dev

#29164 [4.0] [com_finder] Disable search statistics by default
  administrator/components/com_finder/config.xml
  administrator/components/com_finder/src/View/Searches/HtmlView.php
  components/com_finder/src/Helper/FinderHelper.php
Labels: PR-4.0-dev, RTC

#29200 [4.0] Improve views for articles and categories by a new line for alias
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
Labels: PR-4.0-dev, RTC

#29144 [4.0] [com_templates] Use target from event
  build/media_source/com_templates/js/admin-templates-default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#29065 [4.0] Use variable in "read more" string
  language/en-GB/com_content.ini
  layouts/joomla/content/readmore.php
Labels: Language Change, PR-4.0-dev, RTC

#29022 [4.0] WebAssets and Cache enabled
  libraries/src/Document/HtmlDocument.php
  libraries/src/WebAsset/WebAssetManager.php
  libraries/src/WebAsset/WebAssetRegistry.php
Labels: RTC

#29209 [4.0] Store changelogurl during module update via "Extensions: Install"
  libraries/src/Installer/Adapter/ModuleAdapter.php
Labels: PR-4.0-dev

#29030 [4.0] Add Cross-Origin-Opener-Policy to the HTTP Headers Plugin
  administrator/language/en-GB/plg_system_httpheaders.ini
  plugins/system/httpheaders/httpheaders.php
  plugins/system/httpheaders/httpheaders.xml
Labels: PR-4.0-dev, RTC

#29040 [4.0] Remove missing argument handling
  libraries/src/Language/Text.php
Labels: PR-4.0-dev, RTC

#28886 [4.0] Media Manager Events correctly triggered
  administrator/components/com_media/src/Model/ApiModel.php
Labels: PR-4.0-dev, RTC

#28948 [3.x] Backport jQuery 3.5 security fixes
  media/jui/js/jquery.js
  media/jui/js/jquery.min.js
Labels: PR-staging, RTC

#28931 [4.0] Move component specific fields out of com_menus
  administrator/components/com_categories/src/Field/ComponentsCategoryField.php
  administrator/components/com_categories/tmpl/categories/default.xml
  administrator/components/com_categories/tmpl/category/edit.xml
  administrator/components/com_fields/src/Field/ComponentsFieldgroupField.php
  administrator/components/com_fields/src/Field/ComponentsFieldsField.php
  administrator/components/com_fields/tmpl/fields/default.xml
  administrator/components/com_fields/tmpl/groups/default.xml
  administrator/components/com_workflow/src/Field/ComponentsWorkflowField.php
  administrator/components/com_workflow/tmpl/workflows/default.xml
Labels: PR-4.0-dev, RTC

#29214 [4.0] alphabetical sorting in com_categories
  administrator/language/en-GB/com_categories.ini
Labels: PR-4.0-dev, RTC

#29212 [4.0] Fix extension text when renaming in Media Manager
  administrator/components/com_media/resources/scripts/components/modals/rename-modal.vue
Labels: NPM Resource Changed, PR-4.0-dev

#29206 Add an rfc issue template
  .github/ISSUE_TEMPLATE/rfc.md
Labels: PR-staging

#28992 [4.0] Fix install from web
  build/media_source/com_installer/js/installer.es6.js
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  plugins/installer/webinstaller/tmpl/default.php
  plugins/installer/webinstaller/webinstaller.php
Labels: NPM Resource Changed, PR-4.0-dev

#28722 [4.0] Converting several mails to mail templates
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-04-16.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-04-16.sql
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_mails/tmpl/template/edit.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_users/src/Model/MailModel.php
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/plg_system_updatenotification.ini
  administrator/language/en-GB/plg_user_joomla.ini
  api/components/com_contact/src/Controller/ContactController.php
  components/com_contact/src/Controller/ContactController.php
  components/com_users/src/Model/RemindModel.php
  components/com_users/src/Model/ResetModel.php
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
  language/en-GB/com_contact.ini
  language/en-GB/com_users.ini
  libraries/src/Mail/MailTemplate.php
  plugins/system/updatenotification/updatenotification.php
  plugins/user/joomla/joomla.php
Labels: Language Change, PR-4.0-dev

#29223 [4.0] Backend: Plugin changelog fails #29043
  libraries/src/Installer/Adapter/PluginAdapter.php
Labels: PR-4.0-dev

#29227 [4.0] [plg_system_webauthn] Lowercase plugin name
  plugins/system/webauthn/webauthn.xml
Labels: PR-4.0-dev

#28996 Fix form validation when using patterns
  media/system/js/validate-uncompressed.js
  media/system/js/validate.js
Labels: PR-staging, RTC

#29204 TinyMCE size units not working
  plugins/editors/tinymce/tinymce.xml
Labels: PR-staging, RTC
