Repository joomla/joomla-cms, pull requests merged in 2020-02, with the labels that each got.

#27747 [4.0] No change in the display of a comment
  layouts/joomla/form/field/media.php
Labels: RTC

#27754 [4.0] Fix Global Config Text Filters table width
  administrator/components/com_config/src/Field/FiltersField.php
  layouts/joomla/content/text_filters.php
Labels: PR-4.0-dev, RTC

#27763 [4.0] Fix filter to use condition
  administrator/modules/mod_stats_admin/Helper/StatsAdminHelper.php
Labels: PR-4.0-dev, RTC

#27570 [4.0] Add upload file size check to Joomla Update Component Upload & Update
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_upload.php
  administrator/language/en-GB/com_installer.ini
  administrator/language/en-GB/joomla.ini
  build/media_source/com_joomlaupdate/js/default.es5.js
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#27665 [4.0] Add upload file size check to Extensions Installer Upload & Install Package
  build/media_source/com_installer/js/installer.es6.js
  plugins/installer/packageinstaller/tmpl/default.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27766 [4.0] Catch mailer exceptions when sending test mail
  administrator/components/com_config/src/Model/ApplicationModel.php
Labels: PR-4.0-dev, RTC

#27742 [4.0] Fix creating new file/folder in template manager
  build/media_source/com_templates/js/admin-templates-default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27697 [4.0] API global language
  api/language/en-GB/joomla.ini
  crowdin.yml
Labels: PR-4.0-dev

#27732 [4.0] RTL: correcting Joomla Installation display
  installation/forms/setup.xml
  installation/template/images/select-bg-active.svg
  installation/template/images/select-bg-rtl.svg
  installation/template/scss/template-rtl.scss
  installation/template/scss/template.scss
Labels: PR-4.0-dev, RTC

#27746 [4.0] Remove hide default
  plugins/fields/media/media.php
Labels: PR-4.0-dev, RTC

#27705 [4.0 dev] fixed toolbar and toggler
  administrator/templates/atum/index.php
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: PR-4.0-dev, RTC

#27779 [4.0] Dashboard Permissions
  administrator/modules/mod_submenu/Menu/Menu.php
Labels: RTC

#27743 [4.0] Fix custom field insert not working
  build/media_source/com_fields/js/admin-fields-modal.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27738 [4.0] Content Security Policy
  administrator/components/com_csp/Model/ReportsModel.php
  administrator/components/com_csp/forms/filter_reports.xml
  administrator/language/en-GB/com_csp.ini
Labels: Language Change, PR-4.0-dev, RTC

#27722 [4.0] [com_content] Deprecate QueryHelper::buildVotingQuery()
  components/com_content/Helper/QueryHelper.php
Labels: PR-4.0-dev, RTC

#27710 [4.0] Add category caching to routers
  components/com_contact/Service/Router.php
  components/com_content/Service/Router.php
  components/com_newsfeeds/Service/Router.php
Labels: PR-4.0-dev, RTC

#27780 [4.0] Media Manager list view
  administrator/components/com_media/resources/scripts/components/browser/items/row.vue
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27771 [plg_system_actionlogs] Render values in profile
  plugins/system/actionlogs/actionlogs.php
Labels: PR-staging, RTC

#27730 Show correct message when uploaded file is too large
  administrator/components/com_media/controllers/file.php
  administrator/language/en-GB/en-GB.com_media.ini
  libraries/src/Input/Files.php
Labels: Language Change, PR-staging, RTC

#27316 [3.10] Improve pre update checker cs and add a dedicated message when no extensions are found
  administrator/components/com_joomlaupdate/views/default/tmpl/default_preupdatecheck.php
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-3.10-dev, RTC

#27656 [4.0] Cleanup VoteRadio field
  administrator/components/com_content/Field/VoteradioField.php
Labels: PR-4.0-dev, RTC

#27792 [4.0] update com_joomlaupdate.ini - alpha ordering
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev

#20294 Custom field "list of images" doesn't show directories properly
  libraries/joomla/form/fields/folderlist.php
Labels: PR-staging, RTC

#27634 [4.0] Fix image insert not working in admin's Custom HTML module
  plugins/editors-xtd/image/image.php
Labels: PR-4.0-dev, RTC

#27785 [4.0] Media plugin backgrounds
  administrator/components/com_media/resources/styles/components/_media-edit.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27781 [4.0] RTL: fix Global Config database prefix display
  administrator/templates/atum/scss/template-rtl.scss
Labels: RTC

#27719 [4.0] Bump extension class aliases deprecation to 5.0
  libraries/extensions.classmap.php
Labels: PR-4.0-dev, RTC

#27718 [4.0] [plg_fields_subfields] Use namespaced class
  plugins/fields/subfields/subfields.php
Labels: PR-4.0-dev, RTC

#27638 [4.0] Empty catch statement
  libraries/src/Language/LanguageHelper.php
  libraries/src/MVC/Factory/MVCFactory.php
Labels: PR-4.0-dev, RTC

#27693 [4.0] Routing not working in com_contact
  administrator/components/com_contact/Extension/ContactComponent.php
  administrator/components/com_contact/services/provider.php
Labels: PR-4.0-dev

#27689 [4.0] Backend articles model parameterized queries
  administrator/components/com_content/Model/ArticlesModel.php
Labels: PR-4.0-dev, RTC

#27703 [4.0] Routing not working in com_banners
  administrator/components/com_banners/Extension/BannersComponent.php
  administrator/components/com_banners/banners.xml
  administrator/components/com_banners/services/provider.php
  components/com_banners/Service/Router.php
Labels: PR-4.0-dev, RTC

#27695 [4.0] superfluous markup - backtrace
  layouts/joomla/error/backtrace.php
Labels: PR-4.0-dev

#27797 [4.0] Fix edge case PHP Notice in com_finder
  administrator/components/com_finder/Indexer/Helper.php
Labels: RTC

#27800 [4.0] Fix Custom Administrator Menu using Presets.
  administrator/components/com_menus/Controller/MenuController.php
  administrator/components/com_menus/Helper/MenusHelper.php
Labels: RTC

#27579 [4.0] Cassiopea: allow header to be sticky if desired
  language/en-GB/tpl_cassiopeia.ini
  templates/cassiopeia/index.php
  templates/cassiopeia/scss/blocks/_header.scss
  templates/cassiopeia/scss/blocks/_layout.scss
  templates/cassiopeia/templateDetails.xml
Labels: Language Change, PR-4.0-dev, RTC

#27806 [4.0] Reorder fields, remove duplicate fields for caching
  administrator/components/com_config/forms/application.xml
Labels: RTC

#27772 [4.0] I deleted a line that I don't think we need.
  components/com_contact/tmpl/contact/default.php
Labels: PR-4.0-dev, RTC

#27520 [4.0] Update Tinymce
  build/build-modules-js/init.es6.js
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.0-dev

#27811 [4.0] Obvious typo
  administrator/components/com_actionlogs/tmpl/actionlogs/default.php
  build/media_source/com_actionlogs/js/admin-actionlogs-default.es6.js
Labels: RTC

#27704 [4.0] Changing UI for com_mails list view
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/language/en-GB/com_mails.ini
Labels: Language Change, PR-4.0-dev, RTC

#27468 [4.0]Simplified - add module to dashboard background
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: PR-4.0-dev, RTC

#27775 I deleted a line that I don't think we need
  components/com_contact/views/contact/tmpl/default.php
Labels: PR-staging, RTC

#27733 [4.0] Password toggler markup and styling
  administrator/components/com_postinstall/tmpl/messages/default.php
  administrator/modules/mod_login/tmpl/default.php
  administrator/templates/atum/scss/blocks/_form.scss
  administrator/templates/atum/scss/blocks/_login.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
  build/media_source/system/js/fields/passwordview.es6.js
  layouts/joomla/form/field/password.php
  modules/mod_login/tmpl/default.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27803 [4.0]Inconsistent hover
  administrator/templates/atum/scss/blocks/_header.scss
Labels: RTC

#27745 #27744 allow showing ucm_content items with core_access=0. Similar fi…
  modules/mod_tags_popular/helper.php
Labels: PR-staging, RTC

#27166 [4.0] [plg_system_cache] Fix debug with page caching enabled
  plugins/system/cache/cache.php
Labels: PR-4.0-dev, RTC

#27096 [4.0] Move Private Messages to Users
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-11-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-11-19.sql
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/default.xml
  administrator/language/en-GB/mod_menu.ini
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: Language Change, PR-4.0-dev, RTC

#27799 [4.0] Fix fatal error in HTMLHelper
  libraries/src/HTML/HTMLHelper.php
Labels: PR-4.0-dev, RTC

#27721 [4.0] [com_content] Parameterized queries (frontend)
  components/com_content/Model/ArchiveModel.php
  components/com_content/Model/ArticleModel.php
  components/com_content/Service/Router.php
Labels: PR-4.0-dev, RTC

#27701 [4.0] Move columns out of list.select default value
  administrator/components/com_banners/Model/BannersModel.php
  administrator/components/com_banners/Model/ClientsModel.php
  administrator/components/com_languages/Model/LanguagesModel.php
  administrator/components/com_menus/Model/ItemsModel.php
  administrator/components/com_newsfeeds/Model/NewsfeedsModel.php
  administrator/components/com_templates/Model/StylesModel.php
Labels: PR-4.0-dev, RTC

#27669 [4.0] media manager duplicate selectors
  administrator/components/com_media/resources/styles/components/_media-toolbar.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27821 [4.0] - Focus password input when password is revealed
  build/media_source/system/js/fields/passwordview.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27826 [4.0] Remove header SVG curve in error page
  templates/cassiopeia/error.php
Labels: RTC

#27827 [4.0] Menutype Filters
  administrator/components/com_menus/forms/filter_items.xml
  administrator/components/com_menus/forms/filter_itemsadmin.xml
Labels: PR-4.0-dev

#27816 fix error of styling issue with save and close button
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/template-rtl.scss
Labels: PR-4.0-dev, RTC

#27818 [4.0 dev] mobile button visible on desktop
  administrator/templates/atum/index.php
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: PR-4.0-dev, RTC

#27804 [4.0] Meta Description character count
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_config/forms/application.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_languages/forms/language.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_tags/forms/tag.xml
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  build/build-modules-js/init.es6.js
  build/build-modules-js/settings.json
  components/com_config/forms/config.xml
  components/com_content/forms/article.xml
  language/en-GB/joomla.ini
  layouts/joomla/form/field/textarea.php
  libraries/src/Form/Field/TextareaField.php
  package-lock.json
  package.json
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#27793 [4.0] Atum top
  administrator/language/en-GB/tpl_atum.sys.ini
  administrator/templates/atum/index.php
  administrator/templates/atum/templateDetails.xml
Labels: Language Change, PR-4.0-dev

#27756 [4.0] WebAsset support for inline assets
  administrator/templates/atum/Service/HTML/Atum.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  libraries/src/Document/Document.php
  libraries/src/Document/Renderer/Html/MetasRenderer.php
  libraries/src/Document/Renderer/Html/ScriptsRenderer.php
  libraries/src/Document/Renderer/Html/StylesRenderer.php
  libraries/src/WebAsset/WebAssetManager.php
Labels: PR-4.0-dev

#27679 [4.0] Remove getSortFields from content views
  administrator/components/com_content/View/Articles/HtmlView.php
  administrator/components/com_content/View/Featured/HtmlView.php
  administrator/components/com_workflow/View/Stages/HtmlView.php
  administrator/components/com_workflow/View/Workflows/HtmlView.php
Labels: PR-4.0-dev, RTC

#27677 [4.0] Remove getsortfields from views of com_users, menus, modules
  administrator/components/com_menus/View/Items/HtmlView.php
  administrator/components/com_modules/View/Modules/HtmlView.php
  administrator/components/com_users/View/Groups/HtmlView.php
  administrator/components/com_users/View/Levels/HtmlView.php
  administrator/components/com_users/View/Notes/HtmlView.php
  administrator/components/com_users/View/Users/HtmlView.php
Labels: RTC

#27678 [4.0] Remove getSortFields from components- part 1
  administrator/components/com_banners/View/Banners/HtmlView.php
  administrator/components/com_banners/View/Clients/HtmlView.php
  administrator/components/com_banners/View/Tracks/HtmlView.php
  administrator/components/com_contact/View/Contacts/HtmlView.php
  administrator/components/com_csp/View/Reports/HtmlView.php
  administrator/components/com_newsfeeds/View/Newsfeeds/HtmlView.php
  administrator/components/com_plugins/View/Plugins/HtmlView.php
  administrator/components/com_tags/View/Tags/HtmlView.php
Labels: RTC

#27819 [4.0] Display units for size and dimensions in com_media
  administrator/components/com_media/resources/scripts/components/browser/items/row.vue
  administrator/components/com_media/resources/scripts/components/infobar/infobar.vue
  administrator/components/com_media/resources/styles/components/_media-browser.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27680 [4.0] Remove getsortfields from views of com_fields, categories, languages
  administrator/components/com_categories/View/Categories/HtmlView.php
  administrator/components/com_fields/View/Fields/HtmlView.php
  administrator/components/com_fields/View/Groups/HtmlView.php
  administrator/components/com_languages/View/Languages/HtmlView.php
Labels: PR-4.0-dev, RTC

#27833 [4.0] Select multiple
  administrator/components/com_content/tmpl/articles/default.xml
  components/com_content/tmpl/archive/default.xml
  components/com_content/tmpl/featured/default.xml
  modules/mod_articles_category/mod_articles_category.xml
  modules/mod_articles_latest/mod_articles_latest.xml
  modules/mod_articles_news/mod_articles_news.xml
  modules/mod_banners/mod_banners.xml
  plugins/fields/editor/editor.xml
  plugins/fields/editor/params/editor.xml
  plugins/fields/url/params/url.xml
  plugins/fields/url/url.xml
  plugins/system/debug/debug.xml
Labels: PR-4.0-dev, RTC

#27843 [4.0] Admin modules - edit links
  administrator/modules/mod_latest/tmpl/default.php
  administrator/modules/mod_logged/tmpl/default.php
  administrator/modules/mod_popular/tmpl/default.php
Labels: PR-4.0-dev, RTC

#25258 [4.0] Remove Meta Keywords (part 1)
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/src/Controller/RequestController.php
  administrator/components/com_contact/Table/ContactTable.php
  administrator/components/com_languages/forms/language.xml
  administrator/components/com_menus/forms/item_component.xml
  administrator/components/com_newsfeeds/Table/NewsfeedTable.php
  administrator/components/com_tags/Table/TagTable.php
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/joomla.ini
  components/com_config/forms/config.xml
  components/com_contact/View/Contact/HtmlView.php
  components/com_contact/View/Featured/HtmlView.php
  components/com_content/View/Archive/HtmlView.php
  components/com_content/View/Article/HtmlView.php
  components/com_content/View/Category/HtmlView.php
  components/com_content/View/Featured/HtmlView.php
  components/com_content/View/Form/HtmlView.php
  components/com_finder/View/Search/HtmlView.php
  components/com_newsfeeds/View/Newsfeed/HtmlView.php
  components/com_privacy/View/Confirm/HtmlView.php
  components/com_privacy/View/Remind/HtmlView.php
  components/com_privacy/View/Request/HtmlView.php
  components/com_tags/View/Tag/HtmlView.php
  components/com_tags/View/Tags/HtmlView.php
  components/com_users/View/Login/HtmlView.php
  components/com_users/View/Profile/HtmlView.php
  components/com_users/View/Registration/HtmlView.php
  components/com_users/View/Remind/HtmlView.php
  components/com_users/View/Reset/HtmlView.php
  components/com_wrapper/View/Wrapper/HtmlView.php
  installation/configuration.php-dist
  installation/src/Model/ConfigurationModel.php
  installation/src/Model/LanguagesModel.php
  language/en-GB/com_config.ini
  language/en-GB/mod_banners.ini
  language/en-GB/mod_related_items.ini
  language/en-GB/mod_related_items.sys.ini
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/MVC/View/CategoriesView.php
  libraries/src/MVC/View/CategoryView.php
  plugins/sampledata/multilang/multilang.php
Labels: Language Change, PR-4.0-dev, RTC

#27840 [4.0] Update com_finder.sys.ini
  administrator/language/en-GB/com_finder.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#27847 [4.0] Fix codemiror, use original css files
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
Labels: PR-4.0-dev, RTC

#27853 [4.0] WebAssetManager Exception messages
  libraries/src/WebAsset/WebAssetManager.php
Labels: RTC

#27852 [4.0] Translate com_finder modal titles
  administrator/components/com_finder/View/Filters/HtmlView.php
  administrator/components/com_finder/View/Maps/HtmlView.php
Labels: PR-4.0-dev, RTC

#27696 [4.0] Set data directly into state rather than faking a proxy into the input
  api/components/com_categories/Controller/CategoriesController.php
  api/components/com_contenthistory/Controller/HistoryController.php
  api/components/com_fields/Controller/FieldsController.php
  api/components/com_fields/Controller/GroupsController.php
  api/components/com_languages/Controller/OverridesController.php
  api/components/com_menus/Controller/ItemsController.php
  api/components/com_menus/Controller/MenusController.php
  api/components/com_modules/Controller/ModulesController.php
  api/components/com_templates/Controller/StylesController.php
  libraries/src/MVC/Controller/ApiController.php
Labels: PR-4.0-dev

#27795 [4.0] Allow extensions to manipulate data in API on save
  api/components/com_categories/Controller/CategoriesController.php
  libraries/src/MVC/Controller/ApiController.php
Labels: PR-4.0-dev

#27855 [4.0] Fix missed WebAsset for installation/error
  installation/template/error.php
  installation/template/js/template.js
Labels: PR-4.0-dev

#27841 [4.0] Fix Mobile toolbar and filters alignment RTL and LTR
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
Labels: PR-4.0-dev, RTC

#27849 [4.0] Allow setting admin menuitem params during component installation
  libraries/src/Installer/Adapter/ComponentAdapter.php
Labels: Documentation Required, PR-4.0-dev, RTC

#27851 [4.0] Include resize modal markup for image type only
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC

#27860 [4.0] Border color between tabs on hover
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: RTC

#27848 [4.0] npm packages semver
  package-lock.json
  package.json
Labels: RTC

#27865 [4.0] Login page module
  administrator/templates/atum/html/layouts/chromes/body.php
Labels: PR-4.0-dev, RTC

#27862 [4.0] Remove negative margin in tinymce builder
  build/media_source/plg_editors_tinymce/scss/tinymce-builder.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27825 [4.0] Newsfeed Definition List
  components/com_newsfeeds/tmpl/category/default_children.php
Labels: PR-4.0-dev, RTC

#27872 [4.0] WebAsset correct user.css dependencies and sorting
  administrator/templates/atum/joomla.asset.json
  libraries/src/WebAsset/WebAssetManager.php
  templates/cassiopeia/joomla.asset.json
Labels: PR-4.0-dev, RTC

#24991 [4.0] [mod_articles_category] Add items sublayout
  modules/mod_articles_category/tmpl/default.php
  modules/mod_articles_category/tmpl/default_items.php
Labels: PR-4.0-dev, RTC

#27782 [4.0] Unpublish admin modules from dashboard
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#27871 [4.0] Fix page navigation query
  plugins/content/pagenavigation/pagenavigation.php
Labels: PR-4.0-dev, RTC

#27870 [4.0] Missing J installation error language string
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
Labels: Language Change, PR-4.0-dev

#27861 [4.0] Add margin to back-top
  templates/cassiopeia/scss/_mixin.scss
  templates/cassiopeia/scss/blocks/_footer.scss
  templates/cassiopeia/scss/template.scss
Labels: PR-4.0-dev

#24329 [4.0] Code cleanup: remove setFieldAttribute('catid', 'action', …)
  administrator/components/com_banners/Model/BannerModel.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_content/Model/ArticleModel.php
  administrator/components/com_newsfeeds/Model/NewsfeedModel.php
Labels: PR-4.0-dev

#27874 [4.0] Fix undefined property when editing stages/transitions
  administrator/components/com_workflow/Model/StageModel.php
  administrator/components/com_workflow/Model/TransitionModel.php
Labels: RTC

#27859 [4.0] Center modal on mobile
  administrator/templates/atum/scss/vendor/bootstrap/_modal.scss
Labels: RTC

#27857 [4.0] Remove Fade effect
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/_mixin.scss
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
  build/media_source/templates/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27641 [4.0] Namespace Content - Confirm Consent plugin
  plugins/content/confirmconsent/confirmconsent.php
  plugins/content/confirmconsent/confirmconsent.xml
  plugins/content/confirmconsent/src/Field/ConsentBoxField.php
Labels: PR-4.0-dev, RTC

#27854 [4.0] Allow empty metakey values in database tables
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-02-08.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-02-08.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev, RTC

#27878 [4.0] Remove zero opacity from Atum error files
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
Labels: PR-4.0-dev, RTC

#27788 [4.0] Main menu add new shortcuts
  administrator/modules/mod_menu/tmpl/default_submenu.php
Labels: PR-4.0-dev, RTC

#27869 [4.0] Load presets from component directory
  administrator/components/com_content/presets/content.xml
  administrator/components/com_menus/Helper/MenusHelper.php
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/default.xml
  administrator/components/com_users/presets/users.xml
  administrator/language/en-GB/com_content.sys.ini
  administrator/language/en-GB/com_menus.sys.ini
  administrator/language/en-GB/com_users.sys.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/mod_menu.ini
  language/en-GB/lib_joomla.ini
Labels: PR-4.0-dev, RTC

#27879 [4.0] Internet Explorer message
  administrator/language/en-GB/joomla.ini
  administrator/templates/atum/login.php
  administrator/templates/atum/scss/blocks/_login.scss
Labels: Language Change, PR-4.0-dev, RTC

#24311 [4.0] Adding frontend edit for com_contact
  administrator/components/com_contact/Extension/ContactComponent.php
  administrator/components/com_contact/Model/ContactModel.php
  administrator/components/com_contact/Service/HTML/Icon.php
  administrator/language/en-GB/com_contact.sys.ini
  administrator/language/en-GB/joomla.ini
  components/com_contact/Controller/ContactController.php
  components/com_contact/Controller/DisplayController.php
  components/com_contact/Model/FormModel.php
  components/com_contact/Service/Router.php
  components/com_contact/View/Form/HtmlView.php
  components/com_contact/forms/form.xml
  components/com_contact/tmpl/category/default_items.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/form/edit.php
  components/com_contact/tmpl/form/edit.xml
  language/en-GB/com_contact.ini
Labels: Language Change, PR-4.0-dev, RTC

#27882 [4.0] Update the bump script
  build/bump.php
Labels: PR-4.0-dev

#27886 [4.0] Update the build script
  build/build.php
Labels: PR-4.0-dev

#27883 fix error of improper padding for close button in rtl in add modules …
  administrator/templates/atum/scss/blocks/_modals.scss
Labels: PR-4.0-dev, RTC

#27894 [4.0] Help Links
  administrator/components/com_menus/presets/help.xml
  administrator/language/en-GB/mod_menu.ini
Labels: PR-4.0-dev, RTC

#27890 [4.0] [com_content] Use parent query in backend featured model
  administrator/components/com_content/Model/FeaturedModel.php
Labels: PR-4.0-dev, RTC

#25390 [4.0] Error in Update Notification plugin
  plugins/system/updatenotification/updatenotification.php
Labels: PR-4.0-dev

#27893 [4.0] User Menu heaader
  administrator/language/en-GB/mod_user.ini
  administrator/modules/mod_user/tmpl/default.php
  administrator/templates/atum/scss/blocks/_header.scss
Labels: Language Change, PR-4.0-dev, RTC

#27885 [4.0] Quicktask for custom adminmenu
  administrator/components/com_categories/tmpl/categories/default.xml
  administrator/components/com_content/tmpl/articles/default.xml
  administrator/components/com_menus/Helper/MenusHelper.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/modules/mod_submenu/tmpl/default.php
Labels: PR-4.0-dev, RTC

#27891 [4.0] Move featured logic from content table
  administrator/components/com_content/Model/ArticleModel.php
  libraries/src/Table/Content.php
Labels: PR-4.0-dev, RTC

#27900 [4.0] ComponentRecord undefined methods
  libraries/src/Component/ComponentRecord.php
Labels: RTC

#27910 [4.0] Custom Field Groups: Fix query for state
  administrator/components/com_fields/Model/GroupsModel.php
Labels: RTC

#27864 [4.0] Fix background shorthand incompatibilities
  administrator/templates/atum/images/select-bg-rtl.svg
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
  administrator/templates/atum/scss/vendor/bootstrap/_custom-forms.scss
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: PR-4.0-dev, RTC

#27707 [4.0] Make alert inline consistent
  administrator/components/com_installer/tmpl/warnings/default.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_upload.php
Labels: PR-4.0-dev, RTC

#27908 [4.0] TinyMCE new features
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev

#27899 [4.0] Hiding the overflow of container.main class
  administrator/templates/atum/scss/blocks/_global.scss
Labels: PR-4.0-dev, RTC

#27897 [4.0] Fix sticky positioning with RTL in Edge
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: PR-4.0-dev

#27931 [4.0] http status codes
  administrator/components/com_redirect/src/Field/RedirectField.php
Labels: PR-4.0-dev, RTC

#27941 Move editAssociations code to regular save method
  libraries/src/MVC/Controller/FormController.php
  libraries/src/MVC/Model/AdminModel.php
Labels: RTC

#27646 [4.0] Namespace User - Profile plugin
  plugins/user/profile/forms/profile.xml
  plugins/user/profile/profile.php
  plugins/user/profile/profile.xml
  plugins/user/profile/src/Field/DobField.php
  plugins/user/profile/src/Field/TosField.php
Labels: PR-4.0-dev, RTC

#27880 [4.0] Logo alignment [a11y]
  administrator/templates/atum/images/logo-joomla-blue.svg
Labels: PR-4.0-dev, RTC

#27898 [4.0] Categories can have sections
  administrator/components/com_menus/src/Field/ComponentsCategoryField.php
Labels: PR-4.0-dev, RTC

#27901 [4.0] Remove ComponentRecord params property uses
  administrator/components/com_config/src/View/Component/HtmlView.php
  plugins/system/updatenotification/updatenotification.php
Labels: PR-4.0-dev, RTC

#27914 [4.0] Cassiopea: fix smartsearch results display
  build/media_source/com_finder/css/finder.css
Labels: NPM Resource Changed, RTC

#27916 [4.0] add module to dashboard background
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: PR-4.0-dev, RTC

#27923 [4.0] Clean up module chromes
  administrator/templates/atum/html/layouts/chromes/body.php
  administrator/templates/atum/html/layouts/chromes/header-item.php
  administrator/templates/atum/html/layouts/chromes/title.php
  administrator/templates/atum/html/layouts/chromes/well.php
  build/media_source/layouts/css/chromes/outline.css
  layouts/chromes/html5.php
  layouts/chromes/outline.php
  layouts/chromes/sliders.php
  layouts/chromes/tabs.php
  templates/cassiopeia/html/layouts/chromes/cardGrey.php
  templates/cassiopeia/html/layouts/chromes/default.php
Labels: RTC

#27950 [4.0] Forgotton folder in xml
  administrator/components/com_contact/contact.xml
Labels: PR-4.0-dev

#27773 [4.0] Components dashboard
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-02-02.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-02-02.sql
  administrator/components/com_associations/associations.xml
  administrator/components/com_banners/banners.xml
  administrator/components/com_contact/contact.xml
  administrator/components/com_finder/finder.xml
  administrator/components/com_newsfeeds/newsfeeds.xml
  administrator/modules/mod_submenu/tmpl/default.php
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-4.0-dev, RTC

#27917 [4.0] joomla-tabs complete todo
  administrator/components/com_config/tmpl/component/default.php
  build/media_source/com_config/js/admin-application-default.es6.js
Labels: PR-4.0-dev, RTC

#27711 [4.0] Fix discover for languages installed in API directory
  administrator/components/com_installer/src/Helper/InstallerHelper.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
  administrator/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
  libraries/src/Installer/Adapter/LanguageAdapter.php
Labels: Language Change, PR-4.0-dev

#27942 [4.0] Integration Tests READ.ME
  tests/Integration/README.md
Labels: PR-4.0-dev, Unit/System Tests

#23992 [4.0] Enabling translations for debuguser Permissions
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/com_workflow.sys.ini
Labels: Information Required, Language Change, PR-4.0-dev

#27098 [4.0] Fixing switcher label for true/false
  layouts/joomla/form/field/radio/switcher.php
Labels: PR-4.0-dev

#19300 [4.0] Email Validation if there are more than 63 characters
  libraries/src/Form/Rule/EmailRule.php
Labels: PR-4.0-dev, RTC

#27953 [4.0] Fix Configuration change has no effect.
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_joomlaupdate/restore.php
  administrator/components/com_joomlaupdate/restore_finalisation.php
Labels: PR-4.0-dev

#25493 [4.0] Stop TinyMCE autochanging skins when new skins are uploaded
  plugins/editors/tinymce/field/skins.php
  plugins/editors/tinymce/form/setoptions.xml
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev

#27962 [4.0] Error message typo
  libraries/src/WebAsset/WebAssetRegistry.php
Labels: PR-4.0-dev, RTC

#27968 [4.0] Fix active filters not collapsing
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
  build/media_source/system/js/searchtools.es6.js
Labels: RTC

#27964 [4.0] tinymce new minor release
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.php
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.0-dev

#27670 [4.0] Improve mobile view of permissions
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
  layouts/joomla/form/field/rules.php
Labels: PR-4.0-dev, RTC

#27977 [4.0] Hide filter bar in featured view if no filter is active.
  administrator/components/com_content/src/Model/FeaturedModel.php
Labels: RTC

#27686 [4.0] Convert icon- in toolbar to fa- ( part 1 )
  administrator/components/com_associations/src/Field/Modal/AssociationField.php
  administrator/components/com_associations/src/View/Association/HtmlView.php
  administrator/components/com_banners/src/Field/ClicksField.php
  administrator/components/com_banners/src/Field/ImpmadeField.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_categories/src/Field/Modal/CategoryField.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_contact/src/Field/Modal/ContactField.php
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_cpanel/tmpl/cpanel/default.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/maps/default.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_reinstall.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php
  administrator/components/com_joomlaupdate/tmpl/update/finaliseconfirm.php
  administrator/components/com_joomlaupdate/tmpl/upload/captive.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/components/com_media/layouts/toolbar/delete.php
  administrator/components/com_media/layouts/toolbar/upload.php
  administrator/components/com_menus/src/Field/MenutypeField.php
  administrator/components/com_menus/src/Field/Modal/MenuField.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_modules/layouts/toolbar/cancelselect.php
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/src/Field/Modal/NewsfeedField.php
  administrator/components/com_redirect/layouts/toolbar/batch.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/style/edit_assignment.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/modules/mod_login/tmpl/default.php
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/modules/mod_privacy_status/tmpl/default.php
  administrator/modules/mod_submenu/src/Menu/Menu.php
  components/com_contact/tmpl/categories/default_items.php
  components/com_content/tmpl/archive/default_items.php
  components/com_content/tmpl/categories/default_items.php
  components/com_content/tmpl/category/blog_children.php
  components/com_content/tmpl/category/default_children.php
  components/com_newsfeeds/tmpl/categories/default_items.php
  components/com_users/tmpl/login/default_logout.php
  components/com_users/tmpl/profile/default.php
  installation/tmpl/preinstall/default.php
  layouts/joomla/form/field/password.php
  layouts/joomla/tinymce/togglebutton.php
  libraries/cms/html/grid.php
  libraries/cms/html/jgrid.php
  modules/mod_login/tmpl/default.php
  plugins/content/pagenavigation/tmpl/default.php
  plugins/system/stats/layouts/field/uniqueid.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#27937 Remove all default values for type 'text' or 'mediumtext' - redo of PR #17860
  administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-08-29.sql
  administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-11-27.sql
  administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-01-08.sql
  administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-01-09.sql
  administrator/components/com_admin/sql/updates/mysql/3.9.16-2020-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/3.1.0.sql
  administrator/components/com_admin/sql/updates/postgresql/3.6.3-2016-10-04.sql
  administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-08-29.sql
  administrator/components/com_admin/sql/updates/postgresql/3.7.0-2017-01-08.sql
  administrator/components/com_admin/sql/updates/postgresql/3.7.0-2017-01-09.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.16-2020-02-15.sql
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
Labels: PR-staging, RTC

#27972 [4.0] Small Coding Standard Changes
  administrator/components/com_contact/forms/contact.xml
Labels: PR-4.0-dev

#27974 [4.0] Use native php transliterate method when available (stringURLSafe)
  libraries/src/Language/Language.php
Labels: PR-4.0-dev

#27783 [4.0] [com_users] Missing imports, adapt to language pack changes.
  administrator/components/com_users/src/Service/HTML/Users.php
Labels: PR-4.0-dev, RTC

#27978 [4.0] Moving workflow states strings from users to main ini file
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/joomla.ini
Labels: RTC

#27912 [4.0] Change list to switcher
  administrator/components/com_users/forms/config_domain.xml
Labels: PR-4.0-dev, RTC

#27970 [4.0] [com_content] Parameterized queries (backend)
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_content/src/Helper/ContentHelper.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_content/src/Service/HTML/AdministratorService.php
Labels: PR-4.0-dev, RTC

#27989 [4.0] Add admin module quicktask in content preset
  administrator/components/com_content/presets/content.xml
Labels: RTC

#27984 [4.0] Fix contact and newsfeed association propagate functionality
  administrator/components/com_contact/src/Controller/AjaxController.php
  administrator/components/com_newsfeeds/src/Controller/AjaxController.php
Labels: PR-4.0-dev, RTC
