Repository joomla/joomla-cms, pull requests merged in 2020-04, with the labels that each got.

#28532 [4.0] Installation template
  installation/template/scss/template.scss
Labels: PR-4.0-dev

#28516 Use plugin name for path lookup
  administrator/components/com_fields/libraries/fieldsplugin.php
Labels: PR-staging

#28529 convert to prepared statements ContentHistory table
  libraries/src/Table/ContentHistory.php
Labels: RTC

#28526 [4.0] convert to prepared statements Content table
  libraries/src/Table/Content.php
Labels: PR-4.0-dev

#28460 [3.10] Add rips checks for the 3.10-dev branch
  .drone.yml
Labels: PR-3.10-dev, Unit/System Tests

#28534 [4.0] Use only plugin name for path lookup
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
Labels: PR-4.0-dev

#28491 [4.0] convert to prepared statements UserGroup table
  libraries/src/Table/Usergroup.php
Labels: PR-4.0-dev, RTC

#27822 [4.0] Correct inherited Workflow display when creating categories
  administrator/components/com_content/src/Helper/ContentHelper.php
Labels: PR-4.0-dev

#27097 [4.0] Don't use bound parameters with dateAdd()
  modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/privacyconsent/privacyconsent.php
Labels: PR-4.0-dev

#27090 [4.0] Fix language files deleted before uninstall execution
  libraries/src/Installer/Adapter/ComponentAdapter.php
Labels: PR-4.0-dev

#17012 Prevent the api url from being indexed
  components/com_ajax/ajax.php
Labels: PR-staging, Updates Requested

#25103 [4.0] Added event onContentValidateData
  libraries/src/MVC/Model/FormModel.php
Labels: Documentation Required, PR-4.0-dev

#28536 Fix version compare diff
  build/media_source/com_contenthistory/js/admin-compare-compare.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#28366 Deprecating "new" MVC for 4.0 instead of 5.0
  libraries/joomla/controller/base.php
  libraries/joomla/controller/controller.php
  libraries/joomla/model/base.php
  libraries/joomla/model/database.php
  libraries/joomla/model/model.php
  libraries/joomla/view/base.php
  libraries/joomla/view/html.php
  libraries/joomla/view/view.php
Labels: PR-staging

#28541 [4.0] convert to prepared statements ContentType table
  libraries/src/Table/ContentType.php
Labels: PR-4.0-dev

#28365 [4.0] Remove "new" MVC classes v2
  libraries/joomla/controller/base.php
  libraries/joomla/controller/controller.php
  libraries/joomla/model/base.php
  libraries/joomla/model/database.php
  libraries/joomla/model/model.php
  libraries/joomla/view/base.php
  libraries/joomla/view/html.php
  libraries/joomla/view/view.php
  libraries/loader.php
Labels: PR-4.0-dev

#28550 [4.0] Fix Diff in com_templates
  build/media_source/com_templates/js/admin-template-compare.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#28549 [4.0] Joomlaupdate: fix j version in RTL, alpha lang file
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/complete.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_nodownload.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev, RTC

#28553 [4.0] Update a bunch of dependencies
  administrator/components/com_media/resources/scripts/store/actions.js
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#28554 [4.0] convert to prepared statements Menu table
  libraries/src/Table/Menu.php
Labels: PR-4.0-dev

#28547 [4.0] Rework constructor parameters for ConsoleApplication
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Service/Provider/Application.php
Labels: PR-4.0-dev

#28353 [4.0] Fix notice when script hashes enabled
  plugins/system/httpheaders/httpheaders.php
Labels: PR-4.0-dev

#28562 [4.0] webauthn subpackage
  build/media_source/plg_system_webauthn/js/login.es6.js
  build/media_source/plg_system_webauthn/js/management.es6.js
  layouts/plugins/system/webauthn/manage.php
Labels: RTC

#28501 [3.x] Fix errors about int and tinyint columns shown in database schema check on MySQL 8
  libraries/src/Schema/ChangeItem/MysqlChangeItem.php
Labels: PR-staging, RTC

#28558 [4.0] Pagination
  administrator/templates/atum/scss/blocks/_layout.scss
  layouts/joomla/pagination/link.php
  templates/cassiopeia/scss/blocks/_layout.scss
Labels: PR-4.0-dev

#27005 [4.0][webservice] API pagination links
  api/components/com_config/src/View/Application/JsonapiView.php
  api/components/com_config/src/View/Component/JsonapiView.php
  libraries/src/MVC/Controller/ApiController.php
  libraries/src/MVC/View/JsonApiView.php
Labels: PR-4.0-dev

#28566 Change drone artifacts port to 443
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#28011 [4.0] new approach prevent registration as super user
  libraries/src/Form/Field/UsergrouplistField.php
Labels: PR-4.0-dev, RTC

#27987 Update default.php
  modules/mod_breadcrumbs/tmpl/default.php
Labels: PR-staging, RTC

#28063 [3] - JFormFieldPredefinedList fix if filter present
  libraries/joomla/form/fields/predefinedlist.php
  libraries/src/Form/Field/StatusField.php
Labels: PR-staging, RTC

#28217 [3] Fix undesired escaping of single quote in lang string
  administrator/components/com_content/models/fields/modal/article.php
Labels: PR-staging, RTC

#28350 [4.0] Restructuring Installation, splitting up SQL
  installation/sql/mysql/base.sql
  installation/sql/mysql/extensions.sql
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/base.sql
  installation/sql/postgresql/extensions.sql
  installation/sql/postgresql/supports.sql
  installation/src/Controller/InstallationController.php
  installation/src/Model/ConfigurationModel.php
  installation/src/Model/DatabaseModel.php
  installation/src/Model/SetupModel.php
  installation/template/js/setup.js
Labels: PR-4.0-dev, RTC

#28405 [4.0] Fix content history modal
  administrator/components/com_contenthistory/tmpl/history/modal.php
  templates/cassiopeia/scss/blocks/_modals.scss
Labels: RTC

#28551 [4.0] webauthn username notice
  administrator/language/en-GB/plg_system_webauthn.ini
Labels: RTC

#13286 Fix third-party component help in com_config
  administrator/components/com_config/view/component/html.php
Labels: PR-staging

#28571 [4.0] Remove vueify - we use webpack in media manager
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#27601 [4.0] Use namespaced classes in Finder, namespace route helper
  administrator/components/com_finder/src/Controller/IndexerController.php
  administrator/components/com_finder/src/Indexer/Adapter.php
  administrator/components/com_finder/src/Indexer/Driver/Postgresql.php
  administrator/components/com_finder/src/Indexer/Helper.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Result.php
  administrator/components/com_finder/src/Indexer/Token.php
  administrator/components/com_finder/src/Model/SearchesModel.php
  administrator/components/com_finder/src/Service/HTML/Filter.php
  administrator/components/com_finder/src/Service/HTML/Query.php
  components/com_finder/helpers/route.php
  components/com_finder/src/Helper/FinderHelper.php
  components/com_finder/src/Helper/RouteHelper.php
  components/com_finder/src/Model/SearchModel.php
  components/com_finder/src/Model/SuggestionsModel.php
  components/com_finder/src/View/Search/HtmlView.php
  components/com_finder/tmpl/search/default_result.php
  modules/mod_finder/mod_finder.php
  modules/mod_finder/src/Helper/FinderHelper.php
  plugins/extension/finder/finder.php
  plugins/system/fields/fields.php
  plugins/system/highlight/highlight.php
Labels: PR-4.0-dev, RTC

#28431 [4.0] WebAsset for layouts
  administrator/components/com_config/tmpl/component/default.php
  build/media_source/legacy/joomla.asset.json
  build/media_source/system/joomla.asset.json
  components/com_contact/layouts/joomla/form/renderfield.php
  layouts/joomla/content/options_default.php
  layouts/joomla/edit/frontediting_modules.php
  layouts/joomla/form/field/calendar.php
  layouts/joomla/form/field/color/slider.php
  layouts/joomla/form/field/password.php
  layouts/joomla/form/renderfield.php
  layouts/joomla/html/batch/adminlanguage.php
  layouts/joomla/html/batch/item.php
  layouts/joomla/html/batch/language.php
  layouts/joomla/searchtools/default/filters.php
  layouts/joomla/toolbar/containeropen.php
  layouts/plugins/system/webauthn/manage.php
Labels: NPM Resource Changed, PR-4.0-dev

#28579 [4.0] Tinymce column widths frontend
  templates/cassiopeia/scss/vendor/_tinymce.scss
Labels: PR-4.0-dev, RTC

#28577 [4.0] Alignment of question in batch modal
  layouts/joomla/html/batch/item.php
Labels: PR-4.0-dev, RTC

#28493 [4.0] Add OutputFilter tests
  libraries/src/Filter/OutputFilter.php
  tests/Unit/Libraries/Cms/Filter/OutputFilterTest.php
Labels: PR-4.0-dev, Unit/System Tests

#28377 [4.0] Allow extensions to add custom data to other extensions in the API
  libraries/src/MVC/View/Event/OnGetApiFields.php
  libraries/src/MVC/View/JsonApiView.php
  libraries/src/Serializer/Events/OnGetApiAttributes.php
  libraries/src/Serializer/Events/OnGetApiRelation.php
  libraries/src/Serializer/JoomlaSerializer.php
Labels: Documentation Required, PR-4.0-dev

#28561 [4.0] API Token
  administrator/language/en-GB/plg_user_token.ini
  administrator/language/en-GB/plg_user_token.sys.ini
  plugins/user/token/token.xml
  plugins/user/token/token/token.xml
Labels: Language Change, PR-4.0-dev

#28594 Add prebuilt packages for staging
  .drone.yml
Labels: PR-staging, Unit/System Tests

#27967 2FA - Joomla Secret Key - autocomplete="one-time-code"
  administrator/components/com_joomlaupdate/views/update/tmpl/finaliseconfirm.php
  administrator/components/com_joomlaupdate/views/upload/tmpl/captive.php
  administrator/modules/mod_login/tmpl/default.php
  administrator/templates/hathor/html/mod_login/default.php
  components/com_users/models/forms/login.xml
  modules/mod_login/tmpl/default.php
  templates/beez3/html/mod_login/default.php
  templates/protostar/offline.php
  templates/system/offline.php
Labels: PR-staging

#28572 [3.9] Slight improvement for tpl (View Request)
  administrator/components/com_privacy/views/request/tmpl/default.php
Labels: PR-staging, RTC

#28573 Add HTML5 elements and WAI-ARIA to error.php.
  templates/protostar/error.php
Labels: PR-staging, RTC

#28485 Updating installation language files
  installation/language/af-ZA/af-ZA.ini
  installation/language/bs-BA/bs-BA.ini
  installation/language/bs-BA/bs-BA.xml
  installation/language/en-AU/en-AU.ini
  installation/language/en-AU/en-AU.xml
  installation/language/en-CA/en-CA.ini
  installation/language/en-CA/en-CA.xml
  installation/language/en-NZ/en-NZ.ini
  installation/language/en-NZ/en-NZ.xml
  installation/language/en-US/en-US.ini
  installation/language/en-US/en-US.xml
  installation/language/es-CO/es-CO.ini
  installation/language/es-CO/es-CO.xml
  installation/language/hr-HR/hr-HR.ini
  installation/language/hr-HR/hr-HR.xml
  installation/language/it-IT/it-IT.ini
  installation/language/it-IT/it-IT.xml
  installation/language/ja-JP/ja-JP.ini
  installation/language/ja-JP/ja-JP.xml
  installation/language/sk-SK/sk-SK.ini
  installation/language/sk-SK/sk-SK.xml
  installation/language/sl-SI/sl-SI.ini
  installation/language/sl-SI/sl-SI.xml
  installation/language/th-TH/th-TH.ini
  installation/language/th-TH/th-TH.xml
Labels: Language Change, PR-staging

#28597 [3] Fix wrong delete file entry
  administrator/components/com_admin/script.php
Labels: PR-staging

#28598 Use correct language in search tooltip
  administrator/components/com_languages/models/forms/filter_overrides.xml
Labels: PR-staging, RTC

#28602 Preparing the installation in Russian for 3.9.17
  installation/language/ru-RU/ru-RU.ini
  installation/language/ru-RU/ru-RU.xml
Labels: Language Change, PR-staging

#28604 [4.0] Update com_checkin.ini
  administrator/language/en-GB/com_checkin.ini
Labels: Language Change, PR-4.0-dev

#28364 [4.0] Update UCM content types
  administrator/components/com_admin/script.php
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
Labels: PR-4.0-dev

#28605 [4.0] Fix database error shown after new installation with PostgreSQL database
  installation/sql/postgresql/supports.sql
Labels: Beta Blocker, PR-4.0-dev

#28584 [4.0] skip to show joomla token on registration
  plugins/user/token/token.php
Labels: PR-4.0-dev, Release Blocker

#25845 Support non-english chars in JS
  libraries/src/Filter/OutputFilter.php
  tests/unit/suites/libraries/joomla/filter/JFilterOutputTest.php
Labels: PR-staging

#28607 [4.0] Refactor toolbar styling
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/template-rtl.scss
  layouts/joomla/toolbar/dropdown.php
Labels: PR-4.0-dev

#28552 [4.0] Remove "fs" from package.json
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#28589 [4.0][RTL] CSS logical properties initial
  administrator/templates/atum/scss/blocks/_form.scss
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_header.scss
  administrator/templates/atum/scss/blocks/_modals.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
  administrator/templates/atum/scss/blocks/_treeselect.scss
  administrator/templates/atum/scss/pages/_com_config.scss
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
  administrator/templates/atum/scss/template-rtl.scss
Labels: PR-4.0-dev

#28362 [4.0] custom admin articles menu
  administrator/components/com_content/tmpl/articles/default.xml
  administrator/language/en-GB/com_menus.ini
Labels: PR-4.0-dev, RTC

#28615 [4.0] Rewrite searchtools CSS
  administrator/templates/atum/scss/blocks/_toolbar.scss
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
  administrator/templates/atum/scss/template-rtl.scss
  components/com_config/tmpl/config/default.php
  components/com_config/tmpl/modules/default.php
  components/com_config/tmpl/templates/default.php
  layouts/joomla/searchtools/default/bar.php
Labels: PR-4.0-dev

#28380 [4.0] Update Button API typehints
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  libraries/src/Button/ActionButton.php
  libraries/src/Button/FeaturedButton.php
  libraries/src/Button/PublishedButton.php
Labels: PR-4.0-dev

#28619 [4.0] Fix css compile after #28615
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
Labels: PR-4.0-dev, RTC

#28565 [4.0] convert to prepared statements MenuType table
  libraries/src/Table/MenuType.php
Labels: PR-4.0-dev, RTC

#28592 [4.0] Fixing smartsearch issue with some multibytes characters (alternative proposal)
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-29.sql
  administrator/components/com_finder/sql/install.mysql.sql
  installation/sql/mysql/extensions.sql
Labels: PR-4.0-dev, RTC

#28393 Removing ltrim in folderlist form field
  libraries/joomla/form/fields/folderlist.php
  tests/unit/suites/libraries/joomla/form/fields/JFormFieldFolderListTest.php
Labels: PR-staging, RTC

#28622 [4.0][Cassiopeia] Rewrite searchtools CSS
  templates/cassiopeia/scss/system/searchtools/searchtools.scss
  templates/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
Labels: PR-4.0-dev

#28625 [4.0] Fix "Undefined property: stdClass::$version" notices on updated J4 in Extensions Manager
  libraries/src/Extension/ExtensionHelper.php
Labels: PR-4.0-dev

#28631 [4.0] JHhtml namespace
  administrator/components/com_finder/tmpl/index/default.php
  components/com_contact/tmpl/contact/default.php
Labels: PR-4.0-dev

#28630 [4.0] JText namespace
  administrator/components/com_mails/tmpl/templates/default.php
  components/com_contact/tmpl/contact/default.php
  libraries/src/Form/Form.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/MVC/Model/AdminModel.php
  plugins/quickicon/phpversioncheck/phpversioncheck.php
Labels: PR-4.0-dev

#28629 [4.0] Hiding download progress of chocolatey in Appveyor
  .appveyor.yml
Labels: PR-4.0-dev, Unit/System Tests

#28595 [4.0] RTL: fix display of max size for extension install and template new file
  administrator/components/com_templates/tmpl/template/default_modal_file_body.php
  plugins/installer/packageinstaller/tmpl/default.php
Labels: PR-4.0-dev, RTC

#26074 [4.0] admin latest articles
  administrator/modules/mod_latest/tmpl/default.php
Labels: PR-4.0-dev

#28574 [4.0] send email to dotless domains
  libraries/src/Mail/Mail.php
Labels: PR-4.0-dev, RTC

#28637 [4.0]Remove css-vars ponyfill
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/joomla.asset.json
  administrator/templates/atum/login.php
  build/build-modules-js/settings.json
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.0-dev

#28635 [4.0] Defer loading of menu items until required
  libraries/src/Menu/AbstractMenu.php
  libraries/src/Menu/SiteMenu.php
Labels: RTC

#28640 [4.0] Administrator menu module should have the default preset as default
  administrator/modules/mod_menu/mod_menu.xml
Labels: PR-4.0-dev

#28634 [4.0] Add router to interface
  libraries/src/Application/CMSWebApplicationInterface.php
Labels: Beta Blocker, PR-4.0-dev

#28647 [4.0] Fix infinite loop in menu class
  libraries/src/Menu/SiteMenu.php
Labels: PR-4.0-dev

#28642 [4.0] Cleanup of Appveyor test builds
  .appveyor.yml
Labels: PR-4.0-dev, Unit/System Tests

#28650 [4.0] Associations warning translateable
  layouts/joomla/edit/associations.php
Labels: PR-4.0-dev, RTC

#28653 [4.0] Private messages
  administrator/components/com_menus/presets/default.xml
Labels: RTC

#28645 [4.0][Atum] Rounded 'input-group-append'
  administrator/templates/atum/scss/blocks/_form.scss
Labels: RTC

#28638 [4.0]Remove extra css attribute
  administrator/templates/atum/scss/blocks/_utilities.scss
Labels: RTC

#28649 [4.0][a11y] Add a fieldset with id in batch modal of categories
  administrator/components/com_categories/tmpl/categories/default_batch_body.php
Labels: PR-4.0-dev, RTC

#28656 [4.0] Improve strings for adding an extra language
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
  installation/src/View/Remove/HtmlView.php
  installation/tmpl/remove/default.php
Labels: Language Change, PR-4.0-dev, RTC

#28655 [4.0] Add missing update SQL for adding plg_quickicon_downloadkey to the extensions
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-04-11.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-04-11.sql
Labels: PR-4.0-dev, RTC

#28657 [4.0] [a11y] Add fieldset with id to users batch modal
  administrator/components/com_users/tmpl/users/default_batch_body.php
Labels: PR-4.0-dev, RTC

#28652 [4.0] header dropdown menu on tablet
  administrator/templates/atum/scss/blocks/_header.scss
Labels: PR-4.0-dev, RTC

#28646 [4.0] View Private Message
  administrator/components/com_messages/tmpl/message/default.php
Labels: PR-4.0-dev, RTC

#28632 [4.0] Fix featured articles not shown in frontend
  administrator/components/com_content/src/Model/ArticleModel.php
Labels: PR-4.0-dev, RTC

#28644 [4.0][Atum] Some searchtool fixes
  administrator/components/com_associations/layouts/joomla/searchtools/default.php
  administrator/components/com_menus/layouts/joomla/searchtools/default.php
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
Labels: PR-4.0-dev, RTC

#27829 [4.0] minicolors
  administrator/templates/atum/scss/template.scss
  build/media_source/system/scss/_jquery-minicolors.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28580 [4.0] Remove a "development" error_reporting as obsolete
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/includes/framework.php
  administrator/language/en-GB/com_config.ini
  api/includes/framework.php
  includes/framework.php
Labels: Language Change, PR-4.0-dev

#28636 [4.0] Improve asset registry files handling
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Error/Renderer/HtmlRenderer.php
  libraries/src/WebAsset/WebAssetRegistry.php
Labels: PR-4.0-dev

#28610 [3.x]remove redundant table read during Article hit counter increment
  components/com_contact/models/category.php
  components/com_contact/models/contact.php
  components/com_content/models/article.php
  components/com_content/models/category.php
  components/com_newsfeeds/models/category.php
  components/com_newsfeeds/models/newsfeed.php
  components/com_tags/models/tag.php
Labels: PR-staging, RTC

#28627 [4.0][Atum] Rewrite alert CSS
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
Labels: PR-4.0-dev, RTC

#28668 [4.0] Improve text padding in quickicons
  administrator/templates/atum/scss/blocks/_quickicons.scss
  layouts/joomla/quickicons/icon.php
Labels: PR-4.0-dev, RTC

#28667 [4.0] Fix association edit toolbar style
  administrator/components/com_associations/src/View/Association/HtmlView.php
Labels: PR-4.0-dev, RTC

#28658 [4.0][Atum] Choices CSS rewrite
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: PR-4.0-dev

#28495 [3.x] Add missing tables for action logs and the privacy suite to utf8mb4 conversion
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-02.sql
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion-03.sql
  installation/model/database.php
  libraries/src/Schema/ChangeSet.php
Labels: PR-staging, RTC

#28676 [4.0] Choices RTL dropdown fix
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
Labels: PR-4.0-dev

#28678 Fix broken Associations toolbar button when editing category
  administrator/components/com_categories/models/category.php
Labels: PR-staging, RTC, Release Blocker

#28596 [3] Add workaround for calendar fields on reload and invalid save
  libraries/src/MVC/Controller/FormController.php
Labels: PR-staging, RTC

#17859 [com_fields] Update fields.php
  administrator/components/com_fields/helpers/fields.php
Labels: PR-staging, RTC

#28452 Escape return to homepage url in isis and hathor
  administrator/templates/hathor/login.php
  administrator/templates/isis/login.php
Labels: PR-staging, RTC

#28278 Fix loading module by ID on PostgreSQL
  libraries/src/Helper/ModuleHelper.php
Labels: PR-staging, RTC

#28681 [4.0] Fixing tests in media manager
  tests/Codeception/_support/Step/Acceptance/Administrator/Admin.php
  tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
Labels: PR-4.0-dev, Unit/System Tests

#28684 Fix missing lft rgt nested tree rebuild in usergroups table when deleting usergroup(s)
  libraries/src/Table/Usergroup.php
Labels: PR-staging, RTC

#28695 [4.0] Remove closest and matches polyfills
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/mod_menu/js/admin-menu.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  build/media_source/system/js/multiselect.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#28660 [4.0] Big composer update
  composer.json
  composer.lock
  libraries/src/Filter/InputFilter.php
  libraries/src/Form/Filter/SafehtmlFilter.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Media.php
Labels: Composer Dependency Changed, PR-4.0-dev, Unit/System Tests

#28696 [4.0] Fix JS error in codemirror
  build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28683 [4.0] Fix PHP warning "... Parameter must be ... Countable in override.php" when updating
  plugins/installer/override/override.php
Labels: PR-4.0-dev, RTC

#28692 [4.0] Replace 25% & 50% width inline styles with respective classes
  administrator/components/com_admin/tmpl/sysinfo/default_system.php
  administrator/components/com_contenthistory/tmpl/compare/compare.php
  administrator/components/com_contenthistory/tmpl/preview/preview.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/components/com_users/tmpl/users/modal.php
  administrator/modules/mod_logged/tmpl/default.php
Labels: RTC

#28687 [4.0] Fix deleting user groups
  libraries/src/Table/Usergroup.php
Labels: PR-4.0-dev, RTC

#28699 [4.0] Remove module from sidebar in com_config
  administrator/components/com_config/tmpl/application/default.php
Labels: PR-4.0-dev, RTC

#28713 [4.0] Articles - most read
  modules/mod_articles_popular/mod_articles_popular.xml
Labels: RTC

#28723 [4.0][mod_stats] - frontend like admin module
  modules/mod_stats/src/Helper/StatsHelper.php
Labels: RTC

#28718 [4.0] Custom read more text accessibility
  layouts/joomla/content/readmore.php
Labels: PR-4.0-dev, RTC

#28728 [4.0] Make tests passing in PHP 7.4 mandatory
  .drone.yml
Labels: PR-4.0-dev, Unit/System Tests

#28451 [4.0][api][com_users] - Add filter options
  administrator/components/com_users/src/Model/UsersModel.php
  api/components/com_users/src/Controller/UsersController.php
Labels: PR-4.0-dev, RTC

#28732 [4.0] spacer hr display
  administrator/templates/atum/scss/vendor/bootstrap/_form.scss
Labels: RTC

#28603 Update Installation Language Files
  installation/language/cy-GB/cy-GB.ini
  installation/language/cy-GB/cy-GB.xml
  installation/language/el-GR/el-GR.ini
  installation/language/el-GR/el-GR.xml
  installation/language/zh-CN/zh-CN.ini
  installation/language/zh-CN/zh-CN.xml
Labels: Language Change, PR-staging

#28740 Revert "[3.x] Adding New article button in category blog layout"
  components/com_content/views/category/tmpl/blog.php
Labels: PR-staging

#28736 [4.0] com contact select field groups
  administrator/components/com_contact/config.xml
  administrator/components/com_contact/forms/contact.xml
Labels: RTC

#28746 Fix tags single instance view
  components/com_tags/models/tag.php
Labels: PR-staging

#28737 [4.0] Change spacer text to fieldset description
  administrator/language/en-GB/joomla.ini
  administrator/templates/atum/scss/blocks/_alerts.scss
  api/language/en-GB/joomla.ini
  components/com_contact/tmpl/categories/default.xml
  components/com_contact/tmpl/category/default.xml
  components/com_contact/tmpl/featured/default.xml
  components/com_content/tmpl/categories/default.xml
  components/com_content/tmpl/category/blog.xml
  components/com_newsfeeds/tmpl/categories/default.xml
  components/com_newsfeeds/tmpl/category/default.xml
  components/com_tags/tmpl/tag/default.xml
  components/com_tags/tmpl/tag/list.xml
  layouts/joomla/edit/params.php
Labels: Language Change, PR-4.0-dev, RTC

#28752 [4.0] Installation: preventing translation of the "installation" folder
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
  installation/template/js/remove.js
  installation/tmpl/remove/default.php
Labels: RTC

#28760 [4.0] Remove unused PLG_FIELDS_SQL_RULES_ADAPTED
  administrator/language/en-GB/plg_fields_sql.ini
Labels: PR-4.0-dev, RTC

#28761 [3.9] Mark PLG_FIELDS_SQL_RULES_ADAPTED deprecated
  administrator/language/en-GB/en-GB.plg_fields_sql.ini
Labels: RTC

#28768 Revert "[3.9] Mark PLG_FIELDS_SQL_RULES_ADAPTED deprecated"
  administrator/language/en-GB/en-GB.plg_fields_sql.ini
Labels: Language Change, PR-staging

#28767 [4.0] Remove deprecated client handling from the updater extension adapter class
  libraries/src/Updater/Adapter/ExtensionAdapter.php
Labels: Documentation Required, PR-4.0-dev

#28764 [4.0] pull-right is not a bs4 class (frontend)
  components/com_newsfeeds/tmpl/newsfeed/default.php
  layouts/joomla/content/full_image.php
  layouts/joomla/content/intro_image.php
Labels: PR-4.0-dev

#28769 Namespace User - Joomla API Token plugin
  plugins/user/token/forms/token.xml
  plugins/user/token/src/Field/JoomlatokenField.php
  plugins/user/token/token.php
  plugins/user/token/token.xml
Labels: PR-4.0-dev

#28770 Revert "Revert "[3.9] Mark PLG_FIELDS_SQL_RULES_ADAPTED deprecated""
  administrator/language/en-GB/en-GB.plg_fields_sql.ini
Labels: Language Change, PR-staging

#28753 [4.0] Fix subform fields
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#26196 Handle non-existing manifest XML files in update sites
  administrator/components/com_installer/src/Helper/InstallerHelper.php
Labels: PR-4.0-dev

#28756 [4.0][Atum] Rewrite sidebar CSS
  administrator/modules/mod_menu/tmpl/default_submenu.php
  administrator/templates/atum/index.php
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_login.scss
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: PR-4.0-dev, RTC

#28779 Updating Welsh installation language
  installation/language/cy-GB/cy-GB.ini
  installation/language/cy-GB/cy-GB.xml
Labels: Language Change, PR-staging

#28784 PHPDoc fix
  libraries/src/Language/LanguageHelper.php
Labels: PR-staging

#28780 [4.0] Improving Color harmony of the dark colour background in atum
  administrator/templates/atum/Service/HTML/Atum.php
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/templateDetails.xml
Labels: PR-4.0-dev

#28791 Remove btn-sm class
  libraries/src/Toolbar/Button/StandardButton.php
Labels: J4 Backend Template, RTC

#28785 [4.0] Fix captcha plugins and scripts
  build/media_source/plg_captcha_recaptcha/js/recaptcha.es6.js
  build/media_source/plg_captcha_recaptcha_invisible/js/recaptcha.es6.js
  libraries/src/Captcha/Captcha.php
  plugins/captcha/recaptcha/recaptcha.php
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#28786 [4.0] Atum - Change hardcoded class of delete button and add as parameter
  administrator/components/com_templates/src/View/Template/HtmlView.php
  libraries/src/Toolbar/ToolbarHelper.php
Labels: PR-4.0-dev, RTC

#28797 [4.0] Fix PHP error with pagebreak
  plugins/content/pagebreak/tmpl/navigation.php
Labels: RTC

#28741 Fix so when creating a user with a username of more than 150 characters you get a useful error
  administrator/language/en-GB/en-GB.lib_joomla.ini
  language/en-GB/en-GB.lib_joomla.ini
Labels: Language Change, PR-staging

#28802 [4.0][com_actiologs] better visualization for option Verbs To Log
  administrator/components/com_actionlogs/config.xml
Labels: RTC

#28734 [4.0] - Respect the field limits for the asset table
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-29.sql
  administrator/components/com_content/forms/article.xml
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  libraries/src/Table/Table.php
Labels: PR-4.0-dev, RTC

#28773 [4.0] Fix Uncaught TypeError: f.reverse is not a function
  build/media_source/system/js/draggable.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#28806 Only run rips and the packager on the joomla-cms repo
  .drone.yml
Labels: PR-staging, Unit/System Tests
