Repository joomla/joomla-cms, pull requests merged in 2021-05, with the labels that each got.

#33469 [4.0] Remove Deprecated Attributes
  layouts/chromes/table.php
Labels: PR-4.0-dev, RTC

#33461 [4.0] privacy request scope
  administrator/components/com_privacy/tmpl/requests/default.php
Labels: PR-4.0-dev, RTC

#33462 [4.0] Removed <hr> tag in installation plugins
  plugins/installer/folderinstaller/tmpl/default.php
  plugins/installer/packageinstaller/tmpl/default.php
  plugins/installer/urlinstaller/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33458 [4.0] Hide columns in mobile viewport
  administrator/components/com_users/tmpl/groups/default.php
Labels: PR-4.0-dev, RTC

#33464 [4.0] Fix tinymce the options form
  administrator/language/en-GB/plg_editors_tinymce.ini
  layouts/plugins/editors/tinymce/field/tinymcebuilder/setoptions.php
  plugins/editors/tinymce/forms/setoptions.xml
Labels: Language Change, PR-4.0-dev, RTC

#33446 [4.0] Separable buttons on Joomla Update Page
  administrator/components/com_joomlaupdate/tmpl/upload/captive.php
Labels: PR-4.0-dev, RTC

#33444 [4.0] com_templates: Validate input for copy template form
  administrator/components/com_templates/src/Controller/TemplateController.php
  administrator/components/com_templates/tmpl/template/default_modal_copy_body.php
Labels: PR-4.0-dev, RTC

#33457 [4] Add intl extension check to system info, and while there clean up deprecations/types/[]
  administrator/components/com_admin/src/Model/SysinfoModel.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
  administrator/language/en-GB/com_admin.ini
Labels: Language Change, PR-4.0-dev, RTC

#33441 [4.0] Add class in fieldset in com_joomlaupdate
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev, RTC

#33442 [4.0] Private Messages: Add legend in Configuration Form
  administrator/components/com_messages/tmpl/config/default.php
  administrator/language/en-GB/com_messages.ini
Labels: Language Change, PR-4.0-dev, RTC

#33475 [4] Cleanup output html of email field
  layouts/joomla/form/field/email.php
Labels: PR-4.0-dev, RTC

#33470 [4.0] toggle editor icon
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
Labels: PR-4.0-dev, RTC

#33478 [4.0] Fix merge conflict remainder from upmerge from 3.10-dev
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: PR-4.0-dev

#33479 [4.0] PHPCS fixes after upmerge
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php
Labels: PR-4.0-dev

#33484 [4.0] JS codestyle
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#33473 [4.0] Fix tabs in User Access levels and Joomla Update Complete View
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/complete.php
  administrator/components/com_users/tmpl/level/edit.php
Labels: PR-4.0-dev, RTC

#33486 [4.0] Remove cellspacing and cellpadding from Error Backtrace table
  layouts/joomla/error/backtrace.php
Labels: PR-4.0-dev, RTC

#33471 [4] redo the logic behind Empty State Queries.
  administrator/components/com_categories/src/Model/CategoriesModel.php
  administrator/components/com_tags/src/Model/TagsModel.php
  libraries/src/MVC/Model/ListModel.php
Labels: PR-4.0-dev, RTC

#33055 [4] Catch, translate, and expound when GD not available.
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/language/en-GB/com_templates.ini
Labels: Language Change, PR-4.0-dev, RTC

#33456 [4] remove space in output html class list
  templates/cassiopeia/index.php
Labels: PR-4.0-dev, RTC

#33482 [4.0] [UX] Use number field for num_columns in blog and featured layout
  administrator/components/com_content/config.xml
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/featured/default.xml
Labels: PR-4.0-dev, RTC

#33436 [4.0] Move form text below field
  administrator/components/com_templates/tmpl/template/default_modal_copy_body.php
Labels: PR-4.0-dev, RTC

#33448 [4.0] Installation Remove [a11y]
  installation/tmpl/remove/default.php
Labels: PR-4.0-dev, RTC

#33496 [4] s/2008/2021
  administrator/components/com_content/tmpl/articles/emptystate.php
Labels: PR-4.0-dev, RTC

#33474 [4] Empty State for Checking for updates
  administrator/components/com_installer/src/Controller/UpdateController.php
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_installer/src/View/Update/HtmlView.php
  administrator/components/com_installer/tmpl/update/emptystate.php
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#32608 [4.0] Remove display widths for integer data types from SQL scripts for MySQL and MariaDB databases
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-26.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-19.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-08-03.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-05-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-04-11.sql
  administrator/components/com_banners/sql/install.mysql.utf8.sql
  administrator/components/com_contact/sql/install.mysql.utf8.sql
  administrator/components/com_finder/sql/install.mysql.sql
  administrator/components/com_newsfeeds/sql/install.mysql.utf8.sql
  installation/sql/mysql/base.sql
  installation/sql/mysql/extensions.sql
  installation/sql/mysql/supports.sql
  tests/Integration/Libraries/Cms/Table/TableTest.php
  tests/Integration/datasets/mysqli/framework.sql
  tests/Integration/datasets/mysqli/testtable.sql
  tests/Integration/datasets/pgsql/testtable.sql
Labels: PR-4.0-dev, Unit/System Tests

#33483 [4.0] fixes issue where dropdown item doesn't have border radius
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33506 [4.0] database fix text
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: PR-4.0-dev, RTC

#33510 [4.0] br element
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev, RTC

#33060 [4.0] Updated files and folders deletion on updates and remove 3.9.x update SQL scripts
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#33502 [4.0] Improve sample tags
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: Language Change, PR-4.0-dev

#33498 [4.0] filter integer
  administrator/components/com_content/config.xml
  administrator/components/com_messages/forms/config.xml
  administrator/components/com_newsfeeds/config.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_users/config.xml
  components/com_content/tmpl/archive/default.xml
  components/com_content/tmpl/categories/default.xml
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/featured/default.xml
  components/com_finder/tmpl/search/default.xml
  components/com_newsfeeds/tmpl/categories/default.xml
  components/com_newsfeeds/tmpl/category/default.xml
  components/com_newsfeeds/tmpl/newsfeed/default.xml
  plugins/captcha/recaptcha/recaptcha.xml
  plugins/media-action/crop/form/crop.xml
  plugins/media-action/resize/form/resize.xml
  plugins/media-action/rotate/form/rotate.xml
Labels: PR-4.0-dev, RTC

#33507 [4.0] Update download URL of composer 1 for appveyor
  .appveyor.yml
Labels: PR-4.0-dev, Unit/System Tests

#33508 [3.x] Update download URL of composer for appveyor
  .appveyor.yml
Labels: PR-staging, Unit/System Tests

#33511 [4.0] namespace
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
Labels: PR-4.0-dev, RTC

#33390 [4.0] Removing GUI parts of FTP layer
  administrator/components/com_admin/script.php
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/src/Controller/ApplicationController.php
  administrator/components/com_config/src/Controller/ComponentController.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_config/src/View/Application/HtmlView.php
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/application/default_ftp.php
  administrator/components/com_config/tmpl/application/default_ftplogin.php
  administrator/components/com_installer/src/Controller/DisplayController.php
  administrator/components/com_installer/src/Model/InstallModel.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/install/default.php
  administrator/components/com_installer/tmpl/installer/default_ftp.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_languages/src/Model/InstalledModel.php
  administrator/components/com_languages/src/View/Installed/HtmlView.php
  administrator/components/com_templates/src/Controller/TemplateController.php
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/com_installer.ini
  administrator/language/en-GB/com_languages.ini
  administrator/language/en-GB/com_templates.ini
  installation/configuration.php-dist
  installation/forms/preinstall.xml
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
  installation/src/Model/ChecksModel.php
  installation/src/Model/ConfigurationModel.php
  installation/src/Model/SetupModel.php
  installation/template/index.php
  installation/template/js/preinstall.js
  installation/template/js/template.js
  installation/tmpl/preinstall/default.php
  language/en-GB/com_media.ini
Labels: Language Change, PR-4.0-dev, RTC, Release Blocker

#33517 [4.0] type=list options
  administrator/components/com_content/config.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_fields/forms/filter_fields.xml
  administrator/components/com_mails/forms/filter_templates.xml
  components/com_content/forms/article.xml
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/category/default.xml
  components/com_content/tmpl/featured/default.xml
  installation/forms/setup.xml
Labels: PR-4.0-dev, RTC

#33518 [4.0] update cacert.pem
  libraries/src/Http/Transport/cacert.pem
Labels: PR-4.0-dev

#33533 [4.0] Improve Frontend Statistics Module list item layout
  modules/mod_stats/tmpl/default.php
Labels: RTC

#33539 [4.0] config load balancer
  administrator/components/com_config/forms/application.xml
Labels: PR-4.0-dev, RTC

#33543 [4.0] Admin module feed display image
  administrator/modules/mod_feed/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33541 [4.0] mod login admin
  administrator/language/en-GB/mod_login.sys.ini
Labels: PR-4.0-dev, RTC

#33516 [4.0] Remove .text-muted used with .form-text
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_upload.php
  build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
  installation/template/error.php
  installation/tmpl/preinstall/default.php
  layouts/joomla/form/renderfield.php
  plugins/installer/packageinstaller/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33505 [4.0] calendar cellpading
  build/media_source/system/js/fields/calendar.es5.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33472 [4] Introducing empty state to modules
  administrator/modules/mod_latest/mod_latest.php
  administrator/modules/mod_popular/mod_popular.php
  administrator/modules/mod_privacy_dashboard/mod_privacy_dashboard.php
  layouts/joomla/content/emptystate_module.php
Labels: PR-4.0-dev, RTC

#33512 [4.0] Fix the db schema checker in 4.0
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: PR-4.0-dev, RTC

#33554 [4.0] Frontend: Removes Extra hr at the end of Module Edit View
  components/com_config/tmpl/modules/default.php
Labels: J4 Frontend Template, PR-4.0-dev, RTC

#33544 [4.0] Finder date filters
  administrator/components/com_finder/src/Service/HTML/Filter.php
Labels: PR-4.0-dev, RTC

#33489 [4] Empty State for Smart Search Index page
  administrator/components/com_finder/src/View/Index/HtmlView.php
  administrator/components/com_finder/tmpl/index/emptystate.php
  administrator/language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#33495 [4] Search Term Analysis Empty State
  administrator/components/com_finder/src/View/Searches/HtmlView.php
  administrator/components/com_finder/tmpl/searches/emptystate.php
  administrator/language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#33560 [4.0] Cassiopeia - Add overflow hidden to ul and ol
  templates/cassiopeia/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#32806 [4][Tests] Tests without the need of jQuery
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Banner.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Content.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
Labels: PR-4.0-dev, Unit/System Tests

#33488 [4.0] Fix JS errors for com_joomlaupdate
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#33454 [4][Media] Renaming files when containing 100% non-latin ascii
  administrator/language/en-GB/com_media.ini
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: Language Change, PR-4.0-dev, RTC

#33549 [4.0] Add options-form class in Cassiopeia
  layouts/joomla/form/field/media.php
  templates/cassiopeia/scss/blocks/_layout.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33532 [4.0] Version modal toolbar redesigned
  administrator/components/com_contenthistory/tmpl/history/modal.php
Labels: PR-4.0-dev, RTC

#33576 [4.0] Bootstrap 5.0 plus more
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.0-dev, Release Blocker

#33578 [4.0] Atum preview images
  administrator/templates/atum/template_preview.png
  administrator/templates/atum/template_thumbnail.png
Labels: PR-4.0-dev

#33574 [4.0] Add files and folder removal for admin UI repaint to script.php
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#33555 [4.0] Add files removal for removed FTP GUI parts to script.php
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev, RTC

#33588 [4.0] Fix com redirect modal
  administrator/components/com_redirect/tmpl/links/emptystate.php
Labels: PR-4.0-dev

#33593 [4] Post installation messages s/generic icon/bell icon
  administrator/components/com_postinstall/src/View/Messages/HtmlView.php
  administrator/components/com_postinstall/tmpl/messages/default.php
Labels: PR-4.0-dev, RTC

#33536 [4.0] Fix Description for Password Fields that do not have rules
  administrator/components/com_config/forms/application.xml
  administrator/components/com_users/forms/user.xml
  components/com_users/forms/registration.xml
  components/com_users/forms/reset_complete.xml
  layouts/joomla/form/field/password.php
  plugins/authentication/ldap/ldap.xml
Labels: PR-4.0-dev, RTC

#33550 [4.0] Remove com_csp and move the CSP configuration to the HttpHeaders plugin
  .github/CODEOWNERS
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-07-16.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-05-04.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-06-03.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-16.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-05-04.sql
  administrator/components/com_csp/access.xml
  administrator/components/com_csp/config.xml
  administrator/components/com_csp/csp.xml
  administrator/components/com_csp/forms/filter_reports.xml
  administrator/components/com_csp/services/provider.php
  administrator/components/com_csp/src/Controller/DisplayController.php
  administrator/components/com_csp/src/Controller/ReportsController.php
  administrator/components/com_csp/src/Helper/ReporterHelper.php
  administrator/components/com_csp/src/Model/ReportModel.php
  administrator/components/com_csp/src/Model/ReportsModel.php
  administrator/components/com_csp/src/Table/ReportTable.php
  administrator/components/com_csp/src/View/Reports/HtmlView.php
  administrator/components/com_csp/tmpl/reports/default.php
  administrator/components/com_csp/tmpl/reports/default.xml
  administrator/components/com_csp/tmpl/reports/emptystate.php
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/system.xml
  administrator/language/en-GB/com_csp.ini
  administrator/language/en-GB/com_csp.sys.ini
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/mod_menu.ini
  administrator/language/en-GB/plg_system_httpheaders.ini
  api/language/en-GB/joomla.ini
  components/com_csp/src/Controller/ReportController.php
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/system/httpheaders/httpheaders.php
  plugins/system/httpheaders/httpheaders.xml
Labels: Documentation Required, Language Change, PR-4.0-dev, RTC, Release Blocker

#33130 [4.0] Fix tinymce template
  administrator/language/en-GB/plg_editors_tinymce.ini
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/tinymce.php
  templates/cassiopeia/html/tinymce/index.html
  templates/cassiopeia/templateDetails.xml
Labels: Language Change, PR-4.0-dev, RTC

#33610 [4] JSON_PRETTY_PRINT the System Info Json Export
  administrator/components/com_admin/src/View/Sysinfo/JsonView.php
Labels: PR-4.0-dev, RTC

#33624 [4.0] Cassiopeia - Add selector to list overflow style
  templates/cassiopeia/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#33625 [4.0] Post installation module description
  administrator/language/en-GB/mod_post_installation_messages.ini
  administrator/language/en-GB/mod_post_installation_messages.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#33615 [4.0] mod_feed comment
  modules/mod_feed/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33623 [4.0] Title error message
  administrator/templates/atum/scss/blocks/_edit.scss
Labels: NPM Resource Changed, PR-4.0-dev

#33557 [4.0] replacing Bootstrap popover on com_content by already implemented css only version
  administrator/components/com_contact/src/Service/HTML/AdministratorService.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  layouts/joomla/button/action-button.php
  layouts/joomla/button/transition-button.php
  libraries/src/Button/PublishedButton.php
Labels: Language Change, PR-4.0-dev, RTC

#33622 [4.0] Status icons with count
  administrator/modules/mod_messages/tmpl/default.php
  administrator/modules/mod_post_installation_messages/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33611 [4.0] ] fix color selector box too big issue
  build/media_source/system/scss/_jquery-minicolors.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33491 [4] Smart Search: Content Maps Empty State
  administrator/components/com_finder/src/Model/MapsModel.php
  administrator/components/com_finder/src/View/Maps/HtmlView.php
  administrator/components/com_finder/tmpl/maps/emptystate.php
  administrator/language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#33607 [4.0] Dashboard add color
  administrator/templates/atum/scss/blocks/_quickicons.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33400 [4] Empty State for System-> Discover
  administrator/components/com_installer/src/Controller/DiscoverController.php
  administrator/components/com_installer/src/Model/DiscoverModel.php
  administrator/components/com_installer/src/View/Discover/HtmlView.php
  administrator/components/com_installer/tmpl/discover/emptystate.php
  administrator/language/en-GB/com_installer.ini
  layouts/joomla/content/emptystate.php
Labels: Language Change, PR-4.0-dev, RTC

#33613 [4.0] privacy data export email
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-05-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-05-07.sql
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
Labels: PR-4.0-dev, RTC

#33428 [4.0] Remove Migration Script
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev, RTC

#33598 [4][Banners] Remove zip file when downloading tracks
  administrator/components/com_banners/src/Model/TracksModel.php
Labels: PR-4.0-dev, RTC

#33582 [4][Atum] Remove bold from sidebar
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: NPM Resource Changed, PR-4.0-dev

#33621 [4.0] icon before link
  administrator/templates/atum/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33656 [4] s/v/V
  administrator/language/en-GB/tpl_atum.ini
Labels: Language Change, PR-4.0-dev

#33654 Fix some admin error page issues
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
Labels: PR-4.0-dev, RTC

#33668 [4.0] Message and post-install hide
  administrator/modules/mod_messages/tmpl/default.php
  administrator/modules/mod_post_installation_messages/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33676 [4.0] Missing icons
  components/com_users/tmpl/login/default_logout.php
  modules/mod_login/tmpl/default.php
Labels: RTC

#33677 [4.0] Fix console error
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: RTC

#33628 [4.0] Fix Sidebar "sub items" overflow when expanding/toggle menu
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33686 [4.0] Mail templates - Fix Paragraph and Remove Whitespace
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_messages.ini
  language/en-GB/com_users.ini
Labels: Language Change, PR-4.0-dev, RTC

#33682 [4.0] Remove - Use Default - for file selection dropdown in Mail Template attachment
  administrator/components/com_mails/forms/template.xml
Labels: PR-4.0-dev, RTC

#33678 [4.0] mod syndicate icon
  modules/mod_syndicate/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33638 [4.0] Ignore access level check while parsing SEF router
  libraries/src/Router/SiteRouter.php
Labels: PR-4.0-dev, RTC

#33437 [4.0] Remove FTP support for com_joomlaupdate
  administrator/components/com_joomlaupdate/restore.php
  administrator/components/com_joomlaupdate/src/Controller/DisplayController.php
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Helper/Select.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_reinstall.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_upload.php
  administrator/language/en-GB/com_joomlaupdate.ini
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#33568 [4.0] Input slider in media manager
  build/media_source/plg_media-action_resize/js/resize.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#33632 [4] Correctly implement Joomla toolbar in Versions popup
  administrator/components/com_contenthistory/src/View/History/HtmlView.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  build/media_source/com_contenthistory/js/admin-history-modal.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33674 [4] en-GB verses en-US - order the languages
  build/build-modules-js/error-pages.es6.js
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
Labels: PR-4.0-dev, RTC

#33666 [4.0] Remove _FRONTEND_LANGUAGE_DESC on the registration page
  components/com_users/forms/sitelang.xml
Labels: PR-4.0-dev, RTC

#33689 [4.0] Fix double header
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
Labels: PR-4.0-dev, RTC

#33581 [4.0] Change width in com_workflow
  administrator/components/com_workflow/tmpl/workflow/edit.php
Labels: PR-4.0-dev, RTC

#33631 [4.0] Add module to dashboard - save and close button
  administrator/components/com_cpanel/tmpl/cpanel/default.php
  administrator/components/com_modules/tmpl/module/modal.php
Labels: PR-4.0-dev, RTC

#33688 [4.0] com_media drag and drop
  build/media_source/com_media/scss/components/_media-browser.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33679 [4.0] Fix the console errors
  administrator/components/com_modules/tmpl/select/default.php
  build/media_source/com_modules/js/admin-module-search.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33710 s/Disable/Enable
  build/media_source/system/js/fields/passwordview.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#33705 [4.0] Download key merge error
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev, RTC

#33403 [4.0] Add toolbar.scss in Cassiopeia
  templates/cassiopeia/scss/blocks/_toolbar.scss
  templates/cassiopeia/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33693 [4] Remove 2000ms delay in checking for Joomla updates
  build/media_source/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33651 [4.0] use J4 namespacing
  administrator/templates/atum/component.php
  administrator/templates/atum/error.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  administrator/templates/system/component.php
  administrator/templates/system/error.php
Labels: PR-4.0-dev, RTC

#33149 [4] Dont show stats exceptions/failures/warnings to users
  plugins/system/stats/stats.php
Labels: PR-4.0-dev, RTC

#33708 [4.0] Fixed double click error
  layouts/joomla/form/field/password.php
Labels: PR-4.0-dev, RTC

#33707 [4.0] Batch update redirects
  administrator/components/com_redirect/tmpl/links/default_addform.php
Labels: PR-4.0-dev, RTC

#33636 [4.0] grayscale and hue background
  administrator/templates/atum/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33713 [4.0] sidebar-toggle color
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33715 [4.0] content maps
  administrator/components/com_finder/tmpl/maps/default.php
Labels: PR-4.0-dev, RTC

#33732 [4.0] media action resize
  administrator/language/en-GB/plg_media-action_resize.ini
  build/media_source/plg_media-action_resize/js/resize.es6.js
  plugins/media-action/resize/form/resize.xml
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC

#33733 [4] Smart Search: Search Filters Empty State
  administrator/components/com_finder/src/View/Filters/HtmlView.php
  administrator/components/com_finder/tmpl/filters/emptystate.php
  administrator/language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#33706 [4.0] update available
  administrator/language/en-GB/plg_quickicon_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev, RTC

#33734 [4.0] permission tabs background
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: NPM Resource Changed, PR-4.0-dev

#33747 [4.0] Change global configuration icon
  administrator/components/com_config/src/View/Application/HtmlView.php
  administrator/components/com_config/src/View/Component/HtmlView.php
Labels: PR-4.0-dev, RTC

#33744 [4.0] Remove edit button in toolbar
  administrator/components/com_installer/src/View/Updatesites/HtmlView.php
Labels: PR-4.0-dev, RTC

#33718 [4.0] make Atum error page use template params
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
Labels: PR-4.0-dev, RTC

#33766 [4.0] Update Notification emails
  plugins/system/updatenotification/updatenotification.php
Labels: PR-4.0-dev, RTC

#33760 [4.0] Disable Stats plugin
  plugins/system/stats/stats.php
Labels: PR-4.0-dev, RTC

#33756 [4.0] Header height atum
  administrator/modules/mod_user/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33804 [4] remove nested folder which is not needed
  templates/cassiopeia/templateDetails.xml
Labels: PR-4.0-dev, RTC

#33803 [4.0] Fix error sidecol position
  administrator/templates/atum/scss/blocks/_global.scss
  administrator/templates/atum/scss/blocks/_login.scss
Labels: PR-4.0-dev, RTC

#33780 Update styling of the User Profile page and the Single Contact page
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/contact/default_form.php
  components/com_users/tmpl/profile/default.php
  components/com_users/tmpl/profile/default_core.php
  templates/cassiopeia/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33726 [4.0] Changed color of Joomlaversion
  administrator/templates/atum/scss/blocks/_header.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33769 Makes check for field type="Hidden" case-insensitive
  libraries/src/Form/FormField.php
Labels: PR-4.0-dev, RTC

#33815 [4.0] Show Multilingual Associations menu for multilingual sites only
  administrator/modules/mod_menu/src/Menu/CssMenu.php
Labels: PR-4.0-dev, RTC

#33503 [4.0] Fix Custom Classes for Radio Fields
  layouts/joomla/form/field/radio/buttons.php
Labels: PR-4.0-dev, RTC

#33712 [4.0] Backend - Add style to Privacy Quickicon badge
  build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33828 [4.0] Click to check the checkbox in Languages - Overrides
  administrator/components/com_languages/tmpl/overrides/default.php
Labels: PR-4.0-dev, RTC

#33827 [4.0] Fix markup in Privacy Dashboard
  administrator/modules/mod_privacy_dashboard/tmpl/default.php
Labels: PR-4.0-dev, RTC

#33825 [4.0] Optimize code
  administrator/modules/mod_menu/src/Menu/CssMenu.php
Labels: PR-4.0-dev, RTC

#33785 [4.0] missing legend [a11y]
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  layouts/joomla/edit/global.php
Labels: Language Change, PR-4.0-dev, RTC

#33748 [4.0] Joomla style tooltip in com_redirect
  administrator/components/com_redirect/src/Service/HTML/Redirect.php
  administrator/components/com_redirect/tmpl/links/default.php
Labels: PR-4.0-dev, RTC

#33820 [4.0] Fix SQL error when updating from 3.10
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-05-04.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-05-04.sql
Labels: PR-4.0-dev, RTC, Release Blocker

#33735 [4.0] Backend - Fix Privacy Requests Alert
  build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
  plugins/quickicon/privacycheck/privacycheck.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33776 [4.0] Add Joomla style tooltip in com_messages
  administrator/components/com_messages/src/Service/HTML/Messages.php
Labels: PR-4.0-dev, RTC

#33777 [4.0] Cache Handler
  administrator/components/com_config/forms/application.xml
Labels: PR-4.0-dev, RTC

#33818 [4.0] Display Custom Fields for Frontend Contact View Conditionally
  components/com_contact/tmpl/contact/default_user_custom_fields.php
Labels: PR-4.0-dev, RTC

#33763 [4.0] Fix Modules Filter
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  administrator/components/com_modules/src/Service/HTML/Modules.php
Labels: PR-4.0-dev, RTC

#33811 [4.0] com_cpanel submenu
  administrator/modules/mod_submenu/tmpl/default.php
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33775 [4.0] Add class to CLOSE button
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
Labels: PR-4.0-dev, RTC

#33754 [4.0] Sidebar changes
  administrator/templates/atum/index.php
  build/media_source/mod_menu/js/admin-menu.es6.js
  build/media_source/templates/administrator/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33753 Fix com media layout
  administrator/components/com_media/resources/scripts/components/browser/items/row.vue
  build/media_source/com_media/scss/components/_media-browser.scss
  build/media_source/com_media/scss/components/_media-modal.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#33835 [4.0] Remove obsolete table "#__csp" from support.sql so it's not created on new installations
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
Labels: PR-4.0-dev, RTC

#33822 fix: Convert session ids returned from PostgreSQL
  plugins/user/joomla/joomla.php
Labels: PR-4.0-dev, RTC, Release Blocker

#33854 [4.0] Remove horizontal line above button
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_upload.php
  plugins/installer/folderinstaller/tmpl/default.php
  plugins/installer/urlinstaller/tmpl/default.php
Labels: PR-4.0-dev

#32710 setTemplate creates invalid template record
  libraries/src/Application/SiteApplication.php
Labels: PR-4.0-dev, RTC

#33742 Help scroll top
  administrator/components/com_admin/tmpl/help/default.php
  build/media_source/com_admin/joomla.asset.json
  build/media_source/com_admin/js/admin-help.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC
