Repository joomla/joomla-cms, pull requests merged in 2021-09, with the labels that each got.

#35373 [3] Change text when com_joomlaupdate update available
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: RTC, Language Change, PR-3.10-dev

#35079 Fix body overflow in dashboard due to dropdown
  administrator/templates/atum/html/layouts/chromes/well.php
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#34890 [4.0] Use preload instead of prefetch alternative
  templates/cassiopeia/component.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
  templates/cassiopeia/offline.php
  templates/cassiopeia/scss/global/fonts-web_fira-sans.scss
  templates/cassiopeia/scss/global/fonts-web_roboto+noto-sans.scss
  templates/cassiopeia/templateDetails.xml
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35481 [3.10] Fix javascript error for pre-update checker
  administrator/components/com_joomlaupdate/views/default/tmpl/default_preupdatecheck.php
  media/com_joomlaupdate/js/default.js
  media/com_joomlaupdate/js/default.min.js
Labels: RTC, PR-3.10-dev

#35483 [4.0] Delete obsolete pkg_search in extensions table on update from a 4.0 RC or Beta version
  administrator/components/com_admin/sql/updates/mysql/4.0.3-2021-09-04.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.3-2021-09-04.sql
Labels: RTC, PR-4.0-dev

#35469 Tab selector fixed
  administrator/components/com_plugins/tmpl/plugin/edit.php
Labels: RTC, PR-4.0-dev

#34765 [4.0] Capitalize "Hide all messages"
  administrator/language/en-GB/com_postinstall.ini
Labels: RTC, Language Change, PR-4.0-dev

#35138 [4] Remove PHP from a plain text file
  installation/INSTALL
Labels: RTC, PR-4.0-dev

#35017 [4.0] Make note field hideable
  libraries/src/Form/Field/NoteField.php
Labels: RTC, PR-4.0-dev

#35139 [4] Remove default secret
  installation/configuration.php-dist
Labels: RTC, PR-4.0-dev

#35523 [4.0] Show help for system menuitems
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: RTC, PR-4.0-dev

#35459 [4] fix undefined class
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/reinstall.php
Labels: PR-4.0-dev

#35531 Allow the translation bot to recompile the htmls
  build/build-modules-js/init/cleanup-media.es6.js
Labels: PR-4.0-dev

#35533 [4.0] One more
  build/build-modules-js/init/cleanup-media.es6.js
Labels: PR-4.0-dev

#35510 [3.10] Fix misleading "Update Required" in the pre-update checker
  administrator/components/com_joomlaupdate/controllers/update.php
  administrator/components/com_joomlaupdate/models/default.php
  libraries/src/Updater/Update.php
Labels: PR-3.10-dev

#35457 [4.0] Make transitions translateable
  administrator/components/com_admin/sql/updates/mysql/4.0.3-2021-09-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.3-2021-09-05.sql
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/language/en-GB/joomla.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  language/en-GB/joomla.ini
  libraries/src/Form/Field/TransitionField.php
Labels: RTC, Language Change, PR-4.0-dev

#35049 [4.0] Editors have only the resolved url for images
  build/media_source/system/js/fields/joomla-media-select.w-c.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35478 [4.0] Update deleted files and folders for 4.0.3
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#35553 Fix Cassiopeia Offline
  templates/cassiopeia/offline.php
Labels: PR-4.0-dev

#35564 [4] Adapt modal articles to articles
  administrator/components/com_content/tmpl/articles/modal.php
Labels: RTC, PR-4.0-dev

#35576 [3.10] Fix category data lost on failure save
  administrator/components/com_categories/controllers/category.php
Labels: RTC, PR-3.10-dev

#35383 [3] backport of #35362
  libraries/src/MVC/Model/BaseDatabaseModel.php
Labels: PR-3.10-dev

#35602 s/joomla.org/the Joomla! project
  administrator/language/en-GB/en-GB.plg_system_updatenotification.ini
Labels: Language Change, PR-3.10-dev

#35590 [4.0.x] Update skipto
  package-lock.json
Labels: PR-4.0-dev, NPM Resource Changed

#35388 ZIP extraction helper for Joomla Update
  administrator/components/com_admin/script.php
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/finalisation.php
  administrator/components/com_joomlaupdate/joomlaupdate.xml
  administrator/components/com_joomlaupdate/restore.php
  administrator/components/com_joomlaupdate/restore_finalisation.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/tmpl/update/default.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/lib_joomla.ini
  build/media_source/com_joomlaupdate/joomla.asset.json
  build/media_source/com_joomlaupdate/js/admin-update-default.es6.js
  build/media_source/com_joomlaupdate/js/encryption.es5.js
  build/media_source/com_joomlaupdate/js/update.es5.js
Labels: RTC, Language Change, Documentation Required, PR-4.0-dev, NPM Resource Changed

#35455 Fixes Debug bar not displaying logs by default #35454
  plugins/system/debug/debug.php
Labels: RTC

#35589 [4.0] Logged in users module
  administrator/modules/mod_logged/tmpl/disabled.php
Labels: RTC, PR-4.0-dev

#35577 [J4] Adds support for custom class on subforms via xml
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable.php
Labels: RTC, PR-4.0-dev

#35549 remove cassiopeia/images/system
  templates/cassiopeia/images/system/sort_asc.png
  templates/cassiopeia/images/system/sort_desc.png
Labels: RTC, PR-4.0-dev

#35605 [4.x] Tinymce updates
  package-lock.json
  plugins/editors/tinymce/tinymce.xml
Labels: PR-4.0-dev, NPM Resource Changed

#34703 Mozilla cacert update via Github Action
  .github/workflows/cacert-update.yml
Labels: PR-3.10-dev

#35613 [4.0] s/.htacess/.htaccess
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev

#35614 [3] remove example text
  libraries/legacy/application/application.php
Labels: PR-3.10-dev

#35615 [3] s/nessicary/necessary
  libraries/fof/encrypt/base32.php
Labels: PR-3.10-dev

#35616 s/categogy/category
  components/com_content/models/articles.php
Labels: PR-3.10-dev

#35479 [4.0] Remove JHELP_ strings for com_config
  administrator/components/com_actionlogs/config.xml
  administrator/components/com_associations/config.xml
  administrator/components/com_banners/config.xml
  administrator/components/com_cache/config.xml
  administrator/components/com_checkin/config.xml
  administrator/components/com_contact/config.xml
  administrator/components/com_content/config.xml
  administrator/components/com_finder/config.xml
  administrator/components/com_installer/config.xml
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_languages/config.xml
  administrator/components/com_mails/config.xml
  administrator/components/com_media/config.xml
  administrator/components/com_menus/config.xml
  administrator/components/com_messages/config.xml
  administrator/components/com_modules/config.xml
  administrator/components/com_newsfeeds/config.xml
  administrator/components/com_plugins/config.xml
  administrator/components/com_postinstall/config.xml
  administrator/components/com_privacy/config.xml
  administrator/components/com_redirect/config.xml
  administrator/components/com_tags/config.xml
  administrator/components/com_templates/config.xml
  administrator/components/com_users/config.xml
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.0-dev

#35629 [4.1] Add Joomla! Accessibility Team to the code owners
  .github/CODEOWNERS
Labels: RTC, PR-4.1-dev

#35626 [4.0] Fix modal data attributes
  layouts/libraries/html/bootstrap/modal/main.php
  libraries/src/HTML/Helpers/Bootstrap.php
Labels: RTC, PR-4.0-dev

#35638 Fix group in twofactorauth plugins
  plugins/twofactorauth/totp/totp.xml
  plugins/twofactorauth/yubikey/yubikey.xml
Labels: PR-3.10-dev

#35534 [4.0] Remove JHELP_ strings for com_categories
  administrator/components/com_banners/forms/category.xml
  administrator/components/com_categories/src/View/Categories/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_contact/forms/category.xml
  administrator/components/com_content/forms/category.xml
  administrator/components/com_newsfeeds/forms/category.xml
  administrator/components/com_users/forms/category.xml
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.0-dev

#35547 Category custom fields marked as 'subform' act as if they are not
  administrator/components/com_fields/src/Field/SubfieldsField.php
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  plugins/fields/subform/subform.php
  plugins/system/fields/fields.php
Labels: RTC, PR-4.0-dev, RLDQ

#35509 [4][CloudFlare Issues] Remove validation of the session by IP address
  libraries/src/Service/Provider/Session.php
Labels: RTC, PR-4.0-dev

#35659 [4.0] Language Keys may have a : in it.
  libraries/src/Language/Language.php
Labels: RTC

#35540 [4.0] Fix smart search fatal error
  administrator/components/com_finder/src/Indexer/Indexer.php
Labels: RTC, PR-4.0-dev

#35636 [4.0] Fix undefined constant "GLOB_BRACE" error when using TinyMCE on certain OS like e.g. Alpine Linux
  plugins/editors/tinymce/tinymce.php
Labels: RTC, PR-4.0-dev

#35666 [4.0] Update SASS to 1.42
  package-lock.json
  package.json
Labels: PR-4.0-dev, NPM Resource Changed

#35695 [4.0] remove extra spaces
  administrator/components/com_users/forms/fields/user.xml
Labels: RTC, PR-4.0-dev

#35556 [4.0] Check in media field if image is set
  plugins/fields/media/tmpl/media.php
Labels: RTC, PR-4.0-dev
