Repository joomla/joomla-cms, pull requests merged in 2021-08, with the labels that each got.

#34986 [4.0] Fix searchtools error checkActiveStatus
  build/media_source/system/js/searchtools.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34996 [4.0] Fix fatal error while uninstall deleted plugin
  libraries/src/Installer/Adapter/PluginAdapter.php
Labels: PR-4.0-dev, RTC

#34954 [4.0] Updating or uninstalling one library no longer removes another when both belong to same vendor.
  libraries/src/Installer/Adapter/LibraryAdapter.php
Labels: PR-4.0-dev, RTC

#35038 [4.0] remove file check
  plugins/fields/media/tmpl/media.php
Labels: PR-4.0-dev, RTC

#35024 [4.0] fix the path for Cassiopeia js
  build/media_source/templates/site/cassiopeia/js/mod_menu/menu-metismenu.es6.js
  templates/cassiopeia/html/mod_menu/dropdown-metismenu.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#35001 [4.0] Added php8 to list of filtered extensions
  libraries/src/Filter/InputFilter.php
Labels: PR-4.0-dev, Release Blocker

#35026 Fix language strings plural suffixes unit test failing when executing JLanguageTest.php alone
  tests/unit/suites/libraries/joomla/language/JLanguageTest.php
  tests/unit/suites/libraries/joomla/language/data/language/en-GB/en-GB.localise.php
Labels: PR-staging, RTC, Unit/System Tests

#35011 [4.0] Uncaught TypeError in mobile view if article is open
  administrator/templates/atum/html/layouts/status.php
Labels: PR-4.0-dev, RTC

#35022 [4.0] tab focus
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#35058 [4.0] Fix missing npm update of custom elements
  package-lock.json
Labels: Release Blocker, PR-4.0-dev, NPM Resource Changed

#28700 [staging] Fix jalali calendar javascript
  media/system/js/fields/calendar-locales/date/jalali/date-helper.js
  media/system/js/fields/calendar-locales/date/jalali/date-helper.min.js
Labels: RTC, PR-staging

#35037 Remove wrong information from code comment
  administrator/components/com_installer/models/updatesites.php
Labels: RTC, PR-staging

#35034 [3.10] Don't use hard-coded extension_id to insert the EOS310 plugin in update SQL scripts
  administrator/components/com_admin/sql/updates/mysql/3.10.0-2021-05-28.sql
  administrator/components/com_admin/sql/updates/postgresql/3.10.0-2021-05-28.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.10.0-2021-05-28.sql
Labels: PR-3.10-dev

#35061 [4.0] Remove wrong bootstrap css
  templates/cassiopeia/scss/vendor/bootstrap/_dropdown.scss
Labels: PR-4.0-dev, NPM Resource Changed

#35070 [4.0] Exclude "/media/system/images" from files and folders deletion on update
  administrator/components/com_admin/script.php
  build/deleted_file_check.php
Labels: PR-4.0-dev

#35039 [4.0] short and sweet fix
  build/build-modules-js/init/minify-vendor.es6.js
  build/build-modules-js/init/patches.es6.js
  build/build-modules-js/init/recreate-media.es6.js
  package-lock.json
  package.json
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#34999 [4.0] Check target file extension of com_media rename action
  libraries/src/Filter/InputFilter.php
  libraries/src/Helper/MediaHelper.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: Release Blocker, PR-4.0-dev, J4 Media Manager

#35000 Added php8 to list of forbidden executable extensions
  libraries/src/Filter/InputFilter.php
Labels: PR-staging

#35045 [4.0] com_contact.contact. Empty params (null) in onContentPrepare of a plugin
  components/com_contact/src/View/Contact/HtmlView.php
Labels: RTC, PR-4.0-dev

#35074 [4.0] Fix mail template API failing with SQL error when creating mail templates programmatically
  libraries/src/Mail/MailTemplate.php
Labels: PR-4.0-dev

#35073 Update branches and fix some references still pointing to staging
  .drone.jsonnet
  .github/CONTRIBUTING.md
  README.md
  README.txt
  composer.json
  libraries/vendor/composer/autoload_classmap.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.php
Labels: Composer Dependency Changed, PR-3.10-dev

#32541 Make fontawesome+icomoon mapping available as Joomla asset
  build/media_source/system/scss/joomla-fontawesome.scss
  templates/cassiopeia/joomla.asset.json
  templates/cassiopeia/scss/vendor/fontawesome-free/fontawesome.scss
Labels: RTC, PR-4.0-dev, J4 Issue, NPM Resource Changed, J4 Frontend Template

#33052 [4.0] Collapse / accordion function for categories list
  build/media_source/com_categories/css/shared-categories-accordion.css
  build/media_source/com_categories/joomla.asset.json
  build/media_source/com_categories/js/shared-categories-accordion.es6.js
  components/com_content/tmpl/categories/default.php
  components/com_content/tmpl/categories/default_items.php
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35069 [4.0] Eliminating cpanel jumping
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/com_cpanel/js/admin-system-loader.es6.js
  build/media_source/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_source/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
  build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#34989 [4] create a new admin menu with preset - postgresql
  administrator/components/com_menus/src/Helper/MenusHelper.php
Labels: PR-4.0-dev

#35076 [4.0] Update Information
  administrator/templates/atum/scss/pages/_com_joomlaupdate.scss
  administrator/templates/atum/scss/template.scss
Labels: PR-4.0-dev, NPM Resource Changed

#34994 [4.0] Fix the Reset button
  build/media_source/com_media/js/edit-images.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35077 [4.0] Update deleted files and folders for RC 6
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#35084 [4.0] composer update
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#35097 Update installation language date on version bump
  build/bump.php
  installation/language/en-GB/langmetadata.xml
  installation/language/en-US/langmetadata.xml
Labels: Language Change, PR-4.0-dev

#35108 Add a note about WSL based setups to the build script
  build/build.php
Labels: PR-3.10-dev

#35092 [3.10] Apply PHP 5.3 combat changes to the core code and lessphp + phpmailer
  administrator/components/com_joomlaupdate/models/default.php
  composer.lock
  libraries/vendor/composer/installed.json
  libraries/vendor/composer/installed.php
  libraries/vendor/leafo/lessphp/lessc.inc.php
  libraries/vendor/phpmailer/phpmailer/class.phpmaileroauthgoogle.php
Labels: Composer Dependency Changed, Release Blocker, PR-3.10-dev

#35105 [3.10] Disable the critical plugins check for non-major updates.
  administrator/components/com_joomlaupdate/views/default/view.html.php
Labels: Release Blocker, PR-3.10-dev

#35109 [4.0] Use com_mails/access.xml for permissions
  administrator/components/com_mails/config.xml
Labels: PR-4.0-dev

#35093 [4.0] Fix categories accordion
  build/media_source/com_categories/joomla.asset.json
  build/media_source/com_categories/js/shared-categories-accordion.es6.js
  components/com_content/tmpl/categories/default.php
  components/com_content/tmpl/categories/default_items.php
Labels: RTC, NPM Resource Changed

#35121 Add missing class 'Route'
  administrator/components/com_joomlaupdate/src/Controller/DisplayController.php
Labels: PR-4.0-dev

#35128 [4.0] build script exclusions
  build/build.php
Labels: PR-4.0-dev

#35130 Update deleted files and folders for stable
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#35127 Update IFW Plugin version to 4.0.0
  plugins/installer/webinstaller/webinstaller.xml
Labels: Release Blocker, PR-4.0-dev

#35134 [4] Improve english sentence
  build/build.php
Labels: PR-4.0-dev

#35113 [4.0] Fix assets for workflow tables for new installations and updates
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-08-13.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-08-13.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, Release Blocker, PR-4.0-dev

#35146 [4] Remove createSession method
  libraries/src/Factory.php
Labels: PR-4.0-dev

#35151 [4] s/exits/exists
  administrator/components/com_categories/src/View/Categories/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
Labels: PR-4.0-dev

#35149 Corrected 'could not copy files' message
  libraries/src/Installer/Adapter/LibraryAdapter.php
Labels: RTC, PR-4.0-dev

#35152 [4.0] [a11y] Fix broken aria reference in mod_language_switcher
  modules/mod_languages/tmpl/default.php
Labels: PR-4.0-dev

#35140 [4] remove redundant sessions folder in installation
  .gitignore
  installation/sessions/.gitignore
Labels: PR-4.0-dev

#34961 Add new logging category and add sample log entry for it
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/CMSApplication.php
Labels: RTC

#35012 Push footer to bottom and fix content vertically centered and fix scroll to top
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
  templates/cassiopeia/js/template.es5.js
  templates/cassiopeia/js/template.js
  templates/cassiopeia/js/template.min.js
  templates/cassiopeia/scss/blocks/_back-to-top.scss
  templates/cassiopeia/scss/blocks/_css-grid.scss
  templates/cassiopeia/scss/blocks/_layout.scss
Labels: RTC, Release Blocker, PR-4.0-dev, NPM Resource Changed

#34900 [4.0] Render the full information in the installer
  installation/template/scss/template.scss
  installation/tmpl/setup/default.php
Labels: RTC, NPM Resource Changed

#35164 Handle com_search migration to a core supported extension
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-08-17.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-08-17.sql
  administrator/manifests/packages/pkg_search.xml
  build/build.php
Labels: Test instructions missing, PR-4.0-dev

#35168 Installation cleanup
  composer.lock
  installation/src/Model/CleanupModel.php
  installation/template/js/remove.js
  installation/tmpl/remove/default.php
Labels: Composer Dependency Changed, Release Blocker, PR-4.0-dev

#35173 [4.0] Fix installation js for messages
  installation/template/js/remove.js
Labels: PR-4.0-dev

#35171 Accept failing opcache_invalidate on installation
  installation/src/Model/CleanupModel.php
Labels: PR-4.0-dev

#35176 Combine update statements for package_id of search extensions
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-08-17.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-08-17.sql
Labels: Release Blocker, PR-4.0-dev

#35193 [4] Typo of s/__DEPLOY_VERSION_/4.0.0
  libraries/src/Changelog/Changelog.php
Labels: PR-4.0-dev

#35194 [4] Correct FQCN for WebAssetManager
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/reinstall.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/update.php
  administrator/components/com_joomlaupdate/tmpl/upload/default.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu.php
Labels: PR-4.0-dev

#35187 [4] Remove undefined class
  administrator/components/com_joomlaupdate/restore.php
Labels: PR-4.0-dev

#35198 Build tools clean up/audit/fixes
  build/build-modules-js/init/recreate-media.es6.js
  build/build-modules-js/settings.json
  build/build-modules-js/watch.es6.js
  build/build.js
  package-lock.json
  package.json
Labels: PR-4.0-dev, NPM Resource Changed

#35192 [4] s/Tag/TagTable
  components/com_tags/src/Model/TagModel.php
Labels: PR-4.0-dev

#35188 [4] s/Controller/BaseController
  components/com_wrapper/src/Controller/DisplayController.php
Labels: PR-4.0-dev

#35202 Fix JS CS
  build/build-modules-js/watch.es6.js
Labels: PR-4.0-dev

#35201 Upgrade Joomla Browser to non-codeception namespace
  composer.lock
  tests/Codeception/acceptance.suite.dist.yml
Labels: Unit/System Tests, Composer Dependency Changed, PR-4.0-dev

#35203 Attempt fixes for test failures
  composer.lock
  tests/Codeception/_support/Helper/JoomlaDb.php
  tests/Codeception/acceptance.suite.dist.yml
Labels: Unit/System Tests, Test instructions missing, Composer Dependency Changed, PR-4.0-dev

#35199 [4] Add folder permissions check for com_joomlaupdate
  administrator/components/com_admin/src/Model/SysinfoModel.php
Labels: PR-4.0-dev

#35191 [4] Provide the correct return types so that `package` is not interpreted as a return type.
  administrator/components/com_installer/src/Model/InstallModel.php
Labels: PR-4.0-dev

#35186 Correct typo of "__DEPLOY VERSION__" with correct released version 4.0.0
  libraries/src/Document/JsonapiDocument.php
Labels: PR-4.0-dev

#35159 [4] Remove space in XML Atom Feed
  libraries/src/Document/Renderer/Feed/AtomRenderer.php
Labels: RTC, PR-4.0-dev

#35236 s/recomile/recompile
  build/README.md
Labels: PR-4.0-dev

#35235 s/__VERSION_DEPLOY__/4.0.0
  libraries/src/Form/Field/MediaField.php
Labels: PR-4.0-dev

#35237 s/Authenication/Authentication
  build/README.md
Labels: PR-4.0-dev

#35242 s/__DEPOY_VERSION__/__DEPLOY_VERSION__/
  libraries/src/Filter/InputFilter.php
Labels: PR-4.0-dev

#35243 Add PHP6|7|8 to file extensions to scan for short tags
  libraries/src/Filter/InputFilter.php
Labels: PR-4.0-dev

#35241 Correct typehint
  plugins/sampledata/testing/testing.php
Labels: Test instructions missing, PR-4.0-dev

#35239 correct typehint
  administrator/components/com_privacy/tmpl/capabilities/default.php
Labels: PR-4.0-dev

#35240 correct typehint
  administrator/components/com_privacy/tmpl/consents/default.php
Labels: PR-4.0-dev

#35233 [4] Dont attempt LDAP connection if no host provided
  plugins/authentication/ldap/ldap.php
Labels: PR-4.0-dev

#35221 [4.0] Add deprecation note for CMSObject
  libraries/src/Object/CMSObject.php
Labels: PR-4.0-dev

#35065 [4.0] fix translator note in joomla.ini / plg_editors_tinymce.ini
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/plg_editors_tinymce.ini
  api/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.0-dev

#35131 [4] replace deprecated class call
  libraries/src/Helper/ModuleHelper.php
Labels: RTC, PR-4.0-dev

#35124 [4] Code cleanup
  libraries/src/Console/ExtensionDiscoverListCommand.php
Labels: RTC, PR-4.0-dev

#35125 [4] Code Cleanup
  libraries/src/Form/Rule/FolderPathExistsRule.php
Labels: RTC, PR-4.0-dev

#34965 [4.0] Replace Factory::getDbo() with $this->getDbo()
  administrator/components/com_finder/src/Model/FilterModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_languages/src/Model/OverridesModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/src/Model/TemplatesModel.php
Labels: RTC, PR-4.0-dev

#31143 [4.1] Log deprecated only when explicitly requested
  administrator/includes/framework.php
  api/includes/framework.php
  includes/framework.php
  libraries/bootstrap.php
  libraries/src/Document/Renderer/Html/MessageRenderer.php
  libraries/src/Exception/ExceptionHandler.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Language/Text.php
  libraries/src/Log/Log.php
  libraries/src/MVC/View/HtmlView.php
  libraries/src/MVC/View/JsonView.php
  libraries/src/Pagination/Pagination.php
  libraries/src/Router/Route.php
  libraries/src/Session/Session.php
  libraries/src/Toolbar/Toolbar.php
  plugins/system/debug/debug.php
Labels: RTC, PR-4.1-dev

#35064 [4.0] fix typo in translator note
  language/en-GB/mod_footer.ini
Labels: RTC, Language Change, PR-4.0-dev

#35214 [3.10] com_joomlaupdate pointing to joomla 4 when showing as Default in upgraded systems with longer history
  administrator/components/com_joomlaupdate/models/default.php
Labels: PR-3.10-dev

#35135 [4] docblock s/string/array
  libraries/src/Language/Text.php
Labels: RTC, PR-4.0-dev

#35148 [3.10] [4.0] Fix wrong number of parameters for sprintf
  administrator/language/en-GB/en-GB.lib_joomla.ini
  language/en-GB/en-GB.lib_joomla.ini
  libraries/src/Http/Transport/SocketTransport.php
  libraries/src/Mail/Mail.php
Labels: Language Change, PR-3.10-dev

#34340 [4] When using path::clean, a security method, correctly throw a useable exception.
  libraries/src/Filesystem/Path.php
Labels: PR-4.0-dev

#35284 Remove non functioning Third Party GA Beacon
  README.md
Labels: PR-4.0-dev

#35253 [4] Add padding in breadcrumbs when "You are here" not shown.
  modules/mod_breadcrumbs/tmpl/default.php
Labels: RTC, PR-4.0-dev

#35271 [3.10] Backport Add folder permissions check for com_joomlaupdate
  administrator/components/com_admin/models/sysinfo.php
Labels: RTC, PR-3.10-dev

#35270 [3.10] Backport: Add PHP6|7|8 to file extensions to scan for short tags
  libraries/src/Filter/InputFilter.php
Labels: RTC, PR-3.10-dev

#35163 [3.10] Add missing mssql updates
  administrator/components/com_admin/sql/updates/sqlazure/3.10.1-2021-08-17.sql
  installation/sql/sqlazure/joomla.sql
Labels: RTC, PR-3.10-dev

#35272 [3.10] Remove unused fields so they do not cause javascript errors during pre-update check
  administrator/components/com_joomlaupdate/models/default.php
Labels: PR-3.10-dev

#35269 [3.10] Make sure the pre-Upgrade Checker is only shown when there is a update
  administrator/components/com_joomlaupdate/views/default/tmpl/default_update.php
  administrator/components/com_joomlaupdate/views/default/view.html.php
Labels: PR-3.10-dev

#35295 Improve size of user list - alternative to #35285
  administrator/components/com_users/tmpl/users/default.php
Labels: RTC, PR-4.0-dev

#35292 [4] Cleanup of restore.php - Remove redundant constructor
  administrator/components/com_joomlaupdate/restore.php
Labels: RTC, PR-4.0-dev

#35290 [4] Cleanup of restore.php - duplicated copyright/license blocks.
  administrator/components/com_joomlaupdate/restore.php
Labels: RTC, PR-4.0-dev

#35293 [4] Cleanup of restore.php - Remove redundant translation strings
  administrator/components/com_joomlaupdate/restore.php
Labels: PR-4.0-dev

#35280 [4] Code Style
  templates/system/fatal.php
Labels: RTC, PR-4.0-dev

#35294 [4] Highlight the Home Dashboard link only when active page
  build/media_source/mod_menu/js/admin-menu.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35265 [4] Same Easing for Logo and Sidebar transition
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35258 [4] s/mixed/boolean
  libraries/src/Versioning/VersionableControllerTrait.php
Labels: RTC, PR-4.0-dev

#35222 Fix CalendarField::filter to use correct format
  libraries/src/Form/Field/CalendarField.php
Labels: RTC, Release Blocker, PR-4.0-dev

#35266 [4] Solve Logo overflow over the header title
  administrator/templates/atum/scss/blocks/_header.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35154 [J4] not working switch RECORD HITS
  administrator/components/com_content/config.xml
Labels: RTC, PR-4.0-dev

#34881 [4.0] use _blank as target
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_privacy.ini
Labels: RTC, Language Change, PR-4.0-dev

#34846 [4.0] Add opening/closing p tag
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.0-dev

#34845 [4.0] change %s to %d
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_checkin.ini
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_contenthistory.ini
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/com_modules.ini
  administrator/language/en-GB/com_plugins.ini
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/com_workflow.ini
  administrator/language/en-GB/plg_installer_override.ini
  administrator/language/en-GB/plg_quickicon_downloadkey.ini
  installation/language/en-GB/joomla.ini
  language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.0-dev

#32915 [4] Ensure opcache file invalidate on file copy & delete
  administrator/components/com_admin/script.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_joomlaupdate/restore.php
  administrator/components/com_joomlaupdate/restore_finalisation.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  installation/src/Model/CleanupModel.php
  installation/src/Model/ConfigurationModel.php
  libraries/src/Cache/Storage/FileStorage.php
  libraries/src/Filesystem/File.php
  libraries/src/Installer/Installer.php
Labels: PR-4.0-dev

#35309 Fix `class_exists` checks in `restore_finalisation.php`
  administrator/components/com_joomlaupdate/restore_finalisation.php
Labels: RTC, Release Blocker, PR-4.0-dev

#35220 [4] Dont delete /installation in development mode
  installation/tmpl/remove/default.php
Labels: RTC, PR-4.0-dev

#35209 [4.0] Load default language overrides
  libraries/src/Language/Language.php
Labels: RTC, PR-4.0-dev

#35133 [4] Remove J prefix from Class name
  libraries/src/Application/CMSApplication.php
Labels: RTC, PR-4.0-dev

#34958 [4.0] com_config site hr
  components/com_config/tmpl/config/default.php
  components/com_config/tmpl/templates/default.php
Labels: RTC, PR-4.0-dev

#35307 [4.0] Update deleted files and folders for 4.0.1
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#35225 Fix caching when HTMLDocument::countModules is used
  libraries/src/Document/HtmlDocument.php
  libraries/src/Document/Renderer/Html/ModuleRenderer.php
  libraries/src/Helper/ModuleHelper.php
Labels: RTC, Release Blocker, PR-4.0-dev

#34990 [4.0] Menu preset export fix warning
  administrator/components/com_menus/src/View/Menu/XmlView.php
Labels: RTC, PR-4.0-dev

#35310 [4] Build tools should preserve the original timestamps
  build/build-modules-js/error-pages.es6.js
  build/build-modules-js/init/cleanup-media.es6.js
  build/build-modules-js/init/common/concat-files.es6.js
  build/build-modules-js/init/common/copy-all-files.es6.js
  build/build-modules-js/init/exemptions/codemirror.es6.js
  build/build-modules-js/init/exemptions/tinymce.es6.js
  build/build-modules-js/init/localise-packages.es6.js
  build/build-modules-js/init/minify-vendor.es6.js
  build/build-modules-js/init/patches.es6.js
  build/build-modules-js/init/recreate-media.es6.js
  build/build-modules-js/javascript/build-bootstrap-js.es6.js
  build/build-modules-js/javascript/handle-es5.es6.js
  build/build-modules-js/javascript/minify.es6.js
  build/build-modules-js/stylesheets/handle-css.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/build-modules-js/versioning.es6.js
Labels: PR-4.0-dev

#35189 [4] Fix undefined classes in params
  components/com_contenthistory/src/Controller/DisplayController.php
Labels: RTC, PR-4.0-dev

#35327 [3.x] joomlaupdate comment
  administrator/components/com_joomlaupdate/models/default.php
Labels: PR-3.10-dev

#35333 [4.0.1] Fix for constructors missing
  administrator/components/com_joomlaupdate/restore.php
Labels: PR-4.0-dev

#35336 bump updater version
  administrator/components/com_joomlaupdate/joomlaupdate.xml
Labels: PR-4.0-dev

#35343 [3] s/timout/timeout
  administrator/components/com_installer/models/update.php
Labels: PR-3.10-dev

#35348 [3] s/cachtimeout/cachetimeout
  plugins/system/updatenotification/postinstall/updatecachetime.php
Labels: RTC, PR-3.10-dev

#35352 [4] Include custom fatal page so that any post-processing, alerting, can happen as designed
  templates/system/fatal.php
Labels: PR-4.0-dev

#35356 [4.0] Update Message
  administrator/components/com_installer/src/Model/UpdateModel.php
Labels: RTC, PR-4.0-dev

#35339 [4] Fix spinner bg
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35367 [4][com_finder] min value zero for Multiplier options
  administrator/components/com_finder/config.xml
Labels: RTC, PR-4.0-dev

#35116 [4.0] Quick Icons description
  administrator/language/en-GB/mod_quickicon.ini
Labels: RTC, Language Change, PR-4.0-dev

#35142 [4.0] Subform styling for non table layout
  administrator/templates/atum/scss/blocks/_form.scss
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable-table/section.php
  layouts/joomla/form/field/subform/repeatable/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable/section.php
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35397 [4.0] Add missing edit action in MM permissions
  administrator/components/com_media/access.xml
Labels: RTC, PR-4.0-dev

#35409 [4] remove unused import
  templates/cassiopeia/html/mod_menu/dropdown-metismenu.php
Labels: RTC, PR-4.0-dev

#35410 [4] remove unused import
  administrator/components/com_templates/src/Model/TemplatesModel.php
Labels: RTC, PR-4.0-dev

#35411 [4] remove unused import
  libraries/src/Factory.php
Labels: RTC, PR-4.0-dev

#35415 [4.0] 3rd party QuickIcon fix
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: RTC, PR-4.0-dev

#35417 Fix Batch Button: Illegal invocation, in joomla.toolbar.batch
  layouts/joomla/toolbar/batch.php
Labels: RTC, PR-4.0-dev

#35412 [4] Calculate the header space correctly
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: RTC, PR-4.0-dev
