Repository joomla/joomla-cms, pull requests merged in 2021-06, with the labels that each got.

#34325 [4] Fix default state of toggle for behind_loadbalancer
  administrator/components/com_config/forms/application.xml
Labels: PR-4.0-dev, RTC

#34316 [4] The Download Key is missing color
  administrator/components/com_installer/tmpl/update/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: PR-4.0-dev, RTC

#34332 [4.0] Resolve dropdown truncated on home dashboard
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: NPM Resource Changed, PR-4.0-dev

#34334 [4.0] Welcome to Joomla message #34304
  administrator/language/en-GB/com_cpanel.ini
Labels: Language Change, PR-4.0-dev

#34339 [4] Prevent fatal error by importing use CategoryFactoryInterface
  components/com_tags/src/Service/Router.php
Labels: PR-4.0-dev

#34338 [4] Prevent fatal error by importing \Exception
  components/com_contact/src/Model/FormModel.php
Labels: PR-4.0-dev

#34336 [4] correct return type
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverListCommandTest.php
Labels: PR-4.0-dev, Unit/System Tests

#34326 [4.0] Mail Templates Help`
  administrator/help/en-GB/toc.json
  administrator/language/en-GB/com_admin.ini
Labels: Language Change, PR-4.0-dev, RTC

#34335 [4] correct namespace for RuntimeException
  libraries/src/Application/CMSApplication.php
Labels: PR-4.0-dev

#34329 [4.0] open docu link in new window, com_templates
  administrator/language/en-GB/com_templates.ini
Labels: Language Change, PR-4.0-dev

#34337 [4] Fix fatal error by calling correct class name
  components/com_newsfeeds/src/Helper/AssociationHelper.php
Labels: PR-4.0-dev

#34312 [4.0] quickicon class
  layouts/joomla/quickicons/icon.php
Labels: PR-4.0-dev, RTC

#34093 [4] webservices consistency
  api/components/com_content/src/Serializer/ContentSerializer.php
  plugins/webservices/contact/contact.php
  plugins/webservices/content/content.php
  plugins/webservices/privacy/privacy.php
  plugins/webservices/redirect/redirect.php
  tests/Codeception/api/BasicCest.php
  tests/Codeception/api/com_contact/ContactCest.php
  tests/Codeception/api/com_content/ContentCest.php
Labels: Documentation Required, PR-4.0-dev, RLDQ, Unit/System Tests, Webservices

#34290 Apply PHPCS to the build tools and remove unused md5/sha1 hashes
  build/build.php
  build/bump.php
  build/stubGenerator.php
Labels: PR-staging, RTC

#34345 [4.0] key exists is an alias
  components/com_fields/layouts/field/render.php
  components/com_fields/layouts/fields/render.php
  libraries/src/Application/ConsoleApplication.php
Labels: PR-4.0-dev, RTC

#34346 [4.0] concat spaces
  layouts/joomla/content/category_default.php
  layouts/joomla/content/intro_image.php
  layouts/joomla/edit/frontediting_modules.php
  layouts/joomla/form/field/media.php
  layouts/joomla/form/field/tag.php
  layouts/joomla/toolbar/basic.php
  layouts/joomla/toolbar/popup.php
  layouts/joomla/toolbar/standard.php
Labels: PR-4.0-dev, RTC

#34344 [4] Case in function/method call doesn't match the case in declaration
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev

#34343 [4] fix undefined namespace autocompletion in IDEs
  components/com_users/src/Controller/DisplayController.php
  libraries/src/Event/GenericEvent.php
  plugins/system/debug/src/DataCollector/InfoCollector.php
  plugins/system/debug/src/DataCollector/LanguageErrorsCollector.php
  plugins/system/debug/src/DataCollector/LanguageFilesCollector.php
  plugins/system/debug/src/DataCollector/LanguageStringsCollector.php
  plugins/system/debug/src/DataCollector/ProfileCollector.php
  plugins/system/debug/src/DataCollector/SessionCollector.php
Labels: PR-4.0-dev

#34342 [4.0] copy paste fix
  administrator/components/com_banners/tmpl/banner/edit.php
  administrator/components/com_banners/tmpl/client/edit.php
  administrator/components/com_categories/tmpl/category/edit.php
  administrator/components/com_contact/tmpl/contact/edit.php
  administrator/components/com_content/tmpl/article/edit.php
  administrator/components/com_fields/tmpl/field/edit.php
  administrator/components/com_fields/tmpl/group/edit.php
  administrator/components/com_finder/tmpl/filter/edit.php
  administrator/components/com_languages/tmpl/language/edit.php
  administrator/components/com_languages/tmpl/override/edit.php
  administrator/components/com_menus/tmpl/item/edit.php
  administrator/components/com_menus/tmpl/menu/edit.php
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_newsfeeds/tmpl/newsfeed/edit.php
  administrator/components/com_privacy/tmpl/request/edit.php
  administrator/components/com_redirect/tmpl/link/edit.php
  administrator/components/com_tags/tmpl/tag/edit.php
  administrator/components/com_users/tmpl/group/edit.php
  administrator/components/com_users/tmpl/level/edit.php
  administrator/components/com_users/tmpl/note/edit.php
  administrator/components/com_users/tmpl/user/edit.php
  administrator/components/com_workflow/tmpl/stage/edit.php
  administrator/components/com_workflow/tmpl/transition/edit.php
  administrator/components/com_workflow/tmpl/workflow/edit.php
Labels: PR-4.0-dev

#34357 Update Sites filtering breaks when changing the "Select Download Key"
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
Labels: PR-4.0-dev

#34354 Joomla Update pre-update checks for third party extensions are wrong
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#34352 [4.0] Tags Service Router clean up
  components/com_tags/src/Service/Router.php
Labels: PR-4.0-dev

#34360 [4.0] fix copyright date
  build/media_source/com_admin/js/admin-help.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#34251 Make sure the status is always 0
  administrator/components/com_privacy/models/request.php
Labels: PR-staging, RTC

#34350 [4.0] Fix MediaField with custom directory
  libraries/src/Form/Field/MediaField.php
Labels: PR-4.0-dev, RTC

#34319 [4] Cleanup Module Empty State Layout
  layouts/joomla/content/emptystate_module.php
Labels: PR-4.0-dev, RTC

#34318 [4] Set the correct default for record_hits when using php
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_content/src/View/Featured/HtmlView.php
  administrator/modules/mod_popular/mod_popular.php
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Form/Field/ListField.php
  modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
Labels: PR-4.0-dev, RTC

#34050 [4.0] Routing: Fix notice in NoMenu rule
  libraries/src/Component/Router/Rules/NomenuRules.php
Labels: PR-4.0-dev, RTC

#34373 [4.0] empty state mod_latest and mod_popular
  administrator/modules/mod_latest/mod_latest.php
  administrator/modules/mod_popular/mod_popular.php
Labels: PR-4.0-dev, RTC

#34366 [4.0] System Database
  administrator/components/com_menus/presets/system.xml
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#34328 [4] Correct warning alerts colours and joomla-alert custom element css
  administrator/templates/atum/scss/_variables.scss
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
Labels: PR-4.0-dev, RTC

#34323 [4] Change notefield form field to display better
  plugins/user/token/forms/token.xml
Labels: PR-4.0-dev, RTC

#34281 [4.0] Fieldset is missing a Legendtag
  administrator/modules/mod_login/tmpl/default.php
Labels: PR-4.0-dev, RTC

#34376 [4.0] Fix navigation path to database check in language string after PR #34366
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev

#34385 [4.0] Unexpected white space
  administrator/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#34392 [4.0] Unifying the same language string in three joomla.ini files
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: RTC

#34398 [4.0] Unificaton of language string JGLOBAL_BLOG_CLASS
  api/language/en-GB/joomla.ini
Labels: PR-4.0-dev

#34395 [4.0] calendar css
  build/media_source/system/css/fields/calendar-rtl.css
  build/media_source/system/css/fields/calendar.css
Labels: NPM Resource Changed, PR-4.0-dev

#34394 [4.0] Restore pagination padding with highlighted links
  administrator/templates/atum/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34274 [4][webservices] PATCH verb
  libraries/src/MVC/Controller/ApiController.php
Labels: PR-4.0-dev, Webservices

#34386 [4.0] Hide save buttons when no download key field in Update Sites
  administrator/components/com_installer/src/View/Updatesite/HtmlView.php
Labels: PR-4.0-dev, RTC

#34409 [4.0] Broken language strings
  administrator/language/en-GB/com_modules.ini
Labels: Language Change, PR-4.0-dev

#33344 [4.0] Post Installation: Fix Messages Notification Count
  administrator/components/com_postinstall/src/Controller/DisplayController.php
  administrator/components/com_postinstall/src/Model/MessagesModel.php
  administrator/modules/mod_post_installation_messages/mod_post_installation_messages.php
  administrator/modules/mod_post_installation_messages/tmpl/default.php
Labels: PR-4.0-dev, RTC

#34380 [4.0] Composer update joomla/utilities
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev, RTC

#34416 [4.0] Expand all
  administrator/language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev

#34415 [4.0] privacy request sidebar
  administrator/components/com_privacy/src/View/Request/HtmlView.php
Labels: PR-4.0-dev

#34413 [4.0] plg installer non-existent string
  plugins/installer/urlinstaller/tmpl/default.php
Labels: PR-4.0-dev

#34407 [4.0] remove com_joomlaupdate scss
  administrator/templates/atum/scss/pages/_com_joomlaupdate.scss
  administrator/templates/atum/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev

#34411 [4.0] missing string
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js
  plugins/editors/tinymce/tinymce.php
Labels: RTC

#34406 [4.0] remove com_admin scss
  administrator/templates/atum/scss/pages/_com_admin.scss
  administrator/templates/atum/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev

#34403 [4.0] remove com_finder scss
  administrator/templates/atum/scss/pages/_com_finder.scss
  administrator/templates/atum/scss/template.scss
Labels: NPM Resource Changed, PR-4.0-dev

#34375 [4.0] Fix drag and drop re-ordering for grouped items
  build/media_source/system/js/draggable.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34399 [4.0] capitalisation of styles
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-06-04.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-06-04.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev, RTC

#34412 [4.0] Dont try to translate missing label
  libraries/src/Form/FormField.php
Labels: PR-4.0-dev, RTC

#34422 [4.0] Fix query after prepared statements
  modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
Labels: PR-4.0-dev, RTC

#34429 [4.0] Home icon on dashboard
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34420 [4.0] Messaging : options missing string
  administrator/language/en-GB/com_messages.ini
Labels: Language Change, PR-4.0-dev, RTC

#34423 [4.0] codemirror update
  package-lock.json
  plugins/editors/codemirror/codemirror.xml
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34433 [4.0] Reinitialise the installer's cached extensions table's properties after a core update.
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: PR-4.0-dev, Release Blocker

#34142 [4.0] atum Remove underline from badges
  administrator/templates/atum/scss/pages/_com_cpanel.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34310 [4.0] options sidebar
  administrator/components/com_config/tmpl/application/default_navigation.php
  administrator/components/com_config/tmpl/component/default_navigation.php
  administrator/templates/atum/scss/blocks/_sidebar-nav.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34320 [4] hits - Move rendering from outside of the model
  modules/mod_articles_popular/mod_articles_popular.php
  modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
Labels: PR-4.0-dev, RTC

#33900 [4.0] Fix radio buttons in batch processing
  administrator/components/com_fields/tmpl/fields/default_batch_body.php
  administrator/components/com_menus/tmpl/items/default_batch_body.php
Labels: PR-4.0-dev, RTC

#34441 [4.0] admin module descriptions
  administrator/language/en-GB/mod_messages.ini
  administrator/language/en-GB/mod_messages.sys.ini
  administrator/language/en-GB/mod_post_installation_messages.ini
  administrator/language/en-GB/mod_post_installation_messages.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#34418 [4.0] com contact unused fields
  administrator/components/com_contact/config.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/language/en-GB/com_contact.ini
Labels: Language Change, PR-4.0-dev, RTC

#34421 Composer update joomla/utilities
  composer.lock
  libraries/vendor/composer/installed.json
  libraries/vendor/joomla/utilities/src/ArrayHelper.php
  libraries/vendor/joomla/utilities/src/IpHelper.php
Labels: Composer Dependency Changed, PR-staging, RTC

#34434 [4.0] add rel attribute in joomla.ini
  installation/language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#34444 [4.0] Improving the display of an arrow in language string in "plg_system_updatenotification.*"
  administrator/language/en-GB/com_associations.ini
  administrator/language/en-GB/com_cpanel.ini
  administrator/language/en-GB/com_modules.ini
  administrator/language/en-GB/plg_system_stats.ini
  administrator/language/en-GB/plg_system_updatenotification.ini
  administrator/language/en-GB/plg_system_updatenotification.sys.ini
  language/en-GB/mod_login.ini
  language/en-GB/mod_login.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#34458 [4.0] s/encription/encryption
  libraries/src/Console/SetConfigurationCommand.php
Labels: PR-4.0-dev

#34454 [4.0] com_admin typos
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion.sql
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion_optional.sql
Labels: PR-4.0-dev

#34457 [4.0] s/proccess/process
  libraries/src/Application/DaemonApplication.php
Labels: PR-4.0-dev

#34459 [4.0] s/minumum/minimum
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  libraries/src/Updater/Update.php
Labels: PR-4.0-dev

#34455 [4.0] quickicon helper
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: PR-4.0-dev

#34447 [4][webservices] fix contenthistory GET
  api/components/com_contenthistory/src/Controller/HistoryController.php
Labels: PR-4.0-dev, Webservices

#34461 [4.0] help sidebar onhover
  administrator/components/com_admin/tmpl/help/default.php
Labels: PR-4.0-dev, RTC

#34462 [4.0] Cleanup Blog Sample Data Plugin
  plugins/sampledata/blog/blog.php
Labels: PR-4.0-dev, RTC

#34460 [4.0] Multilingual sample data cleanup
  plugins/sampledata/multilang/multilang.php
Labels: PR-4.0-dev, RTC

#34452 [4.0] Replace double quote with single quote
  administrator/components/com_associations/src/Field/Modal/AssociationField.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
  components/com_content/tmpl/article/default_links.php
  layouts/joomla/editors/buttons/modal.php
  layouts/joomla/form/field/contenthistory.php
  layouts/joomla/form/field/media.php
  layouts/plugins/system/privacyconsent/label.php
  layouts/plugins/user/terms/label.php
  libraries/src/Form/Field/ModulepositionField.php
  plugins/user/profile/src/Field/TosField.php
Labels: PR-4.0-dev, RTC

#34449 [4.0] Smart Search when plugin is disabled
  administrator/components/com_finder/src/Controller/DisplayController.php
  administrator/components/com_finder/src/View/Index/HtmlView.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/language/en-GB/com_finder.ini
Labels: Language Change, PR-4.0-dev, RTC

#34465 [4.0] Active sidebar (menu collapsing)
  build/media_source/mod_menu/js/admin-menu.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34466 ARIA IDs are not unique when there are multiple menu's active
  modules/mod_menu/tmpl/collapse-default.php
  templates/cassiopeia/html/mod_menu/collapse-metismenu.php
Labels: PR-4.0-dev, RTC, a11y

#34456 [4.0] com_joomlaupdate typos
  administrator/components/com_joomlaupdate/restore.php
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34483 Fix W3C Warning role="navigation" is unnecessary for element nav
  administrator/components/com_media/resources/scripts/components/breadcrumb/breadcrumb.vue
  layouts/joomla/pagination/links.php
  layouts/joomla/pagination/list.php
  modules/mod_breadcrumbs/tmpl/default.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34408 [4.0] legend css
  administrator/templates/atum/scss/blocks/_form.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34439 [4.0] double translate extension name
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php
Labels: PR-4.0-dev, RTC

#33877 Fix the mobile menu wrongly expanding the logo
  administrator/templates/atum/index.php
  build/media_source/mod_menu/js/admin-menu.es6.js
  build/media_source/templates/administrator/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34049 [3] Routing: Fix notice in NoMenuRule
  libraries/src/Component/Router/Rules/NomenuRules.php
Labels: PR-staging, RTC

#34391 [3.9] Custom Fields : missing value class rendering
  components/com_fields/layouts/field/render.php
Labels: PR-staging, RTC

#34486 [4.0] Hide up/down selector arrows for Hits readonly
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_redirect/forms/link.xml
  administrator/components/com_tags/forms/tag.xml
Labels: PR-4.0-dev, RTC

#34341 Make sure the text files are only generated when needed
  build/build.php
Labels: PR-staging

#34490 [4.0] element-invisible
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php
Labels: PR-4.0-dev

#34489 [4.0] sr-only
  components/com_menus/layouts/joomla/searchtools/default.php
Labels: PR-4.0-dev

#34487 [4.0] Fix sorted by: table caption
  layouts/joomla/searchtools/grid/sort.php
Labels: PR-4.0-dev, RTC

#34493 [4.0] Remove arrows/spinners from ID readonly field
  administrator/components/com_banners/forms/banner.xml
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/forms/group.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_redirect/forms/link.xml
  administrator/components/com_tags/forms/tag.xml
  administrator/components/com_users/forms/user.xml
Labels: RTC

#34481 [4.0] Sanitization for code using insertAdjacentHTML
  build/media_source/com_finder/js/indexer.es6.js
  build/media_source/plg_system_stats/js/stats-message.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#34480 [4.0] Sanitize modals
  build/media_source/vendor/bootstrap/js/modal.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#31567 [4.0] Subform fixes
  administrator/templates/atum/scss/blocks/_edit.scss
  administrator/templates/atum/scss/blocks/_form.scss
  layouts/joomla/form/field/subform/default.php
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section.php
  layouts/joomla/form/field/subform/repeatable.php
  layouts/joomla/form/renderfield.php
  libraries/src/Form/Field/SubformField.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34495 [4.0] Update files and folders deletion on updates to 4.0 RC 2
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#34469 [4.0] Change order of fields and add description in content global options
  administrator/components/com_content/config.xml
Labels: PR-4.0-dev, RTC

#34482 [4.0] Fix searchtool JS error
  build/media_source/system/js/searchtools.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34435 [4.0] alphabetical sorting in com_joomlaupdate
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.0-dev, RTC

#34488 [4][webservices] refactor the URLs for contenthistory
  plugins/webservices/banners/banners.php
  plugins/webservices/contact/contact.php
  plugins/webservices/content/content.php
Labels: Documentation Required, PR-4.0-dev, Webservices

#34472 [4.0] JS files are full of XSS
  administrator/components/com_config/src/Field/FiltersField.php
  administrator/components/com_media/resources/scripts/app/Notifications.es6.js
  administrator/components/com_media/resources/scripts/plugins/translate.es6.js
  build/media_source/com_associations/js/admin-associations-default.es6.js
  build/media_source/com_associations/js/associations-edit.es6.js
  build/media_source/com_associations/js/sidebyside.es5.js
  build/media_source/com_contenthistory/js/admin-compare-compare.es6.js
  build/media_source/com_contenthistory/js/admin-history-modal.es6.js
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/com_cpanel/js/admin-system-loader.es6.js
  build/media_source/com_finder/js/filters.es6.js
  build/media_source/com_finder/js/finder-edit.es6.js
  build/media_source/com_finder/js/index.es6.js
  build/media_source/com_finder/js/indexer.es6.js
  build/media_source/com_finder/js/maps.es6.js
  build/media_source/com_installer/js/changelog.es6.js
  build/media_source/com_joomlaupdate/js/default.es6.js
  build/media_source/com_languages/js/overrider.es6.js
  build/media_source/com_modules/js/admin-module-edit.es6.js
  build/media_source/com_users/js/admin-users-groups.es6.js
  build/media_source/com_users/js/admin-users-mail.es6.js
  build/media_source/legacy/js/ajax-chosen.es5.js
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  build/media_source/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_source/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
  build/media_source/plg_system_webauthn/js/login.es6.js
  build/media_source/plg_system_webauthn/js/management.es6.js
  build/media_source/plg_user_token/js/token.es6.js
  build/media_source/system/js/fields/calendar.es5.js
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-module-order.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-permissions.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  build/media_source/system/js/fields/passwordstrength.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/joomla-hidden-mail.w-c.es6.js
  build/media_source/system/js/searchtools.es6.js
  build/media_source/vendor/bootstrap/js/tab.es6.js
  installation/template/js/setup.js
  installation/template/js/template.js
  layouts/joomla/toolbar/batch.php
  libraries/src/Toolbar/Button/ConfirmButton.php
  libraries/src/Toolbar/Button/StandardButton.php
  plugins/installer/webinstaller/webinstaller.php
Labels: NPM Resource Changed, PR-4.0-dev, Release Blocker

#34505 [4.0] Remove 3.9.27 update SQL scripts after upmerge from 3.10-dev
  administrator/components/com_admin/sql/updates/mysql/3.9.27-2021-04-20.sql
  administrator/components/com_admin/sql/updates/postgresql/3.9.27-2021-04-20.sql
Labels: PR-4.0-dev

#34507 [4.0] FLoC options
  administrator/components/com_config/forms/application.xml
Labels: PR-4.0-dev, RTC

#34506 [4.0] Newsfeed hits field
  administrator/components/com_newsfeeds/forms/newsfeed.xml
Labels: PR-4.0-dev, RTC

#34509 [4.0] Remove media helper from files and folder deletion in script.php
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev, Release Blocker

#34513 [4.0] Fix form validation error
  build/media_source/system/js/fields/validate.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34517 [4.0] Add padding between button and Insert Tags
  administrator/components/com_mails/tmpl/template/edit.php
Labels: PR-4.0-dev, RTC

#34503 [4.0] Smart Search: Fix inserting tokens to DB
  administrator/components/com_finder/src/Indexer/Indexer.php
Labels: PR-4.0-dev, RTC

#34402 [4.0] Fix subform: add row at correct position
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: PR-4.0-dev, RTC

#34514 [4.0] Allow form elements in a subform template (sanitisation)
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34516 [4.0] Fix com_joomlaupdate js error
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#33864 [4.0] Remove unused file
  administrator/components/com_admin/script.php
  administrator/components/com_fields/tmpl/field/modal.php
  build/media_source/com_fields/joomla.asset.json
  build/media_source/com_fields/js/admin-field-edit-modal.es6.js
Labels: PR-4.0-dev, RTC

#34521 [4.0] Update deleted files in script.php to changes from PR #33864
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#34526 [4.0] useractions spelling
  administrator/language/en-GB/com_actionlogs.ini
Labels: Language Change, PR-4.0-dev

#34303 [4.0] Use unset filter to unset created_by data if needed
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_fields/src/Model/GroupModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
Labels: PR-4.0-dev

#34530 [4.0] Make a list for flags in mail-templates
  administrator/components/com_mails/tmpl/templates/default.php
Labels: PR-4.0-dev, RTC

#34478 [4.0] Convert inline to file and remove jQuery
  administrator/components/com_config/src/Field/FiltersField.php
  build/media_source/com_config/joomla.asset.json
  build/media_source/com_config/js/config-filters.es6.js
Labels: NPM Resource Changed, PR-4.0-dev

#34550 [4.0] Learn more
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: Language Change, PR-4.0-dev, RTC

#34552 [4.0] table header font weight
  templates/cassiopeia/scss/vendor/bootstrap/_table.scss
Labels: NPM Resource Changed, PR-4.0-dev

#34535 [4.0] Reorder Featured in Sort Table By dropdown
  administrator/components/com_contact/forms/filter_contacts.xml
  administrator/components/com_content/forms/filter_articles.xml
Labels: PR-4.0-dev, RTC

#34575 [4.0] Workflow Transitions sort
  administrator/components/com_workflow/forms/filter_transitions.xml
  administrator/language/en-GB/com_workflow.ini
Labels: Language Change, PR-4.0-dev

#34580 [4.0] Typo: descending, not decending
  administrator/language/en-GB/com_workflow.ini
Labels: Language Change, PR-4.0-dev

#34569 [4.0] License.php
  administrator/language/en-GB/plg_api-authentication_token.ini
  administrator/language/en-GB/plg_api-authentication_token.sys.ini
  administrator/language/en-GB/plg_system_accessibility.ini
  administrator/language/en-GB/plg_system_accessibility.sys.ini
  administrator/language/en-GB/plg_system_webauthn.ini
  administrator/language/en-GB/plg_system_webauthn.sys.ini
  administrator/language/en-GB/plg_user_token.ini
  administrator/language/en-GB/plg_user_token.sys.ini
  administrator/language/en-GB/plg_webservices_installer.ini
  administrator/language/en-GB/plg_webservices_installer.sys.ini
  administrator/language/en-GB/plg_workflow_featuring.ini
  administrator/language/en-GB/plg_workflow_featuring.sys.ini
  administrator/language/en-GB/plg_workflow_notification.ini
  administrator/language/en-GB/plg_workflow_notification.sys.ini
  administrator/language/en-GB/plg_workflow_publishing.ini
  administrator/language/en-GB/plg_workflow_publishing.sys.ini
Labels: Language Change, PR-4.0-dev, RTC

#34331 [3] Fix Undefined class RuntimeException
  libraries/src/Application/CMSApplication.php
Labels: PR-staging, RTC

#34583 [4.0] com_newsfeeds list feeds in a category
  components/com_newsfeeds/tmpl/category/default.xml
  components/com_newsfeeds/tmpl/category/default_items.php
Labels: PR-4.0-dev, RTC

#34578 [4.0] Constant unused in J4 / com_admin
  administrator/language/en-GB/com_admin.ini
Labels: Language Change, PR-4.0-dev, RTC

#34591 [4.0] Build tools: watch functionality revised
  build/README.md
  build/build-modules-js/javascript/build-com_media-js.es6.js
  build/build-modules-js/watch.es6.js
  build/build.js
Labels: NPM Resource Changed, PR-4.0-dev

#34598 [4.0] phpmailer - security update
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev, Release Blocker

#34612 [4.0] bootstrap 5.0.2
  package-lock.json
  package.json
Labels: PR-4.0-dev, RTC

#34610 [4.0] Clarify build tools
  build/README.md
Labels: PR-4.0-dev, RTC

#34615 [4.0] com_categories [a11y] tooltips
  administrator/components/com_categories/tmpl/categories/default.php
Labels: PR-4.0-dev, RTC

#34627 [4.0] com_menus counts [a11y]
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/language/en-GB/com_menus.ini
Labels: Language Change, PR-4.0-dev, RTC

#34629 [4.0] com_users groups counts [a11y]
  administrator/components/com_users/tmpl/groups/default.php
Labels: PR-4.0-dev, RTC

#34630 [4.0] com_finder indexed content [a11y]
  administrator/components/com_finder/tmpl/maps/default.php
Labels: PR-4.0-dev, RTC

#34581 [4.0] PlgSystemDebug fix: Deprecated usort() Returning bool.
  plugins/system/debug/src/Storage/FileStorage.php
Labels: PHP 8, PR-4.0-dev, RTC

#34618 [4.0] Fix class for selectlist of contacts
  components/com_contact/tmpl/contact/default.php
Labels: PR-4.0-dev, RTC

#34608 Fix metismenu caret wrapping
  templates/cassiopeia/html/mod_menu/dropdown-metismenu_component.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu_url.php
  templates/cassiopeia/scss/blocks/_header.scss
  templates/cassiopeia/scss/vendor/metismenu/_metismenu.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34584 [4.0] Fix Drag'n'Drop a parent-category show children-categories only after page-refresh
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  build/media_source/system/js/draggable.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34520 [4.0] Fix drag and drop ordering
  build/media_source/system/js/draggable.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34576 [4.0] contact icons
  build/media_source/system/scss/_icomoon.scss
Labels: PR-4.0-dev, RTC

#34554 [4.0] com_content set default date field
  administrator/components/com_content/config.xml
Labels: PR-4.0-dev, RTC

#34563 [4.0] Add charactercount to metadescription in contact form
  components/com_contact/forms/form.xml
Labels: PR-4.0-dev, RTC

#34579 [4.0] input border
  administrator/templates/atum/scss/blocks/_form.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#34565 [4.0] character count
  administrator/components/com_menus/forms/item_component.xml
Labels: PR-4.0-dev, RTC

#34614 [4.0] Content versions button [a11y]
  administrator/components/com_contenthistory/tmpl/history/modal.php
Labels: PR-4.0-dev, RTC

#34537 [4.0] Modify modal window and remove orphan label in privacy consent and terms and conditions fields
  administrator/language/en-GB/plg_system_privacyconsent.ini
  administrator/language/en-GB/plg_user_terms.ini
  layouts/plugins/system/privacyconsent/label.php
  layouts/plugins/system/privacyconsent/message.php
  layouts/plugins/user/terms/label.php
  layouts/plugins/user/terms/message.php
  plugins/system/privacyconsent/forms/privacyconsent.xml
  plugins/user/terms/forms/terms.xml
Labels: Language Change, PR-4.0-dev, RTC

#34638 [4.0] Add back "/libraries/vendor/bin" to folder deletion in script.php
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev, RTC

#34644 [4.0] media manager toolbar
  administrator/templates/atum/scss/blocks/_toolbar.scss
Labels: PR-4.0-dev, RTC
