Repository joomla/joomla-cms, pull requests merged in 2021-01, with the labels that each got.

#31772 [4.0] html5 chrome fix [a11y] and markup
  layouts/chromes/html5.php
Labels: PR-4.0-dev

#31823 [4.0] Mail Templates mobile
  administrator/components/com_mails/tmpl/templates/default.php
Labels: PR-4.0-dev

#31826 Updated installation INI file
  installation/language/tr-TR/tr-TR.ini
  installation/language/tr-TR/tr-TR.xml
Labels: Language Change, PR-staging

#30043 [4.0] [cosmetics] Remove variable type mixing in display controller / view
  administrator/components/com_joomlaupdate/src/Controller/DisplayController.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
Labels: PR-4.0-dev

#31834 [4.0] Output correct error message for com_messages
  administrator/components/com_messages/src/Model/MessageModel.php
  administrator/components/com_messages/src/View/Message/HtmlView.php
Labels: PR-4.0-dev

#31822 Add Comment for translators not to touch lines of code
  administrator/language/en-GB/en-GB.com_cpanel.ini
Labels: Language Change, PR-staging, RTC

#31807 [4.0] Normalizing contacts filters in backend and xtd modal
  administrator/components/com_contact/forms/filter_contacts.xml
  components/com_contact/forms/filter_contacts.xml
  components/com_content/forms/filter_articles.xml
Labels: PR-4.0-dev, RTC

#31830 [4.0] Move image box in media manager to bottom
  administrator/components/com_media/tmpl/file/default.php
  build/media_source/com_media/js/edit-images.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31835 [4.0] Ensure language code is validated in the mail template
  administrator/components/com_mails/src/Model/TemplateModel.php
  administrator/language/en-GB/com_mails.ini
Labels: Language Change, PR-4.0-dev, RTC

#31827 [4.0] Fix awesomplete dropdown z-index
  templates/cassiopeia/scss/vendor/_awesomplete.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31819 [4.0] Media field: Uncaught TypeError: MediaXTDElements is undefined
  build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31840 s/http/https
  .editorconfig
Labels: PR-staging

#31841 s/messasge/message
  administrator/components/com_messages/models/message.php
Labels: PR-staging

#31831 [4.0] Fix width in com_modules batch position select
  administrator/components/com_modules/tmpl/modules/default_batch_body.php
Labels: PR-4.0-dev, RTC

#31824 [4.0] com_users webauthn svg
  components/com_users/tmpl/login/default_login.php
Labels: PR-4.0-dev, RTC

#31832 [4.0] Rename Levels to Access Levels in system dashboard
  administrator/components/com_menus/presets/system.xml
  administrator/language/en-GB/mod_menu.ini
Labels: Language Change, PR-4.0-dev, RTC

#31844 [4.0] correction for 31832
  administrator/components/com_menus/presets/system.xml
  administrator/language/en-GB/mod_menu.ini
Labels: Language Change, PR-4.0-dev

#31677 [4.0] Refactor and Cleanup JLIB_FILESYTEM strings
  administrator/language/en-GB/lib_joomla.ini
  installation/language/en-GB/joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Cache/Storage/FileStorage.php
  libraries/src/Filesystem/File.php
  libraries/src/Filesystem/Folder.php
Labels: PR-4.0-dev, RTC

#31839 [4.0] Align icon and text in search button
  templates/cassiopeia/scss/vendor/_awesomplete.scss
Labels: PR-4.0-dev, RTC

#31845 [4.0] Cover cases where the image can't be parsed
  libraries/src/Image/Exception/UnparsableImageException.php
  libraries/src/Image/Image.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: PR-4.0-dev, RTC

#31730 Pull request for #27530 - Make dropdown close at clicking anywhere else
  build/media_source/templates/atum/js/template.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31833 [4.0] Cleanup build files that have been removed
  build/build.php
  tests/Codeception/exclude.txt
Labels: PR-4.0-dev, RTC

#31449 [4.0] Fix old null dates for created times of core content
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-04-22.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-06-28.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-06-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-14.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-23.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-10-17.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-12-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-04-22.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-06-28.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-06-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-14.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-23.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-10-17.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-12-19.sql
Labels: PR-4.0-dev, Release Blocker

#31847 [4.0] TinyMCE help
  plugins/editors/tinymce/src/Field/TinymcebuilderField.php
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev, RTC

#31736 [4.0] COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#31856 [4.0] Menu list readability [a11y]
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/modal.php
Labels: RTC

#31858 [4.0] Wrong tip for COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-4.0-dev, RTC

#31863 [4.0] Disable accessibility plugin in modal
  plugins/system/accessibility/accessibility.php
Labels: PR-4.0-dev

#31853 [4.0] Allow 3rd party scss compiling scripts to coexist with own build tools
  build/build-modules-js/compilecss.es6.js
Labels: PR-4.0-dev

#31872 Revert "Fixing admin user activation"
  plugins/system/languagefilter/languagefilter.php
Labels: PR-staging

#31621 [4.0] Converting additional mails to mail templates
  administrator/components/com_actionlogs/layouts/logstable.php
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-12-08.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-12-08.sql
  administrator/components/com_mails/src/Model/TemplatesModel.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_messages/src/Model/MessageModel.php
  administrator/components/com_privacy/src/Model/ExportModel.php
  administrator/components/com_privacy/src/Model/RequestModel.php
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_messages.ini
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/plg_system_privacyconsent.ini
  components/com_privacy/src/Model/RequestModel.php
  components/com_users/src/Model/RegistrationModel.php
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
  language/en-GB/com_privacy.ini
  language/en-GB/com_users.ini
  plugins/system/privacyconsent/privacyconsent.php
Labels: Language Change, PR-4.0-dev, Release Blocker

#31811 [3.10] Backport placeholder interface for Table classes in Joomla 4
  libraries/src/Tag/TaggableTableInterface.php
  libraries/src/Tag/TaggableTableTrait.php
Labels: PR-3.10-dev

#31879 [4.0] Fix merge conflict from PR 31672
  administrator/components/com_config/forms/application.xml
  layouts/joomla/form/field/password.php
Labels: PR-4.0-dev

#31886 [4.0] Setup legacy CLI app with proper dispatcher and container
  libraries/src/Application/CliApplication.php
Labels: PR-4.0-dev

#31885 [4.0] Minor Cleanup of workflow code
  administrator/components/com_workflow/src/View/Stages/HtmlView.php
  libraries/src/MVC/Model/WorkflowBehaviorTrait.php
  libraries/src/Workflow/Workflow.php
  plugins/sampledata/multilang/multilang.php
Labels: Documentation Required, PR-4.0-dev

#31897 [4.0] Use email field type for password reset
  components/com_users/forms/reset_request.xml
Labels: PR-4.0-dev, RTC

#31932 s/translateable/translatable
  administrator/components/com_content/src/Helper/ContentHelper.php
Labels: RTC

#31935 s/objecct/object
  libraries/src/Installer/Adapter/ModuleAdapter.php
Labels: RTC

#31933 s/externel/external
  administrator/components/com_finder/src/Indexer/Language/El.php
Labels: RTC

#31930 s/Midlename/Middlename
  components/com_contact/src/View/Contact/VcfView.php
Labels: RTC

#31931 s/Allways/Always
  administrator/components/com_joomlaupdate/views/default/view.html.php
Labels: RTC

#31929 s/releated/related
  plugins/workflow/featuring/featuring.php
Labels: RTC

#31907 [4.0] Fix two factor error on profile page
  plugins/twofactorauth/totp/tmpl/form.php
Labels: RTC

#31939 [4.0] Fix 2 strings in com_templates.ini (#31710)
  administrator/language/en-GB/com_templates.ini
Labels: RTC

#31944 [4.0] Update component.php in Cassiopeia
  templates/cassiopeia/component.php
Labels: PR-4.0-dev, RTC

#31963 [4.0] php version check message
  administrator/language/en-GB/plg_quickicon_phpversioncheck.ini
Labels: Language Change, PR-4.0-dev

#31895 [4.0] TinyMCE quickbars
  plugins/editors/tinymce/tinymce.php
Labels: PR-4.0-dev

#31948 s/transiterating/transliterating
  libraries/src/Filesystem/File.php
Labels: PR-4.0-dev, RTC

#31947 s/curent/current
  libraries/src/Image/Filter/Backgroundfill.php
Labels: PR-4.0-dev, RTC

#31953 s/croppping/cropping
  libraries/src/Image/Image.php
Labels: PR-4.0-dev

#31956 s/translateable/translatable
  libraries/src/Mail/MailTemplate.php
Labels: PR-4.0-dev, RTC

#31958 [4.0] Articles - Categories H tags
  modules/mod_articles_categories/tmpl/default_items.php
Labels: PR-4.0-dev

#31945 [4] return built in constants instead of hand typed integers
  libraries/src/Console/AddUserCommand.php
  libraries/src/Console/AddUserToGroupCommand.php
  libraries/src/Console/ChangeUserPasswordCommand.php
  libraries/src/Console/CheckJoomlaUpdatesCommand.php
  libraries/src/Console/CheckUpdatesCommand.php
  libraries/src/Console/CleanCacheCommand.php
  libraries/src/Console/DeleteUserCommand.php
  libraries/src/Console/ExtensionsListCommand.php
  libraries/src/Console/FinderIndexCommand.php
  libraries/src/Console/GetConfigurationCommand.php
  libraries/src/Console/ListUserCommand.php
  libraries/src/Console/RemoveOldFilesCommand.php
  libraries/src/Console/RemoveUserFromGroupCommand.php
  libraries/src/Console/SessionGcCommand.php
  libraries/src/Console/SessionMetadataGcCommand.php
Labels: PR-4.0-dev

#31884 [4.0] Adding accessibility settings to admin profile view
  administrator/components/com_admin/forms/profile.xml
  administrator/language/en-GB/com_admin.ini
Labels: Language Change, PR-4.0-dev

#30409 [4.0][com_postinstall] cache 1 query result
  administrator/components/com_postinstall/src/Model/MessagesModel.php
Labels: PR-4.0-dev, RTC

#31940 [4.0] Banner TracksExport modal
  administrator/components/com_banners/tmpl/tracks/default.php
  layouts/joomla/toolbar/modal.php
Labels: PR-4.0-dev, RTC

#31972 s/Cummulative/Cumulative
  administrator/components/com_finder/helpers/indexer/indexer.php
Labels: RTC

#31978 Updated installation language files for fa-IR
  installation/language/fa-IR/fa-IR.ini
  installation/language/fa-IR/fa-IR.xml
Labels: Language Change, PR-staging

#31988 s/deletion/uninstall
  administrator/language/en-GB/plg_extension_namespacemap.ini
  administrator/language/en-GB/plg_extension_namespacemap.sys.ini
Labels: Language Change, PR-4.0-dev

#32001 s/string/array in docblock
  administrator/components/com_redirect/src/Field/RedirectField.php
  administrator/components/com_users/src/Model/UsersModel.php
Labels: PR-4.0-dev

#31996 [4] Remove un-used imports
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  administrator/components/com_privacy/src/Controller/RequestController.php
  administrator/components/com_workflow/src/Controller/StagesController.php
  administrator/components/com_workflow/src/Controller/WorkflowsController.php
  administrator/components/com_workflow/src/Table/TransitionTable.php
  components/com_media/src/Dispatcher/Dispatcher.php
  layouts/joomla/searchtools/default.php
  libraries/src/Router/SiteRouter.php
  libraries/src/Tag/TaggableTableTrait.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu.php
Labels: PR-4.0-dev

#31994 [4] Remove factually incorrect docblock
  components/com_config/src/Controller/ConfigController.php
Labels: PR-4.0-dev

#32000 [4] Remove unreachable statement
  administrator/components/com_privacy/src/Model/ExportModel.php
  administrator/components/com_users/src/Controller/DisplayController.php
Labels: PR-4.0-dev

#31983 s/JNamespaceMap/JNamespacePsr4Map
  libraries/namespacemap.php
Labels: PR-4.0-dev, RTC

#31995 [4] Remove return after an exception (copy and paste legacy issue)
  components/com_users/src/Controller/RegistrationController.php
Labels: PR-4.0-dev

#31997 [4] remove redundant code in frontend template manager
  components/com_config/src/Model/TemplatesModel.php
Labels: PR-4.0-dev

#31998 [4] Branch in switch is a duplicate, merge them
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: PR-4.0-dev, RTC

#32003 [4] Remove return after an exception (copy and paste legacy issue)
  administrator/components/com_contenthistory/src/View/Preview/HtmlView.php
Labels: PR-4.0-dev

#32004 [4.0] Fix cs in #31997
  components/com_config/src/Model/TemplatesModel.php
Labels: PR-4.0-dev

#32009 [4.0] Remove sampledata images
  build/build.php
Labels: PR-4.0-dev

#32011 [4.0] Fix stats-message.js, should append message instead of insert
  build/media_source/plg_system_stats/js/stats-message.es6.js
Labels: RTC

#31438 [4.0] Searchtools works with selects only
  build/media_source/system/js/searchtools.es6.js
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31946 [4] correct single line comment style
  administrator/index.php
  api/index.php
  cli/joomla.php
  index.php
Labels: PR-4.0-dev, RTC

#31821 [4.0] cassiopeia chrome fix [a11y]
  templates/cassiopeia/html/layouts/chromes/card.php
  templates/cassiopeia/html/layouts/chromes/noCard.php
Labels: PR-4.0-dev, RTC

#31943 [4] Add dry-run and verbose/debug modes to update:joomla:remove-old-files cmd
  administrator/components/com_admin/script.php
  libraries/src/Console/RemoveOldFilesCommand.php
Labels: PR-4.0-dev, RTC

#31952 s/formated/formatted
  libraries/src/HTML/HTMLHelper.php
Labels: PR-staging, RTC

#31954 s/Aappend/Append
  libraries/src/Installer/Installer.php
Labels: PR-staging, RTC

#31955 s/edebug/debug
  libraries/src/Mail/Mail.php
Labels: PR-staging, RTC

#31957 s/constuct/construct
  libraries/src/Table/Nested.php
Labels: PR-staging, RTC

#31959 s/transilterate/transliterate
  libraries/src/Filter/OutputFilter.php
Labels: PR-staging, RTC

#31960 s/sprinftf/sprintf
  libraries/src/Language/Text.php
Labels: PR-staging, RTC

#31961 s/istead/instead
  libraries/src/Table/User.php
Labels: PR-staging, RTC

#31964 s/appropropriate/appropriate
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-staging, RTC

#31965 s/heen/been
  tests/unit/suites/libraries/joomla/session/handler/array.php
Labels: PR-staging, RTC

#31966 s/updpating/updating
  libraries/fof/table/behavior/assets.php
Labels: PR-staging, RTC

#31967 s/useage/usage
  plugins/sampledata/blog/blog.php
Labels: PR-staging, RTC

#31968 s/accordians/accordions. s/accordian/accordion
  libraries/cms/html/bootstrap.php
Labels: PR-staging, RTC

#31969 s/adpater/adapter
  libraries/joomla/model/database.php
Labels: PR-staging, RTC

#31970 s/referencess/references
  libraries/joomla/github/github.php
Labels: PR-staging, RTC

#31971 s/dicussions/discussions
  libraries/joomla/linkedin/groups.php
Labels: PR-staging, RTC

#31951 s/Alows/Allows
  libraries/src/Form/Form.php
Labels: PR-staging, RTC

#31950 s/goup/group s/goups/groups
  libraries/src/Form/Form.php
Labels: PR-staging, RTC

#31949 s/backslahses/backslashes
  libraries/src/Cache/Storage/FileStorage.php
Labels: PR-staging, RTC

#31977 [3.x] Php version check
  plugins/quickicon/phpversioncheck/phpversioncheck.php
Labels: PR-staging, RTC

#31878 Fix PHP CS errors introduced with PR 31672
  layouts/joomla/form/field/password.php
Labels: PR-staging, RTC

#31999 [4.0] Fix smtp test mail and migrate related jquery code to es6
  build/media_source/system/js/fields/joomla-field-send-test-mail.w-c.es6.js
  build/media_source/system/js/fields/passwordview.es6.js
  layouts/joomla/form/field/password.php
  libraries/src/Form/Field/PasswordField.php
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#31938 [4.0][CLI] check install
  cli/joomla.php
Labels: PR-4.0-dev, RTC

#32013 [4.0] Password hint
  layouts/joomla/form/field/password.php
Labels: PR-4.0-dev, RTC

#32024 [4.0] Fix broken pagination in com_plugins
  administrator/components/com_plugins/src/Model/PluginsModel.php
Labels: PR-4.0-dev, RTC

#31698 [4.0] Add User ID validation to fields
  administrator/components/com_banners/forms/banner.xml
  administrator/components/com_categories/forms/category.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/article.xml
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/forms/group.xml
  administrator/components/com_finder/forms/filter.xml
  administrator/components/com_newsfeeds/forms/newsfeed.xml
  administrator/components/com_tags/forms/tag.xml
  administrator/components/com_users/forms/note.xml
  components/com_contact/forms/form.xml
  libraries/src/Form/Rule/UserIdRule.php
  plugins/fields/user/params/user.xml
Labels: PR-4.0-dev, RTC

#31850 [4.0] Order field
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  libraries/src/HTML/Helpers/ListHelper.php
Labels: Language Change, PR-4.0-dev, RTC

#32035 [4] break after return/throw is unreachable code
  libraries/src/Image/Image.php
Labels: PR-4.0-dev

#32043 [4.0] skipto accessibility plugin major upgrade v4.0
  administrator/components/com_admin/script.php
  administrator/language/en-GB/plg_system_skipto.ini
  build/build-modules-js/settings.json
  package-lock.json
  package.json
  plugins/system/skipto/skipto.php
  plugins/system/skipto/skipto.xml
Labels: Language Change, NPM Resource Changed, PR-4.0-dev

#32036 [4] Cleanup of switch and remove unreachable code
  administrator/components/com_postinstall/src/Controller/MessageController.php
Labels: PR-4.0-dev, RTC

#32034 [4] Remove unreachable code in cli CodeStyle.php
  libraries/src/Application/CLI/ColorStyle.php
Labels: PR-4.0-dev, RTC

#32033 [4] Remove unreachable code in webauthn trait
  plugins/system/webauthn/src/PluginTraits/AjaxHandler.php
Labels: PR-4.0-dev, RTC

#32049 [4] add missing import in use in docblock to satisfy IDEs
  libraries/src/MVC/View/ViewInterface.php
Labels: PR-4.0-dev

#32051 [4] s/MVCFactoryInterfaceCF/MVCFactoryInterface
  libraries/src/MVC/Factory/MVCFactoryAwareTrait.php
Labels: PR-4.0-dev

#32053 [4] Correct case of class name s/SimpleXmlElement/SimpleXMLElement
  administrator/components/com_mails/src/Model/TemplateModel.php
  libraries/src/Installer/Manifest.php
Labels: PR-4.0-dev

#32048 s/Unexising/Unexisting
  libraries/src/Filesystem/Meta/language/en-GB/en-GB.lib_joomla_filesystem_patcher.ini
  libraries/src/Filesystem/Patcher.php
Labels: RTC

#32052 [4] fix Notice: Only variables should be passed by reference
  libraries/src/MVC/Controller/BaseController.php
Labels: RTC

#32055 [4] Fix default value type does not match the given type
  libraries/src/Toolbar/ToolbarHelper.php
Labels: RTC

#32057 [4] phpmailerException - add missing include exception and alias it.
  plugins/system/privacyconsent/privacyconsent.php
Labels: RTC

#32058 [4] add missing and fix wrong includes in com_finder, and remove unset on undefined var
  administrator/components/com_finder/src/Indexer/Adapter.php
  administrator/components/com_finder/src/Indexer/Helper.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_finder/src/Model/FilterModel.php
Labels: PR-4.0-dev

#32054 [4] Remove unset call as $xml is not set when here
  libraries/src/Installer/InstallerHelper.php
Labels: PR-4.0-dev

#32050 [4] add missing import for typehint in docblock
  libraries/src/MVC/Model/WorkflowModelInterface.php
Labels: PR-4.0-dev, RTC

#32067 [4.0] Fix edit account URI fragment
  administrator/modules/mod_user/tmpl/default.php
Labels: PR-4.0-dev

#32066 [4.0] Correcting frontend xtd_menu searchtools display
  components/com_menus/layouts/joomla/searchtools/default.php
Labels: PR-4.0-dev, RTC

#32029 [4.0] Cassiopea: xtd Status icons and Clear button colors
  templates/cassiopeia/scss/blocks/_icons.scss
  templates/cassiopeia/scss/system/searchtools/searchtools.scss
  templates/cassiopeia/scss/tools/variables/_variables.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#32072 [4.0] image xtd-editor icon
  plugins/editors-xtd/image/image.php
Labels: PR-4.0-dev

#31545 [4.0] modify #31190
  administrator/modules/mod_login/tmpl/default.php
  build/media_source/plg_system_webauthn/images/webauthn.svg
  libraries/src/HTML/Helpers/Icons.php
  libraries/src/Helper/AuthenticationHelper.php
  modules/mod_login/tmpl/default.php
  plugins/system/webauthn/src/PluginTraits/AdditionalLoginButtons.php
Labels: NPM Resource Changed, PR-4.0-dev, Updates Requested

#32064 $nowDate has to be quoted for the query to work (#32016)
  components/com_content/src/Model/ArticlesModel.php
Labels: PR-4.0-dev, RTC

#32078 [3.10] Make sure the message is more clear for 3.x extensions
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-3.10-dev, RTC

#30786 [3.10] Clear buffered output at all levels
  libraries/src/Exception/ExceptionHandler.php
Labels: PR-3.10-dev

#31231 Deprecate CryptoCipher for 5.0
  libraries/src/Crypt/Cipher/BlowfishCipher.php
  libraries/src/Crypt/Cipher/CryptoCipher.php
  libraries/src/Crypt/Cipher/McryptCipher.php
  libraries/src/Crypt/Cipher/Rijndael256Cipher.php
  libraries/src/Crypt/Cipher/SimpleCipher.php
  libraries/src/Crypt/Cipher/TripleDesCipher.php
  libraries/src/Crypt/README.md
Labels: Documentation Required, PR-3.10-dev

#32088 [4.0] en-* installation strings
  installation/language/en-GB/joomla.ini
  installation/language/en-US/joomla.ini
Labels: Language Change, PR-4.0-dev

#32077 Make sure the sendmail endpoint can only be called via post
  administrator/components/com_config/controller/application/sendtestmail.php
Labels: PR-staging, RTC

#32079 [4.0] Apply .form-control
  administrator/components/com_redirect/tmpl/links/default_batch_body.php
Labels: PR-4.0-dev, RTC

#32093 [4.0] Label menu item title
  administrator/language/en-GB/com_menus.ini
Labels: Language Change, PR-4.0-dev, RTC

#32091 [4.0] TinyMCE toolbar mode
  administrator/language/en-GB/plg_editors_tinymce.ini
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/tinymce.php
Labels: Language Change, PR-4.0-dev, RTC

#32056 [3.10] s/timymce/tinymce
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  media/editors/tinymce/js/tinymce-builder.js
Labels: PR-3.10-dev, RTC

#32099 [3.x] Privacy consents
  administrator/language/en-GB/en-GB.com_privacy.ini
  administrator/language/en-GB/en-GB.plg_authentication_cookie.ini
Labels: Language Change, PR-staging

#32094 [4.0] Aria controls [a11y]
  administrator/components/com_admin/tmpl/help/default.php
  administrator/components/com_config/tmpl/application/default.php
  administrator/components/com_config/tmpl/component/default.php
Labels: PR-4.0-dev, RTC

#32095 [4.0] associations message
  administrator/language/en-GB/com_associations.ini
Labels: Language Change, PR-4.0-dev

#32100 [4.0] Cassiopeia - Correct code in error.php
  templates/cassiopeia/error.php
Labels: RTC

#32098 [3.10] Show the target version to the pre upgrade checker
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-3.10-dev, RTC

#32104 [4.0] RTL: Correcting Admin login 2factor and feedback hints
  administrator/templates/atum/scss/blocks/_login.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#32061 [3.10] Joomla.Showon.initialise API, and make sure that showon initialised only once, fork of 18843
  media/jui/js/cms-uncompressed.js
  media/jui/js/cms.js
Labels: PR-3.10-dev, RTC

#32109 [4.0] post bs5 cs
  administrator/components/com_modules/tmpl/select/default.php
Labels: PR-4.0-dev

#32045 [4] Security. Uncouple the length of a placeholder mask from the actual password length.
  layouts/joomla/form/field/password.php
Labels: PR-4.0-dev, RTC

#32070 [4.0] Front end editing module and menu [a11y] [nojs]
  administrator/language/en-GB/lib_joomla.ini
  build/media_source/legacy/joomla.asset.json
  build/media_source/legacy/js/frontediting.es5.js
  language/en-GB/lib_joomla.ini
  layouts/joomla/edit/frontediting_modules.php
  templates/cassiopeia/scss/blocks/_form.scss
  templates/cassiopeia/scss/blocks/_frontend-edit.scss
Labels: Language Change, NPM Resource Changed, PR-4.0-dev, RTC, Release Blocker

#32112 [4.0] Cassiopeia description post bs5
  language/en-GB/tpl_cassiopeia.ini
  language/en-GB/tpl_cassiopeia.sys.ini
Labels: RTC

#32101 [4.0] RTL: Correcting target blank icon placement
  administrator/templates/atum/scss/template-rtl.scss
Labels: NPM Resource Changed, PR-4.0-dev

#32122 [4.0] Repair alignment of search icon after BS5 merge
  templates/cassiopeia/scss/vendor/_awesomplete.scss
Labels: J4 Frontend Template, NPM Resource Changed, PR-4.0-dev

#32121 [4.0] Atum rtl unused
  administrator/templates/atum/scss/template-rtl.scss
Labels: NPM Resource Changed, PR-4.0-dev

#32125 [4.0] Remove RTL specific css
  administrator/templates/atum/scss/vendor/bootstrap/_dropdown.scss
Labels: NPM Resource Changed, PR-4.0-dev

#32123 [4.0 Cassiopeia unused css
  templates/cassiopeia/scss/vendor/metismenu/_metismenu.scss
Labels: NPM Resource Changed, PR-4.0-dev, RTC

#32130 Revert "[4.0] RTL: Correcting target blank icon placement"
  administrator/templates/atum/scss/template-rtl.scss
Labels: NPM Resource Changed, PR-4.0-dev

#32120 [4.0] External link icon placement
  administrator/templates/atum/scss/blocks/_global.scss
Labels: NPM Resource Changed, PR-4.0-dev

#32110 [4.0] npm update
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.0-dev
