Repository joomla/joomla-cms, pull requests merged in 2021-12, with the labels that each got.

#36174 [4.1] Sort import
  libraries/src/Console/TasksStateCommand.php
Labels: RTC

#36173 [4.1] Fix quote markup in language string
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.1-dev

#36168 [4.0] Fix Hide Article Options
  administrator/components/com_content/tmpl/article/edit.php
Labels: RTC, PR-4.0-dev

#36172 [4.0] Add period to the success message
  administrator/language/en-GB/com_modules.ini
Labels: RTC, Language Change, PR-4.0-dev

#36122 Solve required field attribute causing rendering error
  layouts/joomla/form/field/color/advanced.php
Labels: RTC, PR-4.0-dev

#36181 Revert "[4.0] Fix Hide Article Options"
  administrator/components/com_content/tmpl/article/edit.php
Labels: PR-4.0-dev

#36158 [3.10.4] Updated installation language files
  installation/language/cy-GB/cy-GB.ini
  installation/language/cy-GB/cy-GB.xml
  installation/language/da-DK/da-DK.ini
  installation/language/da-DK/da-DK.xml
  installation/language/de-AT/de-AT.ini
  installation/language/de-AT/de-AT.xml
  installation/language/de-CH/de-CH.ini
  installation/language/de-CH/de-CH.xml
  installation/language/de-DE/de-DE.ini
  installation/language/de-DE/de-DE.xml
  installation/language/de-LI/de-LI.ini
  installation/language/de-LI/de-LI.xml
  installation/language/de-LU/de-LU.ini
  installation/language/de-LU/de-LU.xml
  installation/language/el-GR/el-GR.ini
  installation/language/el-GR/el-GR.xml
  installation/language/es-ES/es-ES.ini
  installation/language/es-ES/es-ES.xml
  installation/language/fa-IR/fa-IR.ini
  installation/language/fa-IR/fa-IR.xml
  installation/language/fr-FR/fr-FR.ini
  installation/language/fr-FR/fr-FR.xml
  installation/language/hr-HR/hr-HR.ini
  installation/language/hr-HR/hr-HR.xml
  installation/language/hu-HU/hu-HU.ini
  installation/language/hu-HU/hu-HU.xml
  installation/language/ja-JP/ja-JP.ini
  installation/language/ja-JP/ja-JP.xml
  installation/language/ka-GE/ka-GE.ini
  installation/language/ka-GE/ka-GE.xml
  installation/language/nb-NO/nb-NO.ini
  installation/language/nb-NO/nb-NO.xml
  installation/language/nl-NL/nl-NL.ini
  installation/language/nl-NL/nl-NL.xml
  installation/language/sl-SI/sl-SI.ini
  installation/language/sl-SI/sl-SI.xml
  installation/language/sv-SE/sv-SE.ini
  installation/language/sv-SE/sv-SE.xml
  installation/language/sw-KE/sw-KE.ini
  installation/language/sw-KE/sw-KE.xml
  installation/language/ta-IN/ta-IN.ini
  installation/language/ta-IN/ta-IN.xml
  installation/language/th-TH/th-TH.ini
  installation/language/th-TH/th-TH.xml
Labels: Language Change, PR-3.10-dev

#36186 [4.0] Fix tinymce plugin configuration
  plugins/editors/tinymce/tinymce.php
Labels: RTC, Release Blocker, PR-4.0-dev

#36178 [4.0] Bootstrap has double imports for alerts and modals
  build/build-modules-js/javascript/build-bootstrap-js.es6.js
Labels: RTC, Release Blocker, PR-4.0-dev

#36194 [4.1] Fix deleted files in script.php for 4.1 Beta 1
  administrator/components/com_admin/script.php
Labels: RTC, PR-4.1-dev

#36222 [4.0][bugfix] Fix fatal error page with no translation
  build/build-modules-js/error-pages.es6.js
Labels: PR-4.0-dev

#36236 [4.1][bugfix] Fix the preview/thumb images for children
  administrator/components/com_templates/src/Service/HTML/Templates.php
Labels: RTC, PR-4.1-dev

#36219 [4.1][bugfix] Fix language inheritance for child template
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, PR-4.1-dev

#36212 [4.1] Tasks manager
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, PR-4.1-dev

#36208 [4.1] Tasks manager column heading
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, PR-4.1-dev

#36206 [4.1] Tasks site offline
  administrator/language/en-GB/plg_task_sitestatus.ini
Labels: RTC, PR-4.1-dev

#36205 [4.1] task titles
  administrator/language/en-GB/plg_task_sitestatus.ini
Labels: RTC, Language Change, PR-4.1-dev

#36203 [4.1] Tasks - empty state
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, PR-4.1-dev

#36200 [4.1] Fix missing class import
  libraries/src/MVC/View/AbstractView.php
Labels: RTC, PR-4.1-dev

#36197 [4.1] Remove unused Import
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
Labels: RTC, PR-4.1-dev

#36192 [4.1] Prevent disabling a parent template when children exist
  administrator/components/com_installer/src/Model/ManageModel.php
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.1-dev

#36191 [4.1] Prevent deleting a parent template if children exist
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Installer/Adapter/TemplateAdapter.php
Labels: RTC, Language Change, PR-4.1-dev

#36228 [4.1] Create Child Template Button
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_templates/tmpl/template/default_modal_child_footer.php
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.1-dev

#36225 [4.1] Fix broken aria label
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_form.scss
  layouts/joomla/searchtools/default/bar.php
Labels: RTC, Release Blocker, a11y, NPM Resource Changed, PR-4.1-dev

#36223 [3.10] Installation languages for ru-RU, it-IT and sk-SK
  installation/language/it-IT/it-IT.ini
  installation/language/it-IT/it-IT.xml
  installation/language/ru-RU/ru-RU.ini
  installation/language/ru-RU/ru-RU.xml
  installation/language/sk-SK/sk-SK.ini
  installation/language/sk-SK/sk-SK.xml
Labels: Language Change, PR-3.10-dev

#36241 [4.1] Child Templates buttons
  administrator/components/com_templates/src/View/Styles/HtmlView.php
  administrator/components/com_templates/src/View/Templates/HtmlView.php
Labels: RTC, PR-4.1-dev

#36211 [4.1] Tasks enabled/disabled
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#36234 [4.0] Add unit and integration tests for 8.1
  .drone.yml
Labels: Unit/System Tests, PR-4.0-dev

#36271 [4.1] Simplify notification labels
  administrator/language/en-GB/plg_system_tasknotification.ini
Labels: RTC, Language Change, PR-4.1-dev

#36270 [4.1] Remove ! in task title
  administrator/language/en-GB/plg_task_checkfiles.ini
Labels: RTC, Language Change, PR-4.1-dev

#36247 [4.1] Schedule Tasks class
  administrator/components/com_scheduler/tmpl/tasks/default.php
Labels: RTC, PR-4.1-dev

#36245 [4.1] Task Manager numeric strings
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#36209 [4.1] Task manager sort
  administrator/components/com_scheduler/forms/filter_tasks.xml
Labels: RTC, PR-4.0-dev

#36288 [4.0] Add missing class attribute
  layouts/joomla/form/field/radio/buttons.php
Labels: RTC, PR-4.0-dev

#36282 [4] php 8.1 deprecation
  libraries/src/Date/Date.php
Labels: PR-4.0-dev

#36281 [4] cannot pass null to trim function in php 8.1
  libraries/src/Uri/Uri.php
Labels: RTC, PR-4.0-dev

#36286 [4] php 8.1 Deprecated: trim(): Passing null to parameter #1
  administrator/components/com_mails/src/Model/TemplatesModel.php
Labels: PR-4.0-dev

#36285 [4] php 8.1 Deprecated: substr(): Passing null to parameter #1
  administrator/modules/mod_submenu/tmpl/default.php
Labels: PR-4.0-dev

#36284 [4] php 8.1 Deprecated: trim(): Passing null to parameter #1
  administrator/components/com_menus/src/Model/ItemsModel.php
  administrator/components/com_menus/src/Model/MenusModel.php
Labels: PR-4.0-dev

#36292 [4.0] PHP 8.1 deprecation notices Feed
  libraries/src/Feed/Feed.php
Labels: PR-4.0-dev

#36283 [4] php 8.1 Deprecated: strpos(): Passing null to parameter
  libraries/src/Toolbar/Button/PopupButton.php
Labels: PR-4.0-dev

#36294 [4.1] Unification of the language com_scheduler
  administrator/language/en-GB/com_scheduler.ini
  administrator/language/en-GB/com_scheduler.sys.ini
Labels: RTC, Language Change, PR-4.1-dev

#36244 [4.1] Scheduled tasks notes
  administrator/components/com_scheduler/tmpl/tasks/default.php
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#36242 [4.1] Action Logs improved search
  administrator/components/com_actionlogs/src/Model/ActionlogsModel.php
  administrator/language/en-GB/com_actionlogs.ini
Labels: RTC, Language Change, PR-4.1-dev

#36296 [4.1] Unification of the language com_scheduler, part 2
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, PR-4.1-dev

#36251 [4.1][bugfix] Assets should be loaded in the layout
  components/com_config/src/View/Config/HtmlView.php
  components/com_config/tmpl/config/default.php
Labels: RTC, PR-4.1-dev

#36290 [4.1][bugfix] Respect Core files
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC, Release Blocker, PR-4.1-dev

#36132 [4.1] Remove Unused Imports from /libraries folder
  libraries/src/Document/Renderer/Html/MessageRenderer.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Language/Text.php
  libraries/src/Log/Log.php
  libraries/src/MVC/View/HtmlView.php
  libraries/src/MVC/View/JsonView.php
  libraries/src/Pagination/Pagination.php
  libraries/src/Router/Route.php
  libraries/src/Session/Session.php
Labels: RTC, PR-4.1-dev

#36259 [4.1] Add propper classes to search input
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_form.scss
  layouts/joomla/searchtools/default/bar.php
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36256 [4.0] s/exits/exists
  libraries/src/Installer/Installer.php
Labels: RTC, PR-4.0-dev

#35396 [4.1] Add some events when fetching media data
  administrator/components/com_media/src/Event/AbstractMediaItemValidationEvent.php
  administrator/components/com_media/src/Event/FetchMediaItemEvent.php
  administrator/components/com_media/src/Event/FetchMediaItemUrlEvent.php
  administrator/components/com_media/src/Event/FetchMediaItemsEvent.php
  administrator/components/com_media/src/Model/ApiModel.php
Labels: RTC, PR-4.1-dev

#36340 [4.0] s/td/th
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
Labels: RTC, PR-4.0-dev

#36341 [4.1] s/Instantiante/Instantiate
  build/media_source/plg_editors_tinymce/js/plugins/highlighter/source.es5.js
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36342 [4.1] plg_system_schedulerunner s/atrributes/attributes
  build/media_source/plg_system_schedulerunner/joomla.asset.json
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36337 [4.1] Remove Duplicate chars from trim
  administrator/components/com_finder/src/Field/ContentmapField.php
  administrator/components/com_finder/src/Service/HTML/Filter.php
  administrator/components/com_finder/tmpl/maps/default.php
Labels: RTC, PR-4.1-dev

#36336 [4.1] s/$presetButtonClases/$presetButtonClasses
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
Labels: RTC, PR-4.1-dev

#36240 [4.1] Check File Size task options
  plugins/task/checkfiles/forms/image_size.xml
Labels: RTC, PR-4.1-dev

#36350 [4.0] Curly brackets instead of square brackets in plg_system_updatenotification.ini
  administrator/language/en-GB/plg_system_updatenotification.ini
Labels: RTC, Language Change, PR-4.0-dev

#36188 Fix code comments
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
Labels: RTC, PR-4.0-dev

#36153 Update compile-to-es2017.es6.js
  build/build-modules-js/javascript/compile-to-es2017.es6.js
Labels: RTC, PR-4.0-dev

#36246 [4.0] Searchtools clear button
  administrator/templates/atum/scss/system/searchtools/searchtools.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36339 [4.0] `td` is not a self closing html tag
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
Labels: RTC, PR-4.0-dev

#35460 [4] Remove attribute thats not allowed here
  administrator/components/com_joomlaupdate/tmpl/upload/default.php
Labels: RTC, PR-4.0-dev

#36295 [4.0] Update npm dependencies
  administrator/components/com_media/resources/scripts/store/actions.es6.js
  administrator/components/com_media/resources/scripts/store/mutations.es6.js
  build/.eslintrc
  build/.stylelintrc.json
  build/build-modules-js/init/common/copy-all-files.es6.js
  build/build-modules-js/init/exemptions/codemirror.es6.js
  build/build-modules-js/settings.json
  build/build-modules-js/utils/debounce.es6.js
  build/build.js
  build/media_source/com_associations/js/associations-edit.es6.js
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/com_fields/js/admin-field-changecontext.es6.js
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  build/media_source/plg_system_webauthn/js/login.es6.js
  build/media_source/plg_system_webauthn/js/management.es6.js
  build/media_source/system/js/fields/joomla-field-color-slider.es6.js
  build/media_source/system/js/fields/joomla-field-module-order.w-c.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  build/media_source/system/js/fields/passwordstrength.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/vendor/bootstrap/js/alert.es6.js
  build/media_source/vendor/bootstrap/js/button.es6.js
  build/media_source/vendor/bootstrap/js/carousel.es6.js
  build/media_source/vendor/bootstrap/js/collapse.es6.js
  build/media_source/vendor/bootstrap/js/dropdown.es6.js
  build/media_source/vendor/bootstrap/js/modal.es6.js
  build/media_source/vendor/bootstrap/js/offcanvas.es6.js
  build/media_source/vendor/bootstrap/js/popover.es6.js
  build/media_source/vendor/bootstrap/js/scrollspy.es6.js
  build/media_source/vendor/bootstrap/js/tab.es6.js
  build/media_source/vendor/bootstrap/js/toast.es6.js
  package-lock.json
  package.json
Labels: PR-4.0-dev, NPM Resource Changed

#36221 [4.0][bugfix] Fix Figure misbehaviour in tinyMCE
  build/media_source/system/js/fields/joomla-media-select.w-c.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36367 [4.0] Update bootstrap to 5.1.3
  package-lock.json
Labels: PR-4.0-dev, NPM Resource Changed

#36260 Add systemtests for php 8.1
  .drone.yml
  tests/Codeception/_support/Step/Acceptance/Administrator/Media.php
  tests/Codeception/acceptance.suite.dist.yml
  tests/Codeception/api.suite.dist.yml
  tests/Codeception/drone-api-run.sh
  tests/Codeception/drone-system-run.sh
Labels: Unit/System Tests, PR-4.0-dev, PHP 8

#36335 Fix this.searchField is null
  build/media_source/system/js/searchtools.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36344 [4.0] Change </td> to </th>
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
Labels: RTC, PR-4.0-dev

#36362 [4.0] PHP 8.1 deprecation notices various
  templates/cassiopeia/html/layouts/chromes/noCard.php
Labels: PR-4.0-dev, PHP 8

#36199 [4.0] Remove unused import
  components/com_contact/src/View/Contact/HtmlView.php
Labels: RTC, PR-4.0-dev

#36198 [4.0] Remove unused import
  libraries/src/Form/Field/TransitionField.php
Labels: RTC, PR-4.0-dev

#36319 [4.0] Send the category params in API GET requests
  api/components/com_categories/src/View/Categories/JsonapiView.php
Labels: RTC, PR-4.0-dev, Webservices

#35989 [4.0] Clear search when a directory is changed in media manager
  administrator/components/com_media/resources/scripts/store/mutations.es6.js
  tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
Labels: RTC, Unit/System Tests, PR-4.0-dev, NPM Resource Changed

#36418 [4] To and Do fell out with each other
  administrator/components/com_config/src/Model/ApplicationModel.php
  layouts/joomla/form/field/rules.php
  libraries/src/Form/Field/RulesField.php
Labels: RTC, PR-4.0-dev

#36391 [4.0] Cache-Control post-check and pre-check
  libraries/src/Application/CMSApplication.php
  plugins/system/languagefilter/languagefilter.php
Labels: RTC, PR-4.0-dev

#36417 [4] Delete lots more code...
  administrator/components/com_associations/src/Controller/AssociationsController.php
  administrator/components/com_config/src/View/Application/HtmlView.php
  administrator/components/com_config/src/View/Component/HtmlView.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_media/src/Controller/PluginController.php
  administrator/components/com_menus/src/Controller/AjaxController.php
  components/com_contact/src/View/Contact/HtmlView.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Editor/Editor.php
  libraries/src/Form/Field/ColorField.php
  libraries/src/Form/Field/MediaField.php
  libraries/src/Form/Field/RulesField.php
  libraries/src/Router/ApiRouter.php
  plugins/editors/none/none.php
  plugins/sampledata/blog/blog.php
  plugins/system/cache/cache.php
Labels: PR-4.1-dev

#36431 [4] composer update maximebf/debugbar to 1.17
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#36429 [4] s/to add to add/to add
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
Labels: RTC, PR-4.0-dev

#36390 [4.0] build.js instructions
  build/build.js
Labels: RTC, PR-4.0-dev

#36466 [4] Fix Drone
  tests/Codeception/acceptance.suite.dist.yml
  tests/Codeception/api.suite.dist.yml
Labels: Unit/System Tests, PR-4.0-dev

#36360 [4.0] PHP 8.1 deprecation notices administrator/components
  administrator/components/com_banners/src/Model/ClientsModel.php
  administrator/components/com_config/src/Controller/DisplayController.php
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_mails/src/Model/TemplateModel.php
  administrator/components/com_menus/tmpl/items/default_batch_body.php
  administrator/components/com_menus/tmpl/items/default_batch_footer.php
  administrator/components/com_templates/src/View/Template/HtmlView.php
Labels: PR-4.0-dev, PHP 8

#36463 [4.0] Mail Templates language files
  administrator/components/com_mails/src/View/Template/HtmlView.php
Labels: RTC

#36267 [4.0] Full Image class hint
  administrator/components/com_content/forms/article.xml
  administrator/language/en-GB/com_content.ini
Labels: RTC, PR-4.0-dev

#36441 [4.0] Uninstalled components with leftover menu records appear in the Components Dashboard
  administrator/modules/mod_submenu/src/Menu/Menu.php
Labels: RTC, PR-4.0-dev

#36416 [4] /s/host/command line
  cli/joomla.php
Labels: RTC, PR-4.0-dev

#36412 [4] Return value type is not compatible with declared
  administrator/components/com_config/src/View/Application/HtmlView.php
  installation/src/Application/InstallationApplication.php
  libraries/src/Application/ApiApplication.php
  libraries/src/Association/AssociationExtensionHelper.php
  libraries/src/Cache/Cache.php
  libraries/src/Changelog/Changelog.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  plugins/editors-xtd/article/article.php
Labels: PR-4.0-dev

#36403 [4] Removed unused code
  administrator/components/com_content/src/Model/ArticleModel.php
Labels: PR-4.0-dev

#36386 [4.0] Replace input with button
  modules/mod_login/tmpl/default_logout.php
  templates/cassiopeia/offline.php
  templates/system/offline.php
Labels: RTC, PR-4.0-dev

#36382 [4.0] remove deprecated type tag
  plugins/system/debug/src/JavascriptRenderer.php
Labels: RTC, PR-4.0-dev

#36182 [4.0] Fix Hide Article Options #36168 [revert revert]
  administrator/components/com_content/tmpl/article/edit.php
Labels: RTC, PR-4.0-dev

#36147 [4.0] admin menu RTL
  administrator/modules/mod_menu/tmpl/default.php
Labels: RTC, PR-4.0-dev

#36190 [4.1] Joomla-Accessibility Checker (jooa11y).
  administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-11-26.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-11-26.sql
  administrator/components/com_content/src/View/Article/HtmlView.php
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/plg_system_jooa11y.ini
  administrator/language/en-GB/plg_system_jooa11y.sys.ini
  api/language/en-GB/joomla.ini
  build/.eslintrc
  build/build-modules-js/settings.json
  build/media_source/plg_system_jooa11y/joomla.asset.json
  build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
  build/media_source/plg_system_jooa11y/scss/jooa11y.scss
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  language/en-GB/joomla.ini
  libraries/src/Toolbar/CoreButtonsTrait.php
  libraries/src/Toolbar/ToolbarHelper.php
  package-lock.json
  package.json
  plugins/system/jooa11y/jooa11y.php
  plugins/system/jooa11y/jooa11y.xml
Labels: RTC, Language Change, NPM Resource Changed, PR-4.1-dev

#36476 [4.0] PHP 8 ReturnTypeWillChange JsonapiDocument::jsonSerialize
  libraries/src/Document/JsonapiDocument.php
Labels: PR-4.0-dev

#36471 [4.0] Update Sites title
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.0-dev

#36464 [4.0] Input bs5 for installation page
  installation/tmpl/remove/default.php
Labels: RTC, PR-4.0-dev

#36155 [4.0] media manager infobar
  build/media_source/com_media/scss/components/_media-infobar.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36470 [4.0] Installer strings
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.0-dev

#36475 [4.1] Fix checked_out value in 4.1.0-2021-11-26.sql and rename to 4.1.0-2021-12-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-12-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-12-29.sql
Labels: RTC, Release Blocker, PR-4.1-dev

#36381 [4.1] s/../.
  api/components/com_media/src/Controller/MediaController.php
Labels: RTC, PR-4.1-dev

#36484 [4] Requesting to be added to code owners
  .github/CODEOWNERS
Labels: PR-4.0-dev

#36404 [4] Ensure message is defined
  administrator/components/com_content/src/Controller/ArticlesController.php
Labels: PR-4.0-dev

#36409 [4.0] Fix array to string conversion
  libraries/src/Table/Nested.php
Labels: PR-4.0-dev

#36488 Revert "[4] Requesting to be added to code owners"
  .github/CODEOWNERS
Labels: PR-4.0-dev

#36494 [3.x] Backup messge
  administrator/language/en-GB/en-GB.com_installer.ini
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, PR-3.10-dev

#36493 [4.0] Minify diff.js
  build/build-modules-js/init/minify-vendor.es6.js
Labels: PR-4.0-dev

#36490 [4.0] RTL Version number in log file
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
Labels: RTC, PR-4.0-dev

#36481 [4] fix missing com_modules.module.90 from #__assets table
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.0-dev

#36496 [4.0] Update deleted files for 4.0.6
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#36414 [4.0] refactor Switch which has only single case
  libraries/src/Changelog/Changelog.php
  libraries/src/Form/Field/CheckboxField.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Form/Field/FileField.php
  libraries/src/Form/Field/ModuleorderField.php
  libraries/src/Form/Field/ModulepositionField.php
  libraries/src/Form/Field/OrderingField.php
  libraries/src/Form/Field/PluginsField.php
  libraries/src/Form/Field/TimezoneField.php
  libraries/src/MVC/Model/LegacyModelLoaderTrait.php
  libraries/src/Updater/Adapter/CollectionAdapter.php
Labels: RTC, PR-4.0-dev

#35458 [4] void method result used
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: PR-4.0-dev

#36474 [4.1] Tiny UX improvement
  administrator/components/com_installer/src/View/Install/HtmlView.php
  administrator/components/com_installer/src/View/Manage/HtmlView.php
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.1-dev

#36318 [4.0] Support to set the location when saving a category through the API
  api/components/com_categories/src/Controller/CategoriesController.php
Labels: RTC, PR-4.0-dev, Webservices

#36047 [4.0] Do not force the change of uploaded mm files to lowercase
  libraries/src/Filesystem/File.php
Labels: RTC, PR-4.0-dev

#36483 [4] Rename phpunit test folders to align with the apps structure
  phpunit.xml.dist
  tests/Unit/libraries/src/Access/RuleTest.php
  tests/Unit/libraries/src/Access/RulesTest.php
  tests/Unit/libraries/src/Application/ConsoleApplicationTest.php
  tests/Unit/libraries/src/Console/ExtensionDiscoverCommandTest.php
  tests/Unit/libraries/src/Console/ExtensionDiscoverInstallCommandTest.php
  tests/Unit/libraries/src/Console/ExtensionDiscoverListCommandTest.php
  tests/Unit/libraries/src/Console/Loader/WritableContainerLoaderTest.php
  tests/Unit/libraries/src/Date/DateTest.php
  tests/Unit/libraries/src/Document/DocumentTest.php
  tests/Unit/libraries/src/Environment/BrowserTest.php
  tests/Unit/libraries/src/Feed/FeedEntryTest.php
  tests/Unit/libraries/src/Feed/FeedFactoryTest.php
  tests/Unit/libraries/src/Feed/FeedLinkTest.php
  tests/Unit/libraries/src/Feed/FeedParserTest.php
  tests/Unit/libraries/src/Feed/FeedTest.php
  tests/Unit/libraries/src/Feed/Parser/AtomParserTest.php
  tests/Unit/libraries/src/Feed/Parser/RssParserTest.php
  tests/Unit/libraries/src/Filter/OutputFilterTest.php
  tests/Unit/libraries/src/Form/Field/AccessiblemediaFieldTest.php
  tests/Unit/libraries/src/Form/Rule/FilePathRuleTest.php
  tests/Unit/libraries/src/Form/Rule/FolderPathExistsRuleTest.php
  tests/Unit/libraries/src/Html/JHtmlDateTest.php
  tests/Unit/libraries/src/Html/JHtmlNumberTest.php
  tests/Unit/libraries/src/Html/JHtmlStringTest.php
  tests/Unit/libraries/src/Html/JHtmlTelTest.php
  tests/Unit/libraries/src/Image/ImageFilterTest.php
  tests/Unit/libraries/src/Image/ImageTest.php
  tests/Unit/libraries/src/Image/filter/FilterBackgroundfillTest.php
  tests/Unit/libraries/src/Image/filter/FilterBrightnessTest.php
  tests/Unit/libraries/src/Image/filter/FilterContrastTest.php
  tests/Unit/libraries/src/Image/filter/FilterEdgedetectTest.php
  tests/Unit/libraries/src/Image/stubs/koala.bmp
  tests/Unit/libraries/src/Image/stubs/koala.gif
  tests/Unit/libraries/src/Image/stubs/koala.jpg
  tests/Unit/libraries/src/Image/stubs/koala.png
  tests/Unit/libraries/src/Image/stubs/koala.webp
  tests/Unit/libraries/src/Image/tmp/.gitkeep
  tests/Unit/libraries/src/Installer/Adapter/ModuleAdapterTest.php
  tests/Unit/libraries/src/Layout/BaseLayoutTest.php
  tests/Unit/libraries/src/Mail/MailHelperTest.php
  tests/Unit/libraries/src/Mail/MailTest.php
  tests/Unit/libraries/src/Microdata/MicrodataTest.php
  tests/Unit/libraries/src/Object/CMSObjectTest.php
  tests/Unit/libraries/src/Session/SessionManagerTest.php
  tests/Unit/libraries/src/Toolbar/Button/CustomButtonTest.php
  tests/Unit/libraries/src/Toolbar/ToolbarTest.php
  tests/Unit/libraries/src/VersionTest.php
Labels: Unit/System Tests, PR-4.0-dev

#36498 Revert "[4] Rename phpunit test folders to align with the apps structure"
  phpunit.xml.dist
  tests/Unit/Libraries/Cms/Access/RuleTest.php
  tests/Unit/Libraries/Cms/Access/RulesTest.php
  tests/Unit/Libraries/Cms/Application/ConsoleApplicationTest.php
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverCommandTest.php
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverInstallCommandTest.php
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverListCommandTest.php
  tests/Unit/Libraries/Cms/Console/Loader/WritableContainerLoaderTest.php
  tests/Unit/Libraries/Cms/Date/DateTest.php
  tests/Unit/Libraries/Cms/Document/DocumentTest.php
  tests/Unit/Libraries/Cms/Environment/BrowserTest.php
  tests/Unit/Libraries/Cms/Feed/FeedEntryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedFactoryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedLinkTest.php
  tests/Unit/Libraries/Cms/Feed/FeedParserTest.php
  tests/Unit/Libraries/Cms/Feed/FeedTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
  tests/Unit/Libraries/Cms/Filter/OutputFilterTest.php
  tests/Unit/Libraries/Cms/Form/Field/AccessiblemediaFieldTest.php
  tests/Unit/Libraries/Cms/Form/Rule/FilePathRuleTest.php
  tests/Unit/Libraries/Cms/Form/Rule/FolderPathExistsRuleTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlDateTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlNumberTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlStringTest.php
  tests/Unit/Libraries/Cms/Html/JHtmlTelTest.php
  tests/Unit/Libraries/Cms/Image/ImageFilterTest.php
  tests/Unit/Libraries/Cms/Image/ImageTest.php
  tests/Unit/Libraries/Cms/Image/filter/FilterBackgroundfillTest.php
  tests/Unit/Libraries/Cms/Image/filter/FilterBrightnessTest.php
  tests/Unit/Libraries/Cms/Image/filter/FilterContrastTest.php
  tests/Unit/Libraries/Cms/Image/filter/FilterEdgedetectTest.php
  tests/Unit/Libraries/Cms/Image/stubs/koala.bmp
  tests/Unit/Libraries/Cms/Image/stubs/koala.gif
  tests/Unit/Libraries/Cms/Image/stubs/koala.jpg
  tests/Unit/Libraries/Cms/Image/stubs/koala.png
  tests/Unit/Libraries/Cms/Image/stubs/koala.webp
  tests/Unit/Libraries/Cms/Image/tmp/.gitkeep
  tests/Unit/Libraries/Cms/Installer/Adapter/ModuleAdapterTest.php
  tests/Unit/Libraries/Cms/Layout/BaseLayoutTest.php
  tests/Unit/Libraries/Cms/Mail/MailHelperTest.php
  tests/Unit/Libraries/Cms/Mail/MailTest.php
  tests/Unit/Libraries/Cms/Microdata/MicrodataTest.php
  tests/Unit/Libraries/Cms/Object/CMSObjectTest.php
  tests/Unit/Libraries/Cms/Session/SessionManagerTest.php
  tests/Unit/Libraries/Cms/Toolbar/Button/CustomButtonTest.php
  tests/Unit/Libraries/Cms/Toolbar/ToolbarTest.php
  tests/Unit/Libraries/Cms/VersionTest.php
Labels: Unit/System Tests, PR-4.0-dev

#36413 [4] correct syntax of union type in docbock
  plugins/sampledata/testing/testing.php
Labels: RTC, PR-4.0-dev

#36385 [4.0] remove redundant check
  plugins/user/token/token.php
Labels: PR-4.0-dev

#36407 [4.1] Correct return type in getQuickiconContent in Tags Controller
  administrator/components/com_tags/src/Controller/TagsController.php
Labels: PR-4.1-dev

#36442 [4.0] Remove reference to old JPrefixed Class + Cleanup (Misc)
  api/includes/app.php
  includes/app.php
  installation/src/Controller/InstallationController.php
  installation/template/error.php
  installation/template/index.php
  layouts/joomla/form/field/subform/default.php
  layouts/joomla/form/field/subform/repeatable-table.php
  layouts/joomla/form/field/subform/repeatable-table/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable-table/section.php
  layouts/joomla/form/field/subform/repeatable.php
  layouts/joomla/form/field/subform/repeatable/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable/section.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder/setaccess.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder/setoptions.php
  libraries/bootstrap.php
  libraries/cms.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CliApplication.php
  libraries/src/Application/DaemonApplication.php
  libraries/src/Application/WebApplication.php
  libraries/src/Event/Table/AbstractEvent.php
  libraries/src/MVC/Controller/AdminController.php
  libraries/src/MVC/Controller/ApiController.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Controller/FormController.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/Menu/AbstractMenu.php
  libraries/src/Plugin/PluginHelper.php
  libraries/src/Response/JsonResponse.php
  libraries/src/Router/SiteRouter.php
  libraries/src/Updater/UpdateAdapter.php
  plugins/actionlog/joomla/joomla.php
  plugins/content/confirmconsent/confirmconsent.php
  plugins/content/emailcloak/emailcloak.php
  plugins/content/vote/vote.php
  plugins/editors/tinymce/tinymce.php
  plugins/extension/finder/finder.php
  plugins/extension/joomla/joomla.php
  plugins/extension/namespacemap/namespacemap.php
  plugins/fields/sql/sql.php
  plugins/privacy/user/user.php
  plugins/sampledata/blog/blog.php
  plugins/sampledata/multilang/multilang.php
  plugins/system/accessibility/accessibility.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/fields/fields.php
  plugins/system/languagefilter/languagefilter.php
  plugins/system/logout/logout.php
  plugins/system/logrotation/logrotation.php
  plugins/system/remember/remember.php
  plugins/system/sef/sef.php
  plugins/system/stats/stats.php
  plugins/user/joomla/joomla.php
  plugins/user/profile/profile.php
  plugins/user/terms/terms.php
Labels: PR-4.0-dev

#36445 [4] Au revoir JObject...
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_fields/src/View/Group/HtmlView.php
  administrator/components/com_finder/src/Controller/IndexerController.php
  administrator/components/com_finder/src/View/Filter/HtmlView.php
  administrator/components/com_finder/src/View/Searches/HtmlView.php
  administrator/components/com_installer/src/View/Installer/HtmlView.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_languages/src/View/Installed/HtmlView.php
  administrator/components/com_languages/src/View/Language/HtmlView.php
  administrator/components/com_languages/src/View/Languages/HtmlView.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_menus/src/Model/MenutypesModel.php
  administrator/components/com_menus/src/View/Item/HtmlView.php
  administrator/components/com_menus/src/View/Menu/HtmlView.php
  administrator/components/com_menus/src/View/Menutypes/HtmlView.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_modules/src/View/Module/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeeds/HtmlView.php
  administrator/components/com_plugins/src/Helper/PluginsHelper.php
  administrator/components/com_plugins/src/Model/PluginModel.php
  administrator/components/com_plugins/src/View/Plugin/HtmlView.php
  administrator/components/com_plugins/src/View/Plugins/HtmlView.php
  administrator/components/com_redirect/src/View/Link/HtmlView.php
  administrator/components/com_tags/src/View/Tag/HtmlView.php
  administrator/components/com_tags/src/View/Tags/HtmlView.php
  administrator/components/com_templates/src/Model/StyleModel.php
  administrator/components/com_templates/src/View/Style/HtmlView.php
  administrator/components/com_templates/src/View/Style/JsonView.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  components/com_contact/src/Model/FormModel.php
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/src/View/Contact/VcfView.php
  components/com_contact/src/View/Featured/HtmlView.php
  components/com_content/src/View/Archive/HtmlView.php
  components/com_content/src/View/Article/HtmlView.php
  components/com_content/src/View/Featured/HtmlView.php
  components/com_content/src/View/Form/HtmlView.php
  components/com_finder/src/View/Search/HtmlView.php
  components/com_tags/src/View/Tag/HtmlView.php
  components/com_tags/src/View/Tags/HtmlView.php
  plugins/editors-xtd/article/article.php
  plugins/editors-xtd/contact/contact.php
  plugins/editors-xtd/fields/fields.php
  plugins/editors-xtd/module/module.php
  plugins/editors-xtd/pagebreak/pagebreak.php
  tests/Unit/Libraries/Cms/Object/CMSObjectTest.php
Labels: PR-4.0-dev

#36443 [4.0] Remove reference to old JPrefixed Class + Cleanup (JTable etc)
  administrator/components/com_actionlogs/src/Model/ActionlogsModel.php
  administrator/components/com_associations/src/Field/Modal/AssociationField.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_contenthistory/src/Model/CompareModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_fields/src/Model/GroupModel.php
  administrator/components/com_fields/src/Table/FieldTable.php
  administrator/components/com_fields/src/Table/GroupTable.php
  administrator/components/com_finder/src/Model/IndexModel.php
  administrator/components/com_finder/src/Model/MapsModel.php
  administrator/components/com_mails/src/Model/TemplateModel.php
  administrator/components/com_menus/src/Model/MenuModel.php
  administrator/components/com_plugins/src/Model/PluginsModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_workflow/src/Model/StagesModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowsModel.php
  administrator/components/com_workflow/src/Table/StageTable.php
  administrator/components/com_workflow/src/Table/TransitionTable.php
  administrator/components/com_workflow/src/Table/WorkflowTable.php
  components/com_privacy/src/Model/RemindModel.php
  components/com_privacy/src/Model/RequestModel.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  libraries/src/Event/Table/AbstractEvent.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Table/Category.php
  libraries/src/UCM/UCMContent.php
  tests/Unit/bootstrap.php
Labels: Unit/System Tests, PR-4.0-dev

#36374 [4.x] Fix checked out pkg_search extension after update from 3.10
  administrator/components/com_admin/sql/updates/mysql/4.0.6-2021-12-23.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.6-2021-12-23.sql
Labels: PR-4.0-dev

#36406 [4.0] Correct return type
  administrator/components/com_content/src/Controller/ArticlesController.php
Labels: PR-4.0-dev

#36398 [3] fix PHP 8 Deprecation preg_split, limit s/null/-1
  libraries/src/Filter/OutputFilter.php
  libraries/src/Schema/ChangeItem/PostgresqlChangeItem.php
Labels: PR-3.10-dev, PHP 8

#36430 [4.0] Remove all references to old JPrefixed Class in /components/
  components/com_config/src/Controller/ConfigController.php
  components/com_config/src/Controller/ModulesController.php
  components/com_config/src/Controller/TemplatesController.php
  components/com_config/src/View/Config/HtmlView.php
  components/com_config/src/View/Modules/HtmlView.php
  components/com_config/src/View/Templates/HtmlView.php
  components/com_contact/src/Controller/DisplayController.php
  components/com_contact/src/Model/FormModel.php
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/src/View/Contact/VcfView.php
  components/com_contact/src/View/Featured/HtmlView.php
  components/com_content/src/Controller/DisplayController.php
  components/com_content/src/Model/CategoryModel.php
  components/com_content/src/View/Archive/HtmlView.php
  components/com_content/src/View/Article/HtmlView.php
  components/com_content/src/View/Category/FeedView.php
  components/com_content/src/View/Featured/HtmlView.php
  components/com_content/src/View/Form/HtmlView.php
  components/com_contenthistory/src/Controller/DisplayController.php
  components/com_fields/src/Controller/DisplayController.php
  components/com_finder/src/View/Search/HtmlView.php
  components/com_modules/src/Controller/DisplayController.php
  components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  components/com_tags/src/View/Tag/HtmlView.php
  components/com_tags/src/View/Tags/HtmlView.php
  components/com_users/src/Model/RemindModel.php
  components/com_users/src/View/Login/HtmlView.php
  components/com_users/src/View/Profile/HtmlView.php
  components/com_users/src/View/Registration/HtmlView.php
  components/com_users/src/View/Remind/HtmlView.php
  components/com_users/src/View/Reset/HtmlView.php
  libraries/src/MVC/Controller/AdminController.php
Labels: PR-4.0-dev

#36384 [4.0] Variable already equals the assigned value
  plugins/system/webauthn/src/PluginTraits/AjaxHandler.php
Labels: PR-4.0-dev

#36427 [4] remove incorrect param in call to posix_getuid
  libraries/src/Application/DaemonApplication.php
Labels: RTC, PR-4.0-dev

#36364 [4.0] codemirror update
  package-lock.json
  plugins/editors/codemirror/codemirror.xml
Labels: PR-4.0-dev, NPM Resource Changed

#36377 [4.1] 'isset' can be replaced with coalesce
  api/components/com_categories/src/View/Categories/JsonapiView.php
  api/components/com_contact/src/View/Contacts/JsonapiView.php
  api/components/com_content/src/View/Articles/JsonapiView.php
  api/components/com_users/src/View/Users/JsonapiView.php
Labels: RTC, PR-4.1-dev

#36461 [4.1] Fix Task Scheduling Behavior with WebCron (...)
  administrator/components/com_scheduler/src/Scheduler/Scheduler.php
Labels: RTC, PR-4.1-dev

#36297 [4.1] Unification of the language com_scheduler, part 3
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#36438 [4.1] Fix pagination in Task Scheduler
  administrator/components/com_scheduler/src/Model/TasksModel.php
Labels: RTC, PR-4.1-dev

#36507 [4.1] Fix asset table sequence next value for PostgreSQL after upmerge from 4.0-dev
  installation/sql/postgresql/base.sql
Labels: Release Blocker, PR-4.1-dev

#36480 [4.1 Scheduled Tasks] Unused constants
  administrator/language/en-GB/com_scheduler.ini
Labels: Language Change, PR-4.1-dev

#36479 [4.1 Scheduled Tasks] Missing constants and demo plugin description
  administrator/language/en-GB/com_scheduler.sys.ini
  plugins/task/demotasks/demotasks.xml
Labels: Language Change, PR-4.1-dev

#36509 [4.0] Fix duplicate lft rgt in assets table for PostgreSQL
  installation/sql/postgresql/base.sql
Labels: Release Blocker, PR-4.0-dev
