Repository joomla/joomla-cms, pull requests merged in 2021-11, with the labels that each got.

#35957 [4.0] s/send/sent
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.0-dev

#35056 [4.0] Fix state filter options in workflows manager
  administrator/components/com_workflow/forms/filter_stages.xml
  administrator/components/com_workflow/forms/filter_transitions.xml
  administrator/components/com_workflow/forms/filter_workflows.xml
Labels: RTC, PR-4.0-dev

#35337 Removed fixed width of logo in Cassiopeia header
  templates/cassiopeia/images/logo.svg
  templates/cassiopeia/scss/blocks/_header.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35685 Subform: fix incorrect data-base-name, do not set empty fieldname
  libraries/src/Form/Field/SubformField.php
Labels: RTC, PR-4.0-dev

#35857 [4] Codestyle Remove space
  administrator/components/com_joomlaupdate/extract.php
Labels: RTC, PR-4.0-dev

#33908 [4.0] php-cs-fixer v3.0 Support
  .gitignore
  .php-cs-fixer.dist.php
  .php_cs.dist
  build/build.php
  composer.json
  composer.lock
  tests/Codeception/exclude.txt
Labels: Unit/System Tests, Composer Dependency Changed, PR-4.0-dev

#35956 Update cacert-update.yml Action
  .github/workflows/cacert-update.yml
Labels: PR-4.0-dev

#35947 [4.0] Fix disabled attribute for Radio form field
  layouts/joomla/form/field/radio/buttons.php
Labels: RTC, PR-4.0-dev

#35923 [4.0] Fix SQL error 1064 (SQL syntax error) on template overrides table updates when updating extensions
  plugins/installer/override/override.php
Labels: RTC, PR-4.0-dev

#35909 Change warning descriptions for minimum to 16MB
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.0-dev

#35894 [4.0] No Articles Message
  components/com_content/tmpl/category/blog.php
  components/com_content/tmpl/category/default_articles.php
Labels: RTC, PR-4.0-dev

#35867 Correct class of div for pagination
  components/com_contact/tmpl/category/default_items.php
Labels: RTC, PR-4.0-dev

#35860 Subhead with buttons is removed on certain breakpoints
  build/media_source/templates/administrator/atum/js/template.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed, hacktoberfest-accepted

#35834 [4.0] Fix hiddenLabel for invisiable recaptcha plugin
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
Labels: RTC, PR-4.0-dev

#35862 Fix table breakpoint in Maintenance: Database view
  administrator/components/com_installer/tmpl/database/default.php
Labels: RTC, PR-4.0-dev, hacktoberfest-accepted

#35662 [4.0] Don't show help button if no help URL or reference is defined
  administrator/components/com_categories/src/View/Categories/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_config/src/View/Component/HtmlView.php
  libraries/src/Toolbar/ToolbarHelper.php
Labels: RTC, PR-4.0-dev

#35875 [4.0] Missing help
  administrator/components/com_menus/forms/itemadmin_container.xml
Labels: RTC, PR-4.0-dev

#35877 [4.0] Joomla CLI breaks if absolute path is used and System Page Cache plugin is enabled
  plugins/system/cache/cache.php
Labels: RTC, PR-4.0-dev

#35978 [4.0] Fix wrong pre-update checker behavior
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
Labels: RTC, PR-4.0-dev

#35963 Display contact without icons
  components/com_contact/tmpl/contact/default_address.php
Labels: RTC, PR-4.0-dev

#35935 [4.0] [webservices] wrong parameter for setting Access-Control-Allow-Headers
  libraries/src/Application/ApiApplication.php
Labels: RTC, PR-4.0-dev

#35700 [4.0] xml review
  administrator/components/com_banners/forms/filter_tracks.xml
  administrator/components/com_installer/forms/filter_languages.xml
  administrator/components/com_privacy/config.xml
  administrator/components/com_tags/forms/filter_tags.xml
  administrator/components/com_templates/forms/filter_styles.xml
  administrator/components/com_workflow/workflow.xml
  components/com_newsfeeds/tmpl/newsfeed/default.xml
  plugins/webservices/installer/installer.xml
Labels: RTC, PR-4.0-dev

#35903 [4.0] modals invisible tinymce fullscreen
  administrator/templates/atum/scss/vendor/_tinymce.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35981 [4.0] Fix wrong input filter type for extension names of site and admin languages in the extensions installer
  libraries/src/Installer/Adapter/LanguageAdapter.php
Labels: RTC, PR-4.0-dev

#35974 [4.0] Fix notice about duplicate joomla/mediawiki in composer.json when running composer install
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.0-dev

#35453 [4.0] Persist search in local storage
  administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue
  administrator/components/com_media/resources/scripts/store/plugins/persisted-state.es6.js
  tests/Codeception/_support/Page/Acceptance/Administrator/MediaListPage.php
  tests/Codeception/acceptance/administrator/components/com_media/MediaListCest.php
Labels: RTC, Unit/System Tests, PR-4.0-dev, NPM Resource Changed

#35990 [4.0] Fix doc block indentation
  administrator/components/com_media/resources/scripts/store/mutations.es6.js
Labels: RTC, PR-4.0-dev

#23577 [4.1] Parameters for Module Chromes
  administrator/components/com_modules/forms/advanced.xml
  administrator/components/com_modules/src/Model/ModuleModel.php
Labels: RTC, PR-4.1-dev

#34658 [4.x] Menu Items with icon only
  administrator/components/com_menus/forms/item_alias.xml
  administrator/components/com_menus/forms/item_component.xml
  administrator/components/com_menus/forms/item_heading.xml
  administrator/components/com_menus/forms/item_separator.xml
  administrator/components/com_menus/forms/item_url.xml
  administrator/components/com_menus/forms/itemadmin_alias.xml
  modules/mod_menu/src/Helper/MenuHelper.php
  modules/mod_menu/tmpl/default_component.php
  modules/mod_menu/tmpl/default_heading.php
  modules/mod_menu/tmpl/default_separator.php
  modules/mod_menu/tmpl/default_url.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu_component.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu_heading.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu_separator.php
  templates/cassiopeia/html/mod_menu/dropdown-metismenu_url.php
Labels: RTC, PR-4.1-dev

#35736 Enhance build tools doc
  build/README.md
Labels: RTC, PR-4.0-dev

#35969 [4.0] [bugfix] Fix popover missing content
  build/media_source/vendor/bootstrap/js/popover.es6.js
Labels: RTC, PR-4.0-dev

#35563 [4.0] pragma header
  administrator/components/com_menus/src/View/Menu/XmlView.php
  libraries/src/Application/CMSApplication.php
  plugins/system/languagefilter/languagefilter.php
Labels: RTC, PR-4.0-dev

#35675 Causing issue in PHP8.0.11 due to BC break in PHP8.0 regarding call_user_func_array and named parameters
  libraries/src/Captcha/Captcha.php
Labels: RTC, PR-4.0-dev

#35936 [3.0] Remove duplicate attributes
  components/com_content/views/categories/tmpl/default_items.php
  components/com_content/views/category/tmpl/blog_children.php
  components/com_content/views/category/tmpl/default_children.php
Labels: RTC, PR-3.10-dev

#35715 Tinymce html5 containers
  administrator/language/en-GB/plg_editors_tinymce.ini
  plugins/editors/tinymce/tinymce.php
Labels: RTC, Language Change, PR-4.0-dev

#35988 Removed Complete & from open site and open admin button
  installation/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.0-dev

#35994 Adds events on show/hide of showon elements
  build/media_source/system/js/showon.es6.js
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36017 [4.1] Make the getElement function easier to read in PluginAdapter
  libraries/src/Installer/Adapter/PluginAdapter.php
Labels: RTC, PR-4.1-dev

#35887 [4.1] Refactor vue browser items
  administrator/components/com_media/resources/scripts/components/browser/actionItems/actionItemsContainer.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/delete.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/download.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/edit.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/export.es6.js
  administrator/components/com_media/resources/scripts/components/browser/actionItems/preview.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/rename.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/share.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/toggle.vue
  administrator/components/com_media/resources/scripts/components/browser/items/audio.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/document.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  administrator/components/com_media/resources/scripts/mediamanager.es6.js
  package-lock.json
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#33086 [4.0] Alternative menu
  administrator/components/com_menus/presets/alternate.xml
  administrator/language/en-GB/mod_menu.ini
Labels: RTC, Language Change, PR-4.0-dev

#35950 [4.1] Contact save to menu
  administrator/components/com_contact/src/Controller/ContactController.php
  administrator/components/com_contact/src/View/Contact/HtmlView.php
Labels: RTC, PR-4.1-dev

#35114 Fix layout article categories list as tree
  build/media_source/com_categories/css/shared-categories-accordion.css
  components/com_content/tmpl/categories/default_items.php
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35886 [4.1] Remove old asset code in media manager
  components/com_media/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-4.1-dev

#36033 [4.0] remove unused fontawesome override
  administrator/templates/atum/scss/vendor/fontawesome-free/fontawesome.scss
Labels: RTC, PR-4.0-dev

#36050 [4.0] Update NPM dependencies to fix audit issues
  package-lock.json
  package.json
Labels: PR-4.0-dev, NPM Resource Changed

#36072 Minimum Password Length
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.0-dev

#36066 [4.0] tinymce plugin configuration re-paint
  administrator/language/en-GB/plg_editors_tinymce.ini
  administrator/language/en-GB/plg_editors_tinymce.sys.ini
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder/setaccess.php
  plugins/editors/tinymce/src/Field/TinymcebuilderField.php
Labels: RTC, Language Change, PR-4.0-dev

#36076 [4.0]custom-select-color-state update
  components/com_contact/tmpl/categories/default.xml
  components/com_contact/tmpl/category/default.xml
Labels: PR-4.0-dev

#36077 [4.0] pre-update check unused class
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
Labels: RTC, PR-4.0-dev

#36079 [4.0] Fix invalid closing HTML tags
  administrator/components/com_associations/tmpl/associations/modal.php
  components/com_contact/tmpl/category/default_items.php
Labels: RTC, PR-4.0-dev

#36078 [4.0] Pre-update check icon spacing
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
Labels: RTC, PR-4.0-dev

#36081 [4.0] mod_articles_archive
  modules/mod_articles_archive/mod_articles_archive.xml
Labels: PR-4.0-dev

#36059 [4.0] build.js codestyle
  build/build.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35610 Hide–able inline help in back– and frontend forms
  administrator/components/com_config/forms/application.xml
  administrator/components/com_config/src/View/Application/HtmlView.php
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/joomla.ini
  build/media_source/legacy/js/toolbar.es5.js
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/inlinehelp.es6.js
  components/com_config/forms/config.xml
  components/com_config/src/View/Config/HtmlView.php
  components/com_config/tmpl/config/default.php
  components/com_config/tmpl/config/default_metadata.php
  components/com_config/tmpl/config/default_seo.php
  components/com_config/tmpl/config/default_site.php
  language/en-GB/com_config.ini
  language/en-GB/joomla.ini
  layouts/joomla/form/field/calendar.php
  layouts/joomla/form/field/combo.php
  layouts/joomla/form/field/email.php
  layouts/joomla/form/field/list.php
  layouts/joomla/form/field/number.php
  layouts/joomla/form/field/password.php
  layouts/joomla/form/field/range.php
  layouts/joomla/form/field/tel.php
  layouts/joomla/form/field/text.php
  layouts/joomla/form/field/textarea.php
  layouts/joomla/form/field/time.php
  layouts/joomla/form/field/url.php
  layouts/joomla/form/renderfield.php
  libraries/src/Toolbar/Button/InlinehelpButton.php
  libraries/src/Toolbar/Toolbar.php
  libraries/src/Toolbar/ToolbarHelper.php
Labels: RTC, Language Change, a11y, NPM Resource Changed, PR-4.1-dev

#35607 [4.1] Language of Parts [a11y]
  administrator/language/en-GB/plg_editors_tinymce.ini
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/tinymce.php
  templates/cassiopeia/scss/editor.scss
  templates/system/scss/editor.scss
Labels: RTC, Language Change, a11y, NPM Resource Changed, PR-4.1-dev

#34808 Re-init tinymce when sorting happen, fix #24343
  media/editors/tinymce/js/tinymce.js
  media/editors/tinymce/js/tinymce.min.js
Labels: PR-3.10-dev

#35591 Make sure only non blocked users can recive actionlogs emails
  administrator/components/com_actionlogs/models/actionlog.php
Labels: PR-3.10-dev

#35841 Add a proper error message if a pack fails to download
  installation/language/en-GB/en-GB.ini
  installation/model/languages.php
Labels: Language Change, PR-3.10-dev

#35980 [3.10] Fix wrong input filter type for extension names of site and admin languages in the extensions installer
  libraries/src/Installer/Adapter/LanguageAdapter.php
Labels: RTC, PR-3.10-dev

#36041 PHP 8.1 compatibility
  administrator/components/com_categories/src/Model/CategoriesModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/Table/Table.php
Labels: RTC, Release Blocker, PR-4.0-dev

#36082 [4.0] max-width inline style
  administrator/components/com_templates/src/Service/HTML/Templates.php
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC, PR-4.0-dev

#35889 [4.0] Update tinymce and codemirror
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
  plugins/editors/tinymce/tinymce.php
  plugins/editors/tinymce/tinymce.xml
Labels: Release Blocker, PR-4.0-dev, NPM Resource Changed

#35528 [3.10] Progressive cache fix
  libraries/src/Document/HtmlDocument.php
Labels: RTC, J3 Issue, PR-3.10-dev

#36091 Validated type=number in Modules
  modules/mod_articles_latest/mod_articles_latest.xml
  modules/mod_articles_news/mod_articles_news.xml
  modules/mod_banners/mod_banners.xml
  modules/mod_feed/mod_feed.xml
  modules/mod_related_items/mod_related_items.xml
  modules/mod_users_latest/mod_users_latest.xml
Labels: PR-4.0-dev

#35788 [4.1] Media webservice
  administrator/language/en-GB/plg_webservices_media.ini
  administrator/language/en-GB/plg_webservices_media.sys.ini
  api/components/com_media/src/Controller/AdaptersController.php
  api/components/com_media/src/Controller/MediaController.php
  api/components/com_media/src/Helper/AdapterTrait.php
  api/components/com_media/src/Model/AdapterModel.php
  api/components/com_media/src/Model/AdaptersModel.php
  api/components/com_media/src/Model/MediaModel.php
  api/components/com_media/src/Model/MediumModel.php
  api/components/com_media/src/View/Adapters/JsonapiView.php
  api/components/com_media/src/View/Media/JsonapiView.php
  api/language/en-GB/com_media.ini
  composer.json
  composer.lock
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Error/JsonApi/SaveExceptionHandler.php
  plugins/webservices/media/media.php
  plugins/webservices/media/media.xml
  tests/Codeception/_support/Helper/Api.php
  tests/Codeception/_support/Helper/JoomlaDb.php
  tests/Codeception/acceptance/01-install/InstallCest.php
  tests/Codeception/api.suite.dist.yml
  tests/Codeception/api/BasicCest.php
  tests/Codeception/api/com_banners/BannerCest.php
  tests/Codeception/api/com_contact/ContactCest.php
  tests/Codeception/api/com_content/ContentCest.php
  tests/Codeception/api/com_media/MediaCest.php
Labels: Unit/System Tests, Language Change, Composer Dependency Changed, PR-4.1-dev

#36098 [4.0] Change markup of "No matching results" alert
  administrator/components/com_mails/tmpl/templates/default.php
Labels: RTC, PR-4.0-dev

#35647 [4.1] Tiny source code syntax highlighting
  administrator/language/en-GB/plg_editors_tinymce.ini
  build/build-modules-js/init/exemptions/tinymce.es6.js
  build/media_source/plg_editors_tinymce/js/plugins/highlighter/plugin.es5.js
  build/media_source/plg_editors_tinymce/js/plugins/highlighter/source.css
  build/media_source/plg_editors_tinymce/js/plugins/highlighter/source.es5.js
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/tinymce.php
Labels: RTC, Language Change, NPM Resource Changed, PR-4.1-dev

#36100 Validated type=number in Administrator Modules
  administrator/modules/mod_custom/mod_custom.xml
  administrator/modules/mod_feed/mod_feed.xml
  administrator/modules/mod_latest/mod_latest.xml
  administrator/modules/mod_latestactions/mod_latestactions.xml
  administrator/modules/mod_logged/mod_logged.xml
  administrator/modules/mod_loginsupport/mod_loginsupport.xml
  administrator/modules/mod_popular/mod_popular.xml
  administrator/modules/mod_privacy_dashboard/mod_privacy_dashboard.xml
  administrator/modules/mod_privacy_status/mod_privacy_status.xml
  administrator/modules/mod_quickicon/mod_quickicon.xml
  administrator/modules/mod_stats_admin/mod_stats_admin.xml
Labels: RTC, PR-4.0-dev

#35485 [3] FOF encryption fails on PHP 8
  libraries/fof/encrypt/aes.php
Labels: PR-3.10-dev

#35863 [4.1] Allow User Media Field to be accessible to Registered users (Reworks #19038)
  components/com_media/src/Dispatcher/Dispatcher.php
  plugins/fields/media/media.php
Labels: RTC, PR-4.1-dev

#36110 [4.0] codemirror update
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
Labels: PR-4.0-dev, NPM Resource Changed

#36094 [4.0] Recreate namespace map on Joomla! update
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: RTC, Release Blocker, PR-4.0-dev

#36125 Correct type hint class name - s/Reset/ResetModel
  components/com_users/src/Controller/ResetController.php
Labels: PR-4.0-dev

#36126 [4.0] Correctly Namespace class
  components/com_config/src/Dispatcher/Dispatcher.php
Labels: PR-4.0-dev

#36123 s/conyact/contact
  administrator/components/com_contact/src/View/Contact/HtmlView.php
Labels: RTC, PR-4.1-dev

#36129 [4.1] HTML line breaks not required in class docblocks
  plugins/task/checkfiles/checkfiles.php
  plugins/task/requests/requests.php
Labels: PR-4.1-dev

#36127 [4.0] fix undefined class in typehint
  components/com_config/src/View/Modules/HtmlView.php
Labels: PR-4.0-dev

#36128 [4.1] 'return' is unnecessary as the last statement in a method
  administrator/components/com_scheduler/src/Task/TaskOption.php
Labels: PR-4.1-dev

#36130 [4.1] Fix Undefined Class s/Jobs/Scheduler
  libraries/src/Console/TasksStateCommand.php
Labels: PR-4.1-dev

#36083 [3.10] Backport php8.1 compatibility fixes
  administrator/components/com_categories/models/categories.php
  administrator/components/com_categories/models/category.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/Table/Table.php
  tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php
Labels: Unit/System Tests, PR-3.10-dev

#35107 [3.10] Add a check whether we are running the core backend template and issue an info when that is not the case
  administrator/components/com_joomlaupdate/models/default.php
  administrator/components/com_joomlaupdate/views/default/tmpl/default_preupdatecheck.php
  administrator/components/com_joomlaupdate/views/default/view.html.php
  administrator/language/en-GB/en-GB.com_joomlaupdate.ini
Labels: Language Change, Documentation Required, PR-3.10-dev

#36136 [4.0] template icon
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_templates/src/View/Templates/HtmlView.php
Labels: RTC, PR-4.0-dev

#36138 [4.0] spaces to tabs
  administrator/manifests/packages/pkg_search.xml
Labels: RTC, PR-4.0-dev

#36040 Cassopeia rtl update
  build/media_source/system/css/frontediting.css
  templates/cassiopeia/scss/blocks/_header.scss
  templates/cassiopeia/scss/template-rtl.scss
  templates/cassiopeia/scss/vendor/metismenu/_metismenu.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#36039 [4.0] remove unused atum rtl css
  administrator/templates/atum/scss/template-rtl.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36036 [4.0] swticher css - rtl
  build/media_source/system/scss/fields/switcher.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#36035 [4.0] com_associations rtl
  build/media_source/com_associations/css/sidebyside.css
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36032 [4.0] header.css unused
  administrator/templates/atum/scss/blocks/_header.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#36031 [4.0] Atum alert styling
  administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#36029 [4.0] Template tree rtl
  administrator/templates/atum/scss/blocks/_treeselect.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#36026 [4.0] Fancy selectbox fix
  administrator/templates/atum/scss/vendor/choicesjs/choices.scss
  templates/cassiopeia/scss/vendor/choicesjs/choices.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#36025 [4.0] RTL: Correcting sidebar menu
  administrator/templates/atum/scss/blocks/_sidebar.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#36133 [4.1] remove unused import in 4.1 media api
  api/components/com_media/src/View/Media/JsonapiView.php
Labels: RTC, PR-4.1-dev

#36030 [4.0] Atum content quicklinks
  administrator/templates/atum/scss/blocks/_quickicons.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#35924 [4.0] Update FieldsModel.php: Fix missing filter in store id.
  administrator/components/com_fields/src/Model/FieldsModel.php
Labels: RTC, PR-4.0-dev

#35996 Solved -- To Top button overlaps information
  templates/cassiopeia/scss/blocks/_back-to-top.scss
Labels: RTC, PR-4.0-dev, NPM Resource Changed, RLDQ

#35960 Notification subject: Use Item title, not model name
  administrator/language/en-GB/plg_workflow_notification.ini
  plugins/workflow/notification/notification.php
Labels: RTC, Language Change, PR-4.0-dev

#35514 [4] Avoid the EOL underline of the title link
  modules/mod_articles_category/tmpl/default_items.php
Labels: RTC, PR-4.0-dev

#35761 [4.0] Versions Toolbar when button disabled
  build/media_source/com_contenthistory/js/admin-history-modal.es6.js
Labels: RTC, PR-4.0-dev, NPM Resource Changed

#35729 Cassiopeia template - changing Tagline to Tagline - Optional text to show as a subheading parameter - ALTERNATIVE (35720)
  language/en-GB/tpl_cassiopeia.ini
  templates/cassiopeia/templateDetails.xml
Labels: RTC, Language Change, PR-4.0-dev

#35855 Finder plugins modify component params registry
  plugins/finder/content/content.php
  plugins/finder/tags/tags.php
Labels: RTC, PR-4.0-dev

#35910 [4.0] Add information to the error message
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: RTC, Language Change, PR-4.0-dev

#36142 [4.0] Update deleted files from 4.0.4 to 4.0.5
  administrator/components/com_admin/script.php
Labels: PR-4.0-dev

#36145 [3.10.4-rc1] s/3.0.0/3.10.4
  tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php
Labels: Unit/System Tests, PR-3.10-dev

#36135 [4.1] Move the new task ini files to the correct folder
  administrator/language/en-GB/plg_system_schedulerunner.ini
  administrator/language/en-GB/plg_system_schedulerunner.sys.ini
  administrator/language/en-GB/plg_system_tasknotification.ini
  administrator/language/en-GB/plg_system_tasknotification.sys.ini
  administrator/language/en-GB/plg_task_checkfiles.ini
  administrator/language/en-GB/plg_task_checkfiles.sys.ini
  administrator/language/en-GB/plg_task_demotasks.ini
  administrator/language/en-GB/plg_task_demotasks.sys.ini
  administrator/language/en-GB/plg_task_requests.ini
  administrator/language/en-GB/plg_task_requests.sys.ini
  administrator/language/en-GB/plg_task_sitestatus.ini
  administrator/language/en-GB/plg_task_sitestatus.sys.ini
  plugins/system/tasknotification/language/en-GB/plg_system_tasknotification.sys.ini
Labels: RTC, Language Change, PR-4.1-dev

#35917 [4.1] Support user defined color theme
  templates/cassiopeia/templateDetails.xml
Labels: RTC, PR-4.1-dev

#36161 [4.0] Remove _com_joomlaupdate.scss from deleted files in script.php
  administrator/components/com_admin/script.php
Labels: RTC, PR-4.0-dev

#35899 [4.1] Inject the event dispatcher into the MVC layer
  components/com_content/src/View/Article/HtmlView.php
  libraries/src/Extension/Service/Provider/MVCFactory.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/View/AbstractView.php
Labels: RTC, PR-4.1-dev
