Repository joomla/joomla-cms, pull requests merged in 2022-11, with the labels that each got.

#39118 Remove release checklist
  build/release-checklist.md
Labels: PR-4.2-dev

#39112 Fixing PHP 8 error when $list is not array
  modules/mod_menu/mod_menu.php
Labels: RTC, PR-4.2-dev

#39123 Upgrade web-authn
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.0-dev

#39145 [4.2] tabs to spaces
  administrator/components/com_actionlogs/src/View/Actionlogs/HtmlView.php
  administrator/components/com_admin/src/Service/HTML/Configuration.php
  administrator/components/com_cache/src/View/Cache/HtmlView.php
  administrator/components/com_media/src/View/Media/HtmlView.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  api/components/com_media/src/Controller/AdaptersController.php
  api/components/com_media/src/Controller/MediaController.php
  api/components/com_media/src/Model/AdapterModel.php
  api/components/com_media/src/Model/AdaptersModel.php
  api/components/com_media/src/Model/MediaModel.php
  api/components/com_media/src/Model/MediumModel.php
  api/components/com_media/src/View/Adapters/JsonapiView.php
  api/components/com_media/src/View/Media/JsonapiView.php
  libraries/src/Cache/Cache.php
  libraries/src/Cache/CacheController.php
  libraries/src/Cache/CacheControllerFactory.php
  libraries/src/Cache/CacheControllerFactoryAwareInterface.php
  libraries/src/Cache/CacheControllerFactoryAwareTrait.php
  libraries/src/Cache/CacheControllerFactoryInterface.php
  libraries/src/Cache/CacheStorage.php
  libraries/src/Cache/Controller/CallbackController.php
  libraries/src/Cache/Controller/OutputController.php
  libraries/src/Cache/Controller/PageController.php
  libraries/src/Cache/Controller/ViewController.php
  libraries/src/Cache/Storage/ApcuStorage.php
  libraries/src/Cache/Storage/CacheStorageHelper.php
  libraries/src/Cache/Storage/FileStorage.php
  libraries/src/Cache/Storage/MemcachedStorage.php
  libraries/src/Cache/Storage/RedisStorage.php
  libraries/src/Cache/Storage/WincacheStorage.php
  libraries/src/Component/Router/RouterViewConfiguration.php
  plugins/fields/media/media.php
  plugins/fields/media/tmpl/media.php
  plugins/privacy/actionlogs/actionlogs.php
  plugins/system/actionlogs/actionlogs.php
  plugins/system/cache/services/provider.php
  plugins/system/cache/src/Extension/Cache.php
  plugins/webservices/media/media.php
  tests/Unit/Libraries/Cms/Cache/CacheControllerFactoryAwareTraitTest.php
Labels: PR-4.2-dev

#39164 [4.3] Re-add removed strings (by Upmerge)
  administrator/language/en-GB/com_templates.ini
Labels: Language Change, PR-4.3-dev

#39162 [4.3] Replace Factory::getUser with getCurrentUser
  components/com_content/src/Model/CategoryModel.php
Labels: PR-4.3-dev

#39147 [4.2] com_cache selection
  administrator/components/com_cache/tmpl/cache/default.php
Labels: RTC, PR-4.2-dev

#39172 [4.3] Migrate quickicon privacycheck plugin to services
  plugins/quickicon/privacycheck/privacycheck.php
  plugins/quickicon/privacycheck/privacycheck.xml
  plugins/quickicon/privacycheck/services/provider.php
  plugins/quickicon/privacycheck/src/Extension/PrivacyCheck.php
Labels: RTC, Maintainers Checked, PR-4.3-dev

#39171 [4.3] Migrate quickicon phpversioncheck plugin to services
  plugins/quickicon/phpversioncheck/phpversioncheck.xml
  plugins/quickicon/phpversioncheck/services/provider.php
  plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php
Labels: RTC, Maintainers Checked, PR-4.3-dev

#39169 [4.3] Migrate quickicon extensionupdate plugin to services
  plugins/quickicon/extensionupdate/extensionupdate.xml
  plugins/quickicon/extensionupdate/services/provider.php
  plugins/quickicon/extensionupdate/src/Extension/Extensionupdate.php
Labels: RTC, Maintainers Checked, PR-4.3-dev

#39143 [4.2] Grammar child/children
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#38983 Replace string interpolation deprectaed in PHP 8.2
  administrator/components/com_scheduler/src/Field/WebcronLinkField.php
  administrator/components/com_scheduler/src/Task/TaskOption.php
  libraries/src/Console/TasksStateCommand.php
  libraries/src/Installer/Adapter/PluginAdapter.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#39020 [4.3] Create traits for the CMSObject error and property handling
  libraries/src/Object/CMSObject.php
  libraries/src/Object/LegacyErrorHandlingTrait.php
  libraries/src/Object/LegacyPropertyManagementTrait.php
Labels: PR-4.3-dev

#39168 [4.3] Migrate quickicon downloadkey plugin to services
  plugins/quickicon/downloadkey/downloadkey.xml
  plugins/quickicon/downloadkey/services/provider.php
  plugins/quickicon/downloadkey/src/Extension/Downloadkey.php
Labels: RTC, Maintainers Checked, PR-4.3-dev

#39186 [4.3] remove karma npm script
  package.json
Labels: NPM Resource Changed, PR-4.3-dev

#39008 [4.3] Migrate the extension namespacemap plugin to services
  plugins/extension/namespacemap/namespacemap.xml
  plugins/extension/namespacemap/services/provider.php
  plugins/extension/namespacemap/src/Extension/NamespaceMap.php
Labels: RTC, PR-4.3-dev

#39007 [4.3] Migrate the extension joomla plugin to services
  plugins/extension/joomla/joomla.xml
  plugins/extension/joomla/services/provider.php
  plugins/extension/joomla/src/Extension/Joomla.php
Labels: RTC, PR-4.3-dev

#38446 [4.3] Convert content contact plugin to services
  plugins/content/contact/contact.xml
  plugins/content/contact/services/provider.php
  plugins/content/contact/src/Extension/Contact.php
Labels: RTC, PR-4.3-dev

#38445 [4.3] Convert confirm consent plugin to services
  plugins/content/confirmconsent/confirmconsent.xml
  plugins/content/confirmconsent/services/provider.php
  plugins/content/confirmconsent/src/Extension/ConfirmConsent.php
  tests/Unit/Plugin/Content/ConfirmConsent/Extension/ConfirmConsentTest.php
Labels: RTC, Unit/System Tests, PR-4.3-dev

#39006 [4.3] Migrate the extension finder plugin to services
  plugins/extension/finder/finder.xml
  plugins/extension/finder/services/provider.php
  plugins/extension/finder/src/Extension/Finder.php
Labels: RTC, PR-4.3-dev

#39122 [4.2] Installation sql ordering
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.2-dev

#39135 [4] sql code style quoteName
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
Labels: RTC, PR-4.2-dev

#39106 [4] Fix: Table caption "Sorted by" in list views shows the wrong sort direction.
  layouts/joomla/searchtools/grid/sort.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#39158 [4][com_categories] Verify that the alias is unique before batch move
  administrator/components/com_categories/src/Model/CategoryModel.php
Labels: RTC, PR-4.2-dev

#38977 Content plugins don't check the object they are operating on
  plugins/content/emailcloak/emailcloak.php
  plugins/content/fields/fields.php
  plugins/content/loadmodule/loadmodule.php
Labels: RTC, PR-4.2-dev

#39214 [4.3] Removing references to FoF from comments
  administrator/components/com_postinstall/src/Model/MessagesModel.php
  administrator/components/com_users/src/Service/Encrypt.php
Labels: PR-4.3-dev

#39212 [4.3] Fix wrong language string constant for category permission notes
  administrator/language/en-GB/com_categories.ini
Labels: RTC, Language Change, PR-4.3-dev

#38987 [[4.3] Allow creating of name.min.css
  administrator/components/com_templates/src/Controller/TemplateController.php
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.3-dev

#39114 [4.3] Rewriting com_tags router
  components/com_tags/src/Helper/RouteHelper.php
  components/com_tags/src/Service/Router.php
Labels: RTC, Release Blocker, PR-4.3-dev

#39154 [4.3] Don't allow to select non-existing tags in com_tags menu items
  components/com_tags/tmpl/tag/default.xml
  components/com_tags/tmpl/tag/list.xml
Labels: RTC, PR-4.3-dev

#39204 [4.3] Update deleted files list in script.php
  administrator/components/com_admin/script.php
Labels: PR-4.3-dev

#39215 [4.3] Installation: Add hint for handling of existing tables with same prefix
  installation/forms/setup.xml
  installation/language/en-GB/joomla.ini
Labels: Language Change, Maintainers Checked, PR-4.3-dev

#39155 [4.3] Backend menu: Wrong encoding for mobile menu item
  administrator/templates/atum/html/layouts/status.php
Labels: PR-4.3-dev

#39240 Upmerge 2022 11 18
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  installation/language/af-ZA/langmetadata.xml
  installation/language/ar-AA/langmetadata.xml
  installation/language/bg-BG/langmetadata.xml
  installation/language/ca-ES/langmetadata.xml
  installation/language/cs-CZ/langmetadata.xml
  installation/language/cy-GB/langmetadata.xml
  installation/language/da-DK/langmetadata.xml
  installation/language/el-GR/langmetadata.xml
  installation/language/en-AU/langmetadata.xml
  installation/language/en-CA/langmetadata.xml
  installation/language/en-NZ/langmetadata.xml
  installation/language/en-US/langmetadata.xml
  installation/language/es-ES/langmetadata.xml
  installation/language/et-EE/langmetadata.xml
  installation/language/eu-ES/langmetadata.xml
  installation/language/fa-AF/langmetadata.xml
  installation/language/fa-IR/langmetadata.xml
  installation/language/fi-FI/langmetadata.xml
  installation/language/fr-FR/langmetadata.xml
  installation/language/he-IL/langmetadata.xml
  installation/language/hu-HU/langmetadata.xml
  installation/language/it-IT/langmetadata.xml
  installation/language/ja-JP/langmetadata.xml
  installation/language/ka-GE/langmetadata.xml
  installation/language/kk-KZ/langmetadata.xml
  installation/language/lt-LT/langmetadata.xml
  installation/language/lv-LV/langmetadata.xml
  installation/language/mk-MK/langmetadata.xml
  installation/language/nl-BE/langmetadata.xml
  installation/language/nl-NL/langmetadata.xml
  installation/language/pl-PL/langmetadata.xml
  installation/language/pt-BR/langmetadata.xml
  installation/language/pt-PT/langmetadata.xml
  installation/language/ro-RO/langmetadata.xml
  installation/language/sk-SK/langmetadata.xml
  installation/language/sl-SI/langmetadata.xml
  installation/language/sr-YU/langmetadata.xml
  installation/language/sv-SE/langmetadata.xml
  installation/language/ta-IN/langmetadata.xml
  installation/language/th-TH/langmetadata.xml
  installation/language/tr-TR/langmetadata.xml
  installation/language/uk-UA/langmetadata.xml
  installation/language/vi-VN/langmetadata.xml
  installation/language/zh-CN/langmetadata.xml
  installation/language/zh-TW/langmetadata.xml
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  layouts/joomla/searchtools/grid/sort.php
  plugins/content/emailcloak/emailcloak.php
  plugins/content/fields/fields.php
  plugins/content/loadmodule/loadmodule.php
Labels: Test instructions missing, Language Change, PR-4.3-dev

#39258 [4.3] Re-add missing information (by Upmerge)
  administrator/language/en-GB/com_tags.ini
Labels: Language Change, PR-4.3-dev

#39261 [4.3] Redis cache PR #38490 for 4.3 branch
  libraries/src/Version.php
Labels: PR-4.3-dev

#39134 Required changes after updating Composer dependencies
  libraries/src/Log/DelegatingPsrLogger.php
  libraries/src/WebAuthn/Server.php
  plugins/multifactorauth/webauthn/src/Helper/Credentials.php
  plugins/multifactorauth/webauthn/src/Hotfix/AndroidKeyAttestationStatementSupport.php
  plugins/multifactorauth/webauthn/src/Hotfix/FidoU2FAttestationStatementSupport.php
  plugins/multifactorauth/webauthn/src/Hotfix/Server.php
  plugins/system/webauthn/src/Authentication.php
  plugins/system/webauthn/src/Hotfix/AndroidKeyAttestationStatementSupport.php
  plugins/system/webauthn/src/Hotfix/FidoU2FAttestationStatementSupport.php
  plugins/system/webauthn/src/Hotfix/Server.php
Labels: PR-5.0-dev

#39224 [4.3] Mark deprecation in DelegatingPsrLogger
  libraries/src/Log/DelegatingPsrLogger.php
Labels: PR-4.3-dev

#39227 [4.2] Fix Calendar pointer
  build/media_source/system/css/fields/calendar-rtl.css
  build/media_source/system/css/fields/calendar.css
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38768 Fix: subform fields do not display in user profile
  components/com_users/tmpl/profile/default_custom.php
Labels: RTC, PR-4.2-dev

#39290 [4.2] Missing/Incorrect Lang String
  libraries/src/Installer/Adapter/ModuleAdapter.php
Labels: RTC, PR-4.2-dev

#39284 [4.3] Discover Select columns
  administrator/components/com_installer/tmpl/discover/default.php
Labels: RTC, Maintainers Checked, PR-4.3-dev

#39301 Fix the layout for our standard
  components/com_users/tmpl/profile/default_custom.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#39295 Fix CodeMirror throwing 404 Not Found on text/html.js
  build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39254 [4.2] Fix save tags assignment
  libraries/src/Form/Field/TagField.php
Labels: RTC, PR-4.2-dev

#39253 [4.3] Pre-select category for new custom field
  administrator/components/com_fields/src/Model/FieldModel.php
Labels: RTC, PR-4.3-dev

#39249 [4.3] Fix browser page title for article menu item
  components/com_content/src/View/Article/HtmlView.php
Labels: RTC, Maintainers Checked, PR-4.3-dev

#39248 [4.3] Fix Media Field with Windows directory separator in value
  libraries/src/Form/Field/MediaField.php
Labels: RTC, PR-4.3-dev

#39305 [4.2] Correct exception class in PSR logger
  libraries/src/Log/DelegatingPsrLogger.php
Labels: PR-4.2-dev

#39320 Align the browserlist to the advertised support
  package.json
Labels: NPM Resource Changed, PR-4.2-dev

#39315 [Maintainance] Browserlist cron update
  package.json
Labels: NPM Resource Changed, PR-4.2-dev

#39067 Allow different table key in FormView
  libraries/src/MVC/View/FormView.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#39108 [4] missed prepared statement
  libraries/src/Installer/Adapter/ModuleAdapter.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#39299 Fix PHP 8.1 notice "PHP Deprecated: strpos(): Passing null to parameter #1" when saving an article
  plugins/content/fields/fields.php
Labels: RTC, PHP 8.x, PR-4.2-dev, Maintainers Checked

#39317 [4.2] missing rel="noopener noreferrer" in link language string
  administrator/language/en-GB/plg_twofactorauth_totp.sys.ini
Labels: RTC, Language Change, PR-4.2-dev

#39153 [4.3] After saving a menu item, rebuild the tree
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: RTC, PR-4.3-dev

#39251 [4.2] Fix logout redirect error on multilingual site
  components/com_users/src/Controller/UserController.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#39113 [4.3] Several fixes to single tag view from com_tags
  administrator/components/com_tags/config.xml
  components/com_tags/src/Controller/DisplayController.php
  components/com_tags/src/Model/TagModel.php
  components/com_tags/src/View/Tag/HtmlView.php
Labels: RTC, PR-4.3-dev

#36269 [4.2] Fix Content - Email Cloaking removes CSS from Link
  build/media_source/system/js/joomla-hidden-mail.w-c.es6.js
  plugins/content/emailcloak/emailcloak.php
Labels: RTC, NPM Resource Changed, PR-4.2-dev, Maintainers Checked

#39287 Add a prefix (editor name) to buttons modal id
  layouts/joomla/editors/buttons/button.php
  layouts/joomla/editors/buttons/modal.php
  libraries/src/Editor/Editor.php
Labels: RTC, PR-4.2-dev

#39334 [4.2] fix code comments
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_templates/src/View/Templates/HtmlView.php
Labels: PR-4.2-dev
