Repository joomla/joomla-cms, pull requests merged in 2022-04, with the labels that each got.

#35732 [4.1] module shared session
  administrator/modules/mod_logged/tmpl/default.php
Labels: RTC, PR-4.1-dev

#37365 [4.1] Action Logs Scheduler
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.1-dev

#37326 [4.1] Install Languages columns
  administrator/components/com_installer/tmpl/languages/default.php
Labels: RTC, PR-4.1-dev

#37387 [4.x] Name attribute in xml - code style
  administrator/components/com_scheduler/scheduler.xml
  plugins/system/schedulerunner/schedulerunner.xml
Labels: RTC, PR-4.1-dev

#37368 [4.1] Display global class for intro and full image
  administrator/components/com_content/forms/article.xml
  components/com_content/forms/article.xml
Labels: RTC, PR-4.1-dev

#37115 [4.1] Remove invalid tooltip option in media field
  administrator/language/en-GB/plg_fields_media.ini
  plugins/fields/media/media.php
  plugins/fields/media/media.xml
  plugins/fields/media/params/media.xml
Labels: RTC, Language Change, PR-4.1-dev

#37131 [4.1] com_templates duplicate id
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC, PR-4.1-dev

#37286 [4.1] Missing error strings in installation
  installation/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.1-dev

#37288 [4.1] content params
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.1-dev

#37335 [4.1] Improve template module position preview
  libraries/src/Helper/ModuleHelper.php
Labels: PR-4.1-dev

#37395 [4.1] Save As Copy moves the original menu item to another menu fix
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: RTC, PR-4.1-dev

#37009 [4.1] [PHP 8.1] Fixes Deprecated: strtolower(): Passing null to string in libraries/src/Log/Log.php on line 387
  libraries/src/Log/Log.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#36900 [4.1] Add label to the collapsible menu
  modules/mod_menu/tmpl/collapse-default.php
  templates/cassiopeia/html/mod_menu/collapse-metismenu.php
Labels: RTC, a11y, PR-4.1-dev

#37453 [4.2] Deprecating WinCache for Joomla 5.0
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Cache/Storage/WincacheStorage.php
  libraries/src/Session/SessionFactory.php
Labels: Language Change, PR-4.2-dev

#37360 Make all Cassiopeia variables !default
  build/media_source/templates/site/cassiopeia/scss/tools/variables/_variables.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37041 [4.1] Update the configuration.php-dist thanks @brianteeman
  installation/configuration.php-dist
Labels: RTC, PR-4.1-dev

#37397 [4.X] Improve media view by making control elements sticky
  build/media_source/com_media/scss/components/_layout.scss
  build/media_source/com_media/scss/components/_media-toolbar.scss
  build/media_source/com_media/scss/components/_media-tree.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37356 [4.1] Align the inline help button to the rest of the btns
  layouts/joomla/toolbar/inlinehelp.php
  libraries/src/Toolbar/Button/InlinehelpButton.php
  libraries/src/Toolbar/ToolbarHelper.php
Labels: RTC, PR-4.1-dev

#36903 [4.1] Web Assets everywhere
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_banners/tmpl/download/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_checkin/tmpl/checkin/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/group/edit.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_finder/tmpl/searches/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/discover/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/updatesite/edit.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_joomlaupdate/tmpl/update/finaliseconfirm.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_messages/tmpl/config/default.php
  administrator/components/com_messages/tmpl/messages/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_privacy/tmpl/consents/default.php
  administrator/components/com_privacy/tmpl/request/default.php
  administrator/components/com_privacy/tmpl/request/edit.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/style/edit.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/components/com_users/tmpl/group/edit.php
  administrator/components/com_users/tmpl/level/edit.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/components/com_users/tmpl/users/modal.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
Labels: RTC, PR-4.1-dev

#37462 [4.1] Layout for 2FA parameter
  administrator/components/com_users/config.xml
Labels: RTC, PR-4.1-dev

#37464 [4.1] webauthn table accessibility
  administrator/language/en-GB/plg_system_webauthn.ini
  layouts/plugins/system/webauthn/manage.php
Labels: RTC, Language Change, PR-4.1-dev

#37450 [4.1][bug] Restore image
  components/com_finder/tmpl/search/default_result.php
Labels: RTC, PR-4.1-dev

#37463 [4.1-dev] Fix DB query in `Scheduler::getTaskRecords()`
  administrator/components/com_scheduler/src/Scheduler/Scheduler.php
Labels: RTC, PR-4.1-dev

#37476 [4.1] One time emergency passwords
  components/com_users/tmpl/profile/edit.php
Labels: RTC, PR-4.1-dev

#37481 [4.1] Restore post-installation messages
  administrator/components/com_postinstall/src/Controller/MessageController.php
Labels: RTC, PR-4.1-dev

#33887 Upgrade not downgrade appveyor
  .appveyor.yml
Labels: Unit/System Tests, Test instructions missing, PR-3.10-dev

#37465 [4.1] Fix Debug plugin to dump $_POST requests
  plugins/system/debug/debug.php
Labels: RTC, PR-4.1-dev

#37118 Fix Fields editor plugin for com_categories
  plugins/editors-xtd/fields/fields.php
Labels: RTC, PR-4.1-dev

#37333 [4.1] Check if the output to escape is null in BaseLayout
  libraries/src/Layout/BaseLayout.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37337 [4.1] Check if attributes have a value before trimming in menu table
  libraries/src/Table/Menu.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37500 [4.1] Language sort
  administrator/components/com_languages/forms/filter_installed.xml
Labels: RTC, PR-4.1-dev

#37506 [4.1] configuration.php-dist debug
  installation/configuration.php-dist
Labels: RTC, PR-4.1-dev

#37505 [4.1] Joomla Update Component update site
  administrator/components/com_admin/sql/updates/mysql/4.1.3-2022-04-08.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.3-2022-04-08.sql
  administrator/components/com_joomlaupdate/joomlaupdate.xml
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.1-dev

#37457 [4.2] MediaVersion use Cache instead of Database (reduce 1 db query)
  libraries/src/Version.php
Labels: RTC, PR-4.2-dev

#37515 Updating composer to version 2
  .drone.yml
Labels: Unit/System Tests, PR-4.1-dev

#37504 [4.1]Mail templates missing tags
  administrator/components/com_admin/sql/updates/mysql/4.1.3-2022-04-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.3-2022-04-07.sql
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
Labels: RTC, PR-4.1-dev

#37525 [4.2] Signing .drone.yml
  .drone.yml
Labels: Unit/System Tests, PR-4.2-dev

#37460 [4.2] Enable use of Form::process() in FormModel
  libraries/src/MVC/Model/FormModel.php
Labels: RTC, PR-4.2-dev

#37531 [4.1] Fix title by contact save to menu
  administrator/components/com_contact/src/Controller/ContactController.php
Labels: RTC, PR-4.1-dev

#37535 [4.1] adjustments in lang files
  administrator/language/en-GB/com_admin.ini
  administrator/language/en-GB/com_admin.sys.ini
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_scheduler.ini
  administrator/language/en-GB/com_scheduler.sys.ini
  administrator/language/en-GB/mod_custom.sys.ini
  administrator/language/en-GB/mod_latest.sys.ini
  administrator/language/en-GB/mod_latestactions.sys.ini
  administrator/language/en-GB/mod_logged.ini
  administrator/language/en-GB/mod_logged.sys.ini
  administrator/language/en-GB/plg_system_httpheaders.ini
  administrator/language/en-GB/plg_task_checkfiles.ini
  administrator/language/en-GB/plg_task_checkfiles.sys.ini
  administrator/language/en-GB/plg_task_demotasks.ini
  administrator/language/en-GB/plg_task_demotasks.sys.ini
  administrator/language/en-GB/plg_task_requests.ini
  administrator/language/en-GB/plg_task_requests.sys.ini
  administrator/language/en-GB/plg_task_sitestatus.ini
  administrator/language/en-GB/plg_task_sitestatus.sys.ini
  language/en-GB/com_ajax.ini
  language/en-GB/joomla.ini
  language/en-GB/lib_joomla.sys.ini
  language/en-GB/lib_simplepie.sys.ini
  language/en-GB/mod_articles_category.sys.ini
  language/en-GB/mod_articles_latest.sys.ini
  language/en-GB/mod_articles_news.sys.ini
  language/en-GB/mod_articles_popular.sys.ini
  language/en-GB/mod_banners.sys.ini
  language/en-GB/mod_breadcrumbs.sys.ini
  language/en-GB/mod_custom.sys.ini
  language/en-GB/mod_feed.sys.ini
  language/en-GB/mod_footer.sys.ini
  language/en-GB/mod_login.sys.ini
  language/en-GB/mod_menu.sys.ini
  language/en-GB/mod_random_image.sys.ini
  language/en-GB/mod_stats.sys.ini
  language/en-GB/mod_syndicate.sys.ini
  language/en-GB/mod_tags_similar.sys.ini
  language/en-GB/mod_users_latest.sys.ini
  language/en-GB/mod_whosonline.sys.ini
Labels: RTC, Language Change, PR-4.1-dev

#37446 [4.2] Convert log type field to fancy select
  administrator/components/com_actionlogs/config.xml
  administrator/components/com_actionlogs/src/Field/LogtypeField.php
  plugins/system/actionlogs/forms/actionlogs.xml
Labels: RTC, PR-4.2-dev

#37502 [4.1] Update input dependency which contains PHP 8.1 fixes
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-4.1-dev, PHP 8.x

#37488 [4.1] Use to PHP 8.1 fixes for debug bar dependency
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-4.1-dev, PHP 8.x

#37095 [4.2] Inject the db into the MVC layer
  administrator/components/com_config/src/Model/ApplicationModel.php
  composer.lock
  libraries/src/Extension/Service/Provider/MVCFactory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/DatabaseAwareTrait.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
Labels: Unit/System Tests, Composer Dependency Changed, PR-4.2-dev

#37556 [4.1] Schedule Tasks notification dates
  plugins/system/tasknotification/tasknotification.php
Labels: RTC, PR-4.1-dev

#37558 [4.1] Action Log comments
  plugins/actionlog/joomla/joomla.php
Labels: RTC, PR-4.1-dev

#37563 [4.1] Description for class "Intro Image"
  administrator/components/com_content/forms/article.xml
Labels: RTC, PR-4.1-dev

#37570 Show loading view in installer component properly
  build/media_source/com_installer/js/installer.es6.js
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37346 [3.10] "I do not agree" for two more plugins
  administrator/language/en-GB/en-GB.plg_system_privacyconsent.ini
  administrator/language/en-GB/en-GB.plg_user_profile.ini
  plugins/system/privacyconsent/privacyconsent/privacyconsent.xml
  plugins/user/profile/profiles/profile.xml
Labels: RTC, Language Change, PR-3.10-dev

#37580 [4.1] codestyle php
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: PR-4.1-dev

#37373 [4.1] Fix Deprecated warning for Calendar Form Field
  libraries/src/Form/Field/CalendarField.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37581 [4.1] codestyle xml
  administrator/components/com_cache/config.xml
  administrator/components/com_config/forms/application.xml
  administrator/components/com_contact/config.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/components/com_content/forms/filter_featured.xml
  administrator/components/com_finder/forms/filter.xml
  administrator/components/com_media/config.xml
  administrator/components/com_menus/forms/item_component.xml
  administrator/components/com_redirect/forms/link.xml
  administrator/components/com_templates/forms/source.xml
  administrator/components/com_users/config.xml
  administrator/modules/mod_custom/mod_custom.xml
  administrator/modules/mod_feed/mod_feed.xml
  administrator/modules/mod_frontend/mod_frontend.xml
  administrator/modules/mod_latest/mod_latest.xml
  administrator/modules/mod_logged/mod_logged.xml
  administrator/modules/mod_login/mod_login.xml
  administrator/modules/mod_messages/mod_messages.xml
  administrator/modules/mod_popular/mod_popular.xml
  administrator/modules/mod_post_installation_messages/mod_post_installation_messages.xml
  administrator/modules/mod_title/mod_title.xml
  administrator/modules/mod_user/mod_user.xml
  administrator/modules/mod_version/mod_version.xml
  components/com_contact/tmpl/category/default.xml
  components/com_content/forms/article.xml
  components/com_content/tmpl/categories/default.xml
  components/com_content/tmpl/category/blog.xml
  components/com_content/tmpl/category/default.xml
  components/com_newsfeeds/tmpl/newsfeed/default.xml
  modules/mod_articles_popular/mod_articles_popular.xml
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/tinymce.xml
Labels: PR-4.1-dev

#37559 [4.1] Multilingual Status [a11y]
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/language/en-GB/com_languages.ini
Labels: RTC, Language Change, a11y, PR-4.1-dev

#37594 [4.1] Read More with Title
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.1-dev

#37588 [4.1] com_media: hardcoded language strings
  administrator/components/com_media/src/Provider/ProviderManager.php
  administrator/components/com_media/src/Provider/ProviderManagerHelperTrait.php
  administrator/components/com_media/src/View/File/HtmlView.php
  administrator/language/en-GB/com_media.ini
Labels: RTC, Language Change, PR-4.1-dev

#37597 [4.1] Update uri dependency to 2.0.2
  composer.lock
Labels: Composer Dependency Changed, PR-4.1-dev

#37565 Updating joomla-projects/joomla-browser
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.2-dev

#36353 [4.1] order formdata
  build/media_source/system/js/draggable.es6.js
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37599 [3.10] Label of privacy confirm request
  language/en-GB/en-GB.com_privacy.ini
Labels: RTC, Language Change, PR-3.10-dev

#35771 Update link.php
  layouts/joomla/pagination/link.php
Labels: RTC, a11y, PBF, PR-4.1-dev

#37424 [4.x] List Filters
  language/en-GB/com_contact.ini
Labels: RTC, Language Change, PR-4.1-dev

#37475 [4.1] add target and rel values in com_installer.ini
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PBF, PR-4.1-dev

#30787 Improve remind an PW request / reset messages
  components/com_users/controllers/remind.php
  components/com_users/controllers/reset.php
  components/com_users/models/reset.php
  language/en-GB/en-GB.com_users.ini
Labels: RTC, Language Change, PR-3.10-dev, PBF

#37604 [4.2] Inject the database into the banner HTML service
  administrator/components/com_banners/src/Extension/BannersComponent.php
  administrator/components/com_banners/src/Service/Html/Banner.php
Labels: RTC, PBF, PR-4.2-dev

#37602 [4.1] com_privacy site router is not working
  administrator/components/com_privacy/services/provider.php
  administrator/components/com_privacy/src/Extension/PrivacyComponent.php
Labels: RTC, PBF, PR-4.1-dev, Maintainers Checked

#37608 [4.2] Remove obsolete db reference in featured view
  components/com_content/src/View/Featured/HtmlView.php
Labels: RTC, PBF, PR-4.2-dev, Maintainers Checked

#37609 [4.2] Remove obsolete db reference in profile view
  components/com_users/src/View/Profile/HtmlView.php
Labels: RTC, PBF, PR-4.2-dev, Maintainers Checked

#37607 [4.2] Remove not used db reference in users view
  administrator/components/com_users/src/View/Users/HtmlView.php
Labels: RTC, PBF, PR-4.2-dev, Maintainers Checked

#37610 [4.2] Does a cleanup of the contact icon HTML service
  administrator/components/com_contact/src/Extension/ContactComponent.php
  administrator/components/com_contact/src/Service/HTML/Icon.php
Labels: RTC, PBF, PR-4.2-dev

#37636 [4.2] Create the field in the base model when it doesn't exist
  libraries/src/MVC/Model/BaseDatabaseModel.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
Labels: RTC, Unit/System Tests, Release Blocker, PR-4.2-dev

#37644 [4.1] cli sitedowncommand
  libraries/src/Console/SiteDownCommand.php
Labels: RTC, PR-4.1-dev

#37648 [4.1] Update RemoveUserFromGroupCommand.php
  libraries/src/Console/RemoveUserFromGroupCommand.php
Labels: RTC, PR-4.1-dev

#37641 [4.1] Discover extension strings
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.1-dev

#37647 [4.1] Update SetConfigurationCommand.php
  libraries/src/Console/SetConfigurationCommand.php
Labels: RTC, PR-4.1-dev

#37653 [4.x] Integration test readme
  tests/Integration/README.md
  tests/Unit/README.md
Labels: Unit/System Tests, PR-4.1-dev

#37445 [4.2] Introduce helper factory aware interface and convert news module to services
  libraries/src/Extension/Module.php
  libraries/src/Extension/Service/Provider/HelperFactory.php
  libraries/src/Helper/HelperFactory.php
  libraries/src/Helper/HelperFactoryAwareInterface.php
  libraries/src/Helper/HelperFactoryAwareTrait.php
  modules/mod_articles_news/mod_articles_news.php
  modules/mod_articles_news/mod_articles_news.xml
  modules/mod_articles_news/services/provider.php
  modules/mod_articles_news/src/Dispatcher/Dispatcher.php
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
Labels: RTC, PR-4.2-dev

#37583 [4.2] Indicate if category not published
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/language/en-GB/lib_joomla.ini
  libraries/src/Button/PublishedButton.php
Labels: RTC, Language Change, PR-4.2-dev, Maintainers Checked

#37632 [4.2] Fix class name in uri test
  tests/Unit/Libraries/Cms/Uri/UriTest.php
Labels: RTC, Unit/System Tests, PR-4.2-dev

#37634 [4.2] Deprecate old resync function
  administrator/components/com_menus/src/Controller/MenusController.php
Labels: RTC, PR-4.2-dev

#37654 [4.2] Allow typing in media field
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  build/media_source/system/js/fields/joomla-media-select.w-c.es6.js
  layouts/joomla/form/field/media.php
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#37672 [4.1] Fix hover button in Templates
  administrator/components/com_templates/tmpl/template/default_modal_rename_footer.php
Labels: RTC, PR-4.1-dev

#37657 [4.x] Batch Users move
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.1-dev

#37680 [4.1] codestyle Update web.config
  libraries/web.config
Labels: RTC, PR-4.1-dev

#37605 [4.2] Move check for discoverable extensions to model
  administrator/components/com_installer/src/Model/DiscoverModel.php
  administrator/components/com_installer/src/View/Discover/HtmlView.php
Labels: RTC, PR-4.2-dev

#37688 [php 80] Fix error when delete a user that have profile values
  plugins/user/profile/profile.php
Labels: RTC, PR-4.1-dev

#37661 [4.2] PHP8.0 fix for BaseDatabaseModel: Only variable references
  libraries/src/MVC/Model/BaseDatabaseModel.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
Labels: Unit/System Tests, PR-4.2-dev

#37693 Selectlist for menuitem parent as fancyselect
  administrator/components/com_menus/forms/item.xml
Labels: RTC, PR-4.2-dev

#37683 Fix options in mailtemplate form
  administrator/components/com_mails/forms/template.xml
  administrator/language/en-GB/com_mails.ini
Labels: RTC, Language Change, PR-4.1-dev

#37694 [4.x] Fix for Modules Filter after duplicate module
  administrator/components/com_modules/src/Controller/ModulesController.php
Labels: RTC, PR-4.1-dev, Maintainers Checked

#37666 [4.1] com_content: hardcoded language string
  components/com_content/helpers/icon.php
  language/en-GB/com_content.ini
Labels: RTC, PR-4.1-dev

#37650 [4.x] Fields - Empty trash
  administrator/components/com_fields/src/View/Fields/HtmlView.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
Labels: RTC, Unit/System Tests, PR-4.1-dev, Maintainers Checked

#37695 [4.1] Correcting Icon tooltip position for select menu item modal
  build/media_source/templates/site/cassiopeia/scss/blocks/_form.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37338 [4.1] Indexer result serializer PHP 8.1 fixes
  administrator/components/com_finder/src/Indexer/Result.php
  tests/Unit/CMS/administrator/components/com_finder/src/Indexer/ResultTest.php
Labels: RTC, Unit/System Tests, PR-4.1-dev, PHP 8.x

#37671 [4.1] Missing description line in config
  administrator/components/com_config/forms/application.xml
Labels: RTC, PR-4.1-dev, Maintainers Checked

#20905 Change date format in Last-Modifed Header
  libraries/src/Application/WebApplication.php
Labels: RTC, PR-3.10-dev

#37497 [4.1] Cast client_id in template to integer to support mysql PDO
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, PR-4.1-dev

#37638 [4.2] Deprecate a not used function in the modules HTML service
  administrator/components/com_modules/src/Service/HTML/Modules.php
Labels: RTC, PR-4.2-dev
