Repository joomla/joomla-cms, pull requests merged in 2022-06, with the labels that each got.

#37943 [4.1] added deprecation note for 5.0 signature change
  libraries/src/Encrypt/Aes.php
Labels: PR-4.1-dev

#37941 [4.2] Fix uninitialized version variable in installer library
  libraries/src/Installer/Installer.php
Labels: RTC, PR-4.2-dev

#36752 [4.2] Smart Search: Allow fuzzy word matching
  administrator/components/com_finder/config.xml
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/language/en-GB/com_finder.ini
  components/com_finder/src/Model/SearchModel.php
Labels: Language Change, PR-4.2-dev

#37944 [4.1] PHP 8.1 Fix deprecated parse_str() passing null, in Menu ItemModel
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: RTC, PR-4.1-dev

#37568 Fix deprecation warning in com_tags
  components/com_tags/src/Model/TagModel.php
Labels: RTC, PR-4.1-dev, PHP 8.x, Maintainers Checked

#37849 Improve PR #37772 - inlineHelp Toggle Button control
  libraries/src/Form/FormField.php
Labels: RTC, PR-4.1-dev

#37967 [4.2] Add Allon Moritz as code owner for libraries
  .github/CODEOWNERS
Labels: PR-4.2-dev

#37955 [4.2] Adds a bunch of unit tests for the MVC layer
  libraries/src/Application/CMSApplication.php
  libraries/src/MVC/Controller/BaseController.php
  tests/Unit/Libraries/Cms/MVC/Controller/BaseControllerTest.php
  tests/Unit/Libraries/Cms/MVC/Model/BaseModelTest.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
  tests/Unit/Libraries/Cms/MVC/Model/FormModelTest.php
  tests/Unit/Libraries/Cms/MVC/Model/ItemModelTest.php
  tests/Unit/Libraries/Cms/MVC/Model/StateBehaviorTraitTest.php
  tests/Unit/Libraries/Cms/MVC/View/AbstractViewTest.php
  tests/Unit/Libraries/Cms/User/CurrentUserTraitTest.php
Labels: Unit/System Tests, PR-4.2-dev

#36693 Make sure a value is passed to base64_decode
  administrator/components/com_installer/src/Controller/InstallController.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37980 [4.2] Namespace StateBehaviorTraitTest
  tests/Unit/Libraries/Cms/MVC/Model/StateBehaviorTraitTest.php
Labels: Unit/System Tests, PR-4.2-dev

#36303 [4.0] AlreadyPunycodeException exception in email test
  libraries/src/String/PunycodeHelper.php
Labels: RTC, PR-4.1-dev

#36766 [4.1] Finder: Fixing Content Map field
  administrator/components/com_finder/src/Field/ContentmapField.php
Labels: RTC, PR-4.1-dev

#36750 [4.1] Smart Search: Fix forced Itemid in module
  modules/mod_finder/mod_finder.php
  modules/mod_finder/mod_finder.xml
  modules/mod_finder/src/Helper/FinderHelper.php
Labels: RTC, PR-4.1-dev

#37977 Fix deprecated warning in taskModel
  administrator/components/com_scheduler/src/Model/TaskModel.php
Labels: RTC, PR-4.1-dev, PHP 8.x, Maintainers Checked

#37932 com_fields - Fix deprecated warning in group model
  administrator/components/com_fields/src/Model/GroupModel.php
Labels: RTC, PR-4.1-dev, PHP 8.x, Maintainers Checked

#37875 [4.x] Component Permissions description
  administrator/components/com_associations/config.xml
  administrator/components/com_banners/config.xml
  administrator/components/com_cache/config.xml
  administrator/components/com_checkin/config.xml
  administrator/components/com_contact/config.xml
  administrator/components/com_finder/config.xml
  administrator/components/com_installer/config.xml
  administrator/components/com_languages/config.xml
  administrator/components/com_mails/config.xml
  administrator/components/com_media/config.xml
  administrator/components/com_messages/config.xml
  administrator/components/com_newsfeeds/config.xml
  administrator/components/com_plugins/config.xml
  administrator/components/com_postinstall/config.xml
  administrator/components/com_redirect/config.xml
  administrator/components/com_tags/config.xml
  administrator/components/com_templates/config.xml
  administrator/components/com_users/config.xml
Labels: RTC, PR-4.1-dev

#37964 [4.1] Fix TinyMCE height for multiple editor instances
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-4.1-dev

#37868 [4.1] Fix generate web cron key
  plugins/system/schedulerunner/schedulerunner.php
Labels: RTC, PR-4.1-dev

#37858 [4.1] Cassiopeia Terms of Service - Display Options Inline
  build/media_source/templates/site/cassiopeia/scss/blocks/_form.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37854 [4.1] Removed version="x" in xml
  administrator/manifests/packages/pkg_search.xml
  plugins/system/schedulerunner/schedulerunner.xml
  plugins/system/tasknotification/tasknotification.xml
  plugins/task/checkfiles/checkfiles.xml
  plugins/task/demotasks/demotasks.xml
  plugins/task/requests/requests.xml
  plugins/task/sitestatus/sitestatus.xml
Labels: RTC, PR-4.1-dev

#37917 [inlinehelp] enable toggle button for inlinehelp in Article edit
  administrator/components/com_content/forms/article.xml
  administrator/components/com_content/src/View/Article/HtmlView.php
Labels: RTC, PR-4.1-dev

#37948 Mail Templates cannot be set to not have mailer overrides
  administrator/components/com_mails/forms/template.xml
  libraries/src/Mail/MailTemplate.php
Labels: RTC, PR-4.1-dev

#37872 [4] Cassipopeia. Banner image and nonces. Move Inline Css to HEAD
  templates/cassiopeia/html/mod_custom/banner.php
Labels: RTC, PR-4.1-dev

#37830 Add a comment on the engine portion about upgrades
  package.json
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37617 [4.1] Update Sites rebuild
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.1-dev

#37990 [4.2] Fix fatal error when update to Joomla 4.2
  administrator/components/com_joomlaupdate/finalisation.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: RTC, Release Blocker, PR-4.2-dev

#37143 Single-load of tags in category models
  components/com_contact/src/Model/CategoryModel.php
  components/com_content/src/Model/ArticlesModel.php
  components/com_newsfeeds/src/Model/CategoryModel.php
  libraries/src/Helper/TagsHelper.php
Labels: RTC, PR-4.2-dev

#37979 [4.2] Update deleted files and folders for 4.2-beta1
  administrator/components/com_admin/script.php
Labels: PR-4.2-dev

#37954 [4.2] Change task plugin to service provider
  administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
  plugins/task/requests/requests.xml
  plugins/task/requests/services/provider.php
  plugins/task/requests/src/Extension/Requests.php
Labels: PR-4.2-dev

#38002 Improve Joomla! Update error state
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/tmpl/update/default.php
  administrator/language/en-GB/com_joomlaupdate.ini
  build/media_source/com_joomlaupdate/js/admin-update-default.es6.js
Labels: RTC, Language Change, NPM Resource Changed, PR-4.2-dev

#38016 Update the release checklist to include the Composer and NPM updates
  build/release-checklist.md
Labels: PR-4.2-dev

#38000 [4.2] Reintroduce workaround for arguments passed by reference
  libraries/src/HTML/HTMLHelper.php
Labels: PR-4.2-dev

#38006 [4.2] Replace Factory::getUser() with $this->getCurrentUser() in components view class
  administrator/components/com_admin/src/View/Sysinfo/HtmlView.php
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_banners/src/View/Banner/HtmlView.php
  administrator/components/com_banners/src/View/Client/HtmlView.php
  administrator/components/com_cache/src/View/Cache/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_config/src/View/Application/HtmlView.php
  administrator/components/com_config/src/View/Component/HtmlView.php
  administrator/components/com_contact/src/View/Contact/HtmlView.php
  administrator/components/com_content/src/View/Article/HtmlView.php
  administrator/components/com_fields/src/View/Field/HtmlView.php
  administrator/components/com_fields/src/View/Fields/HtmlView.php
  administrator/components/com_fields/src/View/Group/HtmlView.php
  administrator/components/com_fields/src/View/Groups/HtmlView.php
  administrator/components/com_finder/src/View/Filter/HtmlView.php
  administrator/components/com_installer/src/View/Install/HtmlView.php
  administrator/components/com_installer/src/View/Languages/HtmlView.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_languages/src/View/Overrides/HtmlView.php
  administrator/components/com_mails/src/View/Templates/HtmlView.php
  administrator/components/com_media/src/View/Media/HtmlView.php
  administrator/components/com_menus/src/View/Item/HtmlView.php
  administrator/components/com_menus/src/View/Items/HtmlView.php
  administrator/components/com_modules/src/View/Module/HtmlView.php
  administrator/components/com_modules/src/View/Modules/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  administrator/components/com_postinstall/src/View/Messages/HtmlView.php
  administrator/components/com_tags/src/View/Tag/HtmlView.php
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_users/src/View/Debuggroup/HtmlView.php
  administrator/components/com_users/src/View/Debuguser/HtmlView.php
  administrator/components/com_users/src/View/Note/HtmlView.php
  administrator/components/com_users/src/View/Users/HtmlView.php
  administrator/components/com_workflow/src/View/Stage/HtmlView.php
  administrator/components/com_workflow/src/View/Stages/HtmlView.php
  administrator/components/com_workflow/src/View/Transition/HtmlView.php
  administrator/components/com_workflow/src/View/Transitions/HtmlView.php
  administrator/components/com_workflow/src/View/Workflow/HtmlView.php
  components/com_config/src/View/Config/HtmlView.php
  components/com_config/src/View/Templates/HtmlView.php
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/src/View/Form/HtmlView.php
  components/com_content/src/View/Archive/HtmlView.php
  components/com_content/src/View/Article/HtmlView.php
  components/com_content/src/View/Featured/HtmlView.php
  components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  components/com_tags/src/View/Tag/HtmlView.php
  components/com_tags/src/View/Tags/HtmlView.php
  components/com_users/src/View/Login/HtmlView.php
  components/com_users/src/View/Profile/HtmlView.php
Labels: RTC, PR-4.2-dev

#37815 [3.10.9] Links from numeric tags cause error 404 #37814
  components/com_tags/models/tag.php
Labels: RTC, PR-3.10-dev

#37994 [4][webservice] user patch
  api/components/com_users/src/Controller/UsersController.php
Labels: RTC, PR-4.1-dev, Webservices

#38017 Add icon to parent category in article details
  layouts/joomla/content/info_block/parent_category.php
Labels: RTC, PR-4.1-dev

#37676 [4.1] webauthn rename/delete
  build/media_source/plg_system_webauthn/js/management.es6.js
  layouts/plugins/system/webauthn/manage.php
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37997 [4.x] Newsfeed pagination list
  components/com_newsfeeds/tmpl/category/default_items.php
Labels: RTC, PR-4.1-dev

#38005 [inlinehelp] Add inlinehelp toggle button for each component config
  administrator/components/com_banners/config.xml
  administrator/components/com_contact/config.xml
  administrator/components/com_finder/config.xml
  administrator/components/com_installer/config.xml
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_mails/config.xml
  administrator/components/com_media/config.xml
  administrator/components/com_modules/config.xml
  administrator/components/com_newsfeeds/config.xml
  administrator/components/com_privacy/config.xml
  administrator/components/com_redirect/config.xml
  administrator/components/com_scheduler/config.xml
  administrator/components/com_users/config.xml
Labels: RTC, PR-4.1-dev

#38014 [inlinehelp] Add inlinehelp toggle button for each component config [PART 2]
  administrator/components/com_actionlogs/config.xml
  administrator/components/com_menus/config.xml
  administrator/components/com_tags/config.xml
  administrator/components/com_templates/config.xml
Labels: RTC, PR-4.1-dev

#37915 [inlinehelp] Add inlineHelp Toggle Button control to modules and plugins
  administrator/components/com_modules/forms/module.xml
  administrator/components/com_modules/forms/moduleadmin.xml
  administrator/components/com_modules/src/View/Module/HtmlView.php
  administrator/components/com_plugins/forms/plugin.xml
  administrator/components/com_plugins/src/View/Plugin/HtmlView.php
  build/media_source/system/js/inlinehelp.es6.js
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37797 Fix DebugBar session issue, add DebugBar\JoomlaHttpDriver
  plugins/system/debug/debug.php
  plugins/system/debug/src/JoomlaHttpDriver.php
Labels: RTC, PR-4.1-dev

#37140 [4.1] All Categories
  components/com_content/tmpl/archive/default.xml
  components/com_content/tmpl/featured/default.xml
Labels: RTC, PR-4.1-dev

#36950 [3.10] Improve core update quickicon as well as none-supported update messages
  administrator/components/com_joomlaupdate/controllers/update.php
  administrator/components/com_joomlaupdate/models/default.php
  administrator/components/com_joomlaupdate/views/default/tmpl/default.php
  administrator/components/com_joomlaupdate/views/default/tmpl/default_preupdatecheck.php
  administrator/templates/hathor/html/com_joomlaupdate/default/default.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  media/plg_quickicon_joomlaupdate/js/jupdatecheck.js
  plugins/quickicon/joomlaupdate/joomlaupdate.php
Labels: PR-3.10-dev, PBF

#37517 [4.2] Inject the cache controller factory
  administrator/components/com_postinstall/src/Model/MessagesModel.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Cache/CacheControllerFactoryAwareInterface.php
  libraries/src/Cache/CacheControllerFactoryAwareTrait.php
  libraries/src/Document/Factory.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Extension/Service/Provider/MVCFactory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/Menu/MenuFactory.php
  libraries/src/Menu/SiteMenu.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Document.php
  libraries/src/Service/Provider/Menu.php
  tests/Unit/Libraries/Cms/Cache/CacheControllerFactoryAwareTraitTest.php
Labels: RTC, Unit/System Tests, PBF, PR-4.2-dev

#37928 [4.2] Change tags plugin to service provider
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/behaviour/taggable/services/provider.php
  plugins/behaviour/taggable/src/Extension/Taggable.php
  plugins/behaviour/taggable/taggable.xml
Labels: RTC, PR-4.2-dev

#37929 [4.2] Convert versionable plugin to services
  plugins/behaviour/versionable/services/provider.php
  plugins/behaviour/versionable/src/Extension/Versionable.php
  plugins/behaviour/versionable/versionable.php
  plugins/behaviour/versionable/versionable.xml
Labels: RTC, PR-4.2-dev

#37947 [4.2] Convert mod_articles_latest to new structure
  modules/mod_articles_latest/mod_articles_latest.php
  modules/mod_articles_latest/mod_articles_latest.xml
  modules/mod_articles_latest/services/provider.php
  modules/mod_articles_latest/src/Dispatcher/Dispatcher.php
  modules/mod_articles_latest/src/Helper/ArticlesLatestHelper.php
Labels: RTC, PR-4.2-dev

#38011 [4.2] Use the app identity in the FormController
  libraries/src/MVC/Controller/FormController.php
Labels: RTC, PR-4.2-dev

#38037 [4.1] Unified spelling of the word YubiKey
  administrator/language/en-GB/plg_twofactorauth_yubikey.ini
  administrator/language/en-GB/plg_twofactorauth_yubikey.sys.ini
Labels: Language Change, PR-4.1-dev

#38034 [4.2] Fix fatal error on users management
  administrator/components/com_users/src/Model/UsersModel.php
Labels: RTC, Release Blocker, PR-4.2-dev, Maintainers Checked

#38019 Enqueue requests made from QuickIcon plugins
  build/media_source/com_cpanel/js/admin-system-loader.es6.js
  build/media_source/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_source/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
  build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
  build/media_source/system/js/core.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38038 Merge branch '3.10-dev' of github.com:joomla/joomla-cms into 4.1-dev
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
  administrator/components/com_joomlaupdate/tmpl/upload/default.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  plugins/quickicon/joomlaupdate/src/Extension/Joomlaupdate.php
Labels: PR-4.1-dev

#38012 [4.2] Replace some static Factory calls with current app access
  libraries/src/MVC/Controller/FormController.php
Labels: RTC, PR-4.2-dev

#38025 [4.2] Replace $this->_db usages in components models
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_categories/src/Model/CategoriesModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_fields/src/Model/GroupModel.php
  administrator/components/com_finder/src/Model/MapsModel.php
  administrator/components/com_installer/src/Model/DiscoverModel.php
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_menus/src/Model/ItemsModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  administrator/components/com_modules/src/Model/PositionsModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_plugins/src/Model/PluginModel.php
  administrator/components/com_plugins/src/Model/PluginsModel.php
  administrator/components/com_tags/src/Model/TagsModel.php
  administrator/components/com_workflow/src/Model/StagesModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
  components/com_finder/src/Model/SearchModel.php
  components/com_tags/src/Model/TagModel.php
Labels: RTC, PR-4.2-dev

#37227 [4.1] skipto update
  build/build-modules-js/settings.json
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.1-dev, PR-4.2-dev

#38036 [4.2] unification YubiKey vs Yubikey
  administrator/language/en-GB/plg_multifactorauth_yubikey.ini
  administrator/language/en-GB/plg_multifactorauth_yubikey.sys.ini
Labels: RTC, Language Change, PR-4.2-dev

#38029 Fix MFA Authentication Code by Email plugin's Force Enable feature
  administrator/components/com_users/src/Dispatcher/Dispatcher.php
  administrator/components/com_users/src/View/Captive/HtmlView.php
  plugins/multifactorauth/email/src/Extension/Email.php
Labels: RTC, PR-4.2-dev

#38009 [4.2] accessibility plugin update and fixes
  administrator/language/en-GB/plg_system_accessibility.ini
  package-lock.json
  plugins/system/accessibility/accessibility.php
  plugins/system/accessibility/accessibility.xml
Labels: RTC, Language Change, NPM Resource Changed, PR-4.2-dev

#38050 Update Mfa.php s/dissappear/disappear
  administrator/components/com_users/src/Helper/Mfa.php
Labels: RTC, PR-4.2-dev

#38053 [4.2] spelling worflow/workflow
  libraries/src/Event/CoreEventAware.php
Labels: RTC, PR-4.2-dev

#38066 [4.2] mod login buttons
  modules/mod_login/tmpl/default.php
Labels: RTC, PR-4.2-dev

#37949 [4.1] Tinymce 5.10.5
  package-lock.json
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.2-dev

#38064 [4.2] Post-installation messages UX
  administrator/components/com_postinstall/src/Controller/MessageController.php
  administrator/components/com_postinstall/src/Model/MessagesModel.php
  administrator/components/com_postinstall/tmpl/messages/default.php
  administrator/language/en-GB/com_postinstall.ini
Labels: RTC, Language Change, PR-4.2-dev

#37701 [4.2] Mail Templates htmlbody
  administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-06-15.sql
  installation/sql/mysql/supports.sql
Labels: RTC, PR-4.2-dev, Maintainers Checked

#38079 [4.2] Namespace CacheControllerFactoryAwareTraitTest
  tests/Unit/Libraries/Cms/Cache/CacheControllerFactoryAwareTraitTest.php
Labels: Unit/System Tests, PR-4.2-dev

#38074 [4.2] pre-update check missing class
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/preupdatecheck.php
Labels: RTC, PR-4.2-dev

#38065 [4.2] user profile dob field
  administrator/language/en-GB/plg_user_profile.ini
  layouts/plugins/user/profile/fields/dob.php
  plugins/user/profile/forms/profile.xml
  plugins/user/profile/src/Field/DobField.php
Labels: RTC, Language Change, PR-4.2-dev

#38075 [4.2] update message
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-4.2-dev

#38071 [4.2] Backup confirm message
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-4.2-dev

#38080 [4.2] Fix missing language strings at installation
  installation/language/en-GB/joomla.ini
  installation/src/Model/LanguagesModel.php
Labels: RTC, PR-4.2-dev

#38085 [4.1] order header ini-file
  administrator/language/en-GB/com_workflow.ini
Labels: RTC, PR-4.1-dev

#37612 [4.2] Move the logic to fetch the languages to the model
  administrator/components/com_menus/src/Controller/DisplayController.php
  administrator/components/com_menus/src/Model/MenusModel.php
  administrator/components/com_modules/src/Controller/DisplayController.php
Labels: PBF, PR-4.2-dev

#38082 Add captive prompts for the rest of MFA methods
  administrator/components/com_users/src/Model/CaptiveModel.php
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/plg_multifactorauth_totp.ini
  administrator/language/en-GB/plg_multifactorauth_yubikey.ini
  components/com_users/tmpl/captive/default.php
  language/en-GB/com_users.ini
  plugins/multifactorauth/totp/src/Extension/Totp.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
Labels: RTC, Language Change, PR-4.2-dev

#38086 [4.1] remove spaces at EOL
  administrator/components/com_modules/forms/module.xml
  administrator/components/com_modules/forms/moduleadmin.xml
  administrator/components/com_plugins/forms/plugin.xml
  build/README.md
  plugins/twofactorauth/totp/tmpl/form.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Banner.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Content.php
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverCommandTest.php
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverInstallCommandTest.php
  tests/Unit/Libraries/Cms/Console/ExtensionDiscoverListCommandTest.php
  tests/Unit/Libraries/Cms/Form/Rule/FolderPathExistsRuleTest.php
Labels: RTC, PR-4.1-dev

#38084 [4.x] htaccess gzip info
  htaccess.txt
Labels: RTC, PR-4.1-dev

#37938 [4.x] Fix installation JS for failed folder delete
  installation/template/js/remove.js
Labels: RTC, PR-4.1-dev

#38042 Update alternate.xml
  administrator/components/com_menus/presets/alternate.xml
Labels: RTC, PR-4.1-dev, Maintainers Checked

#38069 Remove $false = false
  libraries/src/Form/Form.php
Labels: RTC, PR-4.1-dev

#38052 [4.1] spelling goup/group
  libraries/src/Form/Form.php
Labels: RTC, PR-4.1-dev

#38049 [4.1] invalid button type
  administrator/components/com_contenthistory/tmpl/history/modal.php
Labels: RTC, PR-4.1-dev

#38054 [4.1] spelling trough/through
  libraries/src/Cache/Cache.php
  libraries/src/Session/Session.php
Labels: RTC, PR-4.1-dev

#38056 [4.1] spelling preform/perform
  libraries/src/Table/Table.php
Labels: RTC, PR-4.1-dev

#38061 [4.1] spelling corrent/current
  build/media_source/com_media/js/edit-images.es6.js
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#38055 [4.1] spelling identifer/identifier
  libraries/src/Form/Rule/CssIdentifierSubstringRule.php
Labels: RTC, PR-4.1-dev

#38081 Fix deprecated warning in Text
  libraries/src/Language/Text.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#38083 Fix warnings for in admin sub-menu
  administrator/modules/mod_menu/tmpl/default_submenu.php
Labels: PR-4.1-dev, PHP 8.x

#37888 [4.1] Do not throw a warning when the image url is null on clean
  libraries/src/HTML/HTMLHelper.php
Labels: PR-4.1-dev, PHP 8.x

#38060 [4.2] Inject the application into the service provider plugins
  administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
  libraries/src/Plugin/CMSPlugin.php
  plugins/actionlog/joomla/services/provider.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/api-authentication/basic/services/provider.php
  plugins/api-authentication/basic/src/Extension/Basic.php
  plugins/api-authentication/token/services/provider.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/behaviour/versionable/services/provider.php
  plugins/behaviour/versionable/src/Extension/Versionable.php
  plugins/multifactorauth/email/services/provider.php
  plugins/multifactorauth/email/src/Extension/Email.php
  plugins/multifactorauth/fixed/src/Extension/Fixed.php
  plugins/multifactorauth/totp/services/provider.php
  plugins/multifactorauth/totp/src/Extension/Totp.php
  plugins/multifactorauth/webauthn/services/provider.php
  plugins/multifactorauth/webauthn/src/Extension/Webauthn.php
  plugins/multifactorauth/yubikey/services/provider.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/quickicon/joomlaupdate/services/provider.php
  plugins/quickicon/joomlaupdate/src/Extension/Joomlaupdate.php
  plugins/system/cache/services/provider.php
  plugins/system/cache/src/Extension/Cache.php
  plugins/task/requests/services/provider.php
  plugins/task/requests/src/Extension/Requests.php
  tests/Unit/Libraries/Cms/Plugin/CMSPluginTest.php
  tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
Labels: Unit/System Tests, PR-4.2-dev

#37611 [4.2] Inject the database into the finder classes
  administrator/components/com_finder/src/Extension/FinderComponent.php
  administrator/components/com_finder/src/Indexer/Adapter.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_finder/src/Service/HTML/Filter.php
  administrator/components/com_finder/src/Service/HTML/Finder.php
  components/com_finder/src/Model/SearchModel.php
  modules/mod_finder/src/Helper/FinderHelper.php
Labels: PBF, PR-4.2-dev

#37940 [4.2] Improve nonce and strict-dynamic handling within the http header plugin
  plugins/system/httpheaders/httpheaders.php
Labels: RTC, PR-4.2-dev

#38087 [4.2] mod_article_news dont allow creating new tags
  modules/mod_articles_news/mod_articles_news.xml
Labels: RTC, PR-4.2-dev

#37942 [4.2] Improve nonce generation and add the nonce to included files too as well as improve generation
  libraries/src/Document/Renderer/Html/ScriptsRenderer.php
  libraries/src/Document/Renderer/Html/StylesRenderer.php
  plugins/system/httpheaders/httpheaders.php
Labels: RTC, PR-4.2-dev

#37621 [4.2] Inject the database into categories
  libraries/src/Categories/Categories.php
  libraries/src/Categories/CategoryFactory.php
  libraries/src/Extension/Service/Provider/CategoryFactory.php
Labels: PR-4.2-dev

#37622 [4.2] Inject the database into console commands
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Console/AddUserCommand.php
  libraries/src/Console/AddUserToGroupCommand.php
  libraries/src/Console/DeleteUserCommand.php
  libraries/src/Console/ExtensionDiscoverCommand.php
  libraries/src/Console/ExtensionDiscoverInstallCommand.php
  libraries/src/Console/ExtensionRemoveCommand.php
  libraries/src/Console/ExtensionsListCommand.php
  libraries/src/Console/ListUserCommand.php
  libraries/src/Console/RemoveUserFromGroupCommand.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Console.php
Labels: PR-4.2-dev

#37614 [4.2] Move the logic to get the menu item language on login to the model
  components/com_users/src/Controller/UserController.php
  components/com_users/src/Model/LoginModel.php
Labels: PBF, PR-4.2-dev

#37615 [4.2] Does move some db related application code to the respective model
  administrator/components/com_messages/src/Model/MessagesModel.php
  administrator/components/com_templates/src/Model/StyleModel.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/SiteApplication.php
Labels: PBF, PR-4.2-dev

#38093 [4.2] code style unit test plugin
  tests/Unit/Libraries/Cms/Plugin/CMSPluginTest.php
  tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
Labels: Unit/System Tests, PR-4.2-dev

#37625 [4.2] Inject the database into the installer
  administrator/components/com_admin/script.php
  administrator/components/com_installer/src/Model/DiscoverModel.php
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
  installation/src/Application/InstallationApplication.php
  installation/src/Model/ConfigurationModel.php
  installation/src/Model/LanguagesModel.php
  libraries/src/Adapter/Adapter.php
  libraries/src/Console/ExtensionDiscoverInstallCommand.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerAdapter.php
Labels: PR-4.2-dev

#38091 [4.2][cli] cache:clean
  libraries/src/Console/CleanCacheCommand.php
Labels: RTC, PR-4.2-dev

#38099 [4.2] Post-installation messages UX #38064 code optimization
  administrator/components/com_postinstall/src/Controller/MessageController.php
  administrator/components/com_postinstall/src/Model/MessagesModel.php
Labels: RTC, PR-4.2-dev

#38101 [PHP8.1] Contact data deprecated errors
  administrator/components/com_contact/src/Table/ContactTable.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#38102 [PHP 8.1] Fix indexing newsfeeds with no summary
  administrator/components/com_finder/src/Indexer/Indexer.php
Labels: RTC, PR-4.2-dev

#37721 Make the Tags RouteHelper language aware
  components/com_tags/src/Helper/RouteHelper.php
  components/com_tags/tmpl/tags/default_items.php
  layouts/joomla/content/tags.php
  modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
  modules/mod_tags_popular/tmpl/cloud.php
  modules/mod_tags_popular/tmpl/default.php
  plugins/finder/tags/tags.php
Labels: PR-4.2-dev

#38089 [4.2] Banner Tracks Clear
  administrator/components/com_banners/forms/filter_tracks.xml
Labels: RTC, PR-4.2-dev

#38039 [4.2] Update deleted files and folders for 4.2.0-beta2
  administrator/components/com_admin/script.php
Labels: PR-4.2-dev

#38113 [4] install language - an error message when no xml is returned
  administrator/components/com_installer/src/Model/LanguagesModel.php
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.2-dev, Maintainers Checked

#38095 [4.2] Remove mocking XMLReader as it's bad practice. Fix parsing version
  libraries/src/Feed/Parser/AtomParser.php
  libraries/src/Feed/Parser/RssParser.php
  tests/Unit/Libraries/Cms/Feed/FeedFactoryTest.php
  tests/Unit/Libraries/Cms/Feed/FeedParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
Labels: Unit/System Tests, PR-4.2-dev, Maintainers Checked

#38133 Skip Session Manager tests on PHP 8.1 as old version of PHPUnit
  .drone.yml
  tests/Unit/Libraries/Cms/Session/SessionManagerTest.php
Labels: Unit/System Tests, PR-4.2-dev

#38138 [4.x] Fix TinyMCE ext-buttons options
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-4.2-dev

#38132 [4.2] Fix fatal error on webauthn plugin
  plugins/multifactorauth/webauthn/tmpl/default.php
Labels: RTC, PR-4.2-dev

#38098 [4.2] Move demo tasks to service provider
  plugins/task/demotasks/demotasks.xml
  plugins/task/demotasks/services/provider.php
  plugins/task/demotasks/src/Extension/DemoTasks.php
Labels: RTC, PR-4.2-dev

#38144 chore: Set permissions for GitHub actions
  .github/workflows/create-translation-pull-request-v4.yml
Labels: PR-4.2-dev

#38126 Media Manager Folder Selectory a11y
  administrator/components/com_media/resources/scripts/components/tree/drive.vue
  administrator/components/com_media/resources/scripts/components/tree/item.vue
  administrator/components/com_media/resources/scripts/components/tree/tree.vue
  administrator/components/com_media/resources/scripts/mediamanager.es6.js
Labels: RTC, a11y, NPM Resource Changed, PR-4.2-dev

#37681 PSR12 transformation preparation
  administrator/components/com_config/src/Controller/ComponentController.php
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_users/src/Model/UsersModel.php
  build/psr12/.editorconfig
  build/psr12/clean_errors.php
  build/psr12/convert_pull_requests.php
  build/psr12/phpcs.joomla.report.php
  build/psr12/psr12_converter.php
  build/psr12/ruleset.xml
  layouts/joomla/content/blog_style_default_item_title.php
  libraries/src/Form/Field/MenuField.php
  libraries/src/Form/Field/MenuitemField.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormRule.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/Utility/BufferStreamHandler.php
  plugins/authentication/ldap/ldap.php
Labels: PR-4.2-dev

#38159 copyright and licence
  plugins/multifactorauth/webauthn/src/Hotfix/AndroidKeyAttestationStatementSupport.php
  plugins/multifactorauth/webauthn/src/Hotfix/FidoU2FAttestationStatementSupport.php
  plugins/multifactorauth/webauthn/src/Hotfix/Server.php
Labels: PR-4.2-dev, psr12

#38157 [4.2] Add GitHub rebase script
  build/github_rebase.php
Labels: PR-4.2-dev, psr12

#38162 [4.2] Update and correct locked plugins
  administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-06-22.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.0-2022-06-22.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.2-dev, Maintainers Checked

#38158 Show location of cause of deprecation messages
  libraries/src/Exception/ExceptionHandler.php
Labels: RTC, PR-4.2-dev, psr12

#38167 Change PHP code style to PSR-12 for the build folder
  build/build.php
  build/bump.php
  build/deleted_file_check.php
  build/helpTOC.php
  build/psr12/phpcs.joomla.report.php
  build/psr12/psr12_converter.php
  build/stubGenerator.php
Labels: PR-4.2-dev

#38166 [4.2] remove ruleset.xml
  build/build.php
Labels: PR-4.2-dev

#38170 Improve psr12 script
  build/psr12/convert_pull_requests.php
  build/psr12/psr12_converter.php
Labels: PR-4.2-dev

#38171 [4.2] Cleanup some inline phpcs:ignore
  administrator/components/com_categories/src/Model/CategoriesModel.php
  administrator/components/com_users/postinstall/multifactorauth.php
  administrator/components/com_users/src/Controller/CaptiveController.php
  administrator/components/com_users/src/Controller/MethodController.php
  administrator/components/com_users/src/Controller/MethodsController.php
  administrator/components/com_users/src/DataShape/CaptiveRenderOptions.php
  administrator/components/com_users/src/DataShape/DataShapeObject.php
  administrator/components/com_users/src/DataShape/MethodDescriptor.php
  administrator/components/com_users/src/DataShape/SetupRenderOptions.php
  administrator/components/com_users/src/Model/UsersModel.php
  administrator/components/com_users/src/Table/MfaTable.php
  administrator/components/com_users/tmpl/captive/default.php
  administrator/components/com_users/tmpl/captive/select.php
  administrator/components/com_users/tmpl/method/backupcodes.php
  administrator/components/com_users/tmpl/method/edit.php
  administrator/components/com_users/tmpl/methods/default.php
  administrator/components/com_users/tmpl/methods/firsttime.php
  administrator/components/com_users/tmpl/methods/list.php
  administrator/components/com_users/tmpl/users/default.php
  build/media_source/com_scheduler/js/admin-view-select-task-search.es6.js
  components/com_users/tmpl/captive/default.php
  components/com_users/tmpl/captive/select.php
  components/com_users/tmpl/method/backupcodes.php
  components/com_users/tmpl/method/edit.php
  components/com_users/tmpl/methods/default.php
  components/com_users/tmpl/methods/firsttime.php
  components/com_users/tmpl/methods/list.php
  layouts/plugins/system/webauthn/manage.php
  libraries/src/Document/Renderer/Html/MetasRenderer.php
  plugins/multifactorauth/email/src/Extension/Email.php
  plugins/multifactorauth/fixed/src/Extension/Fixed.php
  plugins/multifactorauth/totp/src/Extension/Totp.php
  plugins/multifactorauth/webauthn/src/Extension/Webauthn.php
  plugins/multifactorauth/webauthn/tmpl/default.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/system/webauthn/src/CredentialRepository.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerLogin.php
Labels: NPM Resource Changed, PR-4.2-dev

#38186 Use tabs for non php files in editorconfig
  .editorconfig
Labels: PR-4.2-dev

#38154 [4.2] article status script
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  build/media_source/com_content/joomla.asset.json
  build/media_source/com_content/js/articles-status.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev, psr12

#38165 [4.2] Missing description for combination J+M
  administrator/language/en-GB/plg_system_shortcut.ini
  administrator/language/en-GB/plg_system_shortcut.sys.ini
Labels: RTC, Language Change, PR-4.2-dev

#38184 [4.2] filter order
  administrator/components/com_installer/forms/filter_manage.xml
Labels: RTC, PR-4.2-dev

#38191 [4.2] Code style for webauthn plugin
  plugins/system/webauthn/services/provider.php
Labels: RTC, PR-4.2-dev
