Repository joomla/joomla-cms, pull requests merged in 2022-07, with the labels that each got.

#38194 [4.2] Help Screen
  administrator/help/en-GB/toc.json
Labels: PR-4.2-dev

#38190 [4.2] Classname ImageFilterTests
  tests/Unit/Libraries/Cms/Image/Filter/FilterBackgroundfillTest.php
  tests/Unit/Libraries/Cms/Image/Filter/FilterBrightnessTest.php
  tests/Unit/Libraries/Cms/Image/Filter/FilterContrastTest.php
  tests/Unit/Libraries/Cms/Image/Filter/FilterEdgedetectTest.php
Labels: Unit/System Tests, PR-4.2-dev

#38203 [4.2] Use the app language translate function in plugins
  libraries/src/Plugin/CMSPlugin.php
  plugins/api-authentication/basic/src/Extension/Basic.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/task/requests/src/Extension/Requests.php
  plugins/task/sitestatus/src/Extension/SiteStatus.php
  tests/Unit/Libraries/Cms/Plugin/CMSPluginTest.php
Labels: Unit/System Tests, PR-4.2-dev

#38106 [4.2] Fallback in current user trait to Factory user
  libraries/src/User/CurrentUserTrait.php
Labels: PR-4.2-dev, psr12

#38072 [4.2] Convert the checkfiles plugin to service provider
  plugins/task/checkfiles/checkfiles.xml
  plugins/task/checkfiles/services/provider.php
  plugins/task/checkfiles/src/Extension/Checkfiles.php
  tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
Labels: Unit/System Tests, PR-4.2-dev, psr12

#37747 [4.2] Workflow Notification no recipient
  administrator/language/en-GB/plg_workflow_notification.ini
  plugins/workflow/notification/notification.php
Labels: RTC, Language Change, PR-4.2-dev, psr12

#38155 [4.2] Update deleted files and folders for 4.2.0-beta3
  administrator/components/com_admin/script.php
Labels: PR-4.2-dev, psr12

#38156 [4.2] codemirror update
  package-lock.json
  plugins/editors/codemirror/codemirror.xml
Labels: NPM Resource Changed, PR-4.2-dev, psr12

#38219 Small CS fix after PR #38155
  administrator/components/com_admin/script.php
Labels: PR-4.2-dev

#38218 [4.2] CLI tasks scripts cleanup
  libraries/src/Console/TasksListCommand.php
  libraries/src/Console/TasksRunCommand.php
  libraries/src/Console/TasksStateCommand.php
Labels: RTC, PR-4.2-dev

#38216 [4.2] CLI core scripts cleanup
  libraries/src/Console/UpdateCoreCommand.php
Labels: RTC, PR-4.2-dev

#38215 [4.2] CLI site scripts cleanup
  libraries/src/Console/SiteDownCommand.php
  libraries/src/Console/SiteUpCommand.php
Labels: RTC, PR-4.2-dev

#38212 [4.1] CLI extension scripts cleanup
  libraries/src/Console/ExtensionDiscoverCommand.php
  libraries/src/Console/ExtensionDiscoverListCommand.php
  libraries/src/Console/ExtensionInstallCommand.php
  libraries/src/Console/ExtensionRemoveCommand.php
  libraries/src/Console/ExtensionsListCommand.php
Labels: RTC, PR-4.2-dev

#38210 [4.2] CLI user scripts cleanup
  libraries/src/Console/AddUserCommand.php
  libraries/src/Console/AddUserToGroupCommand.php
  libraries/src/Console/ChangeUserPasswordCommand.php
  libraries/src/Console/DeleteUserCommand.php
  libraries/src/Console/ListUserCommand.php
  libraries/src/Console/RemoveUserFromGroupCommand.php
Labels: RTC, PR-4.2-dev

#38205 [4.2] CLI extensions enabled
  libraries/src/Console/ExtensionDiscoverListCommand.php
  libraries/src/Console/ExtensionsListCommand.php
Labels: RTC, PR-4.2-dev

#38152 [4][cli] update:extensions:check
  libraries/src/Console/CheckUpdatesCommand.php
Labels: RTC, PR-4.2-dev, psr12

#38220 [4][cli] extension:discover:install
  libraries/src/Console/ExtensionDiscoverInstallCommand.php
Labels: PR-4.2-dev

#37534 [4.2] Installation updateuserids
  installation/src/Model/ConfigurationModel.php
Labels: PR-4.2-dev, psr12

#38231 [4.2] Ruleset.xml
  ruleset.xml
Labels: PR-4.2-dev

#38232 [4.2] build badges
  README.md
Labels: PR-4.2-dev

#36749 [4.2] Smart Search: Prevent "#__finder_tokens full" error
  administrator/components/com_finder/config.xml
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/language/en-GB/com_finder.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, Language Change, PR-4.2-dev, psr12

#38236 [4.2] Page navigation focus ring
  plugins/content/pagenavigation/tmpl/default.php
Labels: RTC, PR-4.2-dev

#38172 Joomla.enqueueRequest and Request promise
  build/media_source/com_cpanel/js/admin-system-loader.es6.js
  build/media_source/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_source/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
  build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
  build/media_source/system/js/core.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.2-dev

#38228 [4.2] Fixing labels for Smart Search menu item
  administrator/language/en-GB/com_finder.ini
  components/com_finder/tmpl/search/default.xml
Labels: RTC, Language Change, PR-4.2-dev

#38256 ci: add GitHub token permissions for workflow
  .github/workflows/cacert-update.yml
Labels: PR-4.2-dev

#38227 [4.2] Empty error message in package install
  administrator/language/en-GB/plg_installer_packageinstaller.ini
  build/media_source/plg_installer_packageinstaller/js/packageinstaller.es6.js
Labels: RTC, Language Change, NPM Resource Changed, PR-4.2-dev

#38255 Remove label from a hidden field
  administrator/components/com_categories/forms/category.xml
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#38268 [4] com_content. featured. Remove unused $leadingcount
  components/com_content/tmpl/featured/default.php
Labels: RTC, PR-4.2-dev

#38263 [4] com_content. blog. Remove unused $leadingcount, $introcount, $counter
  components/com_content/tmpl/category/blog.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#38244 [4.2] Menu item custom field
  administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-07-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.0-2022-07-07.sql
  administrator/language/en-GB/plg_fields_menuitem.ini
  administrator/language/en-GB/plg_fields_menuitem.sys.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/fields/menuitem/menuitem.php
  plugins/fields/menuitem/menuitem.xml
  plugins/fields/menuitem/tmpl/menuitem.php
Labels: RTC, Language Change, PR-4.2-dev

#38269 DatabaseInterface missing namespace causing JCategories call to fail
  libraries/src/Categories/Categories.php
Labels: PR-4.2-dev

#38275 [4.2] ExtensionManagerTrait.php. Comments cosmetic.
  libraries/src/Extension/ExtensionManagerTrait.php
Labels: RTC, PR-4.2-dev

#38271 [4.2] add noopener noreferrer in plg_system_webauthn.ini
  administrator/language/en-GB/plg_system_webauthn.ini
Labels: RTC, Language Change, PR-4.2-dev

#38287 [4.2] remove spaces in COM_USERS_MFA_INVALID_CODE
  administrator/language/en-GB/com_users.ini
  language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.2-dev

#38311 Fix wrong extra version from last version reset
  administrator/manifests/files/joomla.xml
  libraries/src/Version.php
Labels: PR-4.2-dev

#38317 [3.10] Workaround the a bit off monthsUntilEOS calculation
  plugins/quickicon/eos310/eos310.php
Labels: RTC, PR-3.10-dev

#38332 [5.0] Enabling packaging for 5.0-dev in drone
  .drone.yml
Labels: Unit/System Tests, PR-5.0-dev

#38331 [4.3] Enabling packaging for 4.3-dev in drone
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#38320 [4.2] Webauth Authenticator Table
  layouts/plugins/system/webauthn/manage.php
Labels: RTC, PR-4.2-dev

#38319 [4.2] MFA backup codes list view
  administrator/components/com_users/tmpl/methods/list.php
  components/com_users/tmpl/methods/list.php
Labels: RTC, PR-4.2-dev

#38309 Remove filename from mod_quickicon manifest
  administrator/modules/mod_quickicon/mod_quickicon.xml
Labels: RTC, PR-4.2-dev, Maintainers Checked

#38304 [4.2] fix yubico.com link
  administrator/language/en-GB/plg_multifactorauth_yubikey.ini
  administrator/language/en-GB/plg_multifactorauth_yubikey.sys.ini
  administrator/language/en-GB/plg_twofactorauth_yubikey.ini
  administrator/language/en-GB/plg_twofactorauth_yubikey.sys.ini
Labels: RTC, Language Change, PR-4.2-dev

#38300 [4.2] Fix Deprecated warnings on login
  components/com_users/tmpl/login/default_login.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#38292 [4][com_templates] deprecated php 8.1
  administrator/components/com_templates/src/View/Template/HtmlView.php
Labels: RTC, PHP 8.x, PR-4.2-dev, Maintainers Checked

#38285 [4.2] mod_breadcrumbs. Fix several issues with ld+json structured data
  modules/mod_breadcrumbs/mod_breadcrumbs.php
  modules/mod_breadcrumbs/src/Helper/BreadcrumbsHelper.php
  modules/mod_breadcrumbs/tmpl/default.php
Labels: RTC, PR-4.2-dev

#38273 Fix error (stdClass|array) to string conversion in article version history
  administrator/components/com_contenthistory/tmpl/preview/preview.php
Labels: RTC, PR-4.2-dev

#38341 Do not show the webauthn form on the registration page
  administrator/language/en-GB/plg_system_webauthn.ini
  plugins/system/webauthn/services/provider.php
  plugins/system/webauthn/src/PluginTraits/UserProfileFields.php
Labels: RTC, Language Change, Release Blocker, PR-4.2-dev
