Repository joomla/joomla-cms, pull requests merged in 2022-09, with the labels that each got.

#38613 [4.2] javascript cs warning
  build/media_source/com_content/js/articles-status.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev, Maintainers Checked

#38632 [4.2] fix shortcut Home Dashboard
  administrator/language/en-GB/joomla.ini
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: Language Change, PR-4.2-dev

#38535 [4.2] Do not set a width of 0 in media thumbnails
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38664 Fix/38233 webauth preload fido
  .gitignore
  administrator/components/com_admin/script.php
  administrator/language/en-GB/plg_system_webauthn.ini
  build/build.php
  build/update_fido_cache.php
  composer.json
  plugins/system/webauthn/services/provider.php
  plugins/system/webauthn/src/Extension/Webauthn.php
  plugins/system/webauthn/src/MetadataRepository.php
  plugins/system/webauthn/webauthn.xml
Labels: RTC, Language Change, Composer Dependency Changed, Release Blocker, PR-4.2-dev

#38670 Update plg_multifactorauth_fixed.ini
  administrator/language/en-GB/plg_multifactorauth_fixed.ini
Labels: RTC, Language Change, PR-4.2-dev

#38614 [4.3] Fix Tinymce and Codemirror version
  package-lock.json
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#38679 Upmerge 2022 09 03
  .gitignore
  administrator/components/com_admin/script.php
  administrator/components/com_admin/src/View/Sysinfo/HtmlView.php
  administrator/components/com_languages/src/View/Overrides/HtmlView.php
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_templates/src/Helper/TemplateHelper.php
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/components/com_users/forms/group.xml
  administrator/components/com_users/tmpl/method/edit.php
  administrator/language/en-GB/com_cpanel.ini
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/com_media.ini
  administrator/language/en-GB/com_templates.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/plg_editors-xtd_readmore.ini
  administrator/language/en-GB/plg_editors-xtd_readmore.sys.ini
  administrator/language/en-GB/plg_installer_override.ini
  administrator/language/en-GB/plg_installer_packageinstaller.ini
  administrator/language/en-GB/plg_installer_webinstaller.ini
  administrator/language/en-GB/plg_multifactorauth_fixed.ini
  administrator/language/en-GB/plg_multifactorauth_webauthn.ini
  administrator/language/en-GB/plg_multifactorauth_webauthn.sys.ini
  administrator/language/en-GB/plg_quickicon_extensionupdate.ini
  administrator/language/en-GB/plg_quickicon_joomlaupdate.ini
  administrator/language/en-GB/plg_quickicon_overridecheck.ini
  administrator/language/en-GB/plg_quickicon_privacycheck.ini
  administrator/language/en-GB/plg_sampledata_blog.ini
  administrator/language/en-GB/plg_system_webauthn.ini
  administrator/language/en-GB/plg_user_profile.ini
  administrator/modules/mod_user/mod_user.xml
  api/language/en-GB/joomla.ini
  build/build.php
  build/media_source/com_content/js/articles-status.es6.js
  build/update_fido_cache.php
  components/com_finder/src/View/Search/OpensearchView.php
  components/com_users/tmpl/method/edit.php
  composer.json
  installation/language/en-GB/joomla.ini
  installation/tmpl/remove/default.php
  language/en-GB/com_content.ini
  language/en-GB/finder_cli.ini
  language/en-GB/joomla.ini
  language/en-GB/mod_articles_category.ini
  language/en-GB/mod_articles_news.ini
  language/en-GB/mod_finder.ini
  plugins/installer/override/override.php
  plugins/sampledata/blog/blog.php
  plugins/system/shortcut/src/Extension/Shortcut.php
  plugins/system/webauthn/services/provider.php
  plugins/system/webauthn/src/Extension/Webauthn.php
  plugins/system/webauthn/src/MetadataRepository.php
  plugins/system/webauthn/webauthn.xml
  plugins/user/profile/profile.php
  tests/Unit/bootstrap.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#38511 [4.3] Fix issue Deprecated: trim(): Passing null on PHP 8.1
  libraries/src/Filesystem/Path.php
Labels: RTC, Information Required, PHP 8.x, Maintainers Checked, PR-4.3-dev

#38607 Contact form captcha
  components/com_contact/tmpl/contact/default_form.php
Labels: RTC, PR-4.2-dev

#38644 [4.2] Actions Dropdown
  layouts/joomla/toolbar/dropdown.php
Labels: RTC, PR-4.2-dev

#38399 Codestyle indent
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_users/tmpl/users/default.php
  components/com_contact/tmpl/contact/default_address.php
  layouts/joomla/content/info_block.php
  modules/mod_articles_categories/tmpl/default_items.php
Labels: RTC, PR-4.2-dev

#38340 Fix PHP notices in CLI coming from the WebAuthn plugin
  plugins/system/webauthn/src/PluginTraits/UserProfileFields.php
Labels: RTC, Updates Requested, PR-4.2-dev

#38352 Language override RTL
  build/media_source/com_languages/css/overrider.css
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38351 com_finder rtl
  build/media_source/com_finder/css/finder.css
Labels: RTC, PR-4.2-dev

#38358 plg_system_webauthn RTL css
  build/media_source/plg_system_webauthn/scss/button.scss
Labels: RTC, PR-4.2-dev

#38349 Install from web - rtl fix
  build/media_source/plg_installer_webinstaller/scss/client.scss
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38350 com_finder unused css
  build/media_source/com_finder/css/dates.css
Labels: RTC, PR-4.2-dev

#38363 media manager select all
  build/media_source/com_media/scss/components/_media-toolbar.scss
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38365 centered search box - rtl
  administrator/components/com_modules/tmpl/select/default.php
  administrator/components/com_scheduler/tmpl/select/default.php
Labels: RTC, PR-4.2-dev

#38425 Use the right mime type in the the media field
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev, Maintainers Checked

#38362 media edit plugins legend
  build/media_source/com_media/scss/components/_media-edit.scss
Labels: RTC, PR-4.2-dev

#38465 Supported font formats mismatch
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.2-dev, Maintainers Checked

#38701 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: PR-4.2-dev

#38435 Missing help buttons
  administrator/components/com_media/config.xml
  administrator/components/com_scheduler/config.xml
Labels: RTC, PR-4.2-dev

#38591 Field Groups options
  administrator/components/com_fields/tmpl/group/edit.php
Labels: RTC, PR-4.2-dev

#38578 Child templates languages
  libraries/src/Document/HtmlDocument.php
Labels: RTC, PR-4.2-dev

#38569 fix typo ($tuple not $tupel)
  administrator/components/com_fields/src/Model/FieldModel.php
Labels: RTC, PR-4.2-dev

#38434 Change bulk unarchive action for redirect links to unpublish
  administrator/components/com_redirect/src/View/Links/HtmlView.php
Labels: RTC, PR-4.2-dev

#38609 [4.2] Removing 3.10-dev from renovate.json
  renovate.json
Labels: PR-4.2-dev

#38698 Use 4.2-dev in core translation workflow
  .editorconfig
  .github/workflows/create-translation-pull-request-v4.yml
Labels: PR-4.2-dev

#38463 com_templates override toggles
  administrator/components/com_templates/forms/source.xml
  administrator/language/en-GB/com_templates.ini
Labels: RTC, PR-4.2-dev

#38612 Pagination Only child
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  plugins/content/pagenavigation/tmpl/default.php
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38669 Duplicated code
  administrator/components/com_menus/tmpl/item/edit.php
Labels: RTC, PR-4.2-dev

#38620 Tag Entry Mode description
  administrator/components/com_tags/config.xml
Labels: RTC, PR-4.2-dev

#38507 [4.2] Column Width
  build/media_source/system/js/table-columns.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38581 Fix DataFormatter::formatCallerInfo to handle Closure
  plugins/system/debug/src/DataFormatter.php
Labels: RTC, PR-4.2-dev

#38562 Missing am/pm in calendar
  build/media_source/system/js/fields/calendar.es5.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38367 [4.2] Fix indents in installation
  installation/tmpl/remove/default.php
  installation/tmpl/setup/default.php
Labels: RTC, PR-4.2-dev

#38368 Keep user.css last in order
  administrator/templates/atum/joomla.asset.json
  templates/cassiopeia/joomla.asset.json
Labels: RTC, PR-4.2-dev

#38371 [4.2] [Smart Search] Moved statistics in the toolbar
  administrator/components/com_finder/src/View/Filters/HtmlView.php
  administrator/components/com_finder/src/View/Index/HtmlView.php
  administrator/components/com_finder/src/View/Maps/HtmlView.php
Labels: RTC, PR-4.2-dev

#38582 Fix to prevent double modification of the module content by chrome style
  libraries/src/Helper/ModuleHelper.php
Labels: RTC, PR-4.2-dev

#38627 Language override both
  administrator/components/com_languages/tmpl/override/edit.php
Labels: RTC, PR-4.2-dev

#38617 Text area and edit field defaults
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.2-dev

#38611 Fix position name in component dashboard
  administrator/components/com_cpanel/src/Controller/DisplayController.php
Labels: RTC, PR-4.2-dev

#38703 Joomla update message style
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-4.2-dev

#38712 [4.3] Switching Codeception error output to cypress output folder
  codeception.yml
Labels: Unit/System Tests, PR-4.3-dev

#38208 [4.2] Small fixes in MFA
  administrator/components/com_users/config.xml
  administrator/components/com_users/src/Model/BackupcodesModel.php
  administrator/components/com_users/src/View/Captive/HtmlView.php
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/plg_multifactorauth_email.ini
Labels: RTC, Language Change, PR-4.2-dev

#38704 Update string
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-4.2-dev

#38576 tag alias
  administrator/components/com_tags/src/Table/TagTable.php
  administrator/language/en-GB/com_tags.ini
  libraries/src/Table/ContentType.php
Labels: RTC, Language Change, PR-4.3-dev

#38540 Admin Menu filter by parent
  administrator/components/com_menus/forms/filter_itemsadmin.xml
  administrator/components/com_menus/src/Field/MenuItemByTypeField.php
Labels: RTC, PR-4.3-dev

#38728 Fix for cp cannot create regular file: File exists
  tests/Codeception/drone-system-run.sh
Labels: Unit/System Tests, PR-4.2-dev

#38736 [4.3] Cypress: change name of install spec
  tests/cypress/integration/00-install/00-install.cy.js
Labels: Unit/System Tests, PR-4.3-dev

#38735 [4.2] php cs
  libraries/src/Console/AddUserCommand.php
Labels: RTC, PR-4.2-dev

#38734 Note on the User Registration menu item
  administrator/language/en-GB/com_users.sys.ini
Labels: RTC, Language Change, PR-4.3-dev

#38738 Fix package doc block tag in site module PHP files
  modules/mod_articles_latest/services/provider.php
  modules/mod_articles_news/services/provider.php
Labels: RTC, PR-4.2-dev

#38732 File Name strings
  administrator/language/en-GB/com_mails.ini
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.2-dev

#38757 mod_submenu throws a fatal error if you use quicktask-permission in presets
  administrator/modules/mod_submenu/tmpl/default.php
Labels: PR-4.2-dev

#38726 jsSafe doc block explanation
  libraries/src/Language/Language.php
  libraries/src/Language/Text.php
Labels: RTC, PR-4.2-dev

#38762 Fixed PHP8.1 deprecation warning "passing null to parameter"
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
Labels: RTC, PR-4.2-dev

#38593 Add ldap tests
  .appveyor.yml
  .drone.yml
  tests/Codeception/_data/certs/CA.crt
  tests/Codeception/_data/certs/openldap.crt
  tests/Codeception/_data/certs/openldap.key
  tests/Unit/Plugin/Authentication/Ldap/LdapPluginTest.php
Labels: Unit/System Tests, PR-4.3-dev

#38772 spelling s/sharable/shareable
  administrator/language/en-GB/com_media.ini
  language/en-GB/com_media.ini
Labels: RTC, Language Change, PR-4.2-dev

#38596 Batch process on users
  administrator/components/com_users/src/Model/UserModel.php
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.2-dev

#38723 Table Columns js
  build/media_source/system/js/table-columns.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38629 [4.2] Initialize the installer script variable correctly
  libraries/src/Installer/InstallerAdapter.php
Labels: RTC, PR-4.2-dev

#38372 [4] missing changelog when discover a plugin/module/template
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
Labels: RTC, PR-4.2-dev

#38714 Remove overrides when a template is uninstalled
  administrator/components/com_admin/sql/updates/mysql/4.2.3-2022-09-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.3-2022-09-07.sql
  libraries/src/Installer/Adapter/TemplateAdapter.php
Labels: RTC, PR-4.2-dev

#38778 Updating 4.3-dev with changes from 4.2-dev
  .github/workflows/create-translation-pull-request-v4.yml
  administrator/components/com_admin/sql/updates/mysql/4.2.3-2022-09-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.3-2022-09-07.sql
  administrator/components/com_users/src/Model/UserModel.php
  administrator/language/en-GB/com_mails.ini
  administrator/language/en-GB/com_media.ini
  administrator/language/en-GB/com_scheduler.ini
  administrator/language/en-GB/com_users.ini
  administrator/modules/mod_submenu/tmpl/default.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  build/media_source/system/js/table-columns.es6.js
  installation/language/af-ZA/joomla.ini
  installation/language/cs-CZ/joomla.ini
  installation/language/es-ES/joomla.ini
  installation/language/hu-HU/joomla.ini
  installation/language/it-IT/joomla.ini
  installation/language/th-TH/joomla.ini
  installation/language/vi-VN/joomla.ini
  installation/language/vi-VN/langmetadata.xml
  language/en-GB/com_media.ini
  libraries/src/Console/AddUserCommand.php
  libraries/src/Helper/MediaHelper.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/InstallerAdapter.php
  libraries/src/Language/Language.php
  libraries/src/Language/Text.php
  modules/mod_articles_latest/services/provider.php
  modules/mod_articles_news/services/provider.php
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
  tests/Codeception/drone-system-run.sh
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#38267 [4.3] Quickicons
  administrator/components/com_banners/src/Controller/BannersController.php
  administrator/components/com_contact/src/Controller/ContactsController.php
  administrator/components/com_content/src/Controller/FeaturedController.php
  administrator/components/com_languages/src/Controller/LanguagesController.php
  administrator/components/com_newsfeeds/src/Controller/NewsfeedsController.php
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_languages.ini
  administrator/language/en-GB/com_newsfeeds.ini
  administrator/language/en-GB/com_tags.ini
  administrator/language/en-GB/mod_quickicon.ini
  administrator/modules/mod_quickicon/mod_quickicon.xml
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: RTC, Language Change, Maintainers Checked, PR-4.3-dev

#38353 removed unused css
  administrator/components/com_admin/script.php
  administrator/components/com_menus/tmpl/item/edit_modules.php
  build/media_source/com_menus/css/admin-item-edit_modules.css
  build/media_source/com_menus/joomla.asset.json
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#38563 Unable to select Url type menu item as Base item in mod_menu
  administrator/components/com_menus/tmpl/items/modal.php
Labels: RTC, PR-4.3-dev

#37633 [5.0] Upgrade TinyMCE to version 6
  build/build-modules-js/init/exemptions/tinymce.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  package-lock.json
  package.json
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
  plugins/editors/tinymce/src/PluginTraits/KnownButtons.php
  plugins/editors/tinymce/src/PluginTraits/ToolbarPresets.php
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-5.0-dev

#38789 [4.2] Renovatebot: force npm and composer versions
  renovate.json
Labels: PR-4.2-dev

#38803 [4.2] npm: fix bootstrap to version 5.1.3
  package.json
Labels: NPM Resource Changed, PR-4.2-dev

#38412 Bootstrap RTL the correct way
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/media_source/templates/administrator/atum/scss/blocks/_header.scss
  build/media_source/templates/administrator/atum/scss/blocks/_sidebar-nav.scss
  build/media_source/templates/administrator/atum/scss/blocks/_sidebar.scss
  build/media_source/templates/administrator/atum/scss/blocks/_toolbar.scss
  build/media_source/templates/administrator/atum/scss/template-rtl.scss
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_bootstrap-rtl.scss
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_custom-forms.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_frontend-edit.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_toolbar.scss
  build/media_source/templates/site/cassiopeia/scss/template-rtl.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_bootstrap-rtl.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/metismenu/_metismenu.scss
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.3-dev

#35678 [4.0] Implement char counter for input field, too
  build/build-modules-js/init/patches.es6.js
  layouts/joomla/form/field/text.php
  libraries/src/Form/Field/TextField.php
Labels: PR-4.3-dev, psr12

#38819 [4.2] Renovatebot: Changing asset updates to npm run update
  renovate.json
Labels: PR-4.2-dev

#38834 [4.2] Renovate: Adding npm ci
  renovate.json
Labels: PR-4.2-dev

#38842 [4.2] Spelling s/successfull/successful
  tests/Unit/Libraries/Cms/MVC/Model/FormModelTest.php
Labels: Unit/System Tests, PR-4.2-dev

#38848 PHP8 fix Debug plugin setMediaVersion use String
  plugins/system/debug/debug.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#38858 [4.3] Project dependency updates
  composer.lock
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: Composer Dependency Changed, NPM Resource Changed, PR-4.3-dev

#38829 [4.2] extra space in class
  administrator/components/com_users/tmpl/debuguser/default.php
Labels: RTC, PR-4.2-dev

#38853 Fix Dashboards for third party components
  administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php
Labels: RTC, PR-4.2-dev

#38843 [4.2] s/wil/will
  administrator/components/com_users/src/Model/UserModel.php
Labels: RTC, PR-4.2-dev

#38825 [4,2] remove JDEFAULT override for com_menus
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/language/en-GB/com_menus.ini
Labels: RTC, Language Change, PR-4.2-dev

#38626 Language Override space
  administrator/components/com_languages/tmpl/overrides/default.php
Labels: RTC, PR-4.2-dev
