Repository joomla/joomla-cms, pull requests merged in 2022-02, with the labels that each got.

#36905 [4.1] Upmerge from 3.10
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  layouts/joomla/html/image.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Controller/FormController.php
  modules/mod_banners/mod_banners.php
  modules/mod_wrapper/mod_wrapper.php
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: PR-4.1-dev

#36591 [4.1] User defined Hide Table Columns
  administrator/components/com_actionlogs/tmpl/actionlogs/default.php
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_banners/tmpl/tracks/default.php
  administrator/components/com_cache/tmpl/cache/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_finder/tmpl/filters/default.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/maps/default.php
  administrator/components/com_installer/tmpl/database/default.php
  administrator/components/com_installer/tmpl/languages/default.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_languages/tmpl/installed/default.php
  administrator/components/com_languages/tmpl/languages/default.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/components/com_mails/tmpl/templates/default.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_plugins/tmpl/plugins/default.php
  administrator/components/com_privacy/tmpl/consents/default.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_scheduler/tmpl/tasks/default.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_templates/tmpl/styles/default.php
  administrator/components/com_templates/tmpl/templates/default.php
  administrator/components/com_users/tmpl/groups/default.php
  administrator/components/com_users/tmpl/levels/default.php
  administrator/components/com_users/tmpl/notes/default.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/components/com_workflow/tmpl/stages/default.php
  administrator/components/com_workflow/tmpl/transitions/default.php
  administrator/components/com_workflow/tmpl/workflows/default.php
  administrator/language/en-GB/joomla.ini
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/multiselect.es6.js
  build/media_source/system/js/table-columns.es6.js
  libraries/src/WebAsset/AssetItem/TableColumnsAssetItem.php
Labels: RTC, PR-4.2-dev

#36876 [4.2] - Adds ordering parameters to web service requests.
  api/components/com_content/src/Controller/ArticlesController.php
Labels: RTC, PR-4.2-dev

#34203 Removed attribute addpathfield as Model_Contact field type is not use…
  components/com_contact/models/forms/filter_contacts.xml
Labels: PR-3.10-dev

#36886 [3.10] Make the headers check before the update download proxy aware by passing it via HttpFactory
  administrator/components/com_joomlaupdate/models/default.php
Labels: PR-3.10-dev

#36878 Add OPcache support to restore.php
  administrator/components/com_joomlaupdate/restore.php
Labels: PR-3.10-dev

#36927 [4.1] Fix Create/edit Procedure For Cron-based Scheduled Tasks
  administrator/components/com_scheduler/src/Field/CronField.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
Labels: RTC, PR-4.1-dev

#36971 [4.1][bug] TinyMCE language bug
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, Release Blocker, PR-4.1-dev

#36970 [4.1] storage of the e-mail address in com_privacy
  components/com_privacy/src/Model/RequestModel.php
Labels: RTC, PR-4.1-dev

#36972 [4.1] [release blocker] The http head call returns a different structure than in J3
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: RTC

#37003 Part 2 of #36878
  administrator/components/com_joomlaupdate/restore.php
Labels: PR-3.10-dev

#37010 [4.1] [Scheduler] [BugFix] WebCron failing when no scheduled tasks are defined, with "message":"A key is required" and Fatal error "Table '#_users' was not locked with LOCK TABLES"
  administrator/components/com_scheduler/src/Model/TaskModel.php
Labels: RTC, PR-4.1-dev

#36932 [4.2] Consider permissions for MM actions
  administrator/components/com_media/resources/scripts/app/Api.es6.js
  administrator/components/com_media/resources/scripts/components/browser/actionItems/actionItemsContainer.vue
  administrator/components/com_media/resources/scripts/components/browser/items/document.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/modals/rename-modal.vue
  administrator/components/com_media/resources/scripts/store/actions.es6.js
  administrator/components/com_media/tmpl/media/default.php
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#37037 [4.1] Add @HLeithner to the codeowners and remove none existent files
  .github/CODEOWNERS
Labels: PR-4.1-dev

#37036 Fix tasks never running when using the PDO MySQL driver
  administrator/components/com_scheduler/src/Model/TaskModel.php
Labels: PR-4.1-dev

#37039 Fix wrong type for ID in CLI scheduler run
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_scheduler/src/Scheduler/Scheduler.php
Labels: PR-4.1-dev

#36997 [3.x] Admin registration emails
  components/com_users/models/registration.php
Labels: RTC, PR-3.10-dev

#36986 [3.10] E-Mail Cloak: part of the TLD will not be truncated
  plugins/content/emailcloak/emailcloak.php
Labels: RTC, PR-3.10-dev

#36969 [3.10] Fix typo within two language strings uninstall -> uninstalled
  administrator/language/en-GB/en-GB.lib_joomla.ini
  language/en-GB/en-GB.lib_joomla.ini
Labels: RTC, PR-3.10-dev

#36953 [3.10] Update contributing.md file to be merged up to 4.1 and 4.2
  .github/CONTRIBUTING.md
Labels: RTC, PR-3.10-dev

#36951 [3.10] Fix redirect updating new_url value
  plugins/system/redirect/redirect.php
Labels: RTC, PR-3.10-dev

#36861 [3.10] Remove FLoC
  administrator/components/com_admin/sql/updates/mysql/3.10.6-2022-01-26.sql
  administrator/components/com_admin/sql/updates/postgresql/3.10.6-2022-01-26.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.10.6-2022-01-26.sql
  administrator/components/com_config/model/form/application.xml
  administrator/language/en-GB/en-GB.com_admin.ini
  administrator/language/en-GB/en-GB.com_config.ini
  htaccess.txt
  installation/sql/mysql/joomla.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/sqlazure/joomla.sql
  libraries/src/Application/CMSApplication.php
Labels: RTC, Language Change, PR-3.10-dev

#36813 Removed unnecessary left join and distinct
  libraries/src/Form/Field/TagField.php
Labels: RTC, PR-3.10-dev

#37092 [4.1] Jooa11y updates
  administrator/language/en-GB/plg_system_jooa11y.ini
  build/build-modules-js/settings.json
  build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
  build/media_source/plg_system_jooa11y/scss/jooa11y.scss
  package-lock.json
  package.json
  plugins/system/jooa11y/jooa11y.php
  plugins/system/jooa11y/jooa11y.xml
Labels: Language Change, NPM Resource Changed, PR-4.1-dev

#35693 [4.1] Log in to read messages
  administrator/language/en-GB/com_messages.ini
Labels: RTC, Language Change, PR-4.1-dev

#37104 [4.1] 3.10 => 4.1 Upmerges
  .github/CONTRIBUTING.md
  administrator/components/com_admin/sql/updates/mysql/4.1.1-2022-02-20.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.1-2022-02-20.sql
  administrator/components/com_config/forms/application.xml
  administrator/language/en-GB/com_admin.ini
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/lib_joomla.ini
  components/com_users/src/Model/RegistrationModel.php
  htaccess.txt
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
  language/en-GB/lib_joomla.ini
  libraries/src/Form/Field/TagField.php
  plugins/content/emailcloak/emailcloak.php
  plugins/system/httpheaders/httpheaders.php
  plugins/system/redirect/redirect.php
Labels: Language Change, PR-4.1-dev

#36863 [4.1] Finder: Translate taxonomy titles in search results
  components/com_finder/tmpl/search/default_result.php
Labels: RTC, PR-4.1-dev

#37084 [4.1] Fix: "Undefined variable $id"
  layouts/joomla/form/renderfield.php
Labels: RTC, PR-4.1-dev

#37049 [4.1 Update com_installer.ini
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.1-dev

#37033 [4.1] Lazy Scheduler disabled
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#37021 Update README.md instruction to use https for github cloning instead of ssh
  README.md
Labels: RTC, PR-4.1-dev

#36937 [4.1] empty state duplicated variables
  layouts/joomla/content/emptystate.php
Labels: RTC, PR-4.1-dev

#37081 [4.1] Fileinfo check
  administrator/components/com_admin/src/Model/SysinfoModel.php
  administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php
Labels: RTC, PR-4.1-dev

#37082 [4.1] Remove title attribute
  administrator/components/com_languages/src/Service/HTML/Languages.php
Labels: RTC, PR-4.1-dev

#36714 [4.1] Scheduled Tasks Help
  administrator/components/com_scheduler/src/View/Select/HtmlView.php
  administrator/components/com_scheduler/src/View/Task/HtmlView.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/language/en-GB/com_admin.ini
Labels: RTC, Language Change, PR-4.1-dev

#36279 [4.1] Rename render to display
  administrator/components/com_fields/forms/field.xml
  administrator/language/en-GB/com_fields.ini
Labels: RTC, Language Change, PR-4.1-dev

#37023 [4.1] `Maintainence` should be `Maintenance`
  build/release-checklist.md
Labels: RTC, PR-4.1-dev

#37014 [4.1] add rel=\"noopener noreferrer\" for target=\"blank\" links
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/plg_captcha_recaptcha.ini
  administrator/language/en-GB/plg_captcha_recaptcha.sys.ini
  administrator/language/en-GB/plg_captcha_recaptcha_invisible.ini
  administrator/language/en-GB/plg_captcha_recaptcha_invisible.sys.ini
  administrator/language/en-GB/plg_twofactorauth_totp.ini
  administrator/language/en-GB/plg_twofactorauth_totp.sys.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.1-dev

#37005 [4.1] - fix All Menu Items Check In
  administrator/components/com_menus/src/View/Items/HtmlView.php
Labels: RTC, PR-4.1-dev

#37007 [4.1] [PHP 8.1] Fix Deprecated notice: strtolower(): Passing null to string in components/com_ajax/ajax.php on line 39
  components/com_ajax/ajax.php
Labels: RTC, PR-4.1-dev, PHP 8

#36929 [4.1] MediaRSS link
  libraries/src/Feed/Parser/Rss/MediaRssParser.php
Labels: RTC, PR-4.1-dev

#36877 [4.1] Finder auto-suggestions broken
  components/com_finder/tmpl/search/default_form.php
  modules/mod_finder/tmpl/default.php
Labels: RTC, PR-4.1-dev

#36865 [J4.1] Better "Your Modules" Article
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: RTC, Language Change, PR-4.1-dev

#37038 [4.1] updated language filenames to non-prefixed names
  administrator/modules/mod_multilangstatus/mod_multilangstatus.xml
  administrator/modules/mod_version/mod_version.xml
  modules/mod_finder/mod_finder.xml
  plugins/filesystem/local/local.xml
  plugins/finder/categories/categories.xml
  plugins/finder/contacts/contacts.xml
  plugins/finder/content/content.xml
  plugins/finder/newsfeeds/newsfeeds.xml
  plugins/finder/tags/tags.xml
  plugins/system/highlight/highlight.xml
  plugins/system/languagecode/languagecode.xml
  plugins/webservices/banners/banners.xml
  plugins/webservices/config/config.xml
  plugins/webservices/contact/contact.xml
  plugins/webservices/content/content.xml
  plugins/webservices/languages/languages.xml
  plugins/webservices/media/media.xml
  plugins/webservices/menus/menus.xml
  plugins/webservices/messages/messages.xml
  plugins/webservices/modules/modules.xml
  plugins/webservices/newsfeeds/newsfeeds.xml
  plugins/webservices/plugins/plugins.xml
  plugins/webservices/privacy/privacy.xml
  plugins/webservices/redirect/redirect.xml
  plugins/webservices/tags/tags.xml
  plugins/webservices/templates/templates.xml
  plugins/webservices/users/users.xml
Labels: RTC, PR-4.1-dev

#37008 [4.1][bugfix] Use the one true way to render images: with jLayout
  plugins/fields/media/tmpl/media.php
Labels: RTC, PR-4.1-dev

#36949 [4.1] Remove tab
  layouts/joomla/form/field/user.php
Labels: RTC, PR-4.1-dev

#36879 [4.1] Fix the SCSS file paths
  build/build-modules-js/init/recreate-media.es6.js
  build/media_source/templates/administrator/atum/scss/vendor/awesomplete/awesomplete.scss
  build/media_source/templates/administrator/atum/scss/vendor/choicesjs/choices.scss
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
  build/media_source/templates/administrator/atum/scss/vendor/minicolors/minicolors.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36998 [4.1] Changed blog modifiers on Cassiopeia
  build/media_source/templates/site/cassiopeia/scss/blocks/_modifiers.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37119 [4.1] English error
  administrator/language/en-GB/joomla.ini
Labels: Language Change, PR-4.1-dev

#37022 [4.1] Use the image JLayout for all the images
  components/com_content/src/View/Category/FeedView.php
  components/com_content/src/View/Featured/FeedView.php
  components/com_content/tmpl/categories/default_items.php
  components/com_finder/tmpl/search/default_result.php
  components/com_tags/tmpl/tag/default.php
  components/com_tags/tmpl/tag/default_items.php
  components/com_tags/tmpl/tag/list.php
  components/com_tags/tmpl/tags/default.php
  components/com_tags/tmpl/tags/default_items.php
  components/com_users/tmpl/login/default_login.php
  components/com_users/tmpl/login/default_logout.php
  modules/mod_feed/tmpl/default.php
Labels: RTC, PR-4.1-dev

#37154 [4.1] Fix wrong sequence next values in PostgreSQL installation SQL scripts
  installation/sql/postgresql/extensions.sql
Labels: RTC, PR-4.1-dev

#36948 [4.1] Use emojis vs google fonts for the accessibility plugin
  plugins/system/accessibility/accessibility.php
Labels: RTC, PR-4.1-dev
