Repository joomla/joomla-cms, pull requests merged in 2022-03, with the labels that each got.

#37130 [4.1] Codemirror search
  build/build-modules-js/init/exemptions/codemirror.es6.js
Labels: RTC, PR-4.1-dev

#37164 [4.1] com_users login div
  components/com_users/tmpl/login/default_login.php
Labels: RTC, PR-4.1-dev

#37160 [4.1] Fix the update version fix of the database fix for 3rd party extensions
  administrator/components/com_installer/src/Model/DatabaseModel.php
Labels: RTC, PR-4.1-dev

#37158 Integrate inline help toggle button to com_config component Options view (see #35610)
  administrator/components/com_config/src/View/Component/HtmlView.php
  administrator/components/com_content/config.xml
Labels: RTC, PR-4.1-dev

#37129 [4.1] Codemirror Full Screen
  administrator/language/en-GB/plg_editors_codemirror.ini
  build/media_source/templates/administrator/atum/scss/vendor/_codemirror.scss
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
Labels: RTC, Language Change, NPM Resource Changed, PR-4.1-dev

#36946 [4.1] template previews need size restrictions
  build/media_source/templates/administrator/atum/scss/pages/_com_templates.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36748 [4.1] Smart Search: Fix missing taxonomy language string
  administrator/components/com_finder/src/Helper/LanguageHelper.php
Labels: RTC, PR-4.1-dev

#35703 [4.0] MenuHelper::getList() doesn't cache menu items
  modules/mod_menu/src/Helper/MenuHelper.php
Labels: RTC, PR-4.1-dev

#35763 [4.0] Fix custom fields on Contact Form
  components/com_contact/src/Model/ContactModel.php
  components/com_contact/src/View/Contact/HtmlView.php
Labels: RTC, PR-4.1-dev

#35323 [4] Remove all references to LDAP ignore_reqcert_tls
  administrator/language/en-GB/plg_authentication_ldap.ini
  plugins/authentication/ldap/ldap.xml
Labels: RTC, Language Change, PR-4.1-dev

#37198 [4.1] remove db prefix from action logs
  plugins/actionlog/joomla/joomla.php
Labels: RTC, PR-4.1-dev

#37202 [4.1] remove unused rtl css
  build/media_source/templates/site/cassiopeia/scss/blocks/_toolbar.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37166 [4] contact search error
  components/com_contact/src/Model/CategoryModel.php
Labels: RTC, PR-4.1-dev

#37213 [4] use correct object to get message from
  administrator/components/com_finder/src/Field/ContenttypesField.php
  administrator/components/com_finder/src/Service/HTML/Finder.php
  administrator/components/com_newsfeeds/src/Field/NewsfeedsField.php
Labels: RTC, PR-4.1-dev

#37214 [4] remove unused imports
  administrator/components/com_media/src/Provider/ProviderManagerHelperTrait.php
  components/com_privacy/src/Model/ConfirmModel.php
  components/com_privacy/src/Model/RequestModel.php
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  plugins/editors/tinymce/src/PluginTraits/ResolveFiles.php
Labels: RTC, PR-4.1-dev

#37196 [4.1] jooa11y plugin options
  administrator/language/en-GB/plg_system_jooa11y.ini
  plugins/system/jooa11y/jooa11y.php
Labels: RTC, Language Change, PR-4.1-dev

#37206 [4.1] Fix wrong checked out values for update sites table
  administrator/components/com_installer/src/Table/UpdatesiteTable.php
Labels: RTC, PR-4.1-dev

#37138 [4.1] Empty radio / checkbox / list fields
  plugins/fields/checkboxes/params/checkboxes.xml
  plugins/fields/list/params/list.xml
  plugins/fields/radio/params/radio.xml
Labels: RTC, PR-4.1-dev

#37135 [4.1] fields in users dashboard
  administrator/modules/mod_submenu/src/Menu/Menu.php
Labels: RTC, PR-4.1-dev

#37096 Fix changed behavior of getAuthorisedViewLevels
  libraries/src/Access/Access.php
Labels: RTC, Release Blocker, PR-4.1-dev, bug, RLDQ

#36947 [4.1] remove underline on buttons etc
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_table.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37178 [4.2] Remove PHP 5.3 compatibility code in HTMLHelper
  libraries/src/HTML/HTMLHelper.php
Labels: RTC, PR-4.2-dev

#37224 [4.1] scheduler sorting
  administrator/components/com_scheduler/forms/filter_tasks.xml
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_scheduler/tmpl/tasks/default.php
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#36860 [4.2] Enable/disable 'Upload&Install' button on the basis of checkbox value
  administrator/components/com_joomlaupdate/tmpl/upload/default.php
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#37237 [4.1] Apply badge markup
  administrator/components/com_mails/tmpl/template/edit.php
Labels: RTC, PR-4.1-dev

#37133 [4.1] Private Messages Emails
  administrator/language/en-GB/com_messages.ini
Labels: RTC, Language Change, PR-4.1-dev

#37149 [4]send email on new user via webservice
  plugins/user/joomla/joomla.php
Labels: RTC, PR-4.1-dev, Webservices

#36786 [4.1] Fix usage of unset parent ID mapping when getting recursive access rules
  libraries/src/Access/Access.php
Labels: RTC, PR-4.1-dev

#37248 [4.1][bug] Retain hidden info when saving as a style
  administrator/components/com_templates/forms/style.xml
  administrator/components/com_templates/tmpl/style/edit.php
Labels: RTC, PR-4.1-dev

#35597 [4.1] Undefined property notice in image layout (Re-do of #29513)
  layouts/joomla/content/full_image.php
Labels: RTC, PR-4.1-dev

#37238 [4.1] Remove Bootstrap tooltip
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, PR-4.1-dev

#36516 [4.1] Misc improvements for Task\TaskOption
  administrator/components/com_scheduler/src/Field/TaskTypeField.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_scheduler/src/Task/TaskOption.php
  administrator/components/com_scheduler/src/Task/TaskOptions.php
  administrator/components/com_scheduler/src/Traits/TaskPluginTrait.php
  administrator/components/com_scheduler/tmpl/select/default.php
Labels: RTC, Updates Requested, PR-4.1-dev

#37203 [4.1] WebAuthn hints
  administrator/language/en-GB/plg_system_webauthn.ini
Labels: RTC, Language Change, PR-4.1-dev

#37256 [4.1] Fix missing template thumbnails
  administrator/components/com_templates/src/Service/HTML/Templates.php
Labels: RTC, PR-4.1-dev

#37087 [4.1] Set a header limit for server timing
  plugins/system/debug/debug.php
Labels: RTC, Release Blocker, PR-4.1-dev

#35967 [4.1] finder show_search_form
  components/com_finder/tmpl/search/default.php
Labels: RTC, PR-4.1-dev

#36875 [4.1] com_scheduler checked out tasks
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_scheduler/src/Table/TaskTable.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_scheduler/tmpl/tasks/default.php
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-4.1-dev

#37139 Better module cache
  libraries/src/Cache/Cache.php
  libraries/src/Cache/Controller/CallbackController.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/WebAsset/WebAssetManager.php
Labels: RTC, Release Blocker, PR-4.1-dev

#37279 [4.1] Composer update maximebf/debugbar to fix PHP 8.1 deprecations of the debug bar
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-4.1-dev

#37283 [4.1] Jooa11y string
  plugins/system/jooa11y/jooa11y.php
Labels: RTC, PR-4.1-dev

#37292 [4.1] Fix RTL installation
  installation/template/index.php
Labels: RTC, PR-4.1-dev

#24651 Fix timestamp format for track_date (banner)
  components/com_banners/models/banner.php
  components/com_banners/models/banners.php
Labels: RTC, PR-3.10-dev

#37181 [3.10] Privacy Consent wording I agree and No
  administrator/language/en-GB/en-GB.plg_user_terms.ini
  plugins/user/terms/terms/terms.xml
Labels: RTC, Language Change, PR-3.10-dev

#37255 [4.1] Remove the math.div deprecation
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  build/build-modules-js/init/patches.es6.js
  build/build.js
  build/media_source/com_media/scss/components/_layout.scss
  build/media_source/com_media/scss/components/_media-infobar.scss
  build/media_source/com_media/scss/components/_media-tree.scss
  build/media_source/system/scss/fields/switcher.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_back-to-top.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_layout.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_modifiers.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/_chosen.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/metismenu/_metismenu.scss
  package-lock.json
  package.json
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37298 [4.1] TinyMCE wrong name for the highlight Plus plugin
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-4.1-dev

#36765 [4.1] Add Visual Indicator for Failing Scheduled Tasks
  administrator/components/com_scheduler/tmpl/tasks/default.php
  administrator/language/en-GB/com_scheduler.ini
  build/media_source/com_scheduler/css/admin-view-tasks.css
  build/media_source/com_scheduler/joomla.asset.json
Labels: RTC, Language Change, NPM Resource Changed, PR-4.1-dev

#37276 # Fix maximum media modal width
  build/media_source/com_media/scss/components/_media-modal.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36888 [3.10] Disable google fonts for 3.10.x new installs
  administrator/components/com_admin/sql/updates/mysql/3.0.0.sql
  installation/sql/mysql/joomla.sql
  installation/sql/mysql/sample_brochure.sql
  installation/sql/mysql/sample_learn.sql
  installation/sql/postgresql/joomla.sql
  installation/sql/postgresql/sample_brochure.sql
  installation/sql/postgresql/sample_learn.sql
  installation/sql/sqlazure/joomla.sql
  installation/sql/sqlazure/sample_brochure.sql
  installation/sql/sqlazure/sample_learn.sql
  templates/protostar/templateDetails.xml
  tests/unit/stubs/database/jos_extensions.csv
  tests/unit/stubs/database/jos_template_styles.csv
  tests/unit/suites/libraries/cms/schema/stubs/mysql/3.0.0.sql
Labels: Unit/System Tests, PR-3.10-dev

#37282 [4.1] Fix for incorrect path name breadcrumbs
  modules/mod_breadcrumbs/tmpl/default.php
Labels: RTC, PR-4.1-dev

#37303 UI improvement fix the position of logo-collapsed in the sidbar
  build/media_source/templates/administrator/atum/scss/blocks/_header.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37116 [4.1] Module "Articles - Categories" - Make the category selection optional
  modules/mod_articles_categories/mod_articles_categories.xml
Labels: RTC, PR-4.1-dev

#37134 [4.1] Private messages reply
  administrator/components/com_messages/src/View/Message/HtmlView.php
  administrator/components/com_messages/src/View/Messages/HtmlView.php
  administrator/components/com_messages/tmpl/messages/emptystate.php
  administrator/modules/mod_menu/src/Menu/CssMenu.php
Labels: RTC, PR-4.1-dev

#37268 [4.1] cpanel add module permissions
  administrator/components/com_cpanel/tmpl/cpanel/default.php
Labels: RTC, PR-4.1-dev

#37075 [4.1.1][regression] TinyMCE language misbehaving
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.1-dev

#37307 [4.1] Admin User accessibility settings
  administrator/components/com_users/forms/user.xml
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.1-dev

#37308 Backport JQuery UI security patch for CVE-2021-41184
  media/jui/js/jquery.ui.core.js
  media/jui/js/jquery.ui.core.min.js
Labels: PR-3.10-dev

#37260 [4.1] Cassiopeia filter buttons
  build/media_source/templates/site/cassiopeia/scss/blocks/_modals.scss
  build/media_source/templates/site/cassiopeia/scss/system/searchtools/searchtools.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37236 [4.1] Space at bottom of sidebar for non logged user.
  administrator/templates/atum/login.php
Labels: RTC, PR-4.1-dev

#37259 [4.1] cassiopeia btn-group
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#36977 [4.1] TinyMCE Update 5.10.3
  package-lock.json
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-4.1-dev

#37287 [4.1] Update deleted files and folders for 4.1.1
  administrator/components/com_admin/script.php
Labels: Release Blocker, PR-4.1-dev

#37272 Remove wrong implementation of display: box and line-clamp
  build/media_source/templates/administrator/atum/scss/pages/_com_modules.scss
Labels: RTC, NPM Resource Changed, PR-4.1-dev

#37310 [4.1] Lazy Stylesheet comment
  templates/cassiopeia/index.php
Labels: RTC, PR-4.1-dev

#37311 Upmerge 3.10 to 4.1.1
  administrator/language/en-GB/plg_user_terms.ini
  components/com_banners/src/Model/BannerModel.php
  components/com_banners/src/Model/BannersModel.php
  plugins/user/terms/forms/terms.xml
Labels: Language Change, PR-4.1-dev

#37323 [4.1] alpha sorting in all 3 joomla.ini
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: Language Change, PR-4.1-dev

#37314 [4.1] Scheduler DocBlock since
  administrator/components/com_scheduler/src/Controller/TasksController.php
  administrator/components/com_scheduler/src/Table/TaskTable.php
  administrator/components/com_scheduler/src/Task/Task.php
  administrator/components/com_scheduler/src/View/Task/HtmlView.php
  plugins/task/demotasks/demotasks.php
Labels: RTC, PR-4.1-dev

#37334 language-update-de
  installation/language/de-AT/de-AT.ini
  installation/language/de-AT/de-AT.xml
  installation/language/de-CH/de-CH.ini
  installation/language/de-CH/de-CH.xml
  installation/language/de-DE/de-DE.ini
  installation/language/de-DE/de-DE.xml
  installation/language/de-LI/de-LI.ini
  installation/language/de-LI/de-LI.xml
  installation/language/de-LU/de-LU.ini
  installation/language/de-LU/de-LU.xml
Labels: Language Change, PR-3.10-dev

#37344 Update create-translation-pull-request-v4.yml
  .github/workflows/create-translation-pull-request-v4.yml
Labels: PR-4.1-dev

#36506 Improved Installer code for SQL updates
  libraries/src/Installer/Installer.php
Labels: RTC, PR-4.2-dev

#36688 [4.2] Deprecate getting the router by the app and introduce a service
  components/com_finder/src/View/Search/HtmlView.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/ApiApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CMSWebApplicationInterface.php
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Extension/Service/Provider/MVCFactory.php
  libraries/src/Factory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/Router/Route.php
  libraries/src/Router/Router.php
  libraries/src/Router/SiteRouterAwareInterface.php
  libraries/src/Router/SiteRouterAwareTrait.php
  libraries/src/Service/Provider/Router.php
  plugins/system/cache/cache.php
  plugins/system/languagefilter/languagefilter.php
Labels: RTC, PR-4.2-dev

#37091 [4.2] Extension installer script enhancements
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerAdapter.php
  libraries/src/Installer/InstallerScriptInterface.php
  libraries/src/Installer/LegacyInstallerScript.php
Labels: RTC, PR-4.2-dev

#37156 [4.2] Make update SQL scripts resilient to multiple executions so broken updates can be fixed
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-03-05.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-08-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-30.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-05-20.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-09-13.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-05-29.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-12-20.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-04-22.sql
  administrator/components/com_admin/sql/updates/mysql/4.0.0-2021-05-30.sql
  administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-11-20.sql
  administrator/components/com_admin/sql/updates/mysql/4.1.0-2022-01-24.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-03-05.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-05-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-19.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2018-07-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-09.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-03-30.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-05-20.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-09-13.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-03-25.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-05-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2020-12-20.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-04-22.sql
  administrator/components/com_admin/sql/updates/postgresql/4.0.0-2021-05-30.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.0-2021-11-20.sql
  administrator/components/com_admin/sql/updates/postgresql/4.1.0-2022-01-24.sql
Labels: RTC, PR-4.2-dev

#37363 [4.1] tab code style
  layouts/joomla/form/field/media.php
Labels: RTC, PR-4.1-dev

#36846 [4.1] [PHP 8.1] Compatibility of htmlentities() types in tinymce DisplayTrait
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37319 [4.1] Check if var to escape is null
  libraries/src/MVC/View/HtmlView.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37324 [4.1] Check if string is null in hasKey function
  libraries/src/Language/Language.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37349 [4.1] Fix some null errors in contact list
  components/com_contact/tmpl/category/default_items.php
  libraries/src/MVC/View/CategoryView.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37340 [4.1] Fix warning on HTMLHelper::_('select.integerlist')
  libraries/src/HTML/Helpers/Select.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37336 [4.1] Json decode can't handle null in login view
  components/com_users/tmpl/login/default_login.php
  components/com_users/tmpl/login/default_logout.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37331 [4.1] Check if model has a value for direction
  libraries/src/MVC/Model/ListModel.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37342 [4.1] Fix Deprecated warning on plugin page
  administrator/components/com_plugins/src/View/Plugin/HtmlView.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37347 [4.1] Do not pass null to base64 decode in front form models
  components/com_contact/src/Model/FormModel.php
  components/com_content/src/Model/FormModel.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37328 [4.1] Check if value is not null in menu item
  administrator/components/com_menus/src/Field/MenutypeField.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37325 [4.1] Check if links are not null in menu item
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: RTC, PR-4.1-dev, PHP 8.x

#37374 [4.2] Handle extensions when the installer script doesn't return a boolean
  libraries/src/Installer/InstallerAdapter.php
  libraries/src/Installer/LegacyInstallerScript.php
Labels: RTC, Release Blocker, PR-4.2-dev

#37379 [4.2] Remove duplicate WebAssetManager
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_scheduler/tmpl/tasks/default.php
Labels: RTC, PR-4.2-dev

#37362 Add ability to save an article from the frontend without being redirected (#37312)
  components/com_content/src/Controller/ArticleController.php
  components/com_content/tmpl/form/edit.php
  language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#37382 Fix wrong update SQL file names
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/postgresql/3.10.7-2022-02-20.sql
  administrator/components/com_admin/sql/updates/sqlazure/3.10.7-2022-02-20.sql
Labels: Release Blocker, PR-3.10-dev

#37383 [4.1] Adapt deleted files list in script.php to PR 37382
  administrator/components/com_admin/script.php
Labels: Release Blocker, PR-4.1-dev

#37385 [4.1] Upmerges 2022-03-27
  installation/language/pl-PL/joomla.ini
Labels: Language Change, PR-4.1-dev

#37381 [4.2] Add alias for old router class names in container
  libraries/src/Service/Provider/Router.php
Labels: PR-4.2-dev

#37393 [4.1] Add text COM_WORKFLOW_STAGE_FORM_NEW to com_workflow.ini
  administrator/language/en-GB/com_workflow.ini
Labels: RTC, Language Change, Release Blocker, a11y, PR-4.1-dev

#37402 [4.1] s\preset\present
  administrator/components/com_admin/script.php
Labels: RTC, PR-4.1-dev

#37403 [4.1] s\PK's\PKs
  libraries/src/MVC/Controller/AdminController.php
Labels: PR-4.1-dev

#37406 [4.1] Language string
  administrator/language/en-GB/com_users.ini
Labels: Language Change, PR-4.1-dev

#37410 [4.1] xml codestyle
  administrator/components/com_users/forms/user.xml
Labels: PR-4.1-dev

#37415 [4.1] Disable auth binding code introduced with 4.1.1
  administrator/components/com_admin/script.php
  administrator/components/com_users/forms/user.xml
  administrator/components/com_users/src/Field/PrimaryauthprovidersField.php
  administrator/components/com_users/src/Model/UserModel.php
  administrator/language/en-GB/com_users.ini
  components/com_users/src/Model/ProfileModel.php
  libraries/src/Authentication/Authentication.php
  libraries/src/Authentication/ProviderAwareAuthenticationPluginInterface.php
  libraries/src/Table/User.php
  libraries/src/User/User.php
  plugins/authentication/cookie/cookie.php
  plugins/authentication/joomla/joomla.php
  plugins/authentication/ldap/ldap.php
  plugins/user/joomla/joomla.php
Labels: Language Change, PR-4.1-dev

#37416 [3.10] Disable auth binding code introduced with 3.10.7
  administrator/components/com_admin/script.php
  administrator/components/com_users/models/fields/primaryauthproviders.php
  administrator/components/com_users/models/forms/user.xml
  administrator/components/com_users/models/user.php
  administrator/language/en-GB/en-GB.com_users.ini
  components/com_users/models/profile.php
  libraries/src/Authentication/Authentication.php
  libraries/src/Authentication/ProviderAwareAuthenticationPluginInterface.php
  libraries/src/Table/User.php
  libraries/src/User/User.php
  plugins/authentication/cookie/cookie.php
  plugins/authentication/gmail/gmail.php
  plugins/authentication/joomla/joomla.php
  plugins/authentication/ldap/ldap.php
  plugins/user/joomla/joomla.php
Labels: Language Change, PR-3.10-dev

#37394 [4.1] Add label for notification tab in workflow transition form
  plugins/workflow/notification/forms/action.xml
Labels: RTC, PR-4.1-dev

#37391 [4.x] codestyle xml
  administrator/components/com_menus/forms/itemadmin_url.xml
Labels: RTC, PR-4.1-dev

#37384 PHP 8.1: Fixes Deprecated: null to string in MailTemplate.php
  libraries/src/Mail/MailTemplate.php
Labels: RTC, PR-4.1-dev, PHP 8.x
