Repository joomla/joomla-cms, pull requests merged in 2022-10, with the labels that each got.

#38883 Updating 4.3-dev with changes from 4.2-dev
  administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php
  administrator/components/com_languages/tmpl/overrides/default.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_users/src/Model/UserModel.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/language/en-GB/com_menus.ini
  build/github_rebase.php
  build/psr12/psr12_converter.php
  installation/language/af-ZA/joomla.ini
  installation/language/af-ZA/langmetadata.xml
  installation/language/bg-BG/joomla.ini
  installation/language/cy-GB/joomla.ini
  installation/language/pt-BR/joomla.ini
  installation/language/vi-VN/joomla.ini
  installation/language/zh-TW/joomla.ini
  plugins/system/debug/debug.php
  renovate.json
  tests/Unit/Libraries/Cms/MVC/Model/FormModelTest.php
Labels: Unit/System Tests, Test instructions missing, Language Change, PR-4.3-dev

#38888 [4.2] Update PR template (motion PROD2022/012)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR-4.2-dev

#38896 [4][com_finder] undefined variable $f_id
  administrator/components/com_finder/src/Controller/DisplayController.php
Labels: RTC, PR-4.2-dev

#38729 Make "Default" layout really as default
  modules/mod_menu/mod_menu.xml
Labels: RTC, PR-4.2-dev

#38863 [4.2] codemirror full screen
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
Labels: RTC, PR-4.2-dev

#38867 [4.2] Missing Folder message
  administrator/language/en-GB/com_media.ini
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: RTC, Language Change, PR-4.2-dev

#38906 JS error in com_scheduler with empty task list
  build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38916 Updating 4.3-dev with changes from 4.2-dev
  .github/PULL_REQUEST_TEMPLATE.md
  administrator/components/com_finder/src/Controller/DisplayController.php
  administrator/language/en-GB/com_media.ini
  build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
  installation/language/af-ZA/langmetadata.xml
  installation/language/ar-AA/langmetadata.xml
  installation/language/bg-BG/langmetadata.xml
  installation/language/ca-ES/langmetadata.xml
  installation/language/cs-CZ/langmetadata.xml
  installation/language/cy-GB/langmetadata.xml
  installation/language/da-DK/langmetadata.xml
  installation/language/el-GR/langmetadata.xml
  installation/language/en-AU/langmetadata.xml
  installation/language/en-CA/langmetadata.xml
  installation/language/en-NZ/langmetadata.xml
  installation/language/en-US/langmetadata.xml
  installation/language/es-ES/langmetadata.xml
  installation/language/et-EE/langmetadata.xml
  installation/language/eu-ES/langmetadata.xml
  installation/language/fa-AF/langmetadata.xml
  installation/language/fa-IR/langmetadata.xml
  installation/language/fi-FI/langmetadata.xml
  installation/language/fr-FR/langmetadata.xml
  installation/language/he-IL/langmetadata.xml
  installation/language/hu-HU/langmetadata.xml
  installation/language/it-IT/langmetadata.xml
  installation/language/ja-JP/langmetadata.xml
  installation/language/ka-GE/langmetadata.xml
  installation/language/kk-KZ/langmetadata.xml
  installation/language/lt-LT/langmetadata.xml
  installation/language/lv-LV/langmetadata.xml
  installation/language/nl-BE/langmetadata.xml
  installation/language/nl-NL/langmetadata.xml
  installation/language/pl-PL/langmetadata.xml
  installation/language/pt-BR/langmetadata.xml
  installation/language/pt-PT/langmetadata.xml
  installation/language/ro-RO/langmetadata.xml
  installation/language/sk-SK/langmetadata.xml
  installation/language/sl-SI/langmetadata.xml
  installation/language/sr-YU/langmetadata.xml
  installation/language/sv-SE/langmetadata.xml
  installation/language/ta-IN/langmetadata.xml
  installation/language/th-TH/langmetadata.xml
  installation/language/tr-TR/langmetadata.xml
  installation/language/uk-UA/langmetadata.xml
  installation/language/vi-VN/langmetadata.xml
  installation/language/zh-CN/langmetadata.xml
  installation/language/zh-TW/langmetadata.xml
  modules/mod_menu/mod_menu.xml
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#38920 Updating 4.3-dev with changes from 4.2-dev
  .github/PULL_REQUEST_TEMPLATE.md
  administrator/components/com_finder/src/Controller/DisplayController.php
  administrator/language/en-GB/com_media.ini
  build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
  installation/language/af-ZA/langmetadata.xml
  installation/language/ar-AA/langmetadata.xml
  installation/language/bg-BG/langmetadata.xml
  installation/language/ca-ES/langmetadata.xml
  installation/language/cs-CZ/langmetadata.xml
  installation/language/cy-GB/langmetadata.xml
  installation/language/da-DK/langmetadata.xml
  installation/language/el-GR/langmetadata.xml
  installation/language/en-AU/langmetadata.xml
  installation/language/en-CA/langmetadata.xml
  installation/language/en-NZ/langmetadata.xml
  installation/language/en-US/langmetadata.xml
  installation/language/es-ES/langmetadata.xml
  installation/language/et-EE/langmetadata.xml
  installation/language/eu-ES/langmetadata.xml
  installation/language/fa-AF/langmetadata.xml
  installation/language/fa-IR/langmetadata.xml
  installation/language/fi-FI/langmetadata.xml
  installation/language/fr-FR/langmetadata.xml
  installation/language/he-IL/langmetadata.xml
  installation/language/hu-HU/langmetadata.xml
  installation/language/it-IT/langmetadata.xml
  installation/language/ja-JP/langmetadata.xml
  installation/language/ka-GE/langmetadata.xml
  installation/language/kk-KZ/langmetadata.xml
  installation/language/lt-LT/langmetadata.xml
  installation/language/lv-LV/langmetadata.xml
  installation/language/nl-BE/langmetadata.xml
  installation/language/nl-NL/langmetadata.xml
  installation/language/pl-PL/langmetadata.xml
  installation/language/pt-BR/langmetadata.xml
  installation/language/pt-PT/langmetadata.xml
  installation/language/ro-RO/langmetadata.xml
  installation/language/sk-SK/langmetadata.xml
  installation/language/sl-SI/langmetadata.xml
  installation/language/sr-YU/langmetadata.xml
  installation/language/sv-SE/langmetadata.xml
  installation/language/ta-IN/langmetadata.xml
  installation/language/th-TH/langmetadata.xml
  installation/language/tr-TR/langmetadata.xml
  installation/language/uk-UA/langmetadata.xml
  installation/language/vi-VN/langmetadata.xml
  installation/language/zh-CN/langmetadata.xml
  installation/language/zh-TW/langmetadata.xml
  modules/mod_menu/mod_menu.xml
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#38823 [4.3] Template Diff View
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2022-09-23.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2022-09-23.sql
  administrator/components/com_templates/config.xml
  administrator/components/com_templates/tmpl/template/default.php
  administrator/language/en-GB/com_templates.ini
  build/build.php
  build/media_source/com_templates/css/admin-templates-default.css
  build/media_source/com_templates/joomla.asset.json
  build/media_source/com_templates/js/admin-template-compare.es6.js
  composer.json
  composer.lock
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Version.php
Labels: RTC, Language Change, Composer Dependency Changed, NPM Resource Changed, PR-4.3-dev, UI/UX

#38406 [5.0] Remove utf8mb4 conversion
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion.sql
  administrator/components/com_admin/sql/others/mysql/utf8mb4-conversion_optional.sql
  administrator/components/com_installer/src/Model/DatabaseModel.php
  administrator/language/en-GB/com_installer.ini
  libraries/src/Schema/ChangeItem/MysqlChangeItem.php
  libraries/src/Schema/ChangeSet.php
Labels: RTC, Language Change, PR-5.0-dev

#38900 TinyMCE fix text dragging
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.2-dev

#38935 Fix order of items not always saved
  build/media_source/system/js/draggable.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#38948 Fix Automatic conversion of false to array
  libraries/src/Document/HtmlDocument.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#38960 Fix empty table in users permissions
  administrator/components/com_users/tmpl/debuguser/default.php
Labels: RTC, PR-4.2-dev

#38944 Updated link
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC, PR-4.2-dev

#38827 [4.2] form placeholder
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
Labels: RTC, NPM Resource Changed, PR-4.2-dev, UI/UX

#38796 [4.2] Do not checkout a record when the user is not logged in
  libraries/src/MVC/Model/FormModel.php
  tests/Unit/Libraries/Cms/MVC/Model/FormModelTest.php
Labels: RTC, PR-4.2-dev

#38907 Ignore PHP warnings raised by simplexml_load_file()
  libraries/namespacemap.php
Labels: RTC, Updates Requested, PR-4.2-dev

#38852 Adding "pattern" attribute to "tel" form field
  layouts/joomla/form/field/tel.php
Labels: RTC, PR-4.2-dev

#37017 [4.2] The alias is already being used - updates
  administrator/components/com_contact/src/Table/ContactTable.php
  administrator/components/com_finder/src/Table/FilterTable.php
  administrator/components/com_newsfeeds/src/Table/NewsfeedTable.php
  administrator/components/com_tags/src/Table/TagTable.php
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/com_newsfeeds.ini
  administrator/language/en-GB/com_tags.ini
  administrator/language/en-GB/lib_joomla.ini
  libraries/src/Table/Category.php
  libraries/src/Table/Content.php
  libraries/src/Table/Menu.php
Labels: Language Change, PR-4.2-dev, psr12

#38771 Media Actions - Better UX
  administrator/components/com_media/resources/scripts/components/browser/actionItems/actionItemsContainer.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/delete.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/download.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/edit.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/preview.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/rename.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/share.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/toggle.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/com_media.ini
  build/media_source/com_media/scss/_variables.scss
  build/media_source/com_media/scss/components/_media-browser.scss
  language/en-GB/com_media.ini
Labels: RTC, Language Change, a11y, NPM Resource Changed, PR-4.2-dev

#38973 Updating 4.3-dev with changes from 4.2-dev
  administrator/components/com_contact/src/Table/ContactTable.php
  administrator/components/com_finder/src/Table/FilterTable.php
  administrator/components/com_media/resources/scripts/components/browser/actionItems/actionItemsContainer.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/delete.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/download.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/edit.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/preview.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/rename.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/share.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/toggle.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/components/com_newsfeeds/src/Table/NewsfeedTable.php
  administrator/components/com_tags/src/Table/TagTable.php
  administrator/components/com_templates/tmpl/template/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/com_media.ini
  administrator/language/en-GB/com_newsfeeds.ini
  administrator/language/en-GB/com_tags.ini
  administrator/language/en-GB/lib_joomla.ini
  build/media_source/com_media/scss/_variables.scss
  build/media_source/com_media/scss/components/_media-browser.scss
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js
  build/media_source/system/js/draggable.es6.js
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
  language/en-GB/com_media.ini
  libraries/namespacemap.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/MVC/Model/FormModel.php
  libraries/src/Table/Category.php
  libraries/src/Table/Content.php
  libraries/src/Table/Menu.php
  tests/Unit/Libraries/Cms/MVC/Model/FormModelTest.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#38972 Correct var type for $fieldCache
  administrator/components/com_fields/src/Helper/FieldsHelper.php
Labels: PR-4.2-dev

#38971 Hide table columns debug
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#38984 Bugfix for issue 38814
  administrator/components/com_content/src/Field/Modal/ArticleField.php
Labels: RTC, PR-4.2-dev

#38889 [4] admin - show association button when supported
  administrator/components/com_categories/src/View/Category/HtmlView.php
Labels: RTC, Documentation Required, hacktoberfest-accepted, PR-4.2-dev, hacktoberfest

#38964 Added class `previous` to the 'Previous' button.
  plugins/content/pagenavigation/tmpl/default.php
Labels: RTC, PR-4.2-dev

#31419 [4.1] Vertical tabs style is forced for nested tabs
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: RTC, NPM Resource Changed, PR-4.2-dev, psr12

#38663 [4.3] NPM build tools cleanup/Perf fixes
  .drone.yml
  build/build-modules-js/init/minify-vendor.es6.js
  build/build-modules-js/javascript/build-com_media-js.es6.js
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/build-modules-js/javascript/compile-to-es5.es6.js
  build/build-modules-js/javascript/handle-es5.es6.js
  build/build-modules-js/javascript/minify.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/media_source/plg_system_jooa11y/scss/jooa11y.scss
  package-lock.json
  package.json
Labels: Unit/System Tests, NPM Resource Changed, PR-4.3-dev

#39002 [4.3] Adding phan static code analyser
  .drone.yml
  .phan/config.php
  .phan/dom.phan_php
  .phan/memcached.phan_php
  .phan/redis.phan_php
  build/build.php
  composer.json
  composer.lock
Labels: Unit/System Tests, Composer Dependency Changed, PR-4.3-dev

#39000 [4.3] Phan: Using DatabaseInterface::quoteName instead of QueryInterface::quoteName
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_finder/src/Indexer/Query.php
Labels: PR-4.3-dev

#38325 [4.3] Add a CLI installation for Joomla
  .drone.yml
  installation/INSTALL
  installation/forms/setup.xml
  installation/includes/cli.php
  installation/joomla.php
  installation/language/en-GB/joomla.cli.ini
  installation/src/Application/CliInstallationApplication.php
  installation/src/Console/InstallCommand.php
  installation/src/Form/Field/Installation/LanguageField.php
  installation/src/Helper/DatabaseHelper.php
  installation/src/Model/DatabaseModel.php
  installation/src/Service/Provider/Application.php
  libraries/src/Form/Field/PasswordField.php
  libraries/src/Form/Rule/PasswordRule.php
  ruleset.xml
  tests/Codeception/drone-api-run.sh
Labels: RTC, Unit/System Tests, Language Change, PR-4.3-dev

#39012 Upmerge 2022 10 21
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  administrator/components/com_users/tmpl/debuggroup/default.php
  administrator/components/com_users/tmpl/debuguser/default.php
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_associations.ini
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_cache.ini
  administrator/language/en-GB/com_categories.ini
  administrator/language/en-GB/com_checkin.ini
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_content.ini
  administrator/language/en-GB/com_contenthistory.ini
  administrator/language/en-GB/com_fields.ini
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/com_installer.ini
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/com_languages.ini
  administrator/language/en-GB/com_mails.ini
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/com_messages.ini
  administrator/language/en-GB/com_modules.ini
  administrator/language/en-GB/com_newsfeeds.ini
  administrator/language/en-GB/com_plugins.ini
  administrator/language/en-GB/com_privacy.ini
  administrator/language/en-GB/com_redirect.ini
  administrator/language/en-GB/com_scheduler.ini
  administrator/language/en-GB/com_tags.ini
  administrator/language/en-GB/com_templates.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/com_workflow.ini
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/plg_system_webauthn.ini
  api/language/en-GB/joomla.ini
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
  language/en-GB/com_contact.ini
  language/en-GB/com_content.ini
  language/en-GB/joomla.ini
  language/en-GB/lib_joomla.ini
  plugins/content/pagenavigation/tmpl/default.php
Labels: Test instructions missing, Language Change, PR-4.3-dev

#35424 [4.3] Fix language constants overrides in com_template.inis and com_categories.ini
  administrator/language/en-GB/com_categories.ini
  administrator/language/en-GB/com_templates.ini
Labels: Language Change, PR-4.3-dev, psr12

#34892 Simplify com_content params model state
  components/com_content/src/Model/CategoryModel.php
Labels: PR-4.3-dev, psr12

#34894 Simplify params model state for com_contact, com_newsfeeds
  components/com_contact/src/Model/CategoryModel.php
  components/com_newsfeeds/src/Model/CategoryModel.php
Labels: PR-4.3-dev, psr12

#36759 [4.3] Finder: Enforce Taxonomies to contain a title
  administrator/components/com_finder/src/Indexer/Result.php
Labels: RTC, PR-4.3-dev, psr12

#35584 Correct access checks for Categories Quick Icon
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: RTC, PBF, PR-4.2-dev, psr12

#39021 [5.0] Fix Drone
  .appveyor.yml
  .drone.yml
  composer.lock
  package-lock.json
Labels: Unit/System Tests, Composer Dependency Changed, NPM Resource Changed, PR-5.0-dev

#39019 Optimizing cypress/drone setup
  .drone.yml
  package-lock.json
  package.json
  tests/cypress/drone-system-run.sh
  tests/cypress/support/index.js
Labels: Unit/System Tests, NPM Resource Changed, PR-4.3-dev

#39025 Renovatebot: Only do security updates on 4.2-dev
  renovate.json
Labels: PR-4.2-dev

#39026 [4.3] Update dependencies
  composer.lock
  package-lock.json
  plugins/editors/tinymce/tinymce.xml
Labels: Composer Dependency Changed, NPM Resource Changed, PR-4.3-dev

#36596 [4.0] Remove "(TEMPORARY)" css rules in main cassiopea template.scss
  build/media_source/templates/administrator/atum/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/template.scss
Labels: NPM Resource Changed, PBF, J4 Frontend Template, PR-4.2-dev, psr12

#39005 [4.2][com_redirect] rawurldecode of new_url
  administrator/components/com_redirect/tmpl/links/default.php
Labels: RTC, PR-4.2-dev

#39037 Remove unused Javascript Testing Framework karma
  package-lock.json
  package.json
  tests/javascript/karma.conf.js
Labels: Unit/System Tests, NPM Resource Changed, PR-4.3-dev

#39018 [5.0] Remove IE 11 warning message due to EOL
  administrator/language/en-GB/joomla.ini
  administrator/templates/atum/login.php
  api/language/en-GB/joomla.ini
  build/media_source/templates/administrator/atum/scss/blocks/_login.scss
Labels: Language Change, NPM Resource Changed, Maintainers Checked, PR-5.0-dev

#30834 [4.3] Message after a login / logout frontend
  components/com_users/src/Controller/UserController.php
  language/en-GB/com_users.ini
Labels: Language Change, PR-4.3-dev, psr12

#38995 [4.3] Use the internal database in the sysinfo model
  administrator/components/com_admin/src/Model/SysinfoModel.php
Labels: RTC, PR-4.3-dev

#37900 [4.2] Improve IE detection warning
  administrator/templates/atum/login.php
Labels: PR-4.2-dev

#38989 Fix error
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
Labels: RTC, PR-4.2-dev

#38405 [5.0] Remove the last code artefacts for Microsoft SQL Server / SQL Azure databases
  libraries/classmap.php
  libraries/src/Schema/ChangeItem.php
  libraries/src/Schema/ChangeItem/SqlsrvChangeItem.php
  libraries/src/Schema/ChangeSet.php
Labels: RTC, PR-5.0-dev

#39039 Upmerge
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
  administrator/templates/atum/login.php
  build/media_source/templates/administrator/atum/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/template.scss
  plugins/editors/codemirror/layouts/editors/codemirror/element.php
  renovate.json
Labels: NPM Resource Changed, PR-4.3-dev

#38676 [5.0] Revert "[4.2] Change the db calls back to the getDbo (#38506)"
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/ListModel.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
Labels: Unit/System Tests, PR-5.0-dev

#39041 Improve openldap in drone
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#39040 [4.3] Drone: Changing order of steps
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#30178 Fixing #__assets table
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-4.3-dev

#35752 [J4.0] Added support in field of type imagelist extensions files for images: AVIF, HEIC, WEBP, WEBP2
  libraries/src/Form/Field/ImagelistField.php
Labels: PR-4.2-dev, PR-4.3-dev, psr12

#39044 [4.3] Drone: Posting link to artifacts as status message in PR
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#31120 Fix workflow/stage unpublish/trash/deletion prevention
  administrator/language/en-GB/com_workflow.ini
  plugins/content/joomla/joomla.php
Labels: RTC, Language Change, Maintainers Checked, PR-4.3-dev, psr12

#39043 Fix code style errors from vue update
  administrator/components/com_media/resources/scripts/components/browser/actionItems/actionItemsContainer.vue
  administrator/components/com_media/resources/scripts/components/browser/actionItems/toggle.vue
Labels: NPM Resource Changed, PR-4.3-dev

#39042 [4.3] Set focus on input in create modal
  administrator/components/com_media/resources/scripts/components/modals/create-folder-modal.vue
Labels: NPM Resource Changed, PR-4.3-dev

#38667 Language Change for issue #38659
  administrator/language/en-GB/plg_system_shortcut.ini
  administrator/language/en-GB/plg_system_shortcut.sys.ini
  build/media_source/plg_system_shortcut/js/shortcut.es6.js
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: RTC, Language Change, NPM Resource Changed, PR-4.2-dev

#38604 User Registration Captcha
  components/com_users/forms/registration.xml
  components/com_users/src/View/Registration/HtmlView.php
  components/com_users/tmpl/registration/default.php
Labels: RTC, PR-4.2-dev, PR-4.3-dev

#38905 PHPDoc for Json input
  administrator/components/com_config/src/Model/ApplicationModel.php
  libraries/src/Input/Input.php
Labels: Maintainers Checked, PR-4.3-dev

#39046 Upmerge/4.3
  administrator/language/en-GB/plg_system_shortcut.ini
  administrator/language/en-GB/plg_system_shortcut.sys.ini
  build/media_source/plg_system_shortcut/js/shortcut.es6.js
  installation/language/pt-BR/joomla.ini
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: Language Change, NPM Resource Changed, PR-4.3-dev

#39066 Update github actions in workflows
  .github/workflows/cacert-update.yml
  .github/workflows/create-translation-pull-request-v4.yml
Labels: PR-4.2-dev

#38590 Fix CaptchaRule to use correct plugin
  libraries/src/Form/Rule/CaptchaRule.php
Labels: RTC, PR-4.2-dev

#39056 [4.3] Fixing php compatibility issues 1
  administrator/components/com_templates/tmpl/template/default.php
  libraries/src/Application/DaemonApplication.php
Labels: PR-4.3-dev

#39071 [4.2] Debug plugin - fix copyright
  plugins/system/debug/src/DataCollector/RequestDataCollector.php
  plugins/system/debug/src/DataCollector/UserCollector.php
Labels: PR-4.2-dev

#39072 [4.2] s/periond/period
  administrator/language/en-GB/plg_system_debug.ini
Labels: Language Change, PR-4.2-dev

#39080 Fix PHPCS from Security Fix
  plugins/system/debug/src/DataCollector/RequestDataCollector.php
Labels: Release Blocker, PR-4.2-dev

#39081 Updating 4.3-dev with changes from 4.2-dev
  .github/workflows/cacert-update.yml
  .github/workflows/create-translation-pull-request-v4.yml
  administrator/components/com_languages/tmpl/language/edit.php
  administrator/components/com_users/tmpl/user/edit.php
  administrator/language/en-GB/com_media.ini
  administrator/language/en-GB/plg_system_debug.ini
  language/en-GB/com_media.ini
  libraries/src/Form/Rule/CaptchaRule.php
  libraries/src/Workflow/WorkflowPluginTrait.php
  plugins/system/debug/debug.php
  plugins/system/debug/debug.xml
  plugins/system/debug/src/DataCollector/RequestDataCollector.php
  plugins/system/debug/src/DataCollector/SessionCollector.php
  plugins/system/debug/src/DataCollector/UserCollector.php
  plugins/system/debug/src/Storage/FileStorage.php
  plugins/task/checkfiles/src/Extension/Checkfiles.php
Labels: Test instructions missing, Language Change, PR-4.3-dev

#39048 [4.3] Fix #30834
  components/com_users/src/Controller/UserController.php
Labels: Release Blocker, PR-4.3-dev

#39079 Migrate qn function to quoteName for phan
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_scheduler/src/Task/Task.php
  libraries/src/Application/MultiFactorAuthenticationHandler.php
  plugins/system/tasknotification/tasknotification.php
  plugins/system/webauthn/src/CredentialRepository.php
  plugins/system/webauthn/src/PluginTraits/UserDeletion.php
  plugins/user/joomla/joomla.php
  plugins/user/token/token.php
Labels: PR-4.3-dev

#39068 [4.3] Remove dependency on factory
  plugins/workflow/publishing/publishing.php
Labels: PR-4.3-dev

#39050 Do not show a deprecated message when no ordering is set in back end list views
  libraries/src/MVC/Model/ListModel.php
Labels: RTC, PR-4.2-dev

#39089 [4.3] Drone: Adding curl to image in case of failure
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#39065 [4.2] Add missing error messages to frontend for PR #37017
  language/en-GB/com_contact.ini
  language/en-GB/com_content.ini
  language/en-GB/lib_joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#39090 Drone: Converting failure script to rclone
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#39098 [4.3] Drone: Fixing nightly build notification
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#39099 Revert "[4.3] Drone: Fixing nightly build notification"
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#39091 [bug] Do not force value validation (media field)
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39038 Fix password renew for users without core.admin permission
  administrator/components/com_users/src/Controller/UserController.php
Labels: RTC, PR-4.2-dev

#39101 [4.3] Update deleted files list in script.php
  administrator/components/com_admin/script.php
Labels: RTC, PR-4.3-dev
