Repository joomla/joomla-cms, pull requests merged in 2022-08, with the labels that each got.

#38278 [4.2] Warning about creating a backup before updating
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
Labels: RTC, PR-4.2-dev

#38281 [4.2] com_media (Mediamanager) configuration view. Text fields to textarea.
  administrator/components/com_media/config.xml
  administrator/components/com_media/tmpl/file/default.php
  administrator/components/com_media/tmpl/media/default.php
Labels: RTC, PR-4.2-dev

#38299 [4.2] Fix redirect on login url error
  components/com_users/src/Controller/UserController.php
Labels: RTC, PR-4.2-dev

#38360 column select rtl css
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_bootstrap-rtl.scss
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.2-dev

#38366 working link to license
  administrator/components/com_admin/tmpl/help/default.php
Labels: RTC, PR-4.2-dev

#38387 Upgrading paragonie/sodium_compat (v1.17.0 => v1.17.1)
  composer.json
  composer.lock
  libraries/vendor/composer/autoload_files.php
  libraries/vendor/composer/autoload_static.php
  libraries/vendor/composer/installed.json
  libraries/vendor/composer/installed.php
  libraries/vendor/paragonie/sodium_compat/src/Compat.php
  libraries/vendor/paragonie/sodium_compat/src/Core/BLAKE2b.php
  libraries/vendor/paragonie/sodium_compat/src/Core/Curve25519.php
  libraries/vendor/paragonie/sodium_compat/src/Core/Util.php
  libraries/vendor/paragonie/sodium_compat/src/Core32/Curve25519.php
  libraries/vendor/paragonie/sodium_compat/src/Core32/Curve25519/Fe.php
  libraries/vendor/paragonie/sodium_compat/src/Core32/Int32.php
  libraries/vendor/paragonie/sodium_compat/src/Core32/Int64.php
  libraries/vendor/paragonie/sodium_compat/src/Core32/Poly1305/State.php
  libraries/vendor/paragonie/sodium_compat/src/Core32/XChaCha20.php
  libraries/vendor/paragonie/sodium_compat/src/File.php
Labels: Composer Dependency Changed, PR-3.10-dev

#38424 Updating 4.3-dev with changes from 4.2-dev
  administrator/components/com_admin/tmpl/help/default.php
  administrator/components/com_contenthistory/tmpl/preview/preview.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_media/config.xml
  administrator/components/com_media/tmpl/file/default.php
  administrator/components/com_media/tmpl/media/default.php
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_users/tmpl/methods/list.php
  administrator/language/en-GB/plg_multifactorauth_yubikey.ini
  administrator/language/en-GB/plg_multifactorauth_yubikey.sys.ini
  administrator/language/en-GB/plg_system_webauthn.ini
  administrator/language/en-GB/plg_twofactorauth_yubikey.ini
  administrator/language/en-GB/plg_twofactorauth_yubikey.sys.ini
  administrator/modules/mod_quickicon/mod_quickicon.xml
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_bootstrap-rtl.scss
  components/com_users/src/Controller/UserController.php
  components/com_users/tmpl/login/default_login.php
  components/com_users/tmpl/methods/list.php
  layouts/plugins/system/webauthn/manage.php
  modules/mod_breadcrumbs/mod_breadcrumbs.php
  modules/mod_breadcrumbs/src/Helper/BreadcrumbsHelper.php
  modules/mod_breadcrumbs/tmpl/default.php
  plugins/system/webauthn/services/provider.php
  plugins/system/webauthn/src/PluginTraits/UserProfileFields.php
  renovate.json
Labels: Language Change, NPM Resource Changed, PR-4.3-dev

#38426 [4.2] Fix empty default_value check in fields plugin
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  plugins/fields/menuitem/params/menuitem.xml
Labels: RTC, Release Blocker, PR-4.2-dev

#38439 Set a default for events to email in User Action Log Options
  plugins/system/actionlogs/forms/actionlogs.xml
Labels: RTC, PR-4.2-dev

#38436 Allow the statistics plugin to run on the captive page
  libraries/src/Application/MultiFactorAuthenticationHandler.php
Labels: RTC, PR-4.2-dev

#38428 [4.3] Deprecate Joomla\CMS\Schema\ChangeItem\SqlsrvChangeItem for 5.0
  libraries/src/Schema/ChangeItem/SqlsrvChangeItem.php
Labels: RTC, PR-4.3-dev

#38442 [4.2] add renovate.json to the exclude list on the build tools
  build/build.php
Labels: Release Blocker, PR-4.2-dev, Maintainers Checked

#38334 [4.2] hotkeys
  build/build-modules-js/settings.json
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: RTC, PR-4.2-dev

#38504 Make sure the itemID is of type int
  components/com_users/src/Controller/UserController.php
Labels: RTC, PR-4.2-dev

#38488 Add bcmath_compat polyfill for servers without BCmath / GMP support
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.2-dev, Maintainers Checked

#38373 [4][com_finder] error when gather statistic enabled
  components/com_finder/src/Helper/FinderHelper.php
Labels: Release Blocker, PR-4.2-dev

#38495 [4.2] remove php open close tags
  administrator/components/com_users/tmpl/user/edit_groups.php
Labels: RTC, PR-4.2-dev

#38494 [4.2] s/validatng/validating
  plugins/multifactorauth/totp/src/Extension/Totp.php
  plugins/multifactorauth/webauthn/src/Extension/Webauthn.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
Labels: PR-4.2-dev

#38496 [4.2] s/favorite/favourite
  administrator/language/en-GB/plg_multifactorauth_totp.ini
Labels: Language Change, PR-4.2-dev

#38506 [4.2] Change the db calls back to the getDbo
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/ListModel.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
Labels: RTC, Unit/System Tests, Release Blocker, PR-4.2-dev

#38516 [4.2] Empty folder
  administrator/components/com_admin/script.php
  build/build.php
Labels: RTC, PR-4.2-dev

#38519 [4.2] Fix issue "updateCheck is null"
  build/media_source/com_joomlaupdate/js/default.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.2-dev

#38490 [4.2] Redis cache
  libraries/src/Version.php
Labels: PR-4.2-dev

#38523 [4.2] Remove hotkeys.js by script.php
  administrator/components/com_admin/script.php
Labels: PR-4.2-dev, Maintainers Checked

#38529 Revert "MFA: ignore non html requests"
  libraries/src/Application/MultiFactorAuthenticationHandler.php
Labels: PR-4.2-dev

#38525 Remove the autoload_psr4 before running finalisation.php
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
Labels: PR-4.2-dev

#38312 [4.2 RC1] Feed display module not working
  libraries/src/Feed/Parser/AtomParser.php
  libraries/src/Feed/Parser/RssParser.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
Labels: RTC, Unit/System Tests, PR-4.2-dev

#38533 Stats collection must not be shown in captive MFA pages
  libraries/src/Application/MultiFactorAuthenticationHandler.php
  plugins/system/stats/stats.php
Labels: RTC, PR-4.2-dev

#38524 CLI application crashed instantiating MVCFactory
  libraries/src/Application/ConsoleApplication.php
Labels: RTC, PR-4.2-dev

#38557 Merge branch 4.2 into 4.3
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-07-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.0-2022-07-07.sql
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_users/src/Controller/CaptiveController.php
  administrator/components/com_users/src/Controller/MethodController.php
  administrator/components/com_users/src/Controller/MethodsController.php
  administrator/components/com_users/src/DataShape/SetupRenderOptions.php
  administrator/components/com_users/src/Helper/UsersHelper.php
  administrator/components/com_users/src/Model/MethodModel.php
  administrator/components/com_users/src/Model/UserModel.php
  administrator/components/com_users/src/Model/UsersModel.php
  administrator/components/com_users/src/View/Captive/HtmlView.php
  administrator/components/com_users/src/View/Debuggroup/HtmlView.php
  administrator/components/com_users/src/View/Debuguser/HtmlView.php
  administrator/components/com_users/tmpl/captive/select.php
  administrator/components/com_users/tmpl/method/backupcodes.php
  administrator/components/com_users/tmpl/user/edit.php
  administrator/components/com_users/tmpl/user/edit_groups.php
  administrator/language/en-GB/plg_fields_menuitem.ini
  administrator/language/en-GB/plg_fields_menuitem.sys.ini
  administrator/language/en-GB/plg_multifactorauth_totp.ini
  build/build-modules-js/settings.json
  build/build.php
  build/media_source/com_joomlaupdate/js/default.es6.js
  components/com_finder/src/Helper/FinderHelper.php
  components/com_users/src/Controller/UserController.php
  composer.json
  composer.lock
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Application/MultiFactorAuthenticationHandler.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Feed/Parser/AtomParser.php
  libraries/src/Feed/Parser/RssParser.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/ListModel.php
  modules/mod_breadcrumbs/src/Helper/BreadcrumbsHelper.php
  plugins/fields/menuitem/menuitem.php
  plugins/fields/menuitem/menuitem.xml
  plugins/fields/menuitem/tmpl/menuitem.php
  plugins/multifactorauth/fixed/src/Extension/Fixed.php
  plugins/multifactorauth/totp/src/Extension/Totp.php
  plugins/multifactorauth/webauthn/src/Extension/Webauthn.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/system/actionlogs/forms/actionlogs.xml
  plugins/system/shortcut/src/Extension/Shortcut.php
  plugins/system/stats/stats.php
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
  tests/Unit/Libraries/Cms/MVC/Model/DatabaseModelTest.php
Labels: Language Change, Composer Dependency Changed, NPM Resource Changed, PR-4.3-dev

#38422 [4.3] Switching from Codeception to Cypress for tests
  .drone.yml
  .gitignore
  cypress.config.js
  package-lock.json
  package.json
  tests/Codeception/_support/Step/Acceptance/Administrator/Category.php
  tests/Codeception/_support/Step/Acceptance/Administrator/Field.php
  tests/Codeception/acceptance/administrator/components/com_content/ContentCategoryListCest.php
  tests/Codeception/acceptance/administrator/components/com_content/ContentFieldListCest.php
  tests/Codeception/acceptance/administrator/components/com_content/ContentListCest.php
  tests/Codeception/acceptance/administrator/components/com_menu/MenuCest.php
  tests/Codeception/acceptance/administrator/components/com_users/UserListCest.php
  tests/cypress/.eslinitrc.js
  tests/cypress/cypress-system-run.sh
  tests/cypress/drone-system-run.sh
  tests/cypress/exclude.txt
  tests/cypress/fixtures/.gitkeep
  tests/cypress/integration/00-install/install.cy.js
  tests/cypress/integration/administrator/components/com_content/ContentCategoryList.cy.js
  tests/cypress/integration/administrator/components/com_content/ContentFieldList.cy.js
  tests/cypress/integration/administrator/components/com_content/ContentList.cy.js
  tests/cypress/integration/administrator/components/com_menu/Menu.cy.js
  tests/cypress/integration/administrator/components/com_users/UserList.cy.js
  tests/cypress/integration/administrator/general.cy.js
  tests/cypress/integration/site/general.cy.js
  tests/cypress/plugins/.gitkeep
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
Labels: Unit/System Tests, NPM Resource Changed, PR-4.3-dev

#38421 [4.3] Activate all unit tests as default
  phpunit-pgsql.xml.dist
  phpunit.xml.dist
  tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php
  tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php
  tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
  tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
  tests/Unit/Plugin/Task/SiteStatus/Extension/SiteStatusPluginTest.php
  tests/Unit/bootstrap.php
  tests/phpunit-appveyor.xml.dist
Labels: Unit/System Tests, Test instructions missing, PR-4.3-dev

#38567 [4.2] Correctly revert pull request no. 38244 for updating from 4.2.0 RC 1
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/4.2.0-2022-07-07.sql
  administrator/components/com_admin/sql/updates/mysql/4.2.1-2022-08-23.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.0-2022-07-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.1-2022-08-23.sql
Labels: PR-4.2-dev

#38209 Update Joomla Version and dependencies for 5.0
  .appveyor.yml
  .drone.yml
  README.md
  README.txt
  administrator/index.php
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/index.php
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  build/helpTOC.php
  cli/joomla.php
  composer.json
  composer.lock
  index.php
  installation/index.php
  installation/language/en-GB/langmetadata.xml
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Version.php
  package-lock.json
  package.json
  tests/Unit/Plugin/Task/Checkfiles/Extension/CheckfilesPluginTest.php
  tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
  tests/Unit/Plugin/Task/SiteStatus/Extension/SiteStatusPluginTest.php
Labels: Unit/System Tests, Language Change, Composer Dependency Changed, NPM Resource Changed, PR-5.0-dev

#38651 Unused Factory
  administrator/components/com_admin/src/View/Sysinfo/HtmlView.php
Labels: PR-4.2-dev

#38625 Unused Joomla\cms\factory
  administrator/components/com_languages/src/View/Overrides/HtmlView.php
Labels: RTC, PR-4.2-dev

#38448 Template override link
  administrator/components/com_templates/tmpl/templates/default.php
Labels: RTC, PR-4.2-dev

#38431 OpenSearch fix for: passing null is deprecated
  components/com_finder/src/View/Search/OpensearchView.php
Labels: RTC, PR-4.2-dev

#38638 Use ellipsis - part 1
  administrator/language/en-GB/com_cpanel.ini
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/joomla.ini
  administrator/language/en-GB/plg_editors-xtd_readmore.ini
  administrator/language/en-GB/plg_editors-xtd_readmore.sys.ini
  administrator/language/en-GB/plg_installer_packageinstaller.ini
  administrator/language/en-GB/plg_installer_webinstaller.ini
  administrator/language/en-GB/plg_multifactorauth_webauthn.ini
  administrator/language/en-GB/plg_multifactorauth_webauthn.sys.ini
  administrator/language/en-GB/plg_quickicon_extensionupdate.ini
  administrator/language/en-GB/plg_quickicon_joomlaupdate.ini
  administrator/language/en-GB/plg_quickicon_overridecheck.ini
  administrator/language/en-GB/plg_quickicon_privacycheck.ini
  api/language/en-GB/joomla.ini
  installation/language/en-GB/joomla.ini
  language/en-GB/com_content.ini
  language/en-GB/finder_cli.ini
  language/en-GB/joomla.ini
  language/en-GB/mod_articles_category.ini
  language/en-GB/mod_articles_news.ini
  language/en-GB/mod_finder.ini
Labels: RTC, Language Change, PR-4.2-dev

#38622 File too large
  administrator/language/en-GB/com_media.ini
  administrator/language/en-GB/lib_joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#38619 User Profile Terms of service
  administrator/language/en-GB/plg_user_profile.ini
  plugins/user/profile/profile.php
Labels: RTC, Language Change, PR-4.2-dev

#38592 Rename all User Groups
  administrator/components/com_users/forms/group.xml
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.2-dev

#38541 Overridden File
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.2-dev

#38537 [4.2] Improve description for Users MFA configuration
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.2-dev

#38570 Install Selected Languages
  installation/language/en-GB/joomla.ini
  installation/tmpl/remove/default.php
Labels: RTC, Language Change, PR-4.2-dev

#38459 [4.2] Correct size of template files to upload
  administrator/components/com_templates/src/Helper/TemplateHelper.php
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.2-dev

#38451 Template Override Description
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.2-dev

#38449 Template Overrides message on update
  administrator/language/en-GB/plg_installer_override.ini
  plugins/installer/override/override.php
Labels: RTC, Language Change, PR-4.2-dev

#38313 [4.2] [Blog Sample Data] Constant instead of encoded "My Blog"
  administrator/language/en-GB/plg_sampledata_blog.ini
  plugins/sampledata/blog/blog.php
Labels: RTC, Language Change, PR-4.2-dev, Maintainers Checked

#38447 Template Override Actions
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_templates/tmpl/template/default_updated_files.php
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-4.2-dev

#38520 [4.2] php cs
  administrator/components/com_users/tmpl/method/edit.php
  components/com_users/tmpl/method/edit.php
Labels: RTC, PR-4.2-dev

#38521 [4.2] fix module name
  administrator/modules/mod_user/mod_user.xml
Labels: RTC, PR-4.2-dev
