Repository joomla/joomla-cms, pull requests merged in 2023-02, with the labels that each got.

#39749 [4.3] Showing Drag and Drop option for empty folder in Media Manager
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39722 Rename cypress.config.js so that it can be included in the .gitignore file.
  .drone.yml
  .gitignore
  cypress.config.dist.js
Labels: Unit/System Tests, PR-4.3-dev

#39772 [4.3] CSP Supplementary to #39726
  administrator/components/com_associations/forms/filter_associations.xml
  administrator/components/com_languages/forms/filter_installed.xml
  administrator/components/com_menus/forms/filter_items.xml
  administrator/components/com_menus/forms/filter_itemsadmin.xml
  administrator/components/com_modules/forms/filter_modules.xml
  administrator/components/com_modules/forms/filter_modulesadmin.xml
  administrator/components/com_templates/forms/filter_styles.xml
  administrator/components/com_templates/forms/filter_templates.xml
  build/media_source/system/js/searchtools.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39771 Add the correct properties to the finder response class
  administrator/components/com_finder/src/Response/Response.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#39766 [4.2] - Admin login - set max width on image
  build/media_source/templates/administrator/atum/scss/blocks/_login.scss
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39714 Update Version.php
  libraries/src/Cache/Cache.php
  libraries/src/Version.php
Labels: RTC, PR-4.2-dev

#39700 remove unused variable
  components/com_contact/src/Model/CategoryModel.php
Labels: RTC, PR-4.2-dev

#39693 [4.2] Check extension description exists Manage Extensions
  administrator/components/com_installer/tmpl/manage/default.php
Labels: RTC, PR-4.2-dev

#39692 [4.2] Check extension description exists Update sites
  administrator/components/com_installer/tmpl/updatesites/default.php
Labels: RTC, PR-4.2-dev

#39350 Use form.elements instead of custom query
  build/media_source/system/js/fields/validate.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39329 [4] Template. Allow manifest tag inheritable = 0 or empty
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, PR-4.2-dev

#38595 [4][com_content] date filter for archived
  components/com_content/src/Model/ArchiveModel.php
Labels: RTC, PR-4.2-dev

#38908 Fix smart search highliter: match word exactly
  build/media_source/system/js/highlight.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39003 Deprecation message in PHP 8.1, clearer code
  plugins/content/loadmodule/loadmodule.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#39378 Adding support to the NEL header to the core httpheaders plugin
  plugins/system/httpheaders/httpheaders.php
  plugins/system/httpheaders/httpheaders.xml
Labels: RTC, Documentation Required, PR-4.3-dev

#39783 Updating 4.3-dev with changes from 4.2-dev
  administrator/components/com_actionlogs/src/Dispatcher/Dispatcher.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_finder/src/Response/Response.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/updatesites/default.php
  administrator/components/com_menus/forms/item_url.xml
  administrator/components/com_menus/forms/itemadmin_url.xml
  administrator/components/com_postinstall/src/Controller/MessageController.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  api/components/com_menus/src/Controller/ItemsController.php
  api/language/en-GB/joomla.ini
  build/build-modules-js/javascript/build-com_media-js.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/highlight.es6.js
  build/media_source/templates/administrator/atum/scss/blocks/_login.scss
  components/com_contact/src/Model/CategoryModel.php
  components/com_content/src/Model/ArchiveModel.php
  libraries/src/Cache/Cache.php
  libraries/src/Layout/FileLayout.php
  libraries/src/Mail/MailTemplate.php
  libraries/src/Version.php
  plugins/content/loadmodule/loadmodule.php
  plugins/editors/tinymce/forms/setoptions.xml
  tests/Codeception/README.md
Labels: Unit/System Tests, Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#39781 [4.3] Normalize styling of inputs
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
  build/media_source/templates/administrator/atum/scss/blocks/_switcher.scss
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_custom-forms.scss
  build/media_source/templates/administrator/atum/scss/vendor/choicesjs/choices.scss
  build/media_source/templates/site/cassiopeia/scss/tools/variables/_variables.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/_chosen.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss
  build/media_source/templates/site/cassiopeia/scss/vendor/choicesjs/choices.scss
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39715 Improving the consistency of the HTML models
  modules/mod_login/tmpl/default.php
Labels: RTC, PR-4.2-dev

#39720 Update md5 Deprecation
  libraries/src/Cache/CacheStorage.php
Labels: RTC, PR-4.2-dev

#39782 [4.3] Fix back button in toolbar
  administrator/components/com_users/src/View/Methods/HtmlView.php
Labels: RTC, PR-4.3-dev

#39788 [4.3] Update deleted files list in script.php for upcoming 4.3.0-beta1
  administrator/components/com_admin/script.php
Labels: PR-4.3-dev

#39798 [4.3] Typo
  plugins/fields/media/services/provider.php
Labels: RTC, PR-4.3-dev

#39801 Typo in DEPLOY_VERSION preventing replacement
  libraries/src/Form/Field/ModuleorderField.php
Labels: PR-4.3-dev

#39799 [4.3] spelling fulfill
  installation/src/Application/CliInstallationApplication.php
Labels: RTC, PR-4.3-dev

#39800 Typo in DEPLOY_VERSION preventing replacement
  administrator/components/com_menus/src/Model/MenusModel.php
Labels: PR-4.2-dev

#39809 Revert "[4.3] Typo"
  plugins/fields/media/services/provider.php
Labels: PR-4.3-dev

#39807 Revert "Typo in DEPLOY_VERSION preventing replacement"
  libraries/src/Form/Field/ModuleorderField.php
Labels: PR-4.3-dev

#39808 Revert "[4.3] spelling fulfill"
  installation/src/Application/CliInstallationApplication.php
Labels: PR-4.3-dev

#39810 Update ModuleorderField.php with typo fix
  libraries/src/Form/Field/ModuleorderField.php
Labels: RTC, PR-4.2-dev

#39815 Typo in JLIB_FILESYSTEM_ERROR_FILE_FIND_COPY
  libraries/src/Filesystem/File.php
Labels: RTC, PR-4.2-dev

#39813 Typo fixes re-injection after reverts
  installation/src/Application/CliInstallationApplication.php
  plugins/fields/media/services/provider.php
Labels: RTC, PR-4.3-dev

#39796 [4.3][bug] Fix the infobar gap
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39797 [4.3] warning.css code style
  build/warning_page/template.css
Labels: RTC, PR-4.3-dev

#39748 [4.2] Highlight Plugin: Exit if app not site
  plugins/system/highlight/highlight.php
Labels: RTC, PR-4.2-dev

#39795 [4.2] Discover Install
  administrator/components/com_installer/src/Model/DiscoverModel.php
Labels: RTC, PR-4.2-dev

#39794 [4.2] module saved
  components/com_config/src/Controller/ModulesController.php
Labels: RTC, PR-4.2-dev

#39630 [4] PHP 8.2 Dynamic property - languagefilter
  libraries/src/Application/WebApplication.php
  plugins/system/languagefilter/languagefilter.php
Labels: RTC, PHP 8.x, PR-4.2-dev, Needs deprecation

#39691 [4.2] Add missing properties
  libraries/src/Client/FtpClient.php
  libraries/src/Installer/InstallerExtension.php
  libraries/src/Installer/Manifest.php
  libraries/src/Installer/Manifest/LibraryManifest.php
  libraries/src/Installer/Manifest/PackageManifest.php
  libraries/src/Log/Logger/DatabaseLogger.php
  ruleset.xml
Labels: RTC, PHP 8.x, PR-4.2-dev, Needs deprecation

#39683 [4] PHP 8.2 Dynamic property - registeredurlparams- cache enabled
  libraries/src/Application/SiteApplication.php
Labels: RTC, PHP 8.x, PR-4.2-dev, Needs deprecation

#39828 Skip side by side
  administrator/components/com_templates/tmpl/template/default.php
  build/media_source/system/js/table-columns.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39834 [4.3] Admin modules and xtd-editor plugins
  administrator/components/com_modules/forms/moduleadmin.xml
Labels: RTC, PR-4.3-dev

#39730 [4.3][csp] Reduce inline onclick usage [List views]
  administrator/components/com_contact/src/Service/HTML/AdministratorService.php
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/components/com_messages/src/Service/HTML/Messages.php
  administrator/components/com_redirect/src/Service/HTML/Redirect.php
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/list-view.es6.js
  layouts/joomla/button/action-button.php
  layouts/joomla/searchtools/grid/sort.php
  libraries/src/HTML/Helpers/ActionsDropdown.php
  libraries/src/HTML/Helpers/Grid.php
  libraries/src/HTML/Helpers/JGrid.php
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39833 [4.3] Media manager: add the missing lock component
  administrator/components/com_media/resources/scripts/components/modals/modal.vue
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39841 Correct name of cypress.config in `build/build.php`
  build/build.php
Labels: PR-4.3-dev

#39870 [4.2] Prevent fatal error when Itemid from query is invalid
  libraries/src/Router/SiteRouter.php
Labels: PR-4.2-dev

#39873 [4.3] Fix the mobile footer of the source modal
  build/media_source/plg_editors_tinymce/js/plugins/highlighter/source.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39881 Fix deprecation warning (PHP 8.1+)
  administrator/components/com_menus/src/Helper/MenusHelper.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#39741 [4.3] Media Manager error message
  administrator/components/com_media/src/Controller/ApiController.php
  administrator/language/en-GB/com_media.ini
Labels: RTC, Language Change, PR-4.3-dev

#39770 Converts the finder plugins to service providers
  plugins/finder/categories/categories.xml
  plugins/finder/categories/services/provider.php
  plugins/finder/categories/src/Extension/Categories.php
  plugins/finder/contacts/contacts.xml
  plugins/finder/contacts/services/provider.php
  plugins/finder/contacts/src/Extension/Contacts.php
  plugins/finder/content/content.xml
  plugins/finder/content/services/provider.php
  plugins/finder/content/src/Extension/Content.php
  plugins/finder/newsfeeds/newsfeeds.xml
  plugins/finder/newsfeeds/services/provider.php
  plugins/finder/newsfeeds/src/Extension/Newsfeeds.php
  plugins/finder/tags/services/provider.php
  plugins/finder/tags/src/Extension/Tags.php
  plugins/finder/tags/tags.xml
Labels: RTC, PR-4.3-dev

#39729 Converts the captcha plugins to service providers
  libraries/src/Captcha/Captcha.php
  plugins/captcha/recaptcha/recaptcha.xml
  plugins/captcha/recaptcha/services/provider.php
  plugins/captcha/recaptcha/src/Extension/ReCaptcha.php
  plugins/captcha/recaptcha_invisible/recaptcha_invisible.xml
  plugins/captcha/recaptcha_invisible/services/provider.php
  plugins/captcha/recaptcha_invisible/src/Extension/InvisibleReCaptcha.php
  tests/Unit/Plugin/Captcha/InvisibleRecaptcha/Extension/InvisibleRecaptchaPluginTest.php
  tests/Unit/Plugin/Captcha/Recaptcha/Extension/RecaptchaPluginTest.php
Labels: RTC, Unit/System Tests, PR-4.3-dev

#39886 [4.3] Update deleted files list in script.php for upcoming 4.3.0-beta3
  administrator/components/com_admin/script.php
Labels: PR-4.3-dev

#39890 Correct folder names in .`gitignore`
  .gitignore
Labels: RTC, PR-4.3-dev

#39864 [4.2] Fix warning when null is passed to FieldsHelper::extract method
  administrator/components/com_fields/src/Helper/FieldsHelper.php
Labels: RTC, PR-4.2-dev

#39905 Add more information to CS fixer when failed
  .drone.yml
Labels: Unit/System Tests, PR-4.3-dev

#39907 [4.2] Contact form banned emails and content
  administrator/language/en-GB/com_contact.ini
  components/com_contact/src/Rule/ContactEmailMessageRule.php
  components/com_contact/src/Rule/ContactEmailRule.php
  components/com_contact/src/Rule/ContactEmailSubjectRule.php
Labels: RTC, Language Change, PR-4.2-dev

#39894 Fix tooltip for subform table layout, #39848
  layouts/joomla/form/field/subform/repeatable-table.php
Labels: RTC, PR-4.2-dev

#39891 [4.2] users modal formatting
  administrator/components/com_users/tmpl/users/modal.php
Labels: RTC, PR-4.2-dev

#39850 [4.2] Fix MailTemplate array regression from 4.2.7
  libraries/src/Mail/MailTemplate.php
Labels: RTC, PR-4.2-dev

#39842 Allow subform field value to be an array
  plugins/fields/subform/subform.php
Labels: RTC, PR-4.2-dev

#38633 Admin Module Cpanel Positions
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.2-dev

#39839 Fix for the title of a loaded module is not visible
  layouts/chromes/table.php
  plugins/content/loadmodule/loadmodule.php
  plugins/content/loadmodule/loadmodule.xml
Labels: RTC, PR-4.2-dev

#39826 Issue #39820 fixed warnings in com_contact
  components/com_contact/tmpl/category/default_items.php
Labels: RTC, PR-4.2-dev

#39906 [4.2] Admin module dropdown
  administrator/modules/mod_quickicon/tmpl/default.php
Labels: RTC, PR-4.2-dev

#38959 Fix display of data-function
  administrator/components/com_modules/tmpl/select/default.php
  administrator/components/com_scheduler/src/View/Select/HtmlView.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_scheduler/tmpl/select/default.php
  administrator/components/com_scheduler/tmpl/select/modal.php
Labels: RTC, PR-4.2-dev

#37716 [4.2] contact fields remove layout override
  components/com_contact/layouts/field/render.php
  components/com_contact/layouts/fields/render.php
Labels: RTC, PR-4.2-dev

#39879 [4.2] Implement com_config dispatcher, fix ACL bug
  administrator/components/com_config/src/Dispatcher/Dispatcher.php
  administrator/components/com_config/src/Helper/ConfigHelper.php
Labels: RTC, PR-4.2-dev

#39576 Firefox subform drag fix
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39705 [4.2] Smart Search options
  administrator/components/com_finder/src/View/Searches/HtmlView.php
  administrator/language/en-GB/com_finder.ini
Labels: RTC, Language Change, PR-4.2-dev

#39893 Mail template fix "reply to"
  libraries/src/Mail/MailTemplate.php
Labels: RTC, PR-4.2-dev

#39276 get Database from DI in Library helper
  libraries/src/Helper/LibraryHelper.php
Labels: RTC, PR-4.2-dev

#39530 [4.3] Remove dead code from plugin field
  plugins/user/token/src/Field/JoomlatokenField.php
Labels: RTC, PR-4.3-dev

#39904 Add option to pass a release date to the bump script
  build/bump.php
Labels: PR-4.3-dev

#39580 [4.3] Use CSRF only for the site's domain
  administrator/components/com_config/tmpl/application/default_mail.php
  build/media_source/system/js/core.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39872 [4.3]No search result found msg in media new
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/tmpl/media/default_texts.php
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39869 [4.2] Fix deprecated warnings for HTMLHelper Calendar
  libraries/src/HTML/HTMLHelper.php
Labels: RTC, PHP 8.x, PR-4.2-dev

#39924 [4.2] module position string
  administrator/components/com_modules/layouts/joomla/form/field/modulespositionedit.php
  administrator/language/en-GB/com_modules.ini
Labels: RTC, Language Change, PR-4.2-dev

#39643 Popovers replaced by Tooltips in Category list in Cassiopeia #35467
  libraries/src/HTML/Helpers/Grid.php
Labels: RTC, PR-4.2-dev, Maintainers Checked

#39935 Updating 4.3-dev with changes from 4.2-dev
  administrator/components/com_config/src/Dispatcher/Dispatcher.php
  administrator/components/com_config/src/Helper/ConfigHelper.php
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  administrator/components/com_finder/src/View/Searches/HtmlView.php
  administrator/components/com_modules/tmpl/select/default.php
  administrator/components/com_scheduler/src/View/Select/HtmlView.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_scheduler/tmpl/select/default.php
  administrator/components/com_scheduler/tmpl/select/modal.php
  administrator/components/com_users/tmpl/users/modal.php
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_finder.ini
  administrator/modules/mod_quickicon/tmpl/default.php
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
  components/com_contact/layouts/fields/render.php
  components/com_contact/src/Rule/ContactEmailMessageRule.php
  components/com_contact/src/Rule/ContactEmailRule.php
  components/com_contact/src/Rule/ContactEmailSubjectRule.php
  components/com_contact/tmpl/category/default_items.php
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  layouts/chromes/table.php
  layouts/joomla/form/field/subform/repeatable-table.php
  libraries/src/Helper/LibraryHelper.php
  libraries/src/Mail/MailTemplate.php
  plugins/content/loadmodule/loadmodule.php
  plugins/content/loadmodule/loadmodule.xml
  plugins/fields/subform/src/Extension/Subform.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-4.3-dev

#39930 [4.2] select category string
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#39940 [4.3] fix namespace captcha unit tests
  tests/Unit/Plugin/Captcha/InvisibleRecaptcha/Extension/InvisibleRecaptchaPluginTest.php
  tests/Unit/Plugin/Captcha/Recaptcha/Extension/RecaptchaPluginTest.php
Labels: Unit/System Tests, PR-4.3-dev

#39923 [4.2] lang string
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-4.2-dev

#39561 Login feedback if user do not have offline access
  plugins/authentication/joomla/joomla.php
Labels: RTC, PR-4.2-dev

#39943 [4.2] Revert 39329 - Release Blocker
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, Release Blocker, PR-4.2-dev, Small

#39395 Invalid void return type
  libraries/src/Application/ApplicationHelper.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CMSWebApplicationInterface.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Menu/AbstractMenu.php
  libraries/src/Serializer/JoomlaSerializer.php
Labels: RTC, PR-4.2-dev, Small

#39563 Installation script messages in Discover emptystate layout
  administrator/components/com_installer/tmpl/discover/emptystate.php
Labels: PR-4.2-dev, Small

#39926 [4.2] Fix missing context for com_fields after publish/unpublish items
  administrator/components/com_fields/src/Controller/FieldsController.php
  administrator/components/com_fields/src/Controller/GroupsController.php
Labels: RTC, PR-4.2-dev

#39863 [4.2] Fix wrong data for calendar custom fields when user registration fail
  components/com_users/src/Controller/RegistrationController.php
Labels: RTC, PR-4.2-dev, Small

#39954 [4.2] Normalise extension names
  libraries/src/Extension/ExtensionManagerTrait.php
Labels: RTC, PR-4.2-dev

#39962 Fix TinyMCE images directory options if '/administrator/images' exists
  plugins/editors/tinymce/src/Field/UploaddirsField.php
Labels: RTC, PR-4.2-dev
