Repository joomla/joomla-cms, pull requests merged in 2023-04, with the labels that each got.

#40197 [4.3][Guided Tours] Make filter search tooltip consistent
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, PR-4.3-dev

#40280 [5.0] Remove obsolete contact and finder menu items creation from postflight method in script.php
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40283 [5.0] Remove pre-4.0.2 legacy update compatibility
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/restore_finalisation.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  build/build.php
  build/deleted_file_check.php
  build/psr12/ruleset.xml
  ruleset.xml
Labels: PR-5.0-dev

#40287 [5.0] Update versions in codemirror.xml and tinymce.xml
  plugins/editors/codemirror/codemirror.xml
  plugins/editors/tinymce/tinymce.xml
Labels: RTC, PR-5.0-dev

#40281 [5.0] Remove "updateContentTypes" method from script.php
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40293 [5.0] Chore/disable polyfill php 7.0 - 8.1
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.0-dev

#40286 [4.3] Fix SQL error "Can't Drop 'asset_id'; check that column/key exists" and checked out Guided Tours module when updating from 4.2.9 or older
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-28.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-28.sql
Labels: RTC, Release Blocker, PR-4.3-dev

#40282 [4.3] Guided Tours fix js error
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40294 [5.0] Adapt postflight method in script.php to the new major version 5
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40298 [5.0] Update deleted files and folders to changes from #40293
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40257 [4.4] Converting File class from CMS to framework package
  administrator/components/com_admin/postinstall/behindproxy.php
  administrator/components/com_admin/script.php
  administrator/components/com_banners/src/Model/TracksModel.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_languages/src/Model/OverridesModel.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  installation/src/Helper/DatabaseHelper.php
  installation/src/Model/CleanupModel.php
  libraries/src/Cache/Storage/FileStorage.php
  libraries/src/Console/UpdateCoreCommand.php
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/Installer/InstallerScript.php
  libraries/src/Language/LanguageHelper.php
  plugins/system/debug/src/Storage/FileStorage.php
  plugins/system/logrotation/logrotation.php
Labels: PR-4.4-dev

#39535 Convert mod_articles_archive to new structure
  modules/mod_articles_archive/mod_articles_archive.php
  modules/mod_articles_archive/mod_articles_archive.xml
  modules/mod_articles_archive/services/provider.php
  modules/mod_articles_archive/src/Dispatcher/Dispatcher.php
  modules/mod_articles_archive/src/Helper/ArticlesArchiveHelper.php
  tests/System/integration/site/modules/mod_articles_archive/Default.cy.js
Labels: Unit/System Tests, Updates Requested, PR-4.4-dev

#39527 Convert mod_articles_category to new structure
  modules/mod_articles_category/mod_articles_category.php
  modules/mod_articles_category/mod_articles_category.xml
  modules/mod_articles_category/services/provider.php
  modules/mod_articles_category/src/Dispatcher/Dispatcher.php
  modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
  tests/System/integration/site/modules/mod_articles_category/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40169 Convert media action plugins to service provider
  plugins/media-action/crop/crop.xml
  plugins/media-action/crop/services/provider.php
  plugins/media-action/crop/src/Extension/Crop.php
  plugins/media-action/resize/resize.xml
  plugins/media-action/resize/services/provider.php
  plugins/media-action/resize/src/Extension/Resize.php
  plugins/media-action/rotate/rotate.xml
  plugins/media-action/rotate/services/provider.php
  plugins/media-action/rotate/src/Extension/Rotate.php
  tests/System/integration/plugins/media-action/crop/CropPlugin.cy.js
  tests/System/integration/plugins/media-action/resize/ResizePlugin.cy.js
  tests/System/integration/plugins/media-action/rotate/RotatePlugin.cy.js
Labels: RTC, Unit/System Tests, PR-4.4-dev

#40173 Convert sampledata plugins to service provider
  plugins/sampledata/blog/blog.xml
  plugins/sampledata/blog/services/provider.php
  plugins/sampledata/blog/src/Extension/Blog.php
  plugins/sampledata/multilang/multilang.xml
  plugins/sampledata/multilang/services/provider.php
  plugins/sampledata/multilang/src/Extension/MultiLanguage.php
  plugins/sampledata/testing/services/provider.php
  plugins/sampledata/testing/src/Extension/Testing.php
  plugins/sampledata/testing/testing.xml
Labels: RTC, PR-4.4-dev

#40323 [4.3] Fix error from #39537 [a11y]
  administrator/components/com_installer/src/View/Update/HtmlView.php
Labels: RTC, PR-4.3-dev

#40322 [4.4] phan: Fixes to admin modules
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  administrator/modules/mod_privacy_status/src/Helper/PrivacyStatusHelper.php
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: PR-4.4-dev

#40312 [4.4] Nodeinterface: Fixing docblock
  libraries/src/Tree/NodeInterface.php
  libraries/src/Tree/NodeTrait.php
Labels: PR-4.4-dev

#40240 Adding login module test for custom user
  tests/System/integration/site/modules/mod_login/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40314 phan: Fixes to Helper classes
  libraries/src/Helper/CMSHelper.php
  libraries/src/Helper/MediaHelper.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Helper/TagsHelper.php
  libraries/src/Helper/UserGroupsHelper.php
  libraries/src/UCM/UCMContent.php
Labels: PR-4.4-dev

#40326 [4.4] login/log in action vs description
  tests/System/integration/site/modules/mod_login/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#37635 Get ordering from model in module controller
  administrator/components/com_modules/src/Controller/ModuleController.php
Labels: RTC, Small, PR-4.4-dev

#40308 [4.3][Guided Tours] Corrected string value for contact alias step
  administrator/language/en-GB/com_guidedtours.sys.ini
Labels: RTC, Language Change, PR-4.3-dev

#40300 [4.3] Guided Tours remove description of permissions fieldset
  administrator/components/com_guidedtours/config.xml
Labels: RTC, PR-4.3-dev

#40319 [4.3] Guided Tours use global language keys
  administrator/components/com_guidedtours/tmpl/steps/default.php
  administrator/components/com_guidedtours/tmpl/tours/default.php
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, PR-4.3-dev

#40301 [4.3] [a11y] Guided Tours table caption
  administrator/language/en-GB/com_guidedtours.ini
  administrator/language/en-GB/com_guidedtours.sys.ini
Labels: RTC, Language Change, PR-4.3-dev

#40318 [4.3] Guided Tours specifier %s to %d
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, PR-4.3-dev

#40313 [4.4] replace deprecated access of input property
  libraries/src/Dispatcher/ComponentDispatcherFactory.php
  libraries/src/Dispatcher/ModuleDispatcherFactory.php
  libraries/src/Factory.php
Labels: RTC, PR-4.4-dev

#40288 Guided Tours: Fix for Toggle Inline Help and Help buttons (Creating a step)
  administrator/components/com_guidedtours/src/View/Step/HtmlView.php
  administrator/components/com_guidedtours/src/View/Tour/HtmlView.php
Labels: RTC, PR-4.3-dev

#39985 [4.4] Phan: MVC classes
  libraries/src/MVC/Controller/AdminController.php
  libraries/src/MVC/Controller/ApiController.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Controller/FormController.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/Model/DatabaseAwareTrait.php
  libraries/src/MVC/Model/FormModel.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/MVC/View/AbstractView.php
  libraries/src/Table/Table.php
Labels: PR-4.4-dev

#40333 Detect the component id correctly when creating a test menu item
  tests/System/integration/site/components/com_contact/Category.cy.js
  tests/System/integration/site/components/com_contact/Featured.cy.js
  tests/System/integration/site/components/com_content/Category.cy.js
  tests/System/plugins/index.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40291 Adding login view test for com_users.
  tests/System/integration/site/components/com_users/Login.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40335 Remove hardcoded category ID in tests
  tests/System/integration/api/com_banners/Banners.cy.js
  tests/System/integration/api/com_contact/Contacts.cy.js
  tests/System/integration/api/com_content/Articles.cy.js
  tests/System/integration/site/modules/mod_articles_category/Default.cy.js
  tests/System/integration/site/modules/mod_articles_popular/Default.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40334 Cypress test to display tags in frontsite
  tests/System/integration/site/components/com_tag/Tag.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40027 [4.4] Phan: Fixing reference to Exceptions
  plugins/finder/categories/src/Extension/Categories.php
  plugins/finder/contacts/src/Extension/Contacts.php
  plugins/finder/content/src/Extension/Content.php
  plugins/finder/newsfeeds/src/Extension/Newsfeeds.php
  plugins/finder/tags/src/Extension/Tags.php
Labels: PR-4.4-dev

#40336 Remove the obsolete resync function in menu controller
  administrator/components/com_menus/src/Controller/MenusController.php
Labels: PR-5.0-dev

#40095 [4.4] Phan: Fixing banners component
  administrator/components/com_banners/src/Controller/BannersController.php
  administrator/components/com_banners/src/Controller/TracksController.php
  administrator/components/com_banners/src/Extension/BannersComponent.php
Labels: PR-4.4-dev

#40321 [4.4] phan: Fixes to com_plugins
  administrator/components/com_plugins/src/Controller/DisplayController.php
  administrator/components/com_plugins/src/Helper/PluginsHelper.php
  administrator/components/com_plugins/src/Model/PluginModel.php
  administrator/components/com_plugins/src/Model/PluginsModel.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
Labels: PR-4.4-dev

#40316 Restore cache feature in category module
  modules/mod_articles_category/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-4.4-dev

#40028 [4.4] Phan: Fixing return docblocks
  administrator/components/com_contact/src/Controller/ContactsController.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  administrator/components/com_installer/src/View/Updatesites/HtmlView.php
  administrator/components/com_languages/src/Controller/LanguagesController.php
  administrator/components/com_media/src/Controller/ApiController.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  administrator/components/com_newsfeeds/src/Controller/NewsfeedsController.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_privacy/src/View/Export/XmlView.php
  administrator/components/com_redirect/src/View/Link/HtmlView.php
  administrator/components/com_tags/src/View/Tags/HtmlView.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_workflow/src/Model/WorkflowsModel.php
  components/com_config/src/Controller/TemplatesController.php
  components/com_contact/src/View/Contact/VcfView.php
  components/com_content/src/View/Featured/FeedView.php
  components/com_tags/src/View/Tag/FeedView.php
  components/com_tags/src/View/Tags/FeedView.php
  components/com_tags/src/View/Tags/HtmlView.php
  components/com_users/src/View/Remind/HtmlView.php
  components/com_users/src/View/Reset/HtmlView.php
  libraries/loader.php
  libraries/src/Encrypt/AES/OpenSSL.php
  libraries/src/Filesystem/Stream.php
  libraries/src/Input/Cli.php
  libraries/src/Input/Input.php
Labels: PR-4.4-dev

#40348 [4.4] fix detection of sampledata testing plugin
  installation/src/Model/ConfigurationModel.php
Labels: RTC, bug, PR-4.4-dev

#40350 Fix disabled select background
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_custom-forms.scss
Labels: RTC, NPM Resource Changed, bug, PR-4.3-dev

#40362 [4.4] Spelling catagories/categories
  tests/System/integration/site/components/com_contact/Categories.cy.js
Labels: RTC, Unit/System Tests, PR-4.4-dev

#40344 Adding com_users reset view test.
  tests/System/integration/site/components/com_users/Reset.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40256 [4.4] Fixes to Form Rule classes from static code analysis
  libraries/src/Form/Rule/CalendarRule.php
  libraries/src/Form/Rule/CaptchaRule.php
  libraries/src/Form/Rule/ColorRule.php
  libraries/src/Form/Rule/CssIdentifierRule.php
  libraries/src/Form/Rule/CssIdentifierSubstringRule.php
  libraries/src/Form/Rule/EmailRule.php
  libraries/src/Form/Rule/EqualsRule.php
  libraries/src/Form/Rule/ExistsRule.php
  libraries/src/Form/Rule/FilePathRule.php
  libraries/src/Form/Rule/FolderPathExistsRule.php
  libraries/src/Form/Rule/NotequalsRule.php
  libraries/src/Form/Rule/NumberRule.php
  libraries/src/Form/Rule/OptionsRule.php
  libraries/src/Form/Rule/PasswordRule.php
  libraries/src/Form/Rule/RulesRule.php
  libraries/src/Form/Rule/SubformRule.php
  libraries/src/Form/Rule/TelRule.php
  libraries/src/Form/Rule/TimeRule.php
  libraries/src/Form/Rule/UrlRule.php
  libraries/src/Form/Rule/UsernameRule.php
Labels: bug, PR-4.4-dev

#39001 [4.4] Phan: Fix some instances of PhanTypeArraySuspicious
  administrator/components/com_admin/src/Model/HelpModel.php
  administrator/components/com_finder/src/Indexer/Helper.php
  components/com_contact/src/Model/ContactModel.php
  libraries/src/Client/FtpClient.php
  libraries/src/Document/OpensearchDocument.php
  libraries/src/Filter/InputFilter.php
Labels: bug, PR-4.4-dev

#40345 Adding com_users registration view test.
  tests/System/integration/site/components/com_users/Registration.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40244 [4.4] Fixes to Form classes from static code analysis
  libraries/src/Form/Form.php
  libraries/src/Form/FormFactoryAwareTrait.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormFilterInterface.php
  libraries/src/Form/FormHelper.php
  libraries/src/Form/FormRule.php
Labels: bug, PR-4.4-dev

#40366 Deprecate the platform define
  libraries/bootstrap.php
  libraries/cms.php
  libraries/import.legacy.php
  libraries/import.php
  tests/Unit/bootstrap.php
Labels: Unit/System Tests, PR-4.4-dev

#40331 [4.4] Phan: Fixes to com_finder
  administrator/components/com_finder/src/Indexer/Helper.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Taxonomy.php
  administrator/components/com_finder/src/Model/FilterModel.php
  administrator/components/com_finder/src/Model/FiltersModel.php
  administrator/components/com_finder/src/Model/IndexModel.php
  administrator/components/com_finder/src/Model/MapsModel.php
  administrator/components/com_finder/src/Model/SearchesModel.php
  administrator/components/com_finder/src/Service/HTML/Filter.php
  components/com_finder/src/Model/SearchModel.php
Labels: bug, PR-4.4-dev

#39552 Convert mod_articles_categories to new structure
  modules/mod_articles_categories/mod_articles_categories.php
  modules/mod_articles_categories/mod_articles_categories.xml
  modules/mod_articles_categories/services/provider.php
  modules/mod_articles_categories/src/Dispatcher/Dispatcher.php
  modules/mod_articles_categories/src/Helper/ArticlesCategoriesHelper.php
  tests/System/integration/site/modules/mod_articles_categories/Default.cy.js
Labels: New Feature, RTC, Unit/System Tests, PR-4.4-dev

#40383 Add custom module test
  tests/System/integration/site/modules/mod_custom/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40381 [4.3] Fix module toolbar save buttons
  administrator/components/com_modules/src/View/Module/HtmlView.php
Labels: RTC, Release Blocker, PR-4.3-dev

#40389 [4.3] Fix category toolbar save button
  administrator/components/com_categories/src/View/Category/HtmlView.php
Labels: RTC, Release Blocker, PR-4.3-dev

#40396 [5.0] Reimplement Joomla 4.3 fix for portable-utf8 dependency
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.0-dev

#39931 Rebuild mod_custom with new Joomla 4 structure
  modules/mod_custom/mod_custom.php
  modules/mod_custom/mod_custom.xml
  modules/mod_custom/services/provider.php
  modules/mod_custom/src/Dispatcher/Dispatcher.php
Labels: New Feature, RTC, PR-4.4-dev

#40386 Improve system tests descriptions
  tests/System/integration/administrator/components/com_categories/Categories.cy.js
  tests/System/integration/administrator/components/com_categories/Category.cy.js
  tests/System/integration/administrator/components/com_content/Article.cy.js
  tests/System/integration/administrator/components/com_content/Articles.cy.js
  tests/System/integration/administrator/components/com_fields/Field.cy.js
  tests/System/integration/administrator/components/com_fields/Fields.cy.js
  tests/System/integration/administrator/components/com_login/Login.cy.js
  tests/System/integration/administrator/components/com_menu/Menu.cy.js
  tests/System/integration/administrator/components/com_menu/MenuItem.cy.js
  tests/System/integration/administrator/components/com_menu/Menus.cy.js
  tests/System/integration/administrator/components/com_users/User.cy.js
  tests/System/integration/administrator/components/com_users/Users.cy.js
  tests/System/integration/site/components/com_contact/Categories.cy.js
  tests/System/integration/site/components/com_contact/Category.cy.js
  tests/System/integration/site/components/com_contact/Contact.cy.js
  tests/System/integration/site/components/com_contact/Featured.cy.js
  tests/System/integration/site/components/com_contact/Form.cy.js
  tests/System/integration/site/components/com_content/Category.cy.js
  tests/System/integration/site/components/com_content/Featured.cy.js
  tests/System/integration/site/components/com_newsfeed/Categories.cy.js
  tests/System/integration/site/components/com_newsfeed/Category.cy.js
  tests/System/integration/site/components/com_newsfeed/NewsFeed.cy.js
  tests/System/integration/site/components/com_tag/Tag.cy.js
  tests/System/integration/site/components/com_users/Login.cy.js
  tests/System/integration/site/components/com_users/Profile.cy.js
  tests/System/integration/site/components/com_users/Registration.cy.js
  tests/System/integration/site/components/com_users/Remind.cy.js
  tests/System/integration/site/components/com_users/Reset.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40384 Adding Edit User Profile form display test
  tests/System/integration/site/components/com_users/Profile_Edit.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40394 Adding direct logout test.
  tests/System/integration/site/components/com_users/Logout.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40402 Add a forward slash in front of the cypress visit calls
  tests/System/integration/administrator/components/com_categories/Categories.cy.js
  tests/System/integration/administrator/components/com_categories/Category.cy.js
  tests/System/integration/administrator/components/com_content/Article.cy.js
  tests/System/integration/administrator/components/com_content/Articles.cy.js
  tests/System/integration/administrator/components/com_fields/Field.cy.js
  tests/System/integration/administrator/components/com_fields/Fields.cy.js
  tests/System/integration/administrator/components/com_menu/Menu.cy.js
  tests/System/integration/administrator/components/com_menu/MenuItem.cy.js
  tests/System/integration/administrator/components/com_menu/Menus.cy.js
  tests/System/integration/administrator/components/com_users/User.cy.js
  tests/System/integration/administrator/components/com_users/Users.cy.js
  tests/System/integration/site/components/com_contact/Categories.cy.js
  tests/System/integration/site/components/com_contact/Form.cy.js
  tests/System/integration/site/components/com_newsfeed/Categories.cy.js
  tests/System/integration/site/components/com_newsfeed/Category.cy.js
  tests/System/integration/site/components/com_tag/Tag.cy.js
  tests/System/integration/site/components/com_users/Login.cy.js
  tests/System/integration/site/components/com_users/Profile.cy.js
  tests/System/integration/site/components/com_users/Profile_Edit.cy.js
  tests/System/integration/site/components/com_users/Registration.cy.js
  tests/System/integration/site/components/com_users/Remind.cy.js
  tests/System/integration/site/components/com_users/Reset.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40407 [4.4] Readme
  tests/System/README.md
Labels: Unit/System Tests, PR-4.4-dev

#40404 Adds system tests for modules
  tests/System/integration/administrator/components/com_modules/Module.cy.js
  tests/System/integration/administrator/components/com_modules/Modules.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40337 Introduce a UserFactoryAware interface
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  administrator/components/com_users/src/View/User/HtmlView.php
  libraries/src/Application/IdentityAware.php
  libraries/src/Extension/Service/Provider/MVCFactory.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/User/UserFactoryAwareInterface.php
  libraries/src/User/UserFactoryAwareTrait.php
  tests/Unit/Libraries/Cms/User/CurrentUserTraitTest.php
  tests/Unit/Libraries/Cms/User/UserFactoryAwareTraitTest.php
Labels: Unit/System Tests, PR-4.4-dev

#40437 [4.3] Delete autoload_psr4.php when update Joomla using CLI
  libraries/src/Console/UpdateCoreCommand.php
Labels: RTC, Release Blocker, bug, PR-4.3-dev

#40414 [4.3] Backporting changes from framework Input/Cookie class to CMS class
  libraries/src/Input/Cookie.php
Labels: RTC, bug, PR-4.3-dev

#40448 Tags router: do not force incorrect Itemid
  components/com_tags/src/Service/Router.php
Labels: RTC, Release Blocker, bug, PR-4.3-dev

#39628 Convert mod_related_items to new structure
  modules/mod_related_items/mod_related_items.php
  modules/mod_related_items/mod_related_items.xml
  modules/mod_related_items/services/provider.php
  modules/mod_related_items/src/Dispatcher/Dispatcher.php
  modules/mod_related_items/src/Helper/RelatedItemsHelper.php
  tests/System/integration/site/modules/mod_related_items/Default.cy.js
Labels: New Feature, Unit/System Tests, PR-4.4-dev

#40455 Tags router: unset Itemid for not matching menu, in the end of build
  components/com_tags/src/Service/Router.php
Labels: RTC, bug, PR-4.3-dev, Small

#40328 [4.4] Rebuild module Breadcrumbs with new Joomla 4 structure
  modules/mod_breadcrumbs/mod_breadcrumbs.php
  modules/mod_breadcrumbs/mod_breadcrumbs.xml
  modules/mod_breadcrumbs/services/provider.php
  modules/mod_breadcrumbs/src/Dispatcher/Dispatcher.php
  modules/mod_breadcrumbs/src/Helper/BreadcrumbsHelper.php
  tests/System/integration/site/modules/mod_breadcrumbs/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40398 [4.3] clear button in list view is not disabled when no "filter" is active
  build/media_source/system/js/searchtools.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, bug, PR-4.3-dev

#40397 [4.3 RC] Unable to toggle check status of a single updated override file using the "Checked" status icon
  build/media_source/system/js/list-view.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, bug, PR-4.3-dev

#40317 [4.4] replace deprecated joomla/string inflector
  libraries/src/MVC/Controller/FormController.php
  libraries/src/MVC/View/ListView.php
  tests/System/integration/administrator/components/com_categories/Category.cy.js
  tests/System/integration/administrator/components/com_content/Article.cy.js
Labels: Unit/System Tests, bug, PR-4.4-dev

#40385 Allow to deprecate WebAssets
  build/media_source/com_templates/joomla.asset.json
  libraries/src/Document/Renderer/Html/ScriptsRenderer.php
  libraries/src/Document/Renderer/Html/StylesRenderer.php
Labels: New Feature, NPM Resource Changed, PR-4.4-dev

#38939 [4.4] PHP8.2 Add missing class properties to views
  administrator/components/com_categories/src/View/Categories/HtmlView.php
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeeds/HtmlView.php
  administrator/components/com_tags/src/View/Tags/HtmlView.php
Labels: PHP 8.x, bug, PR-4.4-dev
