Repository joomla/joomla-cms, pull requests merged in 2023-11, with the labels that each got.

#42258 [5.0] Fix j+a shortcut in TinyMCE JoomlaHighlighter plugin
  build/media_source/plg_system_shortcut/js/shortcut.es6.js
Labels: NPM Resource Changed, bug, PR-5.0-dev, Small

#42223 [5.1] upmerge 2023-10-26
  libraries/src/Application/ConsoleApplication.php
Labels: PR-5.1-dev

#42263 [5.0] Add a todo
  build/media_source/plg_editors_tinymce/js/plugins/joomla-highlighter/plugin.es6.js
Labels: NPM Resource Changed, PR-5.0-dev

#42270 [5.1] upmerges 2023-11-01
  .appveyor.yml
  administrator/components/com_users/tmpl/users/modal.php
  build/media_source/plg_editors_tinymce/js/plugins/joomla-highlighter/plugin.es6.js
  build/media_source/plg_system_shortcut/js/shortcut.es6.js
  package-lock.json
  package.json
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
  plugins/editors/tinymce/tinymce.xml
Labels: Unit/System Tests, NPM Resource Changed, PR-5.1-dev

#42239 [4.4] Update TinyMCE to 5.10.8
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.xml
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.4-dev

#42271 [4.4] Appveyor: Raise MySQL to version 8.0
  .appveyor.yml
Labels: Unit/System Tests, PR-4.4-dev

#41983 [5.1] Redundant else usage
  administrator/components/com_templates/src/Controller/TemplateController.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  libraries/src/Event/AbstractEvent.php
Labels: Feature, RTC, PR-5.1-dev

#42275 [5.1] Fixing packaging and nightly builds
  .drone.yml
Labels: Unit/System Tests, PR-5.1-dev

#42273 [5.0] Fixing packaging and nightly builds
  .drone.yml
Labels: Unit/System Tests, PR-5.0-dev

#37320 [5.1] Add Global Setting for Form Layout option to custom fields
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  administrator/language/en-GB/com_fields.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/plg_fields_list.ini
  administrator/language/en-GB/plg_fields_sql.ini
  plugins/fields/integer/integer.xml
  plugins/fields/integer/params/integer.xml
  plugins/fields/list/list.xml
  plugins/fields/list/params/list.xml
  plugins/fields/radio/params/radio.xml
  plugins/fields/radio/radio.xml
  plugins/fields/sql/params/sql.xml
  plugins/fields/sql/sql.xml
Labels: Feature, RTC, Language Change, PR-5.1-dev

#41854 [5.1] Add SVG support to mod_banners
  components/com_banners/src/Helper/BannerHelper.php
  modules/mod_banners/tmpl/default.php
Labels: Feature, RTC, PR-5.1-dev

#42244 [5.1] Add Tag Relationship in ContentSerializer.php
  api/components/com_content/src/Serializer/ContentSerializer.php
Labels: Feature, Webservices, PR-5.0-dev, PR-5.1-dev

#42278 Revert changes in header block from PR #42244
  api/components/com_content/src/Serializer/ContentSerializer.php
Labels: PR-5.1-dev

#42274 [4.4] Drone: Renaming build script
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#41937 Fix for Finder (Smart Search) indexer removing spaces in long strings
  administrator/components/com_finder/src/Indexer/Parser.php
Labels: RTC, bug, PR-4.4-dev

#42199 fix #42191 Unknown column 'id' in 'field list'
  libraries/src/Installer/InstallerScript.php
Labels: RTC, bug, PR-4.4-dev

#41296 [4.4] com_tags extra parent_id query var
  components/com_tags/src/Service/Router.php
Labels: RTC, bug, PR-4.4-dev

#41358 Fix new J4 components missing assets
  administrator/components/com_admin/script.php
Labels: bug, PR-4.4-dev

#42253 Fix multi-factor migration when updating from J3 to J4
  libraries/src/Application/MultiFactorAuthenticationHandler.php
Labels: RTC, PR-4.4-dev

#42294 [5.0] Cassiopeia should respect inheritance
  templates/cassiopeia/component.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
  templates/cassiopeia/offline.php
Labels: RTC, bug, PR-5.0-dev

#42285 [5.0] Filter values of custom field, fix #42259
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
Labels: RTC, bug, PR-5.0-dev

#42309 [5.1] upmerges 2023-11-07
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  templates/cassiopeia/component.php
  templates/cassiopeia/error.php
  templates/cassiopeia/index.php
  templates/cassiopeia/offline.php
Labels: PR-5.1-dev

#42306 [5.0] Fix tinymce error on mobile
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.0-dev

#42316 Fix missing archive icon
  administrator/components/com_content/tmpl/articles/modal.php
Labels: RTC, bug, PR-4.4-dev

#42166 [5.1] Cleanup input options
  libraries/src/Application/ConsoleApplication.php
Labels: Feature, RTC, PR-5.1-dev

#42284 [4] Saving User Profile logs you out of the backend
  components/com_users/src/Controller/ProfileController.php
  components/com_users/src/Model/ProfileModel.php
Labels: RTC, bug, PR-4.4-dev

#42323 Fix field Color (Simple) rendering
  build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#42325 [4.x] Improve CSS/JS build times
  build/build-modules-js/error-pages.es6.js
  build/build-modules-js/init/exemptions/tinymce.es6.js
  build/build-modules-js/init/minify-vendor.es6.js
  build/build-modules-js/javascript/build-bootstrap-js.es6.js
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/build-modules-js/javascript/minify.es6.js
  build/build-modules-js/stylesheets/handle-css.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/media_source/com_media/scss/components/_layout.scss
  build/media_source/system/css/sortablelist.css
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-4.4-dev

#42331 [4.4] Node 20
  .drone.yml
  README.md
  build/build.js
  package-lock.json
  package.json
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: NPM Resource Changed, PR-4.4-dev

#42330 Fix table multiselect
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/multiselect.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#42332 Fix list select (with choicesjs) losing values in subform
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#42282 Update BannerHelper.php with better deprecation information
  components/com_banners/src/Helper/BannerHelper.php
Labels: bug, PR-5.1-dev

#42341 [4.x] Don't force the process to terminate
  build/build-modules-js/compilecss.es6.js
  build/build-modules-js/compilejs.es6.js
  build/build-modules-js/error-pages.es6.js
  build/build-modules-js/init/cleanup-media.es6.js
  build/build-modules-js/javascript/build-bootstrap-js.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/build.js
Labels: NPM Resource Changed, PR-4.4-dev

#42293 [5.1] Use Dialog field for Modal_Category
  administrator/components/com_categories/layouts/joomla/form/field/modal-select/extra-buttons.php
  administrator/components/com_categories/src/Controller/CategoryController.php
  administrator/components/com_categories/src/Field/Modal/CategoryField.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_categories/tmpl/category/modal.php
  administrator/components/com_categories/tmpl/category/modalreturn.php
Labels: Feature, RTC, PR-5.1-dev

#42326 [5.1] Use Dialog field for Modal_Contact
  administrator/components/com_contact/contact.xml
  administrator/components/com_contact/layouts/joomla/form/field/modal-select/extra-buttons.php
  administrator/components/com_contact/src/Controller/ContactController.php
  administrator/components/com_contact/src/Field/Modal/ContactField.php
  administrator/components/com_contact/src/View/Contact/HtmlView.php
  administrator/components/com_contact/tmpl/contact/modal.php
  administrator/components/com_contact/tmpl/contact/modalreturn.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  build/media_source/com_contact/joomla.asset.json
  build/media_source/com_contact/js/admin-contacts-modal.es6.js
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42327 [5.1] Use Dialog field for Modal_Newsfeed
  administrator/components/com_newsfeeds/layouts/joomla/form/field/modal-select/extra-buttons.php
  administrator/components/com_newsfeeds/newsfeeds.xml
  administrator/components/com_newsfeeds/src/Controller/NewsfeedController.php
  administrator/components/com_newsfeeds/src/Field/Modal/NewsfeedField.php
  administrator/components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  administrator/components/com_newsfeeds/tmpl/newsfeed/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeed/modalreturn.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
Labels: Feature, RTC, PR-5.1-dev

#40528 [4.4] str_replace() on NULL in Joomla\CMS\Uri\Uri::isInternal()
  administrator/components/com_installer/src/Controller/UpdateController.php
Labels: RTC, PHP 8.x, bug, PR-4.4-dev

#42030 [4.4] translation description text static error pages
  build/warning_page/template.js
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: RTC, bug, PR-4.4-dev

#41543 Text::script should update existing script strings
  libraries/src/Language/Text.php
Labels: RTC, bug, PR-4.4-dev

#42345 [5.0] Upmerge 2023-11-12
  .drone.yml
  README.md
  administrator/components/com_admin/script.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_finder/src/Indexer/Parser.php
  administrator/components/com_media/config.xml
  api/components/com_content/src/Controller/ArticlesController.php
  build/build-modules-js/error-pages.es6.js
  build/build-modules-js/init/minify-vendor.es6.js
  build/build-modules-js/javascript/build-bootstrap-js.es6.js
  build/build-modules-js/javascript/build-codemirror.es6.js
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/build-modules-js/javascript/minify.es6.js
  build/build-modules-js/stylesheets/handle-css.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/build.js
  build/media_source/com_media/scss/components/_layout.scss
  build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js
  components/com_tags/src/Service/Router.php
  components/com_tags/tmpl/tag/default.php
  components/com_tags/tmpl/tag/list.php
  components/com_users/src/Controller/ProfileController.php
  components/com_users/src/Model/ProfileModel.php
  includes/incompatible.html
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Application/MultiFactorAuthenticationHandler.php
  libraries/src/Installer/InstallerScript.php
  libraries/src/Workflow/Workflow.php
  modules/mod_related_items/tmpl/default.php
  package-lock.json
  package.json
  plugins/content/joomla/src/Extension/Joomla.php
  plugins/fields/list/src/Extension/ListPlugin.php
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: Unit/System Tests, NPM Resource Changed, PR-5.0-dev

#39490 Admin Articles View - Execute transition button permissions fixed
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_content/tmpl/articles/default.php
Labels: RTC, bug, PR-4.4-dev

#42350 [5.0]Spelling templates
  build/layouts/github.php
Labels: RTC, PR-5.0-dev

#42348 [5.0] spelling descending
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: RTC, Unit/System Tests, PR-5.0-dev

#42349 [5.0] Spelling mismatch
  administrator/components/com_media/resources/scripts/store/state.es6.js
Labels: RTC, NPM Resource Changed, PR-5.0-dev

#42340 [4.4] Use .env files for the node tools
  build/development.env
  build/production.env
  package.json
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#42328 [5.1] Use Dialog for Batch windows
  administrator/components/com_banners/src/View/Banners/HtmlView.php
  administrator/components/com_banners/tmpl/banners/default.php
  administrator/components/com_banners/tmpl/banners/default_batch_body.php
  administrator/components/com_banners/tmpl/banners/default_batch_footer.php
  administrator/components/com_contact/src/View/Contacts/HtmlView.php
  administrator/components/com_contact/tmpl/contacts/default.php
  administrator/components/com_contact/tmpl/contacts/default_batch_body.php
  administrator/components/com_contact/tmpl/contacts/default_batch_footer.php
  administrator/components/com_fields/src/View/Fields/HtmlView.php
  administrator/components/com_fields/src/View/Groups/HtmlView.php
  administrator/components/com_fields/tmpl/fields/default.php
  administrator/components/com_fields/tmpl/fields/default_batch_body.php
  administrator/components/com_fields/tmpl/fields/default_batch_footer.php
  administrator/components/com_fields/tmpl/groups/default.php
  administrator/components/com_fields/tmpl/groups/default_batch_body.php
  administrator/components/com_fields/tmpl/groups/default_batch_footer.php
  administrator/components/com_menus/src/View/Items/HtmlView.php
  administrator/components/com_menus/tmpl/items/default.php
  administrator/components/com_menus/tmpl/items/default_batch_body.php
  administrator/components/com_menus/tmpl/items/default_batch_footer.php
  administrator/components/com_modules/src/View/Modules/HtmlView.php
  administrator/components/com_modules/tmpl/modules/default.php
  administrator/components/com_modules/tmpl/modules/default_batch_body.php
  administrator/components/com_modules/tmpl/modules/default_batch_footer.php
  administrator/components/com_newsfeeds/src/View/Newsfeeds/HtmlView.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default_batch_body.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/default_batch_footer.php
  administrator/components/com_tags/src/View/Tags/HtmlView.php
  administrator/components/com_tags/tmpl/tags/default.php
  administrator/components/com_tags/tmpl/tags/default_batch_body.php
  administrator/components/com_tags/tmpl/tags/default_batch_footer.php
  administrator/components/com_users/src/View/Users/HtmlView.php
  administrator/components/com_users/tmpl/users/default.php
  administrator/components/com_users/tmpl/users/default_batch_body.php
  administrator/components/com_users/tmpl/users/default_batch_footer.php
  build/media_source/com_fields/js/admin-fields-default-batch.es6.js
Labels: Feature, RTC, PR-5.1-dev

#41431 Fix a bug of web assets file joomla.asset.json registration/parsing
  libraries/src/WebAsset/WebAssetRegistry.php
Labels: RTC, bug, PR-4.4-dev

#42180 [5.0] Fix legacy table creation
  libraries/src/Table/Table.php
Labels: RTC, PR-5.0-dev

#42360 [5.0] upmerge 2023-11-18
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_installer/src/Controller/UpdateController.php
  build/build-modules-js/compilecss.es6.js
  build/build-modules-js/compilejs.es6.js
  build/build-modules-js/error-pages.es6.js
  build/build-modules-js/init/cleanup-media.es6.js
  build/build-modules-js/javascript/build-bootstrap-js.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/build.js
  build/development.env
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
  build/media_source/system/js/multiselect.es6.js
  build/production.env
  build/warning_page/template.js
  includes/incompatible.html
  libraries/src/Language/Text.php
  libraries/src/WebAsset/WebAssetRegistry.php
  package-lock.json
  package.json
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: NPM Resource Changed, PR-5.0-dev

#42322 [5.0] Add basic support for conditional dark mode themes in our editors
  administrator/language/en-GB/plg_editors_tinymce.ini
  administrator/templates/atum/index.php
  build/media_source/plg_editors_codemirror/css/codemirror.css
  build/media_source/plg_editors_codemirror/js/codemirror.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  package-lock.json
  package.json
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-5.0-dev

#42346 [5.0] Fix URLs and hardcoded keyName for editing URL, in ModalSelectField
  build/media_source/system/js/fields/modal-content-select-field.es6.js
  layouts/joomla/form/field/modal-select/buttons.php
Labels: RTC

#42336 Declare the context variable correctly
  plugins/workflow/publishing/src/Extension/Publishing.php
Labels: RTC, bug, PR-4.4-dev

#42364 [5.1] Update deleted files list in script.php for 5.1.0-alpha1
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#42369 [5.0] Fix sass-embedded dependencies
  package-lock.json
Labels: NPM Resource Changed, PR-5.0-dev

#42359 [4.4] TinyMCE 5.10.9
  package-lock.json
  plugins/editors/tinymce/tinymce.xml
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#42392 [5.0] Revert TinyMCE builder dark skin
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
Labels: RTC, bug, PR-5.0-dev

#42388 [5.0] revert string removal
  administrator/language/en-GB/com_users.ini
Labels: RTC, Language Change, bug, PR-5.0-dev

#42389 [5.0] Correct language string workflows
  administrator/components/com_workflow/src/Table/WorkflowTable.php
Labels: RTC, bug, PR-5.0-dev

#42398 5.1.0 not 5.1.1 yet
  libraries/src/Version.php
Labels: PR-5.1-dev

#42400 [5.1] upmerges 2023-11-25
  administrator/components/com_workflow/src/Table/WorkflowTable.php
  administrator/language/en-GB/com_users.ini
  administrator/manifests/files/joomla.xml
  layouts/plugins/editors/tinymce/field/tinymcebuilder.php
  libraries/src/Version.php
Labels: Language Change, PR-5.1-dev

#42425 [4.4] Broken language comment
  administrator/language/en-GB/mod_menu.ini
  administrator/language/en-GB/plg_fields_imagelist.ini
Labels: RTC, Language Change, PR-4.4-dev

#42390 [5.1] Workflows missing strings
  administrator/language/en-GB/com_workflow.ini
Labels: RTC, Language Change, bug, PR-5.1-dev

#38588 [5.1][com_actionlog] synch extension to log with email notification
  administrator/components/com_actionlogs/src/Field/UserlogtypeField.php
  plugins/system/actionlogs/forms/actionlogs.xml
  plugins/system/actionlogs/src/Extension/ActionLogs.php
Labels: Feature, RTC, PR-5.1-dev
