Repository joomla/joomla-cms, pull requests merged in 2023-03, with the labels that each got.

#39932 Email Cloaking fires when @ in filename (image) #39786
  plugins/content/emailcloak/emailcloak.php
Labels: RTC, PR-4.2-dev, Small

#39976 [4.3] Smart Search: Fixing toolbar button name
  administrator/components/com_finder/src/View/Index/HtmlView.php
Labels: RTC, PR-4.3-dev

#39937 [4][sql] banners.clickurl varchar(2048)
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-25.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-25.sql
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
Labels: RTC, PR-4.3-dev

#39922 [4.3] fix media manager breadcrumb
  administrator/components/com_media/resources/scripts/components/breadcrumb/breadcrumb.vue
  administrator/components/com_media/resources/scripts/components/browser/table/table.vue
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#39919 [4.3] Smart Search: Hiding language taxonomy without multilanguage enabled
  components/com_finder/tmpl/search/default_result.php
Labels: RTC, PR-4.3-dev, Small

#39996 Updating 4.3-dev with changes from 4.2-dev
  administrator/components/com_fields/src/Controller/FieldsController.php
  administrator/components/com_fields/src/Controller/GroupsController.php
  administrator/components/com_installer/tmpl/discover/emptystate.php
  administrator/components/com_modules/layouts/joomla/form/field/modulespositionedit.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/language/en-GB/com_modules.ini
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  components/com_users/src/Controller/RegistrationController.php
  language/en-GB/joomla.ini
  libraries/src/Application/ApplicationHelper.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CMSWebApplicationInterface.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Extension/ExtensionManagerTrait.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/HTML/Helpers/Grid.php
  libraries/src/Menu/AbstractMenu.php
  libraries/src/Serializer/JoomlaSerializer.php
  plugins/authentication/joomla/src/Extension/Joomla.php
  plugins/content/emailcloak/src/Extension/EmailCloak.php
  plugins/editors/tinymce/src/Field/UploaddirsField.php
Labels: Test instructions missing, Language Change, PR-4.3-dev

#39999 [4.3] Update deleted files and folders lists in script.php for upcoming 4.3.0-beta4
  administrator/components/com_admin/script.php
  components/com_contact/layouts/field/render.php
Labels: PR-4.3-dev

#39944 [4.3] Smart Search: Don't republish items upon save
  administrator/components/com_finder/src/Indexer/Adapter.php
Labels: RTC, PR-4.3-dev

#39938 Fixing URL to contact VCF
  components/com_contact/tmpl/contact/default.php
Labels: RTC, PR-4.2-dev

#39875 Update dependencies
  composer.json
  composer.lock
  package-lock.json
  package.json
  plugins/editors/codemirror/codemirror.xml
Labels: RTC, Composer Dependency Changed, NPM Resource Changed, PR-4.3-dev

#39989 [4.3] Remove an extra space on the XTD-article
  build/media_source/com_content/js/admin-articles-modal.es6.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39973 Improve Finder ajax error handling
  administrator/components/com_finder/tmpl/indexer/default.php
  build/media_source/com_finder/js/finder.es6.js
  build/media_source/com_finder/js/indexer.es6.js
  components/com_finder/tmpl/search/default_form.php
  modules/mod_finder/tmpl/default.php
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39957 [plgTinyMCE] Error correction. Now you can drag and drop images into the material so that the image is saved to a custom directory.
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js
Labels: RTC, NPM Resource Changed, PR-4.2-dev

#39435 [4][com_actionlog] - log event reset password
  components/com_users/src/Model/ResetModel.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
Labels: RTC, PR-4.2-dev

#39953 [5.0] Updating wamania/php-stemmer to 3.0.0
  composer.json
  composer.lock
Labels: Composer Dependency Changed, Maintainers Checked, PR-5.0-dev

#39205 Don't append but set the "Content-Encoding" header value in htaccess.txt
  administrator/components/com_admin/postinstall/htaccesssetce.php
  administrator/components/com_admin/sql/updates/mysql/4.2.9-2023-03-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.2.9-2023-03-07.sql
  administrator/language/en-GB/com_admin.ini
  htaccess.txt
Labels: RTC, Language Change, Documentation Required, PR-4.2-dev, Small

#39998 [4.2] Update deleted files and folders lists in script.php for upcoming 4.2.9
  administrator/components/com_admin/script.php
Labels: Release Blocker, PR-4.2-dev

#39920 Hide promotion in TinyMCE
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-5.0-dev, Small

#39524 [5.0] Remove all return type will change annotations
  administrator/components/com_users/src/DataShape/DataShapeObject.php
  libraries/src/Date/Date.php
  libraries/src/Document/JsonapiDocument.php
  libraries/src/Feed/Feed.php
Labels: PR-5.0-dev, Small

#39058 [4.3] Fixing php compatibility issues 3
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/language/en-GB/com_joomlaupdate.ini
  installation/language/en-GB/joomla.ini
  installation/src/Model/ChecksModel.php
Labels: Language Change, PR-4.3-dev, PR-5.0-dev, Small

#39955 [4.3] PHP8.2: Updating voku/portable-utf8
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-4.3-dev

#40004 [4.3][Guided Tours] Cleanup Steps model
  administrator/components/com_guidedtours/src/Model/StepsModel.php
Labels: RTC, PR-4.3-dev

#39990 [4.3] Phan: Fixing method signature mismatch
  administrator/components/com_content/src/Controller/FeaturedController.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_installer/src/View/Languages/HtmlView.php
  administrator/components/com_languages/src/Model/LanguagesModel.php
  administrator/components/com_mails/src/Model/TemplatesModel.php
  administrator/components/com_menus/src/Model/MenusModel.php
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_tags/src/Model/TagsModel.php
  administrator/components/com_workflow/src/Model/StagesModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowsModel.php
  components/com_contact/src/Model/FeaturedModel.php
  components/com_tags/src/Model/TagModel.php
  components/com_tags/src/Model/TagsModel.php
Labels: PR-4.3-dev

#39984 [4.3] Phan: Optimizing import statements
  administrator/components/com_banners/tmpl/download/default.php
  administrator/components/com_contact/src/Service/HTML/Icon.php
  administrator/components/com_content/src/Extension/ContentComponent.php
  administrator/components/com_content/src/Service/HTML/Icon.php
  administrator/components/com_fields/src/Model/GroupsModel.php
  administrator/components/com_installer/src/View/Database/HtmlView.php
  administrator/components/com_installer/src/View/Discover/HtmlView.php
  administrator/components/com_installer/src/View/Install/HtmlView.php
  administrator/components/com_installer/src/View/Languages/HtmlView.php
  administrator/components/com_installer/src/View/Manage/HtmlView.php
  administrator/components/com_installer/src/View/Update/HtmlView.php
  administrator/components/com_installer/src/View/Updatesites/HtmlView.php
  administrator/components/com_installer/src/View/Warnings/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/update/finaliseconfirm.php
  administrator/components/com_joomlaupdate/tmpl/upload/captive.php
  administrator/components/com_mails/src/View/Templates/HtmlView.php
  administrator/components/com_messages/src/Model/ConfigModel.php
  administrator/components/com_templates/tmpl/template/default.php
  api/components/com_languages/src/Controller/StringsController.php
  build/psr12/phpcs.joomla.report.php
  components/com_content/src/Model/CategoryModel.php
  components/com_tags/src/View/Tag/FeedView.php
  installation/src/Application/CliInstallationApplication.php
  installation/src/Console/InstallCommand.php
  installation/src/Service/Provider/Application.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Console/CleanCacheCommand.php
  libraries/src/Console/ListUserCommand.php
  libraries/src/Document/HtmlDocument.php
  libraries/src/Helper/AuthenticationHelper.php
  libraries/src/MVC/Controller/FormController.php
  libraries/src/String/PunycodeHelper.php
  modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
  modules/mod_breadcrumbs/tmpl/default.php
  plugins/captcha/recaptcha_invisible/src/Extension/InvisibleReCaptcha.php
  plugins/content/joomla/joomla.php
  plugins/editors/tinymce/src/PluginTraits/ActiveSiteTemplate.php
  plugins/system/cache/src/Extension/Cache.php
  plugins/system/webauthn/src/Authentication.php
  plugins/system/webauthn/src/Extension/Webauthn.php
  plugins/system/webauthn/src/MetadataRepository.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerChallenge.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerCreate.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerDelete.php
  templates/cassiopeia/offline.php
  templates/system/offline.php
  tests/Integration/Plugin/Authentication/Ldap/LdapPluginTest.php
  tests/Unit/Libraries/Cms/Feed/FeedFactoryTest.php
Labels: RTC, PR-4.3-dev

#39310 [5.0] Fix class name in Webauthn plugin
  plugins/system/webauthn/src/MetadataRepository.php
Labels: bug, PR-5.0-dev, Small

#39304 [5.0] Remove leftover code in PSR logger
  libraries/src/Log/DelegatingPsrLogger.php
Labels: PR-5.0-dev, Small

#40053 [4.3] guided tours codestyle
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40003 [4.3][Guided Tours] Cleanup Tours model
  administrator/components/com_guidedtours/src/Model/ToursModel.php
Labels: RTC, PR-4.3-dev

#40016 [4.3][GUIDEDTOURS] Cleanup Step model
  administrator/components/com_guidedtours/src/Model/StepModel.php
Labels: RTC, PR-4.3-dev

#40045 [4.3][Guided Tours] Hide 'Take a tour' on small devices
  administrator/modules/mod_guidedtours/tmpl/default.php
Labels: RTC, PR-4.3-dev

#40014 [4.3][GUIDEDTOURS] Cleanup Tour model
  administrator/components/com_guidedtours/src/Model/TourModel.php
Labels: RTC, PR-4.3-dev

#40048 In com_tags, a tagged element's text-variable is transformed into nul…
  components/com_tags/src/View/Tag/HtmlView.php
Labels: PR-4.3-dev

#40015 [4.3][GUIDEDTOURS] Move code from helper to model
  administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
Labels: RTC, PR-4.3-dev

#40017 [4.3] Allow module Helper optional
  libraries/src/Extension/Module.php
  libraries/src/Extension/Service/Provider/Module.php
Labels: RTC, PR-4.3-dev

#40071 [4.4] set the correct version number for 4.4
  README.md
  README.txt
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  build.xml
  installation/language/en-GB/langmetadata.xml
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Version.php
Labels: Language Change, PR-4.4-dev

#40075 [4.3] Readme bump branch
  README.md
Labels: PR-4.3-dev

#40038 Create front end cypress tests
  cypress.config.dist.js
  package-lock.json
  package.json
  tests/cypress/integration/site/components/com_content/Category.cy.js
  tests/cypress/integration/site/components/com_content/Featured.cy.js
  tests/cypress/integration/site/general.cy.js
  tests/cypress/integration/site/modules/mod_login/Default.cy.js
  tests/cypress/support/commands.js
  tests/cypress/support/commands/db.js
  tests/cypress/support/index.js
Labels: Unit/System Tests, NPM Resource Changed, PR-4.4-dev

#40076 Lints the cypress system tests
  build/.eslintrc
  package.json
  tests/cypress/integration/administrator/components/com_content/ContentCategoryList.cy.js
  tests/cypress/integration/administrator/components/com_content/ContentFieldList.cy.js
  tests/cypress/integration/administrator/components/com_content/ContentList.cy.js
  tests/cypress/integration/administrator/components/com_menu/Menu.cy.js
  tests/cypress/integration/administrator/components/com_users/UserList.cy.js
  tests/cypress/integration/administrator/general.cy.js
  tests/cypress/integration/install/install.cy.js
  tests/cypress/integration/site/components/com_content/Category.cy.js
  tests/cypress/integration/site/components/com_content/Featured.cy.js
  tests/cypress/integration/site/modules/mod_login/Default.cy.js
Labels: Unit/System Tests, NPM Resource Changed, PR-4.4-dev

#40063 [4.3][Guided Tours] Remove unnecessary title generation on copy or duplicate
  administrator/components/com_guidedtours/src/Model/StepModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
Labels: RTC, PR-4.3-dev

#40084 [5]Update composer dependencies
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.0-dev

#40060 [4.3] Revert 38576
  administrator/components/com_tags/src/Table/TagTable.php
  administrator/language/en-GB/com_tags.ini
  libraries/src/Table/ContentType.php
Labels: RTC, Language Change, Release Blocker, PR-4.3-dev

#40077 [4.3][Guided Tours] target corrections
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-10.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-10.sql
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40062 [4.3][Guided Tours] When the input field has a value, enable the 'Next' button
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40000 [4.3][Guided Tours] Fixed News Feed tour and User tour target
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-09.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-09.sql
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
Labels: RTC, PR-4.3-dev

#40037 [4.3][Guided Tours] Plugin registers events only under administrator
  plugins/system/guidedtours/services/provider.php
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: RTC, PR-4.3-dev

#40044 [4.3][Guided Tours] Editors should be accessible with tabs
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-07.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-07.sql
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40054 [4.3][Guided Tours] Administrator console unresponsive when CSS selector is invalid
  administrator/language/en-GB/plg_system_guidedtours.ini
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: RTC, Language Change, NPM Resource Changed, PR-4.3-dev

#40034 [4.3][Guided Tours] Tour Edit: Enforce value in extensions
  administrator/components/com_guidedtours/forms/tour.xml
Labels: RTC, PR-4.3-dev

#40074 [4.3] Shortcuts styling
  build/media_source/plg_system_shortcut/js/shortcut.es6.js
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40078 [4.3] Fix banner pinned tooltip to show the action to perform
  administrator/components/com_banners/src/Service/Html/Banner.php
  administrator/language/en-GB/com_banners.ini
Labels: RTC, Language Change, PR-4.3-dev

#40070 [4.3] php-diff line endings
  administrator/components/com_templates/tmpl/template/default.php
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-4.3-dev

#40080 Fix domain checking for request
  build/media_source/system/js/core.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, PR-4.3-dev

#40089 [4.3] Update deleted files and folders lists in script.php for upcoming 4.3.0-rc1
  administrator/components/com_admin/script.php
Labels: PR-4.3-dev

#39983 [4.3] Phan: Languagefilter plugin
  plugins/system/languagefilter/languagefilter.php
Labels: RTC, PR-4.3-dev

#39986 [4.3] Phan: Language classes
  libraries/src/Language/Language.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/Language/Multilanguage.php
  libraries/src/Language/Text.php
  libraries/src/Layout/FileLayout.php
Labels: RTC, PR-4.3-dev

#40098 Move db setup code to plugins file
  cypress.config.dist.js
  tests/cypress/plugins/.gitkeep
  tests/cypress/plugins/index.js
Labels: Unit/System Tests, PR-4.4-dev

#40100 Track inserted items and delete them when test has finished
  tests/cypress/integration/site/components/com_content/Category.cy.js
  tests/cypress/integration/site/components/com_content/Featured.cy.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands/db.js
  tests/cypress/support/index.js
Labels: Unit/System Tests, PR-4.4-dev

#40102 Add mod_articles_news system test
  tests/cypress/integration/site/modules/mod_articles_news/Default.cy.js
  tests/cypress/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#39968 PHP polyfills as explicit dependency
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.2-dev

#40114 Add mod_footer system test
  tests/cypress/integration/site/modules/mod_footer/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40113 [4.4] Converting from File::exists() to is_file()
  administrator/components/com_admin/script.php
  administrator/components/com_config/src/Field/ConfigComponentsField.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_contenthistory/src/Helper/ContenthistoryHelper.php
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/finalisation.php
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_postinstall/src/Controller/MessageController.php
  administrator/components/com_postinstall/src/Model/MessagesModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  components/com_config/tmpl/modules/default.php
  installation/src/Helper/DatabaseHelper.php
  libraries/src/Log/Logger/FormattedtextLogger.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
  plugins/system/tasknotification/tasknotification.php
Labels: PR-4.4-dev

#40092 [4.4] Rebuild mod_users_latest with new Joomla 4 structure
  modules/mod_users_latest/mod_users_latest.php
  modules/mod_users_latest/mod_users_latest.xml
  modules/mod_users_latest/services/provider.php
  modules/mod_users_latest/src/Dispatcher/Dispatcher.php
  modules/mod_users_latest/src/Helper/UsersLatestHelper.php
  tests/cypress/integration/site/modules/mod_users_latest/Default.cy.js
  tests/cypress/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40143 [4.4] Make UsersLatestHelper backward compatible
  modules/mod_users_latest/src/Dispatcher/Dispatcher.php
  modules/mod_users_latest/src/Helper/UsersLatestHelper.php
Labels: PR-4.4-dev

#40154 Cypress test for featured com_contact.
  tests/cypress/integration/site/components/com_contact/Featured.cy.js
  tests/cypress/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40158 Cypress test for Category com_contact
  tests/System/integration/site/components/com_contact/Category.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40109 Add deprecation message for user aid property
  libraries/src/User/User.php
Labels: RTC, PR-4.4-dev

#40110 Add deprecation message for user item_associations property
  libraries/src/Application/WebApplication.php
Labels: PR-4.4-dev

#40156 [4.4] Add text deprecated version + description to actual status in module helper
  modules/mod_articles_latest/src/Helper/ArticlesLatestHelper.php
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
  modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php
  modules/mod_users_latest/src/Helper/UsersLatestHelper.php
Labels: RTC, PR-4.4-dev

#40118 [4.3][Guided Tours] Fix DESCRIPTION: search
  administrator/components/com_guidedtours/src/Model/StepsModel.php
  administrator/components/com_guidedtours/src/Model/ToursModel.php
Labels: RTC, PR-4.3-dev

#40162 Updating 4.3-dev with changes from 4.2-dev
  composer.json
  composer.lock
Labels: Test instructions missing, Composer Dependency Changed, PR-4.3-dev

#40165 [4.4] Update Featured.cy.js
  tests/System/integration/site/components/com_content/Featured.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40166 Test for not featured contacts
  tests/System/integration/site/components/com_contact/Featured.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40066 [4.4] Rebuild mod_footer with new Joomla 4 structure
  modules/mod_footer/mod_footer.php
  modules/mod_footer/mod_footer.xml
  modules/mod_footer/services/provider.php
  modules/mod_footer/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-4.4-dev

#40170 [5.0] Remove obsolete dropUtf8ConversionTable function from script.php
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40146 Convert installer plugins to service providers
  cypress.config.dist.js
  plugins/installer/folderinstaller/folderinstaller.xml
  plugins/installer/folderinstaller/services/provider.php
  plugins/installer/folderinstaller/src/Extension/FolderInstaller.php
  plugins/installer/folderinstaller/tmpl/default.php
  plugins/installer/override/override.xml
  plugins/installer/override/services/provider.php
  plugins/installer/override/src/Extension/Override.php
  plugins/installer/packageinstaller/packageinstaller.xml
  plugins/installer/packageinstaller/services/provider.php
  plugins/installer/packageinstaller/src/Extension/PackageInstaller.php
  plugins/installer/packageinstaller/tmpl/default.php
  plugins/installer/urlinstaller/services/provider.php
  plugins/installer/urlinstaller/src/Extension/UrlInstaller.php
  plugins/installer/urlinstaller/tmpl/default.php
  plugins/installer/urlinstaller/urlinstaller.xml
  plugins/installer/webinstaller/services/provider.php
  plugins/installer/webinstaller/src/Extension/WebInstaller.php
  plugins/installer/webinstaller/webinstaller.xml
  tests/System/integration/plugins/installer/folderinstaller/FolderInstallerPlugin.cy.js
  tests/System/integration/plugins/installer/packageinstaller/PackageInstallerPlugin.cy.js
  tests/System/integration/plugins/installer/urlinstaller/UrlInstallerPlugin.cy.js
  tests/System/integration/plugins/installer/webinstaller/WebInstallerPlugin.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40175 [4.4] Cypress Update README.md
  tests/System/README.md
Labels: Unit/System Tests, PR-4.4-dev

#40171 Cypress test for contact form in com_contact.
  tests/System/integration/site/components/com_contact/Contact.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40142 [4.4] Rebuild plugin PageNavigation with new Joomla 4 structure
  plugins/content/pagenavigation/pagenavigation.xml
  plugins/content/pagenavigation/services/provider.php
  plugins/content/pagenavigation/src/Extension/PageNavigation.php
Labels: RTC, PR-4.4-dev

#40183 Add cypress com_banners test
  tests/System/integration/site/modules/mod_banners/Default.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40179 [4.4] Cypress small update README.md (2)
  tests/System/README.md
Labels: Unit/System Tests, PR-4.4-dev

#40111 [4.4] Deprecating CMS Filesystem package
  libraries/src/Filesystem/File.php
  libraries/src/Filesystem/FilesystemHelper.php
  libraries/src/Filesystem/Folder.php
  libraries/src/Filesystem/Patcher.php
  libraries/src/Filesystem/Path.php
  libraries/src/Filesystem/Stream.php
  libraries/src/Filesystem/Streams/StreamString.php
  libraries/src/Filesystem/Support/StringController.php
Labels: PR-4.4-dev

#40189 [4.4] Cypress test for popular articles in mod_articles_popular
  tests/System/integration/site/modules/mod_articles_popular/Default.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#40194 Fix incorrect HTML rendering
  administrator/templates/atum/html/layouts/status.php
Labels: RTC, PR-4.3-dev

#40203 Add ATT Codeowner (#40203
  .github/CODEOWNERS
Labels: PR-4.3-dev

#40161 [4.3] Remove redundant assignment
  libraries/src/Form/Field/ImagelistField.php
Labels: RTC, PR-4.3-dev

#40192 [4.3] Revert CSP related changes in Grid.php (back to inline scripts)
  libraries/src/HTML/Helpers/Grid.php
Labels: RTC, PR-4.3-dev

#40214 [4.3] Guided Tours Caption [a11y]
  administrator/components/com_guidedtours/tmpl/steps/default.php
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, PR-4.3-dev

#40204 [4.4] Make code consistent, change <folder>services</folder> to <folder>src</folder>
  modules/mod_articles_news/mod_articles_news.xml
  plugins/multifactorauth/email/email.xml
  plugins/multifactorauth/fixed/fixed.xml
  plugins/multifactorauth/totp/totp.xml
  plugins/multifactorauth/webauthn/webauthn.xml
  plugins/multifactorauth/yubikey/yubikey.xml
Labels: PR-4.4-dev

#40219 Split the back end CRUD tests into single tests
  tests/System/integration/administrator/components/com_categories/Categories.cy.js
  tests/System/integration/administrator/components/com_categories/Category.cy.js
  tests/System/integration/administrator/components/com_content/Article.cy.js
  tests/System/integration/administrator/components/com_content/Articles.cy.js
  tests/System/integration/administrator/components/com_content/ContentCategoryList.cy.js
  tests/System/integration/administrator/components/com_content/ContentFieldList.cy.js
  tests/System/integration/administrator/components/com_content/ContentList.cy.js
  tests/System/integration/administrator/components/com_fields/Field.cy.js
  tests/System/integration/administrator/components/com_fields/Fields.cy.js
  tests/System/integration/administrator/components/com_login/Login.cy.js
  tests/System/integration/administrator/components/com_menu/Menu.cy.js
  tests/System/integration/administrator/components/com_menu/MenuItem.cy.js
  tests/System/integration/administrator/components/com_menu/Menus.cy.js
  tests/System/integration/administrator/components/com_users/User.cy.js
  tests/System/integration/administrator/components/com_users/UserList.cy.js
  tests/System/integration/administrator/components/com_users/Users.cy.js
  tests/System/integration/administrator/general.cy.js
  tests/System/integration/api/com_banners/Banners.cy.js
  tests/System/integration/api/com_contact/Contacts.cy.js
  tests/System/integration/api/com_content/Articles.cy.js
  tests/System/integration/api/com_media/Files.cy.js
  tests/System/integration/install/Installation.cy.js
  tests/System/integration/plugins/installer/folderinstaller/FolderInstallerPlugin.cy.js
  tests/System/integration/plugins/installer/packageinstaller/PackageInstallerPlugin.cy.js
  tests/System/integration/plugins/installer/urlinstaller/UrlInstallerPlugin.cy.js
  tests/System/integration/plugins/installer/webinstaller/WebInstallerPlugin.cy.js
  tests/System/integration/site/components/com_contact/Category.cy.js
  tests/System/integration/site/components/com_content/Category.cy.js
  tests/System/integration/site/modules/mod_login/Default.cy.js
  tests/System/support/commands.js
  tests/System/support/commands/db.js
  tests/System/support/index.js
Labels: Unit/System Tests, PR-4.4-dev

#40186 Cypress test for adding field in contact form in com_contact
  tests/System/integration/site/components/com_contact/Contact.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40178 Cypress test for Categories wise view of contacts in com_contact.
  tests/System/integration/site/components/com_contact/Categories.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40164 Test not featured articles
  tests/System/integration/site/components/com_content/Category.cy.js
  tests/System/integration/site/components/com_content/Featured.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#40213 Fix deprecated warning in contenthistory
  administrator/components/com_contenthistory/src/Helper/ContenthistoryHelper.php
Labels: RTC, PHP 8.x, PR-4.3-dev, Small

#40212 Guided Tours: Colon in header and unused strings
  administrator/components/com_guidedtours/src/View/Step/HtmlView.php
  administrator/components/com_guidedtours/src/View/Tour/HtmlView.php
  administrator/language/en-GB/com_guidedtours.ini
  administrator/language/en-GB/com_guidedtours.sys.ini
Labels: RTC, Language Change, PR-4.3-dev

#40227 [4.3] Update namespacemap.php
  libraries/namespacemap.php
Labels: PR-4.3-dev

#40224 [4.4] Introduce local variables to replace repeating method calls
  plugins/authentication/cookie/src/Extension/Cookie.php
Labels: PR-4.4-dev

#40223 Set a higher timeout for cypress verification
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#40232 [4.4] Replace JPATH_PLATFORM with _JEXEC in plugin code
  plugins/authentication/ldap/src/Factory/LdapFactory.php
  plugins/authentication/ldap/src/Factory/LdapFactoryInterface.php
  plugins/content/confirmconsent/src/Field/ConsentBoxField.php
  plugins/system/privacyconsent/src/Field/PrivacyField.php
  plugins/user/profile/src/Field/TosField.php
  plugins/user/terms/src/Field/TermsField.php
Labels: PR-4.4-dev

#40101 Do not log to console in tours js
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
Labels: NPM Resource Changed, PR-4.3-dev

#40236 [4.3] unification header language files
  administrator/language/en-GB/com_guidedtours.sys.ini
  administrator/language/en-GB/plg_system_guidedtours.ini
  administrator/language/en-GB/plg_system_guidedtours.sys.ini
Labels: RTC, Language Change, PR-4.3-dev

#40229 [4.3] Fixing comparison in Url Filter
  libraries/src/Form/Filter/UrlFilter.php
Labels: RTC, PR-4.3-dev

#40246 [5.0] Update deleted files list in script.php to recent changes in the 5.0-dev branch
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40237 [4.3] Fix wrong lft and rgt values in assets table
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-4.3-dev

#40253 [5.0] Remove child template conversion of core templates from script.php
  administrator/components/com_admin/script.php
Labels: PR-5.0-dev

#40252 [5.0] Remove special handling of pkg_search for updates from 3.10 to 4.x
  administrator/components/com_admin/script.php
  administrator/manifests/packages/pkg_search.xml
  build/build.php
Labels: PR-5.0-dev

#40270 [4.3] Help button link urls
  libraries/src/Toolbar/Button/HelpButton.php
Labels: RTC, PR-4.3-dev

#40272 [4.3] fix factory class
  administrator/components/com_redirect/layouts/toolbar/batch.php
Labels: RTC, PR-4.3-dev

#40238 [4.3] [Guided Tours] Fancy select fields are broken and not accessible in tours
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-29.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-29.sql
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
Labels: RTC, NPM Resource Changed, PR-4.3-dev

#40228 Guided tours removal of tour permissions
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-03-28.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-02-15.sql
  administrator/components/com_admin/sql/updates/postgresql/4.3.0-2023-03-28.sql
  administrator/components/com_guidedtours/access.xml
  administrator/components/com_guidedtours/forms/tour.xml
  administrator/components/com_guidedtours/src/Model/StepModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_guidedtours/src/Table/StepTable.php
  administrator/components/com_guidedtours/src/Table/TourTable.php
  administrator/components/com_guidedtours/src/View/Tour/HtmlView.php
  administrator/components/com_guidedtours/tmpl/steps/default.php
  administrator/components/com_guidedtours/tmpl/tour/edit.php
  administrator/components/com_guidedtours/tmpl/tours/default.php
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  ruleset.xml
Labels: RTC, PR-4.3-dev
