Repository joomla/joomla-cms, pull requests merged in 2023-12, with the labels that each got.

#41885 [5.1] resolve todo image filter
  libraries/src/Image/Image.php
  libraries/src/Image/ImageFilter.php
Labels: Feature, RTC, PR-5.1-dev

#41096 [5.1] Joomla Update: Improving error handling when writing files
  administrator/components/com_joomlaupdate/extract.php
Labels: Feature, RTC, PR-5.1-dev

#40527 [4.4] json_decode of NULL in InstallerScript::getItemArray()
  libraries/src/Installer/InstallerScript.php
Labels: RTC, PHP 8.x, bug, PR-4.4-dev

#42490 [4.4] Finder: Do not show error messages for suggestions
  build/media_source/com_finder/js/finder.es6.js
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#42491 [4.4] com_contact: Fixing ignored loadData parameter for getForm
  components/com_contact/src/Model/ContactModel.php
Labels: RTC, PR-4.4-dev

#42458 [4.4] Fix error editor not found in contenthistory modal
  administrator/components/com_contenthistory/tmpl/history/modal.php
Labels: RTC, bug, PR-4.4-dev

#42497 [5.0] Upmerge 2023-12-12
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/language/en-GB/mod_menu.ini
  administrator/language/en-GB/plg_fields_imagelist.ini
  build/media_source/com_finder/js/finder.es6.js
  components/com_contact/src/Model/ContactModel.php
  libraries/src/Installer/InstallerScript.php
Labels: Language Change, NPM Resource Changed, PR-5.0-dev

#42451 [5] install from CLI deprecation php 8
  installation/src/Application/CliInstallationApplication.php
Labels: RTC, PHP 8.x, PR-5.0-dev

#42457 [4.4] Improve com users list view
  administrator/components/com_users/tmpl/users/default.php
Labels: RTC, UI/UX, PR-4.4-dev

#42454 [5.1] Use Dialog for ContentHistory field
  layouts/joomla/form/field/contenthistory.php
  layouts/joomla/toolbar/versions.php
  templates/cassiopeia/component.php
Labels: Feature, RTC, Small, PR-5.1-dev

#42391 [5.1] Fix category select in CategoryModal field
  administrator/components/com_categories/src/Field/Modal/CategoryField.php
Labels: RTC, bug, PR-5.1-dev

#42429 [5] fix Deprecated: Creation of dynamic property
  libraries/src/Updater/Update.php
Labels: RTC, PHP 8.x, bug, PR-5.0-dev

#42387 [5.x] Missing Strings [a11y]
  components/com_contact/forms/filter_contacts.xml
  components/com_content/forms/filter_articles.xml
  components/com_fields/forms/filter_fields.xml
  components/com_menus/forms/filter_items.xml
  components/com_modules/forms/filter_modules.xml
  language/en-GB/joomla.ini
Labels: RTC, Language Change, bug, PR-5.0-dev

#42337 [5.0] Show proper error message when package is installed with no extensions
  libraries/src/Installer/Adapter/PackageAdapter.php
Labels: RTC, bug, PR-5.0-dev

#42081 [5.1] Use Dialog for Shortcut overview
  build/media_source/plg_system_shortcut/js/shortcut.es6.js
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42082 [5.1] Use Dialog for Multilanguage status overview
  administrator/modules/mod_multilangstatus/tmpl/default.php
  build/media_source/mod_multilangstatus/js/admin-multilangstatus.es6.js
  build/media_source/templates/administrator/atum/scss/blocks/_header.scss
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42288 [5.1] Use Dialog for Field Media and Editor Media button
  build/media_source/plg_editors-xtd_image/js/button-image.es6.js
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  build/media_source/system/js/fields/joomla-media-select.w-c.es6.js
  layouts/joomla/form/field/media.php
  plugins/editors-xtd/image/src/Extension/Image.php
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42521 [5.1] Api privacy tests
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: RTC, Unit/System Tests, Small, PR-5.1-dev

#42535 [5.1] Upmerge 2023-12-17
  administrator/components/com_contenthistory/tmpl/history/modal.php
  administrator/language/en-GB/mod_menu.ini
  administrator/language/en-GB/plg_fields_imagelist.ini
  build/media_source/com_finder/js/finder.es6.js
  components/com_contact/forms/filter_contacts.xml
  components/com_contact/src/Model/ContactModel.php
  components/com_content/forms/filter_articles.xml
  components/com_fields/forms/filter_fields.xml
  components/com_menus/forms/filter_items.xml
  components/com_modules/forms/filter_modules.xml
  installation/src/Application/CliInstallationApplication.php
  language/en-GB/joomla.ini
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/InstallerScript.php
  libraries/src/Updater/Update.php
Labels: Language Change, NPM Resource Changed, PR-5.1-dev

#42522 [5.1] Api redirect tests
  tests/System/integration/api/com_redirect/Redirect.cy.js
Labels: RTC, Unit/System Tests, Small, PR-5.1-dev

#42512 [5.1] Api media test
  tests/System/integration/api/com_media/Adapters.cy.js
Labels: RTC, Unit/System Tests, Small, PR-5.1-dev

#42533 [4.4] File::delete() throws error and terminates installation/update/uninstall
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerScript.php
Labels: RTC, bug, PR-4.4-dev

#42489 [4.4] Add information about reasons to Joomla Update when an update was found which doesn't fulfil PHP or DB requirements
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
  libraries/src/Updater/Update.php
Labels: RTC, Language Change, bug, PR-4.4-dev

#42504 Fix link and button colors in header footer of Cassiopeia template
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_layout.scss
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#42545 [4.x] add PHP 8.3 to tests
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#42552 Update the signature for #42545
  .drone.yml
Labels: Unit/System Tests, Test instructions missing, PR-4.4-dev

#42550 [4.4] Joomlaupdate remove br tag from language strings - follow up to PR 42489
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-4.4-dev

#42556 [5.1] upmerge 2023-12-21
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerScript.php
  libraries/src/Updater/Update.php
Labels: Language Change, PR-5.1-dev

#42560 [4.4] Fixes to form validation process
  libraries/src/Form/Form.php
Labels: RTC, PR-4.4-dev

#42562 [4][com_actionlogs] missed load plugin languages
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: RTC, Unit/System Tests, bug, PR-4.4-dev

#42570 [4.4] Better message on package uninstallation when an extension is missing
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Installer/Adapter/PackageAdapter.php
Labels: Language Change, PR-4.4-dev

#42088 [4] backport #41865
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: bug, Maintainers Checked, PR-4.4-dev

#42513 [5.1] Api categories tests
  tests/System/integration/api/com_banners/Categories.cy.js
  tests/System/integration/api/com_contact/Categories.cy.js
  tests/System/integration/api/com_content/Categories.cy.js
  tests/System/integration/api/com_newsfeed/Categories.cy.js
Labels: RTC, Unit/System Tests, Small, PR-5.1-dev

#40033 Fix actionlogs information emails containing HTML links
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  libraries/src/Mail/MailTemplate.php
Labels: Feature, RTC, PR-5.1-dev

#42527 [5.1] Generic doc icon
  administrator/components/com_media/resources/scripts/components/browser/items/document.vue
  build/media_source/com_media/scss/_variables.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#42574 [5] harmonize naming task types
  administrator/language/en-GB/plg_task_deleteactionlogs.ini
  administrator/language/en-GB/plg_task_sessiongc.ini
Labels: RTC, Language Change, bug, PR-5.0-dev

#42544 [5.0] colour contrast in media manager file list [a11y]
  build/media_source/com_media/scss/components/_media-browser.scss
Labels: RTC, NPM Resource Changed, bug, PR-5.0-dev

#42580 [5.0] Upmerge 2023-12-30
  .drone.yml
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/lib_joomla.ini
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_layout.scss
  language/en-GB/lib_joomla.ini
  libraries/src/Form/Form.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: Unit/System Tests, Language Change, NPM Resource Changed, PR-5.0-dev

#42469 [5.0] Update phpseclib to 3.0.34
  composer.lock
Labels: Composer Dependency Changed, PR-5.0-dev

#42315 Fix `function` parameter lost during redirect
  administrator/components/com_menus/tmpl/items/modal.php
Labels: RTC, bug, PR-5.0-dev

#42576 [4.4] Fix SQL error "1104 The SELECT would examine more than MAX_JOIN_SIZE rows" when checking for core updates
  libraries/src/Extension/ExtensionHelper.php
Labels: RTC, bug, PR-4.4-dev

#42583 [5.0] Revert min version in drone
  .drone.yml
Labels: Unit/System Tests, PR-5.0-dev

#42569 [4][com_templates] cast to int for pgsql
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default.php
Labels: RTC, bug, PR-4.4-dev
