Repository joomla/joomla-cms, pull requests merged in 2023-10, with the labels that each got.

#42005 [5.0] Fix contrast color in dark mode installation
  installation/template/scss/template.scss
Labels: NPM Resource Changed, PR-5.0-dev

#42003 [5.0] Install from web dark mode hover fix
  build/media_source/templates/administrator/atum/scss/pages/_plg_web_installer.scss
  build/media_source/templates/administrator/atum/scss/template.scss
Labels: NPM Resource Changed, PR-5.0-dev

#42006 [5.0] Fix permissions list color in dark mode
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: NPM Resource Changed, PR-5.0-dev

#42004 [5.0] Fix actions dropdown hover effect
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_dropdown.scss
Labels: NPM Resource Changed, PR-5.0-dev

#42018 adds missing dropdown icon
  installation/template/images/select-bg-dark.svg
  installation/template/images/select-bg-rtl-dark.svg
Labels: bug, PR-5.0-dev

#42020 [4.4] Fix SQL error in template styles view when using text search together with template filter
  administrator/components/com_templates/src/Model/StylesModel.php
Labels: RTC, Release Blocker, bug, PR-4.4-dev

#42024 [5.0] rtl dark select image
  build/media_source/templates/administrator/atum/images/select-bg-rtl-dark.svg
  installation/template/images/select-bg-rtl-dark.svg
Labels: NPM Resource Changed, PR-5.0-dev

#42026 [5.0] Activate compat plugin for new installations
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: PR-5.0-dev

#42027 [5.0] Upmerge
  administrator/components/com_templates/src/Model/StylesModel.php
Labels: PR-5.0-dev

#42042 [5.0] Set organization as default to activate schemaorg by default
  plugins/system/schemaorg/schemaorg.xml
  plugins/system/schemaorg/src/Extension/Schemaorg.php
Labels: RTC, Release Blocker, bug, PR-5.0-dev

#42047 Update com_joomlaupdate.ini
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-4.4-dev

#42038 [5.0] hash the urls inside css files
  build/build-modules-js/css-versioning.es6.js
  build/build.js
  build/build.php
  package-lock.json
  package.json
Labels: RTC, NPM Resource Changed, bug, PR-5.0-dev

#42050 [5.0] dark mode - quickicon amount
  build/media_source/templates/administrator/atum/scss/blocks/_quickicons.scss
Labels: Release Blocker, NPM Resource Changed, bug, PR-5.0-dev

#42059 [5.1] typo Update state.es6.js
  administrator/components/com_media/resources/scripts/store/state.es6.js
Labels: Language Change, NPM Resource Changed, bug, PR-5.0-dev, PR-5.1-dev

#42054 [5.0] Sample Data Titles contrast a11y
  build/media_source/templates/administrator/atum/scss/pages/_com_cpanel.scss
Labels: NPM Resource Changed, PR-5.0-dev, Dark Mode

#42058 [5.0] Console error due to missing dependency
  administrator/components/com_mails/forms/template.xml
Labels: RTC, Release Blocker, bug, PR-5.0-dev

#42053 [5.0] Installer drag'n drop dark mode a11y
  build/media_source/com_installer/css/installer.css
Labels: NPM Resource Changed, PR-5.0-dev, Dark Mode

#42062 [5.1] upmerges - 2023-10-05
  administrator/components/com_mails/forms/template.xml
  build/media_source/com_installer/css/installer.css
  build/media_source/templates/administrator/atum/scss/pages/_com_cpanel.scss
Labels: NPM Resource Changed, PR-5.1-dev

#42057 [5.0] Treeselect dark mode
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/blocks/_treeselect.scss
Labels: RTC, NPM Resource Changed, PR-5.0-dev, Dark Mode

#42051 [5.0] Dark Mode: Versions toolbar
  administrator/components/com_contenthistory/src/View/History/HtmlView.php
Labels: RTC, bug, PR-5.0-dev, Dark Mode

#42066 [5.0] Remove bs2 classes
  administrator/components/com_users/tmpl/method/edit.php
  components/com_users/tmpl/method/edit.php
Labels: PR-5.0-dev

#42064 [5.0] testing data rss fix
  plugins/sampledata/testing/src/Extension/Testing.php
Labels: PR-5.0-dev

#42060 [5.0] Fix the calendar
  build/media_source/system/css/fields/calendar-rtl.css
  build/media_source/system/css/fields/calendar.css
  build/media_source/system/images/calendar-select-bg-dark-rtl.svg
  build/media_source/system/images/calendar-select-bg-dark.svg
  build/media_source/templates/administrator/atum/scss/blocks/_calendar.scss
Labels: Release Blocker, NPM Resource Changed, PR-5.0-dev

#42071 [5.0] com_templates buttons dark mode
  administrator/components/com_templates/src/View/Template/HtmlView.php
Labels: bug, PR-5.0-dev, Dark Mode

#42078 [5.0] form-select background
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_custom-forms.scss
Labels: NPM Resource Changed, PR-5.0-dev, Dark Mode

#42073 [5.0] code-color dark mode
  build/media_source/templates/administrator/atum/scss/_variables-dark.scss
Labels: NPM Resource Changed, PR-5.0-dev, Dark Mode

#42079 [5.0] Fix dialog height in Safari
  build/media_source/templates/administrator/atum/scss/blocks/_modals.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_modals.scss
Labels: NPM Resource Changed, bug, PR-5.0-dev

#42089 [5.0] Fix SCSS CS broken by PR #42078
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_custom-forms.scss
Labels: NPM Resource Changed, PR-5.0-dev

#42095 [5.1] change version manifest
  administrator/manifests/files/joomla.xml
Labels: PR-5.1-dev

#42085 [5.0] Dark Mode: MFA button
  administrator/components/com_users/tmpl/methods/list.php
Labels: RTC, PR-5.0-dev, Dark Mode

#42091 [5.0] Updating Joomla framework to version 3.0.0
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.0-dev

#42096 [5.0] Check if the value consist with id:alias, extract the id only
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_menus/src/Field/Modal/MenuField.php
Labels: Release Blocker, bug, PR-5.0-dev

#42097 [5.1] upmerges 2023-10-09
  administrator/components/com_contenthistory/src/View/History/HtmlView.php
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/components/com_users/tmpl/method/edit.php
  administrator/components/com_users/tmpl/methods/list.php
  build/media_source/system/css/fields/calendar-rtl.css
  build/media_source/system/css/fields/calendar.css
  build/media_source/system/images/calendar-select-bg-dark-rtl.svg
  build/media_source/system/images/calendar-select-bg-dark.svg
  build/media_source/templates/administrator/atum/scss/_variables-dark.scss
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/blocks/_calendar.scss
  build/media_source/templates/administrator/atum/scss/blocks/_modals.scss
  build/media_source/templates/administrator/atum/scss/blocks/_treeselect.scss
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_custom-forms.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_modals.scss
  components/com_users/tmpl/method/edit.php
  composer.json
  composer.lock
  plugins/sampledata/testing/src/Extension/Testing.php
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.1-dev

#42098 [5.0] Fix language association "clear" button
  build/media_source/com_associations/js/sidebyside.es5.js
Labels: RTC, Release Blocker, NPM Resource Changed, bug, PR-5.0-dev

#42103 [4.4] Noupdate available to joomla 5
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, bug, PR-4.4-dev

#42137 [5.0] Upmerge 4.4
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Language Change, PR-5.0-dev

#42146 [5.1] upmerges 2023-10-16
  administrator/components/com_content/src/Field/Modal/ArticleField.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/components/com_menus/src/Field/Modal/MenuField.php
  administrator/language/en-GB/com_joomlaupdate.ini
  build/media_source/com_associations/js/sidebyside.es5.js
Labels: Language Change, NPM Resource Changed, PR-5.1-dev

#42152 [5.0] Update build script for new github layout
  build/build.php
  build/layouts/github.php
Labels: PR-5.0-dev

#42138 [5.0] installerhelper codestyle
  administrator/components/com_installer/src/Helper/InstallerHelper.php
Labels: RTC, PR-5.0-dev

#42139 [5.0] com_joomlaupdate comment
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: RTC, PR-5.0-dev

#42119 [5.0] Media manager list view parity
  administrator/components/com_media/resources/scripts/components/browser/table/row.vue
  build/media_source/com_media/scss/components/_media-browser.scss
Labels: RTC, NPM Resource Changed, PR-5.0-dev

#42111 Custom Fields: Add warning to Finder option about information disclosure
  administrator/components/com_fields/forms/field.xml
  administrator/language/en-GB/com_fields.ini
Labels: RTC, Language Change, PR-5.0-dev

#41679 [5.0] MailTemplate: Prevent notice in replaceTags
  libraries/src/Mail/MailTemplate.php
Labels: RTC, bug, Maintainers Checked, PR-5.0-dev

#42135 [5.0] Rework the com_messages message view
  administrator/components/com_messages/tmpl/message/default.php
Labels: RTC, PR-5.0-dev, PR-5.1-dev

#42167 [5.0] Remove template special color from core use
  build/media_source/templates/administrator/atum/scss/blocks/_toolbar.scss
Labels: NPM Resource Changed, PR-5.0-dev, Dark Mode

#42116 [5.0] Fixes the cli installer
  libraries/src/Helper/PublicFolderGeneratorHelper.php
Labels: RTC, bug, PR-5.0-dev

#42174 [5.0] Update min PHP requirement to 8.1in installation CLI
  installation/joomla.php
Labels: bug, PR-5.0-dev

#42168 [5.0] Add proper error handling for public folder cli installation
  installation/src/Console/InstallCommand.php
Labels: RTC, bug, PR-5.0-dev

#42188 [5.1] upmerges 2023-10-21
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_installer/src/Helper/InstallerHelper.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/components/com_media/resources/scripts/components/browser/table/row.vue
  administrator/components/com_messages/tmpl/message/default.php
  administrator/language/en-GB/com_fields.ini
  build/build.php
  build/layouts/github.php
  build/media_source/com_media/scss/components/_media-browser.scss
  build/media_source/templates/administrator/atum/scss/blocks/_toolbar.scss
  installation/joomla.php
  installation/src/Console/InstallCommand.php
  libraries/src/Helper/PublicFolderGeneratorHelper.php
  libraries/src/Mail/MailTemplate.php
  libraries/src/Version.php
Labels: Language Change, NPM Resource Changed, PR-5.1-dev

#39013 [5.1] Load plugin group when executing batch tasks
  libraries/src/MVC/Model/AdminModel.php
Labels: Feature, RTC, PBF, Maintainers Checked, Small, PR-5.1-dev

#42140 [5.1] com_installer getListQuery
  administrator/components/com_installer/src/Model/UpdateModel.php
Labels: Feature, RTC, PR-5.1-dev

#42217 [5.0] Load Behaviour - Backward Compatibility in the ConsoleApplication
  libraries/src/Application/ConsoleApplication.php
Labels: bug, PR-5.0-dev

#42220 [5.1] Alias string consistency
  administrator/language/en-GB/com_contact.ini
  administrator/language/en-GB/com_finder.ini
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  language/en-GB/com_contact.ini
  language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-5.1-dev

#42227 [5.0][bug] TinyMCE Setting linebreak with doesn´t work
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-5.0-dev

#41150 [4.4] Context Issue Fix for 41136
  components/com_tags/tmpl/tag/default.php
  components/com_tags/tmpl/tag/list.php
Labels: RTC, bug, PR-4.4-dev

#41900 [4.4] Remove duplicate png
  administrator/components/com_media/config.xml
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, bug, PR-4.4-dev

#42247 [4.4] Fixing drone packager upload
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#42245 [4] module related_items
  modules/mod_related_items/tmpl/default.php
Labels: RTC, bug, PR-4.4-dev

#42206 [4] article field List on webservices
  plugins/fields/list/src/Extension/ListPlugin.php
Labels: RTC, bug, Webservices, PR-4.4-dev

#42157 [4.4.0] Fix condition for menuitems
  plugins/content/joomla/src/Extension/Joomla.php
Labels: RTC, bug, PR-4.4-dev

#42036 [4.4] Proposed fix for Workflow transition error
  libraries/src/Workflow/Workflow.php
Labels: RTC, bug, PR-4.4-dev

#42233 Fix for issue 42229 - webservices content patch tags lost
  api/components/com_content/src/Controller/ArticlesController.php
Labels: RTC, Webservices, PR-4.4-dev

#42240 [5.0] Update TinyMCE to 6.7.2
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.xml
Labels: RTC, Release Blocker, NPM Resource Changed, PR-5.0-dev

#42256 [5.0] User field: fix "No user" selection
  administrator/components/com_users/tmpl/users/modal.php
Labels: RTC, PR-5.0-dev
