Repository joomla/joomla-cms, pull requests merged in 2024-09, with the labels that each got.

#43778 [cypress] lint mjs files
  build/.eslintrc
  package.json
  tests/System/plugins/db.mjs
  tests/System/plugins/fs.mjs
  tests/System/plugins/index.mjs
Labels: Unit/System Tests, NPM Resource Changed, PR-4.4-dev

#43343 Update README.md to include MariaDB
  README.txt
Labels: bug, PR-4.4-dev

#44010 [5.3] Bumping version to 5.3.0-alpha1-dev
  README.md
  README.txt
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  build.xml
  installation/language/en-GB/langmetadata.xml
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Version.php
  package-lock.json
  package.json
Labels: Language Change, NPM Resource Changed, PR-5.3-dev

#44014 [5.3] Drone: Fix version in nightly build messages
  .drone.yml
Labels: Unit/System Tests, PR-5.3-dev

#44053 [4.4] Fix workflow transition task name in featured articles layout
  administrator/components/com_content/tmpl/featured/default.php
Labels: RTC

#44050 [4.4] Improve translation of aria label text by extra language keys
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  layouts/joomla/pagination/link.php
Labels: RTC, Language Change, a11y, PR-4.4-dev

#44000 [5.2] Tinymce lang sort - Part 2
  administrator/language/en-GB/plg_editors_tinymce.ini
Labels: Language Change, bug, PR-5.2-dev

#44026 [5.2] [Guided Tours] Fix help link and add inlinehelp tag to the global settings of the Guided Tours
  administrator/components/com_guidedtours/config.xml
Labels: RTC, PR-5.2-dev

#44036 [5.2] UPD composer files, phpseclib/bcmath_compat 2.0.3
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.2-dev

#43945 [5.2] svg sanitize update
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.1-dev, PR-5.2-dev

#41661 [5.2] Non-static methods called as static from object context
  administrator/components/com_banners/src/Table/BannerTable.php
  libraries/src/Form/Rule/RulesRule.php
  libraries/src/Helper/TagsHelper.php
Labels: bug, PR-5.0-dev, PR-5.1-dev, PR-5.2-dev

#43796 [5.2] MFA and Silent Logins
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerLogin.php
Labels: RTC, bug, PR-5.2-dev

#43934 [5.2] Fix of backward compatibility for Login event arguments
  libraries/src/Event/User/AbstractLoginEvent.php
  libraries/src/Event/User/AbstractLogoutEvent.php
Labels: RTC, bug, PR-5.1-dev, PR-5.2-dev

#43966 [5.2] [Guided tours] Add a What's New tour when updating to Joomla 5.2
  administrator/components/com_admin/sql/updates/mysql/5.2.0-2024-08-22.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.0-2024-08-22.sql
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_2.ini
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_2_steps.ini
  build/media_source/com_guidedtours/images/5_2/enhancedtourheader.png
  build/media_source/com_guidedtours/images/5_2/mailtemplate.png
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: RTC, Language Change, NPM Resource Changed, PR-5.2-dev

#44057 [5.2] Upmerge from 4.4 to 5.2 2024-09-12
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/src/View/Field/HtmlView.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_finder/src/Indexer/Helper.php
  administrator/components/com_finder/src/Indexer/Result.php
  administrator/components/com_finder/src/Indexer/Taxonomy.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
  administrator/language/en-GB/lib_joomla.ini
  build/.eslintrc
  language/en-GB/lib_joomla.ini
  layouts/joomla/pagination/link.php
  libraries/src/Access/Access.php
  libraries/src/Factory.php
  libraries/src/MVC/Model/LegacyModelLoaderTrait.php
  tests/System/plugins/db.mjs
  tests/System/plugins/fs.mjs
  tests/System/plugins/index.mjs
Labels: Unit/System Tests, Language Change, PR-5.2-dev

#43961 [5.2] Remove trailing slash
  libraries/src/Document/Renderer/Html/StylesRenderer.php
Labels: RTC, bug, PR-5.2-dev

#42694 [4.4] Align the access checks for the unpublished articles in frontend category
  components/com_content/src/Model/ArticlesModel.php
Labels: RTC, PR-4.4-dev

#43784 [4][com_scheduler] Manual Execution Rule blocks Lazy and Webcron
  administrator/components/com_scheduler/src/Model/TaskModel.php
Labels: RTC, bug, PR-4.4-dev

#43906 [4.4] Correct file size validation for Media component
  administrator/components/com_media/src/Controller/ApiController.php
Labels: RTC, bug, PR-4.4-dev

#41666 [5.2] Invalid usage of static methods
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_users/src/Model/MailModel.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Authentication/Password/ChainedHandler.php
  libraries/src/Log/DelegatingPsrLogger.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/User/User.php
Labels: bug, PR-5.2-dev

#43922 [4] Tagged Items Menu Item When Both Public and Registered Tags 404
  components/com_tags/src/Model/TagModel.php
Labels: RTC, Information Required, PR-4.4-dev

#44065 [5.2] Deprecate string
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: Language Change, bug, PR-5.2-dev

#44066 [5.2] Updating maximebf/debugbar, joomla/filesystem and phpstan
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.2-dev

#44067 [5.2] Updating Bootstrap to 5.3.3
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-5.2-dev

#44068 [5.2] Upmerge from 4.4 to 5.2 2024-09-13
  administrator/components/com_media/src/Controller/ApiController.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  components/com_content/src/Model/ArticlesModel.php
  components/com_tags/src/Model/TagModel.php
  tests/System/integration/administrator/components/com_actionlogs/Actionlogs.cy.js
  tests/System/integration/administrator/components/com_cache/Default.cy.js
  tests/System/integration/administrator/components/com_checkin/Default.cy.js
  tests/System/integration/administrator/components/com_login/Login.cy.js
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: Unit/System Tests, PR-5.2-dev

#44099 [5.3] Calendar Strings
  layouts/joomla/form/field/calendar.php
Labels: RTC, PR-5.3-dev

#44106 [5.2] [Guided Tours] The 'Welcome' tour contains unescaped quotes in a language string
  administrator/language/en-GB/guidedtours.joomla_welcome.ini
Labels: Language Change, PR-5.2-dev, Guided Tours

#44075 [5.2] [Guided tours] Bug fixes for PR #43966
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_2.ini
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_2_steps.ini
Labels: RTC, Language Change, PR-5.2-dev, Guided Tours

#44093 [5.2] [Guided Tours] Better tour user state wording and explanation
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, PR-5.2-dev, Guided Tours

#43694 [5.2] Created translatable strings for LocalAdapter.php "code review"
  administrator/language/en-GB/com_media.ini
  language/en-GB/com_media.ini
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: RTC, Language Change, PR-5.2-dev

#44082 [5.2] [Guided Tours] Fix permission errors when recording user tour state
  administrator/components/com_guidedtours/src/Controller/AjaxController.php
  administrator/components/com_guidedtours/src/Dispatcher/Dispatcher.php
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, Release Blocker, PR-5.2-dev, Guided Tours

#44104 [5.2] [Guided Tours] Fix content and footer padding
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-5.2-dev, Guided Tours

#44111 [5.2] fix unescaped quotes in sampldata_blog language string
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: RTC, Language Change, PR-5.2-dev

#44110 [5.2] [Guided Tours] unescaped quotes in a language string
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_2.ini
Labels: RTC, Language Change, PR-5.2-dev

#44061 [4.4] Fix next exec calculation for task scheduler
  administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
Labels: RTC, PR-4.4-dev

#44116 [4.4] [Guided Tours] The categories tour is not visible to Managers
  administrator/modules/mod_guidedtours/src/Helper/GuidedToursHelper.php
Labels: RTC, bug, PR-4.4-dev, Guided Tours

#44117 [4.4] Quickicon for article categories fails with error permissions on + (add)
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: RTC, bug, PR-4.4-dev

#44123 [5.2] fix update sql for postgres
  administrator/components/com_admin/sql/updates/postgresql/5.2.0-2024-07-19.sql
Labels: Release Blocker, PR-5.2-dev

#44069 [4.4] Fix start=0 in the pagination
  libraries/src/Router/SiteRouter.php
Labels: RTC, bug, PR-4.4-dev

#44023 [4.4] Check pagination parameters from request, another try
  libraries/src/Pagination/Pagination.php
Labels: RTC, bug, PR-4.4-dev

#44105 [5.2] [Guided Tours] Addition of 'Auto start' step in 'How to create a tour?' tour
  administrator/components/com_admin/sql/updates/mysql/5.2.0-2024-09-17.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.0-2024-09-17.sql
  administrator/language/en-GB/guidedtours.joomla_guidedtours_steps.ini
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
Labels: RTC, Language Change, PR-5.2-dev, Guided Tours

#44107 [4.4] Update .drone.yml
  .drone.yml
Labels: RTC, Unit/System Tests, PR-4.4-dev

#44091 [5.2] [Guided Tours] Global Configuration delay field fix
  administrator/components/com_guidedtours/config.xml
Labels: RTC, PR-5.2-dev, Guided Tours

#44126 Upmerge from 4.4-dev to 5.2-dev on 2024-09-23
  .drone.yml
  administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
  administrator/modules/mod_guidedtours/src/Helper/GuidedToursHelper.php
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
  build/media_source/mod_menu/js/menu.es6.js
  libraries/src/Pagination/Pagination.php
  libraries/src/Router/SiteRouter.php
Labels: Unit/System Tests, NPM Resource Changed, PR-5.2-dev

#44125 [5.2] Updating dev dependencies
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.2-dev

#44077 [4.4][Performance] Fix duplicated DB queries for ActionLog language loading
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
Labels: RTC, Small, PR-4.4-dev, Performance

#44119 [4.x] Fix settings component parameters of menuitems via API
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: RTC, bug, Webservices, PR-4.4-dev

#44142 [5.2] Fix filtering exclude and include articles
  language/en-GB/mod_articles.ini
  modules/mod_articles/mod_articles.xml
  modules/mod_articles/src/Helper/ArticlesHelper.php
Labels: RTC, Language Change, PR-5.2-dev

#44144 Remove forgotten 'card-link' parameter from field and blog sample data
  modules/mod_articles/mod_articles.xml
  plugins/sampledata/blog/src/Extension/Blog.php
Labels: RTC, bug, PR-5.2-dev

#44127 Option to show all articles in the new mod_articles
  language/en-GB/mod_articles.ini
  modules/mod_articles/mod_articles.xml
Labels: RTC, Language Change, PR-5.2-dev

#44132 Added plugin event triggers to the new mod_articles module
  language/en-GB/mod_articles.ini
  modules/mod_articles/mod_articles.xml
  modules/mod_articles/src/Helper/ArticlesHelper.php
  modules/mod_articles/tmpl/default_items.php
  plugins/sampledata/blog/src/Extension/Blog.php
Labels: Feature, RTC, Language Change, PR-5.2-dev

#44145 Articles Module: (Re)Introduced dynamic mode as on mod_articles_category
  language/en-GB/mod_articles.ini
  modules/mod_articles/mod_articles.xml
  modules/mod_articles/src/Dispatcher/Dispatcher.php
  modules/mod_articles/src/Helper/ArticlesHelper.php
  plugins/sampledata/blog/src/Extension/Blog.php
Labels: RTC, Language Change, PR-5.2-dev

#44137 Module Articles show only articles from current user
  language/en-GB/mod_articles.ini
  modules/mod_articles/mod_articles.xml
  modules/mod_articles/src/Helper/ArticlesHelper.php
  modules/mod_articles/tmpl/default.php
Labels: Feature, RTC, Language Change, PR-5.2-dev

#44155 Fix showon for Trigger Plugin Events in mod_articles
  modules/mod_articles/mod_articles.xml
Labels: PR-5.2-dev

#44136 Article module fix read more title
  modules/mod_articles/tmpl/default_items.php
Labels: bug, PR-5.2-dev

#44156 [5.2] Update NPM developer dependency "rollup" from 2.79.1 to 2.79.2
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-5.2-dev

#44158 [5.2] Upmerge from 4.4-dev 2024-09-29
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_menus/src/Model/ItemModel.php
Labels: PR-5.2-dev

#44160 [5.2] Fix saving edited images in media manager
  administrator/components/com_media/src/Controller/ApiController.php
Labels: RTC, Release Blocker, bug, PR-5.2-dev
