Repository joomla/joomla-cms, pull requests merged in 2024-07, with the labels that each got.

#43720 [5.1] Remove in development
  README.md
  README.txt
Labels: RTC, PR-5.1-dev

#43716 [5.1] Allow PDF embeding again
  administrator/language/en-GB/plg_editors_tinymce.ini
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, Language Change, bug, PR-5.1-dev

#43491 [5.2] Show a warning when there are due tasks
  administrator/components/com_scheduler/forms/filter_tasks.xml
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_scheduler/tmpl/tasks/default.php
  administrator/language/en-GB/com_scheduler.ini
Labels: RTC, Language Change, PR-5.2-dev

#43734 Change redirect url (from headers['Location']) from array to string
  libraries/src/Http/Transport/SocketTransport.php
Labels: PR-5.1-dev

#43660 [5.1] Fix radio and checkboxes in nested subform field
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: NPM Resource Changed, bug, PR-5.1-dev

#43618 [5.1] Add onchange option to modal-select form field
  layouts/joomla/form/field/modal-select.php
Labels: RTC, bug, PR-5.1-dev

#43717 [5.1] Add update channel reset to Joomla Update Component
  administrator/components/com_joomlaupdate/src/Controller/DisplayController.php
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/complete.php
  administrator/language/en-GB/com_joomlaupdate.ini
  libraries/src/Console/UpdateCoreCommand.php
Labels: Language Change, Release Blocker, PR-5.1-dev

#42825 [5.1] Load Schema.org only in proper forms
  plugins/system/schemaorg/src/Extension/Schemaorg.php
Labels: RTC, bug, PR-5.1-dev

#43752 [5.1] Use created_by 0 if created_by is empty
  libraries/src/Table/Content.php
Labels: RTC, PR-5.1-dev

#43740 [4.4] Fix display of total votes
  plugins/content/vote/tmpl/rating.php
Labels: RTC, bug, PR-4.4-dev

#43247 [5.2] remove margin-bottom on .btn styling to prevent nasty offset
  administrator/language/en-GB/plg_sampledata_blog.ini
  build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_buttons.scss
  components/com_config/tmpl/config/default.php
  components/com_config/tmpl/modules/default.php
  components/com_config/tmpl/templates/default.php
  components/com_contact/tmpl/form/edit.php
  components/com_content/tmpl/form/edit.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-5.2-dev

#43750 [4.4] [cli] TasksListCommand fix deprecation when execution = manual
  libraries/src/Console/TasksListCommand.php
Labels: RTC, bug, PR-4.4-dev

#43774 [4.4] Fix wrong search for id in fields groups
  administrator/components/com_fields/src/Model/GroupsModel.php
Labels: RTC, bug, PR-4.4-dev

#43361 [5.2] Refactor all instances of File::getExt() & stripExt() to use framework
  administrator/components/com_media/src/Model/ApiModel.php
  administrator/components/com_templates/tmpl/template/default_modal_rename_body.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Mail/MailTemplate.php
  plugins/editors/tinymce/src/PluginTraits/ResolveFiles.php
Labels: Feature, PR-5.2-dev

#43475 [5.2] Mail Templates language file loading not using the MailsHelper::loadTranslationFiles
  administrator/components/com_mails/src/Helper/MailsHelper.php
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_mails/src/View/Templates/HtmlView.php
Labels: RTC, PR-5.2-dev

#43801 [5.1] Update bump script also to update package-lock.json
  build/bump.php
Labels: RTC, PR-5.1-dev

#43782 [4.4] Fix copy/paste
  administrator/components/com_actionlogs/src/Controller/DisplayController.php
Labels: RTC, PR-4.4-dev

#43815 [5.2] Upmerge 2024-07-20
  administrator/components/com_fields/forms/field.xml
  build/bump.php
  build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js
  components/com_wrapper/tmpl/wrapper/default.xml
  libraries/src/Form/Field/AccessiblemediaField.php
  libraries/src/HTML/Helpers/StringHelper.php
  modules/mod_wrapper/mod_wrapper.xml
  package-lock.json
Labels: NPM Resource Changed, PR-5.2-dev

#43704 [5.2] Add deleted files and folders from debugbar dependency update to script.php
  administrator/components/com_admin/script.php
Labels: PR-5.2-dev

#43808 [5.1] Update TinyMCE to 6.8.4
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-5.1-dev

#43731 [cypress] ESM docu update II
  tests/System/README.md
Labels: Unit/System Tests, PR-4.4-dev

#43828 [5.1] Fix attachment handling in libraries Mail class
  libraries/src/Mail/Mail.php
Labels: RTC, bug, PR-5.1-dev

#43835 [5.2] Upmerge 2024-07-23
  libraries/src/Mail/Mail.php
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-5.2-dev

#43579 [5.2] Media field: selectable folders
  administrator/components/com_media/resources/scripts/components/breadcrumb/breadcrumb.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/resources/scripts/components/browser/table/row.vue
  administrator/components/com_media/resources/scripts/components/tree/drive.vue
  administrator/components/com_media/resources/scripts/components/tree/tree.vue
  administrator/language/en-GB/plg_editors_tinymce.ini
  build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es6.js
  build/media_source/system/js/fields/joomla-field-media.w-c.es6.js
  build/media_source/system/js/fields/joomla-media-select.w-c.es6.js
  layouts/joomla/form/field/media.php
  libraries/src/Form/Field/MediaField.php
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/src/Field/UploaddirsField.php
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
  plugins/fields/media/media.xml
  plugins/fields/media/params/media.xml
Labels: Feature, RTC, Language Change, Documentation Required, NPM Resource Changed, PR-5.2-dev

#43690 [5.2] [Guided tours] Add missing auto start parameter in the user interface of tours
  administrator/components/com_guidedtours/forms/tour.xml
  administrator/components/com_guidedtours/tmpl/tour/edit.php
  administrator/language/en-GB/com_guidedtours.ini
Labels: RTC, Language Change, PR-5.2-dev

#41644 [5.2] useless array access
  administrator/components/com_categories/src/Controller/AjaxController.php
  administrator/components/com_contact/src/Controller/AjaxController.php
  administrator/components/com_content/src/Controller/AjaxController.php
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_finder/src/Service/HTML/Filter.php
  administrator/components/com_menus/src/Controller/AjaxController.php
  administrator/components/com_modules/src/Helper/ModulesHelper.php
  administrator/components/com_newsfeeds/src/Controller/AjaxController.php
  administrator/modules/mod_logged/src/Helper/LoggedHelper.php
  libraries/src/Cache/Cache.php
  libraries/src/Cache/CacheController.php
  libraries/src/Form/Field/AliastagField.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/Language/Text.php
Labels: RTC, PR-5.2-dev

#43164 [5.2] SEF/Router: Only merge default menu item when same component
  libraries/src/Router/SiteRouter.php
Labels: Feature, RTC, PR-5.2-dev

#43188 [4.4] Backendmenu: Fixing export of additionla features for menu items
  administrator/components/com_menus/src/View/Menu/XmlView.php
Labels: RTC, bug, PR-4.4-dev

#43839 [5.1] Delete schemaorg item after deleting an item
  plugins/system/schemaorg/src/Extension/Schemaorg.php
Labels: PR-5.1-dev

#43849 Make toolbar for mail-template as other layouts
  administrator/components/com_mails/src/View/Template/HtmlView.php
Labels: RTC, UI/UX, PR-5.2-dev

#43639 [5.2][Events] Use event classes for Actionlog plugins
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/User/AbstractResetEvent.php
  libraries/src/Event/User/AfterResetCompleteEvent.php
  libraries/src/Event/User/AfterResetRequestEvent.php
  libraries/src/Event/User/BeforeResetCompleteEvent.php
  libraries/src/Event/User/BeforeResetRequestEvent.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
Labels: Feature, RTC, PR-5.2-dev

#43848 [4.4] Typo Update showon.es6.js
  build/media_source/system/js/showon.es6.js
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#43764 [5.1] Remove testing channel
  libraries/src/Console/CheckJoomlaUpdatesCommand.php
  libraries/src/Console/CoreUpdateChannelCommand.php
Labels: RTC, bug, PR-5.1-dev

#43852 [5.1] Upmerge 2024-07-26
  administrator/components/com_actionlogs/src/Controller/DisplayController.php
  administrator/components/com_fields/src/Model/GroupsModel.php
  administrator/components/com_menus/src/View/Menu/XmlView.php
  build/media_source/system/js/showon.es6.js
  libraries/src/Console/TasksListCommand.php
  plugins/content/vote/tmpl/rating.php
  tests/System/README.md
Labels: Unit/System Tests, NPM Resource Changed, PR-5.1-dev

#43791 [5.1] Fix Fontend language multilingual without compatibility plugin
  administrator/components/com_users/src/Model/UserModel.php
  components/com_users/src/Model/ProfileModel.php
  components/com_users/src/Model/RegistrationModel.php
Labels: RTC, bug, PR-5.1-dev

#43763 [5.1] Remove an unneeded variable
  libraries/src/Document/Renderer/Html/HeadRenderer.php
Labels: RTC, PR-5.1-dev

#43745 [5.1] Field ModalSelect: make sure token in the URLs
  build/media_source/system/js/fields/modal-content-select-field.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#43823 [5.2] [feature] Media manager select last uploaded item (iframe)
  administrator/components/com_media/resources/scripts/store/mutations.es6.js
Labels: Feature, RTC, NPM Resource Changed, PR-5.2-dev

#43842 [5.2] Feat: Showon for Use Global Option in ListField
  build/media_source/system/js/showon.es6.js
  libraries/src/Form/Field/ListField.php
Labels: Feature, RTC, NPM Resource Changed, PR-5.2-dev

#43829 [5.2] Feat: Introduce Mail Template Layout
  administrator/components/com_mails/config.xml
  administrator/components/com_mails/forms/template.xml
  administrator/components/com_mails/src/Field/MailtemplateLayoutField.php
  administrator/components/com_mails/src/Model/TemplateModel.php
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/com_mails.ini
  layouts/joomla/mail/mailtemplate.php
  libraries/src/Mail/MailTemplate.php
Labels: Feature, RTC, Language Change, PR-5.2-dev

#41662 [5.2] parent keyword misused
  administrator/components/com_associations/src/Controller/AssociationController.php
  api/components/com_modules/src/View/Modules/JsonapiView.php
  components/com_contact/src/View/Category/HtmlView.php
  components/com_content/src/View/Category/HtmlView.php
Labels: RTC, PR-5.2-dev

#43840 [5.2] Content Category Save to Menu
  administrator/components/com_categories/src/Controller/CategoryController.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-5.2-dev

#43846 Don't execute max system tests on pr commits
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#43863 Don't execute all system tests on any commit
  .drone.yml
Labels: Unit/System Tests, PR-5.1-dev

#43841 Add Language string DELETE_FROM_TRASH and replace alle occurences of …
  administrator/components/com_banners/src/View/Banners/HtmlView.php
  administrator/components/com_banners/src/View/Clients/HtmlView.php
  administrator/components/com_categories/src/View/Categories/HtmlView.php
  administrator/components/com_contact/src/View/Contacts/HtmlView.php
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_content/src/View/Featured/HtmlView.php
  administrator/components/com_fields/src/View/Fields/HtmlView.php
  administrator/components/com_fields/src/View/Groups/HtmlView.php
  administrator/components/com_guidedtours/src/View/Steps/HtmlView.php
  administrator/components/com_guidedtours/src/View/Tours/HtmlView.php
  administrator/components/com_languages/src/View/Languages/HtmlView.php
  administrator/components/com_menus/src/View/Items/HtmlView.php
  administrator/components/com_messages/src/View/Messages/HtmlView.php
  administrator/components/com_modules/src/View/Modules/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeeds/HtmlView.php
  administrator/components/com_redirect/src/View/Links/HtmlView.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_tags/src/View/Tags/HtmlView.php
  administrator/components/com_users/src/View/Notes/HtmlView.php
  administrator/components/com_workflow/src/View/Stages/HtmlView.php
  administrator/components/com_workflow/src/View/Transitions/HtmlView.php
  administrator/components/com_workflow/src/View/Workflows/HtmlView.php
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  libraries/src/MVC/View/ListView.php
Labels: RTC, Language Change, PR-5.2-dev
