Repository joomla/joomla-cms, pull requests merged in 2024-11, with the labels that each got.

#44392 [5] fix for Error with trashing items when items are checked out
  libraries/src/MVC/Model/AdminModel.php
Labels: RTC, bug, PR-5.2-dev

#44388 [5.2] Rename update SQL scripts 5.2.0-2024-09-24.sql to 5.2.1-2024-09-24.sql
  administrator/components/com_admin/sql/updates/mysql/5.2.1-2024-09-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.1-2024-09-24.sql
Labels: RTC, PR-5.2-dev

#44209 [5.2.] Fix Dark mode in user-captive view - Fix for Issue #43448
  administrator/components/com_users/tmpl/captive/select.php
  build/media_source/templates/administrator/atum/scss/pages/_com_users.scss
Labels: RTC, NPM Resource Changed, bug, Dark Mode, PR-5.2-dev

#44314 [5.2] Allow relative URLs in wrapper module and component
  components/com_wrapper/tmpl/wrapper/default.xml
  modules/mod_wrapper/mod_wrapper.xml
Labels: RTC, PR-5.2-dev

#44280 [5.2] fix for undefined property: $module
  plugins/actionlog/joomla/src/Extension/Joomla.php
Labels: RTC, PR-5.2-dev

#42962 [6.0] Remove deprecated db object from views
  administrator/components/com_users/src/View/Users/HtmlView.php
  components/com_content/src/View/Featured/HtmlView.php
  components/com_users/src/View/Profile/HtmlView.php
Labels: Feature, RTC, b/c break, PR-6.0-dev

#44283 [5.2] SEF URLs: Check if SEF plugin is published
  components/com_tags/src/Service/Router.php
  libraries/src/Component/Router/Rules/MenuRules.php
Labels: RTC, bug, PR-5.2-dev

#44393 [5][cypress] mod_articles
  tests/System/integration/site/modules/mod_articles/Default.cy.js
Labels: Unit/System Tests, PR-5.2-dev

#44176 [5.2] atum light mode - Fix modal window link color
  administrator/templates/atum/component.php
Labels: RTC, a11y, Backend Template, Dark Mode, PR-5.2-dev

#43321 [5.2] Error handling on extension update
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/language/en-GB/com_installer.ini
Labels: RTC, Language Change, bug, PR-5.2-dev

#44327 [5.2] Articles Module: Remove unused css + modified container query
  build/media_source/mod_articles/css/mod-articles.css
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#44410 [5.2] Fix JS errors in admin menu
  build/media_source/com_menus/js/admin-item-edit_container.es6.js
  build/media_source/system/js/treeselectmenu.es6.js
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#44342 Update debug.es6.js SanitizHTML DOM Text Interpretd as HTML
  build/media_source/com_finder/js/debug.es6.js
Labels: NPM Resource Changed, PR-5.2-dev

#43398 [5.2] Smart Search: Fix URL with highlight query
  plugins/system/highlight/src/Extension/Highlight.php
Labels: Feature, RTC, bug, PR-5.2-dev

#44425 [6.0] Upmerges - 2024-11-08
  administrator/components/com_guidedtours/src/View/Tour/HtmlView.php
Labels: PR-6.0-dev

#44295 [5.3] Add missing MVCFactoryInterface into model constructors
  administrator/components/com_actionlogs/src/Model/ActionlogsModel.php
  administrator/components/com_banners/src/Model/BannersModel.php
  administrator/components/com_banners/src/Model/ClientsModel.php
  administrator/components/com_banners/src/Model/TracksModel.php
  administrator/components/com_cache/src/Model/CacheModel.php
  administrator/components/com_contact/src/Model/ContactsModel.php
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_content/src/Model/FeaturedModel.php
  administrator/components/com_guidedtours/src/Model/StepsModel.php
  administrator/components/com_guidedtours/src/Model/ToursModel.php
  administrator/components/com_mails/src/Model/TemplatesModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  administrator/components/com_modules/src/Model/PositionsModel.php
  administrator/components/com_privacy/src/Model/ConsentsModel.php
  administrator/components/com_privacy/src/Model/RequestsModel.php
  administrator/components/com_workflow/src/Model/StagesModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowsModel.php
  components/com_contact/src/Model/CategoryModel.php
  components/com_contact/src/Model/FeaturedModel.php
  components/com_content/src/Model/ArticlesModel.php
  components/com_content/src/Model/CategoryModel.php
Labels: PR-5.3-dev

#44426 [5.2] Add required content filters for the administrator menu
  administrator/components/com_content/src/Model/ArticlesModel.php
Labels: RTC, PR-5.2-dev

#44422 [5.2] Add missing html elements to sanitizer for finder debugging
  build/media_source/com_finder/js/debug.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, PR-5.2-dev

#44306 [5.2] Fix reCAPTCHA Invisble error getElementsByClassName().forEach is not a function
  build/media_source/plg_captcha_recaptcha_invisible/js/recaptcha.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, bug, PR-5.2-dev

#44379 [5.2] Fix wrong core files and core folders permissions 777 on update from 5.2.0 or 5.2.1
  administrator/components/com_admin/script.php
Labels: RTC, Release Blocker, PR-5.2-dev

#44435 [5.2] Fix JS CS missing trailing comma
  tests/System/plugins/fs.mjs
Labels: Unit/System Tests, PR-5.2-dev

#44439 Removed hardcoded username from Actionlogs.cy.js
  tests/System/integration/administrator/components/com_actionlogs/Actionlogs.cy.js
Labels: Unit/System Tests, PR-5.2-dev

#44441 [5.2] Wrap long text to prevent layout displaying beyond viewport
  administrator/components/com_finder/src/Controller/IndexerController.php
Labels: RTC, bug, PR-5.2-dev

#44444 [5.3] Update README to J5.3
  README.md
  README.txt
Labels: PR-5.3-dev

#44446 [6.0] Upmerges - 2024-11-13
  administrator/components/com_actionlogs/src/Model/ActionlogsModel.php
  administrator/components/com_banners/src/Model/BannersModel.php
  administrator/components/com_banners/src/Model/ClientsModel.php
  administrator/components/com_banners/src/Model/TracksModel.php
  administrator/components/com_cache/src/Model/CacheModel.php
  administrator/components/com_contact/src/Model/ContactsModel.php
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_content/src/Model/FeaturedModel.php
  administrator/components/com_guidedtours/src/Model/StepsModel.php
  administrator/components/com_guidedtours/src/Model/ToursModel.php
  administrator/components/com_mails/src/Model/TemplatesModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  administrator/components/com_modules/src/Model/PositionsModel.php
  administrator/components/com_privacy/src/Model/ConsentsModel.php
  administrator/components/com_privacy/src/Model/RequestsModel.php
  administrator/components/com_workflow/src/Model/StagesModel.php
  administrator/components/com_workflow/src/Model/TransitionsModel.php
  administrator/components/com_workflow/src/Model/WorkflowsModel.php
  components/com_contact/src/Model/CategoryModel.php
  components/com_contact/src/Model/FeaturedModel.php
  components/com_content/src/Model/ArticlesModel.php
  components/com_content/src/Model/CategoryModel.php
Labels: PR-6.0-dev

#40613 [6.0] Added possibility to batch remove a tag
  administrator/language/en-GB/lib_joomla.ini
  build/media_source/layouts/js/joomla/html/batch/batch-tag-addremove.es6.js
  build/media_source/system/joomla.asset.json
  language/en-GB/lib_joomla.ini
  layouts/joomla/html/batch/tag.php
  libraries/src/Helper/TagsHelper.php
  libraries/src/MVC/Model/AdminModel.php
  plugins/behaviour/taggable/src/Extension/Taggable.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-6.0-dev

#44383 Deprecate methods for batch remove tag handling
  libraries/src/Helper/TagsHelper.php
  libraries/src/MVC/Model/AdminModel.php
Labels: PR-5.3-dev

#43822 [5.2] EmailRule unique should look at submitted input data instead of stored form data.
  libraries/src/Form/Rule/EmailRule.php
Labels: RTC, bug, PR-5.2-dev

#43444 "Attempt to assign property 'cleanURL' on bool" fix
  components/com_finder/src/Model/SearchModel.php
Labels: RTC, PR-5.2-dev

#44320 [5.2] mod_submenu php fixes
  administrator/modules/mod_submenu/src/Menu/Menu.php
Labels: RTC, PR-5.2-dev

#44114 [5.2] CalendarField: changing strftime to date
  libraries/src/Form/Field/CalendarField.php
  libraries/src/HTML/HTMLHelper.php
Labels: RTC, PR-5.2-dev

#44313 [5.2] Media manager fix default adapter handling
  administrator/components/com_media/src/Exception/ProviderAccountIsEmptyException.php
  administrator/components/com_media/src/Exception/ProviderAccountNotFoundException.php
  administrator/components/com_media/src/Exception/ProviderNotFoundException.php
  administrator/components/com_media/src/Provider/ProviderManager.php
  administrator/components/com_media/src/Provider/ProviderManagerHelperTrait.php
Labels: RTC, bug, PR-5.2-dev

#44428 [5.2] Harden FormattedTextLogger against object injection attacks
  libraries/src/Log/Logger/FormattedtextLogger.php
Labels: RTC, PR-5.2-dev

#44318 [5.2] mod_menu php fixes
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  libraries/src/Menu/AdministratorMenuItem.php
  libraries/src/Menu/MenuItem.php
Labels: RTC, PHP 8.x, PR-5.2-dev

#44362 Fix password toggle in dynamic subform field
  build/media_source/system/js/fields/passwordstrength.es6.js
  build/media_source/system/js/fields/passwordview.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.2-dev

#44418 [5.2] Check imagecolortransparent for validity
  libraries/src/Image/Image.php
Labels: RTC, bug, PR-5.2-dev

#43532 [5.3] Add Files folder to Media component and to "FileSystem local" adapter
  administrator/components/com_admin/src/Model/SysinfoModel.php
  administrator/components/com_media/config.xml
  administrator/components/com_media/src/Provider/ProviderManagerHelperTrait.php
  administrator/components/com_media/tmpl/media/default.php
  api/components/com_media/src/Model/MediumModel.php
  files/index.html
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  layouts/joomla/form/field/media.php
  libraries/src/Helper/PublicFolderGeneratorHelper.php
  plugins/editors/tinymce/src/Field/UploaddirsField.php
  plugins/filesystem/local/local.xml
  plugins/filesystem/local/src/Extension/Local.php
  tests/System/integration/api/com_media/Files.cy.js
Labels: Feature, RTC, Unit/System Tests, Documentation Required, RMDQ, PR-5.3-dev

#41300 [5.2] Fix Joomla.renderMessages not found with mod_login
  plugins/system/webauthn/src/PluginTraits/AdditionalLoginButtons.php
Labels: PBF, bug, Maintainers Checked, Small, PR-4.4-dev, PR-5.2-dev

#44461 [5.3] Fix deprecation message in installation
  installation/src/View/Remove/HtmlView.php
Labels: RTC, Release Blocker, PR-5.3-dev

#44359 [5.3] Form control fields removable token
  libraries/src/Form/Form.php
Labels: Feature, RTC, PR-5.3-dev

#44463 [5.3] Upmerge from 5.2-dev 2024-11-14 plus temporary fix for com_contact router tests
  administrator/components/com_media/src/Exception/ProviderAccountIsEmptyException.php
  administrator/components/com_media/src/Exception/ProviderAccountNotFoundException.php
  administrator/components/com_media/src/Exception/ProviderNotFoundException.php
  administrator/components/com_media/src/Provider/ProviderManager.php
  administrator/components/com_media/src/Provider/ProviderManagerHelperTrait.php
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  build/media_source/com_associations/js/sidebyside.es6.js
  build/media_source/system/js/fields/passwordstrength.es6.js
  build/media_source/system/js/fields/passwordview.es6.js
  libraries/src/Image/Image.php
  libraries/src/Log/Logger/FormattedtextLogger.php
  libraries/src/Menu/AdministratorMenuItem.php
  libraries/src/Menu/MenuItem.php
  tests/System/integration/site/components/com_contact/Router.cy.js
  tests/System/integration/site/components/com_content/Router.cy.js
Labels: Unit/System Tests, NPM Resource Changed, PR-5.3-dev

#44466 [5.2] Replace deprecated createRestorationFile with createUpdateFile
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
Labels: PR-5.2-dev, PR-5.3-dev

#44450 [5.3] Update deleted files in script.php for the upcoming 5.3.0-alpha1
  administrator/components/com_admin/script.php
Labels: PR-5.3-dev

#44459 [5.3] fix preprocess rule if contains alias (pgsql)
  libraries/src/Component/Router/Rules/PreprocessRules.php
Labels: PR-5.3-dev

#44467 [5.2] Rename update SQL scripts 5.2.1-2024-09-24.sql to 5.2.2-2024-09-24.sql
  administrator/components/com_admin/sql/updates/mysql/5.2.2-2024-09-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.2-2024-09-24.sql
Labels: RTC, PR-5.2-dev

#44471 [5.3] Upmerge changes from 5.2-dev 2024-11-18
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/5.2.2-2024-09-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.2-2024-09-24.sql
  administrator/components/com_guidedtours/src/Controller/StepController.php
  administrator/components/com_media/src/Exception/ProviderAccountIsEmptyException.php
  administrator/components/com_media/src/Exception/ProviderAccountNotFoundException.php
  administrator/components/com_media/src/Exception/ProviderNotFoundException.php
  libraries/src/Log/Logger/FormattedtextLogger.php
  libraries/src/Menu/AdministratorMenuItem.php
  plugins/system/webauthn/src/PluginTraits/AdditionalLoginButtons.php
Labels: PR-5.3-dev

#44483 [5.2] Fix fixFilesystemPermissions method in script.php for not existing folder
  administrator/components/com_admin/script.php
Labels: RTC, Release Blocker, PR-5.2-dev

#44487 [5.3] Upmerge changes from 5.2-dev 2024-11-19
  administrator/components/com_admin/script.php
  includes/incompatible.html
  installation/language/hr-HR/joomla.ini
  installation/language/hr-HR/langmetadata.xml
  installation/language/ta-IN/joomla.ini
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: Language Change, PR-5.3-dev

#44538 [6.0] Upmerges - 2024-11-27
  administrator/components/com_menus/src/View/Menutypes/HtmlView.php
  administrator/manifests/files/joomla.xml
  libraries/src/Component/Router/Rules/PreprocessRules.php
  libraries/src/Form/Form.php
  libraries/src/MVC/View/AbstractView.php
  libraries/src/String/StringableInterface.php
  libraries/src/Version.php
  plugins/fields/checkboxes/src/Extension/Checkboxes.php
  plugins/fields/list/src/Extension/ListPlugin.php
  plugins/fields/media/src/Extension/Media.php
  plugins/fields/radio/src/Extension/Radio.php
  plugins/fields/sql/src/Extension/SQL.php
  plugins/fields/subform/src/Extension/Subform.php
Labels: PR-6.0-dev

#44507 Fix joomlaExtButtons TinyMCE plugin, buttons validation
  build/media_source/plg_editors_tinymce/js/plugins/jxtdbuttons/plugin.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.2-dev

#42493 [5.2] Set correct AssetTitle and AssetParentId
  administrator/components/com_scheduler/src/Table/TaskTable.php
Labels: RTC, bug, PR-5.2-dev

#44476 [5.2] mod articles_news
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
Labels: RTC, bug, PR-5.2-dev

#44478 [5.2] mod articles_category
  modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
Labels: RTC, bug, PR-5.2-dev

#44475 [5.2] mod articles
  modules/mod_articles/src/Helper/ArticlesHelper.php
Labels: RTC, bug, PR-5.2-dev

#44500 [5.2] Allow multiselect for checkboxes
  build/media_source/system/js/multiselect.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.2-dev

#44384 [5.2]postgres and finder suggestions
  components/com_finder/src/Model/SuggestionsModel.php
Labels: RTC, bug, PR-5.2-dev

#44543 [5.2] Fix PHPCS nullable parameter
  administrator/components/com_scheduler/src/Table/TaskTable.php
Labels: PR-5.2-dev

#44539 Remove unused variable
  modules/mod_articles_categories/tmpl/default_items.php
Labels: RTC, PR-5.2-dev

#44544 [6.0] Revert wrong version changes from previous upmerge
  administrator/manifests/files/joomla.xml
  libraries/src/Version.php
Labels: PR-6.0-dev

#44464 Add category node as universal object in PHPStan
  build/phpstan/phpstan.neon
Labels: RTC, PR-5.2-dev

#44513 [6.0] Remove fixFilesystemPermissions method from script.php
  administrator/components/com_admin/script.php
Labels: Feature, RTC, PR-6.0-dev

#44512 [6.0] Delete 5.2.2-2024-09-24.sql update SQL scripts
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/5.2.2-2024-09-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.2-2024-09-24.sql
Labels: Feature, RTC, PR-6.0-dev

#44555 [5.2] Uncaught TypeError: can't access property "getAttribute", toggleButton is null
  build/media_source/system/js/fields/passwordview.es6.js
Labels: RTC, Release Blocker, NPM Resource Changed, bug, PR-5.2-dev
