Repository joomla/joomla-cms, pull requests merged in 2024-02, with the labels that each got.

#39180 [5.0] Find proper script for file uninstall
  libraries/src/Installer/Adapter/FileAdapter.php
Labels: RTC, J4 Issue, PBF, bug, Maintainers Checked, PR-5.0-dev, Small

#42719 [5.1] Add main region on error page
  templates/cassiopeia/error.php
Labels: Feature, RTC, PR-5.1-dev

#42746 [5.1] Use Dialog for scheduler task "Run test"
  administrator/components/com_scheduler/tmpl/tasks/default.php
  build/media_source/com_scheduler/joomla.asset.json
  build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42715 [5.1] Replace deprecated KeyboardEvent code
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  build/media_source/system/js/fields/calendar.es5.js
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42651 [5.1] Template Long Description
  administrator/components/com_templates/tmpl/style/edit.php
Labels: Feature, RTC, PR-5.1-dev

#42747 Add link to JED - schema plugins category in schema plugin form
  administrator/language/en-GB/plg_system_schemaorg.ini
  plugins/system/schemaorg/forms/schemaorg.xml
  plugins/system/schemaorg/src/Extension/Schemaorg.php
Labels: RTC, Language Change, PR-5.1-dev

#40415 [5.0] Switching Input object from CMS to framework class
  administrator/components/com_actionlogs/src/Controller/ActionlogsController.php
  administrator/components/com_users/src/Controller/UsersController.php
  administrator/components/com_workflow/src/View/Transition/HtmlView.php
  components/com_config/src/Controller/ConfigController.php
  components/com_config/src/Controller/ModulesController.php
  components/com_config/src/Controller/TemplatesController.php
  components/com_contact/src/Controller/DisplayController.php
  components/com_content/src/Controller/DisplayController.php
  components/com_contenthistory/src/Controller/DisplayController.php
  components/com_fields/src/Controller/DisplayController.php
  components/com_modules/src/Controller/DisplayController.php
  installation/src/Application/InstallationApplication.php
  installation/src/Controller/InstallationController.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/BaseApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Application/WebApplication.php
  plugins/multifactorauth/email/src/Extension/Email.php
Labels: Feature, PR-5.0-dev, PR-5.1-dev

#42744 [4.4] process fields on fulltext
  plugins/content/fields/src/Extension/Fields.php
Labels: RTC, PR-4.4-dev

#42741 [#42733] Fixes menu verification check for menu types with Unicode characters
  administrator/components/com_menus/src/Controller/DisplayController.php
Labels: RTC, bug, PR-4.4-dev

#42697 Update Nested.php to support aliasing the 'checked_out' column.
  libraries/src/Table/Nested.php
Labels: RTC, PR-4.4-dev

#42759 [5.1] Upmerge 2024-02-04
  libraries/src/Installer/Adapter/FileAdapter.php
Labels: PR-5.1-dev

#42725 [4.4] Smart Search: Don't search for alternative images
  components/com_finder/tmpl/search/default_result.php
Labels: RTC, bug, PR-4.4-dev

#42764 Revert "[5.0] Switching Input object from CMS to framework class"
  administrator/components/com_actionlogs/src/Controller/ActionlogsController.php
  administrator/components/com_users/src/Controller/UsersController.php
  administrator/components/com_workflow/src/View/Transition/HtmlView.php
  components/com_config/src/Controller/ConfigController.php
  components/com_config/src/Controller/ModulesController.php
  components/com_config/src/Controller/TemplatesController.php
  components/com_contact/src/Controller/DisplayController.php
  components/com_content/src/Controller/DisplayController.php
  components/com_contenthistory/src/Controller/DisplayController.php
  components/com_fields/src/Controller/DisplayController.php
  components/com_modules/src/Controller/DisplayController.php
  installation/src/Application/InstallationApplication.php
  installation/src/Controller/InstallationController.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/BaseApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Application/WebApplication.php
  plugins/multifactorauth/email/src/Extension/Email.php
Labels: PR-5.1-dev

#42687 [4.4] Language Filter strings
  administrator/components/com_finder/src/Helper/LanguageHelper.php
Labels: RTC, bug, PR-4.4-dev

#42773 [4.4] Fix strpos(): Passing null is deprecated
  plugins/content/fields/src/Extension/Fields.php
Labels: RTC, Release Blocker, bug, PR-4.4-dev

#42785 [5.1] Update deleted files list in script.php for 5.1.0-alpha4
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#42782 [5.0] - Fix API menus/site/items
  administrator/components/com_menus/src/Field/MenutypeField.php
Labels: PR-5.0-dev

#42789 [5.1] upmerge 2024-02-11
  administrator/components/com_finder/src/Helper/LanguageHelper.php
  administrator/components/com_menus/src/Controller/DisplayController.php
  administrator/components/com_menus/src/Field/MenutypeField.php
  components/com_finder/tmpl/search/default_result.php
  libraries/src/Table/Nested.php
  plugins/content/fields/src/Extension/Fields.php
  tests/System/integration/api/com_menus/SiteMenuItems.cy.js
Labels: Unit/System Tests, PR-5.1-dev

#42470 [4.4] Update phpseclib to 3.0.34
  composer.lock
Labels: Composer Dependency Changed, PR-4.4-dev

#40994 [5.1] Guided Tours - Add checkbox/radio/select target element support, enhanced required field handling
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-02-10.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-02-10.sql
  administrator/components/com_guidedtours/forms/step.xml
  administrator/components/com_guidedtours/src/Extension/GuidedtoursComponent.php
  administrator/components/com_guidedtours/src/Model/StepsModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_guidedtours/src/Table/StepTable.php
  administrator/components/com_guidedtours/tmpl/step/edit.php
  administrator/language/en-GB/com_guidedtours.ini
  build/media_source/com_guidedtours/joomla.asset.json
  build/media_source/com_guidedtours/js/tour-edit.es6.js
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-5.1-dev

#42780 [5.1] Update Jooa11y with latest Sa11y build (Attempt #2)
  administrator/language/en-GB/plg_system_jooa11y.ini
  administrator/language/en-GB/plg_system_jooa11y.sys.ini
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/build-modules-js/settings.json
  build/media_source/plg_behaviour_compat/es5.asset.json
  build/media_source/plg_system_jooa11y/joomla.asset.json
  build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
  build/media_source/plg_system_jooa11y/scss/jooa11y.scss
  package-lock.json
  package.json
  plugins/system/jooa11y/jooa11y.xml
  plugins/system/jooa11y/src/Extension/Jooa11y.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-5.1-dev

#42693 [4.4] Finder: Fixing language of token
  administrator/components/com_finder/src/Indexer/Token.php
Labels: bug, PR-4.4-dev

#42820 [4.4] Fix help icon not opening help screen
  build/media_source/legacy/js/toolbar.es5.js
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#42803 [4] Module 'Feed Display': deprecated Notice
  administrator/modules/mod_feed/tmpl/default.php
  modules/mod_feed/tmpl/default.php
Labels: RTC, PHP 8.x, PR-4.4-dev

#42815 [4.4] tags learn more link
  administrator/components/com_tags/tmpl/tags/emptystate.php
Labels: RTC, PR-4.4-dev

#42849 [4.4] Composer update joomla/filter to 2.0.4
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.4-dev

#42855 [4.4] alphabetical sorting string JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: RTC, Language Change, PR-4.4-dev

#42845 [5.1] Convert mod_multilangstatus to service provider
  administrator/modules/mod_multilangstatus/mod_multilangstatus.php
  administrator/modules/mod_multilangstatus/mod_multilangstatus.xml
  administrator/modules/mod_multilangstatus/services/provider.php
  administrator/modules/mod_multilangstatus/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42866 [5.1] Convert mod_sampledata to service provider
  administrator/modules/mod_sampledata/mod_sampledata.php
  administrator/modules/mod_sampledata/mod_sampledata.xml
  administrator/modules/mod_sampledata/services/provider.php
  administrator/modules/mod_sampledata/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_sampledata/src/Helper/SampledataHelper.php
Labels: RTC, PR-5.1-dev

#42853 [5.1] Convert mod_frontend to service provider
  administrator/modules/mod_frontend/mod_frontend.php
  administrator/modules/mod_frontend/mod_frontend.xml
  administrator/modules/mod_frontend/services/provider.php
  administrator/modules/mod_frontend/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42852 [5.1] Convert mod_user to service provider
  administrator/modules/mod_user/mod_user.php
  administrator/modules/mod_user/mod_user.xml
  administrator/modules/mod_user/services/provider.php
  administrator/modules/mod_user/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42838 [5.1] Convert mod_toolbar to service provider
  administrator/modules/mod_toolbar/mod_toolbar.php
  administrator/modules/mod_toolbar/mod_toolbar.xml
  administrator/modules/mod_toolbar/services/provider.php
  administrator/modules/mod_toolbar/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42827 [5.1] Convert mod_loginsupport to service provider
  administrator/modules/mod_loginsupport/mod_loginsupport.php
  administrator/modules/mod_loginsupport/mod_loginsupport.xml
  administrator/modules/mod_loginsupport/services/provider.php
  administrator/modules/mod_loginsupport/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42801 [5.1] Convert mod_title to service provider
  administrator/modules/mod_title/mod_title.php
  administrator/modules/mod_title/mod_title.xml
  administrator/modules/mod_title/services/provider.php
  administrator/modules/mod_title/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42699 [5.1] Schemaorg => Generic plugin
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-02-25.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-02-25.sql
  administrator/language/en-GB/plg_schemaorg_custom.ini
  administrator/language/en-GB/plg_schemaorg_custom.sys.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/schemaorg/custom/custom.xml
  plugins/schemaorg/custom/forms/schemaorg.xml
  plugins/schemaorg/custom/services/provider.php
  plugins/schemaorg/custom/src/Extension/Custom.php
Labels: Feature, RTC, Language Change, PBF, PR-5.1-dev

#42872 [4.4] Fix wrong redirection for saving user account
  administrator/components/com_users/src/Controller/UserController.php
Labels: RTC, PR-4.4-dev

#42692 [5.1] Implement onAfterInitialiseRouter event
  libraries/src/Event/Router/AfterInitialiseRouterEvent.php
  libraries/src/Event/Router/RouterEvent.php
  libraries/src/Service/Provider/Router.php
  plugins/system/languagefilter/services/provider.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: Feature, RTC, PR-5.1-dev

#42781 Convert mod_stats to service provider
  modules/mod_stats/mod_stats.php
  modules/mod_stats/mod_stats.xml
  modules/mod_stats/services/provider.php
  modules/mod_stats/src/Dispatcher/Dispatcher.php
  modules/mod_stats/tmpl/default.php
Labels: RTC, PR-5.1-dev

#42792 [5.1] Convert mod_wrapper to service provider
  modules/mod_wrapper/mod_wrapper.php
  modules/mod_wrapper/mod_wrapper.xml
  modules/mod_wrapper/services/provider.php
  modules/mod_wrapper/src/Dispatcher/Dispatcher.php
  modules/mod_wrapper/src/Helper/WrapperHelper.php
Labels: RTC, PR-5.1-dev

#42756 [5.1] Fix user field validation on change
  build/media_source/system/js/fields/joomla-field-user.w-c.es6.js
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#42755 [5.1] Fix content history diff error
  build/media_source/com_contenthistory/joomla.asset.json
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#42776 [5.1] Rewrite treeselect in vanilla JS
  administrator/components/com_modules/tmpl/module/edit_assignment.php
  build/media_source/legacy/joomla.asset.json
  build/media_source/legacy/js/treeselectmenu.es5.js
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/treeselectmenu.es6.js
Labels: Feature, Updates Requested, NPM Resource Changed, PR-5.1-dev

#42880 [5.1] WebAssetManager: reset sorting state when new item enabled or disabled
  libraries/src/WebAsset/WebAssetManager.php
Labels: RTC, Release Blocker, bug, PR-5.1-dev

#42814 [5.1] Convert mod_version to service provider
  administrator/modules/mod_version/mod_version.php
  administrator/modules/mod_version/mod_version.xml
  administrator/modules/mod_version/services/provider.php
  administrator/modules/mod_version/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_version/src/Helper/VersionHelper.php
Labels: RTC, PR-5.1-dev

#42805 [6.0] Switching Input object from CMS to framework class
  administrator/components/com_actionlogs/src/Controller/ActionlogsController.php
  administrator/components/com_users/src/Controller/UsersController.php
  administrator/components/com_workflow/src/View/Transition/HtmlView.php
  components/com_config/src/Controller/ConfigController.php
  components/com_config/src/Controller/ModulesController.php
  components/com_config/src/Controller/TemplatesController.php
  components/com_contact/src/Controller/DisplayController.php
  components/com_content/src/Controller/DisplayController.php
  components/com_contenthistory/src/Controller/DisplayController.php
  components/com_fields/src/Controller/DisplayController.php
  components/com_modules/src/Controller/DisplayController.php
  installation/src/Application/InstallationApplication.php
  installation/src/Controller/InstallationController.php
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/BaseApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
  libraries/src/Application/WebApplication.php
  plugins/multifactorauth/email/src/Extension/Email.php
Labels: b/c break, PR-6.0-dev

#37993 [4.4] JTable::store(true) to update NULLs fails if assets are tracked
  libraries/src/Table/Table.php
Labels: RTC, PBF, bug, Maintainers Checked, Small, PR-4.4-dev

#42799 [5.1] TUF-based core updates
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-02-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-02-24.sql
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/update.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/lib_joomla.ini
  composer.json
  composer.lock
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Factory.php
  libraries/src/Http/HttpFactory.php
  libraries/src/Http/HttpFactoryInterface.php
  libraries/src/Service/Provider/Http.php
  libraries/src/TUF/DatabaseStorage.php
  libraries/src/TUF/HttpLoader.php
  libraries/src/TUF/TufFetcher.php
  libraries/src/Table/Tuf.php
  libraries/src/Updater/Adapter/CollectionAdapter.php
  libraries/src/Updater/Adapter/TufAdapter.php
  libraries/src/Updater/ConstraintChecker.php
  libraries/src/Updater/Update.php
  libraries/src/Updater/Updater.php
  tests/System/fixtures/tuf/invalidMetadata.json
  tests/System/fixtures/tuf/validMetadata.json
  tests/System/integration/administrator/components/com_joomlaupdate/Update.cy.js
  tests/System/support/commands/db.js
  tests/Unit/Libraries/Cms/Updater/ConstraintCheckerTest.php
  tests/Unit/Libraries/Cms/Updater/TufAdapterTest.php
  tests/Unit/Libraries/Tuf/DatabaseStorageTest.php
  tests/Unit/Libraries/Tuf/HttpLoaderTest.php
Labels: Feature, RTC, Unit/System Tests, Language Change, Composer Dependency Changed, Release Blocker, PR-5.1-dev

#42886 [5.1] Convert mod_stats_admin to service provider
  administrator/modules/mod_stats_admin/mod_stats_admin.php
  administrator/modules/mod_stats_admin/mod_stats_admin.xml
  administrator/modules/mod_stats_admin/services/provider.php
  administrator/modules/mod_stats_admin/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_stats_admin/src/Helper/StatsAdminHelper.php
Labels: RTC, PR-5.1-dev

#42883 [5.1] Convert mod_syndicate to service provider
  modules/mod_syndicate/mod_syndicate.php
  modules/mod_syndicate/mod_syndicate.xml
  modules/mod_syndicate/services/provider.php
  modules/mod_syndicate/src/Dispatcher/Dispatcher.php
  modules/mod_syndicate/src/Helper/SyndicateHelper.php
Labels: RTC, PR-5.1-dev

#42877 [5.1] Convert mod_custom to service provider
  administrator/modules/mod_custom/mod_custom.php
  administrator/modules/mod_custom/mod_custom.xml
  administrator/modules/mod_custom/services/provider.php
  administrator/modules/mod_custom/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#42868 [5.1] Use local $container instead of getting from Factory
  plugins/system/schemaorg/services/provider.php
Labels: RTC, PR-5.1-dev

#42784 [5.1] Minor cleanup for modules JS
  build/media_source/mod_menu/js/admin-menu.es6.js
  build/media_source/mod_menu/js/menu.es6.js
  build/media_source/mod_quickicon/js/quickicon.es6.js
  build/media_source/mod_sampledata/js/sampledata-process.es6.js
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#42735 Convert mod_messages to service provider
  administrator/modules/mod_messages/mod_messages.php
  administrator/modules/mod_messages/mod_messages.xml
  administrator/modules/mod_messages/services/provider.php
  administrator/modules/mod_messages/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_messages/src/Helper/MessagesHelper.php
Labels: RTC, PR-5.1-dev

#42885 [5.1] Unit test for WebAsset stuff
  tests/Unit/Libraries/Cms/WebAsset/WebAssetManagerTest.php
  tests/Unit/Libraries/Cms/WebAsset/WebAssetRegistryTest.php
  tests/Unit/Libraries/Cms/WebAsset/asset.registry-corrupted.json
  tests/Unit/Libraries/Cms/WebAsset/asset.registry.json
Labels: Feature, Unit/System Tests, PR-5.1-dev

#42717 Change the getItem return type to stdClass and make the CMSObject inherit it
  administrator/components/com_guidedtours/src/Model/StepModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_installer/src/Model/UpdatesiteModel.php
  administrator/components/com_mails/src/Model/TemplateModel.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Object/CMSObject.php
  libraries/src/Workflow/WorkflowPluginTrait.php
Labels: RTC, PR-5.1-dev

#41388 [5.0] Improve DX on the com_templates(styles)
  administrator/components/com_templates/tmpl/style/edit.php
Labels: Feature, RTC, PR-5.1-dev

#42726 [5.1] Replace deprecated substr() with substring()
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  build/media_source/system/js/fields/calendar-locales/date/gregorian/date-helper.es5.js
  build/media_source/system/js/fields/calendar-locales/date/jalali/date-helper.es5.js
  build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js
  build/media_source/system/js/inlinehelp.es6.js
Labels: RTC, Language Change, NPM Resource Changed, PBF, PR-5.1-dev

#42901 [5.1] Languagefilter: Fix implementation of subscriberinterface
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: RTC, PR-5.1-dev

#42904 [5.1] Replace JPATH_PLATFORM with _JEXEC
  libraries/src/TUF/DatabaseStorage.php
  libraries/src/TUF/TufFetcher.php
Labels: PR-5.1-dev

#42881 [5.1] Give a name for the breadcrumbs schema.org asset
  modules/mod_breadcrumbs/tmpl/default.php
Labels: RTC, PR-5.1-dev

#42215 [5.1] Convert mod_feed to service provider
  modules/mod_feed/mod_feed.php
  modules/mod_feed/mod_feed.xml
  modules/mod_feed/services/provider.php
  modules/mod_feed/src/Dispatcher/Dispatcher.php
  modules/mod_feed/src/Helper/FeedHelper.php
  tests/System/integration/site/modules/mod_feed/Default.cy.js
Labels: Feature, RTC, Unit/System Tests, PR-5.1-dev

#42898 [5.1] Convert mod_tags_similar to service provider
  modules/mod_tags_similar/mod_tags_similar.php
  modules/mod_tags_similar/mod_tags_similar.xml
  modules/mod_tags_similar/services/provider.php
  modules/mod_tags_similar/src/Dispatcher/Dispatcher.php
  modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
Labels: RTC, PR-5.1-dev

#42899 [5.1] Convert mod_tags_popular to service provider
  modules/mod_tags_popular/mod_tags_popular.php
  modules/mod_tags_popular/mod_tags_popular.xml
  modules/mod_tags_popular/services/provider.php
  modules/mod_tags_popular/src/Dispatcher/Dispatcher.php
  modules/mod_tags_popular/src/Helper/TagsPopularHelper.php
Labels: RTC, PR-5.1-dev

#42709 [5.1] Fix Form::renderField() can cause duplicate database queries
  libraries/src/Form/Field/CalendarField.php
  libraries/src/Form/Field/CheckboxesField.php
  libraries/src/Form/Field/ColorField.php
  libraries/src/Form/Field/ComboField.php
  libraries/src/Form/Field/ContenthistoryField.php
  libraries/src/Form/Field/EmailField.php
  libraries/src/Form/Field/FileField.php
  libraries/src/Form/Field/GroupedlistField.php
  libraries/src/Form/Field/HiddenField.php
  libraries/src/Form/Field/ListField.php
  libraries/src/Form/Field/MediaField.php
  libraries/src/Form/Field/MeterField.php
  libraries/src/Form/Field/ModalSelectField.php
  libraries/src/Form/Field/ModuleorderField.php
  libraries/src/Form/Field/NumberField.php
  libraries/src/Form/Field/PasswordField.php
  libraries/src/Form/Field/RadiobasicField.php
  libraries/src/Form/Field/RangeField.php
  libraries/src/Form/Field/RulesField.php
  libraries/src/Form/Field/SubformField.php
  libraries/src/Form/Field/TagField.php
  libraries/src/Form/Field/TelephoneField.php
  libraries/src/Form/Field/TextField.php
  libraries/src/Form/Field/TextareaField.php
  libraries/src/Form/Field/TimeField.php
  libraries/src/Form/Field/UrlField.php
  libraries/src/Form/Field/UserField.php
  libraries/src/Form/FormField.php
  plugins/editors/tinymce/src/Field/TinymcebuilderField.php
Labels: RTC, bug, PR-5.1-dev

#42869 [4.4] Fix Banners application crashes
  administrator/components/com_banners/src/Helper/BannersHelper.php
Labels: RTC, PR-4.4-dev

#42702 [5.1] SEF: Implementing trailing slash behavior
  administrator/language/en-GB/plg_system_sef.ini
  plugins/system/sef/sef.xml
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, Language Change, PR-5.1-dev

#42832 [5.1] Adding notice to global configuration for additional options in SEF plugin
  administrator/components/com_config/tmpl/application/default_cache.php
  administrator/components/com_config/tmpl/application/default_cookie.php
  administrator/components/com_config/tmpl/application/default_database.php
  administrator/components/com_config/tmpl/application/default_debug.php
  administrator/components/com_config/tmpl/application/default_filters.php
  administrator/components/com_config/tmpl/application/default_locale.php
  administrator/components/com_config/tmpl/application/default_logging.php
  administrator/components/com_config/tmpl/application/default_logging_custom.php
  administrator/components/com_config/tmpl/application/default_mail.php
  administrator/components/com_config/tmpl/application/default_metadata.php
  administrator/components/com_config/tmpl/application/default_proxy.php
  administrator/components/com_config/tmpl/application/default_seo.php
  administrator/components/com_config/tmpl/application/default_server.php
  administrator/components/com_config/tmpl/application/default_session.php
  administrator/components/com_config/tmpl/application/default_site.php
  administrator/components/com_config/tmpl/application/default_webservices.php
  administrator/language/en-GB/com_config.ini
  layouts/joomla/content/options_default.php
Labels: RTC, Language Change, PR-5.1-dev

#42657 [5.1] Form: Add regex validation rule
  libraries/src/Form/Rule/RegexRule.php
Labels: Feature, RTC, PR-5.1-dev

#39506 [5.1] New Article site
  components/com_content/tmpl/category/blog.php
Labels: Feature, RTC, PBF, Small, PR-5.1-dev

#36692 Use a sensible default if none is found
  libraries/src/Installer/Adapter/ModuleAdapter.php
Labels: RTC, PBF, bug, Small, PR-4.4-dev

#42916 [5.1] Upmerge 2024-02-28
  administrator/components/com_banners/src/Helper/BannersHelper.php
Labels: PR-5.1-dev

#42508 [5.1] Replace hard coded img element by JLayout joomla.html.image and DRY
  modules/mod_banners/tmpl/default.php
Labels: Feature, RTC, PBF, PR-5.1-dev

#41980 [5.1] Unused imports
  administrator/components/com_guidedtours/src/View/Tour/HtmlView.php
  administrator/components/com_users/src/Helper/Mfa.php
  components/com_contact/tmpl/contact/default_links.php
  libraries/src/Error/JsonApi/AuthenticationFailedExceptionHandler.php
  libraries/src/Error/JsonApi/CheckinCheckoutExceptionHandler.php
  libraries/src/Error/JsonApi/InvalidParameterExceptionHandler.php
  libraries/src/Error/JsonApi/InvalidRouteExceptionHandler.php
  libraries/src/Error/JsonApi/NotAcceptableExceptionHandler.php
  libraries/src/Error/JsonApi/NotAllowedExceptionHandler.php
  libraries/src/Error/JsonApi/ResourceNotFoundExceptionHandler.php
  libraries/src/Error/JsonApi/SaveExceptionHandler.php
  libraries/src/Error/JsonApi/SendEmailExceptionHandler.php
  libraries/src/Event/Result/ResultAware.php
  libraries/src/Event/Table/AfterMoveEvent.php
  libraries/src/Form/Field/CalendarField.php
  libraries/src/Mail/MailerFactory.php
  plugins/fields/subform/src/Extension/Subform.php
  plugins/multifactorauth/email/src/Extension/Email.php
  plugins/multifactorauth/fixed/src/Extension/Fixed.php
  plugins/multifactorauth/totp/src/Extension/Totp.php
  plugins/multifactorauth/webauthn/src/Extension/Webauthn.php
  plugins/multifactorauth/webauthn/src/Helper/Credentials.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/system/debug/src/Extension/Debug.php
  plugins/system/webauthn/src/Authentication.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerLogin.php
  plugins/task/deleteactionlogs/src/Extension/DeleteActionLogs.php
  plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
  plugins/task/rotatelogs/src/Extension/RotateLogs.php
  plugins/task/sessiongc/src/Extension/SessionGC.php
  plugins/user/profile/src/Extension/Profile.php
  plugins/workflow/notification/src/Extension/Notification.php
Labels: Feature, RTC, Maintainers Checked, PR-5.1-dev

#42906 [5.1] Followup convert mod_messages to service provider #42735
  administrator/modules/mod_messages/src/Helper/MessagesHelper.php
Labels: RTC, PR-5.1-dev

#42704 [5.1] SEF: Implementing index.php behavior
  administrator/language/en-GB/plg_system_sef.ini
  plugins/system/sef/sef.xml
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, Language Change, PR-5.1-dev

#42910 [5.1] Convert mod_latestactions to service provider
  administrator/modules/mod_latestactions/mod_latestactions.php
  administrator/modules/mod_latestactions/mod_latestactions.xml
  administrator/modules/mod_latestactions/services/provider.php
  administrator/modules/mod_latestactions/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_latestactions/src/Helper/LatestActionsHelper.php
Labels: RTC, PR-5.1-dev
