Repository joomla/joomla-cms, pull requests merged in 2024-12, with the labels that each got.

#44562 [5.3] Upmerge changes from 5.2-dev 2024-12-01
  administrator/components/com_scheduler/src/Table/TaskTable.php
  administrator/templates/atum/index.php
  build/media_source/plg_editors_tinymce/js/plugins/jxtdbuttons/plugin.es6.js
  build/media_source/system/js/fields/passwordview.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/multiselect.es6.js
  build/phpstan/phpstan.neon
  components/com_finder/src/Model/SuggestionsModel.php
  components/com_users/tmpl/method/edit.php
  libraries/src/Updater/Update.php
  modules/mod_articles/src/Helper/ArticlesHelper.php
  modules/mod_articles_categories/tmpl/default_items.php
  modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
Labels: NPM Resource Changed, PR-5.3-dev

#44269 [5.3] xml manifest corrections
  administrator/components/com_actionlogs/actionlogs.xml
  administrator/components/com_admin/admin.xml
  administrator/components/com_banners/banners.xml
  administrator/components/com_messages/messages.xml
  administrator/components/com_workflow/workflow.xml
  administrator/manifests/libraries/joomla.xml
  plugins/editors/tinymce/tinymce.xml
Labels: Feature, RTC, PR-5.3-dev

#44525 [5.2] Plugins: Search not case-insensitive for unicode language
  administrator/components/com_plugins/src/Model/PluginsModel.php
Labels: RTC, bug, PR-5.2-dev

#44173 [5.2] Fix increment on non-alphanumeric string deprecation
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_tags/src/Model/TagModel.php
Labels: RTC, PHP 8.x, bug, PR-5.2-dev

#44519 [5.2] User: Don't reset newly set requireReset
  libraries/src/User/User.php
Labels: RTC, bug, PR-5.2-dev

#44540 [5.2] Tags: Make router discover 404s properly
  components/com_tags/src/Service/Router.php
Labels: RTC, bug, PR-5.2-dev

#44358 [5.2] Catch exception to get the user in the action log model
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
Labels: RTC, bug, PR-5.2-dev

#44559 Update tests ESM references
  tests/System/README.md
Labels: Unit/System Tests, PR-5.2-dev

#44550 [5.3] Actionlogs User filter
  administrator/components/com_actionlogs/forms/filter_actionlogs.xml
  administrator/components/com_actionlogs/src/Field/LogcreatorField.php
Labels: RTC, bug, PR-5.3-dev

#44523 [5.3] Contact icons etc [a11y]
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/contact/default_address.php
Labels: Feature, RTC, a11y, PR-5.3-dev

#44515 [5.3] Tags: Fix broken aliases in routing
  components/com_tags/src/Service/Router.php
Labels: Feature, RTC, PR-5.3-dev

#44486 [5.3]Sort order of fields relative to their actual location in the table
  administrator/components/com_content/forms/filter_articles.xml
  administrator/components/com_content/forms/filter_featured.xml
  administrator/components/com_content/src/Model/ArticlesModel.php
  libraries/src/Form/Field/ListField.php
Labels: Feature, RTC, PR-5.3-dev

#44485 [5.3] Smart Search: Improve Indexer::optimize()
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Taxonomy.php
Labels: Feature, RTC, PR-5.3-dev

#44477 [5.3] Router: Discover tainted URLs for core components
  components/com_contact/src/Service/Router.php
  components/com_content/src/Service/Router.php
  components/com_newsfeeds/src/Service/Router.php
Labels: Feature, RTC, PR-5.3-dev

#44455 [5.3] Routing: Allow to mark parsed URLs as tainted
  libraries/src/Router/Router.php
  plugins/system/sef/src/Extension/Sef.php
Labels: Feature, RTC, PR-5.3-dev

#44577 [4.4] Backport Debug build script
  .drone.yml
  build/build.php
Labels: Unit/System Tests, PR-4.4-dev

#44580 [4.4] Only build zstd format for debug builds
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#44581 [5.2] Backport debug build
  .drone.yml
  build/build.php
Labels: Unit/System Tests, PR-5.2-dev

#44579 [6.0] Upmerges - 2024-12-04
  .drone.yml
  administrator/components/com_actionlogs/actionlogs.xml
  administrator/components/com_actionlogs/forms/filter_actionlogs.xml
  administrator/components/com_actionlogs/src/Field/LogcreatorField.php
  administrator/components/com_admin/admin.xml
  administrator/components/com_banners/banners.xml
  administrator/components/com_content/forms/filter_articles.xml
  administrator/components/com_content/forms/filter_featured.xml
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Taxonomy.php
  administrator/components/com_messages/messages.xml
  administrator/components/com_scheduler/src/Table/TaskTable.php
  administrator/components/com_workflow/workflow.xml
  administrator/manifests/libraries/joomla.xml
  administrator/templates/atum/index.php
  build/build.php
  build/media_source/plg_editors_tinymce/js/plugins/jxtdbuttons/plugin.es6.js
  build/media_source/system/js/fields/passwordview.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/multiselect.es6.js
  build/phpstan/phpstan.neon
  components/com_contact/src/Service/Router.php
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/tmpl/contact/default.php
  components/com_contact/tmpl/contact/default_address.php
  components/com_content/src/Service/Router.php
  components/com_finder/src/Model/SuggestionsModel.php
  components/com_newsfeeds/src/Service/Router.php
  components/com_tags/src/Service/Router.php
  components/com_users/tmpl/method/edit.php
  libraries/src/Form/Field/ListField.php
  libraries/src/Router/Router.php
  libraries/src/Updater/Update.php
  modules/mod_articles/src/Helper/ArticlesHelper.php
  modules/mod_articles_categories/tmpl/default_items.php
  modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php
  modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php
  plugins/editors/tinymce/tinymce.xml
  plugins/system/sef/src/Extension/Sef.php
Labels: Unit/System Tests, Test instructions missing, NPM Resource Changed, PR-6.0-dev

#44582 [6.0] Upmerge 241204
  .drone.yml
Labels: Unit/System Tests, PR-6.0-dev

#42530 [5.3] [com_scheduler] task execution history view
  administrator/components/com_admin/sql/updates/mysql/5.3.0-2024-10-26.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.0-2024-10-26.sql
  administrator/components/com_scheduler/forms/filter_logs.xml
  administrator/components/com_scheduler/src/Controller/LogsController.php
  administrator/components/com_scheduler/src/Field/ExitCodeField.php
  administrator/components/com_scheduler/src/Model/LogsModel.php
  administrator/components/com_scheduler/src/Table/LogsTable.php
  administrator/components/com_scheduler/src/View/Logs/HtmlView.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_scheduler/tmpl/logs/default.php
  administrator/language/en-GB/com_scheduler.ini
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  plugins/system/tasknotification/src/Extension/TaskNotification.php
Labels: Feature, Language Change, PR-5.3-dev

#44567 [5.2] Fix return typehint in IdentityAware trait
  libraries/src/Application/IdentityAware.php
Labels: PR-5.2-dev

#42961 [6.0] The admin model does return a stdClass instead of CMSObject
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_fields/src/Model/GroupModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_users/src/Model/NoteModel.php
  libraries/src/MVC/Model/AdminModel.php
Labels: Feature, b/c break, PR-6.0-dev

#43758 [5.3] [bugfix] Use iife for the scripts core and load validate as module
  build/build-modules-js/javascript/compile-to-es2017.mjs
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/fields/validate.es6.js
Labels: Feature, NPM Resource Changed, PR-5.3-dev

#44585 [5.2] Composer update joomla/application to 3.0.3 to fix PHP deprecations in Web Client
  composer.json
  composer.lock
Labels: Composer Dependency Changed, bug, PR-5.2-dev

#44588 [5.3] Template Override Plugins Compare
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, PR-5.3-dev

#44602 [5.3] tuf_metdata
  installation/sql/mysql/base.sql
Labels: RTC

#44608 [6.0] Upmerges - 2024-12-11
  administrator/components/com_scheduler/forms/filter_logs.xml
  administrator/components/com_scheduler/src/Controller/LogsController.php
  administrator/components/com_scheduler/src/Field/ExitCodeField.php
  administrator/components/com_scheduler/src/Model/LogsModel.php
  administrator/components/com_scheduler/src/Table/LogsTable.php
  administrator/components/com_scheduler/src/View/Logs/HtmlView.php
  administrator/components/com_scheduler/src/View/Tasks/HtmlView.php
  administrator/components/com_scheduler/tmpl/logs/default.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/language/en-GB/com_scheduler.ini
  build/build-modules-js/javascript/compile-to-es2017.mjs
  build/media_source/system/joomla.asset.json
  build/media_source/system/js/fields/validate.es6.js
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  plugins/system/tasknotification/src/Extension/TaskNotification.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-6.0-dev

#44616 [5.3] com_users doc comment
  components/com_users/src/View/Registration/HtmlView.php
Labels: RTC, PR-5.3-dev

#44612 [5.3] Fix doctype
  libraries/src/Menu/MenuItem.php
Labels: RTC, PR-5.3-dev

#44516 [5.3] Send an event before an update site is downloaded
  libraries/src/Event/Installer/BeforeUpdateSiteDownloadEvent.php
  libraries/src/Updater/UpdateAdapter.php
Labels: Feature, RTC, PR-5.3-dev

#44622 [4.4] Update node_modules cross-spawn and nanoid
  package-lock.json
Labels: NPM Resource Changed, PR-4.4-dev

#44521 [5.2] User: Allow MFA before password reset
  libraries/src/Application/AdministratorApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
Labels: RTC, bug, PR-5.2-dev

#44629 [5.2] Fix duplicate entry with the action logs by removing the second call to onJoomlaAfterUpdate
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
Labels: RTC, PR-5.2-dev

#44546 [5.2][CLI] extension:remove -n option "Invalid Response" fix
  libraries/src/Console/ExtensionRemoveCommand.php
Labels: RTC, bug, PR-5.2-dev

#44522 [5.2] Privacy: Allow MFA and invalid privacy consents
  plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
Labels: RTC, bug, PR-5.2-dev

#44565 Refresh changelog URL on manifest cache refresh
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/Installer.php
Labels: RTC, PR-5.2-dev

#44651 [5.2] Upmerge changes from 4.4-dev 2024-12-19
  package-lock.json
Labels: NPM Resource Changed, PR-5.2-dev

#44564 Changelog URL is not updated on package update
  libraries/src/Installer/Adapter/PackageAdapter.php
Labels: RTC, bug, PR-5.2-dev

#44678 [6.0] Upmerges - 2024-12-30
  administrator/components/com_scheduler/src/Controller/LogsController.php
  administrator/components/com_scheduler/src/Field/ExitCodeField.php
  administrator/components/com_scheduler/src/Model/LogsModel.php
  administrator/components/com_scheduler/src/Table/LogsTable.php
  administrator/components/com_scheduler/src/Table/TaskTable.php
  administrator/components/com_scheduler/src/View/Logs/HtmlView.php
  libraries/src/Event/Installer/BeforeUpdateSiteDownloadEvent.php
  libraries/src/Router/Router.php
  plugins/system/tasknotification/src/Extension/TaskNotification.php
Labels: PR-6.0-dev
