Repository joomla/joomla-cms, pull requests merged in 2024-08, with the labels that each got.

#43755 [4.4][bugfix] Use iife for the scripts core and validate
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/media_source/plg_system_jooa11y/js/jooa11y.es6.js
  build/media_source/system/js/core.es6.js
  build/media_source/system/js/fields/validate.es6.js
  package-lock.json
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#43851 [4.4] Fix missing $db->quoteName in FieldLayoutField
  administrator/components/com_fields/src/Field/FieldLayoutField.php
Labels: RTC, PR-4.4-dev

#43651 [4.x] Fix com_content batch modal button logic
  administrator/components/com_content/src/View/Articles/HtmlView.php
Labels: RTC, PR-4.4-dev

#43875 [4.4] fixing typo
  administrator/components/com_content/src/Field/VotelistField.php
  administrator/components/com_content/src/Field/VoteradioField.php
  installation/src/Form/Field/Installation/LanguageField.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/Form/Field/WorkflowconditionField.php
  libraries/src/Form/Field/WorkflowstageField.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormRule.php
  libraries/src/Form/Rule/SubformRule.php
Labels: RTC, bug, PR-4.4-dev

#43882 [5.x] Fix `secure` flag for session cookies
  libraries/src/Service/Provider/Session.php
Labels: RTC, Release Blocker, PR-5.1-dev

#43574 [4.4] Fix for multiselect.js to not to interfere with interactive elements
  build/media_source/system/js/multiselect.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#43789 [4.4] Fix SQL field, get the filter value from the linked filter field
  libraries/src/Form/Field/SqlField.php
Labels: RTC, bug, PR-4.4-dev

#43879 [4.4] Fix newsfeed category html view
  components/com_newsfeeds/src/View/Category/HtmlView.php
Labels: RTC, PR-4.4-dev

#43881 [4.4] Set publish_up in db_createArticle
  tests/System/support/commands/db.mjs
Labels: Unit/System Tests, PR-4.4-dev

#43880 [4.4] Fix newsfeed html view
  components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
Labels: RTC

#43827 [4.4] Revert #42934, do not force Product schema for every article
  plugins/content/vote/tmpl/rating.php
Labels: RTC, bug, PR-4.4-dev

#43722 [4.4] Use joomla-cypress 1.1.1
  package-lock.json
  package.json
  tests/System/README.md
  tests/System/support/commands.mjs
Labels: Unit/System Tests, NPM Resource Changed, PR-4.4-dev

#43854 [5.2] [Guided tours] dark mode colors do not contrast well against the overall interface
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
  build/media_source/templates/administrator/atum/scss/blocks/_shepard-modals.scss
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43230 [5.2] Remove legacy code for filtering state in backend models
  administrator/components/com_associations/src/Model/AssociationsModel.php
  administrator/components/com_cache/src/Model/CacheModel.php
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_finder/src/Model/FiltersModel.php
  administrator/components/com_finder/src/Model/IndexModel.php
  administrator/components/com_finder/src/Model/MapsModel.php
  administrator/components/com_guidedtours/src/Model/ToursModel.php
  administrator/components/com_installer/src/Model/DatabaseModel.php
  administrator/components/com_installer/src/Model/DiscoverModel.php
  administrator/components/com_installer/src/Model/InstallerModel.php
  administrator/components/com_installer/src/Model/LanguagesModel.php
  administrator/components/com_installer/src/Model/ManageModel.php
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
  administrator/components/com_languages/src/Model/InstalledModel.php
  administrator/components/com_languages/src/Model/OverridesModel.php
  administrator/components/com_menus/src/Model/ItemsModel.php
  administrator/components/com_menus/src/Model/MenusModel.php
  administrator/components/com_modules/src/Model/ModulesModel.php
  administrator/components/com_modules/src/Model/PositionsModel.php
  administrator/components/com_privacy/src/Model/ConsentsModel.php
  administrator/components/com_privacy/src/Model/RequestsModel.php
  administrator/components/com_templates/src/Model/StylesModel.php
  administrator/components/com_templates/src/Model/TemplatesModel.php
  administrator/components/com_users/src/Model/DebuggroupModel.php
  administrator/components/com_users/src/Model/DebuguserModel.php
Labels: Feature, RTC, PR-5.2-dev

#43223 [5.2] Delete user access level - check for levels in use
  administrator/components/com_users/src/Model/LevelModel.php
  administrator/language/en-GB/com_users.ini
Labels: Feature, RTC, Language Change, PR-5.2-dev

#43692 [5.2] If RSS feed is blocked, don't allow access to RSS output
  components/com_content/src/View/Featured/FeedView.php
  components/com_finder/src/View/Search/FeedView.php
  components/com_tags/src/View/Tag/FeedView.php
  components/com_tags/src/View/Tags/FeedView.php
  libraries/src/MVC/View/CategoryFeedView.php
Labels: RTC, PR-5.2-dev

#43729 [5.2] Small fix for the dt- tag in content details list
  layouts/joomla/content/info_block.php
Labels: RTC, a11y, Frontend Template, PR-5.2-dev

#43198 [4.4] Form Text Field: Translate text for frontend validation
  layouts/joomla/form/field/text.php
Labels: RTC, bug, PR-4.4-dev

#43746 [5.2] ModalSelect: selecting the title for the field value, when possible
  libraries/src/Form/Field/ModalSelectField.php
Labels: Feature, RTC, PR-5.2-dev

#43825 [5.2] [Guided Tours] Arrows do not show properly, especially in dark mode
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43810 [5.2] [Guided tours] Increase the width and adjust the height of the popup
  administrator/language/en-GB/guidedtours.joomla_welcome.ini
  administrator/language/en-GB/guidedtours.joomla_welcome_steps.ini
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, Language Change, NPM Resource Changed, PR-5.2-dev

#43859 [5.2] Add name to the select image event
  administrator/components/com_media/resources/scripts/components/breadcrumb/breadcrumb.vue
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  administrator/components/com_media/resources/scripts/components/browser/table/row.vue
  administrator/components/com_media/resources/scripts/components/tree/tree.vue
  administrator/components/com_media/resources/scripts/store/mutations.es6.js
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43809 [5.2] [Guided tours] Tour header visual changes + footer padding fix
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43898 [5.2] Mail Template Attachments description
  administrator/language/en-GB/com_mails.ini
Labels: RTC, Language Change, PR-5.2-dev

#43901 [5.1] Upmerges 2024-08-10
  administrator/components/com_content/src/Field/VotelistField.php
  administrator/components/com_content/src/Field/VoteradioField.php
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_fields/src/Field/FieldLayoutField.php
  administrator/components/com_users/src/Helper/Mfa.php
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/media_source/system/js/core.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/multiselect.es6.js
  build/media_source/templates/administrator/atum/js/template.es6.js
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_toolbar.scss
  installation/src/Form/Field/Installation/LanguageField.php
  layouts/joomla/form/field/text.php
  libraries/src/Captcha/Captcha.php
  libraries/src/Form/Field/SqlField.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/Form/Field/WorkflowconditionField.php
  libraries/src/Form/Field/WorkflowstageField.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormRule.php
  libraries/src/Form/Rule/SubformRule.php
  plugins/content/vote/tmpl/rating.php
  tests/System/README.md
  tests/System/support/commands.mjs
Labels: Unit/System Tests, NPM Resource Changed, PR-5.1-dev

#43874 [5.1] Fix encoding for a few popup links
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/index/emptystate.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
Labels: RTC, bug, PR-5.1-dev

#43878 [5.1] Fix header translation for modal select field
  layouts/joomla/form/field/modal-select/buttons.php
Labels: RTC, bug, PR-5.1-dev

#43804 [5.1] Fix JavaScript error caused by using "switcher" layout for radio buttons in subforms
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#43897 [5.1] Private messages relative urls
  administrator/components/com_messages/tmpl/message/default.php
Labels: RTC, PR-5.1-dev

#43352 [5.2] Adding undefined vars $filterForm/$activeFilters to HtmlView
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_installer/src/View/Discover/HtmlView.php
  administrator/components/com_installer/src/View/Languages/HtmlView.php
  administrator/components/com_installer/src/View/Manage/HtmlView.php
  administrator/components/com_installer/src/View/Update/HtmlView.php
  administrator/components/com_languages/src/View/Overrides/HtmlView.php
  administrator/components/com_postinstall/src/View/Messages/HtmlView.php
  administrator/components/com_privacy/tmpl/requests/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  libraries/src/MVC/View/CategoryView.php
Labels: PR-5.2-dev

#43354 [5.2] ArchiveModel: Deprecate and fix getData()
  components/com_content/src/Model/ArchiveModel.php
Labels: PR-5.2-dev

#43355 [5.2] AbstractView: Fix translation of error message
  libraries/src/MVC/View/AbstractView.php
Labels: PR-5.2-dev

#43356 [5.2] Installation: Move getOptions() in models to base class
  installation/src/Model/BaseInstallationModel.php
  installation/src/Model/ChecksModel.php
  installation/src/Model/DatabaseModel.php
  installation/src/Model/LanguagesModel.php
  installation/src/Model/SetupModel.php
Labels: PR-5.2-dev

#43358 [5.2] Adding missing properties to backend component view classes
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_categories/src/View/Category/HtmlView.php
  administrator/components/com_checkin/src/View/Checkin/HtmlView.php
  administrator/components/com_config/src/View/Application/HtmlView.php
  administrator/components/com_config/src/View/Component/HtmlView.php
  administrator/components/com_contact/src/View/Contact/HtmlView.php
  administrator/components/com_content/src/View/Article/HtmlView.php
  administrator/components/com_finder/src/View/Filter/HtmlView.php
  administrator/components/com_menus/src/View/Item/HtmlView.php
  administrator/components/com_modules/src/View/Module/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  administrator/components/com_plugins/src/View/Plugin/HtmlView.php
  administrator/components/com_scheduler/src/View/Task/HtmlView.php
  administrator/components/com_tags/src/View/Tag/HtmlView.php
  administrator/components/com_templates/src/View/Style/HtmlView.php
  administrator/components/com_users/src/View/Group/HtmlView.php
  administrator/components/com_users/src/View/User/HtmlView.php
  administrator/components/com_workflow/src/View/Stages/HtmlView.php
  administrator/components/com_workflow/src/View/Transition/HtmlView.php
Labels: PR-5.2-dev

#43508 [5.2] Remove get()/set() calls to table classes
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_installer/src/Model/DatabaseModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Installer/Adapter/PluginAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Table/ContentHistory.php
  libraries/src/Table/Table.php
  libraries/src/Updater/Adapter/CollectionAdapter.php
  libraries/src/Updater/Adapter/TufAdapter.php
  libraries/src/Updater/Updater.php
  libraries/src/User/User.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
Labels: PR-5.2-dev

#43360 [5.2] Refactor all instances of File::delete() to use framework
  libraries/src/Console/UpdateCoreCommand.php
  plugins/task/rotatelogs/src/Extension/RotateLogs.php
Labels: PR-5.2-dev

#43351 [5.2] Fixing timezone and language parameter in API token auth response
  plugins/api-authentication/token/src/Extension/Token.php
Labels: bug, PR-5.2-dev

#43914 [6.0] Naming the release
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  installation/language/en-GB/langmetadata.xml
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Version.php
  package-lock.json
Labels: Language Change, NPM Resource Changed, PR-6.0-dev

#43091 [5.2] Finder: Simplifying the populateState() method of SearchModel
  components/com_finder/src/Model/SearchModel.php
Labels: Feature, PR-5.2-dev

#43919 [5.2] PHPStan integration
  .drone.yml
  build/build.php
  build/phpstan/joomla-bootstrap.php
  build/phpstan/phpstan.neon
  build/phpstan/src/DynamicReturnType/ControllerLoader.php
  build/phpstan/src/DynamicReturnType/DIContainer.php
  build/phpstan/src/DynamicReturnType/ExtensionManagerInterface.php
  build/phpstan/src/DynamicReturnType/MVCFactoryInterfaceInterface.php
  build/phpstan/src/DynamicReturnType/ModelBootComponent.php
  build/phpstan/src/DynamicReturnType/ModelTableLoader.php
  build/phpstan/src/DynamicReturnType/NamespaceBased.php
  build/phpstan/src/DynamicReturnType/ViewModelLoader.php
  build/phpstan/src/Reflection/FormField.php
  build/phpstan/src/Reflection/FormFieldProperty.php
  build/phpstan/stubs/AdminModel.stub
  build/phpstan/stubs/CMSApplication.stub
  build/phpstan/stubs/Language.stub
  composer.json
  composer.lock
  phpstan.neon
Labels: Unit/System Tests, Composer Dependency Changed, PR-5.2-dev

#43925 Remove phan dependency
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.2-dev

#43432 [5.2] SEF: Add "Strict Routing" option
  administrator/language/en-GB/plg_system_sef.ini
  plugins/system/sef/sef.xml
Labels: Feature, RTC, Language Change, PR-5.2-dev

#42854 [5.2] SEF: Enforcing correct SEF URL
  plugins/system/sef/src/Extension/Sef.php
Labels: Feature, RTC, PBF, PR-5.2-dev

#43870 [5.2] Custom Reply description
  administrator/components/com_contact/config.xml
  administrator/components/com_contact/forms/contact.xml
  administrator/language/en-GB/com_contact.ini
  components/com_contact/tmpl/categories/default.xml
  components/com_contact/tmpl/category/default.xml
  components/com_contact/tmpl/contact/default.xml
  components/com_contact/tmpl/featured/default.xml
Labels: RTC, Language Change, PR-5.2-dev

#43024 [5.2] SEF: Enable new SEF options for new installations
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: Feature, RTC, PR-5.2-dev

#43635 [5.2][Events] Use event classes for Editors and editor buttons plugins
  plugins/editors-xtd/article/src/Extension/Article.php
  plugins/editors-xtd/contact/src/Extension/Contact.php
  plugins/editors-xtd/fields/src/Extension/Fields.php
  plugins/editors-xtd/image/src/Extension/Image.php
  plugins/editors-xtd/menu/src/Extension/Menu.php
  plugins/editors-xtd/module/src/Extension/Module.php
  plugins/editors-xtd/pagebreak/src/Extension/PageBreak.php
  plugins/editors-xtd/readmore/src/Extension/ReadMore.php
  plugins/editors/none/src/Extension/None.php
  plugins/editors/none/src/Provider/EditorNoneProvider.php
  tests/Unit/Plugin/EditorsXtd/PageBreak/Extension/PageBreakTest.php
Labels: Feature, RTC, Unit/System Tests, PR-5.2-dev

#42850 [5.2] SEF: Enforce suffix
  administrator/language/en-GB/plg_system_sef.ini
  plugins/system/sef/sef.xml
  plugins/system/sef/src/Extension/Sef.php
Labels: Feature, RTC, Language Change, PBF, PR-5.2-dev

#43930 [5.2] Partial revert of #43230
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
  administrator/components/com_languages/src/Model/OverridesModel.php
Labels: RTC, bug, PR-5.2-dev

#43935 Fix for [5.2] admin template broken #43932
  administrator/components/com_config/src/View/Application/HtmlView.php
Labels: Release Blocker, bug, PR-5.2-dev

#43937 5.1 to 5.2 upmerge 20240817
  administrator/components/com_content/src/Field/VotelistField.php
  administrator/components/com_content/src/Field/VoteradioField.php
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_fields/src/Field/FieldLayoutField.php
  administrator/components/com_finder/tmpl/index/default.php
  administrator/components/com_finder/tmpl/index/emptystate.php
  administrator/components/com_messages/tmpl/message/default.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
  administrator/components/com_users/src/Helper/Mfa.php
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  build/build-modules-js/javascript/compile-to-es2017.es6.js
  build/media_source/system/js/core.es6.js
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  build/media_source/system/js/fields/validate.es6.js
  build/media_source/system/js/multiselect.es6.js
  build/media_source/templates/administrator/atum/js/template.es6.js
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_toolbar.scss
  installation/language/en-GB/langmetadata.xml
  installation/language/ur-PK/langmetadata.xml
  installation/src/Form/Field/Installation/LanguageField.php
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  layouts/joomla/form/field/modal-select/buttons.php
  layouts/joomla/form/field/text.php
  libraries/src/Captcha/Captcha.php
  libraries/src/Form/Field/SqlField.php
  libraries/src/Form/Field/TransitionField.php
  libraries/src/Form/Field/WorkflowconditionField.php
  libraries/src/Form/Field/WorkflowstageField.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormRule.php
  libraries/src/Form/Rule/SubformRule.php
  plugins/content/vote/tmpl/rating.php
  plugins/system/schemaorg/src/Extension/Schemaorg.php
  tests/System/README.md
  tests/System/support/commands.mjs
Labels: Language Change, NPM Resource Changed, PR-5.2-dev

#43939 [5.2] Updating composer and npm dependencies
  composer.json
  composer.lock
  package-lock.json
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.2-dev

#43862 [5.2] Multilang: Remove restrictions for home language menu items
  administrator/components/com_languages/tmpl/multilangstatus/default.php
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/default.xml
  administrator/language/en-GB/com_languages.ini
  libraries/src/Table/Menu.php
Labels: RTC, Language Change, PR-5.2-dev

#43941 [5.2] [REGRESSION] Fix menu and module list state filter
  administrator/components/com_menus/src/Model/ItemsModel.php
  administrator/components/com_modules/src/Model/ModulesModel.php
Labels: RTC, PR-5.2-dev

#43943 [5.1] Dependencies/update 5.1.3
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.1-dev

#43944 [5.1] Update deleted files list in script.php for 5.1.3
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#43963 [5.1] Upmerge 2024-08-22
  components/com_content/src/View/Archive/HtmlView.php
  components/com_finder/src/View/Search/HtmlView.php
  libraries/src/Cache/Cache.php
  libraries/src/Pagination/Pagination.php
Labels: PR-5.1-dev

#43964 Upmerge 5.1-dev to 5.2-dev 2024-08-22
  administrator/components/com_admin/script.php
  components/com_content/src/View/Archive/HtmlView.php
  components/com_finder/src/View/Search/HtmlView.php
  libraries/src/Cache/Cache.php
  libraries/src/Mail/MailTemplate.php
  libraries/src/Pagination/Pagination.php
Labels: Test instructions missing, PR-5.2-dev

#43967 [4.4] Pagination fixes part 2
  components/com_content/src/View/Archive/HtmlView.php
  components/com_finder/src/View/Search/HtmlView.php
Labels: RTC, PR-4.4-dev

#43970 [5.1] Upmerges 2024-08-23
  components/com_content/src/View/Archive/HtmlView.php
  components/com_finder/src/View/Search/HtmlView.php
Labels: PR-5.1-dev

#43983 [4.4] Fix filter for option, format, view and layout in cache and pagination
  libraries/src/Cache/Cache.php
  libraries/src/Pagination/Pagination.php
Labels: RTC, bug, PR-4.4-dev

#41988 [5.2] Remove call_user_func()
  libraries/src/Form/FormField.php
Labels: Feature, RTC, PR-5.2-dev

#43860 [5.2] radio basic deprecate
  layouts/joomla/form/field/radiobasic.php
  libraries/src/Form/Field/RadiobasicField.php
Labels: RTC, Documentation Required, PR-5.2-dev

#43529 [5.2][Events] Class for MailBeforeRendering event
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/Mail/BeforeRenderingMailTemplateEvent.php
  libraries/src/Event/Mail/MailTemplateEvent.php
  libraries/src/Mail/MailTemplate.php
Labels: Feature, RTC, Small, PR-5.2-dev

#43362 [5.2] Refactor all instances of File to use framework
  administrator/components/com_installer/src/Model/InstallModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  libraries/src/Log/Logger/FormattedtextLogger.php
Labels: RTC, PR-5.2-dev

#43981 [4.4] Escape unsafe tags in mail copy to sender and notification to admin and don't escape custom email fields
  components/com_contact/src/Controller/ContactController.php
  components/com_users/src/Model/RegistrationModel.php
Labels: RTC, Release Blocker, bug, PR-4.4-dev

#43987 [5.1] Upmerges 2024-08-26
  .github/workflows/create-translation-pull-request-v4.yml
  components/com_contact/src/Controller/ContactController.php
  components/com_users/src/Model/RegistrationModel.php
  libraries/src/Cache/Cache.php
  libraries/src/Pagination/Pagination.php
  libraries/src/Version.php
  plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php
Labels: PR-5.1-dev

#43985 [5.2] Spelling
  libraries/src/Mail/MailTemplate.php
Labels: RTC, PR-5.2-dev

#43975 [5.2] Improve UX for template buttons - replace PR #43592
  administrator/components/com_templates/src/View/Template/HtmlView.php
  administrator/language/en-GB/com_templates.ini
Labels: RTC, Language Change, PR-5.2-dev

#41971 [5.2] Invalid pass-by-reference usage
  administrator/components/com_menus/src/Model/MenuModel.php
  administrator/components/com_messages/src/Model/ConfigModel.php
  administrator/components/com_modules/src/Model/PositionsModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: Feature, Maintainers Checked, PR-5.2-dev

#43617 [5.2][Events] Use event classes for Extension plugins
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/Extension/AbstractJoomlaUpdateEvent.php
  libraries/src/Event/Extension/AfterJoomlaUpdateEvent.php
  libraries/src/Event/Extension/BeforeJoomlaUpdateEvent.php
  plugins/extension/finder/src/Extension/Finder.php
  plugins/extension/joomla/src/Extension/Joomla.php
  plugins/extension/namespacemap/src/Extension/NamespaceMap.php
  plugins/installer/override/src/Extension/Override.php
Labels: Feature, RTC, PR-5.2-dev, Enhancement, Review effort [1-5]: 3

#43993 5.1 to 5.2 upmerge 2024-08-28
  .github/workflows/create-translation-pull-request-v4.yml
  components/com_contact/src/Controller/ContactController.php
  components/com_content/src/View/Archive/HtmlView.php
  components/com_finder/src/View/Search/HtmlView.php
  components/com_users/src/Model/RegistrationModel.php
  installation/language/af-ZA/langmetadata.xml
  installation/language/ar-AA/langmetadata.xml
  installation/language/be-BY/langmetadata.xml
  installation/language/bg-BG/langmetadata.xml
  installation/language/ca-ES/langmetadata.xml
  installation/language/cs-CZ/langmetadata.xml
  installation/language/cy-GB/langmetadata.xml
  installation/language/da-DK/langmetadata.xml
  installation/language/el-GR/langmetadata.xml
  installation/language/en-AU/langmetadata.xml
  installation/language/en-CA/langmetadata.xml
  installation/language/en-NZ/langmetadata.xml
  installation/language/en-US/langmetadata.xml
  installation/language/es-ES/langmetadata.xml
  installation/language/et-EE/langmetadata.xml
  installation/language/eu-ES/langmetadata.xml
  installation/language/fa-AF/langmetadata.xml
  installation/language/fa-IR/langmetadata.xml
  installation/language/fi-FI/langmetadata.xml
  installation/language/fr-CA/langmetadata.xml
  installation/language/fr-FR/langmetadata.xml
  installation/language/he-IL/langmetadata.xml
  installation/language/hr-HR/langmetadata.xml
  installation/language/hu-HU/langmetadata.xml
  installation/language/id-ID/langmetadata.xml
  installation/language/it-IT/langmetadata.xml
  installation/language/ja-JP/langmetadata.xml
  installation/language/ka-GE/langmetadata.xml
  installation/language/kk-KZ/langmetadata.xml
  installation/language/ko-KR/langmetadata.xml
  installation/language/lt-LT/langmetadata.xml
  installation/language/lv-LV/langmetadata.xml
  installation/language/mk-MK/langmetadata.xml
  installation/language/nl-BE/langmetadata.xml
  installation/language/nl-NL/langmetadata.xml
  installation/language/pl-PL/joomla.cli.ini
  installation/language/pl-PL/langmetadata.xml
  installation/language/pt-BR/langmetadata.xml
  installation/language/pt-PT/langmetadata.xml
  installation/language/ro-RO/langmetadata.xml
  installation/language/sk-SK/langmetadata.xml
  installation/language/sl-SI/langmetadata.xml
  installation/language/sr-YU/langmetadata.xml
  installation/language/sv-SE/langmetadata.xml
  installation/language/ta-IN/langmetadata.xml
  installation/language/th-TH/langmetadata.xml
  installation/language/tr-TR/langmetadata.xml
  installation/language/uk-UA/langmetadata.xml
  installation/language/ur-PK/langmetadata.xml
  installation/language/vi-VN/langmetadata.xml
  installation/language/zh-CN/langmetadata.xml
  installation/language/zh-TW/langmetadata.xml
  libraries/src/Cache/Cache.php
  libraries/src/Pagination/Pagination.php
  plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php
Labels: Language Change, PR-5.2-dev

#43601 [5.2][Events] Use event classes for Authentication plugins
  plugins/api-authentication/basic/src/Extension/Basic.php
  plugins/authentication/cookie/src/Extension/Cookie.php
  plugins/authentication/joomla/src/Extension/Joomla.php
  plugins/authentication/ldap/src/Extension/Ldap.php
  tests/Integration/Plugin/Authentication/Ldap/LdapPluginTest.php
  tests/Unit/Plugin/Authentication/Ldap/LdapPluginTest.php
Labels: Feature, RTC, Unit/System Tests, PR-5.2-dev

#43607 [5.2][Events] Use event classes for Finder plugins
  plugins/finder/categories/src/Extension/Categories.php
  plugins/finder/contacts/src/Extension/Contacts.php
  plugins/finder/content/src/Extension/Content.php
  plugins/finder/newsfeeds/src/Extension/Newsfeeds.php
  plugins/finder/tags/src/Extension/Tags.php
Labels: Feature, RTC, PR-5.2-dev

#43924 [cypress] PostgreSQL Connection pool for System Tests
  tests/System/plugins/db.mjs
Labels: Unit/System Tests, PR-4.4-dev

#43608 [5.2][Events] Use event classes for Media-action plugins
  administrator/components/com_media/src/Plugin/MediaActionPlugin.php
  plugins/media-action/crop/src/Extension/Crop.php
  plugins/media-action/resize/src/Extension/Resize.php
  plugins/media-action/rotate/src/Extension/Rotate.php
Labels: Feature, RTC, PR-5.2-dev

#43996 4.4 to 5.2 upmerge 2024-08-29
  tests/System/plugins/db.mjs
Labels: Unit/System Tests, PR-5.2-dev

#43910 [5.2] Tinymce lang sort
  administrator/language/en-GB/plg_editors_tinymce.ini
Labels: RTC, Language Change, PR-5.1-dev, PR-5.2-dev

#43960 [Guided Tours] Fix dropdown mouse accessibility on fancy selects
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43965 [5.2] Search for content checked out by an author
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/language/en-GB/com_content.ini
Labels: RTC, Language Change, PR-5.2-dev

#42989 [5.2] SEF: Add option to don't set Itemid to homepage by default
  components/com_contact/src/Service/Router.php
  components/com_content/src/Service/Router.php
  components/com_newsfeeds/src/Service/Router.php
  components/com_tags/src/Service/Router.php
  libraries/src/Component/Router/Rules/MenuRules.php
  tests/System/integration/site/components/com_contact/Contact.cy.js
  tests/System/integration/site/components/com_users/Profile_Edit.cy.js
  tests/System/integration/site/components/com_users/Remind.cy.js
Labels: Feature, RTC, Unit/System Tests, bug, PR-5.2-dev

#43998 Revert "4.4 to 5.2 upmerge 2024-08-29"
  tests/System/plugins/db.mjs
Labels: Unit/System Tests, PR-5.2-dev

#43999 4.4 to 5.2 upmerge 2024-08-29
  tests/System/plugins/db.mjs
Labels: Unit/System Tests, PR-5.2-dev

#43424 Fixed: Consistency of "unpublished" -i con colours #43375
  administrator/components/com_associations/tmpl/associations/default.php
  administrator/components/com_associations/tmpl/associations/modal.php
  administrator/components/com_categories/tmpl/categories/modal.php
  administrator/components/com_contact/tmpl/contacts/modal.php
  administrator/components/com_content/tmpl/articles/modal.php
  administrator/components/com_fields/tmpl/fields/modal.php
  administrator/components/com_modules/tmpl/modules/modal.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/modal.php
Labels: RTC, PR-4.4-dev

#43052 [4.4] Fix Sample data installation, fix finder helper addContentType null value
  administrator/components/com_finder/src/Indexer/Helper.php
Labels: RTC, PHP 8.x, bug, PR-4.4-dev

#43946 Feature/4 4 docblock typo
  libraries/src/Factory.php
  libraries/src/MVC/Model/LegacyModelLoaderTrait.php
Labels: RTC, PR-4.4-dev

#43738 Articles Module
  administrator/components/com_admin/sql/updates/mysql/5.2.0-2024-07-02.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.0-2024-07-02.sql
  build/media_source/mod_articles/css/mod-articles.css
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  language/en-GB/mod_articles.ini
  language/en-GB/mod_articles.sys.ini
  libraries/src/Extension/ExtensionHelper.php
  modules/mod_articles/mod_articles.xml
  modules/mod_articles/services/provider.php
  modules/mod_articles/src/Dispatcher/Dispatcher.php
  modules/mod_articles/src/Helper/ArticlesHelper.php
  modules/mod_articles/tmpl/default.php
  modules/mod_articles/tmpl/default_items.php
  modules/mod_articles/tmpl/default_titles.php
  plugins/sampledata/blog/src/Extension/Blog.php
  tests/System/integration/api/com_modules/Types.cy.js
Labels: Feature, RTC, Unit/System Tests, Language Change, NPM Resource Changed, PR-5.2-dev

#43814 [5.2] [Guided tours] Auto start tours - full functionality
  administrator/components/com_actionlogs/config.xml
  administrator/components/com_admin/sql/updates/mysql/5.2.0-2024-07-19.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.0-2024-07-19.sql
  administrator/components/com_guidedtours/config.xml
  administrator/components/com_guidedtours/src/Controller/AjaxController.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_users/forms/user.xml
  administrator/language/en-GB/com_guidedtours.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/plg_actionlog_joomla.ini
  administrator/language/en-GB/plg_system_guidedtours.ini
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  components/com_users/forms/frontend.xml
  installation/sql/mysql/base.sql
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/base.sql
  installation/sql/postgresql/extensions.sql
  language/en-GB/com_users.ini
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/system/guidedtours/services/provider.php
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: RTC, Language Change, NPM Resource Changed, PR-5.2-dev

#44004 [5.2] Composer dependency updates
  composer.json
  composer.lock
  includes/incompatible.html
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: Composer Dependency Changed, PR-5.2-dev
