Repository joomla/joomla-cms, pull requests merged in 2024-05, with the labels that each got.

#43420 [4.4] Pin version MySql Version in Tests to 8.0
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#43419 [5.1] Pin Mysql Version to 8.0
  .drone.yml
Labels: Unit/System Tests, PR-5.1-dev

#43418 [5.2] Pin Mysql Version to 8.0
  .drone.yml
Labels: Unit/System Tests, PR-5.2-dev

#43353 [4.4] Contact VCF: Properly assign value to array
  components/com_contact/src/View/Contact/VcfView.php
Labels: RTC, bug, PR-4.4-dev

#41677 [5.2] com_users: Simplifying empty check in login layout
  components/com_users/tmpl/login/default_login.php
Labels: Feature, RTC, PR-5.1-dev, PR-5.2-dev

#43386 [5.2] Change the workflows article title
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: RTC, Language Change, PR-5.2-dev

#42907 [5.2] Static function getList deprecated in mod_stats
  modules/mod_stats/src/Dispatcher/Dispatcher.php
  modules/mod_stats/src/Helper/StatsHelper.php
Labels: Feature, RTC, PR-5.1-dev, PR-5.2-dev

#43204 [5.2] Allow nested Subform inside a Subform Custom Field
  administrator/components/com_fields/forms/field.xml
  administrator/components/com_fields/src/Field/SubfieldsField.php
  administrator/components/com_fields/src/Model/FieldModel.php
Labels: Feature, RTC, PR-5.2-dev

#43411 [5.2] TinyMCe insert content
  build/media_source/plg_editors_tinymce/js/plugins/jtemplate/plugin.es5.js
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43381 Replace at feature in SessionManagerTest unit test
  tests/Unit/Libraries/Cms/Session/SessionManagerTest.php
Labels: Unit/System Tests, PR-5.2-dev

#43335 [4.4] Fix ordering for files in the template view
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default_tree.php
  administrator/components/com_templates/tmpl/template/default_tree_media.php
Labels: RTC, bug, PR-4.4-dev

#43436 [5.2] scss comments
  build/media_source/templates/administrator/atum/scss/_variables-dark.scss
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/blocks/_calendar.scss
  build/media_source/templates/administrator/atum/scss/blocks/_header.scss
  build/media_source/templates/administrator/atum/scss/blocks/_icons.scss
  build/media_source/templates/administrator/atum/scss/pages/_com_media.scss
  build/media_source/templates/administrator/atum/scss/system/fields/_switcher.scss
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_buttons.scss
  build/media_source/templates/administrator/atum/scss/vendor/choicesjs/choices.scss
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_toolbar.scss
  build/media_source/templates/site/cassiopeia/scss/tools/variables/_variables.scss
Labels: NPM Resource Changed, PR-5.2-dev

#43377 InputFilter fails on cleaning string with HEX entities as string
  libraries/src/Filter/InputFilter.php
Labels: RTC, bug, PR-4.4-dev

#43454 [5.1] Light/Dark Mode switch
  administrator/language/en-GB/mod_user.ini
  administrator/modules/mod_user/tmpl/default.php
Labels: RTC, Language Change, PR-5.1-dev

#43414 [5] correct forum link
  administrator/language/en-GB/com_cpanel.ini
Labels: RTC, Language Change, PR-5.1-dev

#43402 [5.1] Correct message type for Redirect plugin state
  administrator/components/com_redirect/src/View/Links/HtmlView.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
Labels: RTC, bug, PR-5.1-dev

#43376 [5.1] Fix TinyMCE media button, frontend edit
  plugins/editors-xtd/image/src/Extension/Image.php
Labels: RTC, bug, PR-5.1-dev

#43374 [5.1] Fix TinyMCE media button, insert link bug
  build/media_source/system/js/fields/joomla-media-select.w-c.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#43371 [5.1] EmptyState Help links
  administrator/components/com_banners/tmpl/banners/emptystate.php
  administrator/components/com_banners/tmpl/clients/emptystate.php
  administrator/components/com_banners/tmpl/tracks/emptystate.php
  administrator/components/com_checkin/tmpl/checkin/emptystate.php
  administrator/components/com_contact/tmpl/contacts/emptystate.php
  administrator/components/com_finder/tmpl/maps/emptystate.php
  administrator/components/com_finder/tmpl/searches/emptystate.php
  administrator/components/com_guidedtours/tmpl/steps/emptystate.php
  administrator/components/com_guidedtours/tmpl/tours/emptystate.php
  administrator/components/com_installer/tmpl/discover/emptystate.php
  administrator/components/com_installer/tmpl/update/emptystate.php
  administrator/components/com_installer/tmpl/warnings/emptystate.php
  administrator/components/com_messages/tmpl/messages/emptystate.php
  administrator/components/com_newsfeeds/tmpl/newsfeeds/emptystate.php
  administrator/components/com_privacy/tmpl/consents/emptystate.php
  administrator/components/com_privacy/tmpl/requests/emptystate.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
  administrator/components/com_users/tmpl/notes/emptystate.php
Labels: RTC, bug, PR-5.1-dev

#43288 [5.1] PHP Deprecated: PDO::quote(): Passing null
  libraries/src/Updater/Updater.php
Labels: RTC, bug, PR-5.1-dev

#43291 [5.1] Add backward compatibility for older Plugin/Module bootstrap modals
  administrator/components/com_modules/tmpl/module/modal.php
  administrator/components/com_plugins/tmpl/plugin/modal.php
  build/media_source/vendor/bootstrap/js/modal.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#43234 [5.1] Fix calendar value
  libraries/src/Form/Field/CalendarField.php
Labels: RTC, bug, PR-5.1-dev

#43129 [5.1] Fix for legacy editor-xtd plugins with array of buttons
  libraries/src/Editor/Button/ButtonsRegistry.php
Labels: RTC, bug, PR-5.0-dev, PR-5.1-dev

#43114 [5.1] CodeMirror 6 Javascript highlighting not working
  plugins/editors/codemirror/src/Provider/CodeMirrorProvider.php
Labels: RTC, bug, PR-5.0-dev, PR-5.1-dev

#43292 [5.1] fix wrong parameter value of new trailingslash parameter in SEF plugin
  plugins/system/sef/src/Extension/Sef.php
Labels: bug, PR-5.1-dev

#43251 [5.1] Fix missing entries in help index
  administrator/help/en-GB/toc.json
  administrator/language/en-GB/com_admin.ini
Labels: RTC, Language Change, bug, PR-5.1-dev

#43250 [5.1] Fix build tool helpTOC.php
  build/helpTOC.php
Labels: RTC, bug, PR-5.1-dev

#43308 [5.1] Adminmenu: Toggle for duplicate menus
  build/media_source/mod_menu/js/admin-menu.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#43219 [5.1] Changelog deprecation
  libraries/src/Changelog/Changelog.php
Labels: RTC, PHP 8.x, bug, PR-5.1-dev

#42956 [5.1] Fix PHP warnings on newly created custom fields
  administrator/components/com_fields/src/Model/FieldModel.php
Labels: RTC, bug, PR-5.1-dev

#41458 [5.1] Template-param-brand
  templates/cassiopeia/templateDetails.xml
Labels: RTC, bug, RMDQ, Small, PR-5.1-dev

#43370 [5.1] Update Doc Link
  build/build-modules-js/settings.json
  cli/joomla.php
  installation/includes/cli.php
Labels: PR-5.1-dev

#43446 [5.1] Upmerges 2024-05-08
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_menus/src/View/Menu/XmlView.php
  administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default_tree.php
  administrator/components/com_templates/tmpl/template/default_tree_media.php
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/plg_media-action_crop/js/crop.es6.js
  build/media_source/plg_media-action_resize/js/resize.es6.js
  build/media_source/plg_media-action_rotate/js/rotate.es6.js
  components/com_contact/src/View/Contact/VcfView.php
  libraries/src/Console/CheckUpdatesCommand.php
  libraries/src/Filter/InputFilter.php
  libraries/src/Helper/MediaHelper.php
  libraries/src/Updater/UpdateAdapter.php
  package-lock.json
  package.json
  plugins/content/vote/tmpl/rating.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: Unit/System Tests, NPM Resource Changed, PR-5.1-dev

#43295 [5.1] Proper support for avif/webp images
  administrator/components/com_media/resources/scripts/components/browser/actionItems/actionItemsContainer.vue
  administrator/components/com_media/resources/scripts/components/browser/table/row.vue
  administrator/components/com_media/src/Model/ApiModel.php
  administrator/components/com_media/tmpl/file/default.php
  administrator/components/com_media/tmpl/media/default.php
  libraries/src/Helper/MediaHelper.php
  libraries/src/Image/Image.php
  plugins/media-action/resize/src/Extension/Resize.php
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#43464 [4][com_actionlog] export csv untranslated key
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
Labels: RTC, bug, PR-4.4-dev

#43461 [5.1] Update deleted files and folders lists in script.php for 5.1.1
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#43450 [4.x] MFA Backup Codes [a11y] [UI]
  administrator/components/com_users/tmpl/methods/list.php
  administrator/language/en-GB/com_users.ini
  components/com_users/tmpl/methods/list.php
  language/en-GB/com_users.ini
Labels: RTC, Language Change, PR-4.4-dev

#43478 update content for Contributing.md
  .github/CONTRIBUTING.md
Labels: PR-4.4-dev

#43473 [4.4] Fix permission issues on certain ISP
  administrator/components/com_joomlaupdate/extract.php
Labels: PR-4.4-dev

#43482 Remove myself from the CODEOWNERS file
  .github/CODEOWNERS
Labels: PR-4.4-dev

#43481 [5.1] upmerge 2024-05-16
  .github/CONTRIBUTING.md
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_users/tmpl/methods/list.php
  administrator/language/en-GB/com_users.ini
  components/com_users/tmpl/methods/list.php
  language/en-GB/com_users.ini
Labels: Language Change, PR-5.1-dev

#43445 [4.x] Backport fix for Error in PrivacyConsent::getPrivacyItemId()
  plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
Labels: RTC, PR-4.4-dev

#43345 MediaHelper: proper check if file is an image (#42105)
  libraries/src/Helper/MediaHelper.php
Labels: RTC, bug, PR-4.4-dev

#42593 [4.4] Fixing API authentication issue with Apache with PHP as cgi/fastCGI
  plugins/api-authentication/token/src/Extension/Token.php
Labels: PBF, bug, PR-4.4-dev

#43410 [5.1] Joomla Update : extensions check never ends (from #43226)
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  libraries/src/Updater/Update.php
Labels: Release Blocker, PHP 8.x, bug, PR-5.1-dev

#42769 [5.1] Change redirect url (from headers['Location']) from array to string in CurlTransport
  libraries/src/Http/Transport/CurlTransport.php
Labels: RTC, bug, PR-5.1-dev

#43477 [5.1] Catch block for generic TUF exceptions
  administrator/language/en-GB/lib_joomla.ini
  libraries/src/TUF/HttpLoader.php
  libraries/src/TUF/HttpLoaderException.php
  libraries/src/TUF/TufFetcher.php
Labels: Language Change, PR-5.1-dev

#43368 Update to include MariaDB and remove SQL Server in README (.txt and .md)
  README.md
  README.txt
Labels: RTC, PR-5.1-dev

#43053 [4.4] Fix finder helper addContentType duplicate entry for key 'title'
  administrator/components/com_finder/src/Indexer/Helper.php
Labels: RTC, bug, PR-4.4-dev

#43497 [5.1] updater contraintchecker stability check early return
  libraries/src/Updater/ConstraintChecker.php
Labels: PR-5.1-dev

#43500 [5.2] Upmerge 2024-05-21
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  README.md
  README.txt
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_admin/script.php
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_redirect/config.xml
  administrator/components/com_users/tmpl/methods/list.php
  administrator/language/en-GB/com_redirect.ini
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/language/en-GB/lib_joomla.ini
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  components/com_users/tmpl/methods/list.php
  installation/language/ca-ES/langmetadata.xml
  installation/language/en-GB/langmetadata.xml
  installation/language/hr-HR/joomla.ini
  installation/language/lv-LV/joomla.ini
  installation/language/nl-BE/joomla.ini
  installation/language/pt-BR/joomla.ini
  installation/language/ta-IN/joomla.ini
  installation/language/ur-PK/joomla.ini
  language/en-GB/com_users.ini
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Changelog/Changelog.php
  libraries/src/Helper/MediaHelper.php
  libraries/src/Http/Transport/CurlTransport.php
  libraries/src/TUF/HttpLoader.php
  libraries/src/TUF/HttpLoaderException.php
  libraries/src/TUF/TufFetcher.php
  libraries/src/Updater/ConstraintChecker.php
  libraries/src/Updater/Update.php
  libraries/src/Version.php
  modules/mod_stats/src/Helper/StatsHelper.php
  package-lock.json
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/content/vote/src/Extension/Vote.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: Language Change, PR-5.2-dev

#43296 [5.2] Add missing Toggle inline help button to plugin modal / dialog
  administrator/components/com_plugins/src/View/Plugin/HtmlView.php
Labels: Feature, RTC, PR-5.2-dev

#42797 [5.2] Minor cleanup for plugins JS
  build/media_source/plg_captcha_recaptcha/js/recaptcha.es6.js
  build/media_source/plg_captcha_recaptcha_invisible/js/recaptcha.es6.js
  build/media_source/plg_editors_codemirror/js/codemirror.es6.js
  build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js
  build/media_source/plg_installer_packageinstaller/js/packageinstaller.es6.js
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  build/media_source/plg_media-action_rotate/js/rotate.es6.js
  build/media_source/plg_multifactorauth_webauthn/js/webauthn.es6.js
  build/media_source/plg_quickicon_extensionupdate/js/extensionupdatecheck.es6.js
  build/media_source/plg_quickicon_joomlaupdate/js/jupdatecheck.es6.js
  build/media_source/plg_quickicon_overridecheck/js/overridecheck.es6.js
  build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js
  build/media_source/plg_system_debug/js/debug.es6.js
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  build/media_source/plg_system_schedulerunner/js/run-schedule.es6.js
  build/media_source/plg_system_webauthn/js/login.es6.js
  build/media_source/plg_system_webauthn/js/management.es6.js
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43484 [5.2] Password Strength Symbols
  build/media_source/system/js/fields/passwordstrength.es6.js
Labels: RTC, NPM Resource Changed, PR-5.2-dev

#43357 [5.2] Custom Fields: Correcting typehint for $this in layout
  plugins/fields/checkboxes/tmpl/checkboxes.php
  plugins/fields/list/tmpl/list.php
  plugins/fields/radio/tmpl/radio.php
  plugins/fields/user/tmpl/user.php
Labels: PR-6.0-dev, PR-5.2-dev

#43521 [5.1] DateTime: Don't convert when there is no user
  libraries/src/HTML/HTMLHelper.php
Labels: RTC, PR-5.1-dev

#43537 [5.1] Upmerges 2024-05-27
  administrator/components/com_finder/src/Indexer/Helper.php
Labels: Unit/System Tests, Test instructions missing, PR-5.1-dev

#43542 [5.2] Upmerge 2024-05-27
  administrator/components/com_finder/src/Indexer/Helper.php
  installation/language/af-ZA/langmetadata.xml
  installation/language/ar-AA/langmetadata.xml
  installation/language/be-BY/langmetadata.xml
  installation/language/bg-BG/langmetadata.xml
  installation/language/ca-ES/langmetadata.xml
  installation/language/cs-CZ/langmetadata.xml
  installation/language/cy-GB/langmetadata.xml
  installation/language/da-DK/langmetadata.xml
  installation/language/el-GR/langmetadata.xml
  installation/language/en-AU/langmetadata.xml
  installation/language/en-CA/langmetadata.xml
  installation/language/en-NZ/langmetadata.xml
  installation/language/en-US/langmetadata.xml
  installation/language/es-ES/langmetadata.xml
  installation/language/et-EE/langmetadata.xml
  installation/language/eu-ES/langmetadata.xml
  installation/language/fa-AF/langmetadata.xml
  installation/language/fa-IR/langmetadata.xml
  installation/language/fi-FI/langmetadata.xml
  installation/language/fr-CA/langmetadata.xml
  installation/language/fr-FR/langmetadata.xml
  installation/language/he-IL/langmetadata.xml
  installation/language/hr-HR/joomla.ini
  installation/language/hr-HR/langmetadata.xml
  installation/language/hu-HU/langmetadata.xml
  installation/language/id-ID/langmetadata.xml
  installation/language/it-IT/langmetadata.xml
  installation/language/ja-JP/langmetadata.xml
  installation/language/ka-GE/langmetadata.xml
  installation/language/kk-KZ/langmetadata.xml
  installation/language/ko-KR/langmetadata.xml
  installation/language/lt-LT/langmetadata.xml
  installation/language/lv-LV/langmetadata.xml
  installation/language/mk-MK/langmetadata.xml
  installation/language/nl-BE/langmetadata.xml
  installation/language/nl-NL/langmetadata.xml
  installation/language/pl-PL/langmetadata.xml
  installation/language/pt-BR/joomla.ini
  installation/language/pt-BR/langmetadata.xml
  installation/language/pt-PT/langmetadata.xml
  installation/language/ro-RO/langmetadata.xml
  installation/language/sk-SK/langmetadata.xml
  installation/language/sl-SI/langmetadata.xml
  installation/language/sr-YU/langmetadata.xml
  installation/language/sv-SE/langmetadata.xml
  installation/language/ta-IN/langmetadata.xml
  installation/language/th-TH/langmetadata.xml
  installation/language/tr-TR/langmetadata.xml
  installation/language/uk-UA/langmetadata.xml
  installation/language/ur-PK/joomla.ini
  installation/language/ur-PK/langmetadata.xml
  installation/language/vi-VN/langmetadata.xml
  installation/language/zh-CN/langmetadata.xml
  installation/language/zh-TW/langmetadata.xml
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Version.php
Labels: Language Change, PR-5.2-dev

#43350 [5.2] Cleanup of return types for phpstan
  administrator/components/com_admin/script.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_languages/src/Model/OverridesModel.php
  administrator/components/com_menus/src/Controller/MenuController.php
  administrator/components/com_modules/src/Controller/ModuleController.php
Labels: Feature, PR-5.2-dev

#43487 Update tests/README.md
  tests/README.md
Labels: Unit/System Tests, PR-4.4-dev
