Repository joomla/joomla-cms, pull requests merged in 2024-01, with the labels that each got.

#42591 [5.0] Upmerge 2024-01-02
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default.php
  api/components/com_content/src/Controller/ArticlesController.php
  libraries/src/Extension/ExtensionHelper.php
Labels: PR-5.0-dev

#42609 [5.1] upmerge 2024-01-04
  .drone.yml
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/plg_task_deleteactionlogs.ini
  administrator/language/en-GB/plg_task_sessiongc.ini
  api/components/com_content/src/Controller/ArticlesController.php
  build/media_source/com_media/scss/components/_media-browser.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_layout.scss
  composer.lock
  language/en-GB/lib_joomla.ini
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Form/Form.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: Unit/System Tests, Language Change, Composer Dependency Changed, NPM Resource Changed, PR-5.1-dev

#42584 [5.1] add language deprecation for #37320
  administrator/language/en-GB/com_fields.ini
  administrator/language/en-GB/plg_fields_list.ini
  administrator/language/en-GB/plg_fields_sql.ini
  plugins/fields/subform/params/subform.xml
Labels: RTC, Language Change, PR-5.1-dev

#42505 [5.1] Tests readme
  tests/Integration/README.md
  tests/Unit/README.md
Labels: RTC, Unit/System Tests, PR-5.1-dev

#42620 Revert "[5.1] upmerge 2024-01-04"
  .drone.yml
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/plg_task_deleteactionlogs.ini
  administrator/language/en-GB/plg_task_sessiongc.ini
  api/components/com_content/src/Controller/ArticlesController.php
  build/media_source/com_media/scss/components/_media-browser.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_layout.scss
  composer.lock
  language/en-GB/lib_joomla.ini
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Form/Form.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: Unit/System Tests, Language Change, Composer Dependency Changed, NPM Resource Changed, PR-5.1-dev

#42624 [5.1] upmerge 2024-01-04 fix
  .drone.yml
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_joomlaupdate/tmpl/joomlaupdate/noupdate.php
  administrator/components/com_menus/tmpl/items/modal.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/tmpl/template/default.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/lib_joomla.ini
  administrator/language/en-GB/plg_task_deleteactionlogs.ini
  administrator/language/en-GB/plg_task_sessiongc.ini
  api/components/com_content/src/Controller/ArticlesController.php
  build/media_source/com_media/scss/components/_media-browser.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_footer.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_layout.scss
  composer.lock
  language/en-GB/lib_joomla.ini
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Form/Form.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: Unit/System Tests, Language Change, Composer Dependency Changed, NPM Resource Changed, PR-5.1-dev

#42607 [5.1] Uninstall child of package
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
  libraries/src/Installer/InstallerAdapter.php
Labels: RTC, Language Change, PR-5.1-dev

#42402 [5.1] Article Schemaorg plugin
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2023-11-28.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2023-11-28.sql
  administrator/language/en-GB/plg_schemaorg_article.ini
  administrator/language/en-GB/plg_schemaorg_article.sys.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/schemaorg/article/article.xml
  plugins/schemaorg/article/forms/schemaorg.xml
  plugins/schemaorg/article/services/provider.php
  plugins/schemaorg/article/src/Extension/Article.php
Labels: Feature, RTC, Language Change, PR-5.1-dev

#42599 [4.4] check for valid referrer
  libraries/src/MVC/Controller/BaseController.php
Labels: RTC, PR-4.4-dev

#42586 [5.0] Tags: Add rebuild button to toolbar
  administrator/components/com_tags/src/View/Tags/HtmlView.php
Labels: RTC, PR-5.1-dev

#42638 [4.4] Fix parameter type for whereIn query in ExtensionsHelper - issue 42637
  libraries/src/Extension/ExtensionHelper.php
Labels: RTC, bug, PR-4.4-dev

#42635 Define correct type for field helper doc
  administrator/components/com_fields/src/Helper/FieldsHelper.php
Labels: RTC, PR-4.4-dev

#42616 [4.4] text not visible (error_login)
  administrator/templates/atum/error_login.php
Labels: RTC, bug, PR-4.4-dev

#41973 [5.1] Invalid class
  administrator/components/com_admin/script.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  libraries/src/Installer/LegacyInstallerScript.php
  plugins/content/contact/src/Extension/Contact.php
  plugins/fields/calendar/src/Extension/Calendar.php
  plugins/fields/color/src/Extension/Color.php
  plugins/fields/editor/src/Extension/Editor.php
  plugins/fields/imagelist/src/Extension/Imagelist.php
  plugins/fields/list/src/Extension/ListPlugin.php
  plugins/fields/media/src/Extension/Media.php
  plugins/fields/sql/src/Extension/SQL.php
  plugins/fields/url/src/Extension/Url.php
  plugins/fields/user/src/Extension/User.php
  plugins/installer/folderinstaller/tmpl/default.php
  plugins/installer/webinstaller/tmpl/default.php
  plugins/sampledata/testing/src/Extension/Testing.php
  plugins/system/guidedtours/src/Extension/GuidedTours.php
  plugins/system/jooa11y/src/Extension/Jooa11y.php
  plugins/system/remember/src/Extension/Remember.php
  plugins/system/stats/layouts/message.php
  plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
  plugins/workflow/featuring/src/Extension/Featuring.php
  plugins/workflow/publishing/src/Extension/Publishing.php
Labels: Feature, Maintainers Checked, PR-5.1-dev

#42334 [5.1] Subform rows sorting with buttons, addittionaly to drag and drop
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js
  build/media_source/templates/administrator/atum/scss/blocks/_form.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_form.scss
  layouts/joomla/form/field/subform/repeatable/section-byfieldsets.php
  layouts/joomla/form/field/subform/repeatable/section.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-5.1-dev

#42601 [5.1] CLI: Core Update - improve output
  libraries/src/Console/UpdateCoreCommand.php
Labels: Feature, RTC, PR-5.1-dev

#42423 [5.1] Use Dialog for Module editing
  administrator/components/com_cpanel/tmpl/cpanel/default.php
  administrator/components/com_menus/tmpl/item/edit_modules.php
  administrator/components/com_menus/tmpl/menus/default.php
  administrator/components/com_modules/src/Controller/ModuleController.php
  administrator/components/com_modules/src/View/Module/HtmlView.php
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_modules/tmpl/module/modal.php
  administrator/components/com_modules/tmpl/module/modalreturn.php
  build/media_source/com_cpanel/joomla.asset.json
  build/media_source/com_cpanel/js/admin-add_module.es6.js
  build/media_source/com_menus/js/admin-item-edit_modules.es6.js
  build/media_source/com_menus/js/admin-menus-default.es6.js
  build/media_source/com_modules/joomla.asset.json
  build/media_source/com_modules/js/admin-module-edit.es6.js
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev

#42588 [4.4] Fix missing 'separator' lines between sub menus in Admin Components
  libraries/src/Installer/Adapter/ComponentAdapter.php
Labels: RTC, PR-4.4-dev

#42659 Upmerge
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/templates/atum/error_login.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/Router/SiteRouter.php
  libraries/src/Updater/Update.php
  package.json
Labels: NPM Resource Changed, PR-5.0-dev

#42656 [5.0] Codemirror RTL fix in com_templates
  build/media_source/com_templates/css/admin-templates-default.css
Labels: RTC, NPM Resource Changed, bug, PR-5.0-dev

#42610 [5.1] Add toolbar buttons in language installation toolbar
  administrator/components/com_installer/src/View/Languages/HtmlView.php
  administrator/language/en-GB/com_installer.ini
Labels: Feature, RTC, Language Change, PR-5.1-dev

#42595 [5.0] Is not in development
  README.md
  README.txt
Labels: PR-5.0-dev

#42473 Route the redirect in the menu logout
  components/com_users/src/Controller/UserController.php
Labels: PR-4.4-dev

#42563 [4.4] Api test for com_menus.
  tests/System/integration/api/com_menus/Site.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, PR-4.4-dev

#42602 Language install core loader - Show Joomla Spinner on language install
  administrator/components/com_installer/tmpl/languages/default.php
Labels: RTC, PR-4.4-dev

#42663 [5.1] Unification patch for PR #42610
  administrator/components/com_installer/src/View/Languages/HtmlView.php
  administrator/language/en-GB/com_installer.ini
Labels: Language Change, PR-5.1-dev

#42667 [5.1] upmerge 2024-01-17
  administrator/components/com_fields/src/Helper/FieldsHelper.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/templates/atum/error_login.php
  build/media_source/com_templates/css/admin-templates-default.css
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/Router/SiteRouter.php
  libraries/src/Updater/Update.php
  package.json
Labels: NPM Resource Changed, PR-5.1-dev

#42594 [5.1] CLI: Renaming and improving output of core:update:check
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Console/CheckJoomlaUpdatesCommand.php
Labels: Feature, RTC, PR-5.1-dev

#42597 [5.1] CLI: Adding command to manage Joomla core update channels
  libraries/src/Console/CoreUpdateChannelCommand.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Console.php
Labels: Feature, RTC, PR-5.1-dev

#42395 Update passwordstrength.es6.js
  build/media_source/system/js/fields/passwordstrength.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#42629 Build: Create checksum_update.txt file with tags
  build/build.php
Labels: PR-4.4-dev

#42670 [4.4] Atom Feed: Prevent notice from empty description
  libraries/src/Document/Renderer/Feed/AtomRenderer.php
Labels: RTC, PHP 8.x, bug, PR-4.4-dev

#42623 [5.x] Fix broken parameters for bzip2 and zstd packages in the build/build.php script
  .drone.yml
  build/build.php
Labels: Unit/System Tests, PR-5.0-dev

#42683 [5.0] Codemirror Full Screen background
  build/media_source/plg_editors_codemirror/css/codemirror.css
Labels: RTC, NPM Resource Changed, PR-5.0-dev

#42691 [4.4] Media Manager long filenames
  build/media_source/com_media/scss/components/_media-browser.scss
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#42696 [5.0] Upmerged 2024-01-22
  .github/workflows/cacert-update.yml
  .github/workflows/create-translation-pull-request-v4.yml
  administrator/components/com_installer/tmpl/languages/default.php
  build/build.php
  build/media_source/com_media/scss/components/_media-browser.scss
  components/com_users/src/Controller/UserController.php
  libraries/src/Document/Renderer/Feed/AtomRenderer.php
  plugins/multifactorauth/email/src/Extension/Email.php
  plugins/multifactorauth/totp/src/Extension/Totp.php
  tests/System/integration/api/com_menus/Administrator.cy.js
  tests/System/integration/api/com_menus/Site.cy.js
  tests/System/support/commands/db.js
Labels: Unit/System Tests, NPM Resource Changed, PR-5.0-dev

#42652 [5.0] Update error.php
  templates/cassiopeia/error.php
Labels: RTC, bug, PR-5.0-dev

#42581 com_contact. Rm unused order_up, order_dn
  administrator/components/com_contact/src/View/Contacts/HtmlView.php
Labels: RTC, RMDQ, PR-5.1-dev

#42214 [5.1] Convert mod_banners to service provider
  modules/mod_banners/mod_banners.php
  modules/mod_banners/mod_banners.xml
  modules/mod_banners/services/provider.php
  modules/mod_banners/src/Dispatcher/Dispatcher.php
  modules/mod_banners/src/Helper/BannersHelper.php
Labels: Feature, PR-5.1-dev

#42708 [4.4]Added an api test for site menu items.
  tests/System/integration/api/com_menus/SiteMenuItems.cy.js
Labels: Unit/System Tests, PR-4.4-dev

#42606 Change type of field "value" in table #_fields_values from text to mediumtext
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-01-04.sql
  installation/sql/mysql/supports.sql
Labels: Feature, RTC, PR-5.1-dev

#41968 [5.1] Useless isset argument
  components/com_tags/src/Helper/RouteHelper.php
Labels: Feature, RTC, Maintainers Checked, PR-5.1-dev

#42355 [5.1] Use Dialog for Batch for Redirect component
  administrator/components/com_redirect/src/View/Links/HtmlView.php
  administrator/components/com_redirect/tmpl/links/default.php
  administrator/components/com_redirect/tmpl/links/default_batch_body.php
  administrator/components/com_redirect/tmpl/links/default_batch_footer.php
  administrator/components/com_redirect/tmpl/links/emptystate.php
Labels: Feature, RTC, PR-5.1-dev

#42448 [5.1] HTML Mail template images
  libraries/src/Mail/MailHelper.php
Labels: RTC, PR-5.1-dev

#42661 [5.1] WebAsset fix for calling the onAttachCallback, and cache for tree sorting to improve performance
  libraries/src/Document/Renderer/Html/MetasRenderer.php
  libraries/src/WebAsset/WebAssetManager.php
Labels: RTC, bug, PR-5.1-dev

#42453 [5.1] Use Dialog for extensions changelog
  administrator/components/com_installer/src/Controller/ManageController.php
  administrator/components/com_installer/tmpl/manage/default.php
  administrator/components/com_installer/tmpl/update/default.php
  build/media_source/com_installer/joomla.asset.json
Labels: Feature, RTC, NPM Resource Changed, PR-5.1-dev
