Repository joomla/joomla-cms, pull requests merged in 2024-03, with the labels that each got.

#39546 [4.4] Fix showon for list field (no multiple)
  layouts/joomla/form/field/list-fancy-select.php
  layouts/joomla/form/field/list.php
Labels: RTC, PBF, bug, Small, PR-4.4-dev

#42728 [4.4] Hide columns in mobile view
  administrator/components/com_cache/tmpl/cache/default.php
Labels: RTC, PBF, Small, PR-4.4-dev

#42929 [5.1] Convert mod_languages to service provider
  modules/mod_languages/mod_languages.php
  modules/mod_languages/mod_languages.xml
  modules/mod_languages/services/provider.php
  modules/mod_languages/src/Dispatcher/Dispatcher.php
  modules/mod_languages/src/Helper/LanguagesHelper.php
Labels: RTC, PR-5.1-dev

#42762 [5.1] Switching Folder::makeSafe() to framework version
  administrator/components/com_contenthistory/src/Helper/ContenthistoryHelper.php
Labels: PR-5.1-dev

#41965 [5.1][Events] PageCache event classes
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/PageCache/GetKeyEvent.php
  libraries/src/Event/PageCache/IsExcludedEvent.php
  libraries/src/Event/PageCache/PageCacheEvent.php
  libraries/src/Event/PageCache/SetCachingEvent.php
  plugins/system/cache/src/Extension/Cache.php
Labels: Feature, RTC, PR-5.1-dev

#40131 [5.1] Migrating Joomla\CMS\Filesystem\Folder::exists() to is_dir()
  administrator/components/com_admin/script.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Form/Rule/FolderPathExistsRule.php
  libraries/src/Installer/Adapter/FileAdapter.php
  libraries/src/Installer/Adapter/LanguageAdapter.php
  libraries/src/Installer/Adapter/LibraryAdapter.php
  libraries/src/Installer/Adapter/PackageAdapter.php
  libraries/src/Installer/Adapter/TemplateAdapter.php
  libraries/src/Installer/Installer.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/Installer/InstallerScript.php
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: Feature, RTC, Maintainers Checked, PR-5.0-dev, PR-5.1-dev

#42761 [5.1] Switching Folder::files() to framework version
  administrator/components/com_admin/src/Model/HelpModel.php
  administrator/components/com_banners/src/Model/TracksModel.php
  administrator/components/com_fields/src/Field/FieldLayoutField.php
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  administrator/components/com_languages/src/Model/StringsModel.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Schema/ChangeSet.php
  plugins/editors/tinymce/src/Extension/TinyMCE.php
  plugins/task/rotatelogs/src/Extension/RotateLogs.php
Labels: PR-5.1-dev

#42736 [5.1] Header list field
  administrator/language/en-GB/plg_fields_list.ini
  libraries/src/Form/Field/ListField.php
  libraries/src/Form/Field/SqlField.php
  plugins/fields/list/list.xml
  plugins/fields/list/params/list.xml
Labels: Feature, RTC, Language Change, Updates Requested, PBF, PR-5.1-dev

#42519 [5][webservices] add filter by search
  api/components/com_categories/src/Controller/CategoriesController.php
  api/components/com_tags/src/Controller/TagsController.php
Labels: RTC, PR-5.1-dev

#42427 [5.x] Drop postcss, own package
  build/build-modules-js/css-versioning.es6.js
  package-lock.json
  package.json
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#42428 [5.x] Localize own package
  build/build-modules-js/compress.es6.js
  build/build-modules-js/utils/compressFile.es6.js
  package-lock.json
  package.json
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#38787 [5.1] Menus and categories view with equal headline
  administrator/components/com_banners/tmpl/clients/default.php
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_categories.ini
  package-lock.json
Labels: Feature, RTC, Language Change, a11y, NPM Resource Changed, PBF, UI/UX, PR-5.1-dev

#42729 [5.1] Deprecating RouterLegacy class
  libraries/src/Component/Router/RouterLegacy.php
Labels: Feature, b/c break, PR-5.1-dev

#41981 [5.1] Duplicate DispatcherAwareInterface implementation
  libraries/src/Application/BaseApplication.php
  libraries/src/Application/CliApplication.php
  libraries/src/Application/ConsoleApplication.php
Labels: Feature, Maintainers Checked, PR-5.1-dev

#42935 [5.1] Update deleted files list in script.php for 5.1.0-beta1
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#42940 [4.4] Spelling mistake
  administrator/language/en-GB/plg_system_jooa11y.ini
Labels: RTC, Language Change, PR-4.4-dev

#42941 [5.1] Remove string JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED
  administrator/language/en-GB/lib_joomla.ini
  language/en-GB/lib_joomla.ini
Labels: RTC, Language Change, PR-5.1-dev

#42510 [5.1] Allow custom fields form be manipulates like category form
  administrator/components/com_contact/src/Extension/ContactComponent.php
  administrator/components/com_content/src/Extension/ContentComponent.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_users/src/Extension/UsersComponent.php
  libraries/src/Extension/LegacyComponent.php
  libraries/src/Fields/FieldsFormServiceInterface.php
  libraries/src/Fields/FieldsServiceTrait.php
Labels: Feature, RTC, PR-5.1-dev

#42943 [5.1] Pin PHP-TUF package version
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.1-dev

#42944 [5.1] Fix tooltips in categories
  administrator/components/com_categories/tmpl/categories/default.php
  administrator/language/en-GB/com_banners.ini
  administrator/language/en-GB/com_categories.ini
Labels: RTC, Language Change, PR-5.1-dev

#42930 [5.1] TinyMCE 6.8.3
  package-lock.json
  plugins/editors/tinymce/tinymce.xml
Labels: NPM Resource Changed, PR-5.1-dev

#42774 Time Zone form field to use groupedlist fancy select layout
  administrator/components/com_config/forms/application.xml
  administrator/components/com_users/forms/user.xml
  components/com_users/forms/frontend.xml
  libraries/src/Form/Field/GroupedlistField.php
Labels: Feature, PR-5.1-dev

#41532 Fix PHPDoc in HtmlDocument
  libraries/src/Document/HtmlDocument.php
Labels: Feature, PR-5.1-dev

#42844 [5][cli] Update:extension:check command
  libraries/src/Console/CheckUpdatesCommand.php
Labels: Feature, RTC, PBF, PR-5.1-dev

#42092 [5.1] webservices plugins use concrete event classes
  plugins/webservices/banners/src/Extension/Banners.php
  plugins/webservices/config/src/Extension/Config.php
  plugins/webservices/contact/src/Extension/Contact.php
  plugins/webservices/content/src/Extension/Content.php
  plugins/webservices/installer/src/Extension/Installer.php
  plugins/webservices/languages/src/Extension/Languages.php
  plugins/webservices/media/src/Extension/Media.php
  plugins/webservices/menus/src/Extension/Menus.php
  plugins/webservices/messages/src/Extension/Messages.php
  plugins/webservices/modules/src/Extension/Modules.php
  plugins/webservices/newsfeeds/src/Extension/Newsfeeds.php
  plugins/webservices/plugins/src/Extension/Plugins.php
  plugins/webservices/privacy/src/Extension/Privacy.php
  plugins/webservices/redirect/src/Extension/Redirect.php
  plugins/webservices/tags/src/Extension/Tags.php
  plugins/webservices/templates/src/Extension/Templates.php
  plugins/webservices/users/src/Extension/Users.php
Labels: Feature, PR-5.1-dev

#42568 [5][cli] maintenance database update db structure
  libraries/src/Console/MaintenanceDatabaseCommand.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Console.php
Labels: Feature, RTC, PBF, PR-5.1-dev

#42932 [5.1] Fix SEF redirect while executing parseRule
  plugins/system/sef/src/Extension/Sef.php
Labels: Release Blocker, bug, PR-5.1-dev

#42090 [5.1] Deprecate app/db properties in ActionLogPlugin
  administrator/components/com_actionlogs/src/Plugin/ActionLogPlugin.php
Labels: Feature, PR-5.1-dev

#42945 [5.1] Updates the dependencies
  composer.json
  composer.lock
  package-lock.json
  package.json
  plugins/system/debug/src/AbstractDataCollector.php
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.1-dev

#42928 [4.4]Update plg_system_privacyconsent.ini
  administrator/language/en-GB/plg_system_privacyconsent.ini
Labels: RTC, Language Change, PR-4.4-dev

#42949 [5.1] remove joomla accessibility checker
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-5.1-dev

#42925 [4.4] Fix articles categories module bug
  modules/mod_articles_categories/src/Helper/ArticlesCategoriesHelper.php
Labels: RTC, bug, PR-4.4-dev

#42871 [4.4] Fix System - Page Cache plugin ignore Exclude URLs parameter
  plugins/system/cache/src/Extension/Cache.php
Labels: RTC, PR-4.4-dev

#42870 [4.4] Fix cancel frontend module editing redirection
  components/com_config/src/Controller/ModulesController.php
Labels: RTC, PR-4.4-dev

#42950 [5.1] upmerge 2024-03-04
  administrator/components/com_cache/tmpl/cache/default.php
  administrator/components/com_scheduler/src/Rule/ExecutionRulesRule.php
  administrator/language/en-GB/plg_system_privacyconsent.ini
  components/com_config/src/Controller/ModulesController.php
  layouts/joomla/form/field/list-fancy-select.php
  layouts/joomla/form/field/list.php
  libraries/src/Installer/Adapter/ModuleAdapter.php
  libraries/src/Mail/MailerFactory.php
  modules/mod_articles_categories/src/Helper/ArticlesCategoriesHelper.php
  plugins/system/cache/src/Extension/Cache.php
Labels: Language Change, PR-5.1-dev

#42951 [5.1] Update deleted files list in script.php for 5.1.0-beta1 (2)
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#42895 [4.x] Treeselect fixes
  build/media_source/legacy/joomla.asset.json
  build/media_source/legacy/js/treeselectmenu.es5.js
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#42802 [4.4] Fixing non-SEF URL in feed output
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, PBF, bug, PR-4.4-dev

#42706 [4.4] Feed: Fixing link selection of AtomParser
  libraries/src/Feed/Parser/AtomParser.php
Labels: RTC, PBF, bug, PR-4.4-dev

#42835 [4.4] Smart Search: Properly sort filters
  administrator/components/com_finder/src/Service/HTML/Filter.php
Labels: PBF, bug, PR-4.4-dev

#42461 [6.x] Use Dialog for Article links, when "modal option" is selected
  components/com_content/tmpl/article/default_links.php
Labels: Feature, RTC, PBF, PR-6.0-dev

#42966 [5.1] Typo plg_system_jooa11y.ini
  administrator/language/en-GB/plg_system_jooa11y.ini
Labels: Language Change, PR-5.1-dev

#42953 [5.1] remove deprecated language strings from up-merge #42950
  administrator/language/en-GB/plg_system_privacyconsent.ini
Labels: RTC, Language Change, PR-5.1-dev

#42969 [6.0] Set version to 6.0
  .drone.yml
  README.md
  README.txt
  libraries/src/Version.php
  package.json
  renovate.json
  tests/Unit/Libraries/Cms/Updater/ConstraintCheckerTest.php
Labels: Unit/System Tests, NPM Resource Changed, PR-6.0-dev

#42975 Shorten path to global CSS folder
  templates/cassiopeia/index.php
Labels: RTC

#42970 [5.2] Set version to 5.2
  .drone.yml
  README.md
  README.txt
  libraries/src/Version.php
  package.json
  renovate.json
Labels: RTC, Unit/System Tests, PR-5.2-dev

#42954 [5.1] replace web-token/signature-pack with web-token/jwt-library
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-5.1-dev

#42988 [5.1] Fix SQL error 1242 "Subquery returns more than 1 row" on update when having multiple update sites for the core
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-02-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-02-24.sql
Labels: RTC, Release Blocker, bug, PR-5.1-dev

#42978 [5.1] Aliasing Filesystem classes for installation, updating script.php
  administrator/components/com_admin/script.php
  administrator/components/com_joomlaupdate/finalisation.php
Labels: RTC, Release Blocker, bug, PR-5.1-dev

#42221 [5.x] Template color scheme configuration
  administrator/components/com_users/forms/user.xml
  administrator/language/en-GB/com_users.ini
  administrator/language/en-GB/mod_user.ini
  administrator/language/en-GB/tpl_atum.ini
  administrator/modules/mod_user/tmpl/default.php
  administrator/templates/atum/component.php
  administrator/templates/atum/error_full.php
  administrator/templates/atum/error_login.php
  administrator/templates/atum/index.php
  administrator/templates/atum/login.php
  administrator/templates/atum/templateDetails.xml
  build/media_source/plg_editors_codemirror/js/codemirror.es6.js
  build/media_source/plg_editors_tinymce/js/tinymce.es6.js
  build/media_source/templates/administrator/atum/js/template.es6.js
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/blocks/_utilities.scss
  components/com_users/forms/frontend.xml
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  language/en-GB/com_users.ini
Labels: Feature, Language Change, NPM Resource Changed, PBF, PR-5.1-dev, Dark Mode

#42938 [4.4] [BUGFIX] Enforce UTF-8 on CSS Files
  build/build-modules-js/stylesheets/handle-css.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
Labels: RTC, PR-4.4-dev

#42994 [5.1] Fix version check in Joomla Update component
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
Labels: RTC, Release Blocker, bug, PR-5.1-dev

#43004 [5.1] Update TUF client version
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.1-dev

#43002 [5.1] - Fix JHTTP socket transport http version
  composer.lock
  libraries/src/Http/Transport/SocketTransport.php
Labels: Composer Dependency Changed, Release Blocker, PR-5.1-dev

#42992 [5.1] Fix Send Email button class name
  administrator/components/com_users/src/View/Mail/HtmlView.php
Labels: RTC, PR-5.1-dev

#43008 [5.1] Fix fancy-select for Dark Mode
  build/media_source/templates/administrator/atum/scss/vendor/choicesjs/choices.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43017 [5.1] Dark Mode Web Installer List
  build/media_source/templates/administrator/atum/scss/pages/_plg_web_installer.scss
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev, Dark Mode

#43010 [5.1] Dark mode settings block - to template settings
  administrator/components/com_users/forms/user.xml
  administrator/modules/mod_user/tmpl/default.php
Labels: RTC, bug, PR-5.1-dev, Dark Mode

#42985 [5][com_installer] add toolbar button 1 click
  administrator/components/com_installer/src/View/Manage/HtmlView.php
  administrator/components/com_installer/src/View/Update/HtmlView.php
Labels: RTC, PR-5.1-dev

#43001 [4.x] Fix JHTTP socket transport http version
  composer.json
  composer.lock
  libraries/src/Http/Transport/SocketTransport.php
Labels: RTC, Composer Dependency Changed, PR-4.4-dev

#42990 [5.1] Convert mod_login to service provider
  administrator/modules/mod_login/mod_login.php
  administrator/modules/mod_login/mod_login.xml
  administrator/modules/mod_login/services/provider.php
  administrator/modules/mod_login/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_login/src/Helper/LoginHelper.php
Labels: RTC, PR-5.1-dev

#42977 [5.1] Replace deprecated Factory::getDbo() by $this->getDbo()
  libraries/src/Updater/Updater.php
Labels: RTC, PR-5.1-dev

#42903 [5.1] Core loader custom element rework
  administrator/modules/mod_sampledata/tmpl/default.php
  build/media_source/mod_sampledata/js/sampledata-process.es6.js
  build/media_source/system/js/joomla-core-loader.w-c.es6.js
  build/media_source/system/scss/joomla-core-loader.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#41659 [5.1] Guided tours welcome tour
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-03-08.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-03-08.sql
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/language/en-GB/guidedtours.joomla_welcome.ini
  administrator/language/en-GB/guidedtours.joomla_welcome_steps.ini
  build/media_source/plg_system_guidedtours/js/guidedtours.es6.js
  components/com_newsfeeds/src/View/Category/HtmlView.php
  components/com_newsfeeds/src/View/Newsfeed/HtmlView.php
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  package-lock.json
  package.json
  plugins/system/guidedtours/src/Extension/GuidedTours.php
  tests/System/integration/install/Installation.cy.js
  tests/System/support/commands.js
  tests/System/support/commands/db.js
Labels: Feature, Unit/System Tests, Language Change, NPM Resource Changed, PR-5.1-dev

#42968 [5] contact error when deleting alias
  administrator/components/com_contact/src/Table/ContactTable.php
Labels: RTC, PR-5.1-dev

#42959 [5.1] Form validation: throw error instead of warning
  administrator/components/com_config/src/Controller/ApplicationController.php
  administrator/components/com_finder/src/Controller/FilterController.php
  administrator/components/com_languages/src/Controller/OverrideController.php
  administrator/components/com_mails/src/Controller/TemplateController.php
  administrator/components/com_menus/src/Controller/ItemController.php
  administrator/components/com_menus/src/Controller/MenuController.php
  administrator/components/com_messages/src/Controller/ConfigController.php
  administrator/components/com_templates/src/Controller/StyleController.php
  administrator/components/com_templates/src/Controller/TemplateController.php
  components/com_users/src/Controller/ProfileController.php
  components/com_users/src/Controller/RegistrationController.php
  libraries/src/MVC/Controller/FormController.php
Labels: RTC, PR-5.1-dev

#42900 [5.1] TUF Code Cleanup
  libraries/src/Factory.php
  libraries/src/Http/HttpFactory.php
  libraries/src/Http/HttpFactoryInterface.php
  libraries/src/Service/Provider/Http.php
  libraries/src/TUF/TufFetcher.php
  libraries/src/Updater/Adapter/TufAdapter.php
  libraries/src/Updater/Update.php
Labels: RTC, Release Blocker, PR-5.1-dev

#43027 [5.1] Upmerge 2024-03-14
  administrator/components/com_finder/src/Service/HTML/Filter.php
  build/build-modules-js/stylesheets/handle-css.es6.js
  build/build-modules-js/stylesheets/handle-scss.es6.js
  build/build-modules-js/stylesheets/scss-transform.es6.js
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
  build/media_source/templates/site/cassiopeia/scss/global/colors_alternative.scss
  build/media_source/templates/site/cassiopeia/scss/global/colors_standard.scss
  libraries/src/Feed/Parser/AtomParser.php
  plugins/system/highlight/src/Extension/Highlight.php
  plugins/system/sef/src/Extension/Sef.php
  templates/cassiopeia/index.php
Labels: NPM Resource Changed, PR-5.1-dev

#38573 [5.1]Installation Language
  installation/src/Form/Field/Installation/LanguageField.php
  libraries/src/Language/LanguageHelper.php
Labels: Feature, RTC, PR-5.1-dev

#43018 [5.1] DARK MODE installer drag and drop
  build/media_source/com_installer/css/installer.css
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev, Dark Mode

#43009 [5.1] Revert implementation of AfterInitialiseRouterEvent
  libraries/src/Event/Router/AfterInitialiseRouterEvent.php
  libraries/src/Event/Router/RouterEvent.php
  libraries/src/Service/Provider/Router.php
  plugins/system/languagefilter/services/provider.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
  plugins/system/sef/services/provider.php
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, Release Blocker, bug, PR-5.1-dev

#43033 [4.4] Drone: Fix artifacts upload for 4.4-dev
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#43034 [5.1] Drone: Fix artifacts upload for 5.1-dev
  .drone.yml
Labels: Unit/System Tests, PR-5.1-dev

#43035 [5.2] Drone: Fix artifacts upload for 5.2-dev
  .drone.yml
Labels: Unit/System Tests, PR-5.2-dev

#43036 [6.0] Drone: Fix artifacts upload for 6.0-dev
  .drone.yml
Labels: Unit/System Tests, PR-6.0-dev

#43044 [4.4] When duplicating a tour with 0 (no) steps, SQL fails
  administrator/components/com_guidedtours/src/Model/TourModel.php
Labels: PR-4.4-dev

#43023 [5.1] spinner support for color schemes
  build/media_source/system/js/joomla-core-loader.w-c.es6.js
  build/media_source/system/scss/joomla-core-loader.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43037 [5.1] Guided tours dialog box outline is invisible in dark mode
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43061 [5.1] Guided Tours Welcome Text Update Step 1
  administrator/language/en-GB/guidedtours.joomla_welcome.ini
Labels: Language Change, PR-5.1-dev

#43054 [5.1] Database installation Fields
  installation/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-5.1-dev

#42987 [5.1] Convert mod_post_installation_messages to service provider
  administrator/modules/mod_post_installation_messages/mod_post_installation_messages.php
  administrator/modules/mod_post_installation_messages/mod_post_installation_messages.xml
  administrator/modules/mod_post_installation_messages/services/provider.php
  administrator/modules/mod_post_installation_messages/src/Dispatcher/Dispatcher.php
Labels: RTC, PR-5.1-dev

#43031 [5.1] Update TourTable.php to allow save on tours
  administrator/components/com_guidedtours/src/Table/TourTable.php
Labels: RTC, bug, PR-5.1-dev

#43058 [5.1] Dialog: aria-label for Close button is not translated
  build/media_source/system/js/joomla-dialog.w-c.es6.js
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43038 [5.1] Tour primary button changes size on hover, adding annoying flicker
  build/media_source/plg_system_guidedtours/scss/guidedtours.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#42804 [5] MFA fixed code
  administrator/components/com_users/src/DataShape/CaptiveRenderOptions.php
Labels: RTC, PR-5.1-dev

#43006 [5.1] Explicit return false when no form field was found
  libraries/src/Form/Form.php
Labels: RTC, PR-5.1-dev

#42972 [5.1] Typehint false for getItem
  libraries/src/MVC/Model/AdminModel.php
Labels: RTC, PR-5.1-dev

#43057 [4.4] Cassiopeia back to top
  build/media_source/templates/site/cassiopeia/scss/blocks/_back-to-top.scss
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#43045 [5.1] Update deleted files list in script.php for 5.1.0-beta2 (2)
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#43050 [5.1][com_users] fix batch-copy-move
  administrator/components/com_users/tmpl/users/default_batch_body.php
Labels: RTC, PR-5.1-dev

#43074 [5.1] Trailing Slash: Don't remove slash when it's the only path char
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, PR-5.1-dev

#43064 [5.1] Missing checkbox/radio and select types constants in array
  administrator/components/com_guidedtours/src/Extension/GuidedtoursComponent.php
Labels: RTC, PR-5.1-dev

#43021 [5.1] Let Table extend stdClass
  libraries/src/Table/Table.php
Labels: PR-5.1-dev

#42778 [5.1] Minor cleanup for component JS
  build/media_source/com_actionlogs/js/admin-actionlogs-default.es6.js
  build/media_source/com_admin/js/admin-help.es6.js
  build/media_source/com_associations/js/associations-edit.es6.js
  build/media_source/com_cache/js/admin-cache-default.es6.js
  build/media_source/com_categories/js/shared-categories-accordion.es6.js
  build/media_source/com_config/js/config-default.es6.js
  build/media_source/com_config/js/config-filters.es6.js
  build/media_source/com_config/js/modules-default.es6.js
  build/media_source/com_config/js/templates-default.es6.js
  build/media_source/com_contact/js/admin-contacts-modal.es6.js
  build/media_source/com_content/js/articles-status.es6.js
  build/media_source/com_content/js/form-edit.es6.js
  build/media_source/com_contenthistory/js/admin-compare-compare.es6.js
  build/media_source/com_cpanel/js/admin-cpanel-default.es6.js
  build/media_source/com_cpanel/js/admin-system-loader.es6.js
  build/media_source/com_fields/js/admin-field-changecontext.es6.js
  build/media_source/com_finder/js/finder-edit.es6.js
  build/media_source/com_finder/js/finder.es6.js
  build/media_source/com_joomlaupdate/js/default.es6.js
  build/media_source/com_languages/js/admin-language-edit-change-flag.es6.js
  build/media_source/com_languages/js/overrider.es6.js
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/com_menus/js/admin-item-edit.es6.js
  build/media_source/com_menus/js/admin-item-edit_container.es6.js
  build/media_source/com_menus/js/admin-item-edit_modules.es6.js
  build/media_source/com_menus/js/admin-items-modal.es6.js
  build/media_source/com_modules/js/admin-module-search.es6.js
  build/media_source/com_modules/js/admin-select-modal.es6.js
  build/media_source/com_scheduler/js/admin-view-select-task-search.es6.js
  build/media_source/com_templates/js/admin-template-toggle-assignment.es6.js
  build/media_source/com_templates/js/admin-templates-default.es6.js
  build/media_source/com_users/js/two-factor-list.es6.js
  build/media_source/com_workflow/js/admin-items-workflow-buttons.es6.js
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43083 [5.1] SEF: Don't redirect for documents other than HTML
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, bug, PR-5.1-dev

#43086 [5.1] Upmerge 2024-03-18
  administrator/components/com_guidedtours/src/Model/TourModel.php
  build/media_source/templates/site/cassiopeia/scss/blocks/_back-to-top.scss
Labels: NPM Resource Changed, PR-5.1-dev

#42995 [5.1] Alert links system container [a11y]
  administrator/language/en-GB/com_installer.ini
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
Labels: Language Change, a11y, NPM Resource Changed, bug, PR-5.1-dev, Dark Mode

#43007 [5.1] The item can be null in FieldsHelper
  administrator/components/com_fields/src/Helper/FieldsHelper.php
Labels: RTC, PR-5.1-dev

#43090 [5.1] Updates the dependencies
  composer.json
  composer.lock
  libraries/src/Form/Rule/EmailRule.php
  package-lock.json
  package.json
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.1-dev

#43095 [5.1] Update deleted files list in script.php for 5.1.0-rc1
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#43092 [4.x] Update punycode library to include security fix
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-4.4-dev

#43020 CMSObject should extend stdClass
  libraries/src/Object/CMSObject.php
Labels: PR-4.4-dev

#43102 [5.1] Alert links system container
  build/media_source/templates/administrator/atum/scss/blocks/_alerts.scss
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43055 [4.x] Add support for brotli
  htaccess.txt
Labels: RTC, PR-4.4-dev

#43111 [5.1] fix alpha sorting in PR 42221
  administrator/language/en-GB/mod_user.ini
Labels: Language Change, PR-5.1-dev

#38797 Allow to use filter.state for delete button in ListView
  libraries/src/MVC/View/ListView.php
Labels: RTC, bug, Small, PR-4.4-dev

#43115 [5.1] add missing Header in guidedtours.joomla_welcome
  administrator/language/en-GB/guidedtours.joomla_welcome.ini
  administrator/language/en-GB/guidedtours.joomla_welcome_steps.ini
Labels: RTC, Language Change, PR-5.1-dev

#43119 [5.2] Router: Check directly for RouterInterface
  libraries/src/Router/SiteRouter.php
Labels: bug, PR-5.2-dev

#43120 [5.1] Guided Tours button
  administrator/components/com_guidedtours/tmpl/tours/default.php
Labels: RTC, PR-5.1-dev

#43117 Add missing variable to light theme
  build/media_source/templates/administrator/atum/scss/_variables.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43146 [5.1] Move buttons in Extension Manager to dropdown
  administrator/components/com_installer/src/View/Manage/HtmlView.php
Labels: RTC, PR-5.1-dev

#43125 [5.1]Add focus to treeselect [a11y]
  build/media_source/system/js/treeselectmenu.es6.js
Labels: RTC, a11y, NPM Resource Changed, PR-5.1-dev

#43140 [4.4] User profile edit: No notice when no active menu item
  components/com_users/src/View/Profile/HtmlView.php
Labels: RTC, bug, PR-4.4-dev

#43160 [5.1] Dark Mode menu select toggle colour
  build/media_source/templates/administrator/atum/scss/blocks/_treeselect.scss
Labels: RTC, a11y, NPM Resource Changed, PR-5.1-dev, Dark Mode

#43138 [5.1] pixel shift from dark to light
  build/media_source/templates/administrator/atum/scss/blocks/_header.scss
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43139 [5.1] GuidedTours: No error when joomla-welcome is missing
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: RTC, bug, PR-5.1-dev

#43122 [5.1] Alpha sorting strings in plg_system_jooa11y.ini
  administrator/language/en-GB/plg_system_jooa11y.ini
Labels: RTC, Language Change, PR-5.1-dev

#43116 [5.1] menu icon js fix [a11y]
  build/media_source/mod_menu/js/menu.es6.js
Labels: RTC, NPM Resource Changed, PR-5.1-dev

#43093 [5.1] Finder: Allow finder plugins to output spaces
  administrator/components/com_finder/src/Controller/IndexerController.php
Labels: RTC, bug, PR-5.1-dev

#43080 [5.1] Fix error in media field, add missing dependency in media-select field
  build/media_source/system/joomla.asset.json
Labels: RTC, NPM Resource Changed, bug, PR-5.1-dev

#42936 [5.1] Add exceptions to deleted files check for JS files to be kept on update
  build/deleted_file_check.php
Labels: PR-5.1-dev

#42865 [5][plugin] emailcloack Deprecated: mb_strpos()
  plugins/content/emailcloak/src/Extension/EmailCloak.php
Labels: RTC, PHP 8.x, PR-5.1-dev

#43166 Guided tours welcome performance
  administrator/components/com_guidedtours/src/Model/TourModel.php
  plugins/system/guidedtours/src/Extension/GuidedTours.php
Labels: PR-5.1-dev

#43073 [5.1] phan: fixes plugins
  .phan/config.php
  administrator/components/com_fields/src/Plugin/FieldsListPlugin.php
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  libraries/src/Changelog/Changelog.php
  libraries/src/Image/Image.php
  libraries/src/Image/ImageFilter.php
  libraries/src/Updater/Update.php
  libraries/src/Updater/UpdateAdapter.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/behaviour/compat/src/Extension/Compat.php
  plugins/editors/codemirror/layouts/editors/codemirror/codemirror.php
  plugins/fields/calendar/src/Extension/Calendar.php
  plugins/fields/color/src/Extension/Color.php
  plugins/fields/editor/src/Extension/Editor.php
  plugins/fields/imagelist/src/Extension/Imagelist.php
  plugins/fields/list/src/Extension/ListPlugin.php
  plugins/fields/media/src/Extension/Media.php
  plugins/fields/sql/src/Extension/SQL.php
  plugins/fields/subform/src/Extension/Subform.php
  plugins/fields/url/src/Extension/Url.php
  plugins/fields/user/src/Extension/User.php
  plugins/installer/packageinstaller/tmpl/default.php
  plugins/installer/urlinstaller/tmpl/default.php
  plugins/multifactorauth/webauthn/src/Helper/Credentials.php
  plugins/privacy/consents/src/Extension/Consents.php
  plugins/privacy/contact/src/Extension/Contact.php
  plugins/privacy/content/src/Extension/Content.php
  plugins/privacy/message/src/Extension/Message.php
  plugins/system/actionlogs/src/Extension/ActionLogs.php
  plugins/system/fields/src/Extension/Fields.php
  plugins/system/webauthn/src/Authentication.php
  plugins/webservices/users/src/Extension/Users.php
Labels: PR-5.1-dev

#43147 [5.1] Merge update parameter and improve contrain checker
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php
  administrator/language/en-GB/com_joomlaupdate.ini
  libraries/src/Updater/Adapter/TufAdapter.php
  libraries/src/Updater/ConstraintChecker.php
  libraries/src/Updater/Update.php
Labels: RTC, Language Change, PR-5.1-dev

#43162 [5.1] media punycode folder
  build/build-modules-js/settings.json
Labels: PR-5.1-dev

#42960 [5.1] Change item type to stdClass
  administrator/components/com_banners/src/View/Client/HtmlView.php
  administrator/components/com_fields/src/View/Field/HtmlView.php
  administrator/components/com_fields/src/View/Group/HtmlView.php
  administrator/components/com_finder/src/View/Filter/HtmlView.php
  administrator/components/com_guidedtours/src/View/Step/HtmlView.php
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_menus/src/View/Item/HtmlView.php
  administrator/components/com_newsfeeds/src/View/Newsfeeds/HtmlView.php
  administrator/components/com_plugins/src/View/Plugin/HtmlView.php
  administrator/components/com_privacy/src/View/Request/HtmlView.php
  administrator/components/com_templates/src/View/Style/HtmlView.php
  administrator/components/com_templates/src/View/Style/JsonView.php
  administrator/components/com_users/src/Model/DebuggroupModel.php
  components/com_contact/src/Model/ContactModel.php
  components/com_contact/src/View/Contact/HtmlView.php
  components/com_contact/src/View/Contact/VcfView.php
  components/com_contact/src/View/Featured/HtmlView.php
  components/com_tags/src/Model/TagModel.php
  components/com_tags/src/View/Tag/HtmlView.php
Labels: RTC, PR-5.1-dev

#43172 5.1/upmerges/2024 03 28
  components/com_users/src/View/Profile/HtmlView.php
  htaccess.txt
  libraries/src/MVC/View/ListView.php
Labels: PR-5.1-dev

#43145 [4.4] add PHP8.3 to PhpVersionCheck quickicon
  plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php
Labels: PR-4.4-dev

#43168 [5.1] Update deleted files list in script.php for 5.1.0-rc1 (2)
  administrator/components/com_admin/script.php
Labels: PR-5.1-dev

#43175 [5.1] Fix SQL syntax error when updating to 5.1 on PostgreSQL
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-03-08.sql
Labels: RTC, Release Blocker, bug, PR-5.1-dev

#43171 [5.1] brotli compression
  administrator/components/com_admin/postinstall/htaccessbrotli.php
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-03-28.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-03-28.sql
  administrator/language/en-GB/com_admin.ini
Labels: RTC, Language Change, PR-5.1-dev

#43169 [5.1] Fix SQL error 1242 "Subquery returns more than 1 row" on update when having multiple update sites for the core (2)
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-02-24.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-02-24.sql
Labels: Release Blocker, bug, PR-5.1-dev

#41967 [5.1] Senseless proxy methods
  administrator/components/com_tags/src/Controller/TagController.php
  libraries/src/Component/Exception/MissingComponentException.php
  libraries/src/Toolbar/Button/DropdownButton.php
Labels: bug, PR-5.1-dev

#43135 [5.1] Cog icon focus [a11y]
  build/media_source/templates/administrator/atum/scss/pages/_com_cpanel.scss
Labels: RTC, a11y, NPM Resource Changed, PR-5.1-dev
