Repository joomla/joomla-cms, pull requests merged in 2024-04, with the labels that each got.

#43176 [5.1] tinymce hardening fix
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: RTC, PR-5.1-dev

#43187 [5.1] Delete 4.4.4-2024-03-28.sql update SQL scripts and update deleted files list in script.php
  administrator/components/com_admin/script.php
  administrator/components/com_admin/sql/updates/mysql/4.4.4-2024-03-28.sql
  administrator/components/com_admin/sql/updates/postgresql/4.4.4-2024-03-28.sql
Labels: PR-5.1-dev

#43182 [5.1] Fix duplicate Brotli .htaccess postinstall message after update from 4.4
  administrator/components/com_admin/postinstall/htaccessbrotli.php
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-03-28.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-03-28.sql
Labels: RTC, bug, PR-5.1-dev

#43190 [5.1] Use update channel the correct way
  libraries/src/TUF/DatabaseStorage.php
  libraries/src/TUF/HttpLoader.php
  libraries/src/TUF/TufFetcher.php
  libraries/src/Updater/Adapter/TufAdapter.php
  libraries/src/Updater/ConstraintChecker.php
  tests/Unit/Libraries/Cms/Updater/ConstraintCheckerTest.php
Labels: Unit/System Tests, PR-5.1-dev

#42884 [6.0] Remove deprecated BaseApplication and CLI classes
  libraries/src/Application/BaseApplication.php
  libraries/src/Application/CLI/CliInput.php
  libraries/src/Application/CLI/CliOutput.php
  libraries/src/Application/CLI/ColorStyle.php
  libraries/src/Application/CLI/Output/Processor/ColorProcessor.php
  libraries/src/Application/CLI/Output/Processor/ProcessorInterface.php
  libraries/src/Application/CLI/Output/Stdout.php
  libraries/src/Application/CLI/Output/Xml.php
  libraries/src/Application/CliApplication.php
  plugins/behaviour/compat/src/classmap/classmap.php
Labels: b/c break, PR-6.0-dev

#42890 [6.0] Removing CMS Input package
  installation/src/Service/Provider/Application.php
  libraries/src/Input/Cli.php
  libraries/src/Input/Cookie.php
  libraries/src/Input/Files.php
  libraries/src/Input/Input.php
  libraries/src/Input/Json.php
  libraries/src/Service/Provider/Application.php
  libraries/src/Service/Provider/Input.php
  libraries/src/Service/Provider/Session.php
Labels: b/c break, PR-6.0-dev

#42587 Fix phpdoc in FeatureEvent
  administrator/components/com_content/src/Event/Model/FeatureEvent.php
Labels: RTC, bug, PR-4.4-dev

#43180 [4.4] Postinstallation-Message htaccess.txt brotli change (#43173) - strings sorted alphabetically
  administrator/language/en-GB/com_admin.ini
Labels: RTC, Language Change, PR-4.4-dev

#43191 [4.4] Mfa: Setting timezone for dates in profile
  administrator/components/com_users/src/Model/MethodsModel.php
Labels: RTC

#43207 [5.1] Fix the build tools
  build/build-modules-js/css-versioning.es6.js
Labels: PR-5.1-dev

#43225 [5.1] Upmerges - 2024-04-06
  administrator/components/com_content/src/Event/Model/FeatureEvent.php
  administrator/components/com_users/src/Model/MethodsModel.php
Labels: Test instructions missing, PR-5.1-dev

#43137 [5.1] collapsed sidebar menu [a11y]
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/blocks/_sidebar.scss
Labels: RTC, a11y, NPM Resource Changed, PR-5.1-dev

#43195 [5.1] SEF: Change value for trailingslash option
  plugins/system/sef/sef.xml
  plugins/system/sef/src/Extension/Sef.php
Labels: PR-5.1-dev

#43238 [6.0] Drone: Switching to key authentication for artifacts
  .drone.yml
Labels: Unit/System Tests, PR-6.0-dev

#43236 [4.4] Drone: Switching to key authentication for artifacts
  .drone.yml
Labels: Unit/System Tests, PR-4.4-dev

#43237 [5.2] Drone: Switching to key authentication for artifacts
  .drone.yml
Labels: Unit/System Tests, PR-5.2-dev

#42891 [5.1] Complete com_search deprecation #40727
  administrator/language/en-GB/localise.php
Labels: RTC, Language Change, PR-5.1-dev

#43246 form object
  administrator/components/com_categories/src/Field/CategoryeditField.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_config/src/Model/ComponentModel.php
  administrator/components/com_fields/src/Field/SectionField.php
  administrator/components/com_fields/src/Field/SubfieldsField.php
  administrator/components/com_fields/src/Field/TypeField.php
  administrator/components/com_guidedtours/src/Model/StepModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_mails/src/Model/TemplateModel.php
  administrator/components/com_menus/src/Field/MenuItemByTypeField.php
  administrator/components/com_menus/src/Field/Modal/MenuField.php
  administrator/components/com_redirect/src/Model/LinkModel.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  components/com_config/src/Model/ConfigModel.php
  components/com_config/src/Model/TemplatesModel.php
  plugins/content/confirmconsent/src/Field/ConsentBoxField.php
  plugins/editors/tinymce/src/Field/TemplateslistField.php
  plugins/editors/tinymce/src/Field/UploaddirsField.php
Labels: PR-5.1-dev

#43123 [5.1] language code rich snippet revert
  components/com_content/tmpl/article/default.php
Labels: PR-5.0-dev, PR-5.1-dev

#43297 [5.2] Upmerge 2024-04-18
  installation/language/el-GR/joomla.ini
  installation/language/it-IT/joomla.ini
  installation/language/sv-SE/joomla.ini
  libraries/src/Version.php
Labels: Language Change, PR-5.2-dev

#43304 [5.2] Deprecate WebApplication::$JComponentTitle
  administrator/modules/mod_title/src/Dispatcher/Dispatcher.php
  libraries/src/Application/WebApplication.php
  libraries/src/Toolbar/ToolbarHelper.php
Labels: RTC, PR-5.2-dev

#43232 [5.2] Languagefilter: Add message when no content language is published
  administrator/language/en-GB/plg_system_languagefilter.ini
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: RTC, Language Change, PR-5.2-dev

#43310 [5.1] DarkMode selector
  administrator/components/com_admin/sql/updates/mysql/5.1.1-2024-04-18.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.1-2024-04-18.sql
Labels: RTC, bug, PR-5.1-dev

#43284 [5.1] Update ConstraintChecker.php typo/spelling
  libraries/src/Updater/ConstraintChecker.php
Labels: RTC, PR-5.1-dev

#43249 [5.x] String sentence
  administrator/language/en-GB/lib_joomla.ini
Labels: RTC, Language Change, PR-5.1-dev

#43341 [5.2] Add script to update titles on github
  build/github_update_title.php
Labels: PR-5.2-dev

#43363 [5.2] Fix CS
  build/github_rebase.php
  build/github_update_title.php
Labels: PR-5.2-dev

#43336 [4.4] [bug] Media manager misbehaves on files with capitalized extensions
  build/media_source/com_media/js/edit-images.es6.js
  build/media_source/plg_media-action_crop/js/crop.es6.js
  build/media_source/plg_media-action_resize/js/resize.es6.js
  build/media_source/plg_media-action_rotate/js/rotate.es6.js
  libraries/src/Helper/MediaHelper.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: RTC, NPM Resource Changed, PR-4.4-dev

#43208 [4.4] Untranslated string for warning message in update:extensions:check CLI
  libraries/src/Console/CheckUpdatesCommand.php
  libraries/src/Updater/UpdateAdapter.php
Labels: RTC, bug, PR-4.4-dev

#43274 [4.4] plugins\filesystem\local\src\Adapter\LocalAdapter.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: RTC, bug, PR-4.4-dev

#43192 [4.4] Adminmenu: Toggle for duplicate menus
  build/media_source/mod_menu/js/admin-menu.es6.js
Labels: RTC, NPM Resource Changed, bug, PR-4.4-dev

#43178 [4.4] Adminmenu: Fix export for child items
  administrator/components/com_menus/src/View/Menu/XmlView.php
Labels: RTC, bug, PR-4.4-dev

#43189 [4.4] Backendmenu: Fixing import of presets for menu items (ajaxbadge, ...)
  administrator/components/com_menus/src/Helper/MenusHelper.php
Labels: RTC, bug, PR-4.4-dev

#42934 [4.4] Vote : aggregateRating error in Google Rich Results
  plugins/content/vote/tmpl/rating.php
Labels: RTC, bug, PR-4.4-dev

#43400 Fix System test com_privacy consent (#42523)
  tests/System/integration/administrator/components/com_privacy/Consent.cy.js
Labels: RTC, Unit/System Tests, PR-4.4-dev

#42861 [5.2] Fix of unnecessary SQL query for Fields, get the field value already loaded by getFields()
  administrator/components/com_fields/src/Helper/FieldsHelper.php
Labels: RTC, bug, PR-5.2-dev

#43273 [5.2] json encoded in bind method
  administrator/components/com_contact/src/Table/ContactTable.php
  administrator/components/com_scheduler/src/Table/TaskTable.php
  libraries/src/Table/CoreContent.php
  libraries/src/Table/Extension.php
  libraries/src/Table/Update.php
Labels: Feature, RTC, PR-5.1-dev, PR-5.2-dev

#43378 [5.2] Clarify Cache Plugin
  administrator/language/en-GB/plg_system_cache.ini
  administrator/language/en-GB/plg_system_cache.sys.ini
Labels: RTC, Language Change, PR-5.2-dev

#43216 [5.2] Admin Module Latest
  administrator/language/en-GB/mod_latest.ini
  administrator/modules/mod_latest/src/Helper/LatestHelper.php
  administrator/modules/mod_latest/tmpl/default.php
Labels: Feature, RTC, Language Change, PR-5.2-dev

#43282 [5.2] Compress the thumbnails
  libraries/src/Image/Image.php
Labels: Feature, RTC, PR-5.1-dev, PR-5.2-dev

#42509 [5.2] replace scss variables by css variables
  build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_buttons.scss
Labels: Feature, RTC, NPM Resource Changed, PR-5.2-dev

#43260 [5.2] Added link class selection to TinyMCE dialog
  administrator/language/en-GB/plg_editors_tinymce.ini
  plugins/editors/tinymce/forms/setoptions.xml
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
Labels: Feature, RTC, Language Change, PR-5.2-dev

#42933 [5.2] Vote : add aggregateRating in article's schemaorg information
  plugins/content/vote/src/Extension/Vote.php
  plugins/content/vote/tmpl/rating.php
Labels: Feature, RTC, PR-5.2-dev
