Repository joomla/joomla-cms, pull requests merged in 2025-08, with the labels that each got.

#45747 [5.3] Debug plugin Collector
  plugins/system/debug/src/Extension/Debug.php
Labels: RTC, bug, PR-5.3-dev

#45646 Serve correct 404 status for URLs with invalid controller name
  libraries/src/Dispatcher/ComponentDispatcher.php
Labels: RTC, PR-5.3-dev

#45814 [5.4] Move PHPstan deprecated database interface errors from baseline to main config
  phpstan-baseline.neon
  phpstan.neon
Labels: RTC, PR-5.4-dev

#45761 [5.4] Add checkedout filter to the Article Manager
  administrator/components/com_content/forms/filter_articles.xml
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/language/en-GB/com_content.ini
  api/components/com_content/src/Controller/ArticlesController.php
  components/com_content/src/Model/ArticlesModel.php
Labels: Feature, RTC, Language Change, Documentation Required, PR-5.4-dev

#45832 [5.4] Update deleted files in script.php for the upcoming 5.4.0-beta1
  administrator/components/com_admin/script.php
Labels: PR-5.4-dev

#45834 [6.0] remove deprecated string - redo #45565
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-6.0-dev

#45825 [5.4] HTTP: Remove legacy code for Response calls
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_installer/src/Model/LanguagesModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  libraries/src/Changelog/Changelog.php
  libraries/src/Feed/FeedFactory.php
  libraries/src/Http/Transport/CurlTransport.php
  libraries/src/Http/Transport/SocketTransport.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/TUF/HttpLoader.php
  libraries/src/Updater/Adapter/CollectionAdapter.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  libraries/src/Updater/Update.php
  libraries/src/Updater/UpdateAdapter.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/system/stats/src/Extension/Stats.php
  plugins/task/requests/src/Extension/Requests.php
  tests/Unit/Libraries/Tuf/HttpLoaderTest.php
  tests/Unit/Plugin/Task/Requests/Extension/RequestsPluginTest.php
Labels: RTC, Unit/System Tests, PR-5.4-dev

#45778 [5.4] limitstart php deprecation
  administrator/components/com_installer/src/Model/InstallerModel.php
Labels: RTC, PR-5.4-dev

#45845 [5.4] upmerge 2025-08-05
  build/media_source/templates/administrator/atum/scss/_variables-dark.scss
  build/media_source/templates/administrator/atum/scss/_variables.scss
  build/media_source/templates/administrator/atum/scss/vendor/bootstrap/_buttons.scss
  libraries/src/Dispatcher/ComponentDispatcher.php
  libraries/src/Versioning/VersionableModelTrait.php
  libraries/src/Versioning/Versioning.php
  plugins/system/debug/src/Extension/Debug.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
  tests/System/integration/site/components/com_config/Templates.cy.js
Labels: Unit/System Tests, NPM Resource Changed, PR-5.4-dev

#45828 [6.0] Version in Language string
  language/en-GB/files_joomla.sys.ini
Labels: RTC, Language Change, PR-6.0-dev

#45802 [6.0] Notification email on admin registration approval
  administrator/components/com_users/src/Controller/UserController.php
  administrator/components/com_users/src/Model/UserModel.php
  administrator/components/com_users/src/View/User/HtmlView.php
  administrator/components/com_users/tmpl/user/edit.php
  administrator/language/en-GB/com_users.ini
  build/media_source/com_users/joomla.asset.json
  build/media_source/com_users/js/activate-user-send-email.es6.js
  language/en-GB/com_users.ini
Labels: RTC, Language Change, NPM Resource Changed, PR-6.0-dev

#45786 [6.0] Cassiopeia - Add view-transition for pages
  build/media_source/templates/site/cassiopeia/scss/blocks/_global.scss
Labels: RTC, NPM Resource Changed, PR-6.0-dev

#45787 [6.0] Atum - add view-transition for pages in administrator
  build/media_source/templates/administrator/atum/scss/blocks/_global.scss
Labels: RTC, NPM Resource Changed, PR-6.0-dev

#45794 [6.0] Atum - add nice transition to open/close details
  build/media_source/templates/administrator/atum/scss/blocks/_global.scss
Labels: RTC, NPM Resource Changed, PR-6.0-dev

#45821 [5.4] Fix unlocked and possibly uninstalled core plugins for new installs and updates
  administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-07-25.sql
  administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-08-26.sql
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2023-11-28.sql
  administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-02-25.sql
  administrator/components/com_admin/sql/updates/mysql/5.4.0-2025-08-02.sql
  administrator/components/com_admin/sql/updates/postgresql/5.0.0-2023-07-25.sql
  administrator/components/com_admin/sql/updates/postgresql/5.0.0-2023-08-26.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2023-11-28.sql
  administrator/components/com_admin/sql/updates/postgresql/5.1.0-2024-02-25.sql
  administrator/components/com_admin/sql/updates/postgresql/5.4.0-2025-08-02.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, bug, PR-5.4-dev

#45842 [5.3] Choices force background
  build/media_source/templates/administrator/atum/scss/vendor/choicesjs/choices.scss
Labels: RTC, NPM Resource Changed, bug, PR-5.3-dev

#45865 [6.0] Remove old php versions from from windows workflow tests
  .github/workflows/ci.yml
Labels: PR-6.0-dev

#45852 [5.4] Convert administrator mod_submenu to service provider
  administrator/modules/mod_submenu/mod_submenu.php
  administrator/modules/mod_submenu/mod_submenu.xml
  administrator/modules/mod_submenu/services/provider.php
  administrator/modules/mod_submenu/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_submenu/src/Menu/Menu.php
Labels: RTC, PR-5.4-dev

#45863 [6.x] template assets
  administrator/templates/atum/joomla.asset.json
  templates/cassiopeia/joomla.asset.json
Labels: RTC, PR-6.0-dev

#45695 [5.4] Deprecate app property in FieldsPlugin
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  phpstan-baseline.neon
Labels: RTC, PR-5.4-dev

#45878 [5.4] Extend deprecation of JLoader::register() from 6.0 to 7.0
  libraries/loader.php
  phpstan-baseline.neon
Labels: Documentation Required, PR-5.4-dev

#45855 [6.0] fix invalid json in mysql install
  installation/sql/mysql/base.sql
Labels: RTC, PR-6.0-dev

#45822 [6.0] Fix unlocked and possibly uninstalled core plugins for updates
  administrator/components/com_admin/sql/updates/mysql/6.0.0-2025-08-02.sql
  administrator/components/com_admin/sql/updates/postgresql/6.0.0-2025-08-02.sql
Labels: RTC, bug, PR-6.0-dev

#45893 [5.4] Update deleted files in script.php for the upcoming 5.4.0-beta1 (2)
  administrator/components/com_admin/script.php
Labels: PR-5.4-dev

#45890 [5.4] Use database from container and fix menuType table instantiation
  administrator/modules/mod_menu/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_menu/src/Menu/CssMenu.php
Labels: RTC, Release Blocker, bug, PR-5.4-dev

#45426 [6.0] Restore onBeforeExecute event for CMSApplication
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/SiteApplication.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: Feature, RTC, PR-6.0-dev

#45827 [6.0] Updating dependencies
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_installer/src/Model/LanguagesModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  composer.json
  composer.lock
  libraries/src/Captcha/Google/HttpBridgePostRequestMethod.php
  libraries/src/Changelog/Changelog.php
  libraries/src/Event/AbstractImmutableEvent.php
  libraries/src/Feed/FeedFactory.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/Updater/Adapter/TufAdapter.php
  libraries/src/Updater/Update.php
  libraries/src/Updater/UpdateAdapter.php
  phpstan.neon
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/system/stats/src/Extension/Stats.php
  tests/Unit/Plugin/Authentication/Ldap/LdapPluginTest.php
Labels: Unit/System Tests, Composer Dependency Changed, PR-6.0-dev

#45900 [5.4] Autoupdates - Improve download logging
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-5.4-dev

#45697 [5.4] Allow opt-out from automated updates during installation
  installation/language/en-GB/joomla.ini
  installation/src/Controller/InstallationController.php
  installation/src/Model/AutomatedUpdatesModel.php
  installation/template/index.php
  installation/template/js/remove.js
  installation/tmpl/remove/default.php
Labels: Feature, RTC, Language Change, PR-5.4-dev

#44590 [6.0] Allow adding additional layout base path to form fields
  libraries/src/Form/FormField.php
Labels: RTC, PR-6.0-dev

#45910 [6.0] Add the js-grid-item-is-checked class and remove onClick HtmlHelper Grid
  libraries/src/HTML/Helpers/Grid.php
Labels: RTC, PR-6.0-dev

#45004 [6.0] Field simple color as web component
  administrator/language/en-GB/joomla.ini
  api/language/en-GB/joomla.ini
  build/media_source/system/js/fields/joomla-field-simple-color.w-c.es6.js
  build/media_source/system/scss/fields/joomla-field-simple-color.scss
  language/en-GB/joomla.ini
  layouts/joomla/form/field/color/simple.php
Labels: Feature, RTC, Language Change, NPM Resource Changed, PR-6.0-dev, Enhancement

#45250 [6.0] Removing defs of JPATH_COMPONENT* from installation app
  installation/src/Application/CliInstallationApplication.php
  installation/src/Application/InstallationApplication.php
Labels: RTC, PR-6.0-dev

#44381 [6.0] Fulfill InstallerScriptInterface with a trait
  libraries/src/Installer/InstallerAdapter.php
  libraries/src/Installer/InstallerScriptTrait.php
Labels: Feature, PR-6.0-dev

#45233 [6.0] Note Custom Field Plugin
  administrator/components/com_admin/sql/updates/mysql/6.0.0-2025-08-16.sql
  administrator/components/com_admin/sql/updates/postgresql/6.0.0-2025-08-16.sql
  administrator/language/en-GB/plg_fields_note.ini
  administrator/language/en-GB/plg_fields_note.sys.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  plugins/fields/note/note.xml
  plugins/fields/note/params/note.xml
  plugins/fields/note/services/provider.php
  plugins/fields/note/src/Extension/Note.php
  plugins/fields/note/tmpl/note.php
Labels: Feature, RTC, Language Change, PR-6.0-dev

#45922 [6.0] Refactor default frontend menu to fix submenu support and improve accessiblity
  build/media_source/mod_menu/css/mod-menu.css
  build/media_source/mod_menu/joomla.asset.json
  build/media_source/mod_menu/js/menu.es6.js
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  language/en-GB/mod_menu.ini
  modules/mod_menu/tmpl/default.php
  modules/mod_menu/tmpl/default_component.php
  modules/mod_menu/tmpl/default_heading.php
  modules/mod_menu/tmpl/default_separator.php
  modules/mod_menu/tmpl/default_url.php
Labels: Language Change, NPM Resource Changed, PR-6.0-dev

#43974 [6.0] Numbers custom fields plugin
  administrator/components/com_admin/sql/updates/mysql/6.0.0-2025-08-17.sql
  administrator/components/com_admin/sql/updates/postgresql/6.0.0-2025-08-17.sql
  administrator/language/en-GB/plg_fields_number.ini
  administrator/language/en-GB/plg_fields_number.sys.ini
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  plugins/fields/number/number.xml
  plugins/fields/number/params/number.xml
  plugins/fields/number/services/provider.php
  plugins/fields/number/src/Extension/Number.php
  plugins/fields/number/tmpl/number.php
Labels: Feature, RTC, Language Change, PR-6.0-dev

#45928 [6.0] Update deleted files and folders in script.php for the upcoming 6.0.0-beta1 (2nd PR)
  administrator/components/com_admin/script.php
Labels: PR-6.0-dev

#45923 [6.0] Disable new advanced colors and fonts settings in Cassiopeia
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, PR-6.0-dev

#45515 [6.0] Extend versioning, save releated information in history table and restore historical data
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_banners/src/Model/ClientModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_contenthistory/src/Helper/ContenthistoryHelper.php
  administrator/components/com_contenthistory/tmpl/compare/compare.php
  administrator/components/com_contenthistory/tmpl/preview/preview.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_tags/src/Model/TagModel.php
  administrator/components/com_users/src/Model/NoteModel.php
  administrator/language/en-GB/joomla.ini
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Versioning/VersionableControllerTrait.php
  libraries/src/Versioning/VersionableModelInterface.php
  libraries/src/Versioning/VersionableModelTrait.php
  plugins/behaviour/versionable/src/Extension/Versionable.php
Labels: Feature, Language Change, b/c break, PR-6.0-dev

#45927 [6.0] Actualize Sample Data
  administrator/language/en-GB/plg_sampledata_blog.ini
Labels: RTC, Language Change, PR-6.0-dev

#45918 [5.3] Language string frontend
  administrator/language/en-GB/com_config.ini
Labels: RTC, Language Change, PR-5.3-dev

#45719 [6.0] Add Support for Github Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/post-create.sh
  .devcontainer/xdebug.ini
Labels: PR-6.0-dev

#45883 [5.3] contributing.md
  .github/CONTRIBUTING.md
Labels: RTC, PR-5.3-dev

#45347 [5.4] Optimize smart search module
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_finder/src/Indexer/Taxonomy.php
Labels: RTC, PR-5.4-dev

#42162 [5.3] Update tag router to restrict lossy matches to menu items set to any
  components/com_tags/src/Service/Router.php
Labels: RTC, bug, PR-5.3-dev

#44221 [5.3] Fixing Cassiopeia mobile menu collapse bug #44140
  build/media_source/templates/site/cassiopeia/js/mod_menu/menu-metismenu.es6.js
Labels: RTC, NPM Resource Changed, PBF, bug, PR-5.3-dev

#45597 [5.3] Restored Article Version Now Properly Checked Out to Current User
  libraries/src/Versioning/VersionableModelTrait.php
Labels: RTC, bug, PR-5.3-dev

#45176 [5.3] undefined array key in table\nested.php
  libraries/src/Table/Nested.php
Labels: RTC, PBF, bug, PR-5.3-dev

#45696 [5.4] Implement autoupdate plugin events
  administrator/components/com_joomlaupdate/src/Model/NotificationModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/language/en-GB/com_joomlaupdate.ini
  api/components/com_joomlaupdate/src/Controller/NotificationController.php
  api/components/com_joomlaupdate/src/View/Notification/JsonapiView.php
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/Extension/BeforeJoomlaAutoupdateEvent.php
Labels: Feature, RTC, Language Change, PR-5.4-dev

#45419 [5.3] Set http status header for XML/feed responses
  libraries/src/Error/Renderer/XmlRenderer.php
Labels: RTC, PBF, bug, PR-5.3-dev

#39835 [5.3] Shortening the code for 'No Media found' in Media Manager
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
Labels: RTC, NPM Resource Changed, PBF, bug, Small, PR-5.3-dev

#45980 [5.4] Convert TUF update info URL into legacy format
  libraries/src/Updater/Update.php
Labels: RTC, bug, PR-5.4-dev

#45973 [5.4] Don't insert duplicate records in update SQL scripts when they are executed multiple times
  administrator/components/com_admin/sql/updates/mysql/5.4.0-2025-04-23.sql
  administrator/components/com_admin/sql/updates/mysql/5.4.0-2025-05-10.sql
  administrator/components/com_admin/sql/updates/postgresql/5.4.0-2025-04-23.sql
  administrator/components/com_admin/sql/updates/postgresql/5.4.0-2025-05-10.sql
Labels: bug, PR-5.4-dev

#45984 [5.3] Security updates for composer and npm dependencies for the upcoming 5.3.4 release
  composer.json
  composer.lock
  package-lock.json
Labels: Composer Dependency Changed, NPM Resource Changed, bug, PR-5.3-dev

#45940 [5.4] Revert b/c breaking change in AbstractView::get
  administrator/components/com_menus/layouts/joomla/menu/edit_modules.php
  components/com_contact/src/View/Categories/HtmlView.php
  components/com_content/src/View/Categories/HtmlView.php
  components/com_newsfeeds/src/View/Categories/HtmlView.php
  layouts/joomla/content/categories_default.php
  layouts/joomla/content/category_default.php
  layouts/joomla/edit/admin_modules.php
  layouts/joomla/edit/fieldset.php
  layouts/joomla/edit/global.php
  layouts/joomla/edit/params.php
  layouts/joomla/edit/publishingdata.php
  libraries/src/MVC/View/CategoryView.php
Labels: RTC, bug, PR-5.4-dev

#45986 [5.3] Update joomla/filesystem to fix extension uploads when post_max_size is 0
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, bug, PR-5.3-dev

#45999 [5.4] Update composer dependency joomla/filesystem to 3.2.0
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.4-dev

#45721 [5.4] Autoupdate email groups
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_joomlaupdate/src/Model/NotificationModel.php
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: Feature, RTC, Language Change, PR-5.4-dev

#46008 [5.4] Remove duplicate string
  plugins/editors-xtd/image/src/Extension/Image.php
Labels: bug, PR-5.4-dev

#46003 [5.4] Start/End Featured
  administrator/components/com_content/forms/article.xml
Labels: RTC, bug, PR-5.4-dev

#45947 [6.0] Fix incorrect language tag comparison
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
  plugins/system/sef/src/Extension/Sef.php
Labels: RTC, PBF, bug, PR-6.0-dev

#45930 [6.0] Add CSS to Cassiopeia for the refactored mod_menu
  build/media_source/templates/site/cassiopeia/scss/blocks/_header.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_modifiers.scss
Labels: RTC, NPM Resource Changed, bug, PR-6.0-dev

#45925 [6.0] No htmlhelper for js
  administrator/components/com_modules/tmpl/module/edit.php
  administrator/components/com_templates/tmpl/template/default.php
  components/com_config/tmpl/modules/default.php
  layouts/joomla/form/field/combo.php
  libraries/src/HTML/Helpers/Grid.php
  libraries/src/Language/Text.php
Labels: RTC, PBF, bug, PR-6.0-dev

#46016 [6.0] Upmerges - 2025-08-31
  administrator/components/com_content/forms/article.xml
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_joomlaupdate/src/Model/NotificationModel.php
  administrator/language/en-GB/com_config.ini
  administrator/language/en-GB/com_joomlaupdate.ini
  build/media_source/com_associations/js/associations-edit.es6.js
  libraries/src/Versioning/VersionableModelTrait.php
  plugins/editors-xtd/image/src/Extension/Image.php
Labels: Test instructions missing, Language Change, NPM Resource Changed, PR-6.0-dev

#46019 [6.1] Preparation for Joomla! 6.1
  .github/CONTRIBUTING.md
  README.md
  README.txt
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  build.xml
  installation/language/en-GB/langmetadata.xml
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Application/WebApplication.php
  libraries/src/Event/Extension/BeforeJoomlaAutoupdateEvent.php
  libraries/src/Version.php
  package-lock.json
  package.json
Labels: Language Change, NPM Resource Changed, PR-6.1-dev
