Repository joomla/joomla-cms, pull requests merged in 2025-05, with the labels that each got.

#45410 [5.3] Jooa11y Plugin: Update embedded help URLs in language strings
  administrator/language/en-GB/plg_system_jooa11y.ini
Labels: RTC, Language Change, PR-5.3-dev

#45425 [6.0] Remove the item association property in the web application
  libraries/src/Application/WebApplication.php
Labels: RTC, b/c break, PR-6.0-dev

#45437 Fix deprecation text and add Registry to StateBehaviorTrait
  libraries/src/MVC/Model/State.php
  libraries/src/MVC/Model/StateBehaviorTrait.php
Labels: RTC

#45438 [5.4] Upmerge 2025-05-06
  administrator/language/en-GB/plg_system_jooa11y.ini
  cypress.config.dist.mjs
  tests/System/README.md
  tests/System/entrypoint.sh
  tests/System/plugins/index.mjs
  tests/System/plugins/logs.mjs
  tests/System/support/index.js
Labels: Unit/System Tests, Language Change, PR-5.4-dev

#45395 [5.3] sql postgresql valid json
  administrator/components/com_admin/sql/updates/postgresql/5.2.3-2025-01-09.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.1-2025-04-27.sql
Labels: RTC, bug, PR-5.3-dev

#45430 [6.0] Add aria-label + text to change language button during installation
  installation/language/en-GB/joomla.ini
  installation/tmpl/setup/default.php
Labels: RTC, Language Change, PR-6.0-dev

#45420 [5.3] Installer rtl logical css
  build/build-modules-js/stylesheets/handle-scss.mjs
  installation/template/scss/template-rtl.scss
  installation/template/scss/template.scss
  installation/tmpl/remove/default.php
  installation/tmpl/setup/default.php
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#45388 [5.3] Update the location when an update site exists
  plugins/extension/joomla/src/Extension/Joomla.php
Labels: RTC, bug, PR-5.3-dev

#45424 [5.3] Delete unused build tools file scss-transform.mjs
  build/build-modules-js/stylesheets/scss-transform.mjs
Labels: RTC, PR-5.3-dev

#45381 [5.3] - Action Log Email Notifications - use site timezone
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
Labels: RTC, PR-5.3-dev

#45464 [5.3] Smart Search: Extend lists of elements to space out
  administrator/components/com_finder/src/Indexer/Parser/Html.php
Labels: RTC, bug, PR-5.3-dev

#45445 [5.3] Limit length of searchterm logging to prevent MysqliStatement error
  components/com_finder/src/Helper/FinderHelper.php
Labels: RTC, PR-5.3-dev

#45373 [5.3] Do not display modified url in update check
  libraries/src/Updater/UpdateAdapter.php
Labels: RTC, PR-5.3-dev

#45457 [5.3] Composer update joomla/database to 3.4.2 to fix PHP 8.4 deprecation
  composer.lock
Labels: RTC, Composer Dependency Changed, PHP 8.x, bug, PR-5.3-dev

#45014 [5.3] Unpublish/Run transition article when saving as copy
  administrator/components/com_content/src/Model/ArticleModel.php
Labels: RTC, bug, PR-5.3-dev

#45471 [5.4] Upmerge 2025-05-13
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  administrator/components/com_admin/sql/updates/postgresql/5.2.3-2025-01-09.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.1-2025-04-27.sql
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_finder/src/Indexer/Parser/Html.php
  build/build-modules-js/stylesheets/handle-scss.mjs
  build/build-modules-js/stylesheets/scss-transform.mjs
  components/com_finder/src/Helper/FinderHelper.php
  composer.lock
  installation/template/scss/template-rtl.scss
  installation/template/scss/template.scss
  installation/tmpl/remove/default.php
  installation/tmpl/setup/default.php
  libraries/src/MVC/Model/State.php
  libraries/src/MVC/Model/StateBehaviorTrait.php
  libraries/src/Updater/UpdateAdapter.php
  plugins/extension/joomla/src/Extension/Joomla.php
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.4-dev

#45320 [5.3] Media manager UI bug fixes and Accessibility improvements
  administrator/components/com_media/resources/scripts/components/infobar/infobar.vue
  administrator/components/com_media/resources/scripts/components/tree/disk.vue
  build/media_source/com_media/scss/components/_layout.scss
  build/media_source/com_media/scss/components/_media-infobar.scss
  build/media_source/com_media/scss/components/_media-tree.scss
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#35184 [6.0] Modification fields header tag, module tag add custom options in XML
  libraries/src/Form/Field/HeadertagField.php
  libraries/src/Form/Field/ModuletagField.php
Labels: Feature, RTC, PR-6.0-dev

#44925 [6.0] Add removed Input classes to the compat plugin
  plugins/behaviour/compat/classes/Input/Cookie.php
  plugins/behaviour/compat/classes/Input/Files.php
  plugins/behaviour/compat/classes/Input/Input.php
  plugins/behaviour/compat/classes/Input/Json.php
  plugins/behaviour/compat/src/classmap/classmap.php
Labels: RTC, PR-6.0-dev

#45434 [6.0] Remove the static getLogContentTypeParams function
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
Labels: RTC, b/c break, PR-6.0-dev

#45435 [6.0] Exception not caught. No strings returned
  libraries/src/Language/LanguageHelper.php
Labels: RTC, PR-6.0-dev

#45336 [6.0] Introduce Joomla 6.0 compatibility plugin
  administrator/components/com_admin/script.php
  administrator/language/en-GB/plg_behaviour_compat.ini
  administrator/language/en-GB/plg_behaviour_compat.sys.ini
  administrator/language/en-GB/plg_behaviour_compat6.ini
  administrator/language/en-GB/plg_behaviour_compat6.sys.ini
  build/media_source/plg_behaviour_compat/es5.asset.json
  build/media_source/plg_behaviour_compat6/removed.asset.json
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/behaviour/compat/compat.xml
  plugins/behaviour/compat/services/provider.php
  plugins/behaviour/compat/src/Extension/Compat.php
  plugins/behaviour/compat6/classes/Application/BaseApplication.php
  plugins/behaviour/compat6/classes/Application/CLI/CliInput.php
  plugins/behaviour/compat6/classes/Application/CLI/CliOutput.php
  plugins/behaviour/compat6/classes/Application/CLI/ColorStyle.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Processor/ColorProcessor.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Processor/ProcessorInterface.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Stdout.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Xml.php
  plugins/behaviour/compat6/classes/Application/CliApplication.php
  plugins/behaviour/compat6/classes/Filesystem/File.php
  plugins/behaviour/compat6/classes/Filesystem/FilesystemHelper.php
  plugins/behaviour/compat6/classes/Filesystem/Folder.php
  plugins/behaviour/compat6/classes/Filesystem/Meta/language/en-GB/en-GB.lib_joomla_filesystem_patcher.ini
  plugins/behaviour/compat6/classes/Filesystem/Patcher.php
  plugins/behaviour/compat6/classes/Filesystem/Path.php
  plugins/behaviour/compat6/classes/Filesystem/Stream.php
  plugins/behaviour/compat6/classes/Filesystem/Streams/StreamString.php
  plugins/behaviour/compat6/classes/Filesystem/Support/StringController.php
  plugins/behaviour/compat6/classes/Input/Cookie.php
  plugins/behaviour/compat6/classes/Input/Files.php
  plugins/behaviour/compat6/classes/Input/Input.php
  plugins/behaviour/compat6/classes/Input/Json.php
  plugins/behaviour/compat6/compat6.xml
  plugins/behaviour/compat6/src/Extension/Compat6.php
  plugins/behaviour/compat6/src/classmap/classmap.php
  plugins/behaviour/compat6/src/classmap/extensions.classmap.php
  ruleset.xml
  tests/System/integration/install/Installation.cy.js
Labels: Language Change, Release Blocker, NPM Resource Changed, PR-6.0-dev

#45479 Revert "[6.0] Introduce Joomla 6.0 compatibility plugin"
  administrator/components/com_admin/script.php
  administrator/language/en-GB/plg_behaviour_compat.ini
  administrator/language/en-GB/plg_behaviour_compat.sys.ini
  administrator/language/en-GB/plg_behaviour_compat6.ini
  administrator/language/en-GB/plg_behaviour_compat6.sys.ini
  build/media_source/plg_behaviour_compat/es5.asset.json
  build/media_source/plg_behaviour_compat/removed.asset.json
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/behaviour/compat/classes/Application/BaseApplication.php
  plugins/behaviour/compat/classes/Application/CLI/CliInput.php
  plugins/behaviour/compat/classes/Application/CLI/CliOutput.php
  plugins/behaviour/compat/classes/Application/CLI/ColorStyle.php
  plugins/behaviour/compat/classes/Application/CLI/Output/Processor/ColorProcessor.php
  plugins/behaviour/compat/classes/Application/CLI/Output/Processor/ProcessorInterface.php
  plugins/behaviour/compat/classes/Application/CLI/Output/Stdout.php
  plugins/behaviour/compat/classes/Application/CLI/Output/Xml.php
  plugins/behaviour/compat/classes/Application/CliApplication.php
  plugins/behaviour/compat/classes/Filesystem/File.php
  plugins/behaviour/compat/classes/Filesystem/FilesystemHelper.php
  plugins/behaviour/compat/classes/Filesystem/Folder.php
  plugins/behaviour/compat/classes/Filesystem/Meta/language/en-GB/en-GB.lib_joomla_filesystem_patcher.ini
  plugins/behaviour/compat/classes/Filesystem/Patcher.php
  plugins/behaviour/compat/classes/Filesystem/Path.php
  plugins/behaviour/compat/classes/Filesystem/Stream.php
  plugins/behaviour/compat/classes/Filesystem/Streams/StreamString.php
  plugins/behaviour/compat/classes/Filesystem/Support/StringController.php
  plugins/behaviour/compat/classes/Input/Cookie.php
  plugins/behaviour/compat/classes/Input/Files.php
  plugins/behaviour/compat/classes/Input/Input.php
  plugins/behaviour/compat/classes/Input/Json.php
  plugins/behaviour/compat/compat.xml
  plugins/behaviour/compat/services/provider.php
  plugins/behaviour/compat/src/Extension/Compat.php
  plugins/behaviour/compat/src/classmap/classmap.php
  plugins/behaviour/compat/src/classmap/extensions.classmap.php
  plugins/behaviour/compat6/compat6.xml
  plugins/behaviour/compat6/src/Extension/Compat6.php
  ruleset.xml
  tests/System/integration/install/Installation.cy.js
Labels: Language Change, NPM Resource Changed, PR-6.0-dev

#45242 [5.4] Refactor components Table classes
  administrator/components/com_banners/src/Table/BannerTable.php
  administrator/components/com_banners/src/Table/ClientTable.php
  administrator/components/com_contact/src/Table/ContactTable.php
  administrator/components/com_content/src/Table/FeaturedTable.php
  administrator/components/com_fields/src/Table/FieldTable.php
  administrator/components/com_fields/src/Table/GroupTable.php
  administrator/components/com_finder/src/Table/FilterTable.php
  administrator/components/com_finder/src/Table/LinkTable.php
  administrator/components/com_finder/src/Table/MapTable.php
  administrator/components/com_guidedtours/src/Table/StepTable.php
  administrator/components/com_guidedtours/src/Table/TourTable.php
  administrator/components/com_installer/src/Table/UpdatesiteTable.php
  administrator/components/com_mails/src/Table/TemplateTable.php
  administrator/components/com_menus/src/Table/MenuTable.php
  administrator/components/com_messages/src/Table/MessageTable.php
  administrator/components/com_newsfeeds/src/Table/NewsfeedTable.php
  administrator/components/com_privacy/src/Table/ConsentTable.php
  administrator/components/com_privacy/src/Table/RequestTable.php
  administrator/components/com_redirect/src/Table/LinkTable.php
  administrator/components/com_scheduler/src/Table/LogTable.php
  administrator/components/com_scheduler/src/Table/TaskTable.php
  administrator/components/com_tags/src/Table/TagTable.php
  administrator/components/com_templates/src/Table/StyleTable.php
  administrator/components/com_users/src/Table/MfaTable.php
  administrator/components/com_users/src/Table/NoteTable.php
  administrator/components/com_workflow/src/Table/StageTable.php
  administrator/components/com_workflow/src/Table/TransitionTable.php
  administrator/components/com_workflow/src/Table/WorkflowTable.php
Labels: RTC, PR-5.4-dev

#45243 [5.4] Refactor CMS Table classes
  libraries/src/Table/Asset.php
  libraries/src/Table/Category.php
  libraries/src/Table/Content.php
  libraries/src/Table/ContentHistory.php
  libraries/src/Table/ContentType.php
  libraries/src/Table/CoreContent.php
  libraries/src/Table/Extension.php
  libraries/src/Table/Language.php
  libraries/src/Table/Menu.php
  libraries/src/Table/MenuType.php
  libraries/src/Table/Module.php
  libraries/src/Table/Nested.php
  libraries/src/Table/Ucm.php
  libraries/src/Table/Update.php
  libraries/src/Table/UpdateSite.php
  libraries/src/Table/User.php
  libraries/src/Table/Usergroup.php
  libraries/src/Table/ViewLevel.php
Labels: RTC, PR-5.4-dev

#43395 [5.4] CMSPlugin: deprecation for registerListeners
  libraries/src/Extension/PluginInterface.php
  libraries/src/Plugin/CMSPlugin.php
  libraries/src/Plugin/PluginHelper.php
Labels: RTC, PR-5.4-dev

#45477 [5.3] Use time safe compare method in phpass library
  administrator/manifests/libraries/phpass.xml
  libraries/phpass/PasswordHash.php
Labels: RTC, PR-5.3-dev

#45465 [5.3] Installation Development Mode info
  installation/tmpl/remove/default.php
Labels: RTC, PR-5.3-dev

#44900 [5.3] RTL Calendar Days
  build/media_source/system/js/fields/calendar.es5.js
Labels: RTC, NPM Resource Changed, bug, PR-5.3-dev

#45459 [5.4] Add tag filter none com_contact
  administrator/components/com_contact/forms/filter_contacts.xml
  administrator/components/com_contact/src/Model/ContactsModel.php
Labels: RTC, PR-5.4-dev

#45460 [5.4] Add tag filter none com_newsfeeds
  administrator/components/com_newsfeeds/forms/filter_newsfeeds.xml
  administrator/components/com_newsfeeds/src/Model/NewsfeedsModel.php
Labels: RTC, PR-5.4-dev

#45461 [5.4] Add tag filter none com_categories
  administrator/components/com_categories/forms/filter_categories.xml
  administrator/components/com_categories/src/Model/CategoriesModel.php
Labels: RTC, PR-5.4-dev

#45499 [5.4] Upmerge 2025-05-20
  administrator/components/com_media/resources/scripts/components/infobar/infobar.vue
  administrator/components/com_media/resources/scripts/components/tree/disk.vue
  administrator/manifests/libraries/phpass.xml
  build/media_source/com_media/scss/components/_layout.scss
  build/media_source/com_media/scss/components/_media-infobar.scss
  build/media_source/com_media/scss/components/_media-tree.scss
  build/media_source/system/js/fields/calendar.es5.js
  installation/tmpl/remove/default.php
  libraries/phpass/PasswordHash.php
Labels: NPM Resource Changed, PR-5.4-dev

#45143 [5.4] Automated Core Update Client
  administrator/components/com_admin/sql/updates/mysql/5.4.0-2025-05-10.sql
  administrator/components/com_admin/sql/updates/postgresql/5.4.0-2025-05-10.sql
  administrator/components/com_joomlaupdate/config.xml
  administrator/components/com_joomlaupdate/postinstall/autoupdate.php
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Enum/AutoupdateRegisterState.php
  administrator/components/com_joomlaupdate/src/Enum/AutoupdateState.php
  administrator/components/com_joomlaupdate/src/Model/NotificationModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/language/en-GB/com_joomlaupdate.ini
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_4.ini
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_4_steps.ini
  administrator/language/en-GB/plg_actionlog_joomla.ini
  administrator/language/en-GB/plg_quickicon_autoupdate.ini
  administrator/language/en-GB/plg_quickicon_autoupdate.sys.ini
  administrator/language/en-GB/plg_webservices_joomlaupdate.ini
  administrator/language/en-GB/plg_webservices_joomlaupdate.sys.ini
  api/components/com_joomlaupdate/src/Controller/BaseController.php
  api/components/com_joomlaupdate/src/Controller/HealthcheckController.php
  api/components/com_joomlaupdate/src/Controller/NotificationController.php
  api/components/com_joomlaupdate/src/Controller/UpdatesController.php
  api/components/com_joomlaupdate/src/View/Healthcheck/JsonapiView.php
  api/components/com_joomlaupdate/src/View/Notification/JsonapiView.php
  api/components/com_joomlaupdate/src/View/Updates/JsonapiView.php
  build/media_source/com_guidedtours/images/5_4/automated-updates.jpg
  build/media_source/plg_quickicon_autoupdate/js/healthcheck.es6.js
  index.php
  installation/sql/mysql/base.sql
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/base.sql
  installation/sql/postgresql/supports.sql
  libraries/src/Application/ConsoleApplication.php
  libraries/src/Console/AutomatedUpdatesRegisterCommand.php
  libraries/src/Console/AutomatedUpdatesUnregisterCommand.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Updater/Updater.php
  libraries/src/Uri/Uri.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/extension/joomlaupdate/src/Extension/Joomlaupdate.php
  plugins/quickicon/autoupdate/autoupdate.xml
  plugins/quickicon/autoupdate/services/provider.php
  plugins/quickicon/autoupdate/src/Extension/Autoupdate.php
  plugins/task/updatenotification/src/Extension/UpdateNotification.php
  plugins/webservices/joomlaupdate/joomlaupdate.xml
  plugins/webservices/joomlaupdate/services/provider.php
  plugins/webservices/joomlaupdate/src/Extension/Joomlaupdate.php
Labels: Feature, Language Change, NPM Resource Changed, PR-5.4-dev

#45517 [5.4] Automated Updates information
  administrator/components/com_joomlaupdate/config.xml
  administrator/language/en-GB/com_joomlaupdate.ini
Labels: RTC, Language Change, PR-5.4-dev

#45525 [5.4] Add compat6 behaviour plugin to 5.4 with enabled options
  administrator/components/com_admin/sql/updates/mysql/5.4.0-2025-04-23.sql
  administrator/components/com_admin/sql/updates/postgresql/5.4.0-2025-04-23.sql
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
Labels: RTC, Release Blocker, PR-5.4-dev

#45480 [6.0] Introduce Joomla 6.0 compatibility plugin
  administrator/components/com_admin/script.php
  administrator/language/en-GB/plg_behaviour_compat.ini
  administrator/language/en-GB/plg_behaviour_compat.sys.ini
  administrator/language/en-GB/plg_behaviour_compat6.ini
  administrator/language/en-GB/plg_behaviour_compat6.sys.ini
  build/media_source/plg_behaviour_compat/es5.asset.json
  build/media_source/plg_behaviour_compat6/removed.asset.json
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  libraries/src/Extension/ExtensionHelper.php
  plugins/behaviour/compat/compat.xml
  plugins/behaviour/compat/services/provider.php
  plugins/behaviour/compat/src/Extension/Compat.php
  plugins/behaviour/compat6/classes/Application/BaseApplication.php
  plugins/behaviour/compat6/classes/Application/CLI/CliInput.php
  plugins/behaviour/compat6/classes/Application/CLI/CliOutput.php
  plugins/behaviour/compat6/classes/Application/CLI/ColorStyle.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Processor/ColorProcessor.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Processor/ProcessorInterface.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Stdout.php
  plugins/behaviour/compat6/classes/Application/CLI/Output/Xml.php
  plugins/behaviour/compat6/classes/Application/CliApplication.php
  plugins/behaviour/compat6/classes/Filesystem/File.php
  plugins/behaviour/compat6/classes/Filesystem/FilesystemHelper.php
  plugins/behaviour/compat6/classes/Filesystem/Folder.php
  plugins/behaviour/compat6/classes/Filesystem/Meta/language/en-GB/en-GB.lib_joomla_filesystem_patcher.ini
  plugins/behaviour/compat6/classes/Filesystem/Patcher.php
  plugins/behaviour/compat6/classes/Filesystem/Path.php
  plugins/behaviour/compat6/classes/Filesystem/Stream.php
  plugins/behaviour/compat6/classes/Filesystem/Streams/StreamString.php
  plugins/behaviour/compat6/classes/Filesystem/Support/StringController.php
  plugins/behaviour/compat6/classes/Input/Cookie.php
  plugins/behaviour/compat6/classes/Input/Files.php
  plugins/behaviour/compat6/classes/Input/Input.php
  plugins/behaviour/compat6/classes/Input/Json.php
  plugins/behaviour/compat6/compat6.xml
  plugins/behaviour/compat6/src/Extension/Compat6.php
  plugins/behaviour/compat6/src/classmap/classmap.php
  plugins/behaviour/compat6/src/classmap/extensions.classmap.php
  ruleset.xml
  tests/System/integration/install/Installation.cy.js
Labels: RTC, Language Change, Release Blocker, NPM Resource Changed, PR-6.0-dev

#45520 [5.3] Installation missing string
  installation/language/en-GB/joomla.ini
Labels: RTC, Language Change, PR-5.3-dev

#45534 [6.0] Upmerges - 2025-05-28
  administrator/components/com_joomlaupdate/src/Controller/UpdateController.php
  administrator/components/com_joomlaupdate/src/Model/NotificationModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  api/components/com_joomlaupdate/src/View/Healthcheck/JsonapiView.php
  api/components/com_joomlaupdate/src/View/Notification/JsonapiView.php
  api/components/com_joomlaupdate/src/View/Updates/JsonapiView.php
  libraries/src/Console/AutomatedUpdatesRegisterCommand.php
  libraries/src/Console/AutomatedUpdatesUnregisterCommand.php
  libraries/src/Extension/PluginInterface.php
  libraries/src/Plugin/CMSPlugin.php
  libraries/src/Table/Table.php
  plugins/extension/joomlaupdate/src/Extension/Joomlaupdate.php
  plugins/quickicon/autoupdate/services/provider.php
  plugins/quickicon/autoupdate/src/Extension/Autoupdate.php
  plugins/webservices/joomlaupdate/services/provider.php
  plugins/webservices/joomlaupdate/src/Extension/Joomlaupdate.php
Labels: Test instructions missing, PR-6.0-dev

#45532 [6.0] Update version and links for release notes layout
  build/layouts/github.php
Labels: PR-6.0-dev

#45493 [5.4] Add pre-update checks for backward compatibility plugins for update to Joomla 6
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/language/en-GB/com_joomlaupdate.ini
  libraries/src/Console/UpdateCoreCommand.php
Labels: RTC, Language Change, Release Blocker, PR-5.4-dev

#45527 [5.3] Debug duplicate queries dark mode
  build/media_source/plg_system_debug/widgets/sqlqueries/widget.css
Labels: RTC, NPM Resource Changed, bug, Dark Mode, PR-5.3-dev
