Repository joomla/joomla-cms, pull requests merged in 2025-02, with the labels that each got.

#44809 [5.2] add PHP8.4 to PhpVersionCheck quickicon
  plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php
Labels: PHP 8.x, PR-5.2-dev

#44491 [5.2] Email alt text on contact
  components/com_contact/src/View/Contact/HtmlView.php
Labels: RTC, PR-5.2-dev

#44774 [5.2] Web Asset Manager incorect loading of external resource with / at the end
  libraries/src/WebAsset/WebAssetItem.php
Labels: RTC, bug, PR-5.2-dev

#44805 [5.2] [Security] Composer update symfony/http-client and symfony/process to version 6.4.15
  composer.lock
Labels: Composer Dependency Changed, PR-5.2-dev

#44802 Update Developers link in README.md and README.txt
  README.md
  README.txt
Labels: PR-5.2-dev

#44757 [5.3] Removing dealerdirect/phpcodesniffer-composer-installer entirely
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.3-dev

#44784 [5.2] Tag Router: Allow numeric/CSV IDs (Regression)
  components/com_tags/src/Service/Router.php
Labels: RTC, Release Blocker, bug, PR-5.2-dev

#43986 [5.2] Cache: Fix for counting the Number of Files correctly
  libraries/src/Cache/Storage/FileStorage.php
Labels: RTC, bug, PR-5.2-dev

#44807 [4.4] [Security] Composer update symfony/process to version 5.4.47
  composer.lock
Labels: Composer Dependency Changed, PR-4.4-dev

#44212 5.2 dev Fix breadcrumbs color in light and darkmode, fix for 44134
  build/media_source/com_media/scss/components/_media-breadcrumb.scss
Labels: RTC, NPM Resource Changed, bug, RMDQ, PR-5.2-dev

#44808 [5.3] Updating typo3/phar-stream-wrapper dependency to 4.0.0
  composer.json
  composer.lock
Labels: Composer Dependency Changed, bug, PR-5.3-dev

#44489 [5.3] Switch voku/portable-utf8 to joomla-backport for php8.4 bc
  composer.json
  composer.lock
Labels: Feature, Composer Dependency Changed, PR-5.3-dev

#44806 [5.3] Composer update debug bar to v2.1.0 and adapt to renamed package
  administrator/components/com_admin/script.php
  build/build-modules-js/init/cleanup-media.mjs
  build/build.php
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PHP 8.x, PR-5.3-dev

#44812 [5.3] Updating php-tuf/php-tuf and guzzlehttp/promises
  composer.lock
Labels: Composer Dependency Changed, Documentation Required, PR-5.3-dev

#44778 [5.3] Fix smart search sql error
  administrator/components/com_finder/src/Indexer/Taxonomy.php
Labels: RTC, Release Blocker, bug, PR-5.3-dev

#44611 [6.0] Remove the deprecated isCli function
  installation/src/Application/CliInstallationApplication.php
  libraries/src/Application/CMSApplication.php
  libraries/src/Application/CMSApplicationInterface.php
  libraries/src/Application/ConsoleApplication.php
  libraries/src/User/User.php
Labels: b/c break, PR-6.0-dev

#44637 [6.0] Remove the client id in the model cleanCache function
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_fields/src/Model/GroupModel.php
  administrator/components/com_finder/src/Model/FilterModel.php
  administrator/components/com_languages/src/Model/LanguageModel.php
  administrator/components/com_languages/src/Model/LanguagesModel.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_menus/src/Model/MenuModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_plugins/src/Model/PluginModel.php
  administrator/components/com_templates/src/Model/StyleModel.php
  components/com_content/src/Model/ArticleModel.php
Labels: PR-6.0-dev

#44754 [5.3] Deprecate namespace property of ComponentRecord
  libraries/src/Component/ComponentRecord.php
Labels: Feature, RTC, PR-5.3-dev

#44817 [5.3] onContentPrepareForm should return void instead of boolean
  plugins/content/confirmconsent/src/Extension/ConfirmConsent.php
Labels: PR-5.3-dev

#43427 [5.3] [Events] Use event classes for User plugins
  plugins/user/contactcreator/src/Extension/ContactCreator.php
  plugins/user/joomla/src/Extension/Joomla.php
  plugins/user/profile/src/Extension/Profile.php
  plugins/user/terms/src/Extension/Terms.php
  plugins/user/token/src/Extension/Token.php
Labels: Feature, PR-5.3-dev

#44820 [5.3] Remove useless return statement
  plugins/user/terms/src/Extension/Terms.php
Labels: PR-5.3-dev

#43602 [5.3] [Events] Use event classes for Privacy plugins
  plugins/privacy/actionlogs/src/Extension/Actionlogs.php
  plugins/privacy/consents/src/Extension/Consents.php
  plugins/privacy/contact/src/Extension/Contact.php
  plugins/privacy/content/src/Extension/Content.php
  plugins/privacy/message/src/Extension/Message.php
Labels: Feature, PR-5.3-dev

#43636 [5.3] [Events] Use event classes for Sampledata plugins
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/SampleData/GetOverviewEvent.php
  libraries/src/Event/SampleData/SampleDataEvent.php
  plugins/sampledata/blog/src/Extension/Blog.php
  plugins/sampledata/multilang/src/Extension/MultiLanguage.php
  plugins/sampledata/testing/src/Extension/Testing.php
Labels: Feature, PR-5.3-dev

#44813 [5.3] Update Jooa11y to Sa11y 4.0.3
  administrator/language/en-GB/plg_system_jooa11y.ini
  package-lock.json
  package.json
  plugins/system/jooa11y/jooa11y.xml
  plugins/system/jooa11y/src/Extension/Jooa11y.php
Labels: RTC, Language Change, Documentation Required, NPM Resource Changed, PR-5.3-dev

#43637 [5.3] [Events] Use event classes for System plugins
  libraries/src/Event/CoreEventAware.php
  libraries/src/Event/Plugin/System/Stats/GetStatsDataEvent.php
  plugins/system/accessibility/src/Extension/Accessibility.php
  plugins/system/actionlogs/src/Extension/ActionLogs.php
  plugins/system/fields/src/Extension/Fields.php
  plugins/system/highlight/services/provider.php
  plugins/system/highlight/src/Extension/Highlight.php
  plugins/system/jooa11y/src/Extension/Jooa11y.php
  plugins/system/languagecode/services/provider.php
  plugins/system/languagecode/src/Extension/LanguageCode.php
  plugins/system/log/services/provider.php
  plugins/system/log/src/Extension/Log.php
  plugins/system/logout/src/Extension/Logout.php
  plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
  plugins/system/remember/src/Extension/Remember.php
  plugins/system/skipto/services/provider.php
  plugins/system/skipto/src/Extension/Skipto.php
  plugins/system/stats/src/Extension/Stats.php
  plugins/system/stats/src/Field/DataField.php
Labels: Feature, Documentation Required, PR-5.3-dev

#44655 [6.0] Removing CMSObject from most of the codebase
  administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_guidedtours/src/View/Step/HtmlView.php
  administrator/components/com_installer/src/Helper/InstallerHelper.php
  administrator/components/com_installer/src/Model/UpdatesiteModel.php
  administrator/components/com_installer/src/Model/UpdatesitesModel.php
  administrator/components/com_installer/src/View/Update/HtmlView.php
  administrator/components/com_languages/src/Model/LanguageModel.php
  administrator/components/com_mails/src/Model/TemplateModel.php
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_media/helpers/media.php
  administrator/components/com_menus/src/Model/MenuModel.php
  administrator/components/com_menus/src/Model/MenutypesModel.php
  administrator/components/com_menus/src/View/Menutypes/HtmlView.php
  administrator/components/com_messages/src/Model/ConfigModel.php
  administrator/components/com_modules/src/Model/ModuleModel.php
  administrator/components/com_plugins/src/Helper/PluginsHelper.php
  administrator/components/com_plugins/src/Model/PluginModel.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_scheduler/src/Model/TasksModel.php
  administrator/components/com_templates/src/Helper/TemplatesHelper.php
  administrator/components/com_templates/src/Model/StyleModel.php
  administrator/components/com_users/src/Model/GroupModel.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  components/com_contact/src/Model/FormModel.php
  components/com_content/src/Model/FormModel.php
  components/com_tags/src/Model/TagModel.php
  libraries/src/Access/Rules.php
  libraries/src/HTML/Helpers/AdminLanguage.php
  libraries/src/HTML/Helpers/ContentLanguage.php
  libraries/src/MVC/Controller/ApiController.php
  libraries/src/MVC/View/ListView.php
  libraries/src/TUF/DatabaseStorage.php
  libraries/src/User/UserHelper.php
  plugins/system/guidedtours/src/Extension/GuidedTours.php
  tests/Unit/Libraries/Cms/Access/RulesTest.php
Labels: b/c break, PR-6.0-dev

#44787 [5.3] Deprecate several methods in UsersHelper
  administrator/components/com_users/src/Helper/UsersHelper.php
Labels: RTC, PR-5.3-dev

#44824 [5.3] Update drone for cypress
  .drone.yml
Labels: Unit/System Tests, PR-5.2-dev, PR-5.3-dev

#44825 [6.0] Upmerges - 2025-02-05
  administrator/components/com_finder/src/Indexer/Taxonomy.php
  build/build-modules-js/init/cleanup-media.mjs
  build/build.php
  composer.json
  composer.lock
  libraries/src/Component/ComponentRecord.php
  plugins/content/confirmconsent/src/Extension/ConfirmConsent.php
  plugins/content/contact/src/Extension/Contact.php
  plugins/content/fields/src/Extension/Fields.php
  plugins/content/finder/src/Extension/Finder.php
  plugins/content/joomla/src/Extension/Joomla.php
  plugins/content/loadmodule/src/Extension/LoadModule.php
  plugins/content/pagebreak/src/Extension/PageBreak.php
  plugins/content/pagenavigation/src/Extension/PageNavigation.php
  plugins/content/vote/src/Extension/Vote.php
  tests/Unit/Plugin/Content/ConfirmConsent/Extension/ConfirmConsentTest.php
Labels: Unit/System Tests, Test instructions missing, Composer Dependency Changed, PR-6.0-dev

#44814 [5.3] Update all dependencies
  build/update_fido_cache.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  plugins/editors/tinymce/tinymce.xml
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.3-dev

#44675 [5.3][cypress] com_contenthistory content administrator test
  tests/System/integration/administrator/components/com_contenthistory/Content.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#44822 [5.3] Upmerge changes from 5.2-dev 2025-02-05
  README.md
  README.txt
  administrator/components/com_admin/sql/updates/mysql/5.2.3-2025-01-09.sql
  administrator/components/com_admin/sql/updates/postgresql/5.2.3-2025-01-09.sql
  administrator/language/en-GB/com_actionlogs.ini
  administrator/language/en-GB/com_media.ini
  administrator/language/en-GB/guidedtours.joomla_guidedtoursteps_steps.ini
  build/media_source/com_media/scss/components/_media-breadcrumb.scss
  components/com_tags/src/Service/Router.php
  installation/sql/mysql/supports.sql
  installation/sql/postgresql/supports.sql
  libraries/namespacemap.php
  libraries/src/Cache/Storage/FileStorage.php
  libraries/src/WebAsset/WebAssetItem.php
  plugins/quickicon/phpversioncheck/src/Extension/PhpVersionCheck.php
  tests/System/integration/administrator/components/com_actionlogs/Actionlogs.cy.js
  tests/System/integration/administrator/components/com_banners/Banner.cy.js
  tests/System/integration/administrator/components/com_banners/Banners.cy.js
  tests/System/integration/administrator/components/com_banners/Client.cy.js
  tests/System/integration/administrator/components/com_banners/Clients.cy.js
  tests/System/integration/administrator/components/com_cache/Default.cy.js
  tests/System/integration/administrator/components/com_categories/Categories.cy.js
  tests/System/integration/administrator/components/com_categories/Category.cy.js
  tests/System/integration/administrator/components/com_checkin/Default.cy.js
  tests/System/integration/administrator/components/com_config/Application.cy.js
  tests/System/integration/administrator/components/com_contact/Contact.cy.js
  tests/System/integration/administrator/components/com_contact/Contacts.cy.js
  tests/System/integration/administrator/components/com_content/Article.cy.js
  tests/System/integration/administrator/components/com_content/Articles.cy.js
  tests/System/integration/administrator/components/com_fields/Field.cy.js
  tests/System/integration/administrator/components/com_fields/Fields.cy.js
  tests/System/integration/administrator/components/com_joomlaupdate/Update.cy.js
  tests/System/integration/administrator/components/com_login/Login.cy.js
  tests/System/integration/administrator/components/com_media/Media.cy.js
  tests/System/integration/administrator/components/com_menu/Menu.cy.js
  tests/System/integration/administrator/components/com_menu/MenuItem.cy.js
  tests/System/integration/administrator/components/com_modules/Module.cy.js
  tests/System/integration/administrator/components/com_modules/Modules.cy.js
  tests/System/integration/administrator/components/com_newsfeeds/Newsfeed.cy.js
  tests/System/integration/administrator/components/com_newsfeeds/Newsfeeds.cy.js
  tests/System/integration/administrator/components/com_plugins/Plugins.cy.js
  tests/System/integration/administrator/components/com_scheduler/Tasks.cy.js
  tests/System/integration/administrator/components/com_tags/Tag.cy.js
  tests/System/integration/administrator/components/com_tags/Tags.cy.js
  tests/System/integration/administrator/components/com_users/Group.cy.js
  tests/System/integration/administrator/components/com_users/Groups.cy.js
  tests/System/integration/administrator/components/com_users/Level.cy.js
  tests/System/integration/administrator/components/com_users/Levels.cy.js
  tests/System/integration/administrator/components/com_users/User.cy.js
  tests/System/integration/administrator/components/com_users/Users.cy.js
  tests/System/integration/plugins/system/sef/SefPlugin.cy.js
  tests/System/integration/site/components/com_users/Logout.cy.js
  tests/System/integration/site/components/com_users/Profile_Edit.cy.js
  tests/System/integration/site/components/com_users/Registration.cy.js
  tests/System/integration/site/components/com_users/Remind.cy.js
  tests/System/integration/site/components/com_users/Reset.cy.js
  tests/System/plugins/fs.mjs
  tests/System/support/commands/config.mjs
Labels: Unit/System Tests, Language Change, NPM Resource Changed, PR-5.3-dev

#44592 Fix phpdoc $module parameter type
  libraries/src/Document/Renderer/Html/ModuleRenderer.php
Labels: PR-5.3-dev

#44756 [5.3] Awesomplete accessibility fix
  build/media_source/com_finder/js/finder.es6.js
  components/com_finder/tmpl/search/default_form.php
  language/en-GB/com_finder.ini
  modules/mod_finder/tmpl/default.php
Labels: RTC, Language Change, a11y, NPM Resource Changed, PR-5.3-dev

#44752 [5.3] Convert mod_privacy_status to service provider
  administrator/modules/mod_privacy_status/mod_privacy_status.php
  administrator/modules/mod_privacy_status/mod_privacy_status.xml
  administrator/modules/mod_privacy_status/services/provider.php
  administrator/modules/mod_privacy_status/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_privacy_status/src/Helper/PrivacyStatusHelper.php
Labels: RTC, PR-5.3-dev

#44839 [5.3] alpha-sorting strings in plg_system_jooa11y.ini
  administrator/language/en-GB/plg_system_jooa11y.ini
Labels: Language Change, PR-5.3-dev

#44607 [5.3] Logical css joomla tabs
  build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#44842 [5.3] Improve System - Page Cache plugin code
  plugins/system/cache/src/Extension/Cache.php
Labels: RTC, PR-5.3-dev

#44841 [5.3] Improve System - Language Filter plugin code
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: Feature, RTC, PR-5.3-dev

#44830 [5.3] Improve System - SEF plugin code
  plugins/system/sef/src/Extension/Sef.php
Labels: Feature, PR-5.3-dev

#44843 [5.3] Remove useless clone statement
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_categories/src/Model/CategoryModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_guidedtours/src/Model/StepModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_workflow/src/Model/StageModel.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
Labels: RTC, PR-5.3-dev

#44844 [5.3] Improve System - Debug plugin code
  plugins/system/debug/src/Extension/Debug.php
Labels: Feature, RTC, PR-5.3-dev

#44840 [5.3] Improve System - Additional Accessibility Features code
  plugins/system/accessibility/src/Extension/Accessibility.php
Labels: Feature, RTC, PR-5.3-dev

#43396 [5.3] Deprecate HTMLHelper::script(), HTMLHelper::stylesheet(), extend lifetime for Document style/script methods
  libraries/src/Document/Document.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/WebAsset/WebAssetItem.php
Labels: Feature, RTC, Documentation Required, PR-5.3-dev

#44638 [6.0] Move the JPATH_PLATFORM constant to the compat plugin
  build/phpstan/joomla-bootstrap.php
  build/psr12/clean_errors.php
  libraries/bootstrap.php
  libraries/cms.php
  libraries/import.legacy.php
  libraries/import.php
  plugins/behaviour/compat/src/Extension/Compat.php
  tests/Unit/bootstrap.php
Labels: RTC, Unit/System Tests, b/c break, PR-6.0-dev

#44855 [5.3] Improve System - Keyboard Shortcuts plugin code
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: PR-5.3-dev

#44819 [5.3] Convert administrator mod_feed to service provider
  administrator/modules/mod_feed/mod_feed.php
  administrator/modules/mod_feed/mod_feed.xml
  administrator/modules/mod_feed/services/provider.php
  administrator/modules/mod_feed/src/Dispatcher/Dispatcher.php
  administrator/modules/mod_feed/src/Helper/FeedHelper.php
Labels: RTC, PR-5.3-dev

#44321 [6.0] Remove leftover reCaptcha files
  build/media_source/plg_captcha_recaptcha/js/recaptcha.es6.js
  build/media_source/plg_captcha_recaptcha_invisible/js/recaptcha.es6.js
  build/media_source/plg_captcha_recaptcha_invisible/scss/recaptcha_invisible.scss
  build/psr12/phpcs.joomla.report.php
Labels: Feature, RTC, NPM Resource Changed, b/c break, PR-6.0-dev

#44873 [5.3] Copy the cypress config to not interfere with the cs task
  .drone.yml
Labels: Unit/System Tests, PR-5.3-dev

#44911 [5.2][UnitTest] Use @backupGlobals to backup $_SERVER
  tests/Unit/Libraries/Cms/Environment/BrowserTest.php
  tests/Unit/Libraries/Cms/Uri/UriTest.php
Labels: Unit/System Tests, PR-5.2-dev

#44893 [5.3] Change list to array destruct for components code
  administrator/components/com_associations/src/Controller/AssociationController.php
  administrator/components/com_associations/src/Controller/AssociationsController.php
  administrator/components/com_associations/src/Dispatcher/Dispatcher.php
  administrator/components/com_associations/src/Field/ItemlanguageField.php
  administrator/components/com_associations/src/Model/AssociationsModel.php
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_guidedtours/src/Helper/GuidedtoursHelper.php
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_media/src/Controller/ApiController.php
  administrator/components/com_media/src/Model/FileModel.php
  administrator/components/com_media/src/Provider/ProviderManager.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
  administrator/components/com_tags/src/Model/TagModel.php
  administrator/components/com_workflow/src/Model/StageModel.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
  components/com_contact/src/Service/Router.php
  components/com_content/src/Service/Router.php
  components/com_newsfeeds/src/Service/Router.php
Labels: RTC, PR-5.3-dev

#44877 [5.3] Change Ternary To null coalescing operator for components code
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_workflow/src/Model/StageModel.php
  administrator/components/com_workflow/src/Model/TransitionModel.php
  administrator/components/com_workflow/src/Model/WorkflowModel.php
Labels: RTC, PR-5.3-dev

#44875 [5.3] Use str_contains function for components
  administrator/components/com_associations/src/Helper/AssociationsHelper.php
  administrator/components/com_categories/src/Field/CategoryeditField.php
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_content/src/Event/Model/FeatureEvent.php
  administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php
  administrator/components/com_guidedtours/src/Model/StepModel.php
  administrator/components/com_guidedtours/src/Model/TourModel.php
  administrator/components/com_installer/src/Model/LanguagesModel.php
  administrator/components/com_installer/src/Model/ManageModel.php
  administrator/components/com_installer/src/Model/UpdateModel.php
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_languages/src/Model/StringsModel.php
  administrator/components/com_login/src/Controller/DisplayController.php
  administrator/components/com_menus/src/Model/ItemsModel.php
  administrator/components/com_menus/src/Model/MenutypesModel.php
  administrator/components/com_postinstall/src/Helper/PostinstallHelper.php
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, PR-5.3-dev

#44874 [5.3] Use str_ends_with for components code
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_joomlaupdate/extract.php
  administrator/components/com_joomlaupdate/finalisation.php
  administrator/components/com_templates/src/Model/TemplateModel.php
Labels: RTC, PR-5.3-dev

#44868 [5.3] Use str_starts_with function for components
  administrator/components/com_banners/src/Model/BannerModel.php
  administrator/components/com_config/src/Dispatcher/Dispatcher.php
  administrator/components/com_contact/src/Model/ContactModel.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_cpanel/src/Controller/DisplayController.php
  administrator/components/com_fields/src/Plugin/FieldsPlugin.php
  administrator/components/com_login/src/Model/LoginModel.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_menus/src/Model/MenutypesModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedModel.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_users/src/Dispatcher/Dispatcher.php
  administrator/components/com_users/src/Model/LevelModel.php
  administrator/components/com_users/src/Service/Encrypt.php
  components/com_banners/src/Model/BannersModel.php
  components/com_config/src/Dispatcher/Dispatcher.php
  components/com_wrapper/src/View/Wrapper/HtmlView.php
Labels: RTC, PR-5.3-dev

#44858 [5.3] Restrict bootstrap collapse to the header
  build/media_source/templates/administrator/atum/js/template.es6.js
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#44867 [5.3] Remove the reference to the super global
  libraries/src/Input/Cookie.php
Labels: RTC, PR-5.3-dev

#44845 [5.3] Completely revert PR 44640 - [5.3][com_actionlogs] exclude self from mail notification
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  administrator/components/com_admin/sql/updates/mysql/5.3.0-2024-12-19.sql
  administrator/components/com_admin/sql/updates/mysql/5.3.0-2025-02-09.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.0-2024-12-19.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-02-09.sql
  administrator/language/en-GB/plg_system_actionlogs.ini
  installation/sql/mysql/extensions.sql
  installation/sql/postgresql/extensions.sql
  plugins/system/actionlogs/forms/actionlogs.xml
  plugins/system/actionlogs/src/Extension/ActionLogs.php
Labels: Language Change, Release Blocker, PR-5.3-dev

#44838 [5.3] Update deleted files in script.php for the upcoming 5.3.0-beta1
  administrator/components/com_admin/script.php
Labels: PR-5.3-dev

#44852 [5.3] Fix code style in vue files and and also exit 1 when warnings
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/resources/scripts/components/modals/create-folder-modal.vue
  package.json
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#44920 [5.3] Use null coalescing assignment operator for libraries code
  libraries/src/Button/TransitionButton.php
  libraries/src/Categories/Categories.php
  libraries/src/Editor/Button/ButtonsRegistry.php
  libraries/src/Editor/Editor.php
  libraries/src/Event/Model/PrepareDataEvent.php
  libraries/src/Event/Module/AfterRenderModulesEvent.php
  libraries/src/Event/Module/ModuleListEvent.php
  libraries/src/Event/Plugin/AjaxEvent.php
  libraries/src/Event/Result/ResultAware.php
  libraries/src/Event/View/DisplayEvent.php
  libraries/src/Event/Workflow/AbstractEvent.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Language/LanguageHelper.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/MVC/Model/FormModel.php
  libraries/src/Pagination/Pagination.php
  libraries/src/Toolbar/Button/HelpButton.php
  libraries/src/Toolbar/Button/InlinehelpButton.php
  libraries/src/Toolbar/Button/PopupButton.php
  libraries/src/Toolbar/Button/StandardButton.php
  libraries/src/WebAsset/WebAssetManager.php
  libraries/src/WebAuthn/Server.php
Labels: PR-5.3-dev

#44902 [5.3] Composer update debugbar to 2.1.1 and fix CSS for dark mode
  build/media_source/plg_system_debug/css/debug.css
  composer.lock
Labels: Composer Dependency Changed, NPM Resource Changed, PR-5.3-dev

#44880 [6.0] Extend lifespan of CMSObject and fix deprecations tags
  libraries/src/Object/CMSObject.php
  libraries/src/Object/LegacyErrorHandlingTrait.php
  libraries/src/Object/LegacyPropertyManagementTrait.php
Labels: PR-6.0-dev

#44931 [5.4] Set initial version and code name
  README.md
  README.txt
  administrator/language/en-GB/install.xml
  administrator/language/en-GB/langmetadata.xml
  administrator/manifests/files/joomla.xml
  administrator/manifests/packages/pkg_en-GB.xml
  api/language/en-GB/install.xml
  api/language/en-GB/langmetadata.xml
  build.xml
  installation/language/en-GB/langmetadata.xml
  language/en-GB/install.xml
  language/en-GB/langmetadata.xml
  libraries/src/Version.php
  package-lock.json
  package.json
Labels: Language Change, NPM Resource Changed, PR-5.4-dev

#44932 [6.0] Remove deprecated strings
  administrator/language/en-GB/plg_system_jooa11y.ini
Labels: RTC, Language Change, PR-6.0-dev

#44864 [5.2] Set column alias for BannerTable, fix warning on Save As Copy
  administrator/components/com_banners/src/Table/BannerTable.php
Labels: RTC, bug, PR-5.2-dev

#44876 [5.2] PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated
  libraries/src/Table/Category.php
Labels: RTC, bug, PR-5.2-dev

#44915 [5.3] Use str_starts_with function for libraries code
  libraries/src/Cache/Storage/ApcuStorage.php
  libraries/src/Cache/Storage/MemcachedStorage.php
  libraries/src/Cache/Storage/RedisStorage.php
  libraries/src/Event/AbstractEvent.php
  libraries/src/Filesystem/Folder.php
  libraries/src/Form/Field/SchemaorgComponentSectionsField.php
  libraries/src/Form/Field/WorkflowComponentSectionsField.php
  libraries/src/Form/Filter/TelFilter.php
  libraries/src/Form/Filter/UrlFilter.php
  libraries/src/Form/Form.php
  libraries/src/Form/FormField.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Helper/AuthenticationHelper.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Helper/PublicFolderGeneratorHelper.php
  libraries/src/Http/Transport/CurlTransport.php
  libraries/src/Input/Cli.php
  libraries/src/Installer/Adapter/ComponentAdapter.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Model/FormBehaviorTrait.php
  libraries/src/MVC/Model/ListModel.php
  libraries/src/Mail/MailHelper.php
  libraries/src/Object/LegacyPropertyManagementTrait.php
  libraries/src/Pathway/SitePathway.php
  libraries/src/Plugin/CMSPlugin.php
  libraries/src/Router/ApiRouter.php
  libraries/src/Router/Route.php
  libraries/src/Router/Router.php
  libraries/src/Table/Table.php
  libraries/src/Toolbar/Button/PopupButton.php
  libraries/src/Uri/Uri.php
  libraries/src/User/UserHelper.php
  libraries/src/WebAsset/WebAssetItem.php
  libraries/src/WebAsset/WebAssetManager.php
Labels: RTC, PR-5.3-dev

#44916 [5.3] Use str_ends_with function for libraries code
  libraries/src/HTML/Helpers/StringHelper.php
  libraries/src/Mail/MailHelper.php
  libraries/src/Router/SiteRouter.php
  libraries/src/Schema/ChangeItem/MysqlChangeItem.php
  libraries/src/Updater/Adapter/CollectionAdapter.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  libraries/src/Updater/UpdateAdapter.php
Labels: RTC, PR-5.3-dev

#44918 [5.3] Changes unneeded null check to ?? operator for libraries
  libraries/src/Application/CMSApplication.php
  libraries/src/HTML/Helpers/Access.php
  libraries/src/HTML/Helpers/Bootstrap.php
  libraries/src/Image/Image.php
  libraries/src/MVC/Model/AdminModel.php
  libraries/src/Mail/Mail.php
  libraries/src/Session/MetadataManager.php
  libraries/src/Table/MenuType.php
  libraries/src/Updater/Updater.php
Labels: RTC, PR-5.3-dev

#44921 [5.3] Use ternary operator for libraries
  libraries/src/Form/Field/CalendarField.php
  libraries/src/Form/Form.php
Labels: RTC, PR-5.3-dev

#44936 [5.3] Use str_starts_with function for modules and plugins
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  administrator/modules/mod_submenu/src/Menu/Menu.php
  modules/mod_menu/src/Helper/MenuHelper.php
  modules/mod_wrapper/src/Helper/WrapperHelper.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
  plugins/system/debug/src/Extension/Debug.php
  plugins/system/fields/src/Extension/Fields.php
  plugins/system/httpheaders/src/Extension/Httpheaders.php
  plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
  plugins/user/profile/src/Extension/Profile.php
Labels: RTC, PR-5.3-dev

#44937 [5.3] Use str_ends_with function for modules plugins
  plugins/system/sef/src/Extension/Sef.php
  plugins/task/updatenotification/src/Extension/UpdateNotification.php
Labels: RTC, PR-5.3-dev

#44917 [5.3] Use str_contains function for libraries code
  libraries/src/Application/WebApplication.php
  libraries/src/Authentication/Password/MD5Handler.php
  libraries/src/Client/FtpClient.php
  libraries/src/Console/SetConfigurationCommand.php
  libraries/src/Date/Date.php
  libraries/src/Dispatcher/ComponentDispatcher.php
  libraries/src/Document/Renderer/Feed/RssRenderer.php
  libraries/src/Document/Renderer/Html/ScriptsRenderer.php
  libraries/src/Document/Renderer/Html/StylesRenderer.php
  libraries/src/Environment/Browser.php
  libraries/src/Event/View/DisplayEvent.php
  libraries/src/Event/Workflow/AbstractEvent.php
  libraries/src/Filesystem/File.php
  libraries/src/Form/Field/CaptchaField.php
  libraries/src/Form/Field/MediaField.php
  libraries/src/Form/Field/TagField.php
  libraries/src/Form/Field/TimezoneField.php
  libraries/src/Form/Field/UsergrouplistField.php
  libraries/src/Form/FormField.php
  libraries/src/Form/FormHelper.php
  libraries/src/Form/FormRule.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/HTML/Helpers/Number.php
  libraries/src/HTML/Helpers/Select.php
  libraries/src/HTML/Helpers/StringHelper.php
  libraries/src/Helper/MediaHelper.php
  libraries/src/Helper/ModuleHelper.php
  libraries/src/Helper/TagsHelper.php
  libraries/src/Installer/InstallerHelper.php
  libraries/src/Language/Language.php
  libraries/src/Language/Text.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/MVC/Model/LegacyModelLoaderTrait.php
  libraries/src/MVC/View/HtmlView.php
  libraries/src/Mail/MailHelper.php
  libraries/src/Pathway/SitePathway.php
  libraries/src/Plugin/PluginHelper.php
  libraries/src/Router/Router.php
  libraries/src/Session/Session.php
  libraries/src/Uri/Uri.php
  libraries/src/WebAsset/WebAssetItem.php
Labels: Code Review, PR-5.3-dev

#44938 [5.3] Use str_contains function for modules plugins
  modules/mod_menu/src/Helper/MenuHelper.php
  modules/mod_wrapper/src/Helper/WrapperHelper.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/behaviour/taggable/src/Extension/Taggable.php
  plugins/content/fields/src/Extension/Fields.php
  plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php
  plugins/system/debug/src/DataCollector/QueryCollector.php
  plugins/system/debug/src/Extension/Debug.php
  plugins/system/httpheaders/src/Extension/Httpheaders.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
  plugins/system/redirect/src/Extension/Redirect.php
  plugins/system/sef/src/Extension/Sef.php
  plugins/system/webauthn/src/CredentialRepository.php
  plugins/user/joomla/src/Extension/Joomla.php
Labels: RTC, PR-5.3-dev

#44953 [5.3] Display Mail Templates data use current language
  administrator/components/com_mails/src/View/Templates/HtmlView.php
Labels: RTC, PBF, PR-5.3-dev

#44878 [5.3] Use Null Coalescing Assignment Operator For Components
  .php-cs-fixer.dist.php
  administrator/components/com_content/src/Event/Model/FeatureEvent.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_menus/src/Helper/MenusHelper.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/components/com_menus/src/View/Items/HtmlView.php
  administrator/components/com_scheduler/src/Helper/ExecRuleHelper.php
  administrator/components/com_scheduler/src/Model/TaskModel.php
  administrator/components/com_scheduler/src/Task/Task.php
  administrator/components/com_users/src/Controller/MethodsController.php
  components/com_contact/src/Helper/AssociationHelper.php
  components/com_content/src/Helper/AssociationHelper.php
  components/com_newsfeeds/src/Helper/AssociationHelper.php
  libraries/src/Categories/Categories.php
  libraries/src/Editor/Button/ButtonsRegistry.php
  libraries/src/Editor/Editor.php
  libraries/src/Event/View/DisplayEvent.php
  libraries/src/Event/Workflow/AbstractEvent.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/Toolbar/Button/InlinehelpButton.php
  libraries/src/WebAuthn/Server.php
Labels: RTC, PR-5.3-dev

#43907 [6.0] Gsoc2021 35228 merge featured
  administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-06-01.sql
  administrator/components/com_admin/sql/updates/mysql/6.0.0-2024-08-11.sql
  administrator/components/com_admin/sql/updates/postgresql/6.0.0-2024-06-01.sql
  administrator/components/com_admin/sql/updates/postgresql/6.0.0-2024-08-11.sql
  administrator/components/com_content/forms/filter_articles.xml
  administrator/components/com_content/forms/filter_featured.xml
  administrator/components/com_content/presets/content.xml
  administrator/components/com_content/src/Controller/ArticlesController.php
  administrator/components/com_content/src/Controller/DisplayController.php
  administrator/components/com_content/src/Controller/FeaturedController.php
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_content/src/Model/FeaturedModel.php
  administrator/components/com_content/src/View/Articles/HtmlView.php
  administrator/components/com_content/src/View/Featured/HtmlView.php
  administrator/components/com_content/tmpl/articles/default.php
  administrator/components/com_content/tmpl/featured/default.php
  administrator/components/com_content/tmpl/featured/default.xml
  administrator/components/com_content/tmpl/featured/default_stage_body.php
  administrator/components/com_content/tmpl/featured/default_stage_footer.php
  administrator/components/com_content/tmpl/featured/emptystate.php
  administrator/components/com_menus/presets/alternate.xml
  administrator/components/com_menus/presets/default.xml
  administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Labels: Feature, PR-6.0-dev

#44989 [5.3] Avoid warning when deleting media file/folder
  plugins/system/schemaorg/src/Extension/Schemaorg.php
Labels: RTC, bug, PR-5.3-dev

#44995 Add border last element media breadcrumbs
  build/media_source/com_media/scss/components/_media-breadcrumb.scss
Labels: RTC, PR-5.2-dev

#45005 [cypress] Update Menu.cy.js
  tests/System/integration/administrator/components/com_menu/Menu.cy.js
Labels: RTC, Unit/System Tests, PR-5.2-dev

#44988 [5.2.4] com_contact : Send Copy to Submitter does not work anymore
  components/com_contact/forms/contact.xml
Labels: RTC, PR-5.2-dev

#44488 Redesign carousel implementation to reflect documentation - bug fix
  build/media_source/vendor/bootstrap/js/carousel.es6.js
  libraries/src/HTML/Helpers/Bootstrap.php
Labels: RTC, NPM Resource Changed, bug, PR-5.2-dev

#44998 [5.3] better use str_starts_with
  administrator/components/com_associations/src/Helper/AssociationsHelper.php
  administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php
  administrator/components/com_postinstall/src/Helper/PostinstallHelper.php
  modules/mod_wrapper/src/Helper/WrapperHelper.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: RTC, PR-5.3-dev

#44983 [5.3] Combine multiple unset call into one call
  .php-cs-fixer.dist.php
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_config/src/Model/ComponentModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_menus/src/Model/MenutypesModel.php
  administrator/components/com_modules/src/View/Modules/HtmlView.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  api/components/com_languages/src/View/Overrides/JsonapiView.php
  libraries/src/Changelog/Changelog.php
  libraries/src/Input/Cli.php
  libraries/src/MVC/Controller/AdminController.php
  libraries/src/Updater/Update.php
  libraries/src/User/User.php
  plugins/system/languagefilter/src/Extension/LanguageFilter.php
Labels: RTC, PR-5.3-dev

#44982 [5.3] Change isset($var) && multiple times to one isset call
  .php-cs-fixer.dist.php
  administrator/components/com_associations/src/View/Associations/HtmlView.php
  administrator/components/com_checkin/src/Model/CheckinModel.php
  administrator/components/com_config/src/Controller/ComponentController.php
  administrator/components/com_content/src/Model/ArticleModel.php
  administrator/components/com_contenthistory/src/Helper/ContenthistoryHelper.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_menus/src/Model/ItemModel.php
  administrator/modules/mod_stats_admin/src/Helper/StatsAdminHelper.php
  components/com_finder/src/Service/Router.php
  components/com_tags/src/Service/Router.php
  components/com_users/src/View/Profile/HtmlView.php
  libraries/src/Component/Router/RouterView.php
  libraries/src/Component/Router/Rules/NomenuRules.php
  libraries/src/Document/Renderer/Html/MessageRenderer.php
  libraries/src/Filter/InputFilter.php
  libraries/src/Form/Rule/TimeRule.php
  libraries/src/HTML/Helpers/Select.php
  libraries/src/Installer/Manifest/LibraryManifest.php
  libraries/src/Response/JsonResponse.php
  libraries/src/Table/ContentType.php
  libraries/src/Table/Nested.php
  modules/mod_stats/src/Helper/StatsHelper.php
  plugins/authentication/ldap/src/Extension/Ldap.php
  plugins/task/globalcheckin/src/Extension/Globalcheckin.php
Labels: RTC, PR-5.3-dev

#44981 [5.3] Simplify code using PHPCS Fixer no_unneeded_control_parentheses rule
  .php-cs-fixer.dist.php
  administrator/components/com_associations/src/Helper/AssociationsHelper.php
  administrator/components/com_categories/src/Controller/CategoryController.php
  administrator/components/com_contact/src/Extension/ContactComponent.php
  administrator/components/com_installer/src/Controller/ManageController.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_users/src/Controller/GroupController.php
  administrator/components/com_users/src/Controller/LevelController.php
  components/com_contact/src/Controller/ContactController.php
  components/com_content/helpers/icon.php
  components/com_finder/src/Model/SearchModel.php
  components/com_finder/src/View/Search/HtmlView.php
  libraries/src/Client/FtpClient.php
  libraries/src/Console/SetConfigurationCommand.php
  libraries/src/Helper/UserGroupsHelper.php
  libraries/src/Image/Image.php
Labels: RTC, PR-5.3-dev

#44975 [5.3] Improve api app code using rector rules
  api/components/com_media/src/Controller/MediaController.php
  api/components/com_media/src/Model/AdapterModel.php
  api/components/com_media/src/Model/MediaModel.php
  api/components/com_media/src/Model/MediumModel.php
Labels: RTC, PR-5.3-dev

#44973 [5.3] Change list() to array destruct for libraries code
  libraries/src/Console/SetConfigurationCommand.php
  libraries/src/Dispatcher/ComponentDispatcher.php
  libraries/src/Environment/Browser.php
  libraries/src/Extension/ExtensionManagerTrait.php
  libraries/src/Form/Field/TimezoneField.php
  libraries/src/Form/FormHelper.php
  libraries/src/HTML/HTMLHelper.php
  libraries/src/HTML/Helpers/Number.php
  libraries/src/Input/Cli.php
  libraries/src/Input/Input.php
  libraries/src/MVC/Controller/BaseController.php
  libraries/src/Table/Content.php
Labels: RTC, PR-5.3-dev

#44970 [5.3] Change list() to array destruct for modules and plugins code
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/system/debug/src/JavascriptRenderer.php
  plugins/user/contactcreator/src/Extension/ContactCreator.php
Labels: RTC, PR-5.3-dev

#44969 [5.3] Changes unneeded null check to ?? operator for modules and plugins
  administrator/modules/mod_menu/src/Menu/CssMenu.php
Labels: RTC, PR-5.3-dev

#44967 [5.3] Remove unused exception variable in catch for modules and plugins
  administrator/modules/mod_feed/src/Helper/FeedHelper.php
  administrator/modules/mod_privacy_dashboard/src/Helper/PrivacyDashboardHelper.php
  administrator/modules/mod_stats_admin/src/Helper/StatsAdminHelper.php
  modules/mod_articles_archive/src/Helper/ArticlesArchiveHelper.php
  modules/mod_feed/src/Helper/FeedHelper.php
  modules/mod_related_items/src/Helper/RelatedItemsHelper.php
  modules/mod_stats/src/Helper/StatsHelper.php
  modules/mod_tags_similar/src/Helper/TagsSimilarHelper.php
  modules/mod_users_latest/src/Helper/UsersLatestHelper.php
  modules/mod_whosonline/src/Helper/WhosonlineHelper.php
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/api-authentication/token/src/Extension/Token.php
  plugins/authentication/cookie/src/Extension/Cookie.php
  plugins/content/confirmconsent/src/Field/ConsentBoxField.php
  plugins/editors/tinymce/src/PluginTraits/ActiveSiteTemplate.php
  plugins/extension/finder/src/Extension/Finder.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
  plugins/installer/override/src/Extension/Override.php
  plugins/multifactorauth/email/src/Extension/Email.php
  plugins/multifactorauth/webauthn/src/Extension/Webauthn.php
  plugins/multifactorauth/webauthn/src/Helper/Credentials.php
  plugins/multifactorauth/yubikey/src/Extension/Yubikey.php
  plugins/sampledata/multilang/src/Extension/MultiLanguage.php
  plugins/schemaorg/custom/src/Extension/Custom.php
  plugins/system/actionlogs/src/Extension/ActionLogs.php
  plugins/system/guidedtours/src/Extension/GuidedTours.php
  plugins/system/log/src/Extension/Log.php
  plugins/system/privacyconsent/src/Extension/PrivacyConsent.php
  plugins/system/redirect/src/Extension/Redirect.php
  plugins/system/schedulerunner/src/Extension/ScheduleRunner.php
  plugins/system/stats/src/Extension/Stats.php
  plugins/system/tasknotification/src/Extension/TaskNotification.php
  plugins/system/webauthn/src/Authentication.php
  plugins/system/webauthn/src/CredentialRepository.php
  plugins/system/webauthn/src/Extension/Webauthn.php
  plugins/system/webauthn/src/MetadataRepository.php
  plugins/system/webauthn/src/PluginTraits/AdditionalLoginButtons.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerChallenge.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerDelete.php
  plugins/system/webauthn/src/PluginTraits/AjaxHandlerSaveLabel.php
  plugins/system/webauthn/src/PluginTraits/UserDeletion.php
  plugins/task/checkfiles/src/Extension/Checkfiles.php
  plugins/task/deleteactionlogs/src/Extension/DeleteActionLogs.php
  plugins/task/globalcheckin/src/Extension/Globalcheckin.php
  plugins/task/privacyconsent/src/Extension/PrivacyConsent.php
  plugins/task/requests/src/Extension/Requests.php
  plugins/task/rotatelogs/src/Extension/RotateLogs.php
  plugins/task/sitestatus/src/Extension/SiteStatus.php
  plugins/task/updatenotification/src/Extension/UpdateNotification.php
  plugins/user/joomla/src/Extension/Joomla.php
  plugins/user/profile/src/Extension/Profile.php
  plugins/user/token/src/Extension/Token.php
  plugins/user/token/src/Field/JoomlatokenField.php
Labels: RTC, PR-5.3-dev

#44978 [5.2] Fix set frontediting option from CLI after installation
  installation/src/Model/ConfigurationModel.php
Labels: RTC, bug, PR-5.2-dev

#44952 [5.3] Fix MailsHelper::loadTranslationFiles bug
  administrator/components/com_mails/src/Helper/MailsHelper.php
Labels: RTC, PBF, PR-5.3-dev

#44366 [5.2] Add legacy message to content modules
  language/en-GB/mod_articles_category.ini
  language/en-GB/mod_articles_category.sys.ini
  language/en-GB/mod_articles_latest.ini
  language/en-GB/mod_articles_latest.sys.ini
  language/en-GB/mod_articles_news.ini
  language/en-GB/mod_articles_news.sys.ini
  language/en-GB/mod_articles_popular.ini
  language/en-GB/mod_articles_popular.sys.ini
Labels: Feature, RTC, Language Change, PBF, PR-5.3-dev

#44923 [5.3] Handle fields event in EmailCloak plugin
  plugins/content/emailcloak/src/Extension/EmailCloak.php
Labels: RTC, bug, PR-5.3-dev

#44903 [5.3] Category View: Fix meta tag for author
  components/com_content/src/View/Category/HtmlView.php
Labels: RTC, bug, PR-5.3-dev

#44896 [5.3] Make mailtemplate information available in mail template layout
  libraries/src/Mail/MailTemplate.php
Labels: Feature, RTC, PR-5.3-dev

#44881 [5.3] Remove unnecessary array internal pointer resets
  libraries/src/Form/Field/ChromestyleField.php
  libraries/src/Form/Field/GroupedlistField.php
  libraries/src/Form/Field/HeadertagField.php
  libraries/src/Form/Field/ListField.php
  libraries/src/Form/Field/ModuletagField.php
Labels: RTC, PR-5.3-dev

#44972 [5.3] Use null coalescing assignment operator for modules and plugins
  administrator/modules/mod_menu/src/Menu/CssMenu.php
  plugins/editors/tinymce/src/PluginTraits/XTDButtons.php
  plugins/system/debug/src/DataCollector/ProfileCollector.php
Labels: RTC, Code Review, PR-5.3-dev

#44956 [5.3] Fix field group permission check
  administrator/components/com_fields/src/Model/GroupModel.php
Labels: RTC, bug, PR-5.3-dev

#44943 [5.3] Fields batch copy category
  administrator/components/com_fields/src/Model/FieldModel.php
Labels: RTC, PBF, bug, PR-5.3-dev

#45031 [5.x][docu] Minor fix sudo
  tests/System/README.md
Labels: Unit/System Tests, PR-5.2-dev

#44976 [Cypress] PHP Backend Notice com_media/Files
  tests/System/data/com_media/test-image-1.jpg
  tests/System/data/com_media/test-image-1.png
  tests/System/data/com_media/test-image-2.png
  tests/System/fixtures/com_media/test-image-1.jpg
  tests/System/fixtures/com_media/test-image-2.jpg
  tests/System/fixtures/com_media/test-image-3.jpg
  tests/System/integration/api/com_media/Files.cy.js
Labels: RTC, Unit/System Tests, PR-5.3-dev

#42948 [5.3] Remove unsed variable messages from enqueue messages
  libraries/src/Application/CMSApplication.php
Labels: Feature, RTC, PR-5.3-dev

#44985 [5.3] Mail template outlook background
  layouts/joomla/mail/mailtemplate.php
Labels: RTC, PR-5.3-dev

#45021 [6.0] Remove the tab state script
  build/media_source/legacy/js/tabs-state.es5.js
Labels: NPM Resource Changed, b/c break, PR-6.0-dev

#44604 [5.3] fine grain task notification mail
  administrator/language/en-GB/plg_system_tasknotification.ini
  plugins/system/tasknotification/forms/task_notification.xml
  plugins/system/tasknotification/src/Extension/TaskNotification.php
Labels: RTC, Language Change, PBF, bug, PR-5.3-dev

#43430 [5.3] CMSPlugin: Deprecate use of DispatcherAware and LanguageAware
  libraries/src/Extension/PluginInterface.php
  libraries/src/Plugin/CMSPlugin.php
  plugins/content/finder/src/Extension/Finder.php
  plugins/editors/codemirror/src/Extension/Codemirror.php
  plugins/editors/none/src/Extension/None.php
  plugins/editors/tinymce/src/Extension/TinyMCE.php
  plugins/system/cache/src/Extension/Cache.php
  plugins/system/schemaorg/src/Extension/Schemaorg.php
  plugins/system/shortcut/src/Extension/Shortcut.php
Labels: RTC, PR-5.3-dev
