Repository joomla/joomla-cms, pull requests merged in 2025-03, with the labels that each got.

#45042 [5.3] Remove un-used imports
  administrator/components/com_guidedtours/tmpl/step/edit.php
  administrator/components/com_guidedtours/tmpl/tours/default.php
  administrator/components/com_mails/src/View/Template/HtmlView.php
  libraries/src/MVC/View/ListView.php
  plugins/system/cache/src/Extension/Cache.php
Labels: RTC, PR-5.3-dev

#45059 [5.2][cypress] clean user session
  tests/System/integration/site/components/com_users/Registration.cy.js
  tests/System/plugins/db.mjs
Labels: Unit/System Tests, PR-5.2-dev

#44660 [Cypress][docu] tests/System/README.md revised in 5 points
  tests/System/README.md
Labels: Unit/System Tests, PR-5.2-dev

#43777 [6.0] CategoryNode/Changelog: Remove legacy error handling trait
  libraries/src/Categories/CategoryNode.php
  libraries/src/Changelog/Changelog.php
Labels: Feature, b/c break, PR-6.0-dev

#44240 [6.0] Move CMS Filesystem package to compat plugin
  administrator/language/en-GB/plg_behaviour_compat.ini
  plugins/behaviour/compat/classes/Filesystem/File.php
  plugins/behaviour/compat/classes/Filesystem/FilesystemHelper.php
  plugins/behaviour/compat/classes/Filesystem/Folder.php
  plugins/behaviour/compat/classes/Filesystem/Meta/language/en-GB/en-GB.lib_joomla_filesystem_patcher.ini
  plugins/behaviour/compat/classes/Filesystem/Patcher.php
  plugins/behaviour/compat/classes/Filesystem/Path.php
  plugins/behaviour/compat/classes/Filesystem/Stream.php
  plugins/behaviour/compat/classes/Filesystem/Streams/StreamString.php
  plugins/behaviour/compat/classes/Filesystem/Support/StringController.php
  plugins/behaviour/compat/compat.xml
  plugins/behaviour/compat/src/Extension/Compat.php
  ruleset.xml
Labels: Feature, RTC, Language Change, PR-6.0-dev

#44912 [6.0] Add exceptions to deleted files check for files from PR #44321
  build/deleted_file_check.php
Labels: PR-6.0-dev

#45020 [6.0] Move jquery-noconflict script
  build/build-modules-js/settings.json
  build/media_source/legacy/joomla.asset.json
  build/media_source/legacy/js/jquery-noconflict.es5.js
  build/media_source/vendor/jquery/js/jquery-noconflict.es6.js
Labels: RTC, NPM Resource Changed, PR-6.0-dev, Enhancement

#45068 [5.4] Upmerge changes from 5.3-dev 2025-03-04
  .php-cs-fixer.dist.php
  administrator/components/com_actionlogs/src/Model/ActionlogModel.php
  administrator/components/com_admin/sql/updates/mysql/5.3.0-2025-02-22.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-02-22.sql
  administrator/components/com_banners/src/Controller/BannerController.php
  administrator/components/com_categories/src/Controller/CategoryController.php
  administrator/components/com_contact/src/Controller/ContactController.php
  administrator/components/com_content/src/Controller/ArticleController.php
  administrator/components/com_fields/src/Controller/FieldController.php
  administrator/components/com_fields/src/Controller/GroupController.php
  administrator/components/com_fields/src/Model/FieldModel.php
  administrator/components/com_finder/src/Indexer/Indexer.php
  administrator/components/com_finder/src/Indexer/Query.php
  administrator/components/com_guidedtours/tmpl/step/edit.php
  administrator/components/com_guidedtours/tmpl/tours/default.php
  administrator/components/com_joomlaupdate/src/Controller/DisplayController.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_mails/src/View/Template/HtmlView.php
  administrator/components/com_modules/src/Controller/ModuleController.php
  administrator/components/com_newsfeeds/src/Controller/NewsfeedController.php
  administrator/language/en-GB/plg_extension_joomlaupdate.ini
  administrator/language/en-GB/plg_extension_joomlaupdate.sys.ini
  administrator/language/en-GB/plg_system_tasknotification.ini
  components/com_contact/src/Controller/ContactController.php
  components/com_content/src/Controller/ArticleController.php
  installation/sql/mysql/base.sql
  installation/sql/postgresql/base.sql
  layouts/joomla/mail/mailtemplate.php
  libraries/src/Categories/Categories.php
  libraries/src/Console/CoreUpdateChannelCommand.php
  libraries/src/Extension/ExtensionHelper.php
  libraries/src/Extension/PluginInterface.php
  libraries/src/Form/Form.php
  libraries/src/Form/FormField.php
  libraries/src/MVC/Factory/MVCFactory.php
  libraries/src/MVC/Model/BaseDatabaseModel.php
  libraries/src/MVC/View/ListView.php
  libraries/src/Menu/SiteMenu.php
  libraries/src/Plugin/CMSPlugin.php
  libraries/src/Table/ContentType.php
  plugins/content/finder/src/Extension/Finder.php
  plugins/editors/codemirror/src/Extension/Codemirror.php
  plugins/editors/none/src/Extension/None.php
  plugins/editors/tinymce/src/Extension/TinyMCE.php
  plugins/extension/joomlaupdate/joomlaupdate.xml
  plugins/extension/joomlaupdate/services/provider.php
  plugins/extension/joomlaupdate/src/Extension/Joomlaupdate.php
  plugins/system/cache/src/Extension/Cache.php
  plugins/system/schemaorg/src/Extension/Schemaorg.php
  plugins/system/shortcut/src/Extension/Shortcut.php
  plugins/system/tasknotification/forms/task_notification.xml
  plugins/system/tasknotification/src/Extension/TaskNotification.php
Labels: Language Change, PR-5.4-dev

#45055 [5.3][cypress] add param default for edit field
  tests/System/support/commands/db.mjs
Labels: Unit/System Tests, PR-5.3-dev

#45043 [5.3][webservices] Undefined property: stdClass::$modified_by
  administrator/components/com_contact/src/Model/ContactsModel.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedsModel.php
  api/components/com_newsfeeds/src/View/Feeds/JsonapiView.php
Labels: RTC, Webservices, PR-5.3-dev

#45008 [5.3][ cypress] null coalescing operator
  components/com_users/src/Model/ResetModel.php
Labels: RTC, PR-5.3-dev

#45058 [5.3] Fix wording (#44954)
  administrator/language/en-GB/plg_extension_joomlaupdate.ini
  administrator/language/en-GB/plg_extension_joomlaupdate.sys.ini
Labels: RTC, Language Change, PR-5.3-dev

#44718 [5.3][cypress] do not ignore all uncaught:exception
  tests/System/integration/administrator/components/com_media/Media.cy.js
  tests/System/support/index.js
Labels: Unit/System Tests, PR-5.3-dev

#45051 [5.3][cypress] install extension From Url
  tests/System/integration/administrator/components/com_installer/FromUrl.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45089 [53][Cypress] Don't Force SSL
  tests/System/integration/install/Installation.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45092 [5.3][cypress] PHP Warning: Undefined array key "menuordering" on patch com_menus
  tests/System/integration/api/com_menus/AdministratorMenuItems.cy.js
  tests/System/integration/api/com_menus/SiteMenuItems.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45078 [5.3] Template Description
  administrator/language/en-GB/tpl_atum.ini
  administrator/language/en-GB/tpl_atum.sys.ini
  language/en-GB/tpl_cassiopeia.ini
  language/en-GB/tpl_cassiopeia.sys.ini
Labels: RTC, Language Change, PR-5.3-dev

#45080 [5.3] Arrange task types alphabetically
  administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
  administrator/components/com_scheduler/src/Task/TaskOption.php
Labels: RTC, PR-5.3-dev

#45045 [5.3] Remove un-used variables
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_messages/src/View/Messages/HtmlView.php
  administrator/components/com_scheduler/src/View/Logs/HtmlView.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_users/src/Controller/CallbackController.php
Labels: RTC, PR-5.3-dev

#45077 [5.3] Clean up com_templates StyleModel
  administrator/components/com_templates/src/Model/StyleModel.php
Labels: RTC, PR-5.3-dev

#45053 [5.3] Fix warnings on frontend template options editing
  administrator/components/com_templates/src/View/Style/JsonView.php
Labels: RTC, PR-5.3-dev

#45027 [5.3] Remove redundant entry in the npm tools
  build/build-modules-js/init/minify-vendor.mjs
Labels: RTC, bug, PR-5.3-dev

#45033 [5.3] Do not use the deprecated get functions in Joomla action log plugin
  plugins/actionlog/joomla/src/Extension/Joomla.php
Labels: RTC, PR-5.3-dev

#45030 [5.3][cypress] php warning
  administrator/components/com_users/src/Model/UserModel.php
Labels: RTC, PR-5.3-dev

#45093 [5.3][cypress] PHP Warning Undefined array key "parent_id" on POST com_content
  tests/System/integration/api/com_content/Categories.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#44847 [6.0] Media: allow thumbnail for any file type
  administrator/components/com_media/resources/scripts/components/browser/items/audio.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/document.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  build/media_source/com_media/scss/components/_media-browser.scss
Labels: Feature, NPM Resource Changed, PR-6.0-dev

#45097 [6.0] Replace dialog GIF loader with SVG loader
  build/media_source/system/images/joomla-loader.svg
  build/media_source/templates/administrator/atum/scss/blocks/_modals.scss
  build/media_source/templates/site/cassiopeia/scss/blocks/_modals.scss
Labels: Feature, RTC, NPM Resource Changed, PR-6.0-dev

#45108 [5.3] Upmerge 2025-03-11
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
Labels: PR-5.3-dev

#45110 [5.4] upmerge 2025-03-11
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_contact/src/Model/ContactsModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_media/src/View/Media/HtmlView.php
  administrator/components/com_messages/src/View/Messages/HtmlView.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedsModel.php
  administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
  administrator/components/com_scheduler/src/Task/TaskOption.php
  administrator/components/com_scheduler/src/View/Logs/HtmlView.php
  administrator/components/com_templates/src/Model/StyleModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/src/View/Style/JsonView.php
  administrator/components/com_users/src/Controller/CallbackController.php
  administrator/components/com_users/src/Model/UserModel.php
  administrator/language/en-GB/plg_extension_joomlaupdate.ini
  administrator/language/en-GB/plg_extension_joomlaupdate.sys.ini
  administrator/language/en-GB/tpl_atum.ini
  administrator/language/en-GB/tpl_atum.sys.ini
  api/components/com_newsfeeds/src/View/Feeds/JsonapiView.php
  build/build-modules-js/init/minify-vendor.mjs
  components/com_contact/src/Controller/DisplayController.php
  components/com_content/src/Controller/DisplayController.php
  components/com_contenthistory/src/Controller/DisplayController.php
  components/com_contenthistory/src/Dispatcher/Dispatcher.php
  components/com_fields/src/Controller/DisplayController.php
  components/com_menus/src/Dispatcher/Dispatcher.php
  components/com_modules/src/Controller/DisplayController.php
  components/com_modules/src/Dispatcher/Dispatcher.php
  components/com_users/src/Model/ResetModel.php
  language/en-GB/tpl_cassiopeia.ini
  language/en-GB/tpl_cassiopeia.sys.ini
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
  tests/System/README.md
  tests/System/integration/administrator/components/com_installer/FromUrl.cy.js
  tests/System/integration/administrator/components/com_media/Media.cy.js
  tests/System/integration/api/com_banners/Categories.cy.js
  tests/System/integration/api/com_content/Categories.cy.js
  tests/System/integration/api/com_menus/AdministratorMenuItems.cy.js
  tests/System/integration/api/com_menus/SiteMenuItems.cy.js
  tests/System/integration/install/Installation.cy.js
  tests/System/integration/plugins/system/shortcut/ShortcutPlugin.cy.js
  tests/System/integration/site/components/com_users/Registration.cy.js
  tests/System/plugins/db.mjs
  tests/System/support/commands/db.mjs
  tests/System/support/index.js
Labels: Language Change, PR-5.4-dev

#44792 [5.3] display email address in contact
  language/en-GB/com_contact.ini
  tests/System/integration/api/com_contact/Contacts.cy.js
Labels: RTC, Unit/System Tests, Language Change, PR-5.3-dev

#45124 [6.0] Upmerges - 2025-03-12_2
  administrator/components/com_config/src/Model/ApplicationModel.php
  administrator/components/com_contact/src/Model/ContactsModel.php
  administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
  administrator/components/com_media/src/View/Media/HtmlView.php
  administrator/components/com_messages/src/View/Messages/HtmlView.php
  administrator/components/com_newsfeeds/src/Model/NewsfeedsModel.php
  administrator/components/com_scheduler/src/Helper/SchedulerHelper.php
  administrator/components/com_scheduler/src/Task/TaskOption.php
  administrator/components/com_scheduler/src/View/Logs/HtmlView.php
  administrator/components/com_templates/src/Model/StyleModel.php
  administrator/components/com_templates/src/Model/TemplateModel.php
  administrator/components/com_templates/src/View/Style/JsonView.php
  administrator/components/com_users/src/Controller/CallbackController.php
  administrator/components/com_users/src/Model/UserModel.php
  administrator/language/en-GB/plg_extension_joomlaupdate.ini
  administrator/language/en-GB/plg_extension_joomlaupdate.sys.ini
  administrator/language/en-GB/tpl_atum.ini
  administrator/language/en-GB/tpl_atum.sys.ini
  api/components/com_newsfeeds/src/View/Feeds/JsonapiView.php
  build/build-modules-js/init/minify-vendor.mjs
  components/com_contact/src/Controller/DisplayController.php
  components/com_content/src/Controller/DisplayController.php
  components/com_contenthistory/src/Controller/DisplayController.php
  components/com_contenthistory/src/Dispatcher/Dispatcher.php
  components/com_fields/src/Controller/DisplayController.php
  components/com_menus/src/Dispatcher/Dispatcher.php
  components/com_modules/src/Controller/DisplayController.php
  components/com_modules/src/Dispatcher/Dispatcher.php
  components/com_users/src/Model/ResetModel.php
  language/en-GB/tpl_cassiopeia.ini
  language/en-GB/tpl_cassiopeia.sys.ini
  plugins/actionlog/joomla/src/Extension/Joomla.php
  plugins/filesystem/local/src/Adapter/LocalAdapter.php
  tests/System/README.md
  tests/System/integration/administrator/components/com_installer/FromUrl.cy.js
  tests/System/integration/administrator/components/com_media/Media.cy.js
  tests/System/integration/api/com_banners/Categories.cy.js
  tests/System/integration/api/com_content/Categories.cy.js
  tests/System/integration/api/com_menus/AdministratorMenuItems.cy.js
  tests/System/integration/api/com_menus/SiteMenuItems.cy.js
  tests/System/integration/install/Installation.cy.js
  tests/System/integration/plugins/system/shortcut/ShortcutPlugin.cy.js
  tests/System/integration/site/components/com_users/Registration.cy.js
  tests/System/plugins/db.mjs
  tests/System/support/commands/db.mjs
  tests/System/support/index.js
Labels: Test instructions missing, Language Change, PR-6.0-dev

#45125 [5.3] PHP 8.4 compatibility
  .drone.yml
  composer.lock
  libraries/src/Changelog/Changelog.php
  libraries/src/Updater/Adapter/CollectionAdapter.php
  libraries/src/Updater/Adapter/ExtensionAdapter.php
  libraries/src/Updater/Update.php
Labels: Unit/System Tests, Composer Dependency Changed, PR-5.3-dev

#45104 [5.3][cypress]PHP Warning Undefined array key "parent_id" on POST com_contacts
  tests/System/integration/api/com_contact/Categories.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45127 [5.3][cypress] smart search index & purge
  tests/System/integration/administrator/components/com_finder/Index.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45091 [5.3][cypress] avoid deprecated in api tags
  administrator/components/com_tags/src/Model/TagsModel.php
Labels: RTC, PR-5.3-dev

#45117 [5.3] [a11y] Dark Mode log in message
  build/media_source/templates/administrator/atum/scss/blocks/_login.scss
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#45115 [5.3] System test in media manager to prevent a rename
  tests/System/integration/administrator/components/com_media/Media.cy.js
Labels: RTC, Unit/System Tests, PR-5.3-dev

#45109 [5.3]allowTourAutoStart in user profile
  components/com_users/forms/frontend.xml
  components/com_users/forms/frontend_admin.xml
Labels: RTC, PR-5.3-dev

#44871 [5.3] Guided Tours: What's New
  administrator/components/com_admin/sql/updates/mysql/5.3.0-2025-03-14.sql
  administrator/components/com_admin/sql/updates/postgresql/5.3.0-2025-03-14.sql
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_3.ini
  administrator/language/en-GB/guidedtours.joomla_whatsnew_5_3_steps.ini
  build/media_source/com_guidedtours/images/5_3/filesdirectory.jpg
Labels: RTC, Language Change, NPM Resource Changed, PR-5.3-dev

#45103 [5.3] Catch undefined cors options when saving global options
  administrator/components/com_config/src/Model/ApplicationModel.php
Labels: RTC, PR-5.3-dev

#45003 [5.3][cypress] user login test - report-only-existing-users
  administrator/modules/mod_logged/src/Helper/LoggedHelper.php
Labels: RTC, PR-5.3-dev

#45130 [5.3] Upmerge 2025-03-14
  installation/language/af-ZA/langmetadata.xml
  installation/language/ar-AA/langmetadata.xml
  installation/language/be-BY/langmetadata.xml
  installation/language/bg-BG/langmetadata.xml
  installation/language/ca-ES/langmetadata.xml
  installation/language/cs-CZ/langmetadata.xml
  installation/language/cy-GB/langmetadata.xml
  installation/language/da-DK/langmetadata.xml
  installation/language/el-GR/langmetadata.xml
  installation/language/en-AU/joomla.ini
  installation/language/en-AU/langmetadata.xml
  installation/language/en-CA/joomla.ini
  installation/language/en-CA/langmetadata.xml
  installation/language/en-NZ/joomla.ini
  installation/language/en-NZ/langmetadata.xml
  installation/language/en-US/joomla.ini
  installation/language/en-US/langmetadata.xml
  installation/language/es-ES/langmetadata.xml
  installation/language/et-EE/langmetadata.xml
  installation/language/eu-ES/langmetadata.xml
  installation/language/fa-AF/langmetadata.xml
  installation/language/fa-IR/langmetadata.xml
  installation/language/fi-FI/langmetadata.xml
  installation/language/fr-CA/joomla.ini
  installation/language/fr-CA/langmetadata.xml
  installation/language/fr-FR/langmetadata.xml
  installation/language/he-IL/langmetadata.xml
  installation/language/hr-HR/langmetadata.xml
  installation/language/hu-HU/langmetadata.xml
  installation/language/id-ID/langmetadata.xml
  installation/language/it-IT/langmetadata.xml
  installation/language/ja-JP/langmetadata.xml
  installation/language/ka-GE/langmetadata.xml
  installation/language/kk-KZ/langmetadata.xml
  installation/language/ko-KR/langmetadata.xml
  installation/language/lt-LT/langmetadata.xml
  installation/language/lv-LV/langmetadata.xml
  installation/language/mk-MK/langmetadata.xml
  installation/language/nl-BE/langmetadata.xml
  installation/language/nl-NL/langmetadata.xml
  installation/language/pl-PL/langmetadata.xml
  installation/language/pt-BR/langmetadata.xml
  installation/language/pt-PT/langmetadata.xml
  installation/language/ro-RO/langmetadata.xml
  installation/language/sk-SK/langmetadata.xml
  installation/language/sl-SI/langmetadata.xml
  installation/language/sr-YU/langmetadata.xml
  installation/language/sv-SE/langmetadata.xml
  installation/language/ta-IN/langmetadata.xml
  installation/language/th-TH/langmetadata.xml
  installation/language/tr-TR/langmetadata.xml
  installation/language/uk-UA/langmetadata.xml
  installation/language/ur-PK/langmetadata.xml
  installation/language/vi-VN/langmetadata.xml
  installation/language/zh-CN/langmetadata.xml
  installation/language/zh-TW/langmetadata.xml
Labels: Language Change, PR-5.3-dev

#45064 [5.3] Add missing help link for Articles-Module
  administrator/help/en-GB/toc.json
  administrator/language/en-GB/com_admin.ini
Labels: RTC, Language Change, PR-5.3-dev

#45102 [5.3] Allow email addresses with an underscore
  plugins/content/emailcloak/src/Extension/EmailCloak.php
Labels: RTC, bug, PR-5.3-dev

#45017 [5.4] Cleanup short and sweet script
  build/build-modules-js/init/minify-vendor.mjs
  build/build-modules-js/init/patches.mjs
  build/build-modules-js/settings.json
  build/media_source/vendor/short-and-sweet/js/short-and-sweet.es6.js
Labels: RTC, NPM Resource Changed, Enhancement, PR-5.4-dev

#45131 [5.3][cypress]PHP Warning Undefined array key "parent_id" on POST com_newsfeeds
  tests/System/integration/api/com_newsfeed/Categories.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45133 [5.3][cypress] api test wrong route
  tests/System/integration/api/Basic.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45071 [5.3] Update dependencies
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: RTC, Composer Dependency Changed, NPM Resource Changed, PR-5.3-dev

#44945 [6.0] Change the media manager from CMSObject to stdClass
  administrator/components/com_media/src/Model/ApiModel.php
Labels: RTC, b/c break, PR-6.0-dev

#45158 [5.4] upmerge 2025-03-18
  administrator/components/com_scheduler/src/Task/TaskOption.php
Labels: PR-5.4-dev

#45152 [5.3] Remove non-distributed files
  build/build.php
Labels: RTC, PR-5.3-dev

#44733 [5.3] system test for multi-factor authentication plugins (totp & email)
  package-lock.json
  package.json
  tests/System/integration/administrator/components/com_users/Mfa.cy.js
  tests/System/integration/site/components/com_users/Mfa.cy.js
Labels: Unit/System Tests, NPM Resource Changed, PR-5.3-dev

#45140 [5.3] Major update idna converter
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-5.3-dev

#45138 [5.3] Major update dev dependencies
  build/build-modules-js/javascript/build-bootstrap-js.mjs
  package-lock.json
  package.json
Labels: NPM Resource Changed, PR-5.3-dev

#45148 [5.3] Update http package to version 3.1.0 to fix some deprecation notices
  composer.json
  composer.lock
Labels: RTC, Composer Dependency Changed, PR-5.3-dev

#45038 [6.0] Update deleted files and folders in script.php 2025-02-28
  administrator/components/com_admin/script.php
Labels: PR-6.0-dev

#45166 Update TUF client to fix PHP 8.4 compat issues
  composer.json
  composer.lock
Labels: Composer Dependency Changed, PR-5.3-dev

#45174 Fix install from web
  build/media_source/plg_installer_webinstaller/js/client.es6.js
Labels: NPM Resource Changed, PR-5.2-dev, PR-5.3-dev

#45139 [5.3] Don't use the deprecated CMS Filesystem but the framework package in package installer
  plugins/installer/packageinstaller/tmpl/default.php
Labels: RTC, PR-5.3-dev

#45169 [5.3] php 8.4 compatibility
  administrator/components/com_users/src/Model/CaptiveModel.php
Labels: RTC, PR-5.3-dev

#45129 [5.3] add CORS settings when install from CLI
  installation/src/Model/ConfigurationModel.php
Labels: RTC, PR-5.3-dev

#45180 [5.3] Composer update tobscure/json-api
  composer.lock
Labels: Composer Dependency Changed, PR-5.3-dev

#45188 [5.3] Fix Light Mode Visibility for Table Headers in User Profile
  build/media_source/templates/administrator/atum/scss/pages/_com_users.scss
Labels: RTC, NPM Resource Changed, PR-5.3-dev

#45195 [6.0] Remove deprecated strings
  administrator/language/en-GB/com_menus.ini
  administrator/language/en-GB/mod_stats_admin.sys.ini
  administrator/language/en-GB/plg_content_loadmodule.ini
Labels: RTC, Language Change, PR-6.0-dev

#45142 [6.0] Fixes the missing modified start and end date filter to articled API endpoint
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_users/src/Model/BackupcodesModel.php
  api/components/com_content/src/Controller/ArticlesController.php
  build/build-modules-js/javascript/build-bootstrap-js.mjs
  build/build.php
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  composer.json
  composer.lock
  package-lock.json
  package.json
  plugins/installer/packageinstaller/tmpl/default.php
  tests/System/integration/administrator/components/com_users/Mfa.cy.js
  tests/System/integration/api/com_content/Articles.cy.js
  tests/System/integration/site/components/com_users/Mfa.cy.js
Labels: Feature, RTC, Unit/System Tests, Composer Dependency Changed, NPM Resource Changed, Webservices, PR-6.0-dev

#45209 Revert "[6.0] Fixes the missing modified start and end date filter to…
  administrator/components/com_content/src/Model/ArticlesModel.php
  administrator/components/com_users/src/Model/BackupcodesModel.php
  api/components/com_content/src/Controller/ArticlesController.php
  build/build-modules-js/javascript/build-bootstrap-js.mjs
  build/build.php
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  composer.json
  composer.lock
  package-lock.json
  package.json
  plugins/installer/packageinstaller/tmpl/default.php
  tests/System/integration/administrator/components/com_users/Mfa.cy.js
  tests/System/integration/api/com_content/Articles.cy.js
  tests/System/integration/site/components/com_users/Mfa.cy.js
Labels: Unit/System Tests, Composer Dependency Changed, NPM Resource Changed, PR-6.0-dev

#45208 [5.3][cypress] add tests for issue 45190
  administrator/components/com_templates/src/View/Templates/HtmlView.php
  tests/System/integration/administrator/components/com_templates/Styles.cy.js
  tests/System/integration/administrator/components/com_templates/Templates.cy.js
  tests/System/integration/site/components/com_config/Config.cy.js
  tests/System/integration/site/components/com_config/Modules.cy.js
  tests/System/integration/site/components/com_config/Templates.cy.js
Labels: Unit/System Tests, PR-5.3-dev

#45219 [5.4] upmerge 2025-03-25
  administrator/components/com_templates/src/View/Templates/HtmlView.php
  administrator/components/com_users/src/Model/BackupcodesModel.php
  administrator/components/com_users/src/Model/CaptiveModel.php
  build/build-modules-js/javascript/build-bootstrap-js.mjs
  build/build.php
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  build/media_source/templates/administrator/atum/scss/pages/_com_users.scss
  composer.json
  composer.lock
  installation/src/Model/ConfigurationModel.php
  libraries/src/MVC/View/JsonApiView.php
  package-lock.json
  package.json
  plugins/installer/packageinstaller/tmpl/default.php
  tests/System/integration/administrator/components/com_templates/Styles.cy.js
  tests/System/integration/administrator/components/com_templates/Templates.cy.js
  tests/System/integration/administrator/components/com_users/Mfa.cy.js
  tests/System/integration/site/components/com_config/Config.cy.js
  tests/System/integration/site/components/com_config/Modules.cy.js
  tests/System/integration/site/components/com_config/Templates.cy.js
  tests/System/integration/site/components/com_users/Mfa.cy.js
Labels: Unit/System Tests, Composer Dependency Changed, NPM Resource Changed, PR-5.4-dev

#45220 [5.3] Update deleted files in script.php for the upcoming 5.3.0-rc1
  administrator/components/com_admin/script.php
Labels: PR-5.3-dev

#45207 Update the joomla cypress package
  package-lock.json
Labels: NPM Resource Changed, PR-5.3-dev

#45179 [5.3] Author column
  administrator/components/com_content/tmpl/articles/default.php
Labels: RTC, PR-5.3-dev

#45198 [6.0] Fix fatal error on templates management
  administrator/components/com_templates/tmpl/template/default_description.php
  administrator/components/com_templates/tmpl/templates/default.php
Labels: RTC, PR-6.0-dev

#45197 [6.0] Fix frontend module editing
  administrator/components/com_modules/src/Controller/ModuleController.php
  components/com_config/src/View/Modules/HtmlView.php
Labels: RTC, PR-6.0-dev

#45199 [6.0] Fix frontend save template options error
  administrator/components/com_templates/src/Controller/StyleController.php
Labels: RTC, PR-6.0-dev

#45215 [6.0] Update Site ID fatal error
  administrator/components/com_installer/src/View/Updatesite/HtmlView.php
Labels: RTC, PR-6.0-dev

#45213 [6.0] Fix fatal error private message
  administrator/components/com_messages/src/Model/MessageModel.php
  administrator/components/com_messages/tmpl/message/default.php
Labels: RTC, PR-6.0-dev

#45222 [6.0] Upmerges - 2025-03-26
  administrator/components/com_templates/src/View/Templates/HtmlView.php
  administrator/components/com_users/src/Model/BackupcodesModel.php
  administrator/components/com_users/src/Model/CaptiveModel.php
  build/build-modules-js/javascript/build-bootstrap-js.mjs
  build/build.php
  build/media_source/plg_installer_webinstaller/js/client.es6.js
  build/media_source/templates/administrator/atum/scss/pages/_com_users.scss
  composer.json
  composer.lock
  installation/src/Model/ConfigurationModel.php
  libraries/src/MVC/View/JsonApiView.php
  package-lock.json
  package.json
  plugins/installer/packageinstaller/tmpl/default.php
  tests/System/integration/administrator/components/com_templates/Styles.cy.js
  tests/System/integration/administrator/components/com_templates/Templates.cy.js
  tests/System/integration/administrator/components/com_users/Mfa.cy.js
  tests/System/integration/site/components/com_config/Config.cy.js
  tests/System/integration/site/components/com_config/Modules.cy.js
  tests/System/integration/site/components/com_config/Templates.cy.js
  tests/System/integration/site/components/com_users/Mfa.cy.js
Labels: Unit/System Tests, Test instructions missing, Composer Dependency Changed, NPM Resource Changed, PR-6.0-dev

#45228 [5.4] Upmerge changes from 5.3-dev 2025-03-26
  administrator/components/com_admin/script.php
  administrator/components/com_content/tmpl/articles/default.php
  package-lock.json
Labels: NPM Resource Changed, PR-5.4-dev

#45177 [5.2] change minor version to 5.3
  .github/workflows/create-translation-pull-request-v5.yml
Labels: PR-5.2-dev

#45165 [5.4] Replace table _db with DatabaseAwareTrait
  libraries/src/Table/Table.php
Labels: Feature, RTC, PR-5.4-dev

#45240 [5.3] Upmerge 2025-03-28
  includes/incompatible.html
  installation/language/ar-AA/joomla.ini
  installation/language/nl-BE/joomla.ini
  installation/language/nl-BE/langmetadata.xml
  templates/system/build_incomplete.html
  templates/system/fatal-error.html
  templates/system/incompatible.html
Labels: Language Change, PR-5.3-dev

#45241 [5.3] cypress test grammar
  tests/System/integration/administrator/components/com_contenthistory/Content.cy.js
Labels: RTC, NPM Resource Changed, PR-5.3-dev
